# Fine-tune (LoRA)

Fine-tunes **Qwen2-1.5B** on GSM8K using LoRA. Artifacts go to `output/fine_tune/` (gitignored).

| Output | Contents |
|--------|---------|
| Cell output | tqdm bar + `[train] step=… loss=… lr=… epoch=…` per log event |
| `training_run.log` | Timestamped log, appended each run |
| `trainer_log_history.json` | Per-step `loss`, `learning_rate`, `epoch` from HF Trainer |
| `training_summary.json` | Hyperparameters + final loss / step / epoch |
| `adapter_*/`, checkpoints | Saved by HF Trainer under the run folder |

**Single run:** `RUN_HYPERPARAMETER_SWEEP = False` — uses defaults from `hyperparameters.py`.  
**Sweep:** `True` — one run per entry in `PARAM_COMBINATIONS`, each in its own subfolder (`run_000_…`).

Run cells top to bottom.

### 1 — Imports and callback

Imports the stack and defines `NotebookProgressCallback` (prints `[train]` lines per log event). Run once per session.

In [5]:
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import torch
import transformers
from transformers import TrainerCallback

from qwen_math_flow.download_model import download_qwen_2_15b
from qwen_math_flow.load_dataset import format_gsm8k_as_deterministic_json_chat, load_and_tokenize_math
from qwen_math_flow.lora_finetune import create_lora_model, run_finetune


class NotebookProgressCallback(TrainerCallback):
    """Print one line per Trainer log so loss / lr / epoch show in the notebook while training."""

    def on_train_begin(self, args, state, control, **kwargs):
        print(
            "[train] started | "
            f"epochs={args.num_train_epochs} | log every {args.logging_steps} step(s) | "
            "progress bar + metrics lines below",
            flush=True,
        )

    def on_log(self, args, state, control, logs=None, **kwargs):
        if not logs:
            return
        parts = [f"step={state.global_step}"]
        if logs.get("loss") is not None:
            parts.append(f"loss={logs['loss']:.4f}")
        if logs.get("learning_rate") is not None:
            parts.append(f"lr={logs['learning_rate']:.2e}")
        if logs.get("epoch") is not None:
            parts.append(f"epoch={logs['epoch']:.4f}")
        print("[train] " + " | ".join(parts), flush=True)

    def on_train_end(self, args, state, control, **kwargs):
        print(f"[train] finished | global_step={state.global_step}", flush=True)

### 2 — Config

Set the output path, sweep toggle, and logging verbosity. Training defaults (LR, LoRA rank, batch size, etc.) come from `hyperparameters.py`; entries in `PARAM_COMBINATIONS` override only the keys they list.

Re-run this cell whenever you change sweep settings.

In [6]:
from qwen_math_flow.hyperparameters import (
    DATASET_NAME,
    DATASET_SPLIT,
    GRADIENT_ACCUMULATION_STEPS,
    LEARNING_RATE,
    LOAD_IN_4BIT,
    LORA_ALPHA,
    LORA_R,
    MAX_LENGTH,
    MAX_TRAIN_SAMPLES,
    MODEL_CACHE_DIR,
    NUM_EPOCHS,
    PER_DEVICE_TRAIN_BATCH_SIZE,
)

OUTPUT_BASE = "output/fine_tune"

# False: one run using hyperparameters.py only. True: one run per dict in PARAM_COMBINATIONS.
RUN_HYPERPARAMETER_SWEEP = True

# Sweeps: each dict can override training keys; missing keys use hyperparameters.py defaults.
# Pragmatic 5-run subset from the original 18-combination grid.
PARAM_COMBINATIONS = [
    {
        "learning_rate": 1e-5,
        "lora_r": 8,
        "lora_alpha": 16,
        "num_epochs": 3,
        "max_train_samples": None,
    },
    {
        "learning_rate": 3e-5,
        "lora_r": 16,
        "lora_alpha": 32,
        "num_epochs": 3,
        "max_train_samples": None,
    },
    {
        "learning_rate": 5e-5,
        "lora_r": 32,
        "lora_alpha": 64,
        "num_epochs": 3,
        "max_train_samples": None,
    },
    {
        "learning_rate": 7e-5,
        "lora_r": 16,
        "lora_alpha": 32,
        "num_epochs": 3,
        "max_train_samples": None,
    },
    {
        "learning_rate": 1e-4,
        "lora_r": 32,
        "lora_alpha": 64,
        "num_epochs": 3,
        "max_train_samples": None,
    },
]
# Current size: 5 combinations.


def merged_training_params(overrides: dict) -> dict:
    """Defaults from hyperparameters.py, overridden by one sweep row."""
    return {
        "learning_rate": overrides.get("learning_rate", LEARNING_RATE),
        "lora_r": overrides.get("lora_r", LORA_R),
        "lora_alpha": overrides.get("lora_alpha", LORA_ALPHA),
        "num_epochs": overrides.get("num_epochs", 3),
        "per_device_train_batch_size": overrides.get(
            "per_device_train_batch_size", PER_DEVICE_TRAIN_BATCH_SIZE
        ),
        "gradient_accumulation_steps": overrides.get(
            "gradient_accumulation_steps", GRADIENT_ACCUMULATION_STEPS
        ),
        "max_length": overrides.get("max_length", MAX_LENGTH),
        "max_train_samples": overrides.get("max_train_samples", MAX_TRAIN_SAMPLES),
    }


def combination_subdir(index: int, m: dict) -> str:
    """Unique folder name for one combination."""
    lr = m["learning_rate"]
    lr_s = f"{lr:.0e}".replace("e-0", "e-").replace("e+0", "e+")
    return f"run_{index:03d}_lr{lr_s}_r{m['lora_r']}_a{m['lora_alpha']}_ep{m['num_epochs']}"


SWEEP_RUNS = PARAM_COMBINATIONS if RUN_HYPERPARAMETER_SWEEP else [{}]
NUM_COMBINATIONS = len(SWEEP_RUNS)

# Resume mode: skip run folders that already contain completed summaries.
RESUME_INCOMPLETE_ONLY = True

# Trainer: log loss / lr every N steps (1 = every step — most verbose)
LOGGING_STEPS = 1
SHOW_NOTEBOOK_LOG_LINES = True
DISABLE_TQDM = False
TRANSFORMERS_DEBUG = False

Path(OUTPUT_BASE).mkdir(parents=True, exist_ok=True)
print(f"Output base: {Path(OUTPUT_BASE).resolve()}")
print(f"RUN_HYPERPARAMETER_SWEEP={RUN_HYPERPARAMETER_SWEEP}  →  {NUM_COMBINATIONS} training run(s)")
if RUN_HYPERPARAMETER_SWEEP:
    for i, o in enumerate(PARAM_COMBINATIONS):
        print(f"  [{i}] {o}  →  {combination_subdir(i, merged_training_params(o))}")
print(f"RESUME_INCOMPLETE_ONLY={RESUME_INCOMPLETE_ONLY}")
print(
    f"LOGGING_STEPS={LOGGING_STEPS}  SHOW_NOTEBOOK_LOG_LINES={SHOW_NOTEBOOK_LOG_LINES}  "
    f"DISABLE_TQDM={DISABLE_TQDM}  TRANSFORMERS_DEBUG={TRANSFORMERS_DEBUG}"
)

Output base: C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune
RUN_HYPERPARAMETER_SWEEP=True  →  5 training run(s)
  [0] {'learning_rate': 1e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 3, 'max_train_samples': None}  →  run_000_lr1e-5_r8_a16_ep3
  [1] {'learning_rate': 3e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'max_train_samples': None}  →  run_001_lr3e-5_r16_a32_ep3
  [2] {'learning_rate': 5e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'max_train_samples': None}  →  run_002_lr5e-5_r32_a64_ep3
  [3] {'learning_rate': 7e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'max_train_samples': None}  →  run_003_lr7e-5_r16_a32_ep3
  [4] {'learning_rate': 0.0001, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'max_train_samples': None}  →  run_004_lr1e-4_r32_a64_ep3
RESUME_INCOMPLETE_ONLY=True
LOGGING_STEPS=1  SHOW_NOTEBOOK_LOG_LINES=True  DISABLE_TQDM=False  TRANSFORMERS_DEBUG=False

### 3 — Train

Loads the model and data, runs `run_finetune` for each combination, and writes `training_summary.json`, `trainer_log_history.json`, and `training_run.log` per run. In sweep mode, also writes `sweep_index.json` at the top level. If `RESUME_INCOMPLETE_ONLY=True`, completed run folders are skipped automatically.

Re-run config first if hyperparameters changed.

In [8]:
def _setup_run_logging(log_path: Path) -> None:
    logging.basicConfig(
        level=logging.DEBUG if TRANSFORMERS_DEBUG else logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(log_path, encoding="utf-8", mode="a"),
        ],
        force=True,
    )
    for name in ("transformers", "transformers.trainer", "qwen_math_flow.lora_finetune"):
        logging.getLogger(name).setLevel(logging.DEBUG if TRANSFORMERS_DEBUG else logging.INFO)
    logging.getLogger("datasets").setLevel(logging.WARNING)
    if TRANSFORMERS_DEBUG:
        transformers.logging.set_verbosity_debug()
    else:
        transformers.logging.set_verbosity_info()


all_summaries = []
skipped_runs = 0


def _is_completed_run(out_dir: Path) -> bool:
    summary_path = out_dir / "training_summary.json"
    hist_path = out_dir / "trainer_log_history.json"
    if not summary_path.exists() or not hist_path.exists():
        return False
    try:
        with open(summary_path, "r", encoding="utf-8") as f:
            s = json.load(f)
        with open(hist_path, "r", encoding="utf-8") as f:
            h = json.load(f)
    except Exception:
        return False
    if not isinstance(h, list) or len(h) == 0:
        return False
    last = h[-1] if isinstance(h[-1], dict) else {}
    # Completion marker from Trainer's final summary record.
    return "train_loss" in last and s.get("global_step") is not None


for run_index, overrides in enumerate(SWEEP_RUNS):
    merged = merged_training_params(overrides)
    out = (
        Path(OUTPUT_BASE) / combination_subdir(run_index, merged)
        if RUN_HYPERPARAMETER_SWEEP
        else Path(OUTPUT_BASE)
    )
    out.mkdir(parents=True, exist_ok=True)

    if RESUME_INCOMPLETE_ONLY and _is_completed_run(out):
        print(f"[skip] run {run_index + 1}/{NUM_COMBINATIONS} already completed: {out}", flush=True)
        skipped_runs += 1
        continue

    log_file = out / "training_run.log"

    print(
        f"\n=== Run {run_index + 1}/{NUM_COMBINATIONS}  {out.name}  merged={merged} ===\n",
        flush=True,
    )
    _setup_run_logging(log_file)
    logging.info("Logging to %s", log_file.resolve())

    model, tokenizer = download_qwen_2_15b(
        cache_dir=MODEL_CACHE_DIR,
        load_in_4bit=LOAD_IN_4BIT,
        device_map="auto" if LOAD_IN_4BIT else None,
    )
    tokenized_train = load_and_tokenize_math(
        tokenizer,
        name=DATASET_NAME,
        split=DATASET_SPLIT,
        max_samples=merged["max_train_samples"],
        max_length=merged["max_length"],
        message_formatter=format_gsm8k_as_deterministic_json_chat,
    )
    cap_msg = (
        "full train split"
        if merged["max_train_samples"] is None
        else f"up to {merged['max_train_samples']} samples"
    )
    logging.info(
        "GSM8K training: %s samples (%s), %s epoch(s).",
        len(tokenized_train),
        cap_msg,
        merged["num_epochs"],
    )

    peft_model = create_lora_model(
        model,
        r=merged["lora_r"],
        lora_alpha=merged["lora_alpha"],
        use_4bit_or_8bit=LOAD_IN_4BIT,
    )
    callbacks = []
    if SHOW_NOTEBOOK_LOG_LINES:
        callbacks.append(NotebookProgressCallback())

    metrics = run_finetune(
        peft_model,
        tokenizer,
        tokenized_train,
        output_dir=str(out),
        num_epochs=merged["num_epochs"],
        per_device_train_batch_size=merged["per_device_train_batch_size"],
        gradient_accumulation_steps=merged["gradient_accumulation_steps"],
        learning_rate=merged["learning_rate"],
        logging_steps=LOGGING_STEPS,
        logging_first_step=True,
        logging_strategy="steps",
        disable_tqdm=DISABLE_TQDM,
        callbacks=callbacks,
        save_log_history_json=True,
        bf16=False,
        fp16=True
    )

    summary = {
        "run_index": run_index,
        "run_hyperparameter_sweep": RUN_HYPERPARAMETER_SWEEP,
        "sweep_overrides": overrides,
        "merged_params": merged,
        "finished_at_utc": datetime.now(timezone.utc).isoformat(),
        "output_dir": str(out.resolve()),
        "log_files": {
            "training_run_log": str((out / "training_run.log").resolve()),
            "trainer_log_history_json": str((out / "trainer_log_history.json").resolve()),
        },
        "logging_steps": LOGGING_STEPS,
        "show_notebook_log_lines": SHOW_NOTEBOOK_LOG_LINES,
        "disable_tqdm": DISABLE_TQDM,
        "transformers_debug": TRANSFORMERS_DEBUG,
        "dataset": DATASET_NAME,
        "split": DATASET_SPLIT,
        "num_train_samples": len(tokenized_train),
        "num_epochs": merged["num_epochs"],
        "per_device_train_batch_size": merged["per_device_train_batch_size"],
        "gradient_accumulation_steps": merged["gradient_accumulation_steps"],
        "learning_rate": merged["learning_rate"],
        "max_length": merged["max_length"],
        "lora_r": merged["lora_r"],
        "lora_alpha": merged["lora_alpha"],
        "load_in_4bit": LOAD_IN_4BIT,
        "final_train_loss": metrics.get("train_loss"),
        "global_step": metrics.get("global_step"),
        "epoch": metrics.get("epoch"),
    }
    with open(out / "training_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    all_summaries.append(summary)

    logging.info("Done run %s/%s: %s", run_index + 1, NUM_COMBINATIONS, out.resolve())
    del model, peft_model, tokenizer, tokenized_train
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

if RUN_HYPERPARAMETER_SWEEP:
    sweep_index_path = Path(OUTPUT_BASE) / "sweep_index.json"
    with open(sweep_index_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "finished_at_utc": datetime.now(timezone.utc).isoformat(),
                "num_runs": NUM_COMBINATIONS,
                "num_skipped": skipped_runs,
                "num_executed": len(all_summaries),
                "runs": [
                    {
                        "output_dir": s["output_dir"],
                        "final_train_loss": s.get("final_train_loss"),
                        "merged_params": s["merged_params"],
                    }
                    for s in all_summaries
                ],
            },
            f,
            indent=2,
        )
    print(f"Wrote sweep index: {sweep_index_path.resolve()}")

print(
    f"Finished: total={NUM_COMBINATIONS}, executed={len(all_summaries)}, skipped={skipped_runs}.\n"
    f"Artifacts under:\n  {Path(OUTPUT_BASE).resolve()}\n"
)

=== Run 1/5  run_000_lr1e-5_r8_a16_ep3  merged={'learning_rate': 1e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-06 00:48:39 | INFO     | root | Logging to C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_000_lr1e-5_r8_a16_ep3\training_run.log
2026-04-06 00:48:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 00:48:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 00:48:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 00:48:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-06 00:48:40 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-06 00:48:40 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-06 00:48:41 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"
2026-04-06 00:48:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 00:48:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 00:48:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 00:48:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 10542.37it/s]
2026-04-06 00:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 00:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": false,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

2026-04-06 00:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2-1.5B.
2026-04-06 00:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-06 00:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-06 00:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 00:48:43 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 00:48:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-06 00:48:44 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-06 00:48:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-06 00:48:45 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 2,179,072

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.6833 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.7304 | lr=7.14e-08 | epoch=0.0043
[train] step=3 | loss=1.7382 | lr=1.43e-07 | epoch=0.0064
[train] step=4 | loss=1.7181 | lr=2.14e-07 | epoch=0.0086
[train] step=5 | loss=1.6863 | lr=2.86e-07 | epoch=0.0107
[train] step=6 | loss=1.7077 | lr=3.57e-07 | epoch=0.0128
[train] step=7 | loss=1.6375 | lr=4.29e-07 | epoch=0.0150
[train] step=8 | loss=1.6110 | lr=5.00e-07 | epoch=0.0171
[train] step=9 | loss=1.7025 | lr=5.71e-07 | epoch=0.0193
[train] step=10 | loss=1.7079 | lr=6.43e-07 | epoch=0.0214
[train] step=11 | loss=1.7555 | lr=7.14e-07 | epoch=0.0235
[train] step=12 | loss=1.8420 | lr=7.86e-07 | epoch=0.0257
[train] step=13 | loss=1.7097 | lr=8.57e-07 | epoch=0.0278
[train] step=14 | loss=1.7561 | lr=9.29e-07 | epoch=0.0300
[train] step=15 | loss=1.8109 | lr=1.00e-06 | epoch=0.0321
[train] step=16 | loss=1.7465 | lr=1.07e-06 | epoch=0.0342
[train] step=17 | loss=1.7255 | lr=1.14e-06 | epoch=0.0364
[train] step=18 | loss=1.7416 | lr=1.21e-06 | epoch=0.0385
[train] step=19 | loss=1.7227 | lr=1.29e-06 | epoch=0.0407
[train] step=20 | loss=1.7288 | lr=1.36e-06 | epoch=0.0428
[train] step=21 | loss=1.6662 | lr=1.43e-06 | epoch=0.0449
[train] step=22 | loss=1.7240 | lr=1.50e-06 | epoch=0.0471
[train] step=23 | loss=1.6978 | lr=1.57e-06 | epoch=0.0492
[train] step=24 | loss=1.7399 | lr=1.64e-06 | epoch=0.0514
[train] step=25 | loss=1.6702 | lr=1.71e-06 | epoch=0.0535
[train] step=26 | loss=1.8004 | lr=1.79e-06 | epoch=0.0556
[train] step=27 | loss=1.6488 | lr=1.86e-06 | epoch=0.0578
[train] step=28 | loss=1.6913 | lr=1.93e-06 | epoch=0.0599
[train] step=29 | loss=1.6712 | lr=2.00e-06 | epoch=0.0621
[train] step=30 | loss=1.7300 | lr=2.07e-06 | epoch=0.0642
[train] step=31 | loss=1.6380 | lr=2.14e-06 | epoch=0.0663
[train] step=32 | loss=1.6716 | lr=2.21e-06 | epoch=0.0685
[train] step=33 | loss=1.6845 | lr=2.29e-06 | epoch=0.0706
[train] step=34 | loss=1.7041 | lr=2.36e-06 | epoch=0.0728
[train] step=35 | loss=1.8322 | lr=2.43e-06 | epoch=0.0749
[train] step=36 | loss=1.7129 | lr=2.50e-06 | epoch=0.0770
[train] step=37 | loss=1.7388 | lr=2.57e-06 | epoch=0.0792
[train] step=38 | loss=1.7115 | lr=2.64e-06 | epoch=0.0813
[train] step=39 | loss=1.6842 | lr=2.71e-06 | epoch=0.0835
[train] step=40 | loss=1.8160 | lr=2.79e-06 | epoch=0.0856
[train] step=41 | loss=1.7338 | lr=2.86e-06 | epoch=0.0877
[train] step=42 | loss=1.7324 | lr=2.93e-06 | epoch=0.0899
[train] step=43 | loss=1.7075 | lr=3.00e-06 | epoch=0.0920
[train] step=44 | loss=1.6571 | lr=3.07e-06 | epoch=0.0942
[train] step=45 | loss=1.7233 | lr=3.14e-06 | epoch=0.0963
[train] step=46 | loss=1.6893 | lr=3.21e-06 | epoch=0.0984
[train] step=47 | loss=1.6910 | lr=3.29e-06 | epoch=0.1006
[train] step=48 | loss=1.5730 | lr=3.36e-06 | epoch=0.1027
[train] step=49 | loss=1.6792 | lr=3.43e-06 | epoch=0.1049
[train] step=50 | loss=1.7924 | lr=3.50e-06 | epoch=0.1070
[train] step=51 | loss=1.7323 | lr=3.57e-06 | epoch=0.1091
[train] step=52 | loss=1.7264 | lr=3.64e-06 | epoch=0.1113
[train] step=53 | loss=1.8187 | lr=3.71e-06 | epoch=0.1134
[train] step=54 | loss=1.6815 | lr=3.79e-06 | epoch=0.1156
[train] step=55 | loss=1.5774 | lr=3.86e-06 | epoch=0.1177
[train] step=56 | loss=1.7913 | lr=3.93e-06 | epoch=0.1199
[train] step=57 | loss=1.5570 | lr=4.00e-06 | epoch=0.1220
[train] step=58 | loss=1.7211 | lr=4.07e-06 | epoch=0.1241
[train] step=59 | loss=1.6519 | lr=4.14e-06 | epoch=0.1263
[train] step=60 | loss=1.6497 | lr=4.21e-06 | epoch=0.1284
[train] step=61 | loss=1.6509 | lr=4.29e-06 | epoch=0.1306
[train] step=62 | loss=1.6663 | lr=4.36e-06 | epoch=0.1327
[train] step=63 | loss=1.6148 | lr=4.43e-06 | epoch=0.1348
[train] step=64 | loss=1.8215 | lr=4.50e-06 | epoch=0.1370
[train] step=65 | loss=1.6662 | lr=4.57e-06 | epoch=0.1391
[train] step=66 | loss=1.7089 | lr=4.64e-06 | epoch=0.1413
[train] step=67 | loss=1.6514 | lr=4.71e-06 | epoch=0.1434
[train] step=68 | loss=1.7548 | lr=4.79e-06 | epoch=0.1455
[train] step=69 | loss=1.7932 | lr=4.86e-06 | epoch=0.1477
[train] step=70 | loss=1.7200 | lr=4.93e-06 | epoch=0.1498
[train] step=71 | loss=1.6450 | lr=5.00e-06 | epoch=0.1520
[train] step=72 | loss=1.6820 | lr=5.07e-06 | epoch=0.1541
[train] step=73 | loss=1.6732 | lr=5.14e-06 | epoch=0.1562
[train] step=74 | loss=1.6909 | lr=5.21e-06 | epoch=0.1584
[train] step=75 | loss=1.6461 | lr=5.29e-06 | epoch=0.1605
[train] step=76 | loss=1.6168 | lr=5.36e-06 | epoch=0.1627
[train] step=77 | loss=1.5270 | lr=5.43e-06 | epoch=0.1648
[train] step=78 | loss=1.7149 | lr=5.50e-06 | epoch=0.1669
[train] step=79 | loss=1.7420 | lr=5.57e-06 | epoch=0.1691
[train] step=80 | loss=1.5940 | lr=5.64e-06 | epoch=0.1712
[train] step=81 | loss=1.6307 | lr=5.71e-06 | epoch=0.1734
[train] step=82 | loss=1.6575 | lr=5.79e-06 | epoch=0.1755
[train] step=83 | loss=1.6779 | lr=5.86e-06 | epoch=0.1776
[train] step=84 | loss=1.6368 | lr=5.93e-06 | epoch=0.1798
[train] step=85 | loss=1.7007 | lr=6.00e-06 | epoch=0.1819
[train] step=86 | loss=1.6380 | lr=6.07e-06 | epoch=0.1841
[train] step=87 | loss=1.6224 | lr=6.14e-06 | epoch=0.1862
[train] step=88 | loss=1.6822 | lr=6.21e-06 | epoch=0.1883
[train] step=89 | loss=1.5799 | lr=6.29e-06 | epoch=0.1905
[train] step=90 | loss=1.6670 | lr=6.36e-06 | epoch=0.1926
[train] step=91 | loss=1.5447 | lr=6.43e-06 | epoch=0.1948
[train] step=92 | loss=1.6621 | lr=6.50e-06 | epoch=0.1969
[train] step=93 | loss=1.5974 | lr=6.57e-06 | epoch=0.1990
[train] step=94 | loss=1.6042 | lr=6.64e-06 | epoch=0.2012
[train] step=95 | loss=1.6073 | lr=6.71e-06 | epoch=0.2033
[train] step=96 | loss=1.6224 | lr=6.79e-06 | epoch=0.2055
[train] step=97 | loss=1.5580 | lr=6.86e-06 | epoch=0.2076
[train] step=98 | loss=1.6913 | lr=6.93e-06 | epoch=0.2097
[train] step=99 | loss=1.5856 | lr=7.00e-06 | epoch=0.2119
[train] step=100 | loss=1.5682 | lr=7.07e-06 | epoch=0.2140
[train] step=101 | loss=1.7086 | lr=7.14e-06 | epoch=0.2162
[train] step=102 | loss=1.5872 | lr=7.21e-06 | epoch=0.2183
[train] step=103 | loss=1.5553 | lr=7.29e-06 | epoch=0.2204
[train] step=104 | loss=1.5418 | lr=7.36e-06 | epoch=0.2226
[train] step=105 | loss=1.5369 | lr=7.43e-06 | epoch=0.2247
[train] step=106 | loss=1.5915 | lr=7.50e-06 | epoch=0.2269
[train] step=107 | loss=1.5637 | lr=7.57e-06 | epoch=0.2290
[train] step=108 | loss=1.5512 | lr=7.64e-06 | epoch=0.2311
[train] step=109 | loss=1.5316 | lr=7.71e-06 | epoch=0.2333
[train] step=110 | loss=1.5732 | lr=7.79e-06 | epoch=0.2354
[train] step=111 | loss=1.5923 | lr=7.86e-06 | epoch=0.2376
[train] step=112 | loss=1.5238 | lr=7.93e-06 | epoch=0.2397
[train] step=113 | loss=1.6438 | lr=8.00e-06 | epoch=0.2418
[train] step=114 | loss=1.4924 | lr=8.07e-06 | epoch=0.2440
[train] step=115 | loss=1.6234 | lr=8.14e-06 | epoch=0.2461
[train] step=116 | loss=1.4610 | lr=8.21e-06 | epoch=0.2483
[train] step=117 | loss=1.4958 | lr=8.29e-06 | epoch=0.2504
[train] step=118 | loss=1.5483 | lr=8.36e-06 | epoch=0.2525
[train] step=119 | loss=1.5851 | lr=8.43e-06 | epoch=0.2547
[train] step=120 | loss=1.4475 | lr=8.50e-06 | epoch=0.2568
[train] step=121 | loss=1.5021 | lr=8.57e-06 | epoch=0.2590
[train] step=122 | loss=1.4499 | lr=8.64e-06 | epoch=0.2611
[train] step=123 | loss=1.4103 | lr=8.71e-06 | epoch=0.2632
[train] step=124 | loss=1.4462 | lr=8.79e-06 | epoch=0.2654
[train] step=125 | loss=1.4880 | lr=8.86e-06 | epoch=0.2675
[train] step=126 | loss=1.4681 | lr=8.93e-06 | epoch=0.2697
[train] step=127 | loss=1.4182 | lr=9.00e-06 | epoch=0.2718
[train] step=128 | loss=1.4903 | lr=9.07e-06 | epoch=0.2739
[train] step=129 | loss=1.3377 | lr=9.14e-06 | epoch=0.2761
[train] step=130 | loss=1.4529 | lr=9.21e-06 | epoch=0.2782
[train] step=131 | loss=1.4422 | lr=9.29e-06 | epoch=0.2804
[train] step=132 | loss=1.5167 | lr=9.36e-06 | epoch=0.2825
[train] step=133 | loss=1.4925 | lr=9.43e-06 | epoch=0.2846
[train] step=134 | loss=1.4164 | lr=9.50e-06 | epoch=0.2868
[train] step=135 | loss=1.3429 | lr=9.57e-06 | epoch=0.2889
[train] step=136 | loss=1.3903 | lr=9.64e-06 | epoch=0.2911
[train] step=137 | loss=1.3883 | lr=9.71e-06 | epoch=0.2932
[train] step=138 | loss=1.4266 | lr=9.79e-06 | epoch=0.2953
[train] step=139 | loss=1.4347 | lr=9.86e-06 | epoch=0.2975
[train] step=140 | loss=1.3694 | lr=9.93e-06 | epoch=0.2996
[train] step=141 | loss=1.4157 | lr=1.00e-05 | epoch=0.3018
[train] step=142 | loss=1.4478 | lr=9.99e-06 | epoch=0.3039
[train] step=143 | loss=1.3446 | lr=9.98e-06 | epoch=0.3060
[train] step=144 | loss=1.4202 | lr=9.98e-06 | epoch=0.3082
[train] step=145 | loss=1.3571 | lr=9.97e-06 | epoch=0.3103
[train] step=146 | loss=1.4256 | lr=9.96e-06 | epoch=0.3125
[train] step=147 | loss=1.4456 | lr=9.95e-06 | epoch=0.3146
[train] step=148 | loss=1.3665 | lr=9.94e-06 | epoch=0.3167
[train] step=149 | loss=1.2899 | lr=9.94e-06 | epoch=0.3189
[train] step=150 | loss=1.2602 | lr=9.93e-06 | epoch=0.3210
[train] step=151 | loss=1.2683 | lr=9.92e-06 | epoch=0.3232
[train] step=152 | loss=1.3044 | lr=9.91e-06 | epoch=0.3253
[train] step=153 | loss=1.3262 | lr=9.91e-06 | epoch=0.3274
[train] step=154 | loss=1.3420 | lr=9.90e-06 | epoch=0.3296
[train] step=155 | loss=1.3237 | lr=9.89e-06 | epoch=0.3317
[train] step=156 | loss=1.3497 | lr=9.88e-06 | epoch=0.3339
[train] step=157 | loss=1.2961 | lr=9.87e-06 | epoch=0.3360
[train] step=158 | loss=1.2311 | lr=9.87e-06 | epoch=0.3381
[train] step=159 | loss=1.2453 | lr=9.86e-06 | epoch=0.3403
[train] step=160 | loss=1.2177 | lr=9.85e-06 | epoch=0.3424
[train] step=161 | loss=1.2563 | lr=9.84e-06 | epoch=0.3446
[train] step=162 | loss=1.1691 | lr=9.83e-06 | epoch=0.3467
[train] step=163 | loss=1.2562 | lr=9.83e-06 | epoch=0.3488
[train] step=164 | loss=1.2572 | lr=9.82e-06 | epoch=0.3510
[train] step=165 | loss=1.1585 | lr=9.81e-06 | epoch=0.3531
[train] step=166 | loss=1.2027 | lr=9.80e-06 | epoch=0.3553
[train] step=167 | loss=1.2039 | lr=9.79e-06 | epoch=0.3574
[train] step=168 | loss=1.1322 | lr=9.79e-06 | epoch=0.3596
[train] step=169 | loss=1.1990 | lr=9.78e-06 | epoch=0.3617
[train] step=170 | loss=1.1937 | lr=9.77e-06 | epoch=0.3638
[train] step=171 | loss=1.1894 | lr=9.76e-06 | epoch=0.3660
[train] step=172 | loss=1.2011 | lr=9.75e-06 | epoch=0.3681
[train] step=173 | loss=1.0921 | lr=9.75e-06 | epoch=0.3703
[train] step=174 | loss=1.1516 | lr=9.74e-06 | epoch=0.3724
[train] step=175 | loss=1.1303 | lr=9.73e-06 | epoch=0.3745
[train] step=176 | loss=1.1785 | lr=9.72e-06 | epoch=0.3767
[train] step=177 | loss=1.0998 | lr=9.72e-06 | epoch=0.3788
[train] step=178 | loss=1.0803 | lr=9.71e-06 | epoch=0.3810
[train] step=179 | loss=1.0614 | lr=9.70e-06 | epoch=0.3831
[train] step=180 | loss=1.1022 | lr=9.69e-06 | epoch=0.3852
[train] step=181 | loss=1.0899 | lr=9.68e-06 | epoch=0.3874
[train] step=182 | loss=1.0732 | lr=9.68e-06 | epoch=0.3895
[train] step=183 | loss=1.0260 | lr=9.67e-06 | epoch=0.3917
[train] step=184 | loss=1.0761 | lr=9.66e-06 | epoch=0.3938
[train] step=185 | loss=1.0470 | lr=9.65e-06 | epoch=0.3959
[train] step=186 | loss=1.0431 | lr=9.64e-06 | epoch=0.3981
[train] step=187 | loss=1.0645 | lr=9.64e-06 | epoch=0.4002
[train] step=188 | loss=0.9710 | lr=9.63e-06 | epoch=0.4024
[train] step=189 | loss=1.0084 | lr=9.62e-06 | epoch=0.4045
[train] step=190 | loss=1.0015 | lr=9.61e-06 | epoch=0.4066
[train] step=191 | loss=0.9850 | lr=9.60e-06 | epoch=0.4088
[train] step=192 | loss=0.9397 | lr=9.60e-06 | epoch=0.4109
[train] step=193 | loss=0.9649 | lr=9.59e-06 | epoch=0.4131
[train] step=194 | loss=0.9287 | lr=9.58e-06 | epoch=0.4152
[train] step=195 | loss=0.9959 | lr=9.57e-06 | epoch=0.4173
[train] step=196 | loss=0.9051 | lr=9.56e-06 | epoch=0.4195
[train] step=197 | loss=0.9308 | lr=9.56e-06 | epoch=0.4216
[train] step=198 | loss=0.9065 | lr=9.55e-06 | epoch=0.4238
[train] step=199 | loss=0.9430 | lr=9.54e-06 | epoch=0.4259
[train] step=200 | loss=0.8726 | lr=9.53e-06 | epoch=0.4280
[train] step=201 | loss=0.8311 | lr=9.53e-06 | epoch=0.4302
[train] step=202 | loss=0.9369 | lr=9.52e-06 | epoch=0.4323
[train] step=203 | loss=0.8481 | lr=9.51e-06 | epoch=0.4345
[train] step=204 | loss=0.8731 | lr=9.50e-06 | epoch=0.4366
[train] step=205 | loss=0.7906 | lr=9.49e-06 | epoch=0.4387
[train] step=206 | loss=0.7691 | lr=9.49e-06 | epoch=0.4409
[train] step=207 | loss=0.8153 | lr=9.48e-06 | epoch=0.4430
[train] step=208 | loss=0.7576 | lr=9.47e-06 | epoch=0.4452
[train] step=209 | loss=0.7743 | lr=9.46e-06 | epoch=0.4473
[train] step=210 | loss=0.7539 | lr=9.45e-06 | epoch=0.4494
[train] step=211 | loss=0.7462 | lr=9.45e-06 | epoch=0.4516
[train] step=212 | loss=0.6859 | lr=9.44e-06 | epoch=0.4537
[train] step=213 | loss=0.7598 | lr=9.43e-06 | epoch=0.4559
[train] step=214 | loss=0.7351 | lr=9.42e-06 | epoch=0.4580
[train] step=215 | loss=0.7304 | lr=9.41e-06 | epoch=0.4601
[train] step=216 | loss=0.7080 | lr=9.41e-06 | epoch=0.4623
[train] step=217 | loss=0.6754 | lr=9.40e-06 | epoch=0.4644
[train] step=218 | loss=0.6211 | lr=9.39e-06 | epoch=0.4666
[train] step=219 | loss=0.6626 | lr=9.38e-06 | epoch=0.4687
[train] step=220 | loss=0.6019 | lr=9.38e-06 | epoch=0.4708
[train] step=221 | loss=0.6219 | lr=9.37e-06 | epoch=0.4730
[train] step=222 | loss=0.6157 | lr=9.36e-06 | epoch=0.4751
[train] step=223 | loss=0.5674 | lr=9.35e-06 | epoch=0.4773
[train] step=224 | loss=0.5365 | lr=9.34e-06 | epoch=0.4794
[train] step=225 | loss=0.5528 | lr=9.34e-06 | epoch=0.4815
[train] step=226 | loss=0.5450 | lr=9.33e-06 | epoch=0.4837
[train] step=227 | loss=0.5264 | lr=9.32e-06 | epoch=0.4858
[train] step=228 | loss=0.4988 | lr=9.31e-06 | epoch=0.4880
[train] step=229 | loss=0.4910 | lr=9.30e-06 | epoch=0.4901
[train] step=230 | loss=0.4723 | lr=9.30e-06 | epoch=0.4922
[train] step=231 | loss=0.4688 | lr=9.29e-06 | epoch=0.4944
[train] step=232 | loss=0.4589 | lr=9.28e-06 | epoch=0.4965
[train] step=233 | loss=0.4669 | lr=9.27e-06 | epoch=0.4987

Saving model checkpoint to output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-233
2026-04-06 00:58:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 00:58:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 00:58:48 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 00:58:48 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-233\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-233\tokenizer_config.json

[train] step=234 | loss=0.4398 | lr=9.26e-06 | epoch=0.5008
[train] step=235 | loss=0.4258 | lr=9.26e-06 | epoch=0.5029
[train] step=236 | loss=0.4284 | lr=9.25e-06 | epoch=0.5051
[train] step=237 | loss=0.4398 | lr=9.24e-06 | epoch=0.5072
[train] step=238 | loss=0.4000 | lr=9.23e-06 | epoch=0.5094
[train] step=239 | loss=0.3802 | lr=9.22e-06 | epoch=0.5115
[train] step=240 | loss=0.3811 | lr=9.22e-06 | epoch=0.5136
[train] step=241 | loss=0.3854 | lr=9.21e-06 | epoch=0.5158
[train] step=242 | loss=0.3482 | lr=9.20e-06 | epoch=0.5179
[train] step=243 | loss=0.3800 | lr=9.19e-06 | epoch=0.5201
[train] step=244 | loss=0.3624 | lr=9.19e-06 | epoch=0.5222
[train] step=245 | loss=0.3110 | lr=9.18e-06 | epoch=0.5243
[train] step=246 | loss=0.3543 | lr=9.17e-06 | epoch=0.5265
[train] step=247 | loss=0.3378 | lr=9.16e-06 | epoch=0.5286
[train] step=248 | loss=0.3203 | lr=9.15e-06 | epoch=0.5308
[train] step=249 | loss=0.2913 | lr=9.15e-06 | epoch=0.5329
[train] step=250 | loss=0.2989 | lr=9.14e-06 | epoch=0.5350
[train] step=251 | loss=0.2912 | lr=9.13e-06 | epoch=0.5372
[train] step=252 | loss=0.3056 | lr=9.12e-06 | epoch=0.5393
[train] step=253 | loss=0.3002 | lr=9.11e-06 | epoch=0.5415
[train] step=254 | loss=0.2779 | lr=9.11e-06 | epoch=0.5436
[train] step=255 | loss=0.2700 | lr=9.10e-06 | epoch=0.5457
[train] step=256 | loss=0.2554 | lr=9.09e-06 | epoch=0.5479
[train] step=257 | loss=0.2532 | lr=9.08e-06 | epoch=0.5500
[train] step=258 | loss=0.2594 | lr=9.07e-06 | epoch=0.5522
[train] step=259 | loss=0.2640 | lr=9.07e-06 | epoch=0.5543
[train] step=260 | loss=0.2645 | lr=9.06e-06 | epoch=0.5564
[train] step=261 | loss=0.2434 | lr=9.05e-06 | epoch=0.5586
[train] step=262 | loss=0.2763 | lr=9.04e-06 | epoch=0.5607
[train] step=263 | loss=0.2385 | lr=9.03e-06 | epoch=0.5629
[train] step=264 | loss=0.2300 | lr=9.03e-06 | epoch=0.5650
[train] step=265 | loss=0.2695 | lr=9.02e-06 | epoch=0.5671
[train] step=266 | loss=0.2437 | lr=9.01e-06 | epoch=0.5693
[train] step=267 | loss=0.2436 | lr=9.00e-06 | epoch=0.5714
[train] step=268 | loss=0.2320 | lr=9.00e-06 | epoch=0.5736
[train] step=269 | loss=0.2471 | lr=8.99e-06 | epoch=0.5757
[train] step=270 | loss=0.2563 | lr=8.98e-06 | epoch=0.5778
[train] step=271 | loss=0.2318 | lr=8.97e-06 | epoch=0.5800
[train] step=272 | loss=0.2378 | lr=8.96e-06 | epoch=0.5821
[train] step=273 | loss=0.2260 | lr=8.96e-06 | epoch=0.5843
[train] step=274 | loss=0.2214 | lr=8.95e-06 | epoch=0.5864
[train] step=275 | loss=0.2389 | lr=8.94e-06 | epoch=0.5886
[train] step=276 | loss=0.2442 | lr=8.93e-06 | epoch=0.5907
[train] step=277 | loss=0.2179 | lr=8.92e-06 | epoch=0.5928
[train] step=278 | loss=0.2220 | lr=8.92e-06 | epoch=0.5950
[train] step=279 | loss=0.2116 | lr=8.91e-06 | epoch=0.5971
[train] step=280 | loss=0.2066 | lr=8.90e-06 | epoch=0.5993
[train] step=281 | loss=0.2104 | lr=8.89e-06 | epoch=0.6014
[train] step=282 | loss=0.2177 | lr=8.88e-06 | epoch=0.6035
[train] step=283 | loss=0.2254 | lr=8.88e-06 | epoch=0.6057
[train] step=284 | loss=0.2158 | lr=8.87e-06 | epoch=0.6078
[train] step=285 | loss=0.2095 | lr=8.86e-06 | epoch=0.6100
[train] step=286 | loss=0.2098 | lr=8.85e-06 | epoch=0.6121
[train] step=287 | loss=0.2140 | lr=8.84e-06 | epoch=0.6142
[train] step=288 | loss=0.2132 | lr=8.84e-06 | epoch=0.6164
[train] step=289 | loss=0.2011 | lr=8.83e-06 | epoch=0.6185
[train] step=290 | loss=0.2028 | lr=8.82e-06 | epoch=0.6207
[train] step=291 | loss=0.2272 | lr=8.81e-06 | epoch=0.6228
[train] step=292 | loss=0.2104 | lr=8.81e-06 | epoch=0.6249
[train] step=293 | loss=0.2319 | lr=8.80e-06 | epoch=0.6271
[train] step=294 | loss=0.1971 | lr=8.79e-06 | epoch=0.6292
[train] step=295 | loss=0.2206 | lr=8.78e-06 | epoch=0.6314
[train] step=296 | loss=0.1912 | lr=8.77e-06 | epoch=0.6335
[train] step=297 | loss=0.2211 | lr=8.77e-06 | epoch=0.6356
[train] step=298 | loss=0.1958 | lr=8.76e-06 | epoch=0.6378
[train] step=299 | loss=0.1956 | lr=8.75e-06 | epoch=0.6399
[train] step=300 | loss=0.2027 | lr=8.74e-06 | epoch=0.6421
[train] step=301 | loss=0.2075 | lr=8.73e-06 | epoch=0.6442
[train] step=302 | loss=0.1894 | lr=8.73e-06 | epoch=0.6463
[train] step=303 | loss=0.2002 | lr=8.72e-06 | epoch=0.6485
[train] step=304 | loss=0.2076 | lr=8.71e-06 | epoch=0.6506
[train] step=305 | loss=0.1978 | lr=8.70e-06 | epoch=0.6528
[train] step=306 | loss=0.2248 | lr=8.69e-06 | epoch=0.6549
[train] step=307 | loss=0.2194 | lr=8.69e-06 | epoch=0.6570
[train] step=308 | loss=0.1917 | lr=8.68e-06 | epoch=0.6592
[train] step=309 | loss=0.2217 | lr=8.67e-06 | epoch=0.6613
[train] step=310 | loss=0.1870 | lr=8.66e-06 | epoch=0.6635
[train] step=311 | loss=0.1791 | lr=8.66e-06 | epoch=0.6656
[train] step=312 | loss=0.2241 | lr=8.65e-06 | epoch=0.6677
[train] step=313 | loss=0.2230 | lr=8.64e-06 | epoch=0.6699
[train] step=314 | loss=0.1910 | lr=8.63e-06 | epoch=0.6720
[train] step=315 | loss=0.1826 | lr=8.62e-06 | epoch=0.6742
[train] step=316 | loss=0.1842 | lr=8.62e-06 | epoch=0.6763
[train] step=317 | loss=0.1916 | lr=8.61e-06 | epoch=0.6784
[train] step=318 | loss=0.1843 | lr=8.60e-06 | epoch=0.6806
[train] step=319 | loss=0.2154 | lr=8.59e-06 | epoch=0.6827
[train] step=320 | loss=0.1910 | lr=8.58e-06 | epoch=0.6849
[train] step=321 | loss=0.1790 | lr=8.58e-06 | epoch=0.6870
[train] step=322 | loss=0.1853 | lr=8.57e-06 | epoch=0.6891
[train] step=323 | loss=0.1909 | lr=8.56e-06 | epoch=0.6913
[train] step=324 | loss=0.1802 | lr=8.55e-06 | epoch=0.6934
[train] step=325 | loss=0.1815 | lr=8.54e-06 | epoch=0.6956
[train] step=326 | loss=0.1725 | lr=8.54e-06 | epoch=0.6977
[train] step=327 | loss=0.1802 | lr=8.53e-06 | epoch=0.6998
[train] step=328 | loss=0.2022 | lr=8.52e-06 | epoch=0.7020
[train] step=329 | loss=0.1554 | lr=8.51e-06 | epoch=0.7041
[train] step=330 | loss=0.1600 | lr=8.50e-06 | epoch=0.7063
[train] step=331 | loss=0.1677 | lr=8.50e-06 | epoch=0.7084
[train] step=332 | loss=0.1831 | lr=8.49e-06 | epoch=0.7105
[train] step=333 | loss=0.1907 | lr=8.48e-06 | epoch=0.7127
[train] step=334 | loss=0.1892 | lr=8.47e-06 | epoch=0.7148
[train] step=335 | loss=0.1389 | lr=8.47e-06 | epoch=0.7170
[train] step=336 | loss=0.1641 | lr=8.46e-06 | epoch=0.7191
[train] step=337 | loss=0.1565 | lr=8.45e-06 | epoch=0.7212
[train] step=338 | loss=0.1617 | lr=8.44e-06 | epoch=0.7234
[train] step=339 | loss=0.1753 | lr=8.43e-06 | epoch=0.7255
[train] step=340 | loss=0.1632 | lr=8.43e-06 | epoch=0.7277
[train] step=341 | loss=0.1971 | lr=8.42e-06 | epoch=0.7298
[train] step=342 | loss=0.1486 | lr=8.41e-06 | epoch=0.7319
[train] step=343 | loss=0.1386 | lr=8.40e-06 | epoch=0.7341
[train] step=344 | loss=0.1564 | lr=8.39e-06 | epoch=0.7362
[train] step=345 | loss=0.1756 | lr=8.39e-06 | epoch=0.7384
[train] step=346 | loss=0.1584 | lr=8.38e-06 | epoch=0.7405
[train] step=347 | loss=0.1509 | lr=8.37e-06 | epoch=0.7426
[train] step=348 | loss=0.1700 | lr=8.36e-06 | epoch=0.7448
[train] step=349 | loss=0.1495 | lr=8.35e-06 | epoch=0.7469
[train] step=350 | loss=0.1355 | lr=8.35e-06 | epoch=0.7491
[train] step=351 | loss=0.1620 | lr=8.34e-06 | epoch=0.7512
[train] step=352 | loss=0.1432 | lr=8.33e-06 | epoch=0.7533
[train] step=353 | loss=0.1785 | lr=8.32e-06 | epoch=0.7555
[train] step=354 | loss=0.1249 | lr=8.31e-06 | epoch=0.7576
[train] step=355 | loss=0.1603 | lr=8.31e-06 | epoch=0.7598
[train] step=356 | loss=0.1477 | lr=8.30e-06 | epoch=0.7619
[train] step=357 | loss=0.1557 | lr=8.29e-06 | epoch=0.7640
[train] step=358 | loss=0.1246 | lr=8.28e-06 | epoch=0.7662
[train] step=359 | loss=0.1428 | lr=8.28e-06 | epoch=0.7683
[train] step=360 | loss=0.1574 | lr=8.27e-06 | epoch=0.7705
[train] step=361 | loss=0.1468 | lr=8.26e-06 | epoch=0.7726
[train] step=362 | loss=0.1444 | lr=8.25e-06 | epoch=0.7747
[train] step=363 | loss=0.1698 | lr=8.24e-06 | epoch=0.7769
[train] step=364 | loss=0.1406 | lr=8.24e-06 | epoch=0.7790
[train] step=365 | loss=0.1379 | lr=8.23e-06 | epoch=0.7812
[train] step=366 | loss=0.1634 | lr=8.22e-06 | epoch=0.7833
[train] step=367 | loss=0.1354 | lr=8.21e-06 | epoch=0.7854
[train] step=368 | loss=0.1480 | lr=8.20e-06 | epoch=0.7876
[train] step=369 | loss=0.1528 | lr=8.20e-06 | epoch=0.7897
[train] step=370 | loss=0.1574 | lr=8.19e-06 | epoch=0.7919
[train] step=371 | loss=0.1589 | lr=8.18e-06 | epoch=0.7940
[train] step=372 | loss=0.1523 | lr=8.17e-06 | epoch=0.7961
[train] step=373 | loss=0.1625 | lr=8.16e-06 | epoch=0.7983
[train] step=374 | loss=0.1466 | lr=8.16e-06 | epoch=0.8004
[train] step=375 | loss=0.1482 | lr=8.15e-06 | epoch=0.8026
[train] step=376 | loss=0.1327 | lr=8.14e-06 | epoch=0.8047
[train] step=377 | loss=0.1267 | lr=8.13e-06 | epoch=0.8068
[train] step=378 | loss=0.1342 | lr=8.13e-06 | epoch=0.8090
[train] step=379 | loss=0.1740 | lr=8.12e-06 | epoch=0.8111
[train] step=380 | loss=0.1639 | lr=8.11e-06 | epoch=0.8133
[train] step=381 | loss=0.1598 | lr=8.10e-06 | epoch=0.8154
[train] step=382 | loss=0.1550 | lr=8.09e-06 | epoch=0.8175
[train] step=383 | loss=0.1287 | lr=8.09e-06 | epoch=0.8197
[train] step=384 | loss=0.1179 | lr=8.08e-06 | epoch=0.8218
[train] step=385 | loss=0.1490 | lr=8.07e-06 | epoch=0.8240
[train] step=386 | loss=0.1879 | lr=8.06e-06 | epoch=0.8261
[train] step=387 | loss=0.1271 | lr=8.05e-06 | epoch=0.8283
[train] step=388 | loss=0.1430 | lr=8.05e-06 | epoch=0.8304
[train] step=389 | loss=0.1271 | lr=8.04e-06 | epoch=0.8325
[train] step=390 | loss=0.1326 | lr=8.03e-06 | epoch=0.8347
[train] step=391 | loss=0.1246 | lr=8.02e-06 | epoch=0.8368
[train] step=392 | loss=0.1237 | lr=8.01e-06 | epoch=0.8390
[train] step=393 | loss=0.1326 | lr=8.01e-06 | epoch=0.8411
[train] step=394 | loss=0.1437 | lr=8.00e-06 | epoch=0.8432
[train] step=395 | loss=0.1415 | lr=7.99e-06 | epoch=0.8454
[train] step=396 | loss=0.1484 | lr=7.98e-06 | epoch=0.8475
[train] step=397 | loss=0.1348 | lr=7.97e-06 | epoch=0.8497
[train] step=398 | loss=0.1387 | lr=7.97e-06 | epoch=0.8518
[train] step=399 | loss=0.1336 | lr=7.96e-06 | epoch=0.8539
[train] step=400 | loss=0.1431 | lr=7.95e-06 | epoch=0.8561
[train] step=401 | loss=0.1416 | lr=7.94e-06 | epoch=0.8582
[train] step=402 | loss=0.1331 | lr=7.94e-06 | epoch=0.8604
[train] step=403 | loss=0.1136 | lr=7.93e-06 | epoch=0.8625
[train] step=404 | loss=0.1310 | lr=7.92e-06 | epoch=0.8646
[train] step=405 | loss=0.1348 | lr=7.91e-06 | epoch=0.8668
[train] step=406 | loss=0.1264 | lr=7.90e-06 | epoch=0.8689
[train] step=407 | loss=0.1062 | lr=7.90e-06 | epoch=0.8711
[train] step=408 | loss=0.1493 | lr=7.89e-06 | epoch=0.8732
[train] step=409 | loss=0.1344 | lr=7.88e-06 | epoch=0.8753
[train] step=410 | loss=0.1130 | lr=7.87e-06 | epoch=0.8775
[train] step=411 | loss=0.1256 | lr=7.86e-06 | epoch=0.8796
[train] step=412 | loss=0.1301 | lr=7.86e-06 | epoch=0.8818
[train] step=413 | loss=0.1254 | lr=7.85e-06 | epoch=0.8839
[train] step=414 | loss=0.1404 | lr=7.84e-06 | epoch=0.8860
[train] step=415 | loss=0.1250 | lr=7.83e-06 | epoch=0.8882
[train] step=416 | loss=0.1479 | lr=7.82e-06 | epoch=0.8903
[train] step=417 | loss=0.1385 | lr=7.82e-06 | epoch=0.8925
[train] step=418 | loss=0.1231 | lr=7.81e-06 | epoch=0.8946
[train] step=419 | loss=0.1200 | lr=7.80e-06 | epoch=0.8967
[train] step=420 | loss=0.1411 | lr=7.79e-06 | epoch=0.8989
[train] step=421 | loss=0.1213 | lr=7.78e-06 | epoch=0.9010
[train] step=422 | loss=0.1164 | lr=7.78e-06 | epoch=0.9032
[train] step=423 | loss=0.1449 | lr=7.77e-06 | epoch=0.9053
[train] step=424 | loss=0.1441 | lr=7.76e-06 | epoch=0.9074
[train] step=425 | loss=0.1328 | lr=7.75e-06 | epoch=0.9096
[train] step=426 | loss=0.1234 | lr=7.75e-06 | epoch=0.9117
[train] step=427 | loss=0.1327 | lr=7.74e-06 | epoch=0.9139
[train] step=428 | loss=0.1208 | lr=7.73e-06 | epoch=0.9160
[train] step=429 | loss=0.1352 | lr=7.72e-06 | epoch=0.9181
[train] step=430 | loss=0.1228 | lr=7.71e-06 | epoch=0.9203
[train] step=431 | loss=0.1214 | lr=7.71e-06 | epoch=0.9224
[train] step=432 | loss=0.1658 | lr=7.70e-06 | epoch=0.9246
[train] step=433 | loss=0.1169 | lr=7.69e-06 | epoch=0.9267
[train] step=434 | loss=0.1089 | lr=7.68e-06 | epoch=0.9288
[train] step=435 | loss=0.1339 | lr=7.67e-06 | epoch=0.9310
[train] step=436 | loss=0.1467 | lr=7.67e-06 | epoch=0.9331
[train] step=437 | loss=0.1165 | lr=7.66e-06 | epoch=0.9353
[train] step=438 | loss=0.1101 | lr=7.65e-06 | epoch=0.9374
[train] step=439 | loss=0.1514 | lr=7.64e-06 | epoch=0.9395
[train] step=440 | loss=0.1369 | lr=7.63e-06 | epoch=0.9417
[train] step=441 | loss=0.1322 | lr=7.63e-06 | epoch=0.9438
[train] step=442 | loss=0.1584 | lr=7.62e-06 | epoch=0.9460
[train] step=443 | loss=0.1248 | lr=7.61e-06 | epoch=0.9481
[train] step=444 | loss=0.1262 | lr=7.60e-06 | epoch=0.9502
[train] step=445 | loss=0.1267 | lr=7.59e-06 | epoch=0.9524
[train] step=446 | loss=0.1103 | lr=7.59e-06 | epoch=0.9545
[train] step=447 | loss=0.1082 | lr=7.58e-06 | epoch=0.9567
[train] step=448 | loss=0.1427 | lr=7.57e-06 | epoch=0.9588
[train] step=449 | loss=0.1406 | lr=7.56e-06 | epoch=0.9609
[train] step=450 | loss=0.1044 | lr=7.56e-06 | epoch=0.9631
[train] step=451 | loss=0.1257 | lr=7.55e-06 | epoch=0.9652
[train] step=452 | loss=0.1206 | lr=7.54e-06 | epoch=0.9674
[train] step=453 | loss=0.1125 | lr=7.53e-06 | epoch=0.9695
[train] step=454 | loss=0.1247 | lr=7.52e-06 | epoch=0.9716
[train] step=455 | loss=0.1188 | lr=7.52e-06 | epoch=0.9738
[train] step=456 | loss=0.1415 | lr=7.51e-06 | epoch=0.9759
[train] step=457 | loss=0.1418 | lr=7.50e-06 | epoch=0.9781
[train] step=458 | loss=0.1322 | lr=7.49e-06 | epoch=0.9802
[train] step=459 | loss=0.1395 | lr=7.48e-06 | epoch=0.9823
[train] step=460 | loss=0.1242 | lr=7.48e-06 | epoch=0.9845
[train] step=461 | loss=0.1251 | lr=7.47e-06 | epoch=0.9866
[train] step=462 | loss=0.1243 | lr=7.46e-06 | epoch=0.9888
[train] step=463 | loss=0.1163 | lr=7.45e-06 | epoch=0.9909
[train] step=464 | loss=0.1365 | lr=7.44e-06 | epoch=0.9930
[train] step=465 | loss=0.1214 | lr=7.44e-06 | epoch=0.9952
[train] step=466 | loss=0.1235 | lr=7.43e-06 | epoch=0.9973

Saving model checkpoint to output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-466
2026-04-06 01:08:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:08:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 01:08:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:08:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-466\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-466\tokenizer_config.json

[train] step=467 | loss=0.1319 | lr=7.42e-06 | epoch=0.9995
[train] step=468 | loss=0.0815 | lr=7.41e-06 | epoch=1.0000
[train] step=469 | loss=0.1097 | lr=7.41e-06 | epoch=1.0021
[train] step=470 | loss=0.1303 | lr=7.40e-06 | epoch=1.0043
[train] step=471 | loss=0.1327 | lr=7.39e-06 | epoch=1.0064
[train] step=472 | loss=0.1443 | lr=7.38e-06 | epoch=1.0086
[train] step=473 | loss=0.1283 | lr=7.37e-06 | epoch=1.0107
[train] step=474 | loss=0.1243 | lr=7.37e-06 | epoch=1.0128
[train] step=475 | loss=0.1230 | lr=7.36e-06 | epoch=1.0150
[train] step=476 | loss=0.1353 | lr=7.35e-06 | epoch=1.0171
[train] step=477 | loss=0.1496 | lr=7.34e-06 | epoch=1.0193
[train] step=478 | loss=0.1074 | lr=7.33e-06 | epoch=1.0214
[train] step=479 | loss=0.1391 | lr=7.33e-06 | epoch=1.0235
[train] step=480 | loss=0.1070 | lr=7.32e-06 | epoch=1.0257
[train] step=481 | loss=0.1358 | lr=7.31e-06 | epoch=1.0278
[train] step=482 | loss=0.1434 | lr=7.30e-06 | epoch=1.0300
[train] step=483 | loss=0.1060 | lr=7.29e-06 | epoch=1.0321
[train] step=484 | loss=0.1312 | lr=7.29e-06 | epoch=1.0342
[train] step=485 | loss=0.1074 | lr=7.28e-06 | epoch=1.0364
[train] step=486 | loss=0.1268 | lr=7.27e-06 | epoch=1.0385
[train] step=487 | loss=0.1550 | lr=7.26e-06 | epoch=1.0407
[train] step=488 | loss=0.1390 | lr=7.25e-06 | epoch=1.0428
[train] step=489 | loss=0.1136 | lr=7.25e-06 | epoch=1.0449
[train] step=490 | loss=0.1236 | lr=7.24e-06 | epoch=1.0471
[train] step=491 | loss=0.1254 | lr=7.23e-06 | epoch=1.0492
[train] step=492 | loss=0.1400 | lr=7.22e-06 | epoch=1.0514
[train] step=493 | loss=0.1121 | lr=7.22e-06 | epoch=1.0535
[train] step=494 | loss=0.1302 | lr=7.21e-06 | epoch=1.0556
[train] step=495 | loss=0.1144 | lr=7.20e-06 | epoch=1.0578
[train] step=496 | loss=0.1304 | lr=7.19e-06 | epoch=1.0599
[train] step=497 | loss=0.1219 | lr=7.18e-06 | epoch=1.0621
[train] step=498 | loss=0.1525 | lr=7.18e-06 | epoch=1.0642
[train] step=499 | loss=0.1336 | lr=7.17e-06 | epoch=1.0663
[train] step=500 | loss=0.1333 | lr=7.16e-06 | epoch=1.0685
[train] step=501 | loss=0.1193 | lr=7.15e-06 | epoch=1.0706
[train] step=502 | loss=0.1185 | lr=7.14e-06 | epoch=1.0728
[train] step=503 | loss=0.1626 | lr=7.14e-06 | epoch=1.0749
[train] step=504 | loss=0.1417 | lr=7.13e-06 | epoch=1.0770
[train] step=505 | loss=0.1406 | lr=7.12e-06 | epoch=1.0792
[train] step=506 | loss=0.1184 | lr=7.11e-06 | epoch=1.0813
[train] step=507 | loss=0.1282 | lr=7.10e-06 | epoch=1.0835
[train] step=508 | loss=0.1343 | lr=7.10e-06 | epoch=1.0856
[train] step=509 | loss=0.1722 | lr=7.09e-06 | epoch=1.0877
[train] step=510 | loss=0.1402 | lr=7.08e-06 | epoch=1.0899
[train] step=511 | loss=0.1341 | lr=7.07e-06 | epoch=1.0920
[train] step=512 | loss=0.1268 | lr=7.06e-06 | epoch=1.0942
[train] step=513 | loss=0.1099 | lr=7.06e-06 | epoch=1.0963
[train] step=514 | loss=0.1233 | lr=7.05e-06 | epoch=1.0984
[train] step=515 | loss=0.1260 | lr=7.04e-06 | epoch=1.1006
[train] step=516 | loss=0.1425 | lr=7.03e-06 | epoch=1.1027
[train] step=517 | loss=0.1096 | lr=7.03e-06 | epoch=1.1049
[train] step=518 | loss=0.1499 | lr=7.02e-06 | epoch=1.1070
[train] step=519 | loss=0.1314 | lr=7.01e-06 | epoch=1.1091
[train] step=520 | loss=0.1276 | lr=7.00e-06 | epoch=1.1113
[train] step=521 | loss=0.1191 | lr=6.99e-06 | epoch=1.1134
[train] step=522 | loss=0.1494 | lr=6.99e-06 | epoch=1.1156
[train] step=523 | loss=0.1214 | lr=6.98e-06 | epoch=1.1177
[train] step=524 | loss=0.1251 | lr=6.97e-06 | epoch=1.1199
[train] step=525 | loss=0.1058 | lr=6.96e-06 | epoch=1.1220
[train] step=526 | loss=0.1264 | lr=6.95e-06 | epoch=1.1241
[train] step=527 | loss=0.1152 | lr=6.95e-06 | epoch=1.1263
[train] step=528 | loss=0.1414 | lr=6.94e-06 | epoch=1.1284
[train] step=529 | loss=0.1285 | lr=6.93e-06 | epoch=1.1306
[train] step=530 | loss=0.1278 | lr=6.92e-06 | epoch=1.1327
[train] step=531 | loss=0.1556 | lr=6.91e-06 | epoch=1.1348
[train] step=532 | loss=0.1327 | lr=6.91e-06 | epoch=1.1370
[train] step=533 | loss=0.1304 | lr=6.90e-06 | epoch=1.1391
[train] step=534 | loss=0.1273 | lr=6.89e-06 | epoch=1.1413
[train] step=535 | loss=0.1308 | lr=6.88e-06 | epoch=1.1434
[train] step=536 | loss=0.1353 | lr=6.88e-06 | epoch=1.1455
[train] step=537 | loss=0.1179 | lr=6.87e-06 | epoch=1.1477
[train] step=538 | loss=0.1310 | lr=6.86e-06 | epoch=1.1498
[train] step=539 | loss=0.1228 | lr=6.85e-06 | epoch=1.1520
[train] step=540 | loss=0.1074 | lr=6.84e-06 | epoch=1.1541
[train] step=541 | loss=0.0962 | lr=6.84e-06 | epoch=1.1562
[train] step=542 | loss=0.1368 | lr=6.83e-06 | epoch=1.1584
[train] step=543 | loss=0.1222 | lr=6.82e-06 | epoch=1.1605
[train] step=544 | loss=0.1039 | lr=6.81e-06 | epoch=1.1627
[train] step=545 | loss=0.1151 | lr=6.80e-06 | epoch=1.1648
[train] step=546 | loss=0.1090 | lr=6.80e-06 | epoch=1.1669
[train] step=547 | loss=0.1128 | lr=6.79e-06 | epoch=1.1691
[train] step=548 | loss=0.1200 | lr=6.78e-06 | epoch=1.1712
[train] step=549 | loss=0.0964 | lr=6.77e-06 | epoch=1.1734
[train] step=550 | loss=0.1149 | lr=6.76e-06 | epoch=1.1755
[train] step=551 | loss=0.1211 | lr=6.76e-06 | epoch=1.1776
[train] step=552 | loss=0.1235 | lr=6.75e-06 | epoch=1.1798
[train] step=553 | loss=0.1358 | lr=6.74e-06 | epoch=1.1819
[train] step=554 | loss=0.1138 | lr=6.73e-06 | epoch=1.1841
[train] step=555 | loss=0.1165 | lr=6.72e-06 | epoch=1.1862
[train] step=556 | loss=0.1132 | lr=6.72e-06 | epoch=1.1883
[train] step=557 | loss=0.1443 | lr=6.71e-06 | epoch=1.1905
[train] step=558 | loss=0.1238 | lr=6.70e-06 | epoch=1.1926
[train] step=559 | loss=0.1334 | lr=6.69e-06 | epoch=1.1948
[train] step=560 | loss=0.1228 | lr=6.69e-06 | epoch=1.1969
[train] step=561 | loss=0.1219 | lr=6.68e-06 | epoch=1.1990
[train] step=562 | loss=0.1236 | lr=6.67e-06 | epoch=1.2012
[train] step=563 | loss=0.1343 | lr=6.66e-06 | epoch=1.2033
[train] step=564 | loss=0.1164 | lr=6.65e-06 | epoch=1.2055
[train] step=565 | loss=0.1501 | lr=6.65e-06 | epoch=1.2076
[train] step=566 | loss=0.1261 | lr=6.64e-06 | epoch=1.2097
[train] step=567 | loss=0.1141 | lr=6.63e-06 | epoch=1.2119
[train] step=568 | loss=0.1108 | lr=6.62e-06 | epoch=1.2140
[train] step=569 | loss=0.1289 | lr=6.61e-06 | epoch=1.2162
[train] step=570 | loss=0.1115 | lr=6.61e-06 | epoch=1.2183
[train] step=571 | loss=0.1213 | lr=6.60e-06 | epoch=1.2204
[train] step=572 | loss=0.1300 | lr=6.59e-06 | epoch=1.2226
[train] step=573 | loss=0.1486 | lr=6.58e-06 | epoch=1.2247
[train] step=574 | loss=0.1141 | lr=6.57e-06 | epoch=1.2269
[train] step=575 | loss=0.1241 | lr=6.57e-06 | epoch=1.2290
[train] step=576 | loss=0.1278 | lr=6.56e-06 | epoch=1.2311
[train] step=577 | loss=0.1590 | lr=6.55e-06 | epoch=1.2333
[train] step=578 | loss=0.1288 | lr=6.54e-06 | epoch=1.2354
[train] step=579 | loss=0.1365 | lr=6.53e-06 | epoch=1.2376
[train] step=580 | loss=0.1162 | lr=6.53e-06 | epoch=1.2397
[train] step=581 | loss=0.1206 | lr=6.52e-06 | epoch=1.2418
[train] step=582 | loss=0.1173 | lr=6.51e-06 | epoch=1.2440
[train] step=583 | loss=0.1345 | lr=6.50e-06 | epoch=1.2461
[train] step=584 | loss=0.1189 | lr=6.50e-06 | epoch=1.2483
[train] step=585 | loss=0.1338 | lr=6.49e-06 | epoch=1.2504
[train] step=586 | loss=0.1095 | lr=6.48e-06 | epoch=1.2525
[train] step=587 | loss=0.1265 | lr=6.47e-06 | epoch=1.2547
[train] step=588 | loss=0.1459 | lr=6.46e-06 | epoch=1.2568
[train] step=589 | loss=0.1538 | lr=6.46e-06 | epoch=1.2590
[train] step=590 | loss=0.1428 | lr=6.45e-06 | epoch=1.2611
[train] step=591 | loss=0.1066 | lr=6.44e-06 | epoch=1.2632
[train] step=592 | loss=0.1322 | lr=6.43e-06 | epoch=1.2654
[train] step=593 | loss=0.1154 | lr=6.42e-06 | epoch=1.2675
[train] step=594 | loss=0.1123 | lr=6.42e-06 | epoch=1.2697
[train] step=595 | loss=0.1000 | lr=6.41e-06 | epoch=1.2718
[train] step=596 | loss=0.1188 | lr=6.40e-06 | epoch=1.2739
[train] step=597 | loss=0.1197 | lr=6.39e-06 | epoch=1.2761
[train] step=598 | loss=0.1241 | lr=6.38e-06 | epoch=1.2782
[train] step=599 | loss=0.1188 | lr=6.38e-06 | epoch=1.2804
[train] step=600 | loss=0.1334 | lr=6.37e-06 | epoch=1.2825
[train] step=601 | loss=0.1282 | lr=6.36e-06 | epoch=1.2846
[train] step=602 | loss=0.1124 | lr=6.35e-06 | epoch=1.2868
[train] step=603 | loss=0.1063 | lr=6.34e-06 | epoch=1.2889
[train] step=604 | loss=0.1184 | lr=6.34e-06 | epoch=1.2911
[train] step=605 | loss=0.1138 | lr=6.33e-06 | epoch=1.2932
[train] step=606 | loss=0.0984 | lr=6.32e-06 | epoch=1.2953
[train] step=607 | loss=0.1319 | lr=6.31e-06 | epoch=1.2975
[train] step=608 | loss=0.0962 | lr=6.31e-06 | epoch=1.2996
[train] step=609 | loss=0.1400 | lr=6.30e-06 | epoch=1.3018
[train] step=610 | loss=0.1322 | lr=6.29e-06 | epoch=1.3039
[train] step=611 | loss=0.0967 | lr=6.28e-06 | epoch=1.3060
[train] step=612 | loss=0.1262 | lr=6.27e-06 | epoch=1.3082
[train] step=613 | loss=0.1382 | lr=6.27e-06 | epoch=1.3103
[train] step=614 | loss=0.1199 | lr=6.26e-06 | epoch=1.3125
[train] step=615 | loss=0.1256 | lr=6.25e-06 | epoch=1.3146
[train] step=616 | loss=0.1144 | lr=6.24e-06 | epoch=1.3167
[train] step=617 | loss=0.0961 | lr=6.23e-06 | epoch=1.3189
[train] step=618 | loss=0.1321 | lr=6.23e-06 | epoch=1.3210
[train] step=619 | loss=0.1238 | lr=6.22e-06 | epoch=1.3232
[train] step=620 | loss=0.1189 | lr=6.21e-06 | epoch=1.3253
[train] step=621 | loss=0.1385 | lr=6.20e-06 | epoch=1.3274
[train] step=622 | loss=0.1142 | lr=6.19e-06 | epoch=1.3296
[train] step=623 | loss=0.1220 | lr=6.19e-06 | epoch=1.3317
[train] step=624 | loss=0.1234 | lr=6.18e-06 | epoch=1.3339
[train] step=625 | loss=0.1177 | lr=6.17e-06 | epoch=1.3360
[train] step=626 | loss=0.1086 | lr=6.16e-06 | epoch=1.3381
[train] step=627 | loss=0.1571 | lr=6.16e-06 | epoch=1.3403
[train] step=628 | loss=0.1094 | lr=6.15e-06 | epoch=1.3424
[train] step=629 | loss=0.0932 | lr=6.14e-06 | epoch=1.3446
[train] step=630 | loss=0.1285 | lr=6.13e-06 | epoch=1.3467
[train] step=631 | loss=0.1149 | lr=6.12e-06 | epoch=1.3488
[train] step=632 | loss=0.1250 | lr=6.12e-06 | epoch=1.3510
[train] step=633 | loss=0.1277 | lr=6.11e-06 | epoch=1.3531
[train] step=634 | loss=0.1327 | lr=6.10e-06 | epoch=1.3553
[train] step=635 | loss=0.1201 | lr=6.09e-06 | epoch=1.3574
[train] step=636 | loss=0.1186 | lr=6.08e-06 | epoch=1.3596
[train] step=637 | loss=0.1147 | lr=6.08e-06 | epoch=1.3617
[train] step=638 | loss=0.1339 | lr=6.07e-06 | epoch=1.3638
[train] step=639 | loss=0.1299 | lr=6.06e-06 | epoch=1.3660
[train] step=640 | loss=0.0998 | lr=6.05e-06 | epoch=1.3681
[train] step=641 | loss=0.1199 | lr=6.04e-06 | epoch=1.3703
[train] step=642 | loss=0.1175 | lr=6.04e-06 | epoch=1.3724
[train] step=643 | loss=0.1428 | lr=6.03e-06 | epoch=1.3745
[train] step=644 | loss=0.1381 | lr=6.02e-06 | epoch=1.3767
[train] step=645 | loss=0.1374 | lr=6.01e-06 | epoch=1.3788
[train] step=646 | loss=0.1182 | lr=6.00e-06 | epoch=1.3810
[train] step=647 | loss=0.1032 | lr=6.00e-06 | epoch=1.3831
[train] step=648 | loss=0.1220 | lr=5.99e-06 | epoch=1.3852
[train] step=649 | loss=0.0814 | lr=5.98e-06 | epoch=1.3874
[train] step=650 | loss=0.1024 | lr=5.97e-06 | epoch=1.3895
[train] step=651 | loss=0.1027 | lr=5.97e-06 | epoch=1.3917
[train] step=652 | loss=0.1192 | lr=5.96e-06 | epoch=1.3938
[train] step=653 | loss=0.1330 | lr=5.95e-06 | epoch=1.3959
[train] step=654 | loss=0.0997 | lr=5.94e-06 | epoch=1.3981
[train] step=655 | loss=0.1032 | lr=5.93e-06 | epoch=1.4002
[train] step=656 | loss=0.1300 | lr=5.93e-06 | epoch=1.4024
[train] step=657 | loss=0.1155 | lr=5.92e-06 | epoch=1.4045
[train] step=658 | loss=0.1225 | lr=5.91e-06 | epoch=1.4066
[train] step=659 | loss=0.1306 | lr=5.90e-06 | epoch=1.4088
[train] step=660 | loss=0.1188 | lr=5.89e-06 | epoch=1.4109
[train] step=661 | loss=0.1649 | lr=5.89e-06 | epoch=1.4131
[train] step=662 | loss=0.1241 | lr=5.88e-06 | epoch=1.4152
[train] step=663 | loss=0.1367 | lr=5.87e-06 | epoch=1.4173
[train] step=664 | loss=0.1284 | lr=5.86e-06 | epoch=1.4195
[train] step=665 | loss=0.1136 | lr=5.85e-06 | epoch=1.4216
[train] step=666 | loss=0.1030 | lr=5.85e-06 | epoch=1.4238
[train] step=667 | loss=0.1105 | lr=5.84e-06 | epoch=1.4259
[train] step=668 | loss=0.1181 | lr=5.83e-06 | epoch=1.4280
[train] step=669 | loss=0.1203 | lr=5.82e-06 | epoch=1.4302
[train] step=670 | loss=0.1273 | lr=5.81e-06 | epoch=1.4323
[train] step=671 | loss=0.1222 | lr=5.81e-06 | epoch=1.4345
[train] step=672 | loss=0.1009 | lr=5.80e-06 | epoch=1.4366
[train] step=673 | loss=0.1457 | lr=5.79e-06 | epoch=1.4387
[train] step=674 | loss=0.1278 | lr=5.78e-06 | epoch=1.4409
[train] step=675 | loss=0.1039 | lr=5.78e-06 | epoch=1.4430
[train] step=676 | loss=0.1197 | lr=5.77e-06 | epoch=1.4452
[train] step=677 | loss=0.1099 | lr=5.76e-06 | epoch=1.4473
[train] step=678 | loss=0.1049 | lr=5.75e-06 | epoch=1.4494
[train] step=679 | loss=0.1082 | lr=5.74e-06 | epoch=1.4516
[train] step=680 | loss=0.1121 | lr=5.74e-06 | epoch=1.4537
[train] step=681 | loss=0.1275 | lr=5.73e-06 | epoch=1.4559
[train] step=682 | loss=0.1173 | lr=5.72e-06 | epoch=1.4580
[train] step=683 | loss=0.1105 | lr=5.71e-06 | epoch=1.4601
[train] step=684 | loss=0.1190 | lr=5.70e-06 | epoch=1.4623
[train] step=685 | loss=0.1374 | lr=5.70e-06 | epoch=1.4644
[train] step=686 | loss=0.1203 | lr=5.69e-06 | epoch=1.4666
[train] step=687 | loss=0.1124 | lr=5.68e-06 | epoch=1.4687
[train] step=688 | loss=0.1490 | lr=5.67e-06 | epoch=1.4708
[train] step=689 | loss=0.1209 | lr=5.66e-06 | epoch=1.4730
[train] step=690 | loss=0.1342 | lr=5.66e-06 | epoch=1.4751
[train] step=691 | loss=0.0954 | lr=5.65e-06 | epoch=1.4773
[train] step=692 | loss=0.1241 | lr=5.64e-06 | epoch=1.4794
[train] step=693 | loss=0.1109 | lr=5.63e-06 | epoch=1.4815
[train] step=694 | loss=0.1242 | lr=5.63e-06 | epoch=1.4837
[train] step=695 | loss=0.1028 | lr=5.62e-06 | epoch=1.4858
[train] step=696 | loss=0.1312 | lr=5.61e-06 | epoch=1.4880
[train] step=697 | loss=0.1420 | lr=5.60e-06 | epoch=1.4901
[train] step=698 | loss=0.1312 | lr=5.59e-06 | epoch=1.4922
[train] step=699 | loss=0.1358 | lr=5.59e-06 | epoch=1.4944

Saving model checkpoint to output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-699
2026-04-06 01:17:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:17:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 01:17:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:17:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-699\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-699\tokenizer_config.json

[train] step=700 | loss=0.1107 | lr=5.58e-06 | epoch=1.4965
[train] step=701 | loss=0.1369 | lr=5.57e-06 | epoch=1.4987
[train] step=702 | loss=0.1109 | lr=5.56e-06 | epoch=1.5008
[train] step=703 | loss=0.1150 | lr=5.55e-06 | epoch=1.5029
[train] step=704 | loss=0.1094 | lr=5.55e-06 | epoch=1.5051
[train] step=705 | loss=0.1372 | lr=5.54e-06 | epoch=1.5072
[train] step=706 | loss=0.1316 | lr=5.53e-06 | epoch=1.5094
[train] step=707 | loss=0.1252 | lr=5.52e-06 | epoch=1.5115
[train] step=708 | loss=0.1134 | lr=5.51e-06 | epoch=1.5136
[train] step=709 | loss=0.1011 | lr=5.51e-06 | epoch=1.5158
[train] step=710 | loss=0.1223 | lr=5.50e-06 | epoch=1.5179
[train] step=711 | loss=0.1162 | lr=5.49e-06 | epoch=1.5201
[train] step=712 | loss=0.1168 | lr=5.48e-06 | epoch=1.5222
[train] step=713 | loss=0.1029 | lr=5.47e-06 | epoch=1.5243
[train] step=714 | loss=0.0991 | lr=5.47e-06 | epoch=1.5265
[train] step=715 | loss=0.0965 | lr=5.46e-06 | epoch=1.5286
[train] step=716 | loss=0.1213 | lr=5.45e-06 | epoch=1.5308
[train] step=717 | loss=0.1249 | lr=5.44e-06 | epoch=1.5329
[train] step=718 | loss=0.1241 | lr=5.44e-06 | epoch=1.5350
[train] step=719 | loss=0.0898 | lr=5.43e-06 | epoch=1.5372
[train] step=720 | loss=0.1265 | lr=5.42e-06 | epoch=1.5393
[train] step=721 | loss=0.1236 | lr=5.41e-06 | epoch=1.5415
[train] step=722 | loss=0.1134 | lr=5.40e-06 | epoch=1.5436
[train] step=723 | loss=0.1307 | lr=5.40e-06 | epoch=1.5457
[train] step=724 | loss=0.1056 | lr=5.39e-06 | epoch=1.5479
[train] step=725 | loss=0.1795 | lr=5.38e-06 | epoch=1.5500
[train] step=726 | loss=0.1209 | lr=5.37e-06 | epoch=1.5522
[train] step=727 | loss=0.1168 | lr=5.36e-06 | epoch=1.5543
[train] step=728 | loss=0.1111 | lr=5.36e-06 | epoch=1.5564
[train] step=729 | loss=0.1221 | lr=5.35e-06 | epoch=1.5586
[train] step=730 | loss=0.1233 | lr=5.34e-06 | epoch=1.5607
[train] step=731 | loss=0.1211 | lr=5.33e-06 | epoch=1.5629
[train] step=732 | loss=0.1331 | lr=5.32e-06 | epoch=1.5650
[train] step=733 | loss=0.0959 | lr=5.32e-06 | epoch=1.5671
[train] step=734 | loss=0.1150 | lr=5.31e-06 | epoch=1.5693
[train] step=735 | loss=0.1179 | lr=5.30e-06 | epoch=1.5714
[train] step=736 | loss=0.1162 | lr=5.29e-06 | epoch=1.5736
[train] step=737 | loss=0.1137 | lr=5.28e-06 | epoch=1.5757
[train] step=738 | loss=0.1211 | lr=5.28e-06 | epoch=1.5778
[train] step=739 | loss=0.1197 | lr=5.27e-06 | epoch=1.5800
[train] step=740 | loss=0.1410 | lr=5.26e-06 | epoch=1.5821
[train] step=741 | loss=0.1260 | lr=5.25e-06 | epoch=1.5843
[train] step=742 | loss=0.1342 | lr=5.25e-06 | epoch=1.5864
[train] step=743 | loss=0.1219 | lr=5.24e-06 | epoch=1.5886
[train] step=744 | loss=0.1287 | lr=5.23e-06 | epoch=1.5907
[train] step=745 | loss=0.0980 | lr=5.22e-06 | epoch=1.5928
[train] step=746 | loss=0.1187 | lr=5.21e-06 | epoch=1.5950
[train] step=747 | loss=0.1431 | lr=5.21e-06 | epoch=1.5971
[train] step=748 | loss=0.1049 | lr=5.20e-06 | epoch=1.5993
[train] step=749 | loss=0.1107 | lr=5.19e-06 | epoch=1.6014
[train] step=750 | loss=0.1237 | lr=5.18e-06 | epoch=1.6035
[train] step=751 | loss=0.1251 | lr=5.17e-06 | epoch=1.6057
[train] step=752 | loss=0.1164 | lr=5.17e-06 | epoch=1.6078
[train] step=753 | loss=0.1359 | lr=5.16e-06 | epoch=1.6100
[train] step=754 | loss=0.1241 | lr=5.15e-06 | epoch=1.6121
[train] step=755 | loss=0.1255 | lr=5.14e-06 | epoch=1.6142
[train] step=756 | loss=0.1255 | lr=5.13e-06 | epoch=1.6164
[train] step=757 | loss=0.1080 | lr=5.13e-06 | epoch=1.6185
[train] step=758 | loss=0.1087 | lr=5.12e-06 | epoch=1.6207
[train] step=759 | loss=0.1047 | lr=5.11e-06 | epoch=1.6228
[train] step=760 | loss=0.0930 | lr=5.10e-06 | epoch=1.6249
[train] step=761 | loss=0.1105 | lr=5.09e-06 | epoch=1.6271
[train] step=762 | loss=0.1305 | lr=5.09e-06 | epoch=1.6292
[train] step=763 | loss=0.1279 | lr=5.08e-06 | epoch=1.6314
[train] step=764 | loss=0.1475 | lr=5.07e-06 | epoch=1.6335
[train] step=765 | loss=0.1152 | lr=5.06e-06 | epoch=1.6356
[train] step=766 | loss=0.1429 | lr=5.06e-06 | epoch=1.6378
[train] step=767 | loss=0.1416 | lr=5.05e-06 | epoch=1.6399
[train] step=768 | loss=0.1035 | lr=5.04e-06 | epoch=1.6421
[train] step=769 | loss=0.1259 | lr=5.03e-06 | epoch=1.6442
[train] step=770 | loss=0.0967 | lr=5.02e-06 | epoch=1.6463
[train] step=771 | loss=0.1221 | lr=5.02e-06 | epoch=1.6485
[train] step=772 | loss=0.1051 | lr=5.01e-06 | epoch=1.6506
[train] step=773 | loss=0.1123 | lr=5.00e-06 | epoch=1.6528
[train] step=774 | loss=0.0976 | lr=4.99e-06 | epoch=1.6549
[train] step=775 | loss=0.1256 | lr=4.98e-06 | epoch=1.6570
[train] step=776 | loss=0.1031 | lr=4.98e-06 | epoch=1.6592
[train] step=777 | loss=0.1246 | lr=4.97e-06 | epoch=1.6613
[train] step=778 | loss=0.1238 | lr=4.96e-06 | epoch=1.6635
[train] step=779 | loss=0.1253 | lr=4.95e-06 | epoch=1.6656
[train] step=780 | loss=0.1435 | lr=4.94e-06 | epoch=1.6677
[train] step=781 | loss=0.1078 | lr=4.94e-06 | epoch=1.6699
[train] step=782 | loss=0.1082 | lr=4.93e-06 | epoch=1.6720
[train] step=783 | loss=0.1156 | lr=4.92e-06 | epoch=1.6742
[train] step=784 | loss=0.1253 | lr=4.91e-06 | epoch=1.6763
[train] step=785 | loss=0.0996 | lr=4.91e-06 | epoch=1.6784
[train] step=786 | loss=0.1156 | lr=4.90e-06 | epoch=1.6806
[train] step=787 | loss=0.1144 | lr=4.89e-06 | epoch=1.6827
[train] step=788 | loss=0.1296 | lr=4.88e-06 | epoch=1.6849
[train] step=789 | loss=0.1261 | lr=4.87e-06 | epoch=1.6870
[train] step=790 | loss=0.1207 | lr=4.87e-06 | epoch=1.6891
[train] step=791 | loss=0.1089 | lr=4.86e-06 | epoch=1.6913
[train] step=792 | loss=0.1179 | lr=4.85e-06 | epoch=1.6934
[train] step=793 | loss=0.1315 | lr=4.84e-06 | epoch=1.6956
[train] step=794 | loss=0.1212 | lr=4.83e-06 | epoch=1.6977
[train] step=795 | loss=0.1149 | lr=4.83e-06 | epoch=1.6998
[train] step=796 | loss=0.1416 | lr=4.82e-06 | epoch=1.7020
[train] step=797 | loss=0.1247 | lr=4.81e-06 | epoch=1.7041
[train] step=798 | loss=0.1242 | lr=4.80e-06 | epoch=1.7063
[train] step=799 | loss=0.1239 | lr=4.79e-06 | epoch=1.7084
[train] step=800 | loss=0.1179 | lr=4.79e-06 | epoch=1.7105
[train] step=801 | loss=0.1362 | lr=4.78e-06 | epoch=1.7127
[train] step=802 | loss=0.1226 | lr=4.77e-06 | epoch=1.7148
[train] step=803 | loss=0.1412 | lr=4.76e-06 | epoch=1.7170
[train] step=804 | loss=0.1130 | lr=4.75e-06 | epoch=1.7191
[train] step=805 | loss=0.1142 | lr=4.75e-06 | epoch=1.7212
[train] step=806 | loss=0.1156 | lr=4.74e-06 | epoch=1.7234
[train] step=807 | loss=0.1260 | lr=4.73e-06 | epoch=1.7255
[train] step=808 | loss=0.0911 | lr=4.72e-06 | epoch=1.7277
[train] step=809 | loss=0.1115 | lr=4.72e-06 | epoch=1.7298
[train] step=810 | loss=0.1288 | lr=4.71e-06 | epoch=1.7319
[train] step=811 | loss=0.1100 | lr=4.70e-06 | epoch=1.7341
[train] step=812 | loss=0.1321 | lr=4.69e-06 | epoch=1.7362
[train] step=813 | loss=0.1122 | lr=4.68e-06 | epoch=1.7384
[train] step=814 | loss=0.1041 | lr=4.68e-06 | epoch=1.7405
[train] step=815 | loss=0.1027 | lr=4.67e-06 | epoch=1.7426
[train] step=816 | loss=0.1410 | lr=4.66e-06 | epoch=1.7448
[train] step=817 | loss=0.1217 | lr=4.65e-06 | epoch=1.7469
[train] step=818 | loss=0.1385 | lr=4.64e-06 | epoch=1.7491
[train] step=819 | loss=0.1069 | lr=4.64e-06 | epoch=1.7512
[train] step=820 | loss=0.1222 | lr=4.63e-06 | epoch=1.7533
[train] step=821 | loss=0.1324 | lr=4.62e-06 | epoch=1.7555
[train] step=822 | loss=0.1087 | lr=4.61e-06 | epoch=1.7576
[train] step=823 | loss=0.1297 | lr=4.60e-06 | epoch=1.7598
[train] step=824 | loss=0.1002 | lr=4.60e-06 | epoch=1.7619
[train] step=825 | loss=0.1135 | lr=4.59e-06 | epoch=1.7640
[train] step=826 | loss=0.1063 | lr=4.58e-06 | epoch=1.7662
[train] step=827 | loss=0.1094 | lr=4.57e-06 | epoch=1.7683
[train] step=828 | loss=0.1170 | lr=4.56e-06 | epoch=1.7705
[train] step=829 | loss=0.1010 | lr=4.56e-06 | epoch=1.7726
[train] step=830 | loss=0.1212 | lr=4.55e-06 | epoch=1.7747
[train] step=831 | loss=0.1073 | lr=4.54e-06 | epoch=1.7769
[train] step=832 | loss=0.1353 | lr=4.53e-06 | epoch=1.7790
[train] step=833 | loss=0.1377 | lr=4.53e-06 | epoch=1.7812
[train] step=834 | loss=0.1108 | lr=4.52e-06 | epoch=1.7833
[train] step=835 | loss=0.1420 | lr=4.51e-06 | epoch=1.7854
[train] step=836 | loss=0.1073 | lr=4.50e-06 | epoch=1.7876
[train] step=837 | loss=0.1080 | lr=4.49e-06 | epoch=1.7897
[train] step=838 | loss=0.1415 | lr=4.49e-06 | epoch=1.7919
[train] step=839 | loss=0.1215 | lr=4.48e-06 | epoch=1.7940
[train] step=840 | loss=0.1090 | lr=4.47e-06 | epoch=1.7961
[train] step=841 | loss=0.1065 | lr=4.46e-06 | epoch=1.7983
[train] step=842 | loss=0.1258 | lr=4.45e-06 | epoch=1.8004
[train] step=843 | loss=0.0885 | lr=4.45e-06 | epoch=1.8026
[train] step=844 | loss=0.1074 | lr=4.44e-06 | epoch=1.8047
[train] step=845 | loss=0.1167 | lr=4.43e-06 | epoch=1.8068
[train] step=846 | loss=0.1209 | lr=4.42e-06 | epoch=1.8090
[train] step=847 | loss=0.1048 | lr=4.41e-06 | epoch=1.8111
[train] step=848 | loss=0.0884 | lr=4.41e-06 | epoch=1.8133
[train] step=849 | loss=0.1067 | lr=4.40e-06 | epoch=1.8154
[train] step=850 | loss=0.1254 | lr=4.39e-06 | epoch=1.8175
[train] step=851 | loss=0.1219 | lr=4.38e-06 | epoch=1.8197
[train] step=852 | loss=0.1042 | lr=4.38e-06 | epoch=1.8218
[train] step=853 | loss=0.1349 | lr=4.37e-06 | epoch=1.8240
[train] step=854 | loss=0.1166 | lr=4.36e-06 | epoch=1.8261
[train] step=855 | loss=0.1115 | lr=4.35e-06 | epoch=1.8283
[train] step=856 | loss=0.1303 | lr=4.34e-06 | epoch=1.8304
[train] step=857 | loss=0.1132 | lr=4.34e-06 | epoch=1.8325
[train] step=858 | loss=0.1011 | lr=4.33e-06 | epoch=1.8347
[train] step=859 | loss=0.1184 | lr=4.32e-06 | epoch=1.8368
[train] step=860 | loss=0.1317 | lr=4.31e-06 | epoch=1.8390
[train] step=861 | loss=0.1124 | lr=4.30e-06 | epoch=1.8411
[train] step=862 | loss=0.1044 | lr=4.30e-06 | epoch=1.8432
[train] step=863 | loss=0.1029 | lr=4.29e-06 | epoch=1.8454
[train] step=864 | loss=0.1221 | lr=4.28e-06 | epoch=1.8475
[train] step=865 | loss=0.1109 | lr=4.27e-06 | epoch=1.8497
[train] step=866 | loss=0.1124 | lr=4.26e-06 | epoch=1.8518
[train] step=867 | loss=0.1115 | lr=4.26e-06 | epoch=1.8539
[train] step=868 | loss=0.0928 | lr=4.25e-06 | epoch=1.8561
[train] step=869 | loss=0.1118 | lr=4.24e-06 | epoch=1.8582
[train] step=870 | loss=0.1317 | lr=4.23e-06 | epoch=1.8604
[train] step=871 | loss=0.1348 | lr=4.22e-06 | epoch=1.8625
[train] step=872 | loss=0.1540 | lr=4.22e-06 | epoch=1.8646
[train] step=873 | loss=0.1154 | lr=4.21e-06 | epoch=1.8668
[train] step=874 | loss=0.1219 | lr=4.20e-06 | epoch=1.8689
[train] step=875 | loss=0.1071 | lr=4.19e-06 | epoch=1.8711
[train] step=876 | loss=0.1239 | lr=4.19e-06 | epoch=1.8732
[train] step=877 | loss=0.1433 | lr=4.18e-06 | epoch=1.8753
[train] step=878 | loss=0.1146 | lr=4.17e-06 | epoch=1.8775
[train] step=879 | loss=0.1091 | lr=4.16e-06 | epoch=1.8796
[train] step=880 | loss=0.1560 | lr=4.15e-06 | epoch=1.8818
[train] step=881 | loss=0.1048 | lr=4.15e-06 | epoch=1.8839
[train] step=882 | loss=0.1318 | lr=4.14e-06 | epoch=1.8860
[train] step=883 | loss=0.1131 | lr=4.13e-06 | epoch=1.8882
[train] step=884 | loss=0.1286 | lr=4.12e-06 | epoch=1.8903
[train] step=885 | loss=0.1397 | lr=4.11e-06 | epoch=1.8925
[train] step=886 | loss=0.1144 | lr=4.11e-06 | epoch=1.8946
[train] step=887 | loss=0.1379 | lr=4.10e-06 | epoch=1.8967
[train] step=888 | loss=0.1500 | lr=4.09e-06 | epoch=1.8989
[train] step=889 | loss=0.1418 | lr=4.08e-06 | epoch=1.9010
[train] step=890 | loss=0.1202 | lr=4.07e-06 | epoch=1.9032
[train] step=891 | loss=0.1116 | lr=4.07e-06 | epoch=1.9053
[train] step=892 | loss=0.1073 | lr=4.06e-06 | epoch=1.9074
[train] step=893 | loss=0.1205 | lr=4.05e-06 | epoch=1.9096
[train] step=894 | loss=0.1380 | lr=4.04e-06 | epoch=1.9117
[train] step=895 | loss=0.1317 | lr=4.03e-06 | epoch=1.9139
[train] step=896 | loss=0.0991 | lr=4.03e-06 | epoch=1.9160
[train] step=897 | loss=0.1239 | lr=4.02e-06 | epoch=1.9181
[train] step=898 | loss=0.1242 | lr=4.01e-06 | epoch=1.9203
[train] step=899 | loss=0.1176 | lr=4.00e-06 | epoch=1.9224
[train] step=900 | loss=0.1225 | lr=4.00e-06 | epoch=1.9246
[train] step=901 | loss=0.1140 | lr=3.99e-06 | epoch=1.9267
[train] step=902 | loss=0.1214 | lr=3.98e-06 | epoch=1.9288
[train] step=903 | loss=0.1054 | lr=3.97e-06 | epoch=1.9310
[train] step=904 | loss=0.1143 | lr=3.96e-06 | epoch=1.9331
[train] step=905 | loss=0.1279 | lr=3.96e-06 | epoch=1.9353
[train] step=906 | loss=0.1398 | lr=3.95e-06 | epoch=1.9374
[train] step=907 | loss=0.1166 | lr=3.94e-06 | epoch=1.9395
[train] step=908 | loss=0.1053 | lr=3.93e-06 | epoch=1.9417
[train] step=909 | loss=0.1357 | lr=3.92e-06 | epoch=1.9438
[train] step=910 | loss=0.1220 | lr=3.92e-06 | epoch=1.9460
[train] step=911 | loss=0.1206 | lr=3.91e-06 | epoch=1.9481
[train] step=912 | loss=0.1165 | lr=3.90e-06 | epoch=1.9502
[train] step=913 | loss=0.1250 | lr=3.89e-06 | epoch=1.9524
[train] step=914 | loss=0.0940 | lr=3.88e-06 | epoch=1.9545
[train] step=915 | loss=0.1102 | lr=3.88e-06 | epoch=1.9567
[train] step=916 | loss=0.1130 | lr=3.87e-06 | epoch=1.9588
[train] step=917 | loss=0.0969 | lr=3.86e-06 | epoch=1.9609
[train] step=918 | loss=0.1281 | lr=3.85e-06 | epoch=1.9631
[train] step=919 | loss=0.1218 | lr=3.84e-06 | epoch=1.9652
[train] step=920 | loss=0.1054 | lr=3.84e-06 | epoch=1.9674
[train] step=921 | loss=0.1124 | lr=3.83e-06 | epoch=1.9695
[train] step=922 | loss=0.1187 | lr=3.82e-06 | epoch=1.9716
[train] step=923 | loss=0.1009 | lr=3.81e-06 | epoch=1.9738
[train] step=924 | loss=0.1085 | lr=3.81e-06 | epoch=1.9759
[train] step=925 | loss=0.1191 | lr=3.80e-06 | epoch=1.9781
[train] step=926 | loss=0.1131 | lr=3.79e-06 | epoch=1.9802
[train] step=927 | loss=0.1238 | lr=3.78e-06 | epoch=1.9823
[train] step=928 | loss=0.1245 | lr=3.77e-06 | epoch=1.9845
[train] step=929 | loss=0.1311 | lr=3.77e-06 | epoch=1.9866
[train] step=930 | loss=0.1241 | lr=3.76e-06 | epoch=1.9888
[train] step=931 | loss=0.1022 | lr=3.75e-06 | epoch=1.9909
[train] step=932 | loss=0.1247 | lr=3.74e-06 | epoch=1.9930

Saving model checkpoint to output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-932
2026-04-06 01:27:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:27:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 01:27:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:27:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-932\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-932\tokenizer_config.json

[train] step=933 | loss=0.1509 | lr=3.73e-06 | epoch=1.9952
[train] step=934 | loss=0.1220 | lr=3.73e-06 | epoch=1.9973
[train] step=935 | loss=0.1247 | lr=3.72e-06 | epoch=1.9995
[train] step=936 | loss=0.0496 | lr=3.71e-06 | epoch=2.0000
[train] step=937 | loss=0.1107 | lr=3.70e-06 | epoch=2.0021
[train] step=938 | loss=0.1084 | lr=3.69e-06 | epoch=2.0043
[train] step=939 | loss=0.0881 | lr=3.69e-06 | epoch=2.0064
[train] step=940 | loss=0.1146 | lr=3.68e-06 | epoch=2.0086
[train] step=941 | loss=0.1242 | lr=3.67e-06 | epoch=2.0107
[train] step=942 | loss=0.1221 | lr=3.66e-06 | epoch=2.0128
[train] step=943 | loss=0.1218 | lr=3.66e-06 | epoch=2.0150
[train] step=944 | loss=0.1241 | lr=3.65e-06 | epoch=2.0171
[train] step=945 | loss=0.1236 | lr=3.64e-06 | epoch=2.0193
[train] step=946 | loss=0.1275 | lr=3.63e-06 | epoch=2.0214
[train] step=947 | loss=0.1180 | lr=3.62e-06 | epoch=2.0235
[train] step=948 | loss=0.1147 | lr=3.62e-06 | epoch=2.0257
[train] step=949 | loss=0.1385 | lr=3.61e-06 | epoch=2.0278
[train] step=950 | loss=0.0976 | lr=3.60e-06 | epoch=2.0300
[train] step=951 | loss=0.1185 | lr=3.59e-06 | epoch=2.0321
[train] step=952 | loss=0.1294 | lr=3.58e-06 | epoch=2.0342
[train] step=953 | loss=0.1210 | lr=3.58e-06 | epoch=2.0364
[train] step=954 | loss=0.1083 | lr=3.57e-06 | epoch=2.0385
[train] step=955 | loss=0.1657 | lr=3.56e-06 | epoch=2.0407
[train] step=956 | loss=0.1100 | lr=3.55e-06 | epoch=2.0428
[train] step=957 | loss=0.0979 | lr=3.54e-06 | epoch=2.0449
[train] step=958 | loss=0.1374 | lr=3.54e-06 | epoch=2.0471
[train] step=959 | loss=0.1072 | lr=3.53e-06 | epoch=2.0492
[train] step=960 | loss=0.1164 | lr=3.52e-06 | epoch=2.0514
[train] step=961 | loss=0.1113 | lr=3.51e-06 | epoch=2.0535
[train] step=962 | loss=0.1133 | lr=3.50e-06 | epoch=2.0556
[train] step=963 | loss=0.1261 | lr=3.50e-06 | epoch=2.0578
[train] step=964 | loss=0.0971 | lr=3.49e-06 | epoch=2.0599
[train] step=965 | loss=0.1101 | lr=3.48e-06 | epoch=2.0621
[train] step=966 | loss=0.1312 | lr=3.47e-06 | epoch=2.0642
[train] step=967 | loss=0.1073 | lr=3.47e-06 | epoch=2.0663
[train] step=968 | loss=0.1314 | lr=3.46e-06 | epoch=2.0685
[train] step=969 | loss=0.1213 | lr=3.45e-06 | epoch=2.0706
[train] step=970 | loss=0.1197 | lr=3.44e-06 | epoch=2.0728
[train] step=971 | loss=0.1170 | lr=3.43e-06 | epoch=2.0749
[train] step=972 | loss=0.1397 | lr=3.43e-06 | epoch=2.0770
[train] step=973 | loss=0.1194 | lr=3.42e-06 | epoch=2.0792
[train] step=974 | loss=0.1443 | lr=3.41e-06 | epoch=2.0813
[train] step=975 | loss=0.1095 | lr=3.40e-06 | epoch=2.0835
[train] step=976 | loss=0.1067 | lr=3.39e-06 | epoch=2.0856
[train] step=977 | loss=0.1094 | lr=3.39e-06 | epoch=2.0877
[train] step=978 | loss=0.1045 | lr=3.38e-06 | epoch=2.0899
[train] step=979 | loss=0.1016 | lr=3.37e-06 | epoch=2.0920
[train] step=980 | loss=0.1068 | lr=3.36e-06 | epoch=2.0942
[train] step=981 | loss=0.1237 | lr=3.35e-06 | epoch=2.0963
[train] step=982 | loss=0.1270 | lr=3.35e-06 | epoch=2.0984
[train] step=983 | loss=0.1182 | lr=3.34e-06 | epoch=2.1006
[train] step=984 | loss=0.1050 | lr=3.33e-06 | epoch=2.1027
[train] step=985 | loss=0.1287 | lr=3.32e-06 | epoch=2.1049
[train] step=986 | loss=0.1230 | lr=3.31e-06 | epoch=2.1070
[train] step=987 | loss=0.1388 | lr=3.31e-06 | epoch=2.1091
[train] step=988 | loss=0.1038 | lr=3.30e-06 | epoch=2.1113
[train] step=989 | loss=0.1403 | lr=3.29e-06 | epoch=2.1134
[train] step=990 | loss=0.1149 | lr=3.28e-06 | epoch=2.1156
[train] step=991 | loss=0.1126 | lr=3.28e-06 | epoch=2.1177
[train] step=992 | loss=0.1266 | lr=3.27e-06 | epoch=2.1199
[train] step=993 | loss=0.0854 | lr=3.26e-06 | epoch=2.1220
[train] step=994 | loss=0.1148 | lr=3.25e-06 | epoch=2.1241
[train] step=995 | loss=0.1328 | lr=3.24e-06 | epoch=2.1263
[train] step=996 | loss=0.1087 | lr=3.24e-06 | epoch=2.1284
[train] step=997 | loss=0.1098 | lr=3.23e-06 | epoch=2.1306
[train] step=998 | loss=0.1146 | lr=3.22e-06 | epoch=2.1327
[train] step=999 | loss=0.1257 | lr=3.21e-06 | epoch=2.1348
[train] step=1000 | loss=0.1172 | lr=3.20e-06 | epoch=2.1370
[train] step=1001 | loss=0.1012 | lr=3.20e-06 | epoch=2.1391
[train] step=1002 | loss=0.1084 | lr=3.19e-06 | epoch=2.1413
[train] step=1003 | loss=0.1063 | lr=3.18e-06 | epoch=2.1434
[train] step=1004 | loss=0.1135 | lr=3.17e-06 | epoch=2.1455
[train] step=1005 | loss=0.1216 | lr=3.16e-06 | epoch=2.1477
[train] step=1006 | loss=0.1137 | lr=3.16e-06 | epoch=2.1498
[train] step=1007 | loss=0.1187 | lr=3.15e-06 | epoch=2.1520
[train] step=1008 | loss=0.1057 | lr=3.14e-06 | epoch=2.1541
[train] step=1009 | loss=0.1148 | lr=3.13e-06 | epoch=2.1562
[train] step=1010 | loss=0.0934 | lr=3.13e-06 | epoch=2.1584
[train] step=1011 | loss=0.1528 | lr=3.12e-06 | epoch=2.1605
[train] step=1012 | loss=0.1297 | lr=3.11e-06 | epoch=2.1627
[train] step=1013 | loss=0.1234 | lr=3.10e-06 | epoch=2.1648
[train] step=1014 | loss=0.1051 | lr=3.09e-06 | epoch=2.1669
[train] step=1015 | loss=0.1116 | lr=3.09e-06 | epoch=2.1691
[train] step=1016 | loss=0.1158 | lr=3.08e-06 | epoch=2.1712
[train] step=1017 | loss=0.1318 | lr=3.07e-06 | epoch=2.1734
[train] step=1018 | loss=0.1116 | lr=3.06e-06 | epoch=2.1755
[train] step=1019 | loss=0.1354 | lr=3.05e-06 | epoch=2.1776
[train] step=1020 | loss=0.1043 | lr=3.05e-06 | epoch=2.1798
[train] step=1021 | loss=0.1058 | lr=3.04e-06 | epoch=2.1819
[train] step=1022 | loss=0.1329 | lr=3.03e-06 | epoch=2.1841
[train] step=1023 | loss=0.1090 | lr=3.02e-06 | epoch=2.1862
[train] step=1024 | loss=0.1131 | lr=3.01e-06 | epoch=2.1883
[train] step=1025 | loss=0.1149 | lr=3.01e-06 | epoch=2.1905
[train] step=1026 | loss=0.1353 | lr=3.00e-06 | epoch=2.1926
[train] step=1027 | loss=0.1289 | lr=2.99e-06 | epoch=2.1948
[train] step=1028 | loss=0.1165 | lr=2.98e-06 | epoch=2.1969
[train] step=1029 | loss=0.1484 | lr=2.97e-06 | epoch=2.1990
[train] step=1030 | loss=0.1158 | lr=2.97e-06 | epoch=2.2012
[train] step=1031 | loss=0.1326 | lr=2.96e-06 | epoch=2.2033
[train] step=1032 | loss=0.1210 | lr=2.95e-06 | epoch=2.2055
[train] step=1033 | loss=0.1255 | lr=2.94e-06 | epoch=2.2076
[train] step=1034 | loss=0.1140 | lr=2.94e-06 | epoch=2.2097
[train] step=1035 | loss=0.1297 | lr=2.93e-06 | epoch=2.2119
[train] step=1036 | loss=0.1106 | lr=2.92e-06 | epoch=2.2140
[train] step=1037 | loss=0.1439 | lr=2.91e-06 | epoch=2.2162
[train] step=1038 | loss=0.1335 | lr=2.90e-06 | epoch=2.2183
[train] step=1039 | loss=0.1142 | lr=2.90e-06 | epoch=2.2204
[train] step=1040 | loss=0.0953 | lr=2.89e-06 | epoch=2.2226
[train] step=1041 | loss=0.1050 | lr=2.88e-06 | epoch=2.2247
[train] step=1042 | loss=0.1081 | lr=2.87e-06 | epoch=2.2269
[train] step=1043 | loss=0.1004 | lr=2.86e-06 | epoch=2.2290
[train] step=1044 | loss=0.1407 | lr=2.86e-06 | epoch=2.2311
[train] step=1045 | loss=0.1019 | lr=2.85e-06 | epoch=2.2333
[train] step=1046 | loss=0.1487 | lr=2.84e-06 | epoch=2.2354
[train] step=1047 | loss=0.1348 | lr=2.83e-06 | epoch=2.2376
[train] step=1048 | loss=0.1179 | lr=2.82e-06 | epoch=2.2397
[train] step=1049 | loss=0.1218 | lr=2.82e-06 | epoch=2.2418
[train] step=1050 | loss=0.1072 | lr=2.81e-06 | epoch=2.2440
[train] step=1051 | loss=0.1059 | lr=2.80e-06 | epoch=2.2461
[train] step=1052 | loss=0.1250 | lr=2.79e-06 | epoch=2.2483
[train] step=1053 | loss=0.1191 | lr=2.78e-06 | epoch=2.2504
[train] step=1054 | loss=0.1165 | lr=2.78e-06 | epoch=2.2525
[train] step=1055 | loss=0.1304 | lr=2.77e-06 | epoch=2.2547
[train] step=1056 | loss=0.1279 | lr=2.76e-06 | epoch=2.2568
[train] step=1057 | loss=0.1057 | lr=2.75e-06 | epoch=2.2590
[train] step=1058 | loss=0.0998 | lr=2.75e-06 | epoch=2.2611
[train] step=1059 | loss=0.1289 | lr=2.74e-06 | epoch=2.2632
[train] step=1060 | loss=0.1180 | lr=2.73e-06 | epoch=2.2654
[train] step=1061 | loss=0.1169 | lr=2.72e-06 | epoch=2.2675
[train] step=1062 | loss=0.1165 | lr=2.71e-06 | epoch=2.2697
[train] step=1063 | loss=0.0920 | lr=2.71e-06 | epoch=2.2718
[train] step=1064 | loss=0.1090 | lr=2.70e-06 | epoch=2.2739
[train] step=1065 | loss=0.1052 | lr=2.69e-06 | epoch=2.2761
[train] step=1066 | loss=0.1168 | lr=2.68e-06 | epoch=2.2782
[train] step=1067 | loss=0.1071 | lr=2.67e-06 | epoch=2.2804
[train] step=1068 | loss=0.1327 | lr=2.67e-06 | epoch=2.2825
[train] step=1069 | loss=0.0964 | lr=2.66e-06 | epoch=2.2846
[train] step=1070 | loss=0.1244 | lr=2.65e-06 | epoch=2.2868
[train] step=1071 | loss=0.1183 | lr=2.64e-06 | epoch=2.2889
[train] step=1072 | loss=0.0965 | lr=2.63e-06 | epoch=2.2911
[train] step=1073 | loss=0.1047 | lr=2.63e-06 | epoch=2.2932
[train] step=1074 | loss=0.1032 | lr=2.62e-06 | epoch=2.2953
[train] step=1075 | loss=0.1224 | lr=2.61e-06 | epoch=2.2975
[train] step=1076 | loss=0.1198 | lr=2.60e-06 | epoch=2.2996
[train] step=1077 | loss=0.1099 | lr=2.59e-06 | epoch=2.3018
[train] step=1078 | loss=0.1139 | lr=2.59e-06 | epoch=2.3039
[train] step=1079 | loss=0.1387 | lr=2.58e-06 | epoch=2.3060
[train] step=1080 | loss=0.1226 | lr=2.57e-06 | epoch=2.3082
[train] step=1081 | loss=0.1467 | lr=2.56e-06 | epoch=2.3103
[train] step=1082 | loss=0.1269 | lr=2.56e-06 | epoch=2.3125
[train] step=1083 | loss=0.1208 | lr=2.55e-06 | epoch=2.3146
[train] step=1084 | loss=0.0936 | lr=2.54e-06 | epoch=2.3167
[train] step=1085 | loss=0.1094 | lr=2.53e-06 | epoch=2.3189
[train] step=1086 | loss=0.1066 | lr=2.52e-06 | epoch=2.3210
[train] step=1087 | loss=0.1322 | lr=2.52e-06 | epoch=2.3232
[train] step=1088 | loss=0.1304 | lr=2.51e-06 | epoch=2.3253
[train] step=1089 | loss=0.1082 | lr=2.50e-06 | epoch=2.3274
[train] step=1090 | loss=0.1294 | lr=2.49e-06 | epoch=2.3296
[train] step=1091 | loss=0.1270 | lr=2.48e-06 | epoch=2.3317
[train] step=1092 | loss=0.1173 | lr=2.48e-06 | epoch=2.3339
[train] step=1093 | loss=0.1081 | lr=2.47e-06 | epoch=2.3360
[train] step=1094 | loss=0.1058 | lr=2.46e-06 | epoch=2.3381
[train] step=1095 | loss=0.1205 | lr=2.45e-06 | epoch=2.3403
[train] step=1096 | loss=0.1179 | lr=2.44e-06 | epoch=2.3424
[train] step=1097 | loss=0.1337 | lr=2.44e-06 | epoch=2.3446
[train] step=1098 | loss=0.1107 | lr=2.43e-06 | epoch=2.3467
[train] step=1099 | loss=0.1165 | lr=2.42e-06 | epoch=2.3488
[train] step=1100 | loss=0.1104 | lr=2.41e-06 | epoch=2.3510
[train] step=1101 | loss=0.1262 | lr=2.41e-06 | epoch=2.3531
[train] step=1102 | loss=0.1251 | lr=2.40e-06 | epoch=2.3553
[train] step=1103 | loss=0.1006 | lr=2.39e-06 | epoch=2.3574
[train] step=1104 | loss=0.1249 | lr=2.38e-06 | epoch=2.3596
[train] step=1105 | loss=0.1096 | lr=2.37e-06 | epoch=2.3617
[train] step=1106 | loss=0.1628 | lr=2.37e-06 | epoch=2.3638
[train] step=1107 | loss=0.1179 | lr=2.36e-06 | epoch=2.3660
[train] step=1108 | loss=0.1137 | lr=2.35e-06 | epoch=2.3681
[train] step=1109 | loss=0.1274 | lr=2.34e-06 | epoch=2.3703
[train] step=1110 | loss=0.1195 | lr=2.33e-06 | epoch=2.3724
[train] step=1111 | loss=0.1155 | lr=2.33e-06 | epoch=2.3745
[train] step=1112 | loss=0.1097 | lr=2.32e-06 | epoch=2.3767
[train] step=1113 | loss=0.1309 | lr=2.31e-06 | epoch=2.3788
[train] step=1114 | loss=0.1377 | lr=2.30e-06 | epoch=2.3810
[train] step=1115 | loss=0.1046 | lr=2.29e-06 | epoch=2.3831
[train] step=1116 | loss=0.1385 | lr=2.29e-06 | epoch=2.3852
[train] step=1117 | loss=0.1155 | lr=2.28e-06 | epoch=2.3874
[train] step=1118 | loss=0.1103 | lr=2.27e-06 | epoch=2.3895
[train] step=1119 | loss=0.1206 | lr=2.26e-06 | epoch=2.3917
[train] step=1120 | loss=0.1130 | lr=2.25e-06 | epoch=2.3938
[train] step=1121 | loss=0.1170 | lr=2.25e-06 | epoch=2.3959
[train] step=1122 | loss=0.1291 | lr=2.24e-06 | epoch=2.3981
[train] step=1123 | loss=0.1426 | lr=2.23e-06 | epoch=2.4002
[train] step=1124 | loss=0.1195 | lr=2.22e-06 | epoch=2.4024
[train] step=1125 | loss=0.1120 | lr=2.22e-06 | epoch=2.4045
[train] step=1126 | loss=0.1032 | lr=2.21e-06 | epoch=2.4066
[train] step=1127 | loss=0.1151 | lr=2.20e-06 | epoch=2.4088
[train] step=1128 | loss=0.1108 | lr=2.19e-06 | epoch=2.4109
[train] step=1129 | loss=0.1132 | lr=2.18e-06 | epoch=2.4131
[train] step=1130 | loss=0.1050 | lr=2.18e-06 | epoch=2.4152
[train] step=1131 | loss=0.1279 | lr=2.17e-06 | epoch=2.4173
[train] step=1132 | loss=0.0987 | lr=2.16e-06 | epoch=2.4195
[train] step=1133 | loss=0.1039 | lr=2.15e-06 | epoch=2.4216
[train] step=1134 | loss=0.1217 | lr=2.14e-06 | epoch=2.4238
[train] step=1135 | loss=0.1338 | lr=2.14e-06 | epoch=2.4259
[train] step=1136 | loss=0.1262 | lr=2.13e-06 | epoch=2.4280
[train] step=1137 | loss=0.0977 | lr=2.12e-06 | epoch=2.4302
[train] step=1138 | loss=0.1095 | lr=2.11e-06 | epoch=2.4323
[train] step=1139 | loss=0.1160 | lr=2.10e-06 | epoch=2.4345
[train] step=1140 | loss=0.1213 | lr=2.10e-06 | epoch=2.4366
[train] step=1141 | loss=0.1392 | lr=2.09e-06 | epoch=2.4387
[train] step=1142 | loss=0.1069 | lr=2.08e-06 | epoch=2.4409
[train] step=1143 | loss=0.1194 | lr=2.07e-06 | epoch=2.4430
[train] step=1144 | loss=0.1095 | lr=2.06e-06 | epoch=2.4452
[train] step=1145 | loss=0.0995 | lr=2.06e-06 | epoch=2.4473
[train] step=1146 | loss=0.1127 | lr=2.05e-06 | epoch=2.4494
[train] step=1147 | loss=0.1119 | lr=2.04e-06 | epoch=2.4516
[train] step=1148 | loss=0.1586 | lr=2.03e-06 | epoch=2.4537
[train] step=1149 | loss=0.1272 | lr=2.03e-06 | epoch=2.4559
[train] step=1150 | loss=0.1134 | lr=2.02e-06 | epoch=2.4580
[train] step=1151 | loss=0.1175 | lr=2.01e-06 | epoch=2.4601
[train] step=1152 | loss=0.1149 | lr=2.00e-06 | epoch=2.4623
[train] step=1153 | loss=0.1460 | lr=1.99e-06 | epoch=2.4644
[train] step=1154 | loss=0.1196 | lr=1.99e-06 | epoch=2.4666
[train] step=1155 | loss=0.1052 | lr=1.98e-06 | epoch=2.4687
[train] step=1156 | loss=0.1131 | lr=1.97e-06 | epoch=2.4708
[train] step=1157 | loss=0.1179 | lr=1.96e-06 | epoch=2.4730
[train] step=1158 | loss=0.1060 | lr=1.95e-06 | epoch=2.4751
[train] step=1159 | loss=0.1207 | lr=1.95e-06 | epoch=2.4773
[train] step=1160 | loss=0.1064 | lr=1.94e-06 | epoch=2.4794
[train] step=1161 | loss=0.1129 | lr=1.93e-06 | epoch=2.4815
[train] step=1162 | loss=0.1112 | lr=1.92e-06 | epoch=2.4837
[train] step=1163 | loss=0.1198 | lr=1.91e-06 | epoch=2.4858
[train] step=1164 | loss=0.1040 | lr=1.91e-06 | epoch=2.4880
[train] step=1165 | loss=0.1014 | lr=1.90e-06 | epoch=2.4901

Saving model checkpoint to output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1165
2026-04-06 01:36:55 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:36:55 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 01:36:56 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:36:56 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1165\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1165\tokenizer_config.json

[train] step=1166 | loss=0.1123 | lr=1.89e-06 | epoch=2.4922
[train] step=1167 | loss=0.1063 | lr=1.88e-06 | epoch=2.4944
[train] step=1168 | loss=0.1159 | lr=1.88e-06 | epoch=2.4965
[train] step=1169 | loss=0.1465 | lr=1.87e-06 | epoch=2.4987
[train] step=1170 | loss=0.1020 | lr=1.86e-06 | epoch=2.5008
[train] step=1171 | loss=0.1047 | lr=1.85e-06 | epoch=2.5029
[train] step=1172 | loss=0.1252 | lr=1.84e-06 | epoch=2.5051
[train] step=1173 | loss=0.0895 | lr=1.84e-06 | epoch=2.5072
[train] step=1174 | loss=0.1019 | lr=1.83e-06 | epoch=2.5094
[train] step=1175 | loss=0.1066 | lr=1.82e-06 | epoch=2.5115
[train] step=1176 | loss=0.1164 | lr=1.81e-06 | epoch=2.5136
[train] step=1177 | loss=0.1422 | lr=1.80e-06 | epoch=2.5158
[train] step=1178 | loss=0.1150 | lr=1.80e-06 | epoch=2.5179
[train] step=1179 | loss=0.1159 | lr=1.79e-06 | epoch=2.5201
[train] step=1180 | loss=0.1092 | lr=1.78e-06 | epoch=2.5222
[train] step=1181 | loss=0.1394 | lr=1.77e-06 | epoch=2.5243
[train] step=1182 | loss=0.1072 | lr=1.76e-06 | epoch=2.5265
[train] step=1183 | loss=0.1331 | lr=1.76e-06 | epoch=2.5286
[train] step=1184 | loss=0.1198 | lr=1.75e-06 | epoch=2.5308
[train] step=1185 | loss=0.1222 | lr=1.74e-06 | epoch=2.5329
[train] step=1186 | loss=0.1105 | lr=1.73e-06 | epoch=2.5350
[train] step=1187 | loss=0.1137 | lr=1.72e-06 | epoch=2.5372
[train] step=1188 | loss=0.1084 | lr=1.72e-06 | epoch=2.5393
[train] step=1189 | loss=0.1193 | lr=1.71e-06 | epoch=2.5415
[train] step=1190 | loss=0.1167 | lr=1.70e-06 | epoch=2.5436
[train] step=1191 | loss=0.1474 | lr=1.69e-06 | epoch=2.5457
[train] step=1192 | loss=0.1002 | lr=1.69e-06 | epoch=2.5479
[train] step=1193 | loss=0.0987 | lr=1.68e-06 | epoch=2.5500
[train] step=1194 | loss=0.1129 | lr=1.67e-06 | epoch=2.5522
[train] step=1195 | loss=0.1357 | lr=1.66e-06 | epoch=2.5543
[train] step=1196 | loss=0.1075 | lr=1.65e-06 | epoch=2.5564
[train] step=1197 | loss=0.1276 | lr=1.65e-06 | epoch=2.5586
[train] step=1198 | loss=0.1259 | lr=1.64e-06 | epoch=2.5607
[train] step=1199 | loss=0.1086 | lr=1.63e-06 | epoch=2.5629
[train] step=1200 | loss=0.1233 | lr=1.62e-06 | epoch=2.5650
[train] step=1201 | loss=0.1184 | lr=1.61e-06 | epoch=2.5671
[train] step=1202 | loss=0.1312 | lr=1.61e-06 | epoch=2.5693
[train] step=1203 | loss=0.1228 | lr=1.60e-06 | epoch=2.5714
[train] step=1204 | loss=0.1320 | lr=1.59e-06 | epoch=2.5736
[train] step=1205 | loss=0.1121 | lr=1.58e-06 | epoch=2.5757
[train] step=1206 | loss=0.1053 | lr=1.57e-06 | epoch=2.5778
[train] step=1207 | loss=0.1220 | lr=1.57e-06 | epoch=2.5800
[train] step=1208 | loss=0.1023 | lr=1.56e-06 | epoch=2.5821
[train] step=1209 | loss=0.1205 | lr=1.55e-06 | epoch=2.5843
[train] step=1210 | loss=0.1175 | lr=1.54e-06 | epoch=2.5864
[train] step=1211 | loss=0.1417 | lr=1.53e-06 | epoch=2.5886
[train] step=1212 | loss=0.1219 | lr=1.53e-06 | epoch=2.5907
[train] step=1213 | loss=0.1111 | lr=1.52e-06 | epoch=2.5928
[train] step=1214 | loss=0.0953 | lr=1.51e-06 | epoch=2.5950
[train] step=1215 | loss=0.1180 | lr=1.50e-06 | epoch=2.5971
[train] step=1216 | loss=0.1389 | lr=1.50e-06 | epoch=2.5993
[train] step=1217 | loss=0.1215 | lr=1.49e-06 | epoch=2.6014
[train] step=1218 | loss=0.1124 | lr=1.48e-06 | epoch=2.6035
[train] step=1219 | loss=0.1150 | lr=1.47e-06 | epoch=2.6057
[train] step=1220 | loss=0.1105 | lr=1.46e-06 | epoch=2.6078
[train] step=1221 | loss=0.1228 | lr=1.46e-06 | epoch=2.6100
[train] step=1222 | loss=0.1407 | lr=1.45e-06 | epoch=2.6121
[train] step=1223 | loss=0.1270 | lr=1.44e-06 | epoch=2.6142
[train] step=1224 | loss=0.1023 | lr=1.43e-06 | epoch=2.6164
[train] step=1225 | loss=0.1119 | lr=1.42e-06 | epoch=2.6185
[train] step=1226 | loss=0.1104 | lr=1.42e-06 | epoch=2.6207
[train] step=1227 | loss=0.1134 | lr=1.41e-06 | epoch=2.6228
[train] step=1228 | loss=0.1239 | lr=1.40e-06 | epoch=2.6249
[train] step=1229 | loss=0.1120 | lr=1.39e-06 | epoch=2.6271
[train] step=1230 | loss=0.1190 | lr=1.38e-06 | epoch=2.6292
[train] step=1231 | loss=0.0844 | lr=1.38e-06 | epoch=2.6314
[train] step=1232 | loss=0.1216 | lr=1.37e-06 | epoch=2.6335
[train] step=1233 | loss=0.1368 | lr=1.36e-06 | epoch=2.6356
[train] step=1234 | loss=0.1254 | lr=1.35e-06 | epoch=2.6378
[train] step=1235 | loss=0.1294 | lr=1.34e-06 | epoch=2.6399
[train] step=1236 | loss=0.0960 | lr=1.34e-06 | epoch=2.6421
[train] step=1237 | loss=0.1094 | lr=1.33e-06 | epoch=2.6442
[train] step=1238 | loss=0.1060 | lr=1.32e-06 | epoch=2.6463
[train] step=1239 | loss=0.1291 | lr=1.31e-06 | epoch=2.6485
[train] step=1240 | loss=0.1192 | lr=1.31e-06 | epoch=2.6506
[train] step=1241 | loss=0.1056 | lr=1.30e-06 | epoch=2.6528
[train] step=1242 | loss=0.1425 | lr=1.29e-06 | epoch=2.6549
[train] step=1243 | loss=0.1091 | lr=1.28e-06 | epoch=2.6570
[train] step=1244 | loss=0.1316 | lr=1.27e-06 | epoch=2.6592
[train] step=1245 | loss=0.1039 | lr=1.27e-06 | epoch=2.6613
[train] step=1246 | loss=0.1063 | lr=1.26e-06 | epoch=2.6635
[train] step=1247 | loss=0.1263 | lr=1.25e-06 | epoch=2.6656
[train] step=1248 | loss=0.1145 | lr=1.24e-06 | epoch=2.6677
[train] step=1249 | loss=0.1007 | lr=1.23e-06 | epoch=2.6699
[train] step=1250 | loss=0.0887 | lr=1.23e-06 | epoch=2.6720
[train] step=1251 | loss=0.1413 | lr=1.22e-06 | epoch=2.6742
[train] step=1252 | loss=0.1119 | lr=1.21e-06 | epoch=2.6763
[train] step=1253 | loss=0.1209 | lr=1.20e-06 | epoch=2.6784
[train] step=1254 | loss=0.1139 | lr=1.19e-06 | epoch=2.6806
[train] step=1255 | loss=0.1071 | lr=1.19e-06 | epoch=2.6827
[train] step=1256 | loss=0.1079 | lr=1.18e-06 | epoch=2.6849
[train] step=1257 | loss=0.0906 | lr=1.17e-06 | epoch=2.6870
[train] step=1258 | loss=0.1228 | lr=1.16e-06 | epoch=2.6891
[train] step=1259 | loss=0.1355 | lr=1.16e-06 | epoch=2.6913
[train] step=1260 | loss=0.1152 | lr=1.15e-06 | epoch=2.6934
[train] step=1261 | loss=0.1163 | lr=1.14e-06 | epoch=2.6956
[train] step=1262 | loss=0.1508 | lr=1.13e-06 | epoch=2.6977
[train] step=1263 | loss=0.1001 | lr=1.12e-06 | epoch=2.6998
[train] step=1264 | loss=0.1121 | lr=1.12e-06 | epoch=2.7020
[train] step=1265 | loss=0.1274 | lr=1.11e-06 | epoch=2.7041
[train] step=1266 | loss=0.1429 | lr=1.10e-06 | epoch=2.7063
[train] step=1267 | loss=0.1150 | lr=1.09e-06 | epoch=2.7084
[train] step=1268 | loss=0.1437 | lr=1.08e-06 | epoch=2.7105
[train] step=1269 | loss=0.1426 | lr=1.08e-06 | epoch=2.7127
[train] step=1270 | loss=0.1090 | lr=1.07e-06 | epoch=2.7148
[train] step=1271 | loss=0.1008 | lr=1.06e-06 | epoch=2.7170
[train] step=1272 | loss=0.1055 | lr=1.05e-06 | epoch=2.7191
[train] step=1273 | loss=0.1173 | lr=1.04e-06 | epoch=2.7212
[train] step=1274 | loss=0.1104 | lr=1.04e-06 | epoch=2.7234
[train] step=1275 | loss=0.1209 | lr=1.03e-06 | epoch=2.7255
[train] step=1276 | loss=0.0877 | lr=1.02e-06 | epoch=2.7277
[train] step=1277 | loss=0.1185 | lr=1.01e-06 | epoch=2.7298
[train] step=1278 | loss=0.1189 | lr=1.00e-06 | epoch=2.7319
[train] step=1279 | loss=0.1418 | lr=9.97e-07 | epoch=2.7341
[train] step=1280 | loss=0.1177 | lr=9.89e-07 | epoch=2.7362
[train] step=1281 | loss=0.1073 | lr=9.81e-07 | epoch=2.7384
[train] step=1282 | loss=0.1189 | lr=9.73e-07 | epoch=2.7405
[train] step=1283 | loss=0.1105 | lr=9.65e-07 | epoch=2.7426
[train] step=1284 | loss=0.1414 | lr=9.57e-07 | epoch=2.7448
[train] step=1285 | loss=0.1151 | lr=9.49e-07 | epoch=2.7469
[train] step=1286 | loss=0.0993 | lr=9.41e-07 | epoch=2.7491
[train] step=1287 | loss=0.1150 | lr=9.34e-07 | epoch=2.7512
[train] step=1288 | loss=0.1207 | lr=9.26e-07 | epoch=2.7533
[train] step=1289 | loss=0.1103 | lr=9.18e-07 | epoch=2.7555
[train] step=1290 | loss=0.1447 | lr=9.10e-07 | epoch=2.7576
[train] step=1291 | loss=0.0995 | lr=9.02e-07 | epoch=2.7598
[train] step=1292 | loss=0.1181 | lr=8.94e-07 | epoch=2.7619
[train] step=1293 | loss=0.1032 | lr=8.86e-07 | epoch=2.7640
[train] step=1294 | loss=0.1313 | lr=8.78e-07 | epoch=2.7662
[train] step=1295 | loss=0.1213 | lr=8.70e-07 | epoch=2.7683
[train] step=1296 | loss=0.1364 | lr=8.62e-07 | epoch=2.7705
[train] step=1297 | loss=0.1100 | lr=8.54e-07 | epoch=2.7726
[train] step=1298 | loss=0.1008 | lr=8.47e-07 | epoch=2.7747
[train] step=1299 | loss=0.1250 | lr=8.39e-07 | epoch=2.7769
[train] step=1300 | loss=0.1097 | lr=8.31e-07 | epoch=2.7790
[train] step=1301 | loss=0.1207 | lr=8.23e-07 | epoch=2.7812
[train] step=1302 | loss=0.1185 | lr=8.15e-07 | epoch=2.7833
[train] step=1303 | loss=0.1272 | lr=8.07e-07 | epoch=2.7854
[train] step=1304 | loss=0.1187 | lr=7.99e-07 | epoch=2.7876
[train] step=1305 | loss=0.1356 | lr=7.91e-07 | epoch=2.7897
[train] step=1306 | loss=0.1287 | lr=7.83e-07 | epoch=2.7919
[train] step=1307 | loss=0.1000 | lr=7.75e-07 | epoch=2.7940
[train] step=1308 | loss=0.1022 | lr=7.67e-07 | epoch=2.7961
[train] step=1309 | loss=0.1216 | lr=7.59e-07 | epoch=2.7983
[train] step=1310 | loss=0.1034 | lr=7.52e-07 | epoch=2.8004
[train] step=1311 | loss=0.1340 | lr=7.44e-07 | epoch=2.8026
[train] step=1312 | loss=0.1110 | lr=7.36e-07 | epoch=2.8047
[train] step=1313 | loss=0.1167 | lr=7.28e-07 | epoch=2.8068
[train] step=1314 | loss=0.1119 | lr=7.20e-07 | epoch=2.8090
[train] step=1315 | loss=0.1209 | lr=7.12e-07 | epoch=2.8111
[train] step=1316 | loss=0.1103 | lr=7.04e-07 | epoch=2.8133
[train] step=1317 | loss=0.1238 | lr=6.96e-07 | epoch=2.8154
[train] step=1318 | loss=0.1210 | lr=6.88e-07 | epoch=2.8175
[train] step=1319 | loss=0.0903 | lr=6.80e-07 | epoch=2.8197
[train] step=1320 | loss=0.1081 | lr=6.72e-07 | epoch=2.8218
[train] step=1321 | loss=0.1059 | lr=6.65e-07 | epoch=2.8240
[train] step=1322 | loss=0.0941 | lr=6.57e-07 | epoch=2.8261
[train] step=1323 | loss=0.0967 | lr=6.49e-07 | epoch=2.8283
[train] step=1324 | loss=0.1251 | lr=6.41e-07 | epoch=2.8304
[train] step=1325 | loss=0.0935 | lr=6.33e-07 | epoch=2.8325
[train] step=1326 | loss=0.1093 | lr=6.25e-07 | epoch=2.8347
[train] step=1327 | loss=0.1203 | lr=6.17e-07 | epoch=2.8368
[train] step=1328 | loss=0.1248 | lr=6.09e-07 | epoch=2.8390
[train] step=1329 | loss=0.1233 | lr=6.01e-07 | epoch=2.8411
[train] step=1330 | loss=0.1300 | lr=5.93e-07 | epoch=2.8432
[train] step=1331 | loss=0.0995 | lr=5.85e-07 | epoch=2.8454
[train] step=1332 | loss=0.1590 | lr=5.78e-07 | epoch=2.8475
[train] step=1333 | loss=0.1167 | lr=5.70e-07 | epoch=2.8497
[train] step=1334 | loss=0.1110 | lr=5.62e-07 | epoch=2.8518
[train] step=1335 | loss=0.1390 | lr=5.54e-07 | epoch=2.8539
[train] step=1336 | loss=0.1004 | lr=5.46e-07 | epoch=2.8561
[train] step=1337 | loss=0.1184 | lr=5.38e-07 | epoch=2.8582
[train] step=1338 | loss=0.1192 | lr=5.30e-07 | epoch=2.8604
[train] step=1339 | loss=0.1478 | lr=5.22e-07 | epoch=2.8625
[train] step=1340 | loss=0.1359 | lr=5.14e-07 | epoch=2.8646
[train] step=1341 | loss=0.1000 | lr=5.06e-07 | epoch=2.8668
[train] step=1342 | loss=0.1149 | lr=4.98e-07 | epoch=2.8689
[train] step=1343 | loss=0.1248 | lr=4.91e-07 | epoch=2.8711
[train] step=1344 | loss=0.1002 | lr=4.83e-07 | epoch=2.8732
[train] step=1345 | loss=0.1159 | lr=4.75e-07 | epoch=2.8753
[train] step=1346 | loss=0.1363 | lr=4.67e-07 | epoch=2.8775
[train] step=1347 | loss=0.1358 | lr=4.59e-07 | epoch=2.8796
[train] step=1348 | loss=0.1383 | lr=4.51e-07 | epoch=2.8818
[train] step=1349 | loss=0.0998 | lr=4.43e-07 | epoch=2.8839
[train] step=1350 | loss=0.1293 | lr=4.35e-07 | epoch=2.8860
[train] step=1351 | loss=0.1330 | lr=4.27e-07 | epoch=2.8882
[train] step=1352 | loss=0.1175 | lr=4.19e-07 | epoch=2.8903
[train] step=1353 | loss=0.1174 | lr=4.11e-07 | epoch=2.8925
[train] step=1354 | loss=0.1038 | lr=4.03e-07 | epoch=2.8946
[train] step=1355 | loss=0.1229 | lr=3.96e-07 | epoch=2.8967
[train] step=1356 | loss=0.0986 | lr=3.88e-07 | epoch=2.8989
[train] step=1357 | loss=0.1265 | lr=3.80e-07 | epoch=2.9010
[train] step=1358 | loss=0.1055 | lr=3.72e-07 | epoch=2.9032
[train] step=1359 | loss=0.1112 | lr=3.64e-07 | epoch=2.9053
[train] step=1360 | loss=0.1118 | lr=3.56e-07 | epoch=2.9074
[train] step=1361 | loss=0.1029 | lr=3.48e-07 | epoch=2.9096
[train] step=1362 | loss=0.1191 | lr=3.40e-07 | epoch=2.9117
[train] step=1363 | loss=0.1046 | lr=3.32e-07 | epoch=2.9139
[train] step=1364 | loss=0.1140 | lr=3.24e-07 | epoch=2.9160
[train] step=1365 | loss=0.1343 | lr=3.16e-07 | epoch=2.9181
[train] step=1366 | loss=0.1263 | lr=3.09e-07 | epoch=2.9203
[train] step=1367 | loss=0.1384 | lr=3.01e-07 | epoch=2.9224
[train] step=1368 | loss=0.0764 | lr=2.93e-07 | epoch=2.9246
[train] step=1369 | loss=0.0984 | lr=2.85e-07 | epoch=2.9267
[train] step=1370 | loss=0.1068 | lr=2.77e-07 | epoch=2.9288
[train] step=1371 | loss=0.0852 | lr=2.69e-07 | epoch=2.9310
[train] step=1372 | loss=0.1223 | lr=2.61e-07 | epoch=2.9331
[train] step=1373 | loss=0.1239 | lr=2.53e-07 | epoch=2.9353
[train] step=1374 | loss=0.1022 | lr=2.45e-07 | epoch=2.9374
[train] step=1375 | loss=0.1453 | lr=2.37e-07 | epoch=2.9395
[train] step=1376 | loss=0.1176 | lr=2.29e-07 | epoch=2.9417
[train] step=1377 | loss=0.1053 | lr=2.22e-07 | epoch=2.9438
[train] step=1378 | loss=0.1309 | lr=2.14e-07 | epoch=2.9460
[train] step=1379 | loss=0.1002 | lr=2.06e-07 | epoch=2.9481
[train] step=1380 | loss=0.1270 | lr=1.98e-07 | epoch=2.9502
[train] step=1381 | loss=0.1133 | lr=1.90e-07 | epoch=2.9524
[train] step=1382 | loss=0.1000 | lr=1.82e-07 | epoch=2.9545
[train] step=1383 | loss=0.1001 | lr=1.74e-07 | epoch=2.9567
[train] step=1384 | loss=0.1010 | lr=1.66e-07 | epoch=2.9588
[train] step=1385 | loss=0.1197 | lr=1.58e-07 | epoch=2.9609
[train] step=1386 | loss=0.1101 | lr=1.50e-07 | epoch=2.9631
[train] step=1387 | loss=0.1291 | lr=1.42e-07 | epoch=2.9652
[train] step=1388 | loss=0.1242 | lr=1.34e-07 | epoch=2.9674
[train] step=1389 | loss=0.1269 | lr=1.27e-07 | epoch=2.9695
[train] step=1390 | loss=0.1228 | lr=1.19e-07 | epoch=2.9716
[train] step=1391 | loss=0.1152 | lr=1.11e-07 | epoch=2.9738
[train] step=1392 | loss=0.1049 | lr=1.03e-07 | epoch=2.9759
[train] step=1393 | loss=0.1017 | lr=9.49e-08 | epoch=2.9781
[train] step=1394 | loss=0.1023 | lr=8.70e-08 | epoch=2.9802
[train] step=1395 | loss=0.0986 | lr=7.91e-08 | epoch=2.9823
[train] step=1396 | loss=0.0946 | lr=7.12e-08 | epoch=2.9845
[train] step=1397 | loss=0.1175 | lr=6.33e-08 | epoch=2.9866
[train] step=1398 | loss=0.1164 | lr=5.54e-08 | epoch=2.9888

Saving model checkpoint to output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1398
2026-04-06 01:46:21 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:21 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 01:46:22 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:22 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1398\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1398\tokenizer_config.json

[train] step=1399 | loss=0.1179 | lr=4.75e-08 | epoch=2.9909
[train] step=1400 | loss=0.1345 | lr=3.96e-08 | epoch=2.9930
[train] step=1401 | loss=0.1012 | lr=3.16e-08 | epoch=2.9952
[train] step=1402 | loss=0.1120 | lr=2.37e-08 | epoch=2.9973
[train] step=1403 | loss=0.1507 | lr=1.58e-08 | epoch=2.9995
[train] step=1404 | loss=0.0950 | lr=7.91e-09 | epoch=3.0000

Saving model checkpoint to output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1404
2026-04-06 01:46:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 01:46:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1404\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\checkpoint-1404\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=1404 | epoch=3.0000
[train] finished | global_step=1404

Saving model checkpoint to output\fine_tune\run_000_lr1e-5_r8_a16_ep3
2026-04-06 01:46:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 01:46:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\tokenizer_config.json
chat template saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_000_lr1e-5_r8_a16_ep3\tokenizer_config.json
2026-04-06 01:46:37 | INFO     | root | Done run 1/5: C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_000_lr1e-5_r8_a16_ep3

=== Run 2/5  run_001_lr3e-5_r16_a32_ep3  merged={'learning_rate': 3e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-06 01:46:37 | INFO     | root | Logging to C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_001_lr3e-5_r16_a32_ep3\training_run.log
2026-04-06 01:46:37 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:37 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 01:46:37 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:37 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-06 01:46:38 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-06 01:46:38 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-06 01:46:38 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"
2026-04-06 01:46:38 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:38 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 01:46:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 10560.67it/s]
2026-04-06 01:46:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": false,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

2026-04-06 01:46:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2-1.5B.
2026-04-06 01:46:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:46:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-06 01:46:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 01:46:41 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 01:46:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-06 01:46:41 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-06 01:46:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-06 01:46:43 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 4,358,144

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.6833 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.7304 | lr=2.14e-07 | epoch=0.0043
[train] step=3 | loss=1.7382 | lr=4.29e-07 | epoch=0.0064
[train] step=4 | loss=1.7181 | lr=6.43e-07 | epoch=0.0086
[train] step=5 | loss=1.6863 | lr=8.57e-07 | epoch=0.0107
[train] step=6 | loss=1.7076 | lr=1.07e-06 | epoch=0.0128
[train] step=7 | loss=1.6372 | lr=1.29e-06 | epoch=0.0150
[train] step=8 | loss=1.6104 | lr=1.50e-06 | epoch=0.0171
[train] step=9 | loss=1.7017 | lr=1.71e-06 | epoch=0.0193
[train] step=10 | loss=1.7064 | lr=1.93e-06 | epoch=0.0214
[train] step=11 | loss=1.7532 | lr=2.14e-06 | epoch=0.0235
[train] step=12 | loss=1.8385 | lr=2.36e-06 | epoch=0.0257
[train] step=13 | loss=1.7056 | lr=2.57e-06 | epoch=0.0278
[train] step=14 | loss=1.7508 | lr=2.79e-06 | epoch=0.0300
[train] step=15 | loss=1.8029 | lr=3.00e-06 | epoch=0.0321
[train] step=16 | loss=1.7381 | lr=3.21e-06 | epoch=0.0342
[train] step=17 | loss=1.7151 | lr=3.43e-06 | epoch=0.0364
[train] step=18 | loss=1.7295 | lr=3.64e-06 | epoch=0.0385
[train] step=19 | loss=1.7081 | lr=3.86e-06 | epoch=0.0407
[train] step=20 | loss=1.7131 | lr=4.07e-06 | epoch=0.0428
[train] step=21 | loss=1.6482 | lr=4.29e-06 | epoch=0.0449
[train] step=22 | loss=1.6992 | lr=4.50e-06 | epoch=0.0471
[train] step=23 | loss=1.6735 | lr=4.71e-06 | epoch=0.0492
[train] step=24 | loss=1.7135 | lr=4.93e-06 | epoch=0.0514
[train] step=25 | loss=1.6438 | lr=5.14e-06 | epoch=0.0535
[train] step=26 | loss=1.7684 | lr=5.36e-06 | epoch=0.0556
[train] step=27 | loss=1.6160 | lr=5.57e-06 | epoch=0.0578
[train] step=28 | loss=1.6542 | lr=5.79e-06 | epoch=0.0599
[train] step=29 | loss=1.6341 | lr=6.00e-06 | epoch=0.0621
[train] step=30 | loss=1.6877 | lr=6.21e-06 | epoch=0.0642
[train] step=31 | loss=1.5918 | lr=6.43e-06 | epoch=0.0663
[train] step=32 | loss=1.6216 | lr=6.64e-06 | epoch=0.0685
[train] step=33 | loss=1.6321 | lr=6.86e-06 | epoch=0.0706
[train] step=34 | loss=1.6474 | lr=7.07e-06 | epoch=0.0728
[train] step=35 | loss=1.7668 | lr=7.29e-06 | epoch=0.0749
[train] step=36 | loss=1.6478 | lr=7.50e-06 | epoch=0.0770
[train] step=37 | loss=1.6732 | lr=7.71e-06 | epoch=0.0792
[train] step=38 | loss=1.6421 | lr=7.93e-06 | epoch=0.0813
[train] step=39 | loss=1.6083 | lr=8.14e-06 | epoch=0.0835
[train] step=40 | loss=1.7300 | lr=8.36e-06 | epoch=0.0856
[train] step=41 | loss=1.6392 | lr=8.57e-06 | epoch=0.0877
[train] step=42 | loss=1.6413 | lr=8.79e-06 | epoch=0.0899
[train] step=43 | loss=1.6140 | lr=9.00e-06 | epoch=0.0920
[train] step=44 | loss=1.5620 | lr=9.21e-06 | epoch=0.0942
[train] step=45 | loss=1.6145 | lr=9.43e-06 | epoch=0.0963
[train] step=46 | loss=1.5781 | lr=9.64e-06 | epoch=0.0984
[train] step=47 | loss=1.5749 | lr=9.86e-06 | epoch=0.1006
[train] step=48 | loss=1.4629 | lr=1.01e-05 | epoch=0.1027
[train] step=49 | loss=1.5486 | lr=1.03e-05 | epoch=0.1049
[train] step=50 | loss=1.6468 | lr=1.05e-05 | epoch=0.1070
[train] step=51 | loss=1.5890 | lr=1.07e-05 | epoch=0.1091
[train] step=52 | loss=1.5661 | lr=1.09e-05 | epoch=0.1113
[train] step=53 | loss=1.6508 | lr=1.11e-05 | epoch=0.1134
[train] step=54 | loss=1.5246 | lr=1.14e-05 | epoch=0.1156
[train] step=55 | loss=1.4139 | lr=1.16e-05 | epoch=0.1177
[train] step=56 | loss=1.6044 | lr=1.18e-05 | epoch=0.1199
[train] step=57 | loss=1.3859 | lr=1.20e-05 | epoch=0.1220
[train] step=58 | loss=1.5286 | lr=1.22e-05 | epoch=0.1241
[train] step=59 | loss=1.4511 | lr=1.24e-05 | epoch=0.1263
[train] step=60 | loss=1.4492 | lr=1.26e-05 | epoch=0.1284
[train] step=61 | loss=1.4440 | lr=1.29e-05 | epoch=0.1306
[train] step=62 | loss=1.4449 | lr=1.31e-05 | epoch=0.1327
[train] step=63 | loss=1.3895 | lr=1.33e-05 | epoch=0.1348
[train] step=64 | loss=1.5586 | lr=1.35e-05 | epoch=0.1370
[train] step=65 | loss=1.4234 | lr=1.37e-05 | epoch=0.1391
[train] step=66 | loss=1.4400 | lr=1.39e-05 | epoch=0.1413
[train] step=67 | loss=1.3867 | lr=1.41e-05 | epoch=0.1434
[train] step=68 | loss=1.4627 | lr=1.44e-05 | epoch=0.1455
[train] step=69 | loss=1.4812 | lr=1.46e-05 | epoch=0.1477
[train] step=70 | loss=1.4102 | lr=1.48e-05 | epoch=0.1498
[train] step=71 | loss=1.3433 | lr=1.50e-05 | epoch=0.1520
[train] step=72 | loss=1.3512 | lr=1.52e-05 | epoch=0.1541
[train] step=73 | loss=1.3425 | lr=1.54e-05 | epoch=0.1562
[train] step=74 | loss=1.3443 | lr=1.56e-05 | epoch=0.1584
[train] step=75 | loss=1.2997 | lr=1.59e-05 | epoch=0.1605
[train] step=76 | loss=1.2618 | lr=1.61e-05 | epoch=0.1627
[train] step=77 | loss=1.1728 | lr=1.63e-05 | epoch=0.1648
[train] step=78 | loss=1.3063 | lr=1.65e-05 | epoch=0.1669
[train] step=79 | loss=1.3090 | lr=1.67e-05 | epoch=0.1691
[train] step=80 | loss=1.1967 | lr=1.69e-05 | epoch=0.1712
[train] step=81 | loss=1.2121 | lr=1.71e-05 | epoch=0.1734
[train] step=82 | loss=1.2100 | lr=1.74e-05 | epoch=0.1755
[train] step=83 | loss=1.2046 | lr=1.76e-05 | epoch=0.1776
[train] step=84 | loss=1.1592 | lr=1.78e-05 | epoch=0.1798
[train] step=85 | loss=1.1931 | lr=1.80e-05 | epoch=0.1819
[train] step=86 | loss=1.1386 | lr=1.82e-05 | epoch=0.1841
[train] step=87 | loss=1.0963 | lr=1.84e-05 | epoch=0.1862
[train] step=88 | loss=1.1268 | lr=1.86e-05 | epoch=0.1883
[train] step=89 | loss=1.0349 | lr=1.89e-05 | epoch=0.1905
[train] step=90 | loss=1.0726 | lr=1.91e-05 | epoch=0.1926
[train] step=91 | loss=0.9778 | lr=1.93e-05 | epoch=0.1948
[train] step=92 | loss=1.0293 | lr=1.95e-05 | epoch=0.1969
[train] step=93 | loss=0.9718 | lr=1.97e-05 | epoch=0.1990
[train] step=94 | loss=0.9500 | lr=1.99e-05 | epoch=0.2012
[train] step=95 | loss=0.9291 | lr=2.01e-05 | epoch=0.2033
[train] step=96 | loss=0.9095 | lr=2.04e-05 | epoch=0.2055
[train] step=97 | loss=0.8557 | lr=2.06e-05 | epoch=0.2076
[train] step=98 | loss=0.8962 | lr=2.08e-05 | epoch=0.2097
[train] step=99 | loss=0.8050 | lr=2.10e-05 | epoch=0.2119
[train] step=100 | loss=0.7805 | lr=2.12e-05 | epoch=0.2140
[train] step=101 | loss=0.8039 | lr=2.14e-05 | epoch=0.2162
[train] step=102 | loss=0.7488 | lr=2.16e-05 | epoch=0.2183
[train] step=103 | loss=0.6843 | lr=2.19e-05 | epoch=0.2204
[train] step=104 | loss=0.6608 | lr=2.21e-05 | epoch=0.2226
[train] step=105 | loss=0.6311 | lr=2.23e-05 | epoch=0.2247
[train] step=106 | loss=0.6124 | lr=2.25e-05 | epoch=0.2269
[train] step=107 | loss=0.5804 | lr=2.27e-05 | epoch=0.2290
[train] step=108 | loss=0.5219 | lr=2.29e-05 | epoch=0.2311
[train] step=109 | loss=0.4815 | lr=2.31e-05 | epoch=0.2333
[train] step=110 | loss=0.4907 | lr=2.34e-05 | epoch=0.2354
[train] step=111 | loss=0.4375 | lr=2.36e-05 | epoch=0.2376
[train] step=112 | loss=0.3905 | lr=2.38e-05 | epoch=0.2397
[train] step=113 | loss=0.3878 | lr=2.40e-05 | epoch=0.2418
[train] step=114 | loss=0.3600 | lr=2.42e-05 | epoch=0.2440
[train] step=115 | loss=0.3419 | lr=2.44e-05 | epoch=0.2461
[train] step=116 | loss=0.3145 | lr=2.46e-05 | epoch=0.2483
[train] step=117 | loss=0.2918 | lr=2.49e-05 | epoch=0.2504
[train] step=118 | loss=0.2731 | lr=2.51e-05 | epoch=0.2525
[train] step=119 | loss=0.2661 | lr=2.53e-05 | epoch=0.2547
[train] step=120 | loss=0.2425 | lr=2.55e-05 | epoch=0.2568
[train] step=121 | loss=0.2415 | lr=2.57e-05 | epoch=0.2590
[train] step=122 | loss=0.2507 | lr=2.59e-05 | epoch=0.2611
[train] step=123 | loss=0.2463 | lr=2.61e-05 | epoch=0.2632
[train] step=124 | loss=0.2148 | lr=2.64e-05 | epoch=0.2654
[train] step=125 | loss=0.2285 | lr=2.66e-05 | epoch=0.2675
[train] step=126 | loss=0.2113 | lr=2.68e-05 | epoch=0.2697
[train] step=127 | loss=0.2104 | lr=2.70e-05 | epoch=0.2718
[train] step=128 | loss=0.1978 | lr=2.72e-05 | epoch=0.2739
[train] step=129 | loss=0.1996 | lr=2.74e-05 | epoch=0.2761
[train] step=130 | loss=0.2018 | lr=2.76e-05 | epoch=0.2782
[train] step=131 | loss=0.2214 | lr=2.79e-05 | epoch=0.2804
[train] step=132 | loss=0.1999 | lr=2.81e-05 | epoch=0.2825
[train] step=133 | loss=0.1979 | lr=2.83e-05 | epoch=0.2846
[train] step=134 | loss=0.1797 | lr=2.85e-05 | epoch=0.2868
[train] step=135 | loss=0.1877 | lr=2.87e-05 | epoch=0.2889
[train] step=136 | loss=0.1733 | lr=2.89e-05 | epoch=0.2911
[train] step=137 | loss=0.1936 | lr=2.91e-05 | epoch=0.2932
[train] step=138 | loss=0.1549 | lr=2.94e-05 | epoch=0.2953
[train] step=139 | loss=0.1531 | lr=2.96e-05 | epoch=0.2975
[train] step=140 | loss=0.1616 | lr=2.98e-05 | epoch=0.2996
[train] step=141 | loss=0.2132 | lr=3.00e-05 | epoch=0.3018
[train] step=142 | loss=0.1607 | lr=3.00e-05 | epoch=0.3039
[train] step=143 | loss=0.1605 | lr=3.00e-05 | epoch=0.3060
[train] step=144 | loss=0.1408 | lr=2.99e-05 | epoch=0.3082
[train] step=145 | loss=0.1574 | lr=2.99e-05 | epoch=0.3103
[train] step=146 | loss=0.1439 | lr=2.99e-05 | epoch=0.3125
[train] step=147 | loss=0.1544 | lr=2.99e-05 | epoch=0.3146
[train] step=148 | loss=0.1298 | lr=2.98e-05 | epoch=0.3167
[train] step=149 | loss=0.1398 | lr=2.98e-05 | epoch=0.3189
[train] step=150 | loss=0.1210 | lr=2.98e-05 | epoch=0.3210
[train] step=151 | loss=0.1573 | lr=2.98e-05 | epoch=0.3232
[train] step=152 | loss=0.1208 | lr=2.97e-05 | epoch=0.3253
[train] step=153 | loss=0.1227 | lr=2.97e-05 | epoch=0.3274
[train] step=154 | loss=0.1280 | lr=2.97e-05 | epoch=0.3296
[train] step=155 | loss=0.1052 | lr=2.97e-05 | epoch=0.3317
[train] step=156 | loss=0.1460 | lr=2.96e-05 | epoch=0.3339
[train] step=157 | loss=0.1663 | lr=2.96e-05 | epoch=0.3360
[train] step=158 | loss=0.1272 | lr=2.96e-05 | epoch=0.3381
[train] step=159 | loss=0.1214 | lr=2.96e-05 | epoch=0.3403
[train] step=160 | loss=0.1552 | lr=2.95e-05 | epoch=0.3424
[train] step=161 | loss=0.1138 | lr=2.95e-05 | epoch=0.3446
[train] step=162 | loss=0.1114 | lr=2.95e-05 | epoch=0.3467
[train] step=163 | loss=0.1327 | lr=2.95e-05 | epoch=0.3488
[train] step=164 | loss=0.1489 | lr=2.95e-05 | epoch=0.3510
[train] step=165 | loss=0.1314 | lr=2.94e-05 | epoch=0.3531
[train] step=166 | loss=0.1431 | lr=2.94e-05 | epoch=0.3553
[train] step=167 | loss=0.1109 | lr=2.94e-05 | epoch=0.3574
[train] step=168 | loss=0.1138 | lr=2.94e-05 | epoch=0.3596
[train] step=169 | loss=0.1243 | lr=2.93e-05 | epoch=0.3617
[train] step=170 | loss=0.1186 | lr=2.93e-05 | epoch=0.3638
[train] step=171 | loss=0.1339 | lr=2.93e-05 | epoch=0.3660
[train] step=172 | loss=0.1339 | lr=2.93e-05 | epoch=0.3681
[train] step=173 | loss=0.1090 | lr=2.92e-05 | epoch=0.3703
[train] step=174 | loss=0.1262 | lr=2.92e-05 | epoch=0.3724
[train] step=175 | loss=0.1186 | lr=2.92e-05 | epoch=0.3745
[train] step=176 | loss=0.1516 | lr=2.92e-05 | epoch=0.3767
[train] step=177 | loss=0.0984 | lr=2.91e-05 | epoch=0.3788
[train] step=178 | loss=0.1104 | lr=2.91e-05 | epoch=0.3810
[train] step=179 | loss=0.1199 | lr=2.91e-05 | epoch=0.3831
[train] step=180 | loss=0.1208 | lr=2.91e-05 | epoch=0.3852
[train] step=181 | loss=0.1220 | lr=2.91e-05 | epoch=0.3874
[train] step=182 | loss=0.0999 | lr=2.90e-05 | epoch=0.3895
[train] step=183 | loss=0.0921 | lr=2.90e-05 | epoch=0.3917
[train] step=184 | loss=0.1425 | lr=2.90e-05 | epoch=0.3938
[train] step=185 | loss=0.1098 | lr=2.90e-05 | epoch=0.3959
[train] step=186 | loss=0.0993 | lr=2.89e-05 | epoch=0.3981
[train] step=187 | loss=0.1141 | lr=2.89e-05 | epoch=0.4002
[train] step=188 | loss=0.1471 | lr=2.89e-05 | epoch=0.4024
[train] step=189 | loss=0.1330 | lr=2.89e-05 | epoch=0.4045
[train] step=190 | loss=0.1451 | lr=2.88e-05 | epoch=0.4066
[train] step=191 | loss=0.1096 | lr=2.88e-05 | epoch=0.4088
[train] step=192 | loss=0.1187 | lr=2.88e-05 | epoch=0.4109
[train] step=193 | loss=0.1326 | lr=2.88e-05 | epoch=0.4131
[train] step=194 | loss=0.1179 | lr=2.87e-05 | epoch=0.4152
[train] step=195 | loss=0.1298 | lr=2.87e-05 | epoch=0.4173
[train] step=196 | loss=0.1286 | lr=2.87e-05 | epoch=0.4195
[train] step=197 | loss=0.1043 | lr=2.87e-05 | epoch=0.4216
[train] step=198 | loss=0.1494 | lr=2.86e-05 | epoch=0.4238
[train] step=199 | loss=0.1361 | lr=2.86e-05 | epoch=0.4259
[train] step=200 | loss=0.1152 | lr=2.86e-05 | epoch=0.4280
[train] step=201 | loss=0.1207 | lr=2.86e-05 | epoch=0.4302
[train] step=202 | loss=0.1422 | lr=2.86e-05 | epoch=0.4323
[train] step=203 | loss=0.1213 | lr=2.85e-05 | epoch=0.4345
[train] step=204 | loss=0.1304 | lr=2.85e-05 | epoch=0.4366
[train] step=205 | loss=0.1042 | lr=2.85e-05 | epoch=0.4387
[train] step=206 | loss=0.1159 | lr=2.85e-05 | epoch=0.4409
[train] step=207 | loss=0.1221 | lr=2.84e-05 | epoch=0.4430
[train] step=208 | loss=0.1093 | lr=2.84e-05 | epoch=0.4452
[train] step=209 | loss=0.1297 | lr=2.84e-05 | epoch=0.4473
[train] step=210 | loss=0.1141 | lr=2.84e-05 | epoch=0.4494
[train] step=211 | loss=0.1150 | lr=2.83e-05 | epoch=0.4516
[train] step=212 | loss=0.1231 | lr=2.83e-05 | epoch=0.4537
[train] step=213 | loss=0.1558 | lr=2.83e-05 | epoch=0.4559
[train] step=214 | loss=0.1147 | lr=2.83e-05 | epoch=0.4580
[train] step=215 | loss=0.1327 | lr=2.82e-05 | epoch=0.4601
[train] step=216 | loss=0.1131 | lr=2.82e-05 | epoch=0.4623
[train] step=217 | loss=0.1317 | lr=2.82e-05 | epoch=0.4644
[train] step=218 | loss=0.1099 | lr=2.82e-05 | epoch=0.4666
[train] step=219 | loss=0.1060 | lr=2.81e-05 | epoch=0.4687
[train] step=220 | loss=0.1001 | lr=2.81e-05 | epoch=0.4708
[train] step=221 | loss=0.1073 | lr=2.81e-05 | epoch=0.4730
[train] step=222 | loss=0.1293 | lr=2.81e-05 | epoch=0.4751
[train] step=223 | loss=0.1325 | lr=2.81e-05 | epoch=0.4773
[train] step=224 | loss=0.1045 | lr=2.80e-05 | epoch=0.4794
[train] step=225 | loss=0.1313 | lr=2.80e-05 | epoch=0.4815
[train] step=226 | loss=0.1228 | lr=2.80e-05 | epoch=0.4837
[train] step=227 | loss=0.1247 | lr=2.80e-05 | epoch=0.4858
[train] step=228 | loss=0.1096 | lr=2.79e-05 | epoch=0.4880
[train] step=229 | loss=0.1226 | lr=2.79e-05 | epoch=0.4901
[train] step=230 | loss=0.1118 | lr=2.79e-05 | epoch=0.4922
[train] step=231 | loss=0.1321 | lr=2.79e-05 | epoch=0.4944
[train] step=232 | loss=0.1177 | lr=2.78e-05 | epoch=0.4965
[train] step=233 | loss=0.1334 | lr=2.78e-05 | epoch=0.4987

Saving model checkpoint to output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-233
2026-04-06 01:57:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:57:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 01:57:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 01:57:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-233\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-233\tokenizer_config.json

[train] step=234 | loss=0.1181 | lr=2.78e-05 | epoch=0.5008
[train] step=235 | loss=0.1075 | lr=2.78e-05 | epoch=0.5029
[train] step=236 | loss=0.1135 | lr=2.77e-05 | epoch=0.5051
[train] step=237 | loss=0.1228 | lr=2.77e-05 | epoch=0.5072
[train] step=238 | loss=0.1166 | lr=2.77e-05 | epoch=0.5094
[train] step=239 | loss=0.1116 | lr=2.77e-05 | epoch=0.5115
[train] step=240 | loss=0.1145 | lr=2.77e-05 | epoch=0.5136
[train] step=241 | loss=0.1198 | lr=2.76e-05 | epoch=0.5158
[train] step=242 | loss=0.1070 | lr=2.76e-05 | epoch=0.5179
[train] step=243 | loss=0.1400 | lr=2.76e-05 | epoch=0.5201
[train] step=244 | loss=0.1372 | lr=2.76e-05 | epoch=0.5222
[train] step=245 | loss=0.1092 | lr=2.75e-05 | epoch=0.5243
[train] step=246 | loss=0.1405 | lr=2.75e-05 | epoch=0.5265
[train] step=247 | loss=0.1281 | lr=2.75e-05 | epoch=0.5286
[train] step=248 | loss=0.1041 | lr=2.75e-05 | epoch=0.5308
[train] step=249 | loss=0.0993 | lr=2.74e-05 | epoch=0.5329
[train] step=250 | loss=0.1125 | lr=2.74e-05 | epoch=0.5350
[train] step=251 | loss=0.1139 | lr=2.74e-05 | epoch=0.5372
[train] step=252 | loss=0.1199 | lr=2.74e-05 | epoch=0.5393
[train] step=253 | loss=0.1335 | lr=2.73e-05 | epoch=0.5415
[train] step=254 | loss=0.1121 | lr=2.73e-05 | epoch=0.5436
[train] step=255 | loss=0.1135 | lr=2.73e-05 | epoch=0.5457
[train] step=256 | loss=0.1017 | lr=2.73e-05 | epoch=0.5479
[train] step=257 | loss=0.1086 | lr=2.72e-05 | epoch=0.5500
[train] step=258 | loss=0.1104 | lr=2.72e-05 | epoch=0.5522
[train] step=259 | loss=0.1214 | lr=2.72e-05 | epoch=0.5543
[train] step=260 | loss=0.1202 | lr=2.72e-05 | epoch=0.5564
[train] step=261 | loss=0.1019 | lr=2.72e-05 | epoch=0.5586
[train] step=262 | loss=0.1387 | lr=2.71e-05 | epoch=0.5607
[train] step=263 | loss=0.1077 | lr=2.71e-05 | epoch=0.5629
[train] step=264 | loss=0.0984 | lr=2.71e-05 | epoch=0.5650
[train] step=265 | loss=0.1383 | lr=2.71e-05 | epoch=0.5671
[train] step=266 | loss=0.1157 | lr=2.70e-05 | epoch=0.5693
[train] step=267 | loss=0.1155 | lr=2.70e-05 | epoch=0.5714
[train] step=268 | loss=0.1065 | lr=2.70e-05 | epoch=0.5736
[train] step=269 | loss=0.1163 | lr=2.70e-05 | epoch=0.5757
[train] step=270 | loss=0.1323 | lr=2.69e-05 | epoch=0.5778
[train] step=271 | loss=0.1167 | lr=2.69e-05 | epoch=0.5800
[train] step=272 | loss=0.1220 | lr=2.69e-05 | epoch=0.5821
[train] step=273 | loss=0.0987 | lr=2.69e-05 | epoch=0.5843
[train] step=274 | loss=0.1058 | lr=2.68e-05 | epoch=0.5864
[train] step=275 | loss=0.1235 | lr=2.68e-05 | epoch=0.5886
[train] step=276 | loss=0.1254 | lr=2.68e-05 | epoch=0.5907
[train] step=277 | loss=0.1065 | lr=2.68e-05 | epoch=0.5928
[train] step=278 | loss=0.1042 | lr=2.67e-05 | epoch=0.5950
[train] step=279 | loss=0.1027 | lr=2.67e-05 | epoch=0.5971
[train] step=280 | loss=0.1077 | lr=2.67e-05 | epoch=0.5993
[train] step=281 | loss=0.1080 | lr=2.67e-05 | epoch=0.6014
[train] step=282 | loss=0.1196 | lr=2.67e-05 | epoch=0.6035
[train] step=283 | loss=0.1191 | lr=2.66e-05 | epoch=0.6057
[train] step=284 | loss=0.1102 | lr=2.66e-05 | epoch=0.6078
[train] step=285 | loss=0.1030 | lr=2.66e-05 | epoch=0.6100
[train] step=286 | loss=0.1029 | lr=2.66e-05 | epoch=0.6121
[train] step=287 | loss=0.1168 | lr=2.65e-05 | epoch=0.6142
[train] step=288 | loss=0.1041 | lr=2.65e-05 | epoch=0.6164
[train] step=289 | loss=0.1028 | lr=2.65e-05 | epoch=0.6185
[train] step=290 | loss=0.1078 | lr=2.65e-05 | epoch=0.6207
[train] step=291 | loss=0.1305 | lr=2.64e-05 | epoch=0.6228
[train] step=292 | loss=0.1161 | lr=2.64e-05 | epoch=0.6249
[train] step=293 | loss=0.1404 | lr=2.64e-05 | epoch=0.6271
[train] step=294 | loss=0.1069 | lr=2.64e-05 | epoch=0.6292
[train] step=295 | loss=0.1245 | lr=2.63e-05 | epoch=0.6314
[train] step=296 | loss=0.1048 | lr=2.63e-05 | epoch=0.6335
[train] step=297 | loss=0.1164 | lr=2.63e-05 | epoch=0.6356
[train] step=298 | loss=0.1001 | lr=2.63e-05 | epoch=0.6378
[train] step=299 | loss=0.1076 | lr=2.63e-05 | epoch=0.6399
[train] step=300 | loss=0.1154 | lr=2.62e-05 | epoch=0.6421
[train] step=301 | loss=0.1195 | lr=2.62e-05 | epoch=0.6442
[train] step=302 | loss=0.1029 | lr=2.62e-05 | epoch=0.6463
[train] step=303 | loss=0.1126 | lr=2.62e-05 | epoch=0.6485
[train] step=304 | loss=0.1175 | lr=2.61e-05 | epoch=0.6506
[train] step=305 | loss=0.1029 | lr=2.61e-05 | epoch=0.6528
[train] step=306 | loss=0.1347 | lr=2.61e-05 | epoch=0.6549
[train] step=307 | loss=0.1334 | lr=2.61e-05 | epoch=0.6570
[train] step=308 | loss=0.1065 | lr=2.60e-05 | epoch=0.6592
[train] step=309 | loss=0.1335 | lr=2.60e-05 | epoch=0.6613
[train] step=310 | loss=0.0992 | lr=2.60e-05 | epoch=0.6635
[train] step=311 | loss=0.1013 | lr=2.60e-05 | epoch=0.6656
[train] step=312 | loss=0.1413 | lr=2.59e-05 | epoch=0.6677
[train] step=313 | loss=0.1423 | lr=2.59e-05 | epoch=0.6699
[train] step=314 | loss=0.1101 | lr=2.59e-05 | epoch=0.6720
[train] step=315 | loss=0.1012 | lr=2.59e-05 | epoch=0.6742
[train] step=316 | loss=0.1091 | lr=2.58e-05 | epoch=0.6763
[train] step=317 | loss=0.1127 | lr=2.58e-05 | epoch=0.6784
[train] step=318 | loss=0.1096 | lr=2.58e-05 | epoch=0.6806
[train] step=319 | loss=0.1371 | lr=2.58e-05 | epoch=0.6827
[train] step=320 | loss=0.1170 | lr=2.58e-05 | epoch=0.6849
[train] step=321 | loss=0.1085 | lr=2.57e-05 | epoch=0.6870
[train] step=322 | loss=0.1201 | lr=2.57e-05 | epoch=0.6891
[train] step=323 | loss=0.1144 | lr=2.57e-05 | epoch=0.6913
[train] step=324 | loss=0.1128 | lr=2.57e-05 | epoch=0.6934
[train] step=325 | loss=0.1183 | lr=2.56e-05 | epoch=0.6956
[train] step=326 | loss=0.1081 | lr=2.56e-05 | epoch=0.6977
[train] step=327 | loss=0.1160 | lr=2.56e-05 | epoch=0.6998
[train] step=328 | loss=0.1352 | lr=2.56e-05 | epoch=0.7020
[train] step=329 | loss=0.0900 | lr=2.55e-05 | epoch=0.7041
[train] step=330 | loss=0.0979 | lr=2.55e-05 | epoch=0.7063
[train] step=331 | loss=0.1082 | lr=2.55e-05 | epoch=0.7084
[train] step=332 | loss=0.1277 | lr=2.55e-05 | epoch=0.7105
[train] step=333 | loss=0.1343 | lr=2.54e-05 | epoch=0.7127
[train] step=334 | loss=0.1290 | lr=2.54e-05 | epoch=0.7148
[train] step=335 | loss=0.0870 | lr=2.54e-05 | epoch=0.7170
[train] step=336 | loss=0.1107 | lr=2.54e-05 | epoch=0.7191
[train] step=337 | loss=0.1027 | lr=2.53e-05 | epoch=0.7212
[train] step=338 | loss=0.1103 | lr=2.53e-05 | epoch=0.7234
[train] step=339 | loss=0.1195 | lr=2.53e-05 | epoch=0.7255
[train] step=340 | loss=0.1142 | lr=2.53e-05 | epoch=0.7277
[train] step=341 | loss=0.1456 | lr=2.53e-05 | epoch=0.7298
[train] step=342 | loss=0.1012 | lr=2.52e-05 | epoch=0.7319
[train] step=343 | loss=0.0916 | lr=2.52e-05 | epoch=0.7341
[train] step=344 | loss=0.1104 | lr=2.52e-05 | epoch=0.7362
[train] step=345 | loss=0.1232 | lr=2.52e-05 | epoch=0.7384
[train] step=346 | loss=0.1113 | lr=2.51e-05 | epoch=0.7405
[train] step=347 | loss=0.1042 | lr=2.51e-05 | epoch=0.7426
[train] step=348 | loss=0.1242 | lr=2.51e-05 | epoch=0.7448
[train] step=349 | loss=0.1067 | lr=2.51e-05 | epoch=0.7469
[train] step=350 | loss=0.0879 | lr=2.50e-05 | epoch=0.7491
[train] step=351 | loss=0.1222 | lr=2.50e-05 | epoch=0.7512
[train] step=352 | loss=0.1047 | lr=2.50e-05 | epoch=0.7533
[train] step=353 | loss=0.1359 | lr=2.50e-05 | epoch=0.7555
[train] step=354 | loss=0.0876 | lr=2.49e-05 | epoch=0.7576
[train] step=355 | loss=0.1208 | lr=2.49e-05 | epoch=0.7598
[train] step=356 | loss=0.1033 | lr=2.49e-05 | epoch=0.7619
[train] step=357 | loss=0.1185 | lr=2.49e-05 | epoch=0.7640
[train] step=358 | loss=0.0878 | lr=2.48e-05 | epoch=0.7662
[train] step=359 | loss=0.1081 | lr=2.48e-05 | epoch=0.7683
[train] step=360 | loss=0.1210 | lr=2.48e-05 | epoch=0.7705
[train] step=361 | loss=0.1094 | lr=2.48e-05 | epoch=0.7726
[train] step=362 | loss=0.1094 | lr=2.48e-05 | epoch=0.7747
[train] step=363 | loss=0.1343 | lr=2.47e-05 | epoch=0.7769
[train] step=364 | loss=0.1069 | lr=2.47e-05 | epoch=0.7790
[train] step=365 | loss=0.1012 | lr=2.47e-05 | epoch=0.7812
[train] step=366 | loss=0.1237 | lr=2.47e-05 | epoch=0.7833
[train] step=367 | loss=0.1004 | lr=2.46e-05 | epoch=0.7854
[train] step=368 | loss=0.1171 | lr=2.46e-05 | epoch=0.7876
[train] step=369 | loss=0.1201 | lr=2.46e-05 | epoch=0.7897
[train] step=370 | loss=0.1234 | lr=2.46e-05 | epoch=0.7919
[train] step=371 | loss=0.1277 | lr=2.45e-05 | epoch=0.7940
[train] step=372 | loss=0.1159 | lr=2.45e-05 | epoch=0.7961
[train] step=373 | loss=0.1316 | lr=2.45e-05 | epoch=0.7983
[train] step=374 | loss=0.1124 | lr=2.45e-05 | epoch=0.8004
[train] step=375 | loss=0.1198 | lr=2.44e-05 | epoch=0.8026
[train] step=376 | loss=0.1044 | lr=2.44e-05 | epoch=0.8047
[train] step=377 | loss=0.1001 | lr=2.44e-05 | epoch=0.8068
[train] step=378 | loss=0.1048 | lr=2.44e-05 | epoch=0.8090
[train] step=379 | loss=0.1448 | lr=2.44e-05 | epoch=0.8111
[train] step=380 | loss=0.1354 | lr=2.43e-05 | epoch=0.8133
[train] step=381 | loss=0.1361 | lr=2.43e-05 | epoch=0.8154
[train] step=382 | loss=0.1255 | lr=2.43e-05 | epoch=0.8175
[train] step=383 | loss=0.1017 | lr=2.43e-05 | epoch=0.8197
[train] step=384 | loss=0.0933 | lr=2.42e-05 | epoch=0.8218
[train] step=385 | loss=0.1211 | lr=2.42e-05 | epoch=0.8240
[train] step=386 | loss=0.1625 | lr=2.42e-05 | epoch=0.8261
[train] step=387 | loss=0.1006 | lr=2.42e-05 | epoch=0.8283
[train] step=388 | loss=0.1185 | lr=2.41e-05 | epoch=0.8304
[train] step=389 | loss=0.1022 | lr=2.41e-05 | epoch=0.8325
[train] step=390 | loss=0.1065 | lr=2.41e-05 | epoch=0.8347
[train] step=391 | loss=0.1012 | lr=2.41e-05 | epoch=0.8368
[train] step=392 | loss=0.0992 | lr=2.40e-05 | epoch=0.8390
[train] step=393 | loss=0.1085 | lr=2.40e-05 | epoch=0.8411
[train] step=394 | loss=0.1238 | lr=2.40e-05 | epoch=0.8432
[train] step=395 | loss=0.1169 | lr=2.40e-05 | epoch=0.8454
[train] step=396 | loss=0.1248 | lr=2.39e-05 | epoch=0.8475
[train] step=397 | loss=0.1069 | lr=2.39e-05 | epoch=0.8497
[train] step=398 | loss=0.1140 | lr=2.39e-05 | epoch=0.8518
[train] step=399 | loss=0.1098 | lr=2.39e-05 | epoch=0.8539
[train] step=400 | loss=0.1205 | lr=2.39e-05 | epoch=0.8561
[train] step=401 | loss=0.1189 | lr=2.38e-05 | epoch=0.8582
[train] step=402 | loss=0.1132 | lr=2.38e-05 | epoch=0.8604
[train] step=403 | loss=0.0915 | lr=2.38e-05 | epoch=0.8625
[train] step=404 | loss=0.1110 | lr=2.38e-05 | epoch=0.8646
[train] step=405 | loss=0.1149 | lr=2.37e-05 | epoch=0.8668
[train] step=406 | loss=0.1032 | lr=2.37e-05 | epoch=0.8689
[train] step=407 | loss=0.0882 | lr=2.37e-05 | epoch=0.8711
[train] step=408 | loss=0.1313 | lr=2.37e-05 | epoch=0.8732
[train] step=409 | loss=0.1155 | lr=2.36e-05 | epoch=0.8753
[train] step=410 | loss=0.0960 | lr=2.36e-05 | epoch=0.8775
[train] step=411 | loss=0.1058 | lr=2.36e-05 | epoch=0.8796
[train] step=412 | loss=0.1113 | lr=2.36e-05 | epoch=0.8818
[train] step=413 | loss=0.1084 | lr=2.35e-05 | epoch=0.8839
[train] step=414 | loss=0.1211 | lr=2.35e-05 | epoch=0.8860
[train] step=415 | loss=0.1034 | lr=2.35e-05 | epoch=0.8882
[train] step=416 | loss=0.1280 | lr=2.35e-05 | epoch=0.8903
[train] step=417 | loss=0.1223 | lr=2.34e-05 | epoch=0.8925
[train] step=418 | loss=0.1015 | lr=2.34e-05 | epoch=0.8946
[train] step=419 | loss=0.1015 | lr=2.34e-05 | epoch=0.8967
[train] step=420 | loss=0.1204 | lr=2.34e-05 | epoch=0.8989
[train] step=421 | loss=0.1042 | lr=2.34e-05 | epoch=0.9010
[train] step=422 | loss=0.0982 | lr=2.33e-05 | epoch=0.9032
[train] step=423 | loss=0.1242 | lr=2.33e-05 | epoch=0.9053
[train] step=424 | loss=0.1260 | lr=2.33e-05 | epoch=0.9074
[train] step=425 | loss=0.1146 | lr=2.33e-05 | epoch=0.9096
[train] step=426 | loss=0.1073 | lr=2.32e-05 | epoch=0.9117
[train] step=427 | loss=0.1136 | lr=2.32e-05 | epoch=0.9139
[train] step=428 | loss=0.1003 | lr=2.32e-05 | epoch=0.9160
[train] step=429 | loss=0.1142 | lr=2.32e-05 | epoch=0.9181
[train] step=430 | loss=0.1078 | lr=2.31e-05 | epoch=0.9203
[train] step=431 | loss=0.1021 | lr=2.31e-05 | epoch=0.9224
[train] step=432 | loss=0.1492 | lr=2.31e-05 | epoch=0.9246
[train] step=433 | loss=0.0990 | lr=2.31e-05 | epoch=0.9267
[train] step=434 | loss=0.0967 | lr=2.30e-05 | epoch=0.9288
[train] step=435 | loss=0.1165 | lr=2.30e-05 | epoch=0.9310
[train] step=436 | loss=0.1266 | lr=2.30e-05 | epoch=0.9331
[train] step=437 | loss=0.1023 | lr=2.30e-05 | epoch=0.9353
[train] step=438 | loss=0.0942 | lr=2.30e-05 | epoch=0.9374
[train] step=439 | loss=0.1337 | lr=2.29e-05 | epoch=0.9395
[train] step=440 | loss=0.1245 | lr=2.29e-05 | epoch=0.9417
[train] step=441 | loss=0.1173 | lr=2.29e-05 | epoch=0.9438
[train] step=442 | loss=0.1434 | lr=2.29e-05 | epoch=0.9460
[train] step=443 | loss=0.1052 | lr=2.28e-05 | epoch=0.9481
[train] step=444 | loss=0.1085 | lr=2.28e-05 | epoch=0.9502
[train] step=445 | loss=0.1116 | lr=2.28e-05 | epoch=0.9524
[train] step=446 | loss=0.0946 | lr=2.28e-05 | epoch=0.9545
[train] step=447 | loss=0.0946 | lr=2.27e-05 | epoch=0.9567
[train] step=448 | loss=0.1249 | lr=2.27e-05 | epoch=0.9588
[train] step=449 | loss=0.1264 | lr=2.27e-05 | epoch=0.9609
[train] step=450 | loss=0.0912 | lr=2.27e-05 | epoch=0.9631
[train] step=451 | loss=0.1105 | lr=2.26e-05 | epoch=0.9652
[train] step=452 | loss=0.1075 | lr=2.26e-05 | epoch=0.9674
[train] step=453 | loss=0.0998 | lr=2.26e-05 | epoch=0.9695
[train] step=454 | loss=0.1082 | lr=2.26e-05 | epoch=0.9716
[train] step=455 | loss=0.1048 | lr=2.25e-05 | epoch=0.9738
[train] step=456 | loss=0.1222 | lr=2.25e-05 | epoch=0.9759
[train] step=457 | loss=0.1278 | lr=2.25e-05 | epoch=0.9781
[train] step=458 | loss=0.1196 | lr=2.25e-05 | epoch=0.9802
[train] step=459 | loss=0.1254 | lr=2.25e-05 | epoch=0.9823
[train] step=460 | loss=0.1097 | lr=2.24e-05 | epoch=0.9845
[train] step=461 | loss=0.1117 | lr=2.24e-05 | epoch=0.9866
[train] step=462 | loss=0.1111 | lr=2.24e-05 | epoch=0.9888
[train] step=463 | loss=0.0998 | lr=2.24e-05 | epoch=0.9909
[train] step=464 | loss=0.1207 | lr=2.23e-05 | epoch=0.9930
[train] step=465 | loss=0.1060 | lr=2.23e-05 | epoch=0.9952
[train] step=466 | loss=0.1069 | lr=2.23e-05 | epoch=0.9973

Saving model checkpoint to output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-466
2026-04-06 02:08:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:08:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 02:08:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:08:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-466\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-466\tokenizer_config.json

[train] step=467 | loss=0.1172 | lr=2.23e-05 | epoch=0.9995
[train] step=468 | loss=0.0636 | lr=2.22e-05 | epoch=1.0000
[train] step=469 | loss=0.0948 | lr=2.22e-05 | epoch=1.0021
[train] step=470 | loss=0.1104 | lr=2.22e-05 | epoch=1.0043
[train] step=471 | loss=0.1156 | lr=2.22e-05 | epoch=1.0064
[train] step=472 | loss=0.1269 | lr=2.21e-05 | epoch=1.0086
[train] step=473 | loss=0.1118 | lr=2.21e-05 | epoch=1.0107
[train] step=474 | loss=0.1082 | lr=2.21e-05 | epoch=1.0128
[train] step=475 | loss=0.1077 | lr=2.21e-05 | epoch=1.0150
[train] step=476 | loss=0.1213 | lr=2.20e-05 | epoch=1.0171
[train] step=477 | loss=0.1318 | lr=2.20e-05 | epoch=1.0193
[train] step=478 | loss=0.0898 | lr=2.20e-05 | epoch=1.0214
[train] step=479 | loss=0.1219 | lr=2.20e-05 | epoch=1.0235
[train] step=480 | loss=0.0910 | lr=2.20e-05 | epoch=1.0257
[train] step=481 | loss=0.1185 | lr=2.19e-05 | epoch=1.0278
[train] step=482 | loss=0.1289 | lr=2.19e-05 | epoch=1.0300
[train] step=483 | loss=0.0922 | lr=2.19e-05 | epoch=1.0321
[train] step=484 | loss=0.1149 | lr=2.19e-05 | epoch=1.0342
[train] step=485 | loss=0.0922 | lr=2.18e-05 | epoch=1.0364
[train] step=486 | loss=0.1120 | lr=2.18e-05 | epoch=1.0385
[train] step=487 | loss=0.1397 | lr=2.18e-05 | epoch=1.0407
[train] step=488 | loss=0.1245 | lr=2.18e-05 | epoch=1.0428
[train] step=489 | loss=0.0995 | lr=2.17e-05 | epoch=1.0449
[train] step=490 | loss=0.1084 | lr=2.17e-05 | epoch=1.0471
[train] step=491 | loss=0.1061 | lr=2.17e-05 | epoch=1.0492
[train] step=492 | loss=0.1241 | lr=2.17e-05 | epoch=1.0514
[train] step=493 | loss=0.0992 | lr=2.16e-05 | epoch=1.0535
[train] step=494 | loss=0.1165 | lr=2.16e-05 | epoch=1.0556
[train] step=495 | loss=0.1037 | lr=2.16e-05 | epoch=1.0578
[train] step=496 | loss=0.1185 | lr=2.16e-05 | epoch=1.0599
[train] step=497 | loss=0.1072 | lr=2.16e-05 | epoch=1.0621
[train] step=498 | loss=0.1381 | lr=2.15e-05 | epoch=1.0642
[train] step=499 | loss=0.1198 | lr=2.15e-05 | epoch=1.0663
[train] step=500 | loss=0.1166 | lr=2.15e-05 | epoch=1.0685
[train] step=501 | loss=0.1042 | lr=2.15e-05 | epoch=1.0706
[train] step=502 | loss=0.1029 | lr=2.14e-05 | epoch=1.0728
[train] step=503 | loss=0.1498 | lr=2.14e-05 | epoch=1.0749
[train] step=504 | loss=0.1256 | lr=2.14e-05 | epoch=1.0770
[train] step=505 | loss=0.1238 | lr=2.14e-05 | epoch=1.0792
[train] step=506 | loss=0.1040 | lr=2.13e-05 | epoch=1.0813
[train] step=507 | loss=0.1150 | lr=2.13e-05 | epoch=1.0835
[train] step=508 | loss=0.1201 | lr=2.13e-05 | epoch=1.0856
[train] step=509 | loss=0.1555 | lr=2.13e-05 | epoch=1.0877
[train] step=510 | loss=0.1235 | lr=2.12e-05 | epoch=1.0899
[train] step=511 | loss=0.1154 | lr=2.12e-05 | epoch=1.0920
[train] step=512 | loss=0.1120 | lr=2.12e-05 | epoch=1.0942
[train] step=513 | loss=0.0973 | lr=2.12e-05 | epoch=1.0963
[train] step=514 | loss=0.1083 | lr=2.11e-05 | epoch=1.0984
[train] step=515 | loss=0.1130 | lr=2.11e-05 | epoch=1.1006
[train] step=516 | loss=0.1269 | lr=2.11e-05 | epoch=1.1027
[train] step=517 | loss=0.0974 | lr=2.11e-05 | epoch=1.1049
[train] step=518 | loss=0.1372 | lr=2.11e-05 | epoch=1.1070
[train] step=519 | loss=0.1170 | lr=2.10e-05 | epoch=1.1091
[train] step=520 | loss=0.1128 | lr=2.10e-05 | epoch=1.1113
[train] step=521 | loss=0.1074 | lr=2.10e-05 | epoch=1.1134
[train] step=522 | loss=0.1336 | lr=2.10e-05 | epoch=1.1156
[train] step=523 | loss=0.1065 | lr=2.09e-05 | epoch=1.1177
[train] step=524 | loss=0.1090 | lr=2.09e-05 | epoch=1.1199
[train] step=525 | loss=0.0935 | lr=2.09e-05 | epoch=1.1220
[train] step=526 | loss=0.1103 | lr=2.09e-05 | epoch=1.1241
[train] step=527 | loss=0.0976 | lr=2.08e-05 | epoch=1.1263
[train] step=528 | loss=0.1282 | lr=2.08e-05 | epoch=1.1284
[train] step=529 | loss=0.1126 | lr=2.08e-05 | epoch=1.1306
[train] step=530 | loss=0.1156 | lr=2.08e-05 | epoch=1.1327
[train] step=531 | loss=0.1416 | lr=2.07e-05 | epoch=1.1348
[train] step=532 | loss=0.1155 | lr=2.07e-05 | epoch=1.1370
[train] step=533 | loss=0.1127 | lr=2.07e-05 | epoch=1.1391
[train] step=534 | loss=0.1117 | lr=2.07e-05 | epoch=1.1413
[train] step=535 | loss=0.1142 | lr=2.06e-05 | epoch=1.1434
[train] step=536 | loss=0.1218 | lr=2.06e-05 | epoch=1.1455
[train] step=537 | loss=0.1018 | lr=2.06e-05 | epoch=1.1477
[train] step=538 | loss=0.1175 | lr=2.06e-05 | epoch=1.1498
[train] step=539 | loss=0.1116 | lr=2.06e-05 | epoch=1.1520
[train] step=540 | loss=0.0937 | lr=2.05e-05 | epoch=1.1541
[train] step=541 | loss=0.0849 | lr=2.05e-05 | epoch=1.1562
[train] step=542 | loss=0.1211 | lr=2.05e-05 | epoch=1.1584
[train] step=543 | loss=0.1066 | lr=2.05e-05 | epoch=1.1605
[train] step=544 | loss=0.0927 | lr=2.04e-05 | epoch=1.1627
[train] step=545 | loss=0.1036 | lr=2.04e-05 | epoch=1.1648
[train] step=546 | loss=0.0940 | lr=2.04e-05 | epoch=1.1669
[train] step=547 | loss=0.0996 | lr=2.04e-05 | epoch=1.1691
[train] step=548 | loss=0.1060 | lr=2.03e-05 | epoch=1.1712
[train] step=549 | loss=0.0838 | lr=2.03e-05 | epoch=1.1734
[train] step=550 | loss=0.1026 | lr=2.03e-05 | epoch=1.1755
[train] step=551 | loss=0.1098 | lr=2.03e-05 | epoch=1.1776
[train] step=552 | loss=0.1123 | lr=2.02e-05 | epoch=1.1798
[train] step=553 | loss=0.1213 | lr=2.02e-05 | epoch=1.1819
[train] step=554 | loss=0.1013 | lr=2.02e-05 | epoch=1.1841
[train] step=555 | loss=0.1039 | lr=2.02e-05 | epoch=1.1862
[train] step=556 | loss=0.0998 | lr=2.02e-05 | epoch=1.1883
[train] step=557 | loss=0.1289 | lr=2.01e-05 | epoch=1.1905
[train] step=558 | loss=0.1109 | lr=2.01e-05 | epoch=1.1926
[train] step=559 | loss=0.1185 | lr=2.01e-05 | epoch=1.1948
[train] step=560 | loss=0.1079 | lr=2.01e-05 | epoch=1.1969
[train] step=561 | loss=0.1105 | lr=2.00e-05 | epoch=1.1990
[train] step=562 | loss=0.1115 | lr=2.00e-05 | epoch=1.2012
[train] step=563 | loss=0.1227 | lr=2.00e-05 | epoch=1.2033
[train] step=564 | loss=0.1025 | lr=2.00e-05 | epoch=1.2055
[train] step=565 | loss=0.1376 | lr=1.99e-05 | epoch=1.2076
[train] step=566 | loss=0.1161 | lr=1.99e-05 | epoch=1.2097
[train] step=567 | loss=0.0994 | lr=1.99e-05 | epoch=1.2119
[train] step=568 | loss=0.1011 | lr=1.99e-05 | epoch=1.2140
[train] step=569 | loss=0.1137 | lr=1.98e-05 | epoch=1.2162
[train] step=570 | loss=0.0989 | lr=1.98e-05 | epoch=1.2183
[train] step=571 | loss=0.1077 | lr=1.98e-05 | epoch=1.2204
[train] step=572 | loss=0.1155 | lr=1.98e-05 | epoch=1.2226
[train] step=573 | loss=0.1333 | lr=1.97e-05 | epoch=1.2247
[train] step=574 | loss=0.0999 | lr=1.97e-05 | epoch=1.2269
[train] step=575 | loss=0.1095 | lr=1.97e-05 | epoch=1.2290
[train] step=576 | loss=0.1123 | lr=1.97e-05 | epoch=1.2311
[train] step=577 | loss=0.1430 | lr=1.97e-05 | epoch=1.2333
[train] step=578 | loss=0.1163 | lr=1.96e-05 | epoch=1.2354
[train] step=579 | loss=0.1261 | lr=1.96e-05 | epoch=1.2376
[train] step=580 | loss=0.1029 | lr=1.96e-05 | epoch=1.2397
[train] step=581 | loss=0.1058 | lr=1.96e-05 | epoch=1.2418
[train] step=582 | loss=0.1055 | lr=1.95e-05 | epoch=1.2440
[train] step=583 | loss=0.1211 | lr=1.95e-05 | epoch=1.2461
[train] step=584 | loss=0.1056 | lr=1.95e-05 | epoch=1.2483
[train] step=585 | loss=0.1202 | lr=1.95e-05 | epoch=1.2504
[train] step=586 | loss=0.0979 | lr=1.94e-05 | epoch=1.2525
[train] step=587 | loss=0.1150 | lr=1.94e-05 | epoch=1.2547
[train] step=588 | loss=0.1315 | lr=1.94e-05 | epoch=1.2568
[train] step=589 | loss=0.1396 | lr=1.94e-05 | epoch=1.2590
[train] step=590 | loss=0.1290 | lr=1.93e-05 | epoch=1.2611
[train] step=591 | loss=0.0954 | lr=1.93e-05 | epoch=1.2632
[train] step=592 | loss=0.1178 | lr=1.93e-05 | epoch=1.2654
[train] step=593 | loss=0.1056 | lr=1.93e-05 | epoch=1.2675
[train] step=594 | loss=0.0997 | lr=1.92e-05 | epoch=1.2697
[train] step=595 | loss=0.0860 | lr=1.92e-05 | epoch=1.2718
[train] step=596 | loss=0.1042 | lr=1.92e-05 | epoch=1.2739
[train] step=597 | loss=0.1062 | lr=1.92e-05 | epoch=1.2761
[train] step=598 | loss=0.1099 | lr=1.92e-05 | epoch=1.2782
[train] step=599 | loss=0.1057 | lr=1.91e-05 | epoch=1.2804
[train] step=600 | loss=0.1228 | lr=1.91e-05 | epoch=1.2825
[train] step=601 | loss=0.1170 | lr=1.91e-05 | epoch=1.2846
[train] step=602 | loss=0.1012 | lr=1.91e-05 | epoch=1.2868
[train] step=603 | loss=0.0946 | lr=1.90e-05 | epoch=1.2889
[train] step=604 | loss=0.1024 | lr=1.90e-05 | epoch=1.2911
[train] step=605 | loss=0.1011 | lr=1.90e-05 | epoch=1.2932
[train] step=606 | loss=0.0848 | lr=1.90e-05 | epoch=1.2953
[train] step=607 | loss=0.1164 | lr=1.89e-05 | epoch=1.2975
[train] step=608 | loss=0.0874 | lr=1.89e-05 | epoch=1.2996
[train] step=609 | loss=0.1268 | lr=1.89e-05 | epoch=1.3018
[train] step=610 | loss=0.1220 | lr=1.89e-05 | epoch=1.3039
[train] step=611 | loss=0.0885 | lr=1.88e-05 | epoch=1.3060
[train] step=612 | loss=0.1140 | lr=1.88e-05 | epoch=1.3082
[train] step=613 | loss=0.1245 | lr=1.88e-05 | epoch=1.3103
[train] step=614 | loss=0.1097 | lr=1.88e-05 | epoch=1.3125
[train] step=615 | loss=0.1105 | lr=1.88e-05 | epoch=1.3146
[train] step=616 | loss=0.1037 | lr=1.87e-05 | epoch=1.3167
[train] step=617 | loss=0.0814 | lr=1.87e-05 | epoch=1.3189
[train] step=618 | loss=0.1173 | lr=1.87e-05 | epoch=1.3210
[train] step=619 | loss=0.1143 | lr=1.87e-05 | epoch=1.3232
[train] step=620 | loss=0.1048 | lr=1.86e-05 | epoch=1.3253
[train] step=621 | loss=0.1269 | lr=1.86e-05 | epoch=1.3274
[train] step=622 | loss=0.1042 | lr=1.86e-05 | epoch=1.3296
[train] step=623 | loss=0.1083 | lr=1.86e-05 | epoch=1.3317
[train] step=624 | loss=0.1148 | lr=1.85e-05 | epoch=1.3339
[train] step=625 | loss=0.1063 | lr=1.85e-05 | epoch=1.3360
[train] step=626 | loss=0.0965 | lr=1.85e-05 | epoch=1.3381
[train] step=627 | loss=0.1436 | lr=1.85e-05 | epoch=1.3403
[train] step=628 | loss=0.0991 | lr=1.84e-05 | epoch=1.3424
[train] step=629 | loss=0.0817 | lr=1.84e-05 | epoch=1.3446
[train] step=630 | loss=0.1131 | lr=1.84e-05 | epoch=1.3467
[train] step=631 | loss=0.1037 | lr=1.84e-05 | epoch=1.3488
[train] step=632 | loss=0.1138 | lr=1.83e-05 | epoch=1.3510
[train] step=633 | loss=0.1156 | lr=1.83e-05 | epoch=1.3531
[train] step=634 | loss=0.1210 | lr=1.83e-05 | epoch=1.3553
[train] step=635 | loss=0.1055 | lr=1.83e-05 | epoch=1.3574
[train] step=636 | loss=0.1072 | lr=1.83e-05 | epoch=1.3596
[train] step=637 | loss=0.1020 | lr=1.82e-05 | epoch=1.3617
[train] step=638 | loss=0.1155 | lr=1.82e-05 | epoch=1.3638
[train] step=639 | loss=0.1154 | lr=1.82e-05 | epoch=1.3660
[train] step=640 | loss=0.0874 | lr=1.82e-05 | epoch=1.3681
[train] step=641 | loss=0.1066 | lr=1.81e-05 | epoch=1.3703
[train] step=642 | loss=0.1068 | lr=1.81e-05 | epoch=1.3724
[train] step=643 | loss=0.1281 | lr=1.81e-05 | epoch=1.3745
[train] step=644 | loss=0.1235 | lr=1.81e-05 | epoch=1.3767
[train] step=645 | loss=0.1251 | lr=1.80e-05 | epoch=1.3788
[train] step=646 | loss=0.1066 | lr=1.80e-05 | epoch=1.3810
[train] step=647 | loss=0.0932 | lr=1.80e-05 | epoch=1.3831
[train] step=648 | loss=0.1123 | lr=1.80e-05 | epoch=1.3852
[train] step=649 | loss=0.0743 | lr=1.79e-05 | epoch=1.3874
[train] step=650 | loss=0.0941 | lr=1.79e-05 | epoch=1.3895
[train] step=651 | loss=0.0907 | lr=1.79e-05 | epoch=1.3917
[train] step=652 | loss=0.1050 | lr=1.79e-05 | epoch=1.3938
[train] step=653 | loss=0.1228 | lr=1.78e-05 | epoch=1.3959
[train] step=654 | loss=0.0909 | lr=1.78e-05 | epoch=1.3981
[train] step=655 | loss=0.0893 | lr=1.78e-05 | epoch=1.4002
[train] step=656 | loss=0.1161 | lr=1.78e-05 | epoch=1.4024
[train] step=657 | loss=0.1048 | lr=1.78e-05 | epoch=1.4045
[train] step=658 | loss=0.1104 | lr=1.77e-05 | epoch=1.4066
[train] step=659 | loss=0.1194 | lr=1.77e-05 | epoch=1.4088
[train] step=660 | loss=0.1056 | lr=1.77e-05 | epoch=1.4109
[train] step=661 | loss=0.1507 | lr=1.77e-05 | epoch=1.4131
[train] step=662 | loss=0.1121 | lr=1.76e-05 | epoch=1.4152
[train] step=663 | loss=0.1206 | lr=1.76e-05 | epoch=1.4173
[train] step=664 | loss=0.1169 | lr=1.76e-05 | epoch=1.4195
[train] step=665 | loss=0.1011 | lr=1.76e-05 | epoch=1.4216
[train] step=666 | loss=0.0919 | lr=1.75e-05 | epoch=1.4238
[train] step=667 | loss=0.0977 | lr=1.75e-05 | epoch=1.4259
[train] step=668 | loss=0.1047 | lr=1.75e-05 | epoch=1.4280
[train] step=669 | loss=0.1086 | lr=1.75e-05 | epoch=1.4302
[train] step=670 | loss=0.1121 | lr=1.74e-05 | epoch=1.4323
[train] step=671 | loss=0.1105 | lr=1.74e-05 | epoch=1.4345
[train] step=672 | loss=0.0887 | lr=1.74e-05 | epoch=1.4366
[train] step=673 | loss=0.1317 | lr=1.74e-05 | epoch=1.4387
[train] step=674 | loss=0.1166 | lr=1.73e-05 | epoch=1.4409
[train] step=675 | loss=0.0922 | lr=1.73e-05 | epoch=1.4430
[train] step=676 | loss=0.1089 | lr=1.73e-05 | epoch=1.4452
[train] step=677 | loss=0.0972 | lr=1.73e-05 | epoch=1.4473
[train] step=678 | loss=0.0960 | lr=1.73e-05 | epoch=1.4494
[train] step=679 | loss=0.0978 | lr=1.72e-05 | epoch=1.4516
[train] step=680 | loss=0.0976 | lr=1.72e-05 | epoch=1.4537
[train] step=681 | loss=0.1166 | lr=1.72e-05 | epoch=1.4559
[train] step=682 | loss=0.1065 | lr=1.72e-05 | epoch=1.4580
[train] step=683 | loss=0.0963 | lr=1.71e-05 | epoch=1.4601
[train] step=684 | loss=0.1069 | lr=1.71e-05 | epoch=1.4623
[train] step=685 | loss=0.1248 | lr=1.71e-05 | epoch=1.4644
[train] step=686 | loss=0.1095 | lr=1.71e-05 | epoch=1.4666
[train] step=687 | loss=0.1025 | lr=1.70e-05 | epoch=1.4687
[train] step=688 | loss=0.1358 | lr=1.70e-05 | epoch=1.4708
[train] step=689 | loss=0.1106 | lr=1.70e-05 | epoch=1.4730
[train] step=690 | loss=0.1237 | lr=1.70e-05 | epoch=1.4751
[train] step=691 | loss=0.0860 | lr=1.69e-05 | epoch=1.4773
[train] step=692 | loss=0.1130 | lr=1.69e-05 | epoch=1.4794
[train] step=693 | loss=0.1025 | lr=1.69e-05 | epoch=1.4815
[train] step=694 | loss=0.1137 | lr=1.69e-05 | epoch=1.4837
[train] step=695 | loss=0.0921 | lr=1.69e-05 | epoch=1.4858
[train] step=696 | loss=0.1161 | lr=1.68e-05 | epoch=1.4880
[train] step=697 | loss=0.1300 | lr=1.68e-05 | epoch=1.4901
[train] step=698 | loss=0.1202 | lr=1.68e-05 | epoch=1.4922
[train] step=699 | loss=0.1235 | lr=1.68e-05 | epoch=1.4944

Saving model checkpoint to output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-699
2026-04-06 02:18:56 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:18:56 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 02:18:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:18:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-699\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-699\tokenizer_config.json

[train] step=700 | loss=0.0990 | lr=1.67e-05 | epoch=1.4965
[train] step=701 | loss=0.1253 | lr=1.67e-05 | epoch=1.4987
[train] step=702 | loss=0.0968 | lr=1.67e-05 | epoch=1.5008
[train] step=703 | loss=0.1060 | lr=1.67e-05 | epoch=1.5029
[train] step=704 | loss=0.0995 | lr=1.66e-05 | epoch=1.5051
[train] step=705 | loss=0.1271 | lr=1.66e-05 | epoch=1.5072
[train] step=706 | loss=0.1210 | lr=1.66e-05 | epoch=1.5094
[train] step=707 | loss=0.1144 | lr=1.66e-05 | epoch=1.5115
[train] step=708 | loss=0.1023 | lr=1.65e-05 | epoch=1.5136
[train] step=709 | loss=0.0909 | lr=1.65e-05 | epoch=1.5158
[train] step=710 | loss=0.1098 | lr=1.65e-05 | epoch=1.5179
[train] step=711 | loss=0.1039 | lr=1.65e-05 | epoch=1.5201
[train] step=712 | loss=0.1077 | lr=1.64e-05 | epoch=1.5222
[train] step=713 | loss=0.0936 | lr=1.64e-05 | epoch=1.5243
[train] step=714 | loss=0.0907 | lr=1.64e-05 | epoch=1.5265
[train] step=715 | loss=0.0846 | lr=1.64e-05 | epoch=1.5286
[train] step=716 | loss=0.1120 | lr=1.64e-05 | epoch=1.5308
[train] step=717 | loss=0.1145 | lr=1.63e-05 | epoch=1.5329
[train] step=718 | loss=0.1101 | lr=1.63e-05 | epoch=1.5350
[train] step=719 | loss=0.0809 | lr=1.63e-05 | epoch=1.5372
[train] step=720 | loss=0.1168 | lr=1.63e-05 | epoch=1.5393
[train] step=721 | loss=0.1121 | lr=1.62e-05 | epoch=1.5415
[train] step=722 | loss=0.1041 | lr=1.62e-05 | epoch=1.5436
[train] step=723 | loss=0.1156 | lr=1.62e-05 | epoch=1.5457
[train] step=724 | loss=0.0967 | lr=1.62e-05 | epoch=1.5479
[train] step=725 | loss=0.1664 | lr=1.61e-05 | epoch=1.5500
[train] step=726 | loss=0.1099 | lr=1.61e-05 | epoch=1.5522
[train] step=727 | loss=0.1065 | lr=1.61e-05 | epoch=1.5543
[train] step=728 | loss=0.1027 | lr=1.61e-05 | epoch=1.5564
[train] step=729 | loss=0.1113 | lr=1.60e-05 | epoch=1.5586
[train] step=730 | loss=0.1122 | lr=1.60e-05 | epoch=1.5607
[train] step=731 | loss=0.1096 | lr=1.60e-05 | epoch=1.5629
[train] step=732 | loss=0.1180 | lr=1.60e-05 | epoch=1.5650
[train] step=733 | loss=0.0851 | lr=1.59e-05 | epoch=1.5671
[train] step=734 | loss=0.1047 | lr=1.59e-05 | epoch=1.5693
[train] step=735 | loss=0.1053 | lr=1.59e-05 | epoch=1.5714
[train] step=736 | loss=0.1063 | lr=1.59e-05 | epoch=1.5736
[train] step=737 | loss=0.1058 | lr=1.59e-05 | epoch=1.5757
[train] step=738 | loss=0.1098 | lr=1.58e-05 | epoch=1.5778
[train] step=739 | loss=0.1101 | lr=1.58e-05 | epoch=1.5800
[train] step=740 | loss=0.1281 | lr=1.58e-05 | epoch=1.5821
[train] step=741 | loss=0.1145 | lr=1.58e-05 | epoch=1.5843
[train] step=742 | loss=0.1225 | lr=1.57e-05 | epoch=1.5864
[train] step=743 | loss=0.1081 | lr=1.57e-05 | epoch=1.5886
[train] step=744 | loss=0.1166 | lr=1.57e-05 | epoch=1.5907
[train] step=745 | loss=0.0894 | lr=1.57e-05 | epoch=1.5928
[train] step=746 | loss=0.1100 | lr=1.56e-05 | epoch=1.5950
[train] step=747 | loss=0.1335 | lr=1.56e-05 | epoch=1.5971
[train] step=748 | loss=0.0973 | lr=1.56e-05 | epoch=1.5993
[train] step=749 | loss=0.1014 | lr=1.56e-05 | epoch=1.6014
[train] step=750 | loss=0.1136 | lr=1.55e-05 | epoch=1.6035
[train] step=751 | loss=0.1153 | lr=1.55e-05 | epoch=1.6057
[train] step=752 | loss=0.1070 | lr=1.55e-05 | epoch=1.6078
[train] step=753 | loss=0.1253 | lr=1.55e-05 | epoch=1.6100
[train] step=754 | loss=0.1106 | lr=1.55e-05 | epoch=1.6121
[train] step=755 | loss=0.1140 | lr=1.54e-05 | epoch=1.6142
[train] step=756 | loss=0.1151 | lr=1.54e-05 | epoch=1.6164
[train] step=757 | loss=0.0979 | lr=1.54e-05 | epoch=1.6185
[train] step=758 | loss=0.0974 | lr=1.54e-05 | epoch=1.6207
[train] step=759 | loss=0.0962 | lr=1.53e-05 | epoch=1.6228
[train] step=760 | loss=0.0826 | lr=1.53e-05 | epoch=1.6249
[train] step=761 | loss=0.1002 | lr=1.53e-05 | epoch=1.6271
[train] step=762 | loss=0.1207 | lr=1.53e-05 | epoch=1.6292
[train] step=763 | loss=0.1191 | lr=1.52e-05 | epoch=1.6314
[train] step=764 | loss=0.1378 | lr=1.52e-05 | epoch=1.6335
[train] step=765 | loss=0.1036 | lr=1.52e-05 | epoch=1.6356
[train] step=766 | loss=0.1297 | lr=1.52e-05 | epoch=1.6378
[train] step=767 | loss=0.1313 | lr=1.51e-05 | epoch=1.6399
[train] step=768 | loss=0.0927 | lr=1.51e-05 | epoch=1.6421
[train] step=769 | loss=0.1161 | lr=1.51e-05 | epoch=1.6442
[train] step=770 | loss=0.0889 | lr=1.51e-05 | epoch=1.6463
[train] step=771 | loss=0.1120 | lr=1.50e-05 | epoch=1.6485
[train] step=772 | loss=0.0947 | lr=1.50e-05 | epoch=1.6506
[train] step=773 | loss=0.1005 | lr=1.50e-05 | epoch=1.6528
[train] step=774 | loss=0.0851 | lr=1.50e-05 | epoch=1.6549
[train] step=775 | loss=0.1132 | lr=1.50e-05 | epoch=1.6570
[train] step=776 | loss=0.0895 | lr=1.49e-05 | epoch=1.6592
[train] step=777 | loss=0.1115 | lr=1.49e-05 | epoch=1.6613
[train] step=778 | loss=0.1134 | lr=1.49e-05 | epoch=1.6635
[train] step=779 | loss=0.1132 | lr=1.49e-05 | epoch=1.6656
[train] step=780 | loss=0.1321 | lr=1.48e-05 | epoch=1.6677
[train] step=781 | loss=0.0955 | lr=1.48e-05 | epoch=1.6699
[train] step=782 | loss=0.1005 | lr=1.48e-05 | epoch=1.6720
[train] step=783 | loss=0.1072 | lr=1.48e-05 | epoch=1.6742
[train] step=784 | loss=0.1141 | lr=1.47e-05 | epoch=1.6763
[train] step=785 | loss=0.0875 | lr=1.47e-05 | epoch=1.6784
[train] step=786 | loss=0.1076 | lr=1.47e-05 | epoch=1.6806
[train] step=787 | loss=0.1033 | lr=1.47e-05 | epoch=1.6827
[train] step=788 | loss=0.1224 | lr=1.46e-05 | epoch=1.6849
[train] step=789 | loss=0.1150 | lr=1.46e-05 | epoch=1.6870
[train] step=790 | loss=0.1078 | lr=1.46e-05 | epoch=1.6891
[train] step=791 | loss=0.0993 | lr=1.46e-05 | epoch=1.6913
[train] step=792 | loss=0.1033 | lr=1.45e-05 | epoch=1.6934
[train] step=793 | loss=0.1174 | lr=1.45e-05 | epoch=1.6956
[train] step=794 | loss=0.1102 | lr=1.45e-05 | epoch=1.6977
[train] step=795 | loss=0.1030 | lr=1.45e-05 | epoch=1.6998
[train] step=796 | loss=0.1276 | lr=1.45e-05 | epoch=1.7020
[train] step=797 | loss=0.1129 | lr=1.44e-05 | epoch=1.7041
[train] step=798 | loss=0.1131 | lr=1.44e-05 | epoch=1.7063
[train] step=799 | loss=0.1110 | lr=1.44e-05 | epoch=1.7084
[train] step=800 | loss=0.1086 | lr=1.44e-05 | epoch=1.7105
[train] step=801 | loss=0.1254 | lr=1.43e-05 | epoch=1.7127
[train] step=802 | loss=0.1130 | lr=1.43e-05 | epoch=1.7148
[train] step=803 | loss=0.1299 | lr=1.43e-05 | epoch=1.7170
[train] step=804 | loss=0.1023 | lr=1.43e-05 | epoch=1.7191
[train] step=805 | loss=0.1058 | lr=1.42e-05 | epoch=1.7212
[train] step=806 | loss=0.1050 | lr=1.42e-05 | epoch=1.7234
[train] step=807 | loss=0.1141 | lr=1.42e-05 | epoch=1.7255
[train] step=808 | loss=0.0795 | lr=1.42e-05 | epoch=1.7277
[train] step=809 | loss=0.0997 | lr=1.41e-05 | epoch=1.7298
[train] step=810 | loss=0.1164 | lr=1.41e-05 | epoch=1.7319
[train] step=811 | loss=0.1004 | lr=1.41e-05 | epoch=1.7341
[train] step=812 | loss=0.1187 | lr=1.41e-05 | epoch=1.7362
[train] step=813 | loss=0.1058 | lr=1.41e-05 | epoch=1.7384
[train] step=814 | loss=0.0919 | lr=1.40e-05 | epoch=1.7405
[train] step=815 | loss=0.0914 | lr=1.40e-05 | epoch=1.7426
[train] step=816 | loss=0.1278 | lr=1.40e-05 | epoch=1.7448
[train] step=817 | loss=0.1092 | lr=1.40e-05 | epoch=1.7469
[train] step=818 | loss=0.1246 | lr=1.39e-05 | epoch=1.7491
[train] step=819 | loss=0.0964 | lr=1.39e-05 | epoch=1.7512
[train] step=820 | loss=0.1106 | lr=1.39e-05 | epoch=1.7533
[train] step=821 | loss=0.1188 | lr=1.39e-05 | epoch=1.7555
[train] step=822 | loss=0.0989 | lr=1.38e-05 | epoch=1.7576
[train] step=823 | loss=0.1187 | lr=1.38e-05 | epoch=1.7598
[train] step=824 | loss=0.0935 | lr=1.38e-05 | epoch=1.7619
[train] step=825 | loss=0.1039 | lr=1.38e-05 | epoch=1.7640
[train] step=826 | loss=0.0945 | lr=1.37e-05 | epoch=1.7662
[train] step=827 | loss=0.0991 | lr=1.37e-05 | epoch=1.7683
[train] step=828 | loss=0.1060 | lr=1.37e-05 | epoch=1.7705
[train] step=829 | loss=0.0930 | lr=1.37e-05 | epoch=1.7726
[train] step=830 | loss=0.1090 | lr=1.36e-05 | epoch=1.7747
[train] step=831 | loss=0.0966 | lr=1.36e-05 | epoch=1.7769
[train] step=832 | loss=0.1252 | lr=1.36e-05 | epoch=1.7790
[train] step=833 | loss=0.1266 | lr=1.36e-05 | epoch=1.7812
[train] step=834 | loss=0.1000 | lr=1.36e-05 | epoch=1.7833
[train] step=835 | loss=0.1297 | lr=1.35e-05 | epoch=1.7854
[train] step=836 | loss=0.0997 | lr=1.35e-05 | epoch=1.7876
[train] step=837 | loss=0.0988 | lr=1.35e-05 | epoch=1.7897
[train] step=838 | loss=0.1298 | lr=1.35e-05 | epoch=1.7919
[train] step=839 | loss=0.1126 | lr=1.34e-05 | epoch=1.7940
[train] step=840 | loss=0.0973 | lr=1.34e-05 | epoch=1.7961
[train] step=841 | loss=0.0961 | lr=1.34e-05 | epoch=1.7983
[train] step=842 | loss=0.1127 | lr=1.34e-05 | epoch=1.8004
[train] step=843 | loss=0.0809 | lr=1.33e-05 | epoch=1.8026
[train] step=844 | loss=0.0990 | lr=1.33e-05 | epoch=1.8047
[train] step=845 | loss=0.1057 | lr=1.33e-05 | epoch=1.8068
[train] step=846 | loss=0.1100 | lr=1.33e-05 | epoch=1.8090
[train] step=847 | loss=0.0961 | lr=1.32e-05 | epoch=1.8111
[train] step=848 | loss=0.0811 | lr=1.32e-05 | epoch=1.8133
[train] step=849 | loss=0.0953 | lr=1.32e-05 | epoch=1.8154
[train] step=850 | loss=0.1155 | lr=1.32e-05 | epoch=1.8175
[train] step=851 | loss=0.1135 | lr=1.31e-05 | epoch=1.8197
[train] step=852 | loss=0.0914 | lr=1.31e-05 | epoch=1.8218
[train] step=853 | loss=0.1244 | lr=1.31e-05 | epoch=1.8240
[train] step=854 | loss=0.1044 | lr=1.31e-05 | epoch=1.8261
[train] step=855 | loss=0.1024 | lr=1.31e-05 | epoch=1.8283
[train] step=856 | loss=0.1177 | lr=1.30e-05 | epoch=1.8304
[train] step=857 | loss=0.0978 | lr=1.30e-05 | epoch=1.8325
[train] step=858 | loss=0.0914 | lr=1.30e-05 | epoch=1.8347
[train] step=859 | loss=0.1065 | lr=1.30e-05 | epoch=1.8368
[train] step=860 | loss=0.1203 | lr=1.29e-05 | epoch=1.8390
[train] step=861 | loss=0.1027 | lr=1.29e-05 | epoch=1.8411
[train] step=862 | loss=0.0935 | lr=1.29e-05 | epoch=1.8432
[train] step=863 | loss=0.0910 | lr=1.29e-05 | epoch=1.8454
[train] step=864 | loss=0.1124 | lr=1.28e-05 | epoch=1.8475
[train] step=865 | loss=0.1043 | lr=1.28e-05 | epoch=1.8497
[train] step=866 | loss=0.1046 | lr=1.28e-05 | epoch=1.8518
[train] step=867 | loss=0.1050 | lr=1.28e-05 | epoch=1.8539
[train] step=868 | loss=0.0830 | lr=1.27e-05 | epoch=1.8561
[train] step=869 | loss=0.1018 | lr=1.27e-05 | epoch=1.8582
[train] step=870 | loss=0.1203 | lr=1.27e-05 | epoch=1.8604
[train] step=871 | loss=0.1255 | lr=1.27e-05 | epoch=1.8625
[train] step=872 | loss=0.1433 | lr=1.27e-05 | epoch=1.8646
[train] step=873 | loss=0.1042 | lr=1.26e-05 | epoch=1.8668
[train] step=874 | loss=0.1119 | lr=1.26e-05 | epoch=1.8689
[train] step=875 | loss=0.0980 | lr=1.26e-05 | epoch=1.8711
[train] step=876 | loss=0.1119 | lr=1.26e-05 | epoch=1.8732
[train] step=877 | loss=0.1323 | lr=1.25e-05 | epoch=1.8753
[train] step=878 | loss=0.1016 | lr=1.25e-05 | epoch=1.8775
[train] step=879 | loss=0.0965 | lr=1.25e-05 | epoch=1.8796
[train] step=880 | loss=0.1458 | lr=1.25e-05 | epoch=1.8818
[train] step=881 | loss=0.0959 | lr=1.24e-05 | epoch=1.8839
[train] step=882 | loss=0.1204 | lr=1.24e-05 | epoch=1.8860
[train] step=883 | loss=0.1044 | lr=1.24e-05 | epoch=1.8882
[train] step=884 | loss=0.1174 | lr=1.24e-05 | epoch=1.8903
[train] step=885 | loss=0.1267 | lr=1.23e-05 | epoch=1.8925
[train] step=886 | loss=0.1071 | lr=1.23e-05 | epoch=1.8946
[train] step=887 | loss=0.1271 | lr=1.23e-05 | epoch=1.8967
[train] step=888 | loss=0.1395 | lr=1.23e-05 | epoch=1.8989
[train] step=889 | loss=0.1301 | lr=1.22e-05 | epoch=1.9010
[train] step=890 | loss=0.1116 | lr=1.22e-05 | epoch=1.9032
[train] step=891 | loss=0.1044 | lr=1.22e-05 | epoch=1.9053
[train] step=892 | loss=0.0960 | lr=1.22e-05 | epoch=1.9074
[train] step=893 | loss=0.1133 | lr=1.22e-05 | epoch=1.9096
[train] step=894 | loss=0.1267 | lr=1.21e-05 | epoch=1.9117
[train] step=895 | loss=0.1213 | lr=1.21e-05 | epoch=1.9139
[train] step=896 | loss=0.0895 | lr=1.21e-05 | epoch=1.9160
[train] step=897 | loss=0.1152 | lr=1.21e-05 | epoch=1.9181
[train] step=898 | loss=0.1130 | lr=1.20e-05 | epoch=1.9203
[train] step=899 | loss=0.1071 | lr=1.20e-05 | epoch=1.9224
[train] step=900 | loss=0.1143 | lr=1.20e-05 | epoch=1.9246
[train] step=901 | loss=0.1026 | lr=1.20e-05 | epoch=1.9267
[train] step=902 | loss=0.1136 | lr=1.19e-05 | epoch=1.9288
[train] step=903 | loss=0.0967 | lr=1.19e-05 | epoch=1.9310
[train] step=904 | loss=0.1059 | lr=1.19e-05 | epoch=1.9331
[train] step=905 | loss=0.1172 | lr=1.19e-05 | epoch=1.9353
[train] step=906 | loss=0.1294 | lr=1.18e-05 | epoch=1.9374
[train] step=907 | loss=0.1069 | lr=1.18e-05 | epoch=1.9395
[train] step=908 | loss=0.0950 | lr=1.18e-05 | epoch=1.9417
[train] step=909 | loss=0.1278 | lr=1.18e-05 | epoch=1.9438
[train] step=910 | loss=0.1122 | lr=1.17e-05 | epoch=1.9460
[train] step=911 | loss=0.1106 | lr=1.17e-05 | epoch=1.9481
[train] step=912 | loss=0.1074 | lr=1.17e-05 | epoch=1.9502
[train] step=913 | loss=0.1112 | lr=1.17e-05 | epoch=1.9524
[train] step=914 | loss=0.0825 | lr=1.17e-05 | epoch=1.9545
[train] step=915 | loss=0.1000 | lr=1.16e-05 | epoch=1.9567
[train] step=916 | loss=0.1017 | lr=1.16e-05 | epoch=1.9588
[train] step=917 | loss=0.0905 | lr=1.16e-05 | epoch=1.9609
[train] step=918 | loss=0.1140 | lr=1.16e-05 | epoch=1.9631
[train] step=919 | loss=0.1111 | lr=1.15e-05 | epoch=1.9652
[train] step=920 | loss=0.0955 | lr=1.15e-05 | epoch=1.9674
[train] step=921 | loss=0.1024 | lr=1.15e-05 | epoch=1.9695
[train] step=922 | loss=0.1095 | lr=1.15e-05 | epoch=1.9716
[train] step=923 | loss=0.0939 | lr=1.14e-05 | epoch=1.9738
[train] step=924 | loss=0.0958 | lr=1.14e-05 | epoch=1.9759
[train] step=925 | loss=0.1095 | lr=1.14e-05 | epoch=1.9781
[train] step=926 | loss=0.1032 | lr=1.14e-05 | epoch=1.9802
[train] step=927 | loss=0.1150 | lr=1.13e-05 | epoch=1.9823
[train] step=928 | loss=0.1143 | lr=1.13e-05 | epoch=1.9845
[train] step=929 | loss=0.1242 | lr=1.13e-05 | epoch=1.9866
[train] step=930 | loss=0.1138 | lr=1.13e-05 | epoch=1.9888
[train] step=931 | loss=0.0923 | lr=1.13e-05 | epoch=1.9909
[train] step=932 | loss=0.1137 | lr=1.12e-05 | epoch=1.9930

Saving model checkpoint to output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-932
2026-04-06 02:29:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:29:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 02:29:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:29:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-932\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-932\tokenizer_config.json

[train] step=933 | loss=0.1395 | lr=1.12e-05 | epoch=1.9952
[train] step=934 | loss=0.1126 | lr=1.12e-05 | epoch=1.9973
[train] step=935 | loss=0.1131 | lr=1.12e-05 | epoch=1.9995
[train] step=936 | loss=0.0391 | lr=1.11e-05 | epoch=2.0000
[train] step=937 | loss=0.0983 | lr=1.11e-05 | epoch=2.0021
[train] step=938 | loss=0.1007 | lr=1.11e-05 | epoch=2.0043
[train] step=939 | loss=0.0780 | lr=1.11e-05 | epoch=2.0064
[train] step=940 | loss=0.1027 | lr=1.10e-05 | epoch=2.0086
[train] step=941 | loss=0.1123 | lr=1.10e-05 | epoch=2.0107
[train] step=942 | loss=0.1127 | lr=1.10e-05 | epoch=2.0128
[train] step=943 | loss=0.1085 | lr=1.10e-05 | epoch=2.0150
[train] step=944 | loss=0.1135 | lr=1.09e-05 | epoch=2.0171
[train] step=945 | loss=0.1133 | lr=1.09e-05 | epoch=2.0193
[train] step=946 | loss=0.1142 | lr=1.09e-05 | epoch=2.0214
[train] step=947 | loss=0.1067 | lr=1.09e-05 | epoch=2.0235
[train] step=948 | loss=0.1051 | lr=1.08e-05 | epoch=2.0257
[train] step=949 | loss=0.1300 | lr=1.08e-05 | epoch=2.0278
[train] step=950 | loss=0.0891 | lr=1.08e-05 | epoch=2.0300
[train] step=951 | loss=0.1056 | lr=1.08e-05 | epoch=2.0321
[train] step=952 | loss=0.1157 | lr=1.08e-05 | epoch=2.0342
[train] step=953 | loss=0.1109 | lr=1.07e-05 | epoch=2.0364
[train] step=954 | loss=0.0995 | lr=1.07e-05 | epoch=2.0385
[train] step=955 | loss=0.1552 | lr=1.07e-05 | epoch=2.0407
[train] step=956 | loss=0.1000 | lr=1.07e-05 | epoch=2.0428
[train] step=957 | loss=0.0875 | lr=1.06e-05 | epoch=2.0449
[train] step=958 | loss=0.1250 | lr=1.06e-05 | epoch=2.0471
[train] step=959 | loss=0.0979 | lr=1.06e-05 | epoch=2.0492
[train] step=960 | loss=0.1034 | lr=1.06e-05 | epoch=2.0514
[train] step=961 | loss=0.1037 | lr=1.05e-05 | epoch=2.0535
[train] step=962 | loss=0.1037 | lr=1.05e-05 | epoch=2.0556
[train] step=963 | loss=0.1170 | lr=1.05e-05 | epoch=2.0578
[train] step=964 | loss=0.0872 | lr=1.05e-05 | epoch=2.0599
[train] step=965 | loss=0.1001 | lr=1.04e-05 | epoch=2.0621
[train] step=966 | loss=0.1185 | lr=1.04e-05 | epoch=2.0642
[train] step=967 | loss=0.0989 | lr=1.04e-05 | epoch=2.0663
[train] step=968 | loss=0.1193 | lr=1.04e-05 | epoch=2.0685
[train] step=969 | loss=0.1081 | lr=1.03e-05 | epoch=2.0706
[train] step=970 | loss=0.1113 | lr=1.03e-05 | epoch=2.0728
[train] step=971 | loss=0.1067 | lr=1.03e-05 | epoch=2.0749
[train] step=972 | loss=0.1282 | lr=1.03e-05 | epoch=2.0770
[train] step=973 | loss=0.1126 | lr=1.03e-05 | epoch=2.0792
[train] step=974 | loss=0.1321 | lr=1.02e-05 | epoch=2.0813
[train] step=975 | loss=0.0996 | lr=1.02e-05 | epoch=2.0835
[train] step=976 | loss=0.0965 | lr=1.02e-05 | epoch=2.0856
[train] step=977 | loss=0.0946 | lr=1.02e-05 | epoch=2.0877
[train] step=978 | loss=0.0951 | lr=1.01e-05 | epoch=2.0899
[train] step=979 | loss=0.0914 | lr=1.01e-05 | epoch=2.0920
[train] step=980 | loss=0.0973 | lr=1.01e-05 | epoch=2.0942
[train] step=981 | loss=0.1121 | lr=1.01e-05 | epoch=2.0963
[train] step=982 | loss=0.1187 | lr=1.00e-05 | epoch=2.0984
[train] step=983 | loss=0.1059 | lr=1.00e-05 | epoch=2.1006
[train] step=984 | loss=0.0947 | lr=9.99e-06 | epoch=2.1027
[train] step=985 | loss=0.1170 | lr=9.97e-06 | epoch=2.1049
[train] step=986 | loss=0.1127 | lr=9.94e-06 | epoch=2.1070
[train] step=987 | loss=0.1265 | lr=9.92e-06 | epoch=2.1091
[train] step=988 | loss=0.0927 | lr=9.90e-06 | epoch=2.1113
[train] step=989 | loss=0.1274 | lr=9.87e-06 | epoch=2.1134
[train] step=990 | loss=0.1027 | lr=9.85e-06 | epoch=2.1156
[train] step=991 | loss=0.1021 | lr=9.83e-06 | epoch=2.1177
[train] step=992 | loss=0.1174 | lr=9.80e-06 | epoch=2.1199
[train] step=993 | loss=0.0760 | lr=9.78e-06 | epoch=2.1220
[train] step=994 | loss=0.1003 | lr=9.75e-06 | epoch=2.1241
[train] step=995 | loss=0.1218 | lr=9.73e-06 | epoch=2.1263
[train] step=996 | loss=0.0984 | lr=9.71e-06 | epoch=2.1284
[train] step=997 | loss=0.0968 | lr=9.68e-06 | epoch=2.1306
[train] step=998 | loss=0.1041 | lr=9.66e-06 | epoch=2.1327
[train] step=999 | loss=0.1193 | lr=9.64e-06 | epoch=2.1348
[train] step=1000 | loss=0.1048 | lr=9.61e-06 | epoch=2.1370
[train] step=1001 | loss=0.0934 | lr=9.59e-06 | epoch=2.1391
[train] step=1002 | loss=0.1002 | lr=9.56e-06 | epoch=2.1413
[train] step=1003 | loss=0.0978 | lr=9.54e-06 | epoch=2.1434
[train] step=1004 | loss=0.1034 | lr=9.52e-06 | epoch=2.1455
[train] step=1005 | loss=0.1082 | lr=9.49e-06 | epoch=2.1477
[train] step=1006 | loss=0.1031 | lr=9.47e-06 | epoch=2.1498
[train] step=1007 | loss=0.1065 | lr=9.45e-06 | epoch=2.1520
[train] step=1008 | loss=0.0933 | lr=9.42e-06 | epoch=2.1541
[train] step=1009 | loss=0.1038 | lr=9.40e-06 | epoch=2.1562
[train] step=1010 | loss=0.0835 | lr=9.38e-06 | epoch=2.1584
[train] step=1011 | loss=0.1406 | lr=9.35e-06 | epoch=2.1605
[train] step=1012 | loss=0.1189 | lr=9.33e-06 | epoch=2.1627
[train] step=1013 | loss=0.1107 | lr=9.30e-06 | epoch=2.1648
[train] step=1014 | loss=0.0965 | lr=9.28e-06 | epoch=2.1669
[train] step=1015 | loss=0.0997 | lr=9.26e-06 | epoch=2.1691
[train] step=1016 | loss=0.1063 | lr=9.23e-06 | epoch=2.1712
[train] step=1017 | loss=0.1217 | lr=9.21e-06 | epoch=2.1734
[train] step=1018 | loss=0.1030 | lr=9.19e-06 | epoch=2.1755
[train] step=1019 | loss=0.1253 | lr=9.16e-06 | epoch=2.1776
[train] step=1020 | loss=0.0945 | lr=9.14e-06 | epoch=2.1798
[train] step=1021 | loss=0.0941 | lr=9.11e-06 | epoch=2.1819
[train] step=1022 | loss=0.1244 | lr=9.09e-06 | epoch=2.1841
[train] step=1023 | loss=0.0999 | lr=9.07e-06 | epoch=2.1862
[train] step=1024 | loss=0.1036 | lr=9.04e-06 | epoch=2.1883
[train] step=1025 | loss=0.1010 | lr=9.02e-06 | epoch=2.1905
[train] step=1026 | loss=0.1194 | lr=9.00e-06 | epoch=2.1926
[train] step=1027 | loss=0.1175 | lr=8.97e-06 | epoch=2.1948
[train] step=1028 | loss=0.1057 | lr=8.95e-06 | epoch=2.1969
[train] step=1029 | loss=0.1396 | lr=8.92e-06 | epoch=2.1990
[train] step=1030 | loss=0.1053 | lr=8.90e-06 | epoch=2.2012
[train] step=1031 | loss=0.1197 | lr=8.88e-06 | epoch=2.2033
[train] step=1032 | loss=0.1081 | lr=8.85e-06 | epoch=2.2055
[train] step=1033 | loss=0.1186 | lr=8.83e-06 | epoch=2.2076
[train] step=1034 | loss=0.1047 | lr=8.81e-06 | epoch=2.2097
[train] step=1035 | loss=0.1170 | lr=8.78e-06 | epoch=2.2119
[train] step=1036 | loss=0.0979 | lr=8.76e-06 | epoch=2.2140
[train] step=1037 | loss=0.1319 | lr=8.73e-06 | epoch=2.2162
[train] step=1038 | loss=0.1226 | lr=8.71e-06 | epoch=2.2183
[train] step=1039 | loss=0.1040 | lr=8.69e-06 | epoch=2.2204
[train] step=1040 | loss=0.0866 | lr=8.66e-06 | epoch=2.2226
[train] step=1041 | loss=0.0930 | lr=8.64e-06 | epoch=2.2247
[train] step=1042 | loss=0.0998 | lr=8.62e-06 | epoch=2.2269
[train] step=1043 | loss=0.0920 | lr=8.59e-06 | epoch=2.2290
[train] step=1044 | loss=0.1277 | lr=8.57e-06 | epoch=2.2311
[train] step=1045 | loss=0.0923 | lr=8.54e-06 | epoch=2.2333
[train] step=1046 | loss=0.1347 | lr=8.52e-06 | epoch=2.2354
[train] step=1047 | loss=0.1253 | lr=8.50e-06 | epoch=2.2376
[train] step=1048 | loss=0.1044 | lr=8.47e-06 | epoch=2.2397
[train] step=1049 | loss=0.1127 | lr=8.45e-06 | epoch=2.2418
[train] step=1050 | loss=0.0939 | lr=8.43e-06 | epoch=2.2440
[train] step=1051 | loss=0.0947 | lr=8.40e-06 | epoch=2.2461
[train] step=1052 | loss=0.1148 | lr=8.38e-06 | epoch=2.2483
[train] step=1053 | loss=0.1089 | lr=8.35e-06 | epoch=2.2504
[train] step=1054 | loss=0.1039 | lr=8.33e-06 | epoch=2.2525
[train] step=1055 | loss=0.1169 | lr=8.31e-06 | epoch=2.2547
[train] step=1056 | loss=0.1184 | lr=8.28e-06 | epoch=2.2568
[train] step=1057 | loss=0.0974 | lr=8.26e-06 | epoch=2.2590
[train] step=1058 | loss=0.0926 | lr=8.24e-06 | epoch=2.2611
[train] step=1059 | loss=0.1160 | lr=8.21e-06 | epoch=2.2632
[train] step=1060 | loss=0.1082 | lr=8.19e-06 | epoch=2.2654
[train] step=1061 | loss=0.1064 | lr=8.16e-06 | epoch=2.2675
[train] step=1062 | loss=0.1072 | lr=8.14e-06 | epoch=2.2697
[train] step=1063 | loss=0.0814 | lr=8.12e-06 | epoch=2.2718
[train] step=1064 | loss=0.0992 | lr=8.09e-06 | epoch=2.2739
[train] step=1065 | loss=0.0985 | lr=8.07e-06 | epoch=2.2761
[train] step=1066 | loss=0.1061 | lr=8.05e-06 | epoch=2.2782
[train] step=1067 | loss=0.0948 | lr=8.02e-06 | epoch=2.2804
[train] step=1068 | loss=0.1228 | lr=8.00e-06 | epoch=2.2825
[train] step=1069 | loss=0.0892 | lr=7.97e-06 | epoch=2.2846
[train] step=1070 | loss=0.1138 | lr=7.95e-06 | epoch=2.2868
[train] step=1071 | loss=0.1070 | lr=7.93e-06 | epoch=2.2889
[train] step=1072 | loss=0.0889 | lr=7.90e-06 | epoch=2.2911
[train] step=1073 | loss=0.0939 | lr=7.88e-06 | epoch=2.2932
[train] step=1074 | loss=0.0942 | lr=7.86e-06 | epoch=2.2953
[train] step=1075 | loss=0.1098 | lr=7.83e-06 | epoch=2.2975
[train] step=1076 | loss=0.1092 | lr=7.81e-06 | epoch=2.2996
[train] step=1077 | loss=0.1001 | lr=7.78e-06 | epoch=2.3018
[train] step=1078 | loss=0.1029 | lr=7.76e-06 | epoch=2.3039
[train] step=1079 | loss=0.1256 | lr=7.74e-06 | epoch=2.3060
[train] step=1080 | loss=0.1132 | lr=7.71e-06 | epoch=2.3082
[train] step=1081 | loss=0.1334 | lr=7.69e-06 | epoch=2.3103
[train] step=1082 | loss=0.1145 | lr=7.67e-06 | epoch=2.3125
[train] step=1083 | loss=0.1104 | lr=7.64e-06 | epoch=2.3146
[train] step=1084 | loss=0.0854 | lr=7.62e-06 | epoch=2.3167
[train] step=1085 | loss=0.1007 | lr=7.59e-06 | epoch=2.3189
[train] step=1086 | loss=0.0928 | lr=7.57e-06 | epoch=2.3210
[train] step=1087 | loss=0.1190 | lr=7.55e-06 | epoch=2.3232
[train] step=1088 | loss=0.1215 | lr=7.52e-06 | epoch=2.3253
[train] step=1089 | loss=0.0949 | lr=7.50e-06 | epoch=2.3274
[train] step=1090 | loss=0.1206 | lr=7.48e-06 | epoch=2.3296
[train] step=1091 | loss=0.1169 | lr=7.45e-06 | epoch=2.3317
[train] step=1092 | loss=0.1052 | lr=7.43e-06 | epoch=2.3339
[train] step=1093 | loss=0.0988 | lr=7.41e-06 | epoch=2.3360
[train] step=1094 | loss=0.0947 | lr=7.38e-06 | epoch=2.3381
[train] step=1095 | loss=0.1092 | lr=7.36e-06 | epoch=2.3403
[train] step=1096 | loss=0.1070 | lr=7.33e-06 | epoch=2.3424
[train] step=1097 | loss=0.1242 | lr=7.31e-06 | epoch=2.3446
[train] step=1098 | loss=0.0986 | lr=7.29e-06 | epoch=2.3467
[train] step=1099 | loss=0.1053 | lr=7.26e-06 | epoch=2.3488
[train] step=1100 | loss=0.1002 | lr=7.24e-06 | epoch=2.3510
[train] step=1101 | loss=0.1154 | lr=7.22e-06 | epoch=2.3531
[train] step=1102 | loss=0.1138 | lr=7.19e-06 | epoch=2.3553
[train] step=1103 | loss=0.0894 | lr=7.17e-06 | epoch=2.3574
[train] step=1104 | loss=0.1140 | lr=7.14e-06 | epoch=2.3596
[train] step=1105 | loss=0.1025 | lr=7.12e-06 | epoch=2.3617
[train] step=1106 | loss=0.1523 | lr=7.10e-06 | epoch=2.3638
[train] step=1107 | loss=0.1092 | lr=7.07e-06 | epoch=2.3660
[train] step=1108 | loss=0.1043 | lr=7.05e-06 | epoch=2.3681
[train] step=1109 | loss=0.1158 | lr=7.03e-06 | epoch=2.3703
[train] step=1110 | loss=0.1093 | lr=7.00e-06 | epoch=2.3724
[train] step=1111 | loss=0.1042 | lr=6.98e-06 | epoch=2.3745
[train] step=1112 | loss=0.0958 | lr=6.95e-06 | epoch=2.3767
[train] step=1113 | loss=0.1215 | lr=6.93e-06 | epoch=2.3788
[train] step=1114 | loss=0.1263 | lr=6.91e-06 | epoch=2.3810
[train] step=1115 | loss=0.0951 | lr=6.88e-06 | epoch=2.3831
[train] step=1116 | loss=0.1295 | lr=6.86e-06 | epoch=2.3852
[train] step=1117 | loss=0.1056 | lr=6.84e-06 | epoch=2.3874
[train] step=1118 | loss=0.0990 | lr=6.81e-06 | epoch=2.3895
[train] step=1119 | loss=0.1103 | lr=6.79e-06 | epoch=2.3917
[train] step=1120 | loss=0.1035 | lr=6.76e-06 | epoch=2.3938
[train] step=1121 | loss=0.1057 | lr=6.74e-06 | epoch=2.3959
[train] step=1122 | loss=0.1195 | lr=6.72e-06 | epoch=2.3981
[train] step=1123 | loss=0.1288 | lr=6.69e-06 | epoch=2.4002
[train] step=1124 | loss=0.1070 | lr=6.67e-06 | epoch=2.4024
[train] step=1125 | loss=0.1006 | lr=6.65e-06 | epoch=2.4045
[train] step=1126 | loss=0.0919 | lr=6.62e-06 | epoch=2.4066
[train] step=1127 | loss=0.1053 | lr=6.60e-06 | epoch=2.4088
[train] step=1128 | loss=0.1026 | lr=6.57e-06 | epoch=2.4109
[train] step=1129 | loss=0.1035 | lr=6.55e-06 | epoch=2.4131
[train] step=1130 | loss=0.0960 | lr=6.53e-06 | epoch=2.4152
[train] step=1131 | loss=0.1173 | lr=6.50e-06 | epoch=2.4173
[train] step=1132 | loss=0.0897 | lr=6.48e-06 | epoch=2.4195
[train] step=1133 | loss=0.0946 | lr=6.46e-06 | epoch=2.4216
[train] step=1134 | loss=0.1116 | lr=6.43e-06 | epoch=2.4238
[train] step=1135 | loss=0.1214 | lr=6.41e-06 | epoch=2.4259
[train] step=1136 | loss=0.1156 | lr=6.38e-06 | epoch=2.4280
[train] step=1137 | loss=0.0889 | lr=6.36e-06 | epoch=2.4302
[train] step=1138 | loss=0.0986 | lr=6.34e-06 | epoch=2.4323
[train] step=1139 | loss=0.1058 | lr=6.31e-06 | epoch=2.4345
[train] step=1140 | loss=0.1105 | lr=6.29e-06 | epoch=2.4366
[train] step=1141 | loss=0.1288 | lr=6.27e-06 | epoch=2.4387
[train] step=1142 | loss=0.0997 | lr=6.24e-06 | epoch=2.4409
[train] step=1143 | loss=0.1058 | lr=6.22e-06 | epoch=2.4430
[train] step=1144 | loss=0.0989 | lr=6.19e-06 | epoch=2.4452
[train] step=1145 | loss=0.0900 | lr=6.17e-06 | epoch=2.4473
[train] step=1146 | loss=0.1061 | lr=6.15e-06 | epoch=2.4494
[train] step=1147 | loss=0.1022 | lr=6.12e-06 | epoch=2.4516
[train] step=1148 | loss=0.1465 | lr=6.10e-06 | epoch=2.4537
[train] step=1149 | loss=0.1171 | lr=6.08e-06 | epoch=2.4559
[train] step=1150 | loss=0.1029 | lr=6.05e-06 | epoch=2.4580
[train] step=1151 | loss=0.1073 | lr=6.03e-06 | epoch=2.4601
[train] step=1152 | loss=0.1048 | lr=6.00e-06 | epoch=2.4623
[train] step=1153 | loss=0.1354 | lr=5.98e-06 | epoch=2.4644
[train] step=1154 | loss=0.1100 | lr=5.96e-06 | epoch=2.4666
[train] step=1155 | loss=0.0964 | lr=5.93e-06 | epoch=2.4687
[train] step=1156 | loss=0.1017 | lr=5.91e-06 | epoch=2.4708
[train] step=1157 | loss=0.1074 | lr=5.89e-06 | epoch=2.4730
[train] step=1158 | loss=0.0977 | lr=5.86e-06 | epoch=2.4751
[train] step=1159 | loss=0.1132 | lr=5.84e-06 | epoch=2.4773
[train] step=1160 | loss=0.0974 | lr=5.81e-06 | epoch=2.4794
[train] step=1161 | loss=0.1010 | lr=5.79e-06 | epoch=2.4815
[train] step=1162 | loss=0.1027 | lr=5.77e-06 | epoch=2.4837
[train] step=1163 | loss=0.1051 | lr=5.74e-06 | epoch=2.4858
[train] step=1164 | loss=0.0912 | lr=5.72e-06 | epoch=2.4880
[train] step=1165 | loss=0.0888 | lr=5.70e-06 | epoch=2.4901

Saving model checkpoint to output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1165
2026-04-06 02:40:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:40:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 02:40:19 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:40:19 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1165\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1165\tokenizer_config.json

[train] step=1166 | loss=0.1023 | lr=5.67e-06 | epoch=2.4922
[train] step=1167 | loss=0.0979 | lr=5.65e-06 | epoch=2.4944
[train] step=1168 | loss=0.1027 | lr=5.63e-06 | epoch=2.4965
[train] step=1169 | loss=0.1349 | lr=5.60e-06 | epoch=2.4987
[train] step=1170 | loss=0.0923 | lr=5.58e-06 | epoch=2.5008
[train] step=1171 | loss=0.0953 | lr=5.55e-06 | epoch=2.5029
[train] step=1172 | loss=0.1128 | lr=5.53e-06 | epoch=2.5051
[train] step=1173 | loss=0.0797 | lr=5.51e-06 | epoch=2.5072
[train] step=1174 | loss=0.0905 | lr=5.48e-06 | epoch=2.5094
[train] step=1175 | loss=0.0966 | lr=5.46e-06 | epoch=2.5115
[train] step=1176 | loss=0.1062 | lr=5.44e-06 | epoch=2.5136
[train] step=1177 | loss=0.1289 | lr=5.41e-06 | epoch=2.5158
[train] step=1178 | loss=0.1046 | lr=5.39e-06 | epoch=2.5179
[train] step=1179 | loss=0.1045 | lr=5.36e-06 | epoch=2.5201
[train] step=1180 | loss=0.0996 | lr=5.34e-06 | epoch=2.5222
[train] step=1181 | loss=0.1290 | lr=5.32e-06 | epoch=2.5243
[train] step=1182 | loss=0.0971 | lr=5.29e-06 | epoch=2.5265
[train] step=1183 | loss=0.1222 | lr=5.27e-06 | epoch=2.5286
[train] step=1184 | loss=0.1086 | lr=5.25e-06 | epoch=2.5308
[train] step=1185 | loss=0.1091 | lr=5.22e-06 | epoch=2.5329
[train] step=1186 | loss=0.1011 | lr=5.20e-06 | epoch=2.5350
[train] step=1187 | loss=0.1036 | lr=5.17e-06 | epoch=2.5372
[train] step=1188 | loss=0.0975 | lr=5.15e-06 | epoch=2.5393
[train] step=1189 | loss=0.1084 | lr=5.13e-06 | epoch=2.5415
[train] step=1190 | loss=0.1097 | lr=5.10e-06 | epoch=2.5436
[train] step=1191 | loss=0.1362 | lr=5.08e-06 | epoch=2.5457
[train] step=1192 | loss=0.0872 | lr=5.06e-06 | epoch=2.5479
[train] step=1193 | loss=0.0890 | lr=5.03e-06 | epoch=2.5500
[train] step=1194 | loss=0.1040 | lr=5.01e-06 | epoch=2.5522
[train] step=1195 | loss=0.1268 | lr=4.98e-06 | epoch=2.5543
[train] step=1196 | loss=0.0989 | lr=4.96e-06 | epoch=2.5564
[train] step=1197 | loss=0.1144 | lr=4.94e-06 | epoch=2.5586
[train] step=1198 | loss=0.1147 | lr=4.91e-06 | epoch=2.5607
[train] step=1199 | loss=0.0981 | lr=4.89e-06 | epoch=2.5629
[train] step=1200 | loss=0.1121 | lr=4.87e-06 | epoch=2.5650
[train] step=1201 | loss=0.1045 | lr=4.84e-06 | epoch=2.5671
[train] step=1202 | loss=0.1162 | lr=4.82e-06 | epoch=2.5693
[train] step=1203 | loss=0.1118 | lr=4.79e-06 | epoch=2.5714
[train] step=1204 | loss=0.1227 | lr=4.77e-06 | epoch=2.5736
[train] step=1205 | loss=0.1022 | lr=4.75e-06 | epoch=2.5757
[train] step=1206 | loss=0.0959 | lr=4.72e-06 | epoch=2.5778
[train] step=1207 | loss=0.1099 | lr=4.70e-06 | epoch=2.5800
[train] step=1208 | loss=0.0917 | lr=4.68e-06 | epoch=2.5821
[train] step=1209 | loss=0.1086 | lr=4.65e-06 | epoch=2.5843
[train] step=1210 | loss=0.1103 | lr=4.63e-06 | epoch=2.5864
[train] step=1211 | loss=0.1287 | lr=4.60e-06 | epoch=2.5886
[train] step=1212 | loss=0.1085 | lr=4.58e-06 | epoch=2.5907
[train] step=1213 | loss=0.1013 | lr=4.56e-06 | epoch=2.5928
[train] step=1214 | loss=0.0889 | lr=4.53e-06 | epoch=2.5950
[train] step=1215 | loss=0.1113 | lr=4.51e-06 | epoch=2.5971
[train] step=1216 | loss=0.1298 | lr=4.49e-06 | epoch=2.5993
[train] step=1217 | loss=0.1105 | lr=4.46e-06 | epoch=2.6014
[train] step=1218 | loss=0.1027 | lr=4.44e-06 | epoch=2.6035
[train] step=1219 | loss=0.1067 | lr=4.41e-06 | epoch=2.6057
[train] step=1220 | loss=0.1032 | lr=4.39e-06 | epoch=2.6078
[train] step=1221 | loss=0.1109 | lr=4.37e-06 | epoch=2.6100
[train] step=1222 | loss=0.1292 | lr=4.34e-06 | epoch=2.6121
[train] step=1223 | loss=0.1167 | lr=4.32e-06 | epoch=2.6142
[train] step=1224 | loss=0.0921 | lr=4.30e-06 | epoch=2.6164
[train] step=1225 | loss=0.1026 | lr=4.27e-06 | epoch=2.6185
[train] step=1226 | loss=0.0991 | lr=4.25e-06 | epoch=2.6207
[train] step=1227 | loss=0.1011 | lr=4.22e-06 | epoch=2.6228
[train] step=1228 | loss=0.1128 | lr=4.20e-06 | epoch=2.6249
[train] step=1229 | loss=0.1004 | lr=4.18e-06 | epoch=2.6271
[train] step=1230 | loss=0.1112 | lr=4.15e-06 | epoch=2.6292
[train] step=1231 | loss=0.0770 | lr=4.13e-06 | epoch=2.6314
[train] step=1232 | loss=0.1106 | lr=4.11e-06 | epoch=2.6335
[train] step=1233 | loss=0.1243 | lr=4.08e-06 | epoch=2.6356
[train] step=1234 | loss=0.1154 | lr=4.06e-06 | epoch=2.6378
[train] step=1235 | loss=0.1179 | lr=4.03e-06 | epoch=2.6399
[train] step=1236 | loss=0.0871 | lr=4.01e-06 | epoch=2.6421
[train] step=1237 | loss=0.0999 | lr=3.99e-06 | epoch=2.6442
[train] step=1238 | loss=0.0993 | lr=3.96e-06 | epoch=2.6463
[train] step=1239 | loss=0.1213 | lr=3.94e-06 | epoch=2.6485
[train] step=1240 | loss=0.1113 | lr=3.92e-06 | epoch=2.6506
[train] step=1241 | loss=0.0953 | lr=3.89e-06 | epoch=2.6528
[train] step=1242 | loss=0.1289 | lr=3.87e-06 | epoch=2.6549
[train] step=1243 | loss=0.0989 | lr=3.84e-06 | epoch=2.6570
[train] step=1244 | loss=0.1235 | lr=3.82e-06 | epoch=2.6592
[train] step=1245 | loss=0.0940 | lr=3.80e-06 | epoch=2.6613
[train] step=1246 | loss=0.0967 | lr=3.77e-06 | epoch=2.6635
[train] step=1247 | loss=0.1173 | lr=3.75e-06 | epoch=2.6656
[train] step=1248 | loss=0.1041 | lr=3.73e-06 | epoch=2.6677
[train] step=1249 | loss=0.0906 | lr=3.70e-06 | epoch=2.6699
[train] step=1250 | loss=0.0817 | lr=3.68e-06 | epoch=2.6720
[train] step=1251 | loss=0.1318 | lr=3.66e-06 | epoch=2.6742
[train] step=1252 | loss=0.1020 | lr=3.63e-06 | epoch=2.6763
[train] step=1253 | loss=0.1110 | lr=3.61e-06 | epoch=2.6784
[train] step=1254 | loss=0.1050 | lr=3.58e-06 | epoch=2.6806
[train] step=1255 | loss=0.0983 | lr=3.56e-06 | epoch=2.6827
[train] step=1256 | loss=0.0956 | lr=3.54e-06 | epoch=2.6849
[train] step=1257 | loss=0.0817 | lr=3.51e-06 | epoch=2.6870
[train] step=1258 | loss=0.1109 | lr=3.49e-06 | epoch=2.6891
[train] step=1259 | loss=0.1260 | lr=3.47e-06 | epoch=2.6913
[train] step=1260 | loss=0.1020 | lr=3.44e-06 | epoch=2.6934
[train] step=1261 | loss=0.1041 | lr=3.42e-06 | epoch=2.6956
[train] step=1262 | loss=0.1391 | lr=3.39e-06 | epoch=2.6977
[train] step=1263 | loss=0.0933 | lr=3.37e-06 | epoch=2.6998
[train] step=1264 | loss=0.1027 | lr=3.35e-06 | epoch=2.7020
[train] step=1265 | loss=0.1129 | lr=3.32e-06 | epoch=2.7041
[train] step=1266 | loss=0.1332 | lr=3.30e-06 | epoch=2.7063
[train] step=1267 | loss=0.1071 | lr=3.28e-06 | epoch=2.7084
[train] step=1268 | loss=0.1336 | lr=3.25e-06 | epoch=2.7105
[train] step=1269 | loss=0.1331 | lr=3.23e-06 | epoch=2.7127
[train] step=1270 | loss=0.0993 | lr=3.20e-06 | epoch=2.7148
[train] step=1271 | loss=0.0915 | lr=3.18e-06 | epoch=2.7170
[train] step=1272 | loss=0.0946 | lr=3.16e-06 | epoch=2.7191
[train] step=1273 | loss=0.1085 | lr=3.13e-06 | epoch=2.7212
[train] step=1274 | loss=0.0996 | lr=3.11e-06 | epoch=2.7234
[train] step=1275 | loss=0.1092 | lr=3.09e-06 | epoch=2.7255
[train] step=1276 | loss=0.0787 | lr=3.06e-06 | epoch=2.7277
[train] step=1277 | loss=0.1067 | lr=3.04e-06 | epoch=2.7298
[train] step=1278 | loss=0.1059 | lr=3.01e-06 | epoch=2.7319
[train] step=1279 | loss=0.1302 | lr=2.99e-06 | epoch=2.7341
[train] step=1280 | loss=0.1088 | lr=2.97e-06 | epoch=2.7362
[train] step=1281 | loss=0.0996 | lr=2.94e-06 | epoch=2.7384
[train] step=1282 | loss=0.1073 | lr=2.92e-06 | epoch=2.7405
[train] step=1283 | loss=0.0984 | lr=2.90e-06 | epoch=2.7426
[train] step=1284 | loss=0.1318 | lr=2.87e-06 | epoch=2.7448
[train] step=1285 | loss=0.1070 | lr=2.85e-06 | epoch=2.7469
[train] step=1286 | loss=0.0885 | lr=2.82e-06 | epoch=2.7491
[train] step=1287 | loss=0.1061 | lr=2.80e-06 | epoch=2.7512
[train] step=1288 | loss=0.1125 | lr=2.78e-06 | epoch=2.7533
[train] step=1289 | loss=0.1002 | lr=2.75e-06 | epoch=2.7555
[train] step=1290 | loss=0.1315 | lr=2.73e-06 | epoch=2.7576
[train] step=1291 | loss=0.0905 | lr=2.71e-06 | epoch=2.7598
[train] step=1292 | loss=0.1076 | lr=2.68e-06 | epoch=2.7619
[train] step=1293 | loss=0.0927 | lr=2.66e-06 | epoch=2.7640
[train] step=1294 | loss=0.1213 | lr=2.63e-06 | epoch=2.7662
[train] step=1295 | loss=0.1085 | lr=2.61e-06 | epoch=2.7683
[train] step=1296 | loss=0.1309 | lr=2.59e-06 | epoch=2.7705
[train] step=1297 | loss=0.1004 | lr=2.56e-06 | epoch=2.7726
[train] step=1298 | loss=0.0903 | lr=2.54e-06 | epoch=2.7747
[train] step=1299 | loss=0.1157 | lr=2.52e-06 | epoch=2.7769
[train] step=1300 | loss=0.1000 | lr=2.49e-06 | epoch=2.7790
[train] step=1301 | loss=0.1099 | lr=2.47e-06 | epoch=2.7812
[train] step=1302 | loss=0.1083 | lr=2.44e-06 | epoch=2.7833
[train] step=1303 | loss=0.1152 | lr=2.42e-06 | epoch=2.7854
[train] step=1304 | loss=0.1071 | lr=2.40e-06 | epoch=2.7876
[train] step=1305 | loss=0.1244 | lr=2.37e-06 | epoch=2.7897
[train] step=1306 | loss=0.1176 | lr=2.35e-06 | epoch=2.7919
[train] step=1307 | loss=0.0883 | lr=2.33e-06 | epoch=2.7940
[train] step=1308 | loss=0.0950 | lr=2.30e-06 | epoch=2.7961
[train] step=1309 | loss=0.1137 | lr=2.28e-06 | epoch=2.7983
[train] step=1310 | loss=0.0953 | lr=2.25e-06 | epoch=2.8004
[train] step=1311 | loss=0.1242 | lr=2.23e-06 | epoch=2.8026
[train] step=1312 | loss=0.1017 | lr=2.21e-06 | epoch=2.8047
[train] step=1313 | loss=0.1088 | lr=2.18e-06 | epoch=2.8068
[train] step=1314 | loss=0.1003 | lr=2.16e-06 | epoch=2.8090
[train] step=1315 | loss=0.1127 | lr=2.14e-06 | epoch=2.8111
[train] step=1316 | loss=0.0996 | lr=2.11e-06 | epoch=2.8133
[train] step=1317 | loss=0.1152 | lr=2.09e-06 | epoch=2.8154
[train] step=1318 | loss=0.1085 | lr=2.06e-06 | epoch=2.8175
[train] step=1319 | loss=0.0813 | lr=2.04e-06 | epoch=2.8197
[train] step=1320 | loss=0.1001 | lr=2.02e-06 | epoch=2.8218
[train] step=1321 | loss=0.0966 | lr=1.99e-06 | epoch=2.8240
[train] step=1322 | loss=0.0853 | lr=1.97e-06 | epoch=2.8261
[train] step=1323 | loss=0.0885 | lr=1.95e-06 | epoch=2.8283
[train] step=1324 | loss=0.1132 | lr=1.92e-06 | epoch=2.8304
[train] step=1325 | loss=0.0876 | lr=1.90e-06 | epoch=2.8325
[train] step=1326 | loss=0.1017 | lr=1.88e-06 | epoch=2.8347
[train] step=1327 | loss=0.1095 | lr=1.85e-06 | epoch=2.8368
[train] step=1328 | loss=0.1138 | lr=1.83e-06 | epoch=2.8390
[train] step=1329 | loss=0.1117 | lr=1.80e-06 | epoch=2.8411
[train] step=1330 | loss=0.1183 | lr=1.78e-06 | epoch=2.8432
[train] step=1331 | loss=0.0891 | lr=1.76e-06 | epoch=2.8454
[train] step=1332 | loss=0.1457 | lr=1.73e-06 | epoch=2.8475
[train] step=1333 | loss=0.1056 | lr=1.71e-06 | epoch=2.8497
[train] step=1334 | loss=0.1016 | lr=1.69e-06 | epoch=2.8518
[train] step=1335 | loss=0.1265 | lr=1.66e-06 | epoch=2.8539
[train] step=1336 | loss=0.0928 | lr=1.64e-06 | epoch=2.8561
[train] step=1337 | loss=0.1068 | lr=1.61e-06 | epoch=2.8582
[train] step=1338 | loss=0.1106 | lr=1.59e-06 | epoch=2.8604
[train] step=1339 | loss=0.1393 | lr=1.57e-06 | epoch=2.8625
[train] step=1340 | loss=0.1240 | lr=1.54e-06 | epoch=2.8646
[train] step=1341 | loss=0.0903 | lr=1.52e-06 | epoch=2.8668
[train] step=1342 | loss=0.1066 | lr=1.50e-06 | epoch=2.8689
[train] step=1343 | loss=0.1162 | lr=1.47e-06 | epoch=2.8711
[train] step=1344 | loss=0.0921 | lr=1.45e-06 | epoch=2.8732
[train] step=1345 | loss=0.1068 | lr=1.42e-06 | epoch=2.8753
[train] step=1346 | loss=0.1234 | lr=1.40e-06 | epoch=2.8775
[train] step=1347 | loss=0.1245 | lr=1.38e-06 | epoch=2.8796
[train] step=1348 | loss=0.1287 | lr=1.35e-06 | epoch=2.8818
[train] step=1349 | loss=0.0918 | lr=1.33e-06 | epoch=2.8839
[train] step=1350 | loss=0.1189 | lr=1.31e-06 | epoch=2.8860
[train] step=1351 | loss=0.1205 | lr=1.28e-06 | epoch=2.8882
[train] step=1352 | loss=0.1064 | lr=1.26e-06 | epoch=2.8903
[train] step=1353 | loss=0.1072 | lr=1.23e-06 | epoch=2.8925
[train] step=1354 | loss=0.0949 | lr=1.21e-06 | epoch=2.8946
[train] step=1355 | loss=0.1178 | lr=1.19e-06 | epoch=2.8967
[train] step=1356 | loss=0.0928 | lr=1.16e-06 | epoch=2.8989
[train] step=1357 | loss=0.1202 | lr=1.14e-06 | epoch=2.9010
[train] step=1358 | loss=0.0945 | lr=1.12e-06 | epoch=2.9032
[train] step=1359 | loss=0.1043 | lr=1.09e-06 | epoch=2.9053
[train] step=1360 | loss=0.1008 | lr=1.07e-06 | epoch=2.9074
[train] step=1361 | loss=0.0938 | lr=1.04e-06 | epoch=2.9096
[train] step=1362 | loss=0.1089 | lr=1.02e-06 | epoch=2.9117
[train] step=1363 | loss=0.0943 | lr=9.97e-07 | epoch=2.9139
[train] step=1364 | loss=0.1046 | lr=9.73e-07 | epoch=2.9160
[train] step=1365 | loss=0.1257 | lr=9.49e-07 | epoch=2.9181
[train] step=1366 | loss=0.1169 | lr=9.26e-07 | epoch=2.9203
[train] step=1367 | loss=0.1244 | lr=9.02e-07 | epoch=2.9224
[train] step=1368 | loss=0.0700 | lr=8.78e-07 | epoch=2.9246
[train] step=1369 | loss=0.0920 | lr=8.54e-07 | epoch=2.9267
[train] step=1370 | loss=0.0967 | lr=8.31e-07 | epoch=2.9288
[train] step=1371 | loss=0.0774 | lr=8.07e-07 | epoch=2.9310
[train] step=1372 | loss=0.1106 | lr=7.83e-07 | epoch=2.9331
[train] step=1373 | loss=0.1122 | lr=7.59e-07 | epoch=2.9353
[train] step=1374 | loss=0.0934 | lr=7.36e-07 | epoch=2.9374
[train] step=1375 | loss=0.1330 | lr=7.12e-07 | epoch=2.9395
[train] step=1376 | loss=0.1081 | lr=6.88e-07 | epoch=2.9417
[train] step=1377 | loss=0.0925 | lr=6.65e-07 | epoch=2.9438
[train] step=1378 | loss=0.1205 | lr=6.41e-07 | epoch=2.9460
[train] step=1379 | loss=0.0922 | lr=6.17e-07 | epoch=2.9481
[train] step=1380 | loss=0.1181 | lr=5.93e-07 | epoch=2.9502
[train] step=1381 | loss=0.1039 | lr=5.70e-07 | epoch=2.9524
[train] step=1382 | loss=0.0893 | lr=5.46e-07 | epoch=2.9545
[train] step=1383 | loss=0.0908 | lr=5.22e-07 | epoch=2.9567
[train] step=1384 | loss=0.0934 | lr=4.98e-07 | epoch=2.9588
[train] step=1385 | loss=0.1107 | lr=4.75e-07 | epoch=2.9609
[train] step=1386 | loss=0.0999 | lr=4.51e-07 | epoch=2.9631
[train] step=1387 | loss=0.1166 | lr=4.27e-07 | epoch=2.9652
[train] step=1388 | loss=0.1142 | lr=4.03e-07 | epoch=2.9674
[train] step=1389 | loss=0.1131 | lr=3.80e-07 | epoch=2.9695
[train] step=1390 | loss=0.1126 | lr=3.56e-07 | epoch=2.9716
[train] step=1391 | loss=0.1053 | lr=3.32e-07 | epoch=2.9738
[train] step=1392 | loss=0.0977 | lr=3.09e-07 | epoch=2.9759
[train] step=1393 | loss=0.0938 | lr=2.85e-07 | epoch=2.9781
[train] step=1394 | loss=0.0953 | lr=2.61e-07 | epoch=2.9802
[train] step=1395 | loss=0.0902 | lr=2.37e-07 | epoch=2.9823
[train] step=1396 | loss=0.0853 | lr=2.14e-07 | epoch=2.9845
[train] step=1397 | loss=0.1085 | lr=1.90e-07 | epoch=2.9866
[train] step=1398 | loss=0.1075 | lr=1.66e-07 | epoch=2.9888

Saving model checkpoint to output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1398
2026-04-06 02:50:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:50:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 02:50:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:50:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1398\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1398\tokenizer_config.json

[train] step=1399 | loss=0.1099 | lr=1.42e-07 | epoch=2.9909
[train] step=1400 | loss=0.1231 | lr=1.19e-07 | epoch=2.9930
[train] step=1401 | loss=0.0909 | lr=9.49e-08 | epoch=2.9952
[train] step=1402 | loss=0.1030 | lr=7.12e-08 | epoch=2.9973
[train] step=1403 | loss=0.1383 | lr=4.75e-08 | epoch=2.9995
[train] step=1404 | loss=0.0863 | lr=2.37e-08 | epoch=3.0000

Saving model checkpoint to output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1404
2026-04-06 02:51:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 02:51:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1404\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\checkpoint-1404\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=1404 | epoch=3.0000
[train] finished | global_step=1404

Saving model checkpoint to output\fine_tune\run_001_lr3e-5_r16_a32_ep3
2026-04-06 02:51:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 02:51:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\tokenizer_config.json
chat template saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_001_lr3e-5_r16_a32_ep3\tokenizer_config.json
2026-04-06 02:51:08 | INFO     | root | Done run 2/5: C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_001_lr3e-5_r16_a32_ep3

=== Run 3/5  run_002_lr5e-5_r32_a64_ep3  merged={'learning_rate': 5e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-06 02:51:08 | INFO     | root | Logging to C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_002_lr5e-5_r32_a64_ep3\training_run.log
2026-04-06 02:51:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 02:51:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-06 02:51:08 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-06 02:51:09 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-06 02:51:09 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"
2026-04-06 02:51:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 02:51:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 10241.83it/s]
2026-04-06 02:51:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": false,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

2026-04-06 02:51:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2-1.5B.
2026-04-06 02:51:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-06 02:51:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-06 02:51:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 02:51:12 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 02:51:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-06 02:51:12 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-06 02:51:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-06 02:51:14 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 8,716,288

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.6833 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.7304 | lr=3.57e-07 | epoch=0.0043
[train] step=3 | loss=1.7381 | lr=7.14e-07 | epoch=0.0064
[train] step=4 | loss=1.7181 | lr=1.07e-06 | epoch=0.0086
[train] step=5 | loss=1.6858 | lr=1.43e-06 | epoch=0.0107
[train] step=6 | loss=1.7065 | lr=1.79e-06 | epoch=0.0128
[train] step=7 | loss=1.6350 | lr=2.14e-06 | epoch=0.0150
[train] step=8 | loss=1.6067 | lr=2.50e-06 | epoch=0.0171
[train] step=9 | loss=1.6958 | lr=2.86e-06 | epoch=0.0193
[train] step=10 | loss=1.6978 | lr=3.21e-06 | epoch=0.0214
[train] step=11 | loss=1.7413 | lr=3.57e-06 | epoch=0.0235
[train] step=12 | loss=1.8217 | lr=3.93e-06 | epoch=0.0257
[train] step=13 | loss=1.6874 | lr=4.29e-06 | epoch=0.0278
[train] step=14 | loss=1.7289 | lr=4.64e-06 | epoch=0.0300
[train] step=15 | loss=1.7731 | lr=5.00e-06 | epoch=0.0321
[train] step=16 | loss=1.7082 | lr=5.36e-06 | epoch=0.0342
[train] step=17 | loss=1.6802 | lr=5.71e-06 | epoch=0.0364
[train] step=18 | loss=1.6905 | lr=6.07e-06 | epoch=0.0385
[train] step=19 | loss=1.6634 | lr=6.43e-06 | epoch=0.0407
[train] step=20 | loss=1.6663 | lr=6.79e-06 | epoch=0.0428
[train] step=21 | loss=1.5962 | lr=7.14e-06 | epoch=0.0449
[train] step=22 | loss=1.6338 | lr=7.50e-06 | epoch=0.0471
[train] step=23 | loss=1.6064 | lr=7.86e-06 | epoch=0.0492
[train] step=24 | loss=1.6425 | lr=8.21e-06 | epoch=0.0514
[train] step=25 | loss=1.5716 | lr=8.57e-06 | epoch=0.0535
[train] step=26 | loss=1.6825 | lr=8.93e-06 | epoch=0.0556
[train] step=27 | loss=1.5302 | lr=9.29e-06 | epoch=0.0578
[train] step=28 | loss=1.5552 | lr=9.64e-06 | epoch=0.0599
[train] step=29 | loss=1.5342 | lr=1.00e-05 | epoch=0.0621
[train] step=30 | loss=1.5747 | lr=1.04e-05 | epoch=0.0642
[train] step=31 | loss=1.4719 | lr=1.07e-05 | epoch=0.0663
[train] step=32 | loss=1.4905 | lr=1.11e-05 | epoch=0.0685
[train] step=33 | loss=1.4946 | lr=1.14e-05 | epoch=0.0706
[train] step=34 | loss=1.4996 | lr=1.18e-05 | epoch=0.0728
[train] step=35 | loss=1.5969 | lr=1.21e-05 | epoch=0.0749
[train] step=36 | loss=1.4828 | lr=1.25e-05 | epoch=0.0770
[train] step=37 | loss=1.4993 | lr=1.29e-05 | epoch=0.0792
[train] step=38 | loss=1.4606 | lr=1.32e-05 | epoch=0.0813
[train] step=39 | loss=1.4170 | lr=1.36e-05 | epoch=0.0835
[train] step=40 | loss=1.5068 | lr=1.39e-05 | epoch=0.0856
[train] step=41 | loss=1.4134 | lr=1.43e-05 | epoch=0.0877
[train] step=42 | loss=1.4120 | lr=1.46e-05 | epoch=0.0899
[train] step=43 | loss=1.3791 | lr=1.50e-05 | epoch=0.0920
[train] step=44 | loss=1.3194 | lr=1.54e-05 | epoch=0.0942
[train] step=45 | loss=1.3576 | lr=1.57e-05 | epoch=0.0963
[train] step=46 | loss=1.3053 | lr=1.61e-05 | epoch=0.0984
[train] step=47 | loss=1.3007 | lr=1.64e-05 | epoch=0.1006
[train] step=48 | loss=1.1952 | lr=1.68e-05 | epoch=0.1027
[train] step=49 | loss=1.2442 | lr=1.71e-05 | epoch=0.1049
[train] step=50 | loss=1.3082 | lr=1.75e-05 | epoch=0.1070
[train] step=51 | loss=1.2515 | lr=1.79e-05 | epoch=0.1091
[train] step=52 | loss=1.2109 | lr=1.82e-05 | epoch=0.1113
[train] step=53 | loss=1.2641 | lr=1.86e-05 | epoch=0.1134
[train] step=54 | loss=1.1584 | lr=1.89e-05 | epoch=0.1156
[train] step=55 | loss=1.0503 | lr=1.93e-05 | epoch=0.1177
[train] step=56 | loss=1.1604 | lr=1.96e-05 | epoch=0.1199
[train] step=57 | loss=0.9876 | lr=2.00e-05 | epoch=0.1220
[train] step=58 | loss=1.0668 | lr=2.04e-05 | epoch=0.1241
[train] step=59 | loss=0.9855 | lr=2.07e-05 | epoch=0.1263
[train] step=60 | loss=0.9641 | lr=2.11e-05 | epoch=0.1284
[train] step=61 | loss=0.9295 | lr=2.14e-05 | epoch=0.1306
[train] step=62 | loss=0.9001 | lr=2.18e-05 | epoch=0.1327
[train] step=63 | loss=0.8429 | lr=2.21e-05 | epoch=0.1348
[train] step=64 | loss=0.8989 | lr=2.25e-05 | epoch=0.1370
[train] step=65 | loss=0.8024 | lr=2.29e-05 | epoch=0.1391
[train] step=66 | loss=0.7734 | lr=2.32e-05 | epoch=0.1413
[train] step=67 | loss=0.7133 | lr=2.36e-05 | epoch=0.1434
[train] step=68 | loss=0.7098 | lr=2.39e-05 | epoch=0.1455
[train] step=69 | loss=0.6852 | lr=2.43e-05 | epoch=0.1477
[train] step=70 | loss=0.6140 | lr=2.46e-05 | epoch=0.1498
[train] step=71 | loss=0.5475 | lr=2.50e-05 | epoch=0.1520
[train] step=72 | loss=0.5043 | lr=2.54e-05 | epoch=0.1541
[train] step=73 | loss=0.4751 | lr=2.57e-05 | epoch=0.1562
[train] step=74 | loss=0.4327 | lr=2.61e-05 | epoch=0.1584
[train] step=75 | loss=0.3868 | lr=2.64e-05 | epoch=0.1605
[train] step=76 | loss=0.3433 | lr=2.68e-05 | epoch=0.1627
[train] step=77 | loss=0.3007 | lr=2.71e-05 | epoch=0.1648
[train] step=78 | loss=0.2981 | lr=2.75e-05 | epoch=0.1669
[train] step=79 | loss=0.2790 | lr=2.79e-05 | epoch=0.1691
[train] step=80 | loss=0.2824 | lr=2.82e-05 | epoch=0.1712
[train] step=81 | loss=0.2692 | lr=2.86e-05 | epoch=0.1734
[train] step=82 | loss=0.2415 | lr=2.89e-05 | epoch=0.1755
[train] step=83 | loss=0.2229 | lr=2.93e-05 | epoch=0.1776
[train] step=84 | loss=0.2076 | lr=2.96e-05 | epoch=0.1798
[train] step=85 | loss=0.2280 | lr=3.00e-05 | epoch=0.1819
[train] step=86 | loss=0.2225 | lr=3.04e-05 | epoch=0.1841
[train] step=87 | loss=0.1798 | lr=3.07e-05 | epoch=0.1862
[train] step=88 | loss=0.2051 | lr=3.11e-05 | epoch=0.1883
[train] step=89 | loss=0.1771 | lr=3.14e-05 | epoch=0.1905
[train] step=90 | loss=0.1728 | lr=3.18e-05 | epoch=0.1926
[train] step=91 | loss=0.1629 | lr=3.21e-05 | epoch=0.1948
[train] step=92 | loss=0.1800 | lr=3.25e-05 | epoch=0.1969
[train] step=93 | loss=0.1673 | lr=3.29e-05 | epoch=0.1990
[train] step=94 | loss=0.1529 | lr=3.32e-05 | epoch=0.2012
[train] step=95 | loss=0.1540 | lr=3.36e-05 | epoch=0.2033
[train] step=96 | loss=0.1467 | lr=3.39e-05 | epoch=0.2055
[train] step=97 | loss=0.1569 | lr=3.43e-05 | epoch=0.2076
[train] step=98 | loss=0.1460 | lr=3.46e-05 | epoch=0.2097
[train] step=99 | loss=0.1240 | lr=3.50e-05 | epoch=0.2119
[train] step=100 | loss=0.1382 | lr=3.54e-05 | epoch=0.2140
[train] step=101 | loss=0.1214 | lr=3.57e-05 | epoch=0.2162
[train] step=102 | loss=0.1649 | lr=3.61e-05 | epoch=0.2183
[train] step=103 | loss=0.1246 | lr=3.64e-05 | epoch=0.2204
[train] step=104 | loss=0.1397 | lr=3.68e-05 | epoch=0.2226
[train] step=105 | loss=0.1446 | lr=3.71e-05 | epoch=0.2247
[train] step=106 | loss=0.1350 | lr=3.75e-05 | epoch=0.2269
[train] step=107 | loss=0.1435 | lr=3.79e-05 | epoch=0.2290
[train] step=108 | loss=0.1148 | lr=3.82e-05 | epoch=0.2311
[train] step=109 | loss=0.1103 | lr=3.86e-05 | epoch=0.2333
[train] step=110 | loss=0.1514 | lr=3.89e-05 | epoch=0.2354
[train] step=111 | loss=0.1196 | lr=3.93e-05 | epoch=0.2376
[train] step=112 | loss=0.1139 | lr=3.96e-05 | epoch=0.2397
[train] step=113 | loss=0.1145 | lr=4.00e-05 | epoch=0.2418
[train] step=114 | loss=0.1428 | lr=4.04e-05 | epoch=0.2440
[train] step=115 | loss=0.1259 | lr=4.07e-05 | epoch=0.2461
[train] step=116 | loss=0.1377 | lr=4.11e-05 | epoch=0.2483
[train] step=117 | loss=0.1263 | lr=4.14e-05 | epoch=0.2504
[train] step=118 | loss=0.1142 | lr=4.18e-05 | epoch=0.2525
[train] step=119 | loss=0.1140 | lr=4.21e-05 | epoch=0.2547
[train] step=120 | loss=0.1102 | lr=4.25e-05 | epoch=0.2568
[train] step=121 | loss=0.1186 | lr=4.29e-05 | epoch=0.2590
[train] step=122 | loss=0.1359 | lr=4.32e-05 | epoch=0.2611
[train] step=123 | loss=0.1431 | lr=4.36e-05 | epoch=0.2632
[train] step=124 | loss=0.1115 | lr=4.39e-05 | epoch=0.2654
[train] step=125 | loss=0.1314 | lr=4.43e-05 | epoch=0.2675
[train] step=126 | loss=0.1189 | lr=4.46e-05 | epoch=0.2697
[train] step=127 | loss=0.1267 | lr=4.50e-05 | epoch=0.2718
[train] step=128 | loss=0.1071 | lr=4.54e-05 | epoch=0.2739
[train] step=129 | loss=0.1238 | lr=4.57e-05 | epoch=0.2761
[train] step=130 | loss=0.1235 | lr=4.61e-05 | epoch=0.2782
[train] step=131 | loss=0.1446 | lr=4.64e-05 | epoch=0.2804
[train] step=132 | loss=0.1251 | lr=4.68e-05 | epoch=0.2825
[train] step=133 | loss=0.1259 | lr=4.71e-05 | epoch=0.2846
[train] step=134 | loss=0.1146 | lr=4.75e-05 | epoch=0.2868
[train] step=135 | loss=0.1294 | lr=4.79e-05 | epoch=0.2889
[train] step=136 | loss=0.1171 | lr=4.82e-05 | epoch=0.2911
[train] step=137 | loss=0.1401 | lr=4.86e-05 | epoch=0.2932
[train] step=138 | loss=0.1041 | lr=4.89e-05 | epoch=0.2953
[train] step=139 | loss=0.1064 | lr=4.93e-05 | epoch=0.2975
[train] step=140 | loss=0.1196 | lr=4.96e-05 | epoch=0.2996
[train] step=141 | loss=0.1731 | lr=5.00e-05 | epoch=0.3018
[train] step=142 | loss=0.1187 | lr=5.00e-05 | epoch=0.3039
[train] step=143 | loss=0.1266 | lr=4.99e-05 | epoch=0.3060
[train] step=144 | loss=0.1081 | lr=4.99e-05 | epoch=0.3082
[train] step=145 | loss=0.1255 | lr=4.98e-05 | epoch=0.3103
[train] step=146 | loss=0.1143 | lr=4.98e-05 | epoch=0.3125
[train] step=147 | loss=0.1234 | lr=4.98e-05 | epoch=0.3146
[train] step=148 | loss=0.1041 | lr=4.97e-05 | epoch=0.3167
[train] step=149 | loss=0.1181 | lr=4.97e-05 | epoch=0.3189
[train] step=150 | loss=0.0982 | lr=4.96e-05 | epoch=0.3210
[train] step=151 | loss=0.1374 | lr=4.96e-05 | epoch=0.3232
[train] step=152 | loss=0.1000 | lr=4.96e-05 | epoch=0.3253
[train] step=153 | loss=0.1049 | lr=4.95e-05 | epoch=0.3274
[train] step=154 | loss=0.1105 | lr=4.95e-05 | epoch=0.3296
[train] step=155 | loss=0.0896 | lr=4.94e-05 | epoch=0.3317
[train] step=156 | loss=0.1295 | lr=4.94e-05 | epoch=0.3339
[train] step=157 | loss=0.1490 | lr=4.94e-05 | epoch=0.3360
[train] step=158 | loss=0.1125 | lr=4.93e-05 | epoch=0.3381
[train] step=159 | loss=0.1067 | lr=4.93e-05 | epoch=0.3403
[train] step=160 | loss=0.1441 | lr=4.92e-05 | epoch=0.3424
[train] step=161 | loss=0.1029 | lr=4.92e-05 | epoch=0.3446
[train] step=162 | loss=0.1003 | lr=4.92e-05 | epoch=0.3467
[train] step=163 | loss=0.1225 | lr=4.91e-05 | epoch=0.3488
[train] step=164 | loss=0.1372 | lr=4.91e-05 | epoch=0.3510
[train] step=165 | loss=0.1192 | lr=4.91e-05 | epoch=0.3531
[train] step=166 | loss=0.1302 | lr=4.90e-05 | epoch=0.3553
[train] step=167 | loss=0.1006 | lr=4.90e-05 | epoch=0.3574
[train] step=168 | loss=0.1036 | lr=4.89e-05 | epoch=0.3596
[train] step=169 | loss=0.1156 | lr=4.89e-05 | epoch=0.3617
[train] step=170 | loss=0.1055 | lr=4.89e-05 | epoch=0.3638
[train] step=171 | loss=0.1201 | lr=4.88e-05 | epoch=0.3660
[train] step=172 | loss=0.1218 | lr=4.88e-05 | epoch=0.3681
[train] step=173 | loss=0.0979 | lr=4.87e-05 | epoch=0.3703
[train] step=174 | loss=0.1165 | lr=4.87e-05 | epoch=0.3724
[train] step=175 | loss=0.1108 | lr=4.87e-05 | epoch=0.3745
[train] step=176 | loss=0.1428 | lr=4.86e-05 | epoch=0.3767
[train] step=177 | loss=0.0890 | lr=4.86e-05 | epoch=0.3788
[train] step=178 | loss=0.1022 | lr=4.85e-05 | epoch=0.3810
[train] step=179 | loss=0.1093 | lr=4.85e-05 | epoch=0.3831
[train] step=180 | loss=0.1122 | lr=4.85e-05 | epoch=0.3852
[train] step=181 | loss=0.1114 | lr=4.84e-05 | epoch=0.3874
[train] step=182 | loss=0.0918 | lr=4.84e-05 | epoch=0.3895
[train] step=183 | loss=0.0845 | lr=4.83e-05 | epoch=0.3917
[train] step=184 | loss=0.1331 | lr=4.83e-05 | epoch=0.3938
[train] step=185 | loss=0.1009 | lr=4.83e-05 | epoch=0.3959
[train] step=186 | loss=0.0930 | lr=4.82e-05 | epoch=0.3981
[train] step=187 | loss=0.1056 | lr=4.82e-05 | epoch=0.4002
[train] step=188 | loss=0.1369 | lr=4.81e-05 | epoch=0.4024
[train] step=189 | loss=0.1248 | lr=4.81e-05 | epoch=0.4045
[train] step=190 | loss=0.1337 | lr=4.81e-05 | epoch=0.4066
[train] step=191 | loss=0.1032 | lr=4.80e-05 | epoch=0.4088
[train] step=192 | loss=0.1105 | lr=4.80e-05 | epoch=0.4109
[train] step=193 | loss=0.1251 | lr=4.79e-05 | epoch=0.4131
[train] step=194 | loss=0.1086 | lr=4.79e-05 | epoch=0.4152
[train] step=195 | loss=0.1215 | lr=4.79e-05 | epoch=0.4173
[train] step=196 | loss=0.1202 | lr=4.78e-05 | epoch=0.4195
[train] step=197 | loss=0.0954 | lr=4.78e-05 | epoch=0.4216
[train] step=198 | loss=0.1411 | lr=4.77e-05 | epoch=0.4238
[train] step=199 | loss=0.1275 | lr=4.77e-05 | epoch=0.4259
[train] step=200 | loss=0.1075 | lr=4.77e-05 | epoch=0.4280
[train] step=201 | loss=0.1102 | lr=4.76e-05 | epoch=0.4302
[train] step=202 | loss=0.1354 | lr=4.76e-05 | epoch=0.4323
[train] step=203 | loss=0.1119 | lr=4.75e-05 | epoch=0.4345
[train] step=204 | loss=0.1230 | lr=4.75e-05 | epoch=0.4366
[train] step=205 | loss=0.0974 | lr=4.75e-05 | epoch=0.4387
[train] step=206 | loss=0.1080 | lr=4.74e-05 | epoch=0.4409
[train] step=207 | loss=0.1162 | lr=4.74e-05 | epoch=0.4430
[train] step=208 | loss=0.1002 | lr=4.73e-05 | epoch=0.4452
[train] step=209 | loss=0.1208 | lr=4.73e-05 | epoch=0.4473
[train] step=210 | loss=0.1077 | lr=4.73e-05 | epoch=0.4494
[train] step=211 | loss=0.1072 | lr=4.72e-05 | epoch=0.4516
[train] step=212 | loss=0.1141 | lr=4.72e-05 | epoch=0.4537
[train] step=213 | loss=0.1472 | lr=4.72e-05 | epoch=0.4559
[train] step=214 | loss=0.1074 | lr=4.71e-05 | epoch=0.4580
[train] step=215 | loss=0.1256 | lr=4.71e-05 | epoch=0.4601
[train] step=216 | loss=0.1065 | lr=4.70e-05 | epoch=0.4623
[train] step=217 | loss=0.1249 | lr=4.70e-05 | epoch=0.4644
[train] step=218 | loss=0.1041 | lr=4.70e-05 | epoch=0.4666
[train] step=219 | loss=0.0990 | lr=4.69e-05 | epoch=0.4687
[train] step=220 | loss=0.0941 | lr=4.69e-05 | epoch=0.4708
[train] step=221 | loss=0.1003 | lr=4.68e-05 | epoch=0.4730
[train] step=222 | loss=0.1229 | lr=4.68e-05 | epoch=0.4751
[train] step=223 | loss=0.1239 | lr=4.68e-05 | epoch=0.4773
[train] step=224 | loss=0.1001 | lr=4.67e-05 | epoch=0.4794
[train] step=225 | loss=0.1249 | lr=4.67e-05 | epoch=0.4815
[train] step=226 | loss=0.1165 | lr=4.66e-05 | epoch=0.4837
[train] step=227 | loss=0.1190 | lr=4.66e-05 | epoch=0.4858
[train] step=228 | loss=0.1040 | lr=4.66e-05 | epoch=0.4880
[train] step=229 | loss=0.1166 | lr=4.65e-05 | epoch=0.4901
[train] step=230 | loss=0.1060 | lr=4.65e-05 | epoch=0.4922
[train] step=231 | loss=0.1267 | lr=4.64e-05 | epoch=0.4944
[train] step=232 | loss=0.1101 | lr=4.64e-05 | epoch=0.4965
[train] step=233 | loss=0.1251 | lr=4.64e-05 | epoch=0.4987

Saving model checkpoint to output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-233
2026-04-06 03:01:00 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:01:00 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:01:00 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:01:00 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-233\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-233\tokenizer_config.json

[train] step=234 | loss=0.1122 | lr=4.63e-05 | epoch=0.5008
[train] step=235 | loss=0.1011 | lr=4.63e-05 | epoch=0.5029
[train] step=236 | loss=0.1094 | lr=4.62e-05 | epoch=0.5051
[train] step=237 | loss=0.1151 | lr=4.62e-05 | epoch=0.5072
[train] step=238 | loss=0.1124 | lr=4.62e-05 | epoch=0.5094
[train] step=239 | loss=0.1067 | lr=4.61e-05 | epoch=0.5115
[train] step=240 | loss=0.1082 | lr=4.61e-05 | epoch=0.5136
[train] step=241 | loss=0.1141 | lr=4.60e-05 | epoch=0.5158
[train] step=242 | loss=0.1004 | lr=4.60e-05 | epoch=0.5179
[train] step=243 | loss=0.1338 | lr=4.60e-05 | epoch=0.5201
[train] step=244 | loss=0.1303 | lr=4.59e-05 | epoch=0.5222
[train] step=245 | loss=0.1031 | lr=4.59e-05 | epoch=0.5243
[train] step=246 | loss=0.1338 | lr=4.58e-05 | epoch=0.5265
[train] step=247 | loss=0.1244 | lr=4.58e-05 | epoch=0.5286
[train] step=248 | loss=0.0993 | lr=4.58e-05 | epoch=0.5308
[train] step=249 | loss=0.0941 | lr=4.57e-05 | epoch=0.5329
[train] step=250 | loss=0.1076 | lr=4.57e-05 | epoch=0.5350
[train] step=251 | loss=0.1066 | lr=4.56e-05 | epoch=0.5372
[train] step=252 | loss=0.1146 | lr=4.56e-05 | epoch=0.5393
[train] step=253 | loss=0.1264 | lr=4.56e-05 | epoch=0.5415
[train] step=254 | loss=0.1082 | lr=4.55e-05 | epoch=0.5436
[train] step=255 | loss=0.1093 | lr=4.55e-05 | epoch=0.5457
[train] step=256 | loss=0.0950 | lr=4.55e-05 | epoch=0.5479
[train] step=257 | loss=0.1020 | lr=4.54e-05 | epoch=0.5500
[train] step=258 | loss=0.1045 | lr=4.54e-05 | epoch=0.5522
[train] step=259 | loss=0.1149 | lr=4.53e-05 | epoch=0.5543
[train] step=260 | loss=0.1153 | lr=4.53e-05 | epoch=0.5564
[train] step=261 | loss=0.0967 | lr=4.53e-05 | epoch=0.5586
[train] step=262 | loss=0.1329 | lr=4.52e-05 | epoch=0.5607
[train] step=263 | loss=0.1014 | lr=4.52e-05 | epoch=0.5629
[train] step=264 | loss=0.0940 | lr=4.51e-05 | epoch=0.5650
[train] step=265 | loss=0.1317 | lr=4.51e-05 | epoch=0.5671
[train] step=266 | loss=0.1080 | lr=4.51e-05 | epoch=0.5693
[train] step=267 | loss=0.1105 | lr=4.50e-05 | epoch=0.5714
[train] step=268 | loss=0.1027 | lr=4.50e-05 | epoch=0.5736
[train] step=269 | loss=0.1123 | lr=4.49e-05 | epoch=0.5757
[train] step=270 | loss=0.1268 | lr=4.49e-05 | epoch=0.5778
[train] step=271 | loss=0.1115 | lr=4.49e-05 | epoch=0.5800
[train] step=272 | loss=0.1159 | lr=4.48e-05 | epoch=0.5821
[train] step=273 | loss=0.0930 | lr=4.48e-05 | epoch=0.5843
[train] step=274 | loss=0.1004 | lr=4.47e-05 | epoch=0.5864
[train] step=275 | loss=0.1187 | lr=4.47e-05 | epoch=0.5886
[train] step=276 | loss=0.1209 | lr=4.47e-05 | epoch=0.5907
[train] step=277 | loss=0.1026 | lr=4.46e-05 | epoch=0.5928
[train] step=278 | loss=0.0975 | lr=4.46e-05 | epoch=0.5950
[train] step=279 | loss=0.0987 | lr=4.45e-05 | epoch=0.5971
[train] step=280 | loss=0.1019 | lr=4.45e-05 | epoch=0.5993
[train] step=281 | loss=0.1030 | lr=4.45e-05 | epoch=0.6014
[train] step=282 | loss=0.1139 | lr=4.44e-05 | epoch=0.6035
[train] step=283 | loss=0.1126 | lr=4.44e-05 | epoch=0.6057
[train] step=284 | loss=0.1027 | lr=4.43e-05 | epoch=0.6078
[train] step=285 | loss=0.0981 | lr=4.43e-05 | epoch=0.6100
[train] step=286 | loss=0.0970 | lr=4.43e-05 | epoch=0.6121
[train] step=287 | loss=0.1123 | lr=4.42e-05 | epoch=0.6142
[train] step=288 | loss=0.0975 | lr=4.42e-05 | epoch=0.6164
[train] step=289 | loss=0.0996 | lr=4.41e-05 | epoch=0.6185
[train] step=290 | loss=0.1043 | lr=4.41e-05 | epoch=0.6207
[train] step=291 | loss=0.1247 | lr=4.41e-05 | epoch=0.6228
[train] step=292 | loss=0.1107 | lr=4.40e-05 | epoch=0.6249
[train] step=293 | loss=0.1340 | lr=4.40e-05 | epoch=0.6271
[train] step=294 | loss=0.1028 | lr=4.39e-05 | epoch=0.6292
[train] step=295 | loss=0.1199 | lr=4.39e-05 | epoch=0.6314
[train] step=296 | loss=0.1000 | lr=4.39e-05 | epoch=0.6335
[train] step=297 | loss=0.1117 | lr=4.38e-05 | epoch=0.6356
[train] step=298 | loss=0.0955 | lr=4.38e-05 | epoch=0.6378
[train] step=299 | loss=0.1019 | lr=4.37e-05 | epoch=0.6399
[train] step=300 | loss=0.1113 | lr=4.37e-05 | epoch=0.6421
[train] step=301 | loss=0.1152 | lr=4.37e-05 | epoch=0.6442
[train] step=302 | loss=0.0977 | lr=4.36e-05 | epoch=0.6463
[train] step=303 | loss=0.1078 | lr=4.36e-05 | epoch=0.6485
[train] step=304 | loss=0.1119 | lr=4.36e-05 | epoch=0.6506
[train] step=305 | loss=0.0982 | lr=4.35e-05 | epoch=0.6528
[train] step=306 | loss=0.1286 | lr=4.35e-05 | epoch=0.6549
[train] step=307 | loss=0.1259 | lr=4.34e-05 | epoch=0.6570
[train] step=308 | loss=0.1006 | lr=4.34e-05 | epoch=0.6592
[train] step=309 | loss=0.1290 | lr=4.34e-05 | epoch=0.6613
[train] step=310 | loss=0.0919 | lr=4.33e-05 | epoch=0.6635
[train] step=311 | loss=0.0964 | lr=4.33e-05 | epoch=0.6656
[train] step=312 | loss=0.1368 | lr=4.32e-05 | epoch=0.6677
[train] step=313 | loss=0.1374 | lr=4.32e-05 | epoch=0.6699
[train] step=314 | loss=0.1051 | lr=4.32e-05 | epoch=0.6720
[train] step=315 | loss=0.0955 | lr=4.31e-05 | epoch=0.6742
[train] step=316 | loss=0.1047 | lr=4.31e-05 | epoch=0.6763
[train] step=317 | loss=0.1075 | lr=4.30e-05 | epoch=0.6784
[train] step=318 | loss=0.1053 | lr=4.30e-05 | epoch=0.6806
[train] step=319 | loss=0.1305 | lr=4.30e-05 | epoch=0.6827
[train] step=320 | loss=0.1102 | lr=4.29e-05 | epoch=0.6849
[train] step=321 | loss=0.1047 | lr=4.29e-05 | epoch=0.6870
[train] step=322 | loss=0.1162 | lr=4.28e-05 | epoch=0.6891
[train] step=323 | loss=0.1090 | lr=4.28e-05 | epoch=0.6913
[train] step=324 | loss=0.1084 | lr=4.28e-05 | epoch=0.6934
[train] step=325 | loss=0.1153 | lr=4.27e-05 | epoch=0.6956
[train] step=326 | loss=0.1033 | lr=4.27e-05 | epoch=0.6977
[train] step=327 | loss=0.1135 | lr=4.26e-05 | epoch=0.6998
[train] step=328 | loss=0.1308 | lr=4.26e-05 | epoch=0.7020
[train] step=329 | loss=0.0859 | lr=4.26e-05 | epoch=0.7041
[train] step=330 | loss=0.0933 | lr=4.25e-05 | epoch=0.7063
[train] step=331 | loss=0.1026 | lr=4.25e-05 | epoch=0.7084
[train] step=332 | loss=0.1219 | lr=4.24e-05 | epoch=0.7105
[train] step=333 | loss=0.1288 | lr=4.24e-05 | epoch=0.7127
[train] step=334 | loss=0.1229 | lr=4.24e-05 | epoch=0.7148
[train] step=335 | loss=0.0834 | lr=4.23e-05 | epoch=0.7170
[train] step=336 | loss=0.1045 | lr=4.23e-05 | epoch=0.7191
[train] step=337 | loss=0.0984 | lr=4.22e-05 | epoch=0.7212
[train] step=338 | loss=0.1049 | lr=4.22e-05 | epoch=0.7234
[train] step=339 | loss=0.1151 | lr=4.22e-05 | epoch=0.7255
[train] step=340 | loss=0.1096 | lr=4.21e-05 | epoch=0.7277
[train] step=341 | loss=0.1401 | lr=4.21e-05 | epoch=0.7298
[train] step=342 | loss=0.0983 | lr=4.20e-05 | epoch=0.7319
[train] step=343 | loss=0.0874 | lr=4.20e-05 | epoch=0.7341
[train] step=344 | loss=0.1055 | lr=4.20e-05 | epoch=0.7362
[train] step=345 | loss=0.1192 | lr=4.19e-05 | epoch=0.7384
[train] step=346 | loss=0.1067 | lr=4.19e-05 | epoch=0.7405
[train] step=347 | loss=0.1006 | lr=4.19e-05 | epoch=0.7426
[train] step=348 | loss=0.1183 | lr=4.18e-05 | epoch=0.7448
[train] step=349 | loss=0.1007 | lr=4.18e-05 | epoch=0.7469
[train] step=350 | loss=0.0842 | lr=4.17e-05 | epoch=0.7491
[train] step=351 | loss=0.1179 | lr=4.17e-05 | epoch=0.7512
[train] step=352 | loss=0.1001 | lr=4.17e-05 | epoch=0.7533
[train] step=353 | loss=0.1305 | lr=4.16e-05 | epoch=0.7555
[train] step=354 | loss=0.0841 | lr=4.16e-05 | epoch=0.7576
[train] step=355 | loss=0.1176 | lr=4.15e-05 | epoch=0.7598
[train] step=356 | loss=0.0991 | lr=4.15e-05 | epoch=0.7619
[train] step=357 | loss=0.1139 | lr=4.15e-05 | epoch=0.7640
[train] step=358 | loss=0.0827 | lr=4.14e-05 | epoch=0.7662
[train] step=359 | loss=0.1034 | lr=4.14e-05 | epoch=0.7683
[train] step=360 | loss=0.1177 | lr=4.13e-05 | epoch=0.7705
[train] step=361 | loss=0.1052 | lr=4.13e-05 | epoch=0.7726
[train] step=362 | loss=0.1058 | lr=4.13e-05 | epoch=0.7747
[train] step=363 | loss=0.1299 | lr=4.12e-05 | epoch=0.7769
[train] step=364 | loss=0.1004 | lr=4.12e-05 | epoch=0.7790
[train] step=365 | loss=0.0968 | lr=4.11e-05 | epoch=0.7812
[train] step=366 | loss=0.1181 | lr=4.11e-05 | epoch=0.7833
[train] step=367 | loss=0.0945 | lr=4.11e-05 | epoch=0.7854
[train] step=368 | loss=0.1128 | lr=4.10e-05 | epoch=0.7876
[train] step=369 | loss=0.1150 | lr=4.10e-05 | epoch=0.7897
[train] step=370 | loss=0.1204 | lr=4.09e-05 | epoch=0.7919
[train] step=371 | loss=0.1210 | lr=4.09e-05 | epoch=0.7940
[train] step=372 | loss=0.1102 | lr=4.09e-05 | epoch=0.7961
[train] step=373 | loss=0.1266 | lr=4.08e-05 | epoch=0.7983
[train] step=374 | loss=0.1083 | lr=4.08e-05 | epoch=0.8004
[train] step=375 | loss=0.1174 | lr=4.07e-05 | epoch=0.8026
[train] step=376 | loss=0.1016 | lr=4.07e-05 | epoch=0.8047
[train] step=377 | loss=0.0965 | lr=4.07e-05 | epoch=0.8068
[train] step=378 | loss=0.1002 | lr=4.06e-05 | epoch=0.8090
[train] step=379 | loss=0.1393 | lr=4.06e-05 | epoch=0.8111
[train] step=380 | loss=0.1320 | lr=4.05e-05 | epoch=0.8133
[train] step=381 | loss=0.1326 | lr=4.05e-05 | epoch=0.8154
[train] step=382 | loss=0.1194 | lr=4.05e-05 | epoch=0.8175
[train] step=383 | loss=0.0973 | lr=4.04e-05 | epoch=0.8197
[train] step=384 | loss=0.0881 | lr=4.04e-05 | epoch=0.8218
[train] step=385 | loss=0.1156 | lr=4.03e-05 | epoch=0.8240
[train] step=386 | loss=0.1570 | lr=4.03e-05 | epoch=0.8261
[train] step=387 | loss=0.0955 | lr=4.03e-05 | epoch=0.8283
[train] step=388 | loss=0.1138 | lr=4.02e-05 | epoch=0.8304
[train] step=389 | loss=0.0966 | lr=4.02e-05 | epoch=0.8325
[train] step=390 | loss=0.1008 | lr=4.02e-05 | epoch=0.8347
[train] step=391 | loss=0.0974 | lr=4.01e-05 | epoch=0.8368
[train] step=392 | loss=0.0943 | lr=4.01e-05 | epoch=0.8390
[train] step=393 | loss=0.1044 | lr=4.00e-05 | epoch=0.8411
[train] step=394 | loss=0.1203 | lr=4.00e-05 | epoch=0.8432
[train] step=395 | loss=0.1123 | lr=4.00e-05 | epoch=0.8454
[train] step=396 | loss=0.1195 | lr=3.99e-05 | epoch=0.8475
[train] step=397 | loss=0.1016 | lr=3.99e-05 | epoch=0.8497
[train] step=398 | loss=0.1103 | lr=3.98e-05 | epoch=0.8518
[train] step=399 | loss=0.1047 | lr=3.98e-05 | epoch=0.8539
[train] step=400 | loss=0.1157 | lr=3.98e-05 | epoch=0.8561
[train] step=401 | loss=0.1123 | lr=3.97e-05 | epoch=0.8582
[train] step=402 | loss=0.1090 | lr=3.97e-05 | epoch=0.8604
[train] step=403 | loss=0.0887 | lr=3.96e-05 | epoch=0.8625
[train] step=404 | loss=0.1066 | lr=3.96e-05 | epoch=0.8646
[train] step=405 | loss=0.1107 | lr=3.96e-05 | epoch=0.8668
[train] step=406 | loss=0.0987 | lr=3.95e-05 | epoch=0.8689
[train] step=407 | loss=0.0854 | lr=3.95e-05 | epoch=0.8711
[train] step=408 | loss=0.1271 | lr=3.94e-05 | epoch=0.8732
[train] step=409 | loss=0.1119 | lr=3.94e-05 | epoch=0.8753
[train] step=410 | loss=0.0918 | lr=3.94e-05 | epoch=0.8775
[train] step=411 | loss=0.1014 | lr=3.93e-05 | epoch=0.8796
[train] step=412 | loss=0.1082 | lr=3.93e-05 | epoch=0.8818
[train] step=413 | loss=0.1048 | lr=3.92e-05 | epoch=0.8839
[train] step=414 | loss=0.1173 | lr=3.92e-05 | epoch=0.8860
[train] step=415 | loss=0.0983 | lr=3.92e-05 | epoch=0.8882
[train] step=416 | loss=0.1230 | lr=3.91e-05 | epoch=0.8903
[train] step=417 | loss=0.1184 | lr=3.91e-05 | epoch=0.8925
[train] step=418 | loss=0.0970 | lr=3.90e-05 | epoch=0.8946
[train] step=419 | loss=0.0975 | lr=3.90e-05 | epoch=0.8967
[train] step=420 | loss=0.1160 | lr=3.90e-05 | epoch=0.8989
[train] step=421 | loss=0.0992 | lr=3.89e-05 | epoch=0.9010
[train] step=422 | loss=0.0932 | lr=3.89e-05 | epoch=0.9032
[train] step=423 | loss=0.1201 | lr=3.88e-05 | epoch=0.9053
[train] step=424 | loss=0.1224 | lr=3.88e-05 | epoch=0.9074
[train] step=425 | loss=0.1086 | lr=3.88e-05 | epoch=0.9096
[train] step=426 | loss=0.1035 | lr=3.87e-05 | epoch=0.9117
[train] step=427 | loss=0.1088 | lr=3.87e-05 | epoch=0.9139
[train] step=428 | loss=0.0959 | lr=3.86e-05 | epoch=0.9160
[train] step=429 | loss=0.1101 | lr=3.86e-05 | epoch=0.9181
[train] step=430 | loss=0.1036 | lr=3.86e-05 | epoch=0.9203
[train] step=431 | loss=0.0976 | lr=3.85e-05 | epoch=0.9224
[train] step=432 | loss=0.1446 | lr=3.85e-05 | epoch=0.9246
[train] step=433 | loss=0.0948 | lr=3.84e-05 | epoch=0.9267
[train] step=434 | loss=0.0928 | lr=3.84e-05 | epoch=0.9288
[train] step=435 | loss=0.1126 | lr=3.84e-05 | epoch=0.9310
[train] step=436 | loss=0.1212 | lr=3.83e-05 | epoch=0.9331
[train] step=437 | loss=0.0988 | lr=3.83e-05 | epoch=0.9353
[train] step=438 | loss=0.0893 | lr=3.83e-05 | epoch=0.9374
[train] step=439 | loss=0.1294 | lr=3.82e-05 | epoch=0.9395
[train] step=440 | loss=0.1203 | lr=3.82e-05 | epoch=0.9417
[train] step=441 | loss=0.1128 | lr=3.81e-05 | epoch=0.9438
[train] step=442 | loss=0.1393 | lr=3.81e-05 | epoch=0.9460
[train] step=443 | loss=0.1006 | lr=3.81e-05 | epoch=0.9481
[train] step=444 | loss=0.1034 | lr=3.80e-05 | epoch=0.9502
[train] step=445 | loss=0.1069 | lr=3.80e-05 | epoch=0.9524
[train] step=446 | loss=0.0898 | lr=3.79e-05 | epoch=0.9545
[train] step=447 | loss=0.0913 | lr=3.79e-05 | epoch=0.9567
[train] step=448 | loss=0.1201 | lr=3.79e-05 | epoch=0.9588
[train] step=449 | loss=0.1221 | lr=3.78e-05 | epoch=0.9609
[train] step=450 | loss=0.0891 | lr=3.78e-05 | epoch=0.9631
[train] step=451 | loss=0.1055 | lr=3.77e-05 | epoch=0.9652
[train] step=452 | loss=0.1033 | lr=3.77e-05 | epoch=0.9674
[train] step=453 | loss=0.0968 | lr=3.77e-05 | epoch=0.9695
[train] step=454 | loss=0.1034 | lr=3.76e-05 | epoch=0.9716
[train] step=455 | loss=0.1021 | lr=3.76e-05 | epoch=0.9738
[train] step=456 | loss=0.1166 | lr=3.75e-05 | epoch=0.9759
[train] step=457 | loss=0.1227 | lr=3.75e-05 | epoch=0.9781
[train] step=458 | loss=0.1154 | lr=3.75e-05 | epoch=0.9802
[train] step=459 | loss=0.1219 | lr=3.74e-05 | epoch=0.9823
[train] step=460 | loss=0.1054 | lr=3.74e-05 | epoch=0.9845
[train] step=461 | loss=0.1087 | lr=3.73e-05 | epoch=0.9866
[train] step=462 | loss=0.1081 | lr=3.73e-05 | epoch=0.9888
[train] step=463 | loss=0.0949 | lr=3.73e-05 | epoch=0.9909
[train] step=464 | loss=0.1179 | lr=3.72e-05 | epoch=0.9930
[train] step=465 | loss=0.1005 | lr=3.72e-05 | epoch=0.9952
[train] step=466 | loss=0.1024 | lr=3.71e-05 | epoch=0.9973

Saving model checkpoint to output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-466
2026-04-06 03:10:25 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:10:25 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:10:25 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:10:25 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-466\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-466\tokenizer_config.json

[train] step=467 | loss=0.1129 | lr=3.71e-05 | epoch=0.9995
[train] step=468 | loss=0.0579 | lr=3.71e-05 | epoch=1.0000
[train] step=469 | loss=0.0892 | lr=3.70e-05 | epoch=1.0021
[train] step=470 | loss=0.1017 | lr=3.70e-05 | epoch=1.0043
[train] step=471 | loss=0.1096 | lr=3.69e-05 | epoch=1.0064
[train] step=472 | loss=0.1216 | lr=3.69e-05 | epoch=1.0086
[train] step=473 | loss=0.1056 | lr=3.69e-05 | epoch=1.0107
[train] step=474 | loss=0.1024 | lr=3.68e-05 | epoch=1.0128
[train] step=475 | loss=0.1010 | lr=3.68e-05 | epoch=1.0150
[train] step=476 | loss=0.1150 | lr=3.67e-05 | epoch=1.0171
[train] step=477 | loss=0.1277 | lr=3.67e-05 | epoch=1.0193
[train] step=478 | loss=0.0837 | lr=3.67e-05 | epoch=1.0214
[train] step=479 | loss=0.1168 | lr=3.66e-05 | epoch=1.0235
[train] step=480 | loss=0.0842 | lr=3.66e-05 | epoch=1.0257
[train] step=481 | loss=0.1121 | lr=3.66e-05 | epoch=1.0278
[train] step=482 | loss=0.1241 | lr=3.65e-05 | epoch=1.0300
[train] step=483 | loss=0.0876 | lr=3.65e-05 | epoch=1.0321
[train] step=484 | loss=0.1104 | lr=3.64e-05 | epoch=1.0342
[train] step=485 | loss=0.0882 | lr=3.64e-05 | epoch=1.0364
[train] step=486 | loss=0.1056 | lr=3.64e-05 | epoch=1.0385
[train] step=487 | loss=0.1330 | lr=3.63e-05 | epoch=1.0407
[train] step=488 | loss=0.1179 | lr=3.63e-05 | epoch=1.0428
[train] step=489 | loss=0.0934 | lr=3.62e-05 | epoch=1.0449
[train] step=490 | loss=0.1013 | lr=3.62e-05 | epoch=1.0471
[train] step=491 | loss=0.0984 | lr=3.62e-05 | epoch=1.0492
[train] step=492 | loss=0.1174 | lr=3.61e-05 | epoch=1.0514
[train] step=493 | loss=0.0947 | lr=3.61e-05 | epoch=1.0535
[train] step=494 | loss=0.1106 | lr=3.60e-05 | epoch=1.0556
[train] step=495 | loss=0.0994 | lr=3.60e-05 | epoch=1.0578
[train] step=496 | loss=0.1154 | lr=3.60e-05 | epoch=1.0599
[train] step=497 | loss=0.1018 | lr=3.59e-05 | epoch=1.0621
[train] step=498 | loss=0.1326 | lr=3.59e-05 | epoch=1.0642
[train] step=499 | loss=0.1159 | lr=3.58e-05 | epoch=1.0663
[train] step=500 | loss=0.1090 | lr=3.58e-05 | epoch=1.0685
[train] step=501 | loss=0.0987 | lr=3.58e-05 | epoch=1.0706
[train] step=502 | loss=0.0971 | lr=3.57e-05 | epoch=1.0728
[train] step=503 | loss=0.1455 | lr=3.57e-05 | epoch=1.0749
[train] step=504 | loss=0.1198 | lr=3.56e-05 | epoch=1.0770
[train] step=505 | loss=0.1187 | lr=3.56e-05 | epoch=1.0792
[train] step=506 | loss=0.0978 | lr=3.56e-05 | epoch=1.0813
[train] step=507 | loss=0.1109 | lr=3.55e-05 | epoch=1.0835
[train] step=508 | loss=0.1146 | lr=3.55e-05 | epoch=1.0856
[train] step=509 | loss=0.1497 | lr=3.54e-05 | epoch=1.0877
[train] step=510 | loss=0.1168 | lr=3.54e-05 | epoch=1.0899
[train] step=511 | loss=0.1085 | lr=3.54e-05 | epoch=1.0920
[train] step=512 | loss=0.1068 | lr=3.53e-05 | epoch=1.0942
[train] step=513 | loss=0.0921 | lr=3.53e-05 | epoch=1.0963
[train] step=514 | loss=0.1008 | lr=3.52e-05 | epoch=1.0984
[train] step=515 | loss=0.1064 | lr=3.52e-05 | epoch=1.1006
[train] step=516 | loss=0.1213 | lr=3.52e-05 | epoch=1.1027
[train] step=517 | loss=0.0911 | lr=3.51e-05 | epoch=1.1049
[train] step=518 | loss=0.1306 | lr=3.51e-05 | epoch=1.1070
[train] step=519 | loss=0.1124 | lr=3.50e-05 | epoch=1.1091
[train] step=520 | loss=0.1047 | lr=3.50e-05 | epoch=1.1113
[train] step=521 | loss=0.1019 | lr=3.50e-05 | epoch=1.1134
[train] step=522 | loss=0.1290 | lr=3.49e-05 | epoch=1.1156
[train] step=523 | loss=0.1024 | lr=3.49e-05 | epoch=1.1177
[train] step=524 | loss=0.1030 | lr=3.48e-05 | epoch=1.1199
[train] step=525 | loss=0.0895 | lr=3.48e-05 | epoch=1.1220
[train] step=526 | loss=0.1062 | lr=3.48e-05 | epoch=1.1241
[train] step=527 | loss=0.0900 | lr=3.47e-05 | epoch=1.1263
[train] step=528 | loss=0.1241 | lr=3.47e-05 | epoch=1.1284
[train] step=529 | loss=0.1062 | lr=3.47e-05 | epoch=1.1306
[train] step=530 | loss=0.1096 | lr=3.46e-05 | epoch=1.1327
[train] step=531 | loss=0.1369 | lr=3.46e-05 | epoch=1.1348
[train] step=532 | loss=0.1094 | lr=3.45e-05 | epoch=1.1370
[train] step=533 | loss=0.1054 | lr=3.45e-05 | epoch=1.1391
[train] step=534 | loss=0.1059 | lr=3.45e-05 | epoch=1.1413
[train] step=535 | loss=0.1080 | lr=3.44e-05 | epoch=1.1434
[train] step=536 | loss=0.1155 | lr=3.44e-05 | epoch=1.1455
[train] step=537 | loss=0.0970 | lr=3.43e-05 | epoch=1.1477
[train] step=538 | loss=0.1101 | lr=3.43e-05 | epoch=1.1498
[train] step=539 | loss=0.1067 | lr=3.43e-05 | epoch=1.1520
[train] step=540 | loss=0.0896 | lr=3.42e-05 | epoch=1.1541
[train] step=541 | loss=0.0794 | lr=3.42e-05 | epoch=1.1562
[train] step=542 | loss=0.1155 | lr=3.41e-05 | epoch=1.1584
[train] step=543 | loss=0.1018 | lr=3.41e-05 | epoch=1.1605
[train] step=544 | loss=0.0870 | lr=3.41e-05 | epoch=1.1627
[train] step=545 | loss=0.0995 | lr=3.40e-05 | epoch=1.1648
[train] step=546 | loss=0.0881 | lr=3.40e-05 | epoch=1.1669
[train] step=547 | loss=0.0946 | lr=3.39e-05 | epoch=1.1691
[train] step=548 | loss=0.1024 | lr=3.39e-05 | epoch=1.1712
[train] step=549 | loss=0.0808 | lr=3.39e-05 | epoch=1.1734
[train] step=550 | loss=0.0973 | lr=3.38e-05 | epoch=1.1755
[train] step=551 | loss=0.1047 | lr=3.38e-05 | epoch=1.1776
[train] step=552 | loss=0.1082 | lr=3.37e-05 | epoch=1.1798
[train] step=553 | loss=0.1147 | lr=3.37e-05 | epoch=1.1819
[train] step=554 | loss=0.0948 | lr=3.37e-05 | epoch=1.1841
[train] step=555 | loss=0.0991 | lr=3.36e-05 | epoch=1.1862
[train] step=556 | loss=0.0953 | lr=3.36e-05 | epoch=1.1883
[train] step=557 | loss=0.1221 | lr=3.35e-05 | epoch=1.1905
[train] step=558 | loss=0.1067 | lr=3.35e-05 | epoch=1.1926
[train] step=559 | loss=0.1119 | lr=3.35e-05 | epoch=1.1948
[train] step=560 | loss=0.0992 | lr=3.34e-05 | epoch=1.1969
[train] step=561 | loss=0.1057 | lr=3.34e-05 | epoch=1.1990
[train] step=562 | loss=0.1052 | lr=3.33e-05 | epoch=1.2012
[train] step=563 | loss=0.1171 | lr=3.33e-05 | epoch=1.2033
[train] step=564 | loss=0.0966 | lr=3.33e-05 | epoch=1.2055
[train] step=565 | loss=0.1337 | lr=3.32e-05 | epoch=1.2076
[train] step=566 | loss=0.1129 | lr=3.32e-05 | epoch=1.2097
[train] step=567 | loss=0.0943 | lr=3.31e-05 | epoch=1.2119
[train] step=568 | loss=0.0985 | lr=3.31e-05 | epoch=1.2140
[train] step=569 | loss=0.1081 | lr=3.31e-05 | epoch=1.2162
[train] step=570 | loss=0.0953 | lr=3.30e-05 | epoch=1.2183
[train] step=571 | loss=0.1029 | lr=3.30e-05 | epoch=1.2204
[train] step=572 | loss=0.1104 | lr=3.30e-05 | epoch=1.2226
[train] step=573 | loss=0.1268 | lr=3.29e-05 | epoch=1.2247
[train] step=574 | loss=0.0933 | lr=3.29e-05 | epoch=1.2269
[train] step=575 | loss=0.1030 | lr=3.28e-05 | epoch=1.2290
[train] step=576 | loss=0.1082 | lr=3.28e-05 | epoch=1.2311
[train] step=577 | loss=0.1367 | lr=3.28e-05 | epoch=1.2333
[train] step=578 | loss=0.1124 | lr=3.27e-05 | epoch=1.2354
[train] step=579 | loss=0.1208 | lr=3.27e-05 | epoch=1.2376
[train] step=580 | loss=0.0966 | lr=3.26e-05 | epoch=1.2397
[train] step=581 | loss=0.1000 | lr=3.26e-05 | epoch=1.2418
[train] step=582 | loss=0.1001 | lr=3.26e-05 | epoch=1.2440
[train] step=583 | loss=0.1157 | lr=3.25e-05 | epoch=1.2461
[train] step=584 | loss=0.1010 | lr=3.25e-05 | epoch=1.2483
[train] step=585 | loss=0.1167 | lr=3.24e-05 | epoch=1.2504
[train] step=586 | loss=0.0941 | lr=3.24e-05 | epoch=1.2525
[train] step=587 | loss=0.1109 | lr=3.24e-05 | epoch=1.2547
[train] step=588 | loss=0.1255 | lr=3.23e-05 | epoch=1.2568
[train] step=589 | loss=0.1335 | lr=3.23e-05 | epoch=1.2590
[train] step=590 | loss=0.1231 | lr=3.22e-05 | epoch=1.2611
[train] step=591 | loss=0.0903 | lr=3.22e-05 | epoch=1.2632
[train] step=592 | loss=0.1118 | lr=3.22e-05 | epoch=1.2654
[train] step=593 | loss=0.1007 | lr=3.21e-05 | epoch=1.2675
[train] step=594 | loss=0.0959 | lr=3.21e-05 | epoch=1.2697
[train] step=595 | loss=0.0819 | lr=3.20e-05 | epoch=1.2718
[train] step=596 | loss=0.0988 | lr=3.20e-05 | epoch=1.2739
[train] step=597 | loss=0.1011 | lr=3.20e-05 | epoch=1.2761
[train] step=598 | loss=0.1040 | lr=3.19e-05 | epoch=1.2782
[train] step=599 | loss=0.1008 | lr=3.19e-05 | epoch=1.2804
[train] step=600 | loss=0.1167 | lr=3.18e-05 | epoch=1.2825
[train] step=601 | loss=0.1111 | lr=3.18e-05 | epoch=1.2846
[train] step=602 | loss=0.0956 | lr=3.18e-05 | epoch=1.2868
[train] step=603 | loss=0.0905 | lr=3.17e-05 | epoch=1.2889
[train] step=604 | loss=0.0957 | lr=3.17e-05 | epoch=1.2911
[train] step=605 | loss=0.0960 | lr=3.16e-05 | epoch=1.2932
[train] step=606 | loss=0.0802 | lr=3.16e-05 | epoch=1.2953
[train] step=607 | loss=0.1117 | lr=3.16e-05 | epoch=1.2975
[train] step=608 | loss=0.0850 | lr=3.15e-05 | epoch=1.2996
[train] step=609 | loss=0.1206 | lr=3.15e-05 | epoch=1.3018
[train] step=610 | loss=0.1187 | lr=3.14e-05 | epoch=1.3039
[train] step=611 | loss=0.0835 | lr=3.14e-05 | epoch=1.3060
[train] step=612 | loss=0.1104 | lr=3.14e-05 | epoch=1.3082
[train] step=613 | loss=0.1183 | lr=3.13e-05 | epoch=1.3103
[train] step=614 | loss=0.1067 | lr=3.13e-05 | epoch=1.3125
[train] step=615 | loss=0.1051 | lr=3.13e-05 | epoch=1.3146
[train] step=616 | loss=0.0985 | lr=3.12e-05 | epoch=1.3167
[train] step=617 | loss=0.0774 | lr=3.12e-05 | epoch=1.3189
[train] step=618 | loss=0.1117 | lr=3.11e-05 | epoch=1.3210
[train] step=619 | loss=0.1089 | lr=3.11e-05 | epoch=1.3232
[train] step=620 | loss=0.0993 | lr=3.11e-05 | epoch=1.3253
[train] step=621 | loss=0.1213 | lr=3.10e-05 | epoch=1.3274
[train] step=622 | loss=0.1002 | lr=3.10e-05 | epoch=1.3296
[train] step=623 | loss=0.1033 | lr=3.09e-05 | epoch=1.3317
[train] step=624 | loss=0.1103 | lr=3.09e-05 | epoch=1.3339
[train] step=625 | loss=0.1017 | lr=3.09e-05 | epoch=1.3360
[train] step=626 | loss=0.0915 | lr=3.08e-05 | epoch=1.3381
[train] step=627 | loss=0.1397 | lr=3.08e-05 | epoch=1.3403
[train] step=628 | loss=0.0945 | lr=3.07e-05 | epoch=1.3424
[train] step=629 | loss=0.0786 | lr=3.07e-05 | epoch=1.3446
[train] step=630 | loss=0.1081 | lr=3.07e-05 | epoch=1.3467
[train] step=631 | loss=0.1002 | lr=3.06e-05 | epoch=1.3488
[train] step=632 | loss=0.1102 | lr=3.06e-05 | epoch=1.3510
[train] step=633 | loss=0.1116 | lr=3.05e-05 | epoch=1.3531
[train] step=634 | loss=0.1163 | lr=3.05e-05 | epoch=1.3553
[train] step=635 | loss=0.1001 | lr=3.05e-05 | epoch=1.3574
[train] step=636 | loss=0.1019 | lr=3.04e-05 | epoch=1.3596
[train] step=637 | loss=0.0966 | lr=3.04e-05 | epoch=1.3617
[train] step=638 | loss=0.1093 | lr=3.03e-05 | epoch=1.3638
[train] step=639 | loss=0.1097 | lr=3.03e-05 | epoch=1.3660
[train] step=640 | loss=0.0832 | lr=3.03e-05 | epoch=1.3681
[train] step=641 | loss=0.1008 | lr=3.02e-05 | epoch=1.3703
[train] step=642 | loss=0.1015 | lr=3.02e-05 | epoch=1.3724
[train] step=643 | loss=0.1211 | lr=3.01e-05 | epoch=1.3745
[train] step=644 | loss=0.1162 | lr=3.01e-05 | epoch=1.3767
[train] step=645 | loss=0.1204 | lr=3.01e-05 | epoch=1.3788
[train] step=646 | loss=0.1012 | lr=3.00e-05 | epoch=1.3810
[train] step=647 | loss=0.0901 | lr=3.00e-05 | epoch=1.3831
[train] step=648 | loss=0.1080 | lr=2.99e-05 | epoch=1.3852
[train] step=649 | loss=0.0708 | lr=2.99e-05 | epoch=1.3874
[train] step=650 | loss=0.0901 | lr=2.99e-05 | epoch=1.3895
[train] step=651 | loss=0.0876 | lr=2.98e-05 | epoch=1.3917
[train] step=652 | loss=0.0990 | lr=2.98e-05 | epoch=1.3938
[train] step=653 | loss=0.1164 | lr=2.97e-05 | epoch=1.3959
[train] step=654 | loss=0.0866 | lr=2.97e-05 | epoch=1.3981
[train] step=655 | loss=0.0853 | lr=2.97e-05 | epoch=1.4002
[train] step=656 | loss=0.1094 | lr=2.96e-05 | epoch=1.4024
[train] step=657 | loss=0.1010 | lr=2.96e-05 | epoch=1.4045
[train] step=658 | loss=0.1052 | lr=2.95e-05 | epoch=1.4066
[train] step=659 | loss=0.1146 | lr=2.95e-05 | epoch=1.4088
[train] step=660 | loss=0.1006 | lr=2.95e-05 | epoch=1.4109
[train] step=661 | loss=0.1437 | lr=2.94e-05 | epoch=1.4131
[train] step=662 | loss=0.1077 | lr=2.94e-05 | epoch=1.4152
[train] step=663 | loss=0.1139 | lr=2.94e-05 | epoch=1.4173
[train] step=664 | loss=0.1117 | lr=2.93e-05 | epoch=1.4195
[train] step=665 | loss=0.0954 | lr=2.93e-05 | epoch=1.4216
[train] step=666 | loss=0.0879 | lr=2.92e-05 | epoch=1.4238
[train] step=667 | loss=0.0927 | lr=2.92e-05 | epoch=1.4259
[train] step=668 | loss=0.1002 | lr=2.92e-05 | epoch=1.4280
[train] step=669 | loss=0.1048 | lr=2.91e-05 | epoch=1.4302
[train] step=670 | loss=0.1071 | lr=2.91e-05 | epoch=1.4323
[train] step=671 | loss=0.1056 | lr=2.90e-05 | epoch=1.4345
[train] step=672 | loss=0.0849 | lr=2.90e-05 | epoch=1.4366
[train] step=673 | loss=0.1267 | lr=2.90e-05 | epoch=1.4387
[train] step=674 | loss=0.1121 | lr=2.89e-05 | epoch=1.4409
[train] step=675 | loss=0.0879 | lr=2.89e-05 | epoch=1.4430
[train] step=676 | loss=0.1031 | lr=2.88e-05 | epoch=1.4452
[train] step=677 | loss=0.0926 | lr=2.88e-05 | epoch=1.4473
[train] step=678 | loss=0.0921 | lr=2.88e-05 | epoch=1.4494
[train] step=679 | loss=0.0919 | lr=2.87e-05 | epoch=1.4516
[train] step=680 | loss=0.0923 | lr=2.87e-05 | epoch=1.4537
[train] step=681 | loss=0.1114 | lr=2.86e-05 | epoch=1.4559
[train] step=682 | loss=0.1019 | lr=2.86e-05 | epoch=1.4580
[train] step=683 | loss=0.0908 | lr=2.86e-05 | epoch=1.4601
[train] step=684 | loss=0.1027 | lr=2.85e-05 | epoch=1.4623
[train] step=685 | loss=0.1184 | lr=2.85e-05 | epoch=1.4644
[train] step=686 | loss=0.1050 | lr=2.84e-05 | epoch=1.4666
[train] step=687 | loss=0.0985 | lr=2.84e-05 | epoch=1.4687
[train] step=688 | loss=0.1299 | lr=2.84e-05 | epoch=1.4708
[train] step=689 | loss=0.1077 | lr=2.83e-05 | epoch=1.4730
[train] step=690 | loss=0.1190 | lr=2.83e-05 | epoch=1.4751
[train] step=691 | loss=0.0832 | lr=2.82e-05 | epoch=1.4773
[train] step=692 | loss=0.1088 | lr=2.82e-05 | epoch=1.4794
[train] step=693 | loss=0.0991 | lr=2.82e-05 | epoch=1.4815
[train] step=694 | loss=0.1071 | lr=2.81e-05 | epoch=1.4837
[train] step=695 | loss=0.0867 | lr=2.81e-05 | epoch=1.4858
[train] step=696 | loss=0.1105 | lr=2.80e-05 | epoch=1.4880
[train] step=697 | loss=0.1240 | lr=2.80e-05 | epoch=1.4901
[train] step=698 | loss=0.1144 | lr=2.80e-05 | epoch=1.4922
[train] step=699 | loss=0.1199 | lr=2.79e-05 | epoch=1.4944

Saving model checkpoint to output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-699
2026-04-06 03:20:04 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:20:04 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:20:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:20:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-699\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-699\tokenizer_config.json

[train] step=700 | loss=0.0946 | lr=2.79e-05 | epoch=1.4965
[train] step=701 | loss=0.1209 | lr=2.78e-05 | epoch=1.4987
[train] step=702 | loss=0.0899 | lr=2.78e-05 | epoch=1.5008
[train] step=703 | loss=0.1010 | lr=2.78e-05 | epoch=1.5029
[train] step=704 | loss=0.0965 | lr=2.77e-05 | epoch=1.5051
[train] step=705 | loss=0.1227 | lr=2.77e-05 | epoch=1.5072
[train] step=706 | loss=0.1163 | lr=2.77e-05 | epoch=1.5094
[train] step=707 | loss=0.1100 | lr=2.76e-05 | epoch=1.5115
[train] step=708 | loss=0.0961 | lr=2.76e-05 | epoch=1.5136
[train] step=709 | loss=0.0861 | lr=2.75e-05 | epoch=1.5158
[train] step=710 | loss=0.1046 | lr=2.75e-05 | epoch=1.5179
[train] step=711 | loss=0.0992 | lr=2.75e-05 | epoch=1.5201
[train] step=712 | loss=0.1041 | lr=2.74e-05 | epoch=1.5222
[train] step=713 | loss=0.0896 | lr=2.74e-05 | epoch=1.5243
[train] step=714 | loss=0.0878 | lr=2.73e-05 | epoch=1.5265
[train] step=715 | loss=0.0809 | lr=2.73e-05 | epoch=1.5286
[train] step=716 | loss=0.1084 | lr=2.73e-05 | epoch=1.5308
[train] step=717 | loss=0.1099 | lr=2.72e-05 | epoch=1.5329
[train] step=718 | loss=0.1048 | lr=2.72e-05 | epoch=1.5350
[train] step=719 | loss=0.0774 | lr=2.71e-05 | epoch=1.5372
[train] step=720 | loss=0.1133 | lr=2.71e-05 | epoch=1.5393
[train] step=721 | loss=0.1088 | lr=2.71e-05 | epoch=1.5415
[train] step=722 | loss=0.1009 | lr=2.70e-05 | epoch=1.5436
[train] step=723 | loss=0.1107 | lr=2.70e-05 | epoch=1.5457
[train] step=724 | loss=0.0927 | lr=2.69e-05 | epoch=1.5479
[train] step=725 | loss=0.1597 | lr=2.69e-05 | epoch=1.5500
[train] step=726 | loss=0.1056 | lr=2.69e-05 | epoch=1.5522
[train] step=727 | loss=0.1017 | lr=2.68e-05 | epoch=1.5543
[train] step=728 | loss=0.0995 | lr=2.68e-05 | epoch=1.5564
[train] step=729 | loss=0.1070 | lr=2.67e-05 | epoch=1.5586
[train] step=730 | loss=0.1055 | lr=2.67e-05 | epoch=1.5607
[train] step=731 | loss=0.1041 | lr=2.67e-05 | epoch=1.5629
[train] step=732 | loss=0.1114 | lr=2.66e-05 | epoch=1.5650
[train] step=733 | loss=0.0803 | lr=2.66e-05 | epoch=1.5671
[train] step=734 | loss=0.1000 | lr=2.65e-05 | epoch=1.5693
[train] step=735 | loss=0.0998 | lr=2.65e-05 | epoch=1.5714
[train] step=736 | loss=0.1012 | lr=2.65e-05 | epoch=1.5736
[train] step=737 | loss=0.1019 | lr=2.64e-05 | epoch=1.5757
[train] step=738 | loss=0.1051 | lr=2.64e-05 | epoch=1.5778
[train] step=739 | loss=0.1055 | lr=2.63e-05 | epoch=1.5800
[train] step=740 | loss=0.1227 | lr=2.63e-05 | epoch=1.5821
[train] step=741 | loss=0.1086 | lr=2.63e-05 | epoch=1.5843
[train] step=742 | loss=0.1186 | lr=2.62e-05 | epoch=1.5864
[train] step=743 | loss=0.1019 | lr=2.62e-05 | epoch=1.5886
[train] step=744 | loss=0.1109 | lr=2.61e-05 | epoch=1.5907
[train] step=745 | loss=0.0855 | lr=2.61e-05 | epoch=1.5928
[train] step=746 | loss=0.1058 | lr=2.61e-05 | epoch=1.5950
[train] step=747 | loss=0.1272 | lr=2.60e-05 | epoch=1.5971
[train] step=748 | loss=0.0949 | lr=2.60e-05 | epoch=1.5993
[train] step=749 | loss=0.0980 | lr=2.59e-05 | epoch=1.6014
[train] step=750 | loss=0.1076 | lr=2.59e-05 | epoch=1.6035
[train] step=751 | loss=0.1104 | lr=2.59e-05 | epoch=1.6057
[train] step=752 | loss=0.1029 | lr=2.58e-05 | epoch=1.6078
[train] step=753 | loss=0.1192 | lr=2.58e-05 | epoch=1.6100
[train] step=754 | loss=0.1046 | lr=2.58e-05 | epoch=1.6121
[train] step=755 | loss=0.1093 | lr=2.57e-05 | epoch=1.6142
[train] step=756 | loss=0.1088 | lr=2.57e-05 | epoch=1.6164
[train] step=757 | loss=0.0942 | lr=2.56e-05 | epoch=1.6185
[train] step=758 | loss=0.0914 | lr=2.56e-05 | epoch=1.6207
[train] step=759 | loss=0.0927 | lr=2.56e-05 | epoch=1.6228
[train] step=760 | loss=0.0770 | lr=2.55e-05 | epoch=1.6249
[train] step=761 | loss=0.0955 | lr=2.55e-05 | epoch=1.6271
[train] step=762 | loss=0.1163 | lr=2.54e-05 | epoch=1.6292
[train] step=763 | loss=0.1153 | lr=2.54e-05 | epoch=1.6314
[train] step=764 | loss=0.1321 | lr=2.54e-05 | epoch=1.6335
[train] step=765 | loss=0.0984 | lr=2.53e-05 | epoch=1.6356
[train] step=766 | loss=0.1235 | lr=2.53e-05 | epoch=1.6378
[train] step=767 | loss=0.1262 | lr=2.52e-05 | epoch=1.6399
[train] step=768 | loss=0.0900 | lr=2.52e-05 | epoch=1.6421
[train] step=769 | loss=0.1123 | lr=2.52e-05 | epoch=1.6442
[train] step=770 | loss=0.0852 | lr=2.51e-05 | epoch=1.6463
[train] step=771 | loss=0.1081 | lr=2.51e-05 | epoch=1.6485
[train] step=772 | loss=0.0905 | lr=2.50e-05 | epoch=1.6506
[train] step=773 | loss=0.0964 | lr=2.50e-05 | epoch=1.6528
[train] step=774 | loss=0.0808 | lr=2.50e-05 | epoch=1.6549
[train] step=775 | loss=0.1074 | lr=2.49e-05 | epoch=1.6570
[train] step=776 | loss=0.0819 | lr=2.49e-05 | epoch=1.6592
[train] step=777 | loss=0.1059 | lr=2.48e-05 | epoch=1.6613
[train] step=778 | loss=0.1085 | lr=2.48e-05 | epoch=1.6635
[train] step=779 | loss=0.1080 | lr=2.48e-05 | epoch=1.6656
[train] step=780 | loss=0.1272 | lr=2.47e-05 | epoch=1.6677
[train] step=781 | loss=0.0913 | lr=2.47e-05 | epoch=1.6699
[train] step=782 | loss=0.0962 | lr=2.46e-05 | epoch=1.6720
[train] step=783 | loss=0.1032 | lr=2.46e-05 | epoch=1.6742
[train] step=784 | loss=0.1097 | lr=2.46e-05 | epoch=1.6763
[train] step=785 | loss=0.0837 | lr=2.45e-05 | epoch=1.6784
[train] step=786 | loss=0.1032 | lr=2.45e-05 | epoch=1.6806
[train] step=787 | loss=0.0997 | lr=2.44e-05 | epoch=1.6827
[train] step=788 | loss=0.1179 | lr=2.44e-05 | epoch=1.6849
[train] step=789 | loss=0.1098 | lr=2.44e-05 | epoch=1.6870
[train] step=790 | loss=0.1025 | lr=2.43e-05 | epoch=1.6891
[train] step=791 | loss=0.0942 | lr=2.43e-05 | epoch=1.6913
[train] step=792 | loss=0.0987 | lr=2.42e-05 | epoch=1.6934
[train] step=793 | loss=0.1128 | lr=2.42e-05 | epoch=1.6956
[train] step=794 | loss=0.1042 | lr=2.42e-05 | epoch=1.6977
[train] step=795 | loss=0.0995 | lr=2.41e-05 | epoch=1.6998
[train] step=796 | loss=0.1217 | lr=2.41e-05 | epoch=1.7020
[train] step=797 | loss=0.1084 | lr=2.41e-05 | epoch=1.7041
[train] step=798 | loss=0.1073 | lr=2.40e-05 | epoch=1.7063
[train] step=799 | loss=0.1055 | lr=2.40e-05 | epoch=1.7084
[train] step=800 | loss=0.1042 | lr=2.39e-05 | epoch=1.7105
[train] step=801 | loss=0.1190 | lr=2.39e-05 | epoch=1.7127
[train] step=802 | loss=0.1089 | lr=2.39e-05 | epoch=1.7148
[train] step=803 | loss=0.1260 | lr=2.38e-05 | epoch=1.7170
[train] step=804 | loss=0.0961 | lr=2.38e-05 | epoch=1.7191
[train] step=805 | loss=0.1017 | lr=2.37e-05 | epoch=1.7212
[train] step=806 | loss=0.1003 | lr=2.37e-05 | epoch=1.7234
[train] step=807 | loss=0.1081 | lr=2.37e-05 | epoch=1.7255
[train] step=808 | loss=0.0751 | lr=2.36e-05 | epoch=1.7277
[train] step=809 | loss=0.0950 | lr=2.36e-05 | epoch=1.7298
[train] step=810 | loss=0.1127 | lr=2.35e-05 | epoch=1.7319
[train] step=811 | loss=0.0957 | lr=2.35e-05 | epoch=1.7341
[train] step=812 | loss=0.1147 | lr=2.35e-05 | epoch=1.7362
[train] step=813 | loss=0.1023 | lr=2.34e-05 | epoch=1.7384
[train] step=814 | loss=0.0879 | lr=2.34e-05 | epoch=1.7405
[train] step=815 | loss=0.0874 | lr=2.33e-05 | epoch=1.7426
[train] step=816 | loss=0.1216 | lr=2.33e-05 | epoch=1.7448
[train] step=817 | loss=0.1033 | lr=2.33e-05 | epoch=1.7469
[train] step=818 | loss=0.1192 | lr=2.32e-05 | epoch=1.7491
[train] step=819 | loss=0.0927 | lr=2.32e-05 | epoch=1.7512
[train] step=820 | loss=0.1067 | lr=2.31e-05 | epoch=1.7533
[train] step=821 | loss=0.1125 | lr=2.31e-05 | epoch=1.7555
[train] step=822 | loss=0.0935 | lr=2.31e-05 | epoch=1.7576
[train] step=823 | loss=0.1131 | lr=2.30e-05 | epoch=1.7598
[train] step=824 | loss=0.0905 | lr=2.30e-05 | epoch=1.7619
[train] step=825 | loss=0.0994 | lr=2.29e-05 | epoch=1.7640
[train] step=826 | loss=0.0894 | lr=2.29e-05 | epoch=1.7662
[train] step=827 | loss=0.0958 | lr=2.29e-05 | epoch=1.7683
[train] step=828 | loss=0.1013 | lr=2.28e-05 | epoch=1.7705
[train] step=829 | loss=0.0894 | lr=2.28e-05 | epoch=1.7726
[train] step=830 | loss=0.1038 | lr=2.27e-05 | epoch=1.7747
[train] step=831 | loss=0.0925 | lr=2.27e-05 | epoch=1.7769
[train] step=832 | loss=0.1192 | lr=2.27e-05 | epoch=1.7790
[train] step=833 | loss=0.1219 | lr=2.26e-05 | epoch=1.7812
[train] step=834 | loss=0.0955 | lr=2.26e-05 | epoch=1.7833
[train] step=835 | loss=0.1246 | lr=2.25e-05 | epoch=1.7854
[train] step=836 | loss=0.0955 | lr=2.25e-05 | epoch=1.7876
[train] step=837 | loss=0.0944 | lr=2.25e-05 | epoch=1.7897
[train] step=838 | loss=0.1239 | lr=2.24e-05 | epoch=1.7919
[train] step=839 | loss=0.1093 | lr=2.24e-05 | epoch=1.7940
[train] step=840 | loss=0.0918 | lr=2.23e-05 | epoch=1.7961
[train] step=841 | loss=0.0931 | lr=2.23e-05 | epoch=1.7983
[train] step=842 | loss=0.1073 | lr=2.23e-05 | epoch=1.8004
[train] step=843 | loss=0.0779 | lr=2.22e-05 | epoch=1.8026
[train] step=844 | loss=0.0957 | lr=2.22e-05 | epoch=1.8047
[train] step=845 | loss=0.1003 | lr=2.22e-05 | epoch=1.8068
[train] step=846 | loss=0.1042 | lr=2.21e-05 | epoch=1.8090
[train] step=847 | loss=0.0935 | lr=2.21e-05 | epoch=1.8111
[train] step=848 | loss=0.0768 | lr=2.20e-05 | epoch=1.8133
[train] step=849 | loss=0.0916 | lr=2.20e-05 | epoch=1.8154
[train] step=850 | loss=0.1121 | lr=2.20e-05 | epoch=1.8175
[train] step=851 | loss=0.1098 | lr=2.19e-05 | epoch=1.8197
[train] step=852 | loss=0.0877 | lr=2.19e-05 | epoch=1.8218
[train] step=853 | loss=0.1189 | lr=2.18e-05 | epoch=1.8240
[train] step=854 | loss=0.1003 | lr=2.18e-05 | epoch=1.8261
[train] step=855 | loss=0.0981 | lr=2.18e-05 | epoch=1.8283
[train] step=856 | loss=0.1121 | lr=2.17e-05 | epoch=1.8304
[train] step=857 | loss=0.0924 | lr=2.17e-05 | epoch=1.8325
[train] step=858 | loss=0.0873 | lr=2.16e-05 | epoch=1.8347
[train] step=859 | loss=0.1016 | lr=2.16e-05 | epoch=1.8368
[train] step=860 | loss=0.1141 | lr=2.16e-05 | epoch=1.8390
[train] step=861 | loss=0.0985 | lr=2.15e-05 | epoch=1.8411
[train] step=862 | loss=0.0911 | lr=2.15e-05 | epoch=1.8432
[train] step=863 | loss=0.0879 | lr=2.14e-05 | epoch=1.8454
[train] step=864 | loss=0.1069 | lr=2.14e-05 | epoch=1.8475
[train] step=865 | loss=0.1015 | lr=2.14e-05 | epoch=1.8497
[train] step=866 | loss=0.1011 | lr=2.13e-05 | epoch=1.8518
[train] step=867 | loss=0.1027 | lr=2.13e-05 | epoch=1.8539
[train] step=868 | loss=0.0800 | lr=2.12e-05 | epoch=1.8561
[train] step=869 | loss=0.0979 | lr=2.12e-05 | epoch=1.8582
[train] step=870 | loss=0.1157 | lr=2.12e-05 | epoch=1.8604
[train] step=871 | loss=0.1219 | lr=2.11e-05 | epoch=1.8625
[train] step=872 | loss=0.1379 | lr=2.11e-05 | epoch=1.8646
[train] step=873 | loss=0.0987 | lr=2.10e-05 | epoch=1.8668
[train] step=874 | loss=0.1075 | lr=2.10e-05 | epoch=1.8689
[train] step=875 | loss=0.0935 | lr=2.10e-05 | epoch=1.8711
[train] step=876 | loss=0.1064 | lr=2.09e-05 | epoch=1.8732
[train] step=877 | loss=0.1269 | lr=2.09e-05 | epoch=1.8753
[train] step=878 | loss=0.0954 | lr=2.08e-05 | epoch=1.8775
[train] step=879 | loss=0.0905 | lr=2.08e-05 | epoch=1.8796
[train] step=880 | loss=0.1400 | lr=2.08e-05 | epoch=1.8818
[train] step=881 | loss=0.0908 | lr=2.07e-05 | epoch=1.8839
[train] step=882 | loss=0.1154 | lr=2.07e-05 | epoch=1.8860
[train] step=883 | loss=0.0996 | lr=2.06e-05 | epoch=1.8882
[train] step=884 | loss=0.1133 | lr=2.06e-05 | epoch=1.8903
[train] step=885 | loss=0.1198 | lr=2.06e-05 | epoch=1.8925
[train] step=886 | loss=0.1029 | lr=2.05e-05 | epoch=1.8946
[train] step=887 | loss=0.1223 | lr=2.05e-05 | epoch=1.8967
[train] step=888 | loss=0.1346 | lr=2.05e-05 | epoch=1.8989
[train] step=889 | loss=0.1251 | lr=2.04e-05 | epoch=1.9010
[train] step=890 | loss=0.1074 | lr=2.04e-05 | epoch=1.9032
[train] step=891 | loss=0.1008 | lr=2.03e-05 | epoch=1.9053
[train] step=892 | loss=0.0924 | lr=2.03e-05 | epoch=1.9074
[train] step=893 | loss=0.1090 | lr=2.03e-05 | epoch=1.9096
[train] step=894 | loss=0.1218 | lr=2.02e-05 | epoch=1.9117
[train] step=895 | loss=0.1158 | lr=2.02e-05 | epoch=1.9139
[train] step=896 | loss=0.0848 | lr=2.01e-05 | epoch=1.9160
[train] step=897 | loss=0.1116 | lr=2.01e-05 | epoch=1.9181
[train] step=898 | loss=0.1087 | lr=2.01e-05 | epoch=1.9203
[train] step=899 | loss=0.1033 | lr=2.00e-05 | epoch=1.9224
[train] step=900 | loss=0.1105 | lr=2.00e-05 | epoch=1.9246
[train] step=901 | loss=0.0995 | lr=1.99e-05 | epoch=1.9267
[train] step=902 | loss=0.1105 | lr=1.99e-05 | epoch=1.9288
[train] step=903 | loss=0.0941 | lr=1.99e-05 | epoch=1.9310
[train] step=904 | loss=0.1014 | lr=1.98e-05 | epoch=1.9331
[train] step=905 | loss=0.1131 | lr=1.98e-05 | epoch=1.9353
[train] step=906 | loss=0.1246 | lr=1.97e-05 | epoch=1.9374
[train] step=907 | loss=0.1033 | lr=1.97e-05 | epoch=1.9395
[train] step=908 | loss=0.0902 | lr=1.97e-05 | epoch=1.9417
[train] step=909 | loss=0.1233 | lr=1.96e-05 | epoch=1.9438
[train] step=910 | loss=0.1076 | lr=1.96e-05 | epoch=1.9460
[train] step=911 | loss=0.1048 | lr=1.95e-05 | epoch=1.9481
[train] step=912 | loss=0.1037 | lr=1.95e-05 | epoch=1.9502
[train] step=913 | loss=0.1050 | lr=1.95e-05 | epoch=1.9524
[train] step=914 | loss=0.0791 | lr=1.94e-05 | epoch=1.9545
[train] step=915 | loss=0.0956 | lr=1.94e-05 | epoch=1.9567
[train] step=916 | loss=0.0969 | lr=1.93e-05 | epoch=1.9588
[train] step=917 | loss=0.0879 | lr=1.93e-05 | epoch=1.9609
[train] step=918 | loss=0.1082 | lr=1.93e-05 | epoch=1.9631
[train] step=919 | loss=0.1082 | lr=1.92e-05 | epoch=1.9652
[train] step=920 | loss=0.0915 | lr=1.92e-05 | epoch=1.9674
[train] step=921 | loss=0.0983 | lr=1.91e-05 | epoch=1.9695
[train] step=922 | loss=0.1052 | lr=1.91e-05 | epoch=1.9716
[train] step=923 | loss=0.0911 | lr=1.91e-05 | epoch=1.9738
[train] step=924 | loss=0.0916 | lr=1.90e-05 | epoch=1.9759
[train] step=925 | loss=0.1059 | lr=1.90e-05 | epoch=1.9781
[train] step=926 | loss=0.0996 | lr=1.89e-05 | epoch=1.9802
[train] step=927 | loss=0.1107 | lr=1.89e-05 | epoch=1.9823
[train] step=928 | loss=0.1099 | lr=1.89e-05 | epoch=1.9845
[train] step=929 | loss=0.1196 | lr=1.88e-05 | epoch=1.9866
[train] step=930 | loss=0.1091 | lr=1.88e-05 | epoch=1.9888
[train] step=931 | loss=0.0897 | lr=1.88e-05 | epoch=1.9909
[train] step=932 | loss=0.1071 | lr=1.87e-05 | epoch=1.9930

Saving model checkpoint to output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-932
2026-04-06 03:29:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:29:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:29:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:29:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-932\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-932\tokenizer_config.json

[train] step=933 | loss=0.1344 | lr=1.87e-05 | epoch=1.9952
[train] step=934 | loss=0.1074 | lr=1.86e-05 | epoch=1.9973
[train] step=935 | loss=0.1079 | lr=1.86e-05 | epoch=1.9995
[train] step=936 | loss=0.0350 | lr=1.86e-05 | epoch=2.0000
[train] step=937 | loss=0.0909 | lr=1.85e-05 | epoch=2.0021
[train] step=938 | loss=0.0959 | lr=1.85e-05 | epoch=2.0043
[train] step=939 | loss=0.0730 | lr=1.84e-05 | epoch=2.0064
[train] step=940 | loss=0.0972 | lr=1.84e-05 | epoch=2.0086
[train] step=941 | loss=0.1049 | lr=1.84e-05 | epoch=2.0107
[train] step=942 | loss=0.1063 | lr=1.83e-05 | epoch=2.0128
[train] step=943 | loss=0.1017 | lr=1.83e-05 | epoch=2.0150
[train] step=944 | loss=0.1055 | lr=1.82e-05 | epoch=2.0171
[train] step=945 | loss=0.1067 | lr=1.82e-05 | epoch=2.0193
[train] step=946 | loss=0.1093 | lr=1.82e-05 | epoch=2.0214
[train] step=947 | loss=0.1003 | lr=1.81e-05 | epoch=2.0235
[train] step=948 | loss=0.0995 | lr=1.81e-05 | epoch=2.0257
[train] step=949 | loss=0.1239 | lr=1.80e-05 | epoch=2.0278
[train] step=950 | loss=0.0834 | lr=1.80e-05 | epoch=2.0300
[train] step=951 | loss=0.0993 | lr=1.80e-05 | epoch=2.0321
[train] step=952 | loss=0.1077 | lr=1.79e-05 | epoch=2.0342
[train] step=953 | loss=0.1056 | lr=1.79e-05 | epoch=2.0364
[train] step=954 | loss=0.0941 | lr=1.78e-05 | epoch=2.0385
[train] step=955 | loss=0.1487 | lr=1.78e-05 | epoch=2.0407
[train] step=956 | loss=0.0929 | lr=1.78e-05 | epoch=2.0428
[train] step=957 | loss=0.0809 | lr=1.77e-05 | epoch=2.0449
[train] step=958 | loss=0.1193 | lr=1.77e-05 | epoch=2.0471
[train] step=959 | loss=0.0940 | lr=1.76e-05 | epoch=2.0492
[train] step=960 | loss=0.0947 | lr=1.76e-05 | epoch=2.0514
[train] step=961 | loss=0.0994 | lr=1.76e-05 | epoch=2.0535
[train] step=962 | loss=0.0965 | lr=1.75e-05 | epoch=2.0556
[train] step=963 | loss=0.1117 | lr=1.75e-05 | epoch=2.0578
[train] step=964 | loss=0.0809 | lr=1.74e-05 | epoch=2.0599
[train] step=965 | loss=0.0930 | lr=1.74e-05 | epoch=2.0621
[train] step=966 | loss=0.1114 | lr=1.74e-05 | epoch=2.0642
[train] step=967 | loss=0.0945 | lr=1.73e-05 | epoch=2.0663
[train] step=968 | loss=0.1126 | lr=1.73e-05 | epoch=2.0685
[train] step=969 | loss=0.1002 | lr=1.72e-05 | epoch=2.0706
[train] step=970 | loss=0.1052 | lr=1.72e-05 | epoch=2.0728
[train] step=971 | loss=0.1021 | lr=1.72e-05 | epoch=2.0749
[train] step=972 | loss=0.1213 | lr=1.71e-05 | epoch=2.0770
[train] step=973 | loss=0.1073 | lr=1.71e-05 | epoch=2.0792
[train] step=974 | loss=0.1257 | lr=1.70e-05 | epoch=2.0813
[train] step=975 | loss=0.0952 | lr=1.70e-05 | epoch=2.0835
[train] step=976 | loss=0.0891 | lr=1.70e-05 | epoch=2.0856
[train] step=977 | loss=0.0875 | lr=1.69e-05 | epoch=2.0877
[train] step=978 | loss=0.0908 | lr=1.69e-05 | epoch=2.0899
[train] step=979 | loss=0.0858 | lr=1.69e-05 | epoch=2.0920
[train] step=980 | loss=0.0912 | lr=1.68e-05 | epoch=2.0942
[train] step=981 | loss=0.1062 | lr=1.68e-05 | epoch=2.0963
[train] step=982 | loss=0.1121 | lr=1.67e-05 | epoch=2.0984
[train] step=983 | loss=0.0996 | lr=1.67e-05 | epoch=2.1006
[train] step=984 | loss=0.0876 | lr=1.67e-05 | epoch=2.1027
[train] step=985 | loss=0.1115 | lr=1.66e-05 | epoch=2.1049
[train] step=986 | loss=0.1053 | lr=1.66e-05 | epoch=2.1070
[train] step=987 | loss=0.1207 | lr=1.65e-05 | epoch=2.1091
[train] step=988 | loss=0.0857 | lr=1.65e-05 | epoch=2.1113
[train] step=989 | loss=0.1184 | lr=1.65e-05 | epoch=2.1134
[train] step=990 | loss=0.0985 | lr=1.64e-05 | epoch=2.1156
[train] step=991 | loss=0.0976 | lr=1.64e-05 | epoch=2.1177
[train] step=992 | loss=0.1096 | lr=1.63e-05 | epoch=2.1199
[train] step=993 | loss=0.0715 | lr=1.63e-05 | epoch=2.1220
[train] step=994 | loss=0.0928 | lr=1.63e-05 | epoch=2.1241
[train] step=995 | loss=0.1155 | lr=1.62e-05 | epoch=2.1263
[train] step=996 | loss=0.0931 | lr=1.62e-05 | epoch=2.1284
[train] step=997 | loss=0.0890 | lr=1.61e-05 | epoch=2.1306
[train] step=998 | loss=0.0987 | lr=1.61e-05 | epoch=2.1327
[train] step=999 | loss=0.1155 | lr=1.61e-05 | epoch=2.1348
[train] step=1000 | loss=0.0978 | lr=1.60e-05 | epoch=2.1370
[train] step=1001 | loss=0.0888 | lr=1.60e-05 | epoch=2.1391
[train] step=1002 | loss=0.0946 | lr=1.59e-05 | epoch=2.1413
[train] step=1003 | loss=0.0918 | lr=1.59e-05 | epoch=2.1434
[train] step=1004 | loss=0.0969 | lr=1.59e-05 | epoch=2.1455
[train] step=1005 | loss=0.1004 | lr=1.58e-05 | epoch=2.1477
[train] step=1006 | loss=0.0987 | lr=1.58e-05 | epoch=2.1498
[train] step=1007 | loss=0.1010 | lr=1.57e-05 | epoch=2.1520
[train] step=1008 | loss=0.0865 | lr=1.57e-05 | epoch=2.1541
[train] step=1009 | loss=0.0986 | lr=1.57e-05 | epoch=2.1562
[train] step=1010 | loss=0.0780 | lr=1.56e-05 | epoch=2.1584
[train] step=1011 | loss=0.1335 | lr=1.56e-05 | epoch=2.1605
[train] step=1012 | loss=0.1123 | lr=1.55e-05 | epoch=2.1627
[train] step=1013 | loss=0.1043 | lr=1.55e-05 | epoch=2.1648
[train] step=1014 | loss=0.0907 | lr=1.55e-05 | epoch=2.1669
[train] step=1015 | loss=0.0882 | lr=1.54e-05 | epoch=2.1691
[train] step=1016 | loss=0.1018 | lr=1.54e-05 | epoch=2.1712
[train] step=1017 | loss=0.1147 | lr=1.53e-05 | epoch=2.1734
[train] step=1018 | loss=0.0973 | lr=1.53e-05 | epoch=2.1755
[train] step=1019 | loss=0.1196 | lr=1.53e-05 | epoch=2.1776
[train] step=1020 | loss=0.0902 | lr=1.52e-05 | epoch=2.1798
[train] step=1021 | loss=0.0898 | lr=1.52e-05 | epoch=2.1819
[train] step=1022 | loss=0.1194 | lr=1.52e-05 | epoch=2.1841
[train] step=1023 | loss=0.0937 | lr=1.51e-05 | epoch=2.1862
[train] step=1024 | loss=0.0973 | lr=1.51e-05 | epoch=2.1883
[train] step=1025 | loss=0.0954 | lr=1.50e-05 | epoch=2.1905
[train] step=1026 | loss=0.1096 | lr=1.50e-05 | epoch=2.1926
[train] step=1027 | loss=0.1116 | lr=1.50e-05 | epoch=2.1948
[train] step=1028 | loss=0.0992 | lr=1.49e-05 | epoch=2.1969
[train] step=1029 | loss=0.1319 | lr=1.49e-05 | epoch=2.1990
[train] step=1030 | loss=0.1002 | lr=1.48e-05 | epoch=2.2012
[train] step=1031 | loss=0.1115 | lr=1.48e-05 | epoch=2.2033
[train] step=1032 | loss=0.1014 | lr=1.48e-05 | epoch=2.2055
[train] step=1033 | loss=0.1124 | lr=1.47e-05 | epoch=2.2076
[train] step=1034 | loss=0.0981 | lr=1.47e-05 | epoch=2.2097
[train] step=1035 | loss=0.1098 | lr=1.46e-05 | epoch=2.2119
[train] step=1036 | loss=0.0920 | lr=1.46e-05 | epoch=2.2140
[train] step=1037 | loss=0.1258 | lr=1.46e-05 | epoch=2.2162
[train] step=1038 | loss=0.1155 | lr=1.45e-05 | epoch=2.2183
[train] step=1039 | loss=0.0994 | lr=1.45e-05 | epoch=2.2204
[train] step=1040 | loss=0.0833 | lr=1.44e-05 | epoch=2.2226
[train] step=1041 | loss=0.0880 | lr=1.44e-05 | epoch=2.2247
[train] step=1042 | loss=0.0956 | lr=1.44e-05 | epoch=2.2269
[train] step=1043 | loss=0.0876 | lr=1.43e-05 | epoch=2.2290
[train] step=1044 | loss=0.1188 | lr=1.43e-05 | epoch=2.2311
[train] step=1045 | loss=0.0872 | lr=1.42e-05 | epoch=2.2333
[train] step=1046 | loss=0.1278 | lr=1.42e-05 | epoch=2.2354
[train] step=1047 | loss=0.1181 | lr=1.42e-05 | epoch=2.2376
[train] step=1048 | loss=0.0987 | lr=1.41e-05 | epoch=2.2397
[train] step=1049 | loss=0.1052 | lr=1.41e-05 | epoch=2.2418
[train] step=1050 | loss=0.0881 | lr=1.40e-05 | epoch=2.2440
[train] step=1051 | loss=0.0872 | lr=1.40e-05 | epoch=2.2461
[train] step=1052 | loss=0.1076 | lr=1.40e-05 | epoch=2.2483
[train] step=1053 | loss=0.1026 | lr=1.39e-05 | epoch=2.2504
[train] step=1054 | loss=0.0960 | lr=1.39e-05 | epoch=2.2525
[train] step=1055 | loss=0.1087 | lr=1.38e-05 | epoch=2.2547
[train] step=1056 | loss=0.1113 | lr=1.38e-05 | epoch=2.2568
[train] step=1057 | loss=0.0919 | lr=1.38e-05 | epoch=2.2590
[train] step=1058 | loss=0.0888 | lr=1.37e-05 | epoch=2.2611
[train] step=1059 | loss=0.1090 | lr=1.37e-05 | epoch=2.2632
[train] step=1060 | loss=0.1013 | lr=1.36e-05 | epoch=2.2654
[train] step=1061 | loss=0.0986 | lr=1.36e-05 | epoch=2.2675
[train] step=1062 | loss=0.1021 | lr=1.36e-05 | epoch=2.2697
[train] step=1063 | loss=0.0772 | lr=1.35e-05 | epoch=2.2718
[train] step=1064 | loss=0.0927 | lr=1.35e-05 | epoch=2.2739
[train] step=1065 | loss=0.0939 | lr=1.34e-05 | epoch=2.2761
[train] step=1066 | loss=0.1001 | lr=1.34e-05 | epoch=2.2782
[train] step=1067 | loss=0.0891 | lr=1.34e-05 | epoch=2.2804
[train] step=1068 | loss=0.1163 | lr=1.33e-05 | epoch=2.2825
[train] step=1069 | loss=0.0829 | lr=1.33e-05 | epoch=2.2846
[train] step=1070 | loss=0.1070 | lr=1.33e-05 | epoch=2.2868
[train] step=1071 | loss=0.0989 | lr=1.32e-05 | epoch=2.2889
[train] step=1072 | loss=0.0834 | lr=1.32e-05 | epoch=2.2911
[train] step=1073 | loss=0.0879 | lr=1.31e-05 | epoch=2.2932
[train] step=1074 | loss=0.0902 | lr=1.31e-05 | epoch=2.2953
[train] step=1075 | loss=0.1028 | lr=1.31e-05 | epoch=2.2975
[train] step=1076 | loss=0.1039 | lr=1.30e-05 | epoch=2.2996
[train] step=1077 | loss=0.0945 | lr=1.30e-05 | epoch=2.3018
[train] step=1078 | loss=0.0990 | lr=1.29e-05 | epoch=2.3039
[train] step=1079 | loss=0.1152 | lr=1.29e-05 | epoch=2.3060
[train] step=1080 | loss=0.1066 | lr=1.29e-05 | epoch=2.3082
[train] step=1081 | loss=0.1270 | lr=1.28e-05 | epoch=2.3103
[train] step=1082 | loss=0.1090 | lr=1.28e-05 | epoch=2.3125
[train] step=1083 | loss=0.1028 | lr=1.27e-05 | epoch=2.3146
[train] step=1084 | loss=0.0792 | lr=1.27e-05 | epoch=2.3167
[train] step=1085 | loss=0.0955 | lr=1.27e-05 | epoch=2.3189
[train] step=1086 | loss=0.0857 | lr=1.26e-05 | epoch=2.3210
[train] step=1087 | loss=0.1121 | lr=1.26e-05 | epoch=2.3232
[train] step=1088 | loss=0.1145 | lr=1.25e-05 | epoch=2.3253
[train] step=1089 | loss=0.0893 | lr=1.25e-05 | epoch=2.3274
[train] step=1090 | loss=0.1149 | lr=1.25e-05 | epoch=2.3296
[train] step=1091 | loss=0.1119 | lr=1.24e-05 | epoch=2.3317
[train] step=1092 | loss=0.0975 | lr=1.24e-05 | epoch=2.3339
[train] step=1093 | loss=0.0925 | lr=1.23e-05 | epoch=2.3360
[train] step=1094 | loss=0.0905 | lr=1.23e-05 | epoch=2.3381
[train] step=1095 | loss=0.1020 | lr=1.23e-05 | epoch=2.3403
[train] step=1096 | loss=0.0997 | lr=1.22e-05 | epoch=2.3424
[train] step=1097 | loss=0.1182 | lr=1.22e-05 | epoch=2.3446
[train] step=1098 | loss=0.0922 | lr=1.21e-05 | epoch=2.3467
[train] step=1099 | loss=0.0987 | lr=1.21e-05 | epoch=2.3488
[train] step=1100 | loss=0.0938 | lr=1.21e-05 | epoch=2.3510
[train] step=1101 | loss=0.1097 | lr=1.20e-05 | epoch=2.3531
[train] step=1102 | loss=0.1065 | lr=1.20e-05 | epoch=2.3553
[train] step=1103 | loss=0.0838 | lr=1.19e-05 | epoch=2.3574
[train] step=1104 | loss=0.1083 | lr=1.19e-05 | epoch=2.3596
[train] step=1105 | loss=0.0975 | lr=1.19e-05 | epoch=2.3617
[train] step=1106 | loss=0.1453 | lr=1.18e-05 | epoch=2.3638
[train] step=1107 | loss=0.1030 | lr=1.18e-05 | epoch=2.3660
[train] step=1108 | loss=0.0978 | lr=1.17e-05 | epoch=2.3681
[train] step=1109 | loss=0.1084 | lr=1.17e-05 | epoch=2.3703
[train] step=1110 | loss=0.1027 | lr=1.17e-05 | epoch=2.3724
[train] step=1111 | loss=0.0994 | lr=1.16e-05 | epoch=2.3745
[train] step=1112 | loss=0.0919 | lr=1.16e-05 | epoch=2.3767
[train] step=1113 | loss=0.1150 | lr=1.16e-05 | epoch=2.3788
[train] step=1114 | loss=0.1207 | lr=1.15e-05 | epoch=2.3810
[train] step=1115 | loss=0.0903 | lr=1.15e-05 | epoch=2.3831
[train] step=1116 | loss=0.1215 | lr=1.14e-05 | epoch=2.3852
[train] step=1117 | loss=0.0998 | lr=1.14e-05 | epoch=2.3874
[train] step=1118 | loss=0.0944 | lr=1.14e-05 | epoch=2.3895
[train] step=1119 | loss=0.1026 | lr=1.13e-05 | epoch=2.3917
[train] step=1120 | loss=0.0982 | lr=1.13e-05 | epoch=2.3938
[train] step=1121 | loss=0.0975 | lr=1.12e-05 | epoch=2.3959
[train] step=1122 | loss=0.1134 | lr=1.12e-05 | epoch=2.3981
[train] step=1123 | loss=0.1217 | lr=1.12e-05 | epoch=2.4002
[train] step=1124 | loss=0.0992 | lr=1.11e-05 | epoch=2.4024
[train] step=1125 | loss=0.0938 | lr=1.11e-05 | epoch=2.4045
[train] step=1126 | loss=0.0870 | lr=1.10e-05 | epoch=2.4066
[train] step=1127 | loss=0.0993 | lr=1.10e-05 | epoch=2.4088
[train] step=1128 | loss=0.0979 | lr=1.10e-05 | epoch=2.4109
[train] step=1129 | loss=0.0976 | lr=1.09e-05 | epoch=2.4131
[train] step=1130 | loss=0.0903 | lr=1.09e-05 | epoch=2.4152
[train] step=1131 | loss=0.1103 | lr=1.08e-05 | epoch=2.4173
[train] step=1132 | loss=0.0824 | lr=1.08e-05 | epoch=2.4195
[train] step=1133 | loss=0.0879 | lr=1.08e-05 | epoch=2.4216
[train] step=1134 | loss=0.1040 | lr=1.07e-05 | epoch=2.4238
[train] step=1135 | loss=0.1124 | lr=1.07e-05 | epoch=2.4259
[train] step=1136 | loss=0.1104 | lr=1.06e-05 | epoch=2.4280
[train] step=1137 | loss=0.0834 | lr=1.06e-05 | epoch=2.4302
[train] step=1138 | loss=0.0930 | lr=1.06e-05 | epoch=2.4323
[train] step=1139 | loss=0.0992 | lr=1.05e-05 | epoch=2.4345
[train] step=1140 | loss=0.1040 | lr=1.05e-05 | epoch=2.4366
[train] step=1141 | loss=0.1233 | lr=1.04e-05 | epoch=2.4387
[train] step=1142 | loss=0.0918 | lr=1.04e-05 | epoch=2.4409
[train] step=1143 | loss=0.1000 | lr=1.04e-05 | epoch=2.4430
[train] step=1144 | loss=0.0941 | lr=1.03e-05 | epoch=2.4452
[train] step=1145 | loss=0.0845 | lr=1.03e-05 | epoch=2.4473
[train] step=1146 | loss=0.1012 | lr=1.02e-05 | epoch=2.4494
[train] step=1147 | loss=0.0964 | lr=1.02e-05 | epoch=2.4516
[train] step=1148 | loss=0.1412 | lr=1.02e-05 | epoch=2.4537
[train] step=1149 | loss=0.1125 | lr=1.01e-05 | epoch=2.4559
[train] step=1150 | loss=0.0971 | lr=1.01e-05 | epoch=2.4580
[train] step=1151 | loss=0.0991 | lr=1.00e-05 | epoch=2.4601
[train] step=1152 | loss=0.0990 | lr=1.00e-05 | epoch=2.4623
[train] step=1153 | loss=0.1294 | lr=9.97e-06 | epoch=2.4644
[train] step=1154 | loss=0.1037 | lr=9.93e-06 | epoch=2.4666
[train] step=1155 | loss=0.0931 | lr=9.89e-06 | epoch=2.4687
[train] step=1156 | loss=0.0958 | lr=9.85e-06 | epoch=2.4708
[train] step=1157 | loss=0.1018 | lr=9.81e-06 | epoch=2.4730
[train] step=1158 | loss=0.0921 | lr=9.77e-06 | epoch=2.4751
[train] step=1159 | loss=0.1079 | lr=9.73e-06 | epoch=2.4773
[train] step=1160 | loss=0.0932 | lr=9.69e-06 | epoch=2.4794
[train] step=1161 | loss=0.0945 | lr=9.65e-06 | epoch=2.4815
[train] step=1162 | loss=0.0967 | lr=9.61e-06 | epoch=2.4837
[train] step=1163 | loss=0.0964 | lr=9.57e-06 | epoch=2.4858
[train] step=1164 | loss=0.0845 | lr=9.53e-06 | epoch=2.4880
[train] step=1165 | loss=0.0805 | lr=9.49e-06 | epoch=2.4901

Saving model checkpoint to output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1165
2026-04-06 03:39:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:39:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:39:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:39:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1165\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1165\tokenizer_config.json

[train] step=1166 | loss=0.0938 | lr=9.45e-06 | epoch=2.4922
[train] step=1167 | loss=0.0926 | lr=9.41e-06 | epoch=2.4944
[train] step=1168 | loss=0.0961 | lr=9.38e-06 | epoch=2.4965
[train] step=1169 | loss=0.1283 | lr=9.34e-06 | epoch=2.4987
[train] step=1170 | loss=0.0857 | lr=9.30e-06 | epoch=2.5008
[train] step=1171 | loss=0.0890 | lr=9.26e-06 | epoch=2.5029
[train] step=1172 | loss=0.1064 | lr=9.22e-06 | epoch=2.5051
[train] step=1173 | loss=0.0752 | lr=9.18e-06 | epoch=2.5072
[train] step=1174 | loss=0.0847 | lr=9.14e-06 | epoch=2.5094
[train] step=1175 | loss=0.0903 | lr=9.10e-06 | epoch=2.5115
[train] step=1176 | loss=0.1017 | lr=9.06e-06 | epoch=2.5136
[train] step=1177 | loss=0.1222 | lr=9.02e-06 | epoch=2.5158
[train] step=1178 | loss=0.0972 | lr=8.98e-06 | epoch=2.5179
[train] step=1179 | loss=0.0980 | lr=8.94e-06 | epoch=2.5201
[train] step=1180 | loss=0.0928 | lr=8.90e-06 | epoch=2.5222
[train] step=1181 | loss=0.1209 | lr=8.86e-06 | epoch=2.5243
[train] step=1182 | loss=0.0917 | lr=8.82e-06 | epoch=2.5265
[train] step=1183 | loss=0.1144 | lr=8.78e-06 | epoch=2.5286
[train] step=1184 | loss=0.1038 | lr=8.74e-06 | epoch=2.5308
[train] step=1185 | loss=0.1019 | lr=8.70e-06 | epoch=2.5329
[train] step=1186 | loss=0.0963 | lr=8.66e-06 | epoch=2.5350
[train] step=1187 | loss=0.0965 | lr=8.62e-06 | epoch=2.5372
[train] step=1188 | loss=0.0903 | lr=8.58e-06 | epoch=2.5393
[train] step=1189 | loss=0.1020 | lr=8.54e-06 | epoch=2.5415
[train] step=1190 | loss=0.1049 | lr=8.50e-06 | epoch=2.5436
[train] step=1191 | loss=0.1299 | lr=8.47e-06 | epoch=2.5457
[train] step=1192 | loss=0.0816 | lr=8.43e-06 | epoch=2.5479
[train] step=1193 | loss=0.0842 | lr=8.39e-06 | epoch=2.5500
[train] step=1194 | loss=0.0999 | lr=8.35e-06 | epoch=2.5522
[train] step=1195 | loss=0.1214 | lr=8.31e-06 | epoch=2.5543
[train] step=1196 | loss=0.0941 | lr=8.27e-06 | epoch=2.5564
[train] step=1197 | loss=0.1078 | lr=8.23e-06 | epoch=2.5586
[train] step=1198 | loss=0.1086 | lr=8.19e-06 | epoch=2.5607
[train] step=1199 | loss=0.0914 | lr=8.15e-06 | epoch=2.5629
[train] step=1200 | loss=0.1061 | lr=8.11e-06 | epoch=2.5650
[train] step=1201 | loss=0.0968 | lr=8.07e-06 | epoch=2.5671
[train] step=1202 | loss=0.1074 | lr=8.03e-06 | epoch=2.5693
[train] step=1203 | loss=0.1044 | lr=7.99e-06 | epoch=2.5714
[train] step=1204 | loss=0.1153 | lr=7.95e-06 | epoch=2.5736
[train] step=1205 | loss=0.0956 | lr=7.91e-06 | epoch=2.5757
[train] step=1206 | loss=0.0907 | lr=7.87e-06 | epoch=2.5778
[train] step=1207 | loss=0.1033 | lr=7.83e-06 | epoch=2.5800
[train] step=1208 | loss=0.0854 | lr=7.79e-06 | epoch=2.5821
[train] step=1209 | loss=0.1020 | lr=7.75e-06 | epoch=2.5843
[train] step=1210 | loss=0.1053 | lr=7.71e-06 | epoch=2.5864
[train] step=1211 | loss=0.1225 | lr=7.67e-06 | epoch=2.5886
[train] step=1212 | loss=0.1014 | lr=7.63e-06 | epoch=2.5907
[train] step=1213 | loss=0.0957 | lr=7.59e-06 | epoch=2.5928
[train] step=1214 | loss=0.0830 | lr=7.56e-06 | epoch=2.5950
[train] step=1215 | loss=0.1058 | lr=7.52e-06 | epoch=2.5971
[train] step=1216 | loss=0.1215 | lr=7.48e-06 | epoch=2.5993
[train] step=1217 | loss=0.1050 | lr=7.44e-06 | epoch=2.6014
[train] step=1218 | loss=0.0981 | lr=7.40e-06 | epoch=2.6035
[train] step=1219 | loss=0.1025 | lr=7.36e-06 | epoch=2.6057
[train] step=1220 | loss=0.0985 | lr=7.32e-06 | epoch=2.6078
[train] step=1221 | loss=0.1041 | lr=7.28e-06 | epoch=2.6100
[train] step=1222 | loss=0.1226 | lr=7.24e-06 | epoch=2.6121
[train] step=1223 | loss=0.1100 | lr=7.20e-06 | epoch=2.6142
[train] step=1224 | loss=0.0855 | lr=7.16e-06 | epoch=2.6164
[train] step=1225 | loss=0.0972 | lr=7.12e-06 | epoch=2.6185
[train] step=1226 | loss=0.0912 | lr=7.08e-06 | epoch=2.6207
[train] step=1227 | loss=0.0942 | lr=7.04e-06 | epoch=2.6228
[train] step=1228 | loss=0.1070 | lr=7.00e-06 | epoch=2.6249
[train] step=1229 | loss=0.0943 | lr=6.96e-06 | epoch=2.6271
[train] step=1230 | loss=0.1039 | lr=6.92e-06 | epoch=2.6292
[train] step=1231 | loss=0.0717 | lr=6.88e-06 | epoch=2.6314
[train] step=1232 | loss=0.1055 | lr=6.84e-06 | epoch=2.6335
[train] step=1233 | loss=0.1180 | lr=6.80e-06 | epoch=2.6356
[train] step=1234 | loss=0.1077 | lr=6.76e-06 | epoch=2.6378
[train] step=1235 | loss=0.1121 | lr=6.72e-06 | epoch=2.6399
[train] step=1236 | loss=0.0810 | lr=6.69e-06 | epoch=2.6421
[train] step=1237 | loss=0.0947 | lr=6.65e-06 | epoch=2.6442
[train] step=1238 | loss=0.0921 | lr=6.61e-06 | epoch=2.6463
[train] step=1239 | loss=0.1160 | lr=6.57e-06 | epoch=2.6485
[train] step=1240 | loss=0.1067 | lr=6.53e-06 | epoch=2.6506
[train] step=1241 | loss=0.0880 | lr=6.49e-06 | epoch=2.6528
[train] step=1242 | loss=0.1210 | lr=6.45e-06 | epoch=2.6549
[train] step=1243 | loss=0.0924 | lr=6.41e-06 | epoch=2.6570
[train] step=1244 | loss=0.1175 | lr=6.37e-06 | epoch=2.6592
[train] step=1245 | loss=0.0877 | lr=6.33e-06 | epoch=2.6613
[train] step=1246 | loss=0.0912 | lr=6.29e-06 | epoch=2.6635
[train] step=1247 | loss=0.1118 | lr=6.25e-06 | epoch=2.6656
[train] step=1248 | loss=0.0975 | lr=6.21e-06 | epoch=2.6677
[train] step=1249 | loss=0.0842 | lr=6.17e-06 | epoch=2.6699
[train] step=1250 | loss=0.0778 | lr=6.13e-06 | epoch=2.6720
[train] step=1251 | loss=0.1255 | lr=6.09e-06 | epoch=2.6742
[train] step=1252 | loss=0.0952 | lr=6.05e-06 | epoch=2.6763
[train] step=1253 | loss=0.1047 | lr=6.01e-06 | epoch=2.6784
[train] step=1254 | loss=0.0979 | lr=5.97e-06 | epoch=2.6806
[train] step=1255 | loss=0.0949 | lr=5.93e-06 | epoch=2.6827
[train] step=1256 | loss=0.0899 | lr=5.89e-06 | epoch=2.6849
[train] step=1257 | loss=0.0764 | lr=5.85e-06 | epoch=2.6870
[train] step=1258 | loss=0.1059 | lr=5.81e-06 | epoch=2.6891
[train] step=1259 | loss=0.1190 | lr=5.78e-06 | epoch=2.6913
[train] step=1260 | loss=0.0944 | lr=5.74e-06 | epoch=2.6934
[train] step=1261 | loss=0.0981 | lr=5.70e-06 | epoch=2.6956
[train] step=1262 | loss=0.1319 | lr=5.66e-06 | epoch=2.6977
[train] step=1263 | loss=0.0891 | lr=5.62e-06 | epoch=2.6998
[train] step=1264 | loss=0.0963 | lr=5.58e-06 | epoch=2.7020
[train] step=1265 | loss=0.1044 | lr=5.54e-06 | epoch=2.7041
[train] step=1266 | loss=0.1257 | lr=5.50e-06 | epoch=2.7063
[train] step=1267 | loss=0.1014 | lr=5.46e-06 | epoch=2.7084
[train] step=1268 | loss=0.1274 | lr=5.42e-06 | epoch=2.7105
[train] step=1269 | loss=0.1266 | lr=5.38e-06 | epoch=2.7127
[train] step=1270 | loss=0.0945 | lr=5.34e-06 | epoch=2.7148
[train] step=1271 | loss=0.0865 | lr=5.30e-06 | epoch=2.7170
[train] step=1272 | loss=0.0895 | lr=5.26e-06 | epoch=2.7191
[train] step=1273 | loss=0.1025 | lr=5.22e-06 | epoch=2.7212
[train] step=1274 | loss=0.0937 | lr=5.18e-06 | epoch=2.7234
[train] step=1275 | loss=0.1043 | lr=5.14e-06 | epoch=2.7255
[train] step=1276 | loss=0.0742 | lr=5.10e-06 | epoch=2.7277
[train] step=1277 | loss=0.1014 | lr=5.06e-06 | epoch=2.7298
[train] step=1278 | loss=0.0976 | lr=5.02e-06 | epoch=2.7319
[train] step=1279 | loss=0.1234 | lr=4.98e-06 | epoch=2.7341
[train] step=1280 | loss=0.1045 | lr=4.94e-06 | epoch=2.7362
[train] step=1281 | loss=0.0947 | lr=4.91e-06 | epoch=2.7384
[train] step=1282 | loss=0.1015 | lr=4.87e-06 | epoch=2.7405
[train] step=1283 | loss=0.0932 | lr=4.83e-06 | epoch=2.7426
[train] step=1284 | loss=0.1247 | lr=4.79e-06 | epoch=2.7448
[train] step=1285 | loss=0.1019 | lr=4.75e-06 | epoch=2.7469
[train] step=1286 | loss=0.0834 | lr=4.71e-06 | epoch=2.7491
[train] step=1287 | loss=0.0996 | lr=4.67e-06 | epoch=2.7512
[train] step=1288 | loss=0.1072 | lr=4.63e-06 | epoch=2.7533
[train] step=1289 | loss=0.0957 | lr=4.59e-06 | epoch=2.7555
[train] step=1290 | loss=0.1232 | lr=4.55e-06 | epoch=2.7576
[train] step=1291 | loss=0.0866 | lr=4.51e-06 | epoch=2.7598
[train] step=1292 | loss=0.1024 | lr=4.47e-06 | epoch=2.7619
[train] step=1293 | loss=0.0887 | lr=4.43e-06 | epoch=2.7640
[train] step=1294 | loss=0.1159 | lr=4.39e-06 | epoch=2.7662
[train] step=1295 | loss=0.1031 | lr=4.35e-06 | epoch=2.7683
[train] step=1296 | loss=0.1264 | lr=4.31e-06 | epoch=2.7705
[train] step=1297 | loss=0.0952 | lr=4.27e-06 | epoch=2.7726
[train] step=1298 | loss=0.0831 | lr=4.23e-06 | epoch=2.7747
[train] step=1299 | loss=0.1098 | lr=4.19e-06 | epoch=2.7769
[train] step=1300 | loss=0.0953 | lr=4.15e-06 | epoch=2.7790
[train] step=1301 | loss=0.1034 | lr=4.11e-06 | epoch=2.7812
[train] step=1302 | loss=0.1007 | lr=4.07e-06 | epoch=2.7833
[train] step=1303 | loss=0.1052 | lr=4.03e-06 | epoch=2.7854
[train] step=1304 | loss=0.1002 | lr=4.00e-06 | epoch=2.7876
[train] step=1305 | loss=0.1174 | lr=3.96e-06 | epoch=2.7897
[train] step=1306 | loss=0.1129 | lr=3.92e-06 | epoch=2.7919
[train] step=1307 | loss=0.0819 | lr=3.88e-06 | epoch=2.7940
[train] step=1308 | loss=0.0907 | lr=3.84e-06 | epoch=2.7961
[train] step=1309 | loss=0.1088 | lr=3.80e-06 | epoch=2.7983
[train] step=1310 | loss=0.0915 | lr=3.76e-06 | epoch=2.8004
[train] step=1311 | loss=0.1163 | lr=3.72e-06 | epoch=2.8026
[train] step=1312 | loss=0.0965 | lr=3.68e-06 | epoch=2.8047
[train] step=1313 | loss=0.1038 | lr=3.64e-06 | epoch=2.8068
[train] step=1314 | loss=0.0958 | lr=3.60e-06 | epoch=2.8090
[train] step=1315 | loss=0.1075 | lr=3.56e-06 | epoch=2.8111
[train] step=1316 | loss=0.0931 | lr=3.52e-06 | epoch=2.8133
[train] step=1317 | loss=0.1085 | lr=3.48e-06 | epoch=2.8154
[train] step=1318 | loss=0.1015 | lr=3.44e-06 | epoch=2.8175
[train] step=1319 | loss=0.0763 | lr=3.40e-06 | epoch=2.8197
[train] step=1320 | loss=0.0938 | lr=3.36e-06 | epoch=2.8218
[train] step=1321 | loss=0.0915 | lr=3.32e-06 | epoch=2.8240
[train] step=1322 | loss=0.0796 | lr=3.28e-06 | epoch=2.8261
[train] step=1323 | loss=0.0827 | lr=3.24e-06 | epoch=2.8283
[train] step=1324 | loss=0.1065 | lr=3.20e-06 | epoch=2.8304
[train] step=1325 | loss=0.0844 | lr=3.16e-06 | epoch=2.8325
[train] step=1326 | loss=0.0964 | lr=3.13e-06 | epoch=2.8347
[train] step=1327 | loss=0.1035 | lr=3.09e-06 | epoch=2.8368
[train] step=1328 | loss=0.1077 | lr=3.05e-06 | epoch=2.8390
[train] step=1329 | loss=0.1060 | lr=3.01e-06 | epoch=2.8411
[train] step=1330 | loss=0.1111 | lr=2.97e-06 | epoch=2.8432
[train] step=1331 | loss=0.0829 | lr=2.93e-06 | epoch=2.8454
[train] step=1332 | loss=0.1342 | lr=2.89e-06 | epoch=2.8475
[train] step=1333 | loss=0.0982 | lr=2.85e-06 | epoch=2.8497
[train] step=1334 | loss=0.0966 | lr=2.81e-06 | epoch=2.8518
[train] step=1335 | loss=0.1200 | lr=2.77e-06 | epoch=2.8539
[train] step=1336 | loss=0.0866 | lr=2.73e-06 | epoch=2.8561
[train] step=1337 | loss=0.1009 | lr=2.69e-06 | epoch=2.8582
[train] step=1338 | loss=0.1049 | lr=2.65e-06 | epoch=2.8604
[train] step=1339 | loss=0.1334 | lr=2.61e-06 | epoch=2.8625
[train] step=1340 | loss=0.1164 | lr=2.57e-06 | epoch=2.8646
[train] step=1341 | loss=0.0860 | lr=2.53e-06 | epoch=2.8668
[train] step=1342 | loss=0.1004 | lr=2.49e-06 | epoch=2.8689
[train] step=1343 | loss=0.1103 | lr=2.45e-06 | epoch=2.8711
[train] step=1344 | loss=0.0879 | lr=2.41e-06 | epoch=2.8732
[train] step=1345 | loss=0.0995 | lr=2.37e-06 | epoch=2.8753
[train] step=1346 | loss=0.1162 | lr=2.33e-06 | epoch=2.8775
[train] step=1347 | loss=0.1163 | lr=2.29e-06 | epoch=2.8796
[train] step=1348 | loss=0.1221 | lr=2.25e-06 | epoch=2.8818
[train] step=1349 | loss=0.0874 | lr=2.22e-06 | epoch=2.8839
[train] step=1350 | loss=0.1105 | lr=2.18e-06 | epoch=2.8860
[train] step=1351 | loss=0.1127 | lr=2.14e-06 | epoch=2.8882
[train] step=1352 | loss=0.0998 | lr=2.10e-06 | epoch=2.8903
[train] step=1353 | loss=0.0997 | lr=2.06e-06 | epoch=2.8925
[train] step=1354 | loss=0.0892 | lr=2.02e-06 | epoch=2.8946
[train] step=1355 | loss=0.1142 | lr=1.98e-06 | epoch=2.8967
[train] step=1356 | loss=0.0899 | lr=1.94e-06 | epoch=2.8989
[train] step=1357 | loss=0.1155 | lr=1.90e-06 | epoch=2.9010
[train] step=1358 | loss=0.0884 | lr=1.86e-06 | epoch=2.9032
[train] step=1359 | loss=0.0988 | lr=1.82e-06 | epoch=2.9053
[train] step=1360 | loss=0.0951 | lr=1.78e-06 | epoch=2.9074
[train] step=1361 | loss=0.0884 | lr=1.74e-06 | epoch=2.9096
[train] step=1362 | loss=0.1020 | lr=1.70e-06 | epoch=2.9117
[train] step=1363 | loss=0.0890 | lr=1.66e-06 | epoch=2.9139
[train] step=1364 | loss=0.0999 | lr=1.62e-06 | epoch=2.9160
[train] step=1365 | loss=0.1182 | lr=1.58e-06 | epoch=2.9181
[train] step=1366 | loss=0.1115 | lr=1.54e-06 | epoch=2.9203
[train] step=1367 | loss=0.1161 | lr=1.50e-06 | epoch=2.9224
[train] step=1368 | loss=0.0659 | lr=1.46e-06 | epoch=2.9246
[train] step=1369 | loss=0.0877 | lr=1.42e-06 | epoch=2.9267
[train] step=1370 | loss=0.0909 | lr=1.38e-06 | epoch=2.9288
[train] step=1371 | loss=0.0734 | lr=1.34e-06 | epoch=2.9310
[train] step=1372 | loss=0.1051 | lr=1.31e-06 | epoch=2.9331
[train] step=1373 | loss=0.1068 | lr=1.27e-06 | epoch=2.9353
[train] step=1374 | loss=0.0880 | lr=1.23e-06 | epoch=2.9374
[train] step=1375 | loss=0.1259 | lr=1.19e-06 | epoch=2.9395
[train] step=1376 | loss=0.1038 | lr=1.15e-06 | epoch=2.9417
[train] step=1377 | loss=0.0857 | lr=1.11e-06 | epoch=2.9438
[train] step=1378 | loss=0.1135 | lr=1.07e-06 | epoch=2.9460
[train] step=1379 | loss=0.0886 | lr=1.03e-06 | epoch=2.9481
[train] step=1380 | loss=0.1119 | lr=9.89e-07 | epoch=2.9502
[train] step=1381 | loss=0.0996 | lr=9.49e-07 | epoch=2.9524
[train] step=1382 | loss=0.0826 | lr=9.10e-07 | epoch=2.9545
[train] step=1383 | loss=0.0872 | lr=8.70e-07 | epoch=2.9567
[train] step=1384 | loss=0.0901 | lr=8.31e-07 | epoch=2.9588
[train] step=1385 | loss=0.1056 | lr=7.91e-07 | epoch=2.9609
[train] step=1386 | loss=0.0946 | lr=7.52e-07 | epoch=2.9631
[train] step=1387 | loss=0.1074 | lr=7.12e-07 | epoch=2.9652
[train] step=1388 | loss=0.1075 | lr=6.72e-07 | epoch=2.9674
[train] step=1389 | loss=0.1050 | lr=6.33e-07 | epoch=2.9695
[train] step=1390 | loss=0.1045 | lr=5.93e-07 | epoch=2.9716
[train] step=1391 | loss=0.1009 | lr=5.54e-07 | epoch=2.9738
[train] step=1392 | loss=0.0926 | lr=5.14e-07 | epoch=2.9759
[train] step=1393 | loss=0.0880 | lr=4.75e-07 | epoch=2.9781
[train] step=1394 | loss=0.0916 | lr=4.35e-07 | epoch=2.9802
[train] step=1395 | loss=0.0870 | lr=3.96e-07 | epoch=2.9823
[train] step=1396 | loss=0.0792 | lr=3.56e-07 | epoch=2.9845
[train] step=1397 | loss=0.1036 | lr=3.16e-07 | epoch=2.9866
[train] step=1398 | loss=0.1024 | lr=2.77e-07 | epoch=2.9888

Saving model checkpoint to output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1398
2026-04-06 03:48:27 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:27 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:48:28 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:28 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1398\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1398\tokenizer_config.json

[train] step=1399 | loss=0.1046 | lr=2.37e-07 | epoch=2.9909
[train] step=1400 | loss=0.1149 | lr=1.98e-07 | epoch=2.9930
[train] step=1401 | loss=0.0854 | lr=1.58e-07 | epoch=2.9952
[train] step=1402 | loss=0.0977 | lr=1.19e-07 | epoch=2.9973
[train] step=1403 | loss=0.1298 | lr=7.91e-08 | epoch=2.9995
[train] step=1404 | loss=0.0852 | lr=3.96e-08 | epoch=3.0000

Saving model checkpoint to output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1404
2026-04-06 03:48:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1404\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\checkpoint-1404\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=1404 | epoch=3.0000
[train] finished | global_step=1404

Saving model checkpoint to output\fine_tune\run_002_lr5e-5_r32_a64_ep3
2026-04-06 03:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\tokenizer_config.json
chat template saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_002_lr5e-5_r32_a64_ep3\tokenizer_config.json
2026-04-06 03:48:43 | INFO     | root | Done run 3/5: C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_002_lr5e-5_r32_a64_ep3

=== Run 4/5  run_003_lr7e-5_r16_a32_ep3  merged={'learning_rate': 7e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-06 03:48:43 | INFO     | root | Logging to C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_003_lr7e-5_r16_a32_ep3\training_run.log
2026-04-06 03:48:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 03:48:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-06 03:48:43 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-06 03:48:44 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-06 03:48:44 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"
2026-04-06 03:48:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 03:48:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9656.00it/s]
2026-04-06 03:48:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": false,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

2026-04-06 03:48:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2-1.5B.
2026-04-06 03:48:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:48:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-06 03:48:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 03:48:46 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 03:48:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-06 03:48:47 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-06 03:48:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-06 03:48:49 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 4,358,144

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.6833 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.7304 | lr=5.00e-07 | epoch=0.0043
[train] step=3 | loss=1.7382 | lr=1.00e-06 | epoch=0.0064
[train] step=4 | loss=1.7180 | lr=1.50e-06 | epoch=0.0086
[train] step=5 | loss=1.6860 | lr=2.00e-06 | epoch=0.0107
[train] step=6 | loss=1.7070 | lr=2.50e-06 | epoch=0.0128
[train] step=7 | loss=1.6360 | lr=3.00e-06 | epoch=0.0150
[train] step=8 | loss=1.6084 | lr=3.50e-06 | epoch=0.0171
[train] step=9 | loss=1.6984 | lr=4.00e-06 | epoch=0.0193
[train] step=10 | loss=1.7016 | lr=4.50e-06 | epoch=0.0214
[train] step=11 | loss=1.7465 | lr=5.00e-06 | epoch=0.0235
[train] step=12 | loss=1.8289 | lr=5.50e-06 | epoch=0.0257
[train] step=13 | loss=1.6950 | lr=6.00e-06 | epoch=0.0278
[train] step=14 | loss=1.7381 | lr=6.50e-06 | epoch=0.0300
[train] step=15 | loss=1.7852 | lr=7.00e-06 | epoch=0.0321
[train] step=16 | loss=1.7203 | lr=7.50e-06 | epoch=0.0342
[train] step=17 | loss=1.6942 | lr=8.00e-06 | epoch=0.0364
[train] step=18 | loss=1.7061 | lr=8.50e-06 | epoch=0.0385
[train] step=19 | loss=1.6811 | lr=9.00e-06 | epoch=0.0407
[train] step=20 | loss=1.6850 | lr=9.50e-06 | epoch=0.0428
[train] step=21 | loss=1.6166 | lr=1.00e-05 | epoch=0.0449
[train] step=22 | loss=1.6587 | lr=1.05e-05 | epoch=0.0471
[train] step=23 | loss=1.6324 | lr=1.10e-05 | epoch=0.0492
[train] step=24 | loss=1.6703 | lr=1.15e-05 | epoch=0.0514
[train] step=25 | loss=1.6000 | lr=1.20e-05 | epoch=0.0535
[train] step=26 | loss=1.7162 | lr=1.25e-05 | epoch=0.0556
[train] step=27 | loss=1.5635 | lr=1.30e-05 | epoch=0.0578
[train] step=28 | loss=1.5932 | lr=1.35e-05 | epoch=0.0599
[train] step=29 | loss=1.5732 | lr=1.40e-05 | epoch=0.0621
[train] step=30 | loss=1.6178 | lr=1.45e-05 | epoch=0.0642
[train] step=31 | loss=1.5170 | lr=1.50e-05 | epoch=0.0663
[train] step=32 | loss=1.5386 | lr=1.55e-05 | epoch=0.0685
[train] step=33 | loss=1.5442 | lr=1.60e-05 | epoch=0.0706
[train] step=34 | loss=1.5511 | lr=1.65e-05 | epoch=0.0728
[train] step=35 | loss=1.6525 | lr=1.70e-05 | epoch=0.0749
[train] step=36 | loss=1.5362 | lr=1.75e-05 | epoch=0.0770
[train] step=37 | loss=1.5554 | lr=1.80e-05 | epoch=0.0792
[train] step=38 | loss=1.5187 | lr=1.85e-05 | epoch=0.0813
[train] step=39 | loss=1.4772 | lr=1.90e-05 | epoch=0.0835
[train] step=40 | loss=1.5764 | lr=1.95e-05 | epoch=0.0856
[train] step=41 | loss=1.4830 | lr=2.00e-05 | epoch=0.0877
[train] step=42 | loss=1.4838 | lr=2.05e-05 | epoch=0.0899
[train] step=43 | loss=1.4516 | lr=2.10e-05 | epoch=0.0920
[train] step=44 | loss=1.3939 | lr=2.15e-05 | epoch=0.0942
[train] step=45 | loss=1.4348 | lr=2.20e-05 | epoch=0.0963
[train] step=46 | loss=1.3859 | lr=2.25e-05 | epoch=0.0984
[train] step=47 | loss=1.3820 | lr=2.30e-05 | epoch=0.1006
[train] step=48 | loss=1.2740 | lr=2.35e-05 | epoch=0.1027
[train] step=49 | loss=1.3319 | lr=2.40e-05 | epoch=0.1049
[train] step=50 | loss=1.4041 | lr=2.45e-05 | epoch=0.1070
[train] step=51 | loss=1.3463 | lr=2.50e-05 | epoch=0.1091
[train] step=52 | loss=1.3087 | lr=2.55e-05 | epoch=0.1113
[train] step=53 | loss=1.3704 | lr=2.60e-05 | epoch=0.1134
[train] step=54 | loss=1.2590 | lr=2.65e-05 | epoch=0.1156
[train] step=55 | loss=1.1492 | lr=2.70e-05 | epoch=0.1177
[train] step=56 | loss=1.2820 | lr=2.75e-05 | epoch=0.1199
[train] step=57 | loss=1.0959 | lr=2.80e-05 | epoch=0.1220
[train] step=58 | loss=1.1917 | lr=2.85e-05 | epoch=0.1241
[train] step=59 | loss=1.1101 | lr=2.90e-05 | epoch=0.1263
[train] step=60 | loss=1.0926 | lr=2.95e-05 | epoch=0.1284
[train] step=61 | loss=1.0639 | lr=3.00e-05 | epoch=0.1306
[train] step=62 | loss=1.0403 | lr=3.05e-05 | epoch=0.1327
[train] step=63 | loss=0.9802 | lr=3.10e-05 | epoch=0.1348
[train] step=64 | loss=1.0651 | lr=3.15e-05 | epoch=0.1370
[train] step=65 | loss=0.9566 | lr=3.20e-05 | epoch=0.1391
[train] step=66 | loss=0.9364 | lr=3.25e-05 | epoch=0.1413
[train] step=67 | loss=0.8760 | lr=3.30e-05 | epoch=0.1434
[train] step=68 | loss=0.8890 | lr=3.35e-05 | epoch=0.1455
[train] step=69 | loss=0.8709 | lr=3.40e-05 | epoch=0.1477
[train] step=70 | loss=0.7965 | lr=3.45e-05 | epoch=0.1498
[train] step=71 | loss=0.7269 | lr=3.50e-05 | epoch=0.1520
[train] step=72 | loss=0.6898 | lr=3.55e-05 | epoch=0.1541
[train] step=73 | loss=0.6582 | lr=3.60e-05 | epoch=0.1562
[train] step=74 | loss=0.6161 | lr=3.65e-05 | epoch=0.1584
[train] step=75 | loss=0.5563 | lr=3.70e-05 | epoch=0.1605
[train] step=76 | loss=0.4979 | lr=3.75e-05 | epoch=0.1627
[train] step=77 | loss=0.4309 | lr=3.80e-05 | epoch=0.1648
[train] step=78 | loss=0.4286 | lr=3.85e-05 | epoch=0.1669
[train] step=79 | loss=0.3906 | lr=3.90e-05 | epoch=0.1691
[train] step=80 | loss=0.3643 | lr=3.95e-05 | epoch=0.1712
[train] step=81 | loss=0.3379 | lr=4.00e-05 | epoch=0.1734
[train] step=82 | loss=0.3010 | lr=4.05e-05 | epoch=0.1755
[train] step=83 | loss=0.2768 | lr=4.10e-05 | epoch=0.1776
[train] step=84 | loss=0.2543 | lr=4.15e-05 | epoch=0.1798
[train] step=85 | loss=0.2708 | lr=4.20e-05 | epoch=0.1819
[train] step=86 | loss=0.2583 | lr=4.25e-05 | epoch=0.1841
[train] step=87 | loss=0.2101 | lr=4.30e-05 | epoch=0.1862
[train] step=88 | loss=0.2337 | lr=4.35e-05 | epoch=0.1883
[train] step=89 | loss=0.2020 | lr=4.40e-05 | epoch=0.1905
[train] step=90 | loss=0.1986 | lr=4.45e-05 | epoch=0.1926
[train] step=91 | loss=0.1868 | lr=4.50e-05 | epoch=0.1948
[train] step=92 | loss=0.2062 | lr=4.55e-05 | epoch=0.1969
[train] step=93 | loss=0.1914 | lr=4.60e-05 | epoch=0.1990
[train] step=94 | loss=0.1757 | lr=4.65e-05 | epoch=0.2012
[train] step=95 | loss=0.1744 | lr=4.70e-05 | epoch=0.2033
[train] step=96 | loss=0.1654 | lr=4.75e-05 | epoch=0.2055
[train] step=97 | loss=0.1730 | lr=4.80e-05 | epoch=0.2076
[train] step=98 | loss=0.1628 | lr=4.85e-05 | epoch=0.2097
[train] step=99 | loss=0.1390 | lr=4.90e-05 | epoch=0.2119
[train] step=100 | loss=0.1513 | lr=4.95e-05 | epoch=0.2140
[train] step=101 | loss=0.1350 | lr=5.00e-05 | epoch=0.2162
[train] step=102 | loss=0.1760 | lr=5.05e-05 | epoch=0.2183
[train] step=103 | loss=0.1353 | lr=5.10e-05 | epoch=0.2204
[train] step=104 | loss=0.1488 | lr=5.15e-05 | epoch=0.2226
[train] step=105 | loss=0.1531 | lr=5.20e-05 | epoch=0.2247
[train] step=106 | loss=0.1423 | lr=5.25e-05 | epoch=0.2269
[train] step=107 | loss=0.1490 | lr=5.30e-05 | epoch=0.2290
[train] step=108 | loss=0.1200 | lr=5.35e-05 | epoch=0.2311
[train] step=109 | loss=0.1162 | lr=5.40e-05 | epoch=0.2333
[train] step=110 | loss=0.1547 | lr=5.45e-05 | epoch=0.2354
[train] step=111 | loss=0.1234 | lr=5.50e-05 | epoch=0.2376
[train] step=112 | loss=0.1162 | lr=5.55e-05 | epoch=0.2397
[train] step=113 | loss=0.1169 | lr=5.60e-05 | epoch=0.2418
[train] step=114 | loss=0.1457 | lr=5.65e-05 | epoch=0.2440
[train] step=115 | loss=0.1284 | lr=5.70e-05 | epoch=0.2461
[train] step=116 | loss=0.1403 | lr=5.75e-05 | epoch=0.2483
[train] step=117 | loss=0.1275 | lr=5.80e-05 | epoch=0.2504
[train] step=118 | loss=0.1153 | lr=5.85e-05 | epoch=0.2525
[train] step=119 | loss=0.1150 | lr=5.90e-05 | epoch=0.2547
[train] step=120 | loss=0.1126 | lr=5.95e-05 | epoch=0.2568
[train] step=121 | loss=0.1199 | lr=6.00e-05 | epoch=0.2590
[train] step=122 | loss=0.1376 | lr=6.05e-05 | epoch=0.2611
[train] step=123 | loss=0.1439 | lr=6.10e-05 | epoch=0.2632
[train] step=124 | loss=0.1129 | lr=6.15e-05 | epoch=0.2654
[train] step=125 | loss=0.1324 | lr=6.20e-05 | epoch=0.2675
[train] step=126 | loss=0.1201 | lr=6.25e-05 | epoch=0.2697
[train] step=127 | loss=0.1284 | lr=6.30e-05 | epoch=0.2718
[train] step=128 | loss=0.1089 | lr=6.35e-05 | epoch=0.2739
[train] step=129 | loss=0.1254 | lr=6.40e-05 | epoch=0.2761
[train] step=130 | loss=0.1237 | lr=6.45e-05 | epoch=0.2782
[train] step=131 | loss=0.1464 | lr=6.50e-05 | epoch=0.2804
[train] step=132 | loss=0.1260 | lr=6.55e-05 | epoch=0.2825
[train] step=133 | loss=0.1267 | lr=6.60e-05 | epoch=0.2846
[train] step=134 | loss=0.1165 | lr=6.65e-05 | epoch=0.2868
[train] step=135 | loss=0.1310 | lr=6.70e-05 | epoch=0.2889
[train] step=136 | loss=0.1184 | lr=6.75e-05 | epoch=0.2911
[train] step=137 | loss=0.1422 | lr=6.80e-05 | epoch=0.2932
[train] step=138 | loss=0.1048 | lr=6.85e-05 | epoch=0.2953
[train] step=139 | loss=0.1076 | lr=6.90e-05 | epoch=0.2975
[train] step=140 | loss=0.1201 | lr=6.95e-05 | epoch=0.2996
[train] step=141 | loss=0.1739 | lr=7.00e-05 | epoch=0.3018
[train] step=142 | loss=0.1207 | lr=6.99e-05 | epoch=0.3039
[train] step=143 | loss=0.1272 | lr=6.99e-05 | epoch=0.3060
[train] step=144 | loss=0.1082 | lr=6.98e-05 | epoch=0.3082
[train] step=145 | loss=0.1258 | lr=6.98e-05 | epoch=0.3103
[train] step=146 | loss=0.1154 | lr=6.97e-05 | epoch=0.3125
[train] step=147 | loss=0.1249 | lr=6.97e-05 | epoch=0.3146
[train] step=148 | loss=0.1052 | lr=6.96e-05 | epoch=0.3167
[train] step=149 | loss=0.1188 | lr=6.96e-05 | epoch=0.3189
[train] step=150 | loss=0.0991 | lr=6.95e-05 | epoch=0.3210
[train] step=151 | loss=0.1380 | lr=6.94e-05 | epoch=0.3232
[train] step=152 | loss=0.1007 | lr=6.94e-05 | epoch=0.3253
[train] step=153 | loss=0.1053 | lr=6.93e-05 | epoch=0.3274
[train] step=154 | loss=0.1110 | lr=6.93e-05 | epoch=0.3296
[train] step=155 | loss=0.0906 | lr=6.92e-05 | epoch=0.3317
[train] step=156 | loss=0.1311 | lr=6.92e-05 | epoch=0.3339
[train] step=157 | loss=0.1498 | lr=6.91e-05 | epoch=0.3360
[train] step=158 | loss=0.1130 | lr=6.91e-05 | epoch=0.3381
[train] step=159 | loss=0.1081 | lr=6.90e-05 | epoch=0.3403
[train] step=160 | loss=0.1442 | lr=6.89e-05 | epoch=0.3424
[train] step=161 | loss=0.1035 | lr=6.89e-05 | epoch=0.3446
[train] step=162 | loss=0.1014 | lr=6.88e-05 | epoch=0.3467
[train] step=163 | loss=0.1231 | lr=6.88e-05 | epoch=0.3488
[train] step=164 | loss=0.1384 | lr=6.87e-05 | epoch=0.3510
[train] step=165 | loss=0.1201 | lr=6.87e-05 | epoch=0.3531
[train] step=166 | loss=0.1309 | lr=6.86e-05 | epoch=0.3553
[train] step=167 | loss=0.1019 | lr=6.86e-05 | epoch=0.3574
[train] step=168 | loss=0.1044 | lr=6.85e-05 | epoch=0.3596
[train] step=169 | loss=0.1161 | lr=6.84e-05 | epoch=0.3617
[train] step=170 | loss=0.1067 | lr=6.84e-05 | epoch=0.3638
[train] step=171 | loss=0.1218 | lr=6.83e-05 | epoch=0.3660
[train] step=172 | loss=0.1233 | lr=6.83e-05 | epoch=0.3681
[train] step=173 | loss=0.0992 | lr=6.82e-05 | epoch=0.3703
[train] step=174 | loss=0.1175 | lr=6.82e-05 | epoch=0.3724
[train] step=175 | loss=0.1109 | lr=6.81e-05 | epoch=0.3745
[train] step=176 | loss=0.1438 | lr=6.81e-05 | epoch=0.3767
[train] step=177 | loss=0.0901 | lr=6.80e-05 | epoch=0.3788
[train] step=178 | loss=0.1027 | lr=6.80e-05 | epoch=0.3810
[train] step=179 | loss=0.1101 | lr=6.79e-05 | epoch=0.3831
[train] step=180 | loss=0.1127 | lr=6.78e-05 | epoch=0.3852
[train] step=181 | loss=0.1115 | lr=6.78e-05 | epoch=0.3874
[train] step=182 | loss=0.0920 | lr=6.77e-05 | epoch=0.3895
[train] step=183 | loss=0.0846 | lr=6.77e-05 | epoch=0.3917
[train] step=184 | loss=0.1344 | lr=6.76e-05 | epoch=0.3938
[train] step=185 | loss=0.1008 | lr=6.76e-05 | epoch=0.3959
[train] step=186 | loss=0.0931 | lr=6.75e-05 | epoch=0.3981
[train] step=187 | loss=0.1058 | lr=6.75e-05 | epoch=0.4002
[train] step=188 | loss=0.1379 | lr=6.74e-05 | epoch=0.4024
[train] step=189 | loss=0.1255 | lr=6.73e-05 | epoch=0.4045
[train] step=190 | loss=0.1343 | lr=6.73e-05 | epoch=0.4066
[train] step=191 | loss=0.1032 | lr=6.72e-05 | epoch=0.4088
[train] step=192 | loss=0.1119 | lr=6.72e-05 | epoch=0.4109
[train] step=193 | loss=0.1260 | lr=6.71e-05 | epoch=0.4131
[train] step=194 | loss=0.1096 | lr=6.71e-05 | epoch=0.4152
[train] step=195 | loss=0.1223 | lr=6.70e-05 | epoch=0.4173
[train] step=196 | loss=0.1214 | lr=6.70e-05 | epoch=0.4195
[train] step=197 | loss=0.0964 | lr=6.69e-05 | epoch=0.4216
[train] step=198 | loss=0.1420 | lr=6.68e-05 | epoch=0.4238
[train] step=199 | loss=0.1270 | lr=6.68e-05 | epoch=0.4259
[train] step=200 | loss=0.1077 | lr=6.67e-05 | epoch=0.4280
[train] step=201 | loss=0.1112 | lr=6.67e-05 | epoch=0.4302
[train] step=202 | loss=0.1358 | lr=6.66e-05 | epoch=0.4323
[train] step=203 | loss=0.1127 | lr=6.66e-05 | epoch=0.4345
[train] step=204 | loss=0.1240 | lr=6.65e-05 | epoch=0.4366
[train] step=205 | loss=0.0981 | lr=6.65e-05 | epoch=0.4387
[train] step=206 | loss=0.1089 | lr=6.64e-05 | epoch=0.4409
[train] step=207 | loss=0.1160 | lr=6.63e-05 | epoch=0.4430
[train] step=208 | loss=0.1013 | lr=6.63e-05 | epoch=0.4452
[train] step=209 | loss=0.1220 | lr=6.62e-05 | epoch=0.4473
[train] step=210 | loss=0.1086 | lr=6.62e-05 | epoch=0.4494
[train] step=211 | loss=0.1083 | lr=6.61e-05 | epoch=0.4516
[train] step=212 | loss=0.1153 | lr=6.61e-05 | epoch=0.4537
[train] step=213 | loss=0.1480 | lr=6.60e-05 | epoch=0.4559
[train] step=214 | loss=0.1086 | lr=6.60e-05 | epoch=0.4580
[train] step=215 | loss=0.1268 | lr=6.59e-05 | epoch=0.4601
[train] step=216 | loss=0.1068 | lr=6.58e-05 | epoch=0.4623
[train] step=217 | loss=0.1255 | lr=6.58e-05 | epoch=0.4644
[train] step=218 | loss=0.1046 | lr=6.57e-05 | epoch=0.4666
[train] step=219 | loss=0.0996 | lr=6.57e-05 | epoch=0.4687
[train] step=220 | loss=0.0942 | lr=6.56e-05 | epoch=0.4708
[train] step=221 | loss=0.1009 | lr=6.56e-05 | epoch=0.4730
[train] step=222 | loss=0.1235 | lr=6.55e-05 | epoch=0.4751
[train] step=223 | loss=0.1252 | lr=6.55e-05 | epoch=0.4773
[train] step=224 | loss=0.1008 | lr=6.54e-05 | epoch=0.4794
[train] step=225 | loss=0.1254 | lr=6.53e-05 | epoch=0.4815
[train] step=226 | loss=0.1169 | lr=6.53e-05 | epoch=0.4837
[train] step=227 | loss=0.1191 | lr=6.52e-05 | epoch=0.4858
[train] step=228 | loss=0.1044 | lr=6.52e-05 | epoch=0.4880
[train] step=229 | loss=0.1164 | lr=6.51e-05 | epoch=0.4901
[train] step=230 | loss=0.1068 | lr=6.51e-05 | epoch=0.4922
[train] step=231 | loss=0.1271 | lr=6.50e-05 | epoch=0.4944
[train] step=232 | loss=0.1104 | lr=6.50e-05 | epoch=0.4965
[train] step=233 | loss=0.1264 | lr=6.49e-05 | epoch=0.4987

Saving model checkpoint to output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-233
2026-04-06 03:58:38 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:58:38 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 03:58:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 03:58:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-233\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-233\tokenizer_config.json

[train] step=234 | loss=0.1128 | lr=6.48e-05 | epoch=0.5008
[train] step=235 | loss=0.1024 | lr=6.48e-05 | epoch=0.5029
[train] step=236 | loss=0.1099 | lr=6.47e-05 | epoch=0.5051
[train] step=237 | loss=0.1155 | lr=6.47e-05 | epoch=0.5072
[train] step=238 | loss=0.1123 | lr=6.46e-05 | epoch=0.5094
[train] step=239 | loss=0.1071 | lr=6.46e-05 | epoch=0.5115
[train] step=240 | loss=0.1093 | lr=6.45e-05 | epoch=0.5136
[train] step=241 | loss=0.1148 | lr=6.45e-05 | epoch=0.5158
[train] step=242 | loss=0.1017 | lr=6.44e-05 | epoch=0.5179
[train] step=243 | loss=0.1340 | lr=6.44e-05 | epoch=0.5201
[train] step=244 | loss=0.1314 | lr=6.43e-05 | epoch=0.5222
[train] step=245 | loss=0.1034 | lr=6.42e-05 | epoch=0.5243
[train] step=246 | loss=0.1355 | lr=6.42e-05 | epoch=0.5265
[train] step=247 | loss=0.1247 | lr=6.41e-05 | epoch=0.5286
[train] step=248 | loss=0.1000 | lr=6.41e-05 | epoch=0.5308
[train] step=249 | loss=0.0945 | lr=6.40e-05 | epoch=0.5329
[train] step=250 | loss=0.1082 | lr=6.40e-05 | epoch=0.5350
[train] step=251 | loss=0.1073 | lr=6.39e-05 | epoch=0.5372
[train] step=252 | loss=0.1149 | lr=6.39e-05 | epoch=0.5393
[train] step=253 | loss=0.1276 | lr=6.38e-05 | epoch=0.5415
[train] step=254 | loss=0.1084 | lr=6.37e-05 | epoch=0.5436
[train] step=255 | loss=0.1100 | lr=6.37e-05 | epoch=0.5457
[train] step=256 | loss=0.0955 | lr=6.36e-05 | epoch=0.5479
[train] step=257 | loss=0.1023 | lr=6.36e-05 | epoch=0.5500
[train] step=258 | loss=0.1048 | lr=6.35e-05 | epoch=0.5522
[train] step=259 | loss=0.1152 | lr=6.35e-05 | epoch=0.5543
[train] step=260 | loss=0.1160 | lr=6.34e-05 | epoch=0.5564
[train] step=261 | loss=0.0974 | lr=6.34e-05 | epoch=0.5586
[train] step=262 | loss=0.1330 | lr=6.33e-05 | epoch=0.5607
[train] step=263 | loss=0.1019 | lr=6.32e-05 | epoch=0.5629
[train] step=264 | loss=0.0940 | lr=6.32e-05 | epoch=0.5650
[train] step=265 | loss=0.1324 | lr=6.31e-05 | epoch=0.5671
[train] step=266 | loss=0.1088 | lr=6.31e-05 | epoch=0.5693
[train] step=267 | loss=0.1117 | lr=6.30e-05 | epoch=0.5714
[train] step=268 | loss=0.1029 | lr=6.30e-05 | epoch=0.5736
[train] step=269 | loss=0.1121 | lr=6.29e-05 | epoch=0.5757
[train] step=270 | loss=0.1273 | lr=6.29e-05 | epoch=0.5778
[train] step=271 | loss=0.1117 | lr=6.28e-05 | epoch=0.5800
[train] step=272 | loss=0.1160 | lr=6.27e-05 | epoch=0.5821
[train] step=273 | loss=0.0940 | lr=6.27e-05 | epoch=0.5843
[train] step=274 | loss=0.1012 | lr=6.26e-05 | epoch=0.5864
[train] step=275 | loss=0.1194 | lr=6.26e-05 | epoch=0.5886
[train] step=276 | loss=0.1217 | lr=6.25e-05 | epoch=0.5907
[train] step=277 | loss=0.1026 | lr=6.25e-05 | epoch=0.5928
[train] step=278 | loss=0.0982 | lr=6.24e-05 | epoch=0.5950
[train] step=279 | loss=0.0984 | lr=6.24e-05 | epoch=0.5971
[train] step=280 | loss=0.1025 | lr=6.23e-05 | epoch=0.5993
[train] step=281 | loss=0.1036 | lr=6.22e-05 | epoch=0.6014
[train] step=282 | loss=0.1134 | lr=6.22e-05 | epoch=0.6035
[train] step=283 | loss=0.1133 | lr=6.21e-05 | epoch=0.6057
[train] step=284 | loss=0.1036 | lr=6.21e-05 | epoch=0.6078
[train] step=285 | loss=0.0982 | lr=6.20e-05 | epoch=0.6100
[train] step=286 | loss=0.0978 | lr=6.20e-05 | epoch=0.6121
[train] step=287 | loss=0.1131 | lr=6.19e-05 | epoch=0.6142
[train] step=288 | loss=0.0982 | lr=6.19e-05 | epoch=0.6164
[train] step=289 | loss=0.0999 | lr=6.18e-05 | epoch=0.6185
[train] step=290 | loss=0.1048 | lr=6.17e-05 | epoch=0.6207
[train] step=291 | loss=0.1249 | lr=6.17e-05 | epoch=0.6228
[train] step=292 | loss=0.1115 | lr=6.16e-05 | epoch=0.6249
[train] step=293 | loss=0.1344 | lr=6.16e-05 | epoch=0.6271
[train] step=294 | loss=0.1034 | lr=6.15e-05 | epoch=0.6292
[train] step=295 | loss=0.1203 | lr=6.15e-05 | epoch=0.6314
[train] step=296 | loss=0.1003 | lr=6.14e-05 | epoch=0.6335
[train] step=297 | loss=0.1121 | lr=6.14e-05 | epoch=0.6356
[train] step=298 | loss=0.0956 | lr=6.13e-05 | epoch=0.6378
[train] step=299 | loss=0.1022 | lr=6.12e-05 | epoch=0.6399
[train] step=300 | loss=0.1119 | lr=6.12e-05 | epoch=0.6421
[train] step=301 | loss=0.1161 | lr=6.11e-05 | epoch=0.6442
[train] step=302 | loss=0.0985 | lr=6.11e-05 | epoch=0.6463
[train] step=303 | loss=0.1091 | lr=6.10e-05 | epoch=0.6485
[train] step=304 | loss=0.1124 | lr=6.10e-05 | epoch=0.6506
[train] step=305 | loss=0.0986 | lr=6.09e-05 | epoch=0.6528
[train] step=306 | loss=0.1290 | lr=6.09e-05 | epoch=0.6549
[train] step=307 | loss=0.1272 | lr=6.08e-05 | epoch=0.6570
[train] step=308 | loss=0.1015 | lr=6.08e-05 | epoch=0.6592
[train] step=309 | loss=0.1289 | lr=6.07e-05 | epoch=0.6613
[train] step=310 | loss=0.0927 | lr=6.06e-05 | epoch=0.6635
[train] step=311 | loss=0.0963 | lr=6.06e-05 | epoch=0.6656
[train] step=312 | loss=0.1375 | lr=6.05e-05 | epoch=0.6677
[train] step=313 | loss=0.1383 | lr=6.05e-05 | epoch=0.6699
[train] step=314 | loss=0.1058 | lr=6.04e-05 | epoch=0.6720
[train] step=315 | loss=0.0959 | lr=6.04e-05 | epoch=0.6742
[train] step=316 | loss=0.1048 | lr=6.03e-05 | epoch=0.6763
[train] step=317 | loss=0.1081 | lr=6.03e-05 | epoch=0.6784
[train] step=318 | loss=0.1057 | lr=6.02e-05 | epoch=0.6806
[train] step=319 | loss=0.1312 | lr=6.01e-05 | epoch=0.6827
[train] step=320 | loss=0.1119 | lr=6.01e-05 | epoch=0.6849
[train] step=321 | loss=0.1046 | lr=6.00e-05 | epoch=0.6870
[train] step=322 | loss=0.1161 | lr=6.00e-05 | epoch=0.6891
[train] step=323 | loss=0.1102 | lr=5.99e-05 | epoch=0.6913
[train] step=324 | loss=0.1087 | lr=5.99e-05 | epoch=0.6934
[train] step=325 | loss=0.1156 | lr=5.98e-05 | epoch=0.6956
[train] step=326 | loss=0.1041 | lr=5.98e-05 | epoch=0.6977
[train] step=327 | loss=0.1135 | lr=5.97e-05 | epoch=0.6998
[train] step=328 | loss=0.1315 | lr=5.96e-05 | epoch=0.7020
[train] step=329 | loss=0.0864 | lr=5.96e-05 | epoch=0.7041
[train] step=330 | loss=0.0942 | lr=5.95e-05 | epoch=0.7063
[train] step=331 | loss=0.1034 | lr=5.95e-05 | epoch=0.7084
[train] step=332 | loss=0.1224 | lr=5.94e-05 | epoch=0.7105
[train] step=333 | loss=0.1295 | lr=5.94e-05 | epoch=0.7127
[train] step=334 | loss=0.1234 | lr=5.93e-05 | epoch=0.7148
[train] step=335 | loss=0.0838 | lr=5.93e-05 | epoch=0.7170
[train] step=336 | loss=0.1044 | lr=5.92e-05 | epoch=0.7191
[train] step=337 | loss=0.0981 | lr=5.91e-05 | epoch=0.7212
[train] step=338 | loss=0.1056 | lr=5.91e-05 | epoch=0.7234
[train] step=339 | loss=0.1154 | lr=5.90e-05 | epoch=0.7255
[train] step=340 | loss=0.1099 | lr=5.90e-05 | epoch=0.7277
[train] step=341 | loss=0.1422 | lr=5.89e-05 | epoch=0.7298
[train] step=342 | loss=0.0983 | lr=5.89e-05 | epoch=0.7319
[train] step=343 | loss=0.0879 | lr=5.88e-05 | epoch=0.7341
[train] step=344 | loss=0.1067 | lr=5.88e-05 | epoch=0.7362
[train] step=345 | loss=0.1189 | lr=5.87e-05 | epoch=0.7384
[train] step=346 | loss=0.1075 | lr=5.86e-05 | epoch=0.7405
[train] step=347 | loss=0.1009 | lr=5.86e-05 | epoch=0.7426
[train] step=348 | loss=0.1196 | lr=5.85e-05 | epoch=0.7448
[train] step=349 | loss=0.1014 | lr=5.85e-05 | epoch=0.7469
[train] step=350 | loss=0.0843 | lr=5.84e-05 | epoch=0.7491
[train] step=351 | loss=0.1179 | lr=5.84e-05 | epoch=0.7512
[train] step=352 | loss=0.0999 | lr=5.83e-05 | epoch=0.7533
[train] step=353 | loss=0.1315 | lr=5.83e-05 | epoch=0.7555
[train] step=354 | loss=0.0849 | lr=5.82e-05 | epoch=0.7576
[train] step=355 | loss=0.1182 | lr=5.81e-05 | epoch=0.7598
[train] step=356 | loss=0.0989 | lr=5.81e-05 | epoch=0.7619
[train] step=357 | loss=0.1142 | lr=5.80e-05 | epoch=0.7640
[train] step=358 | loss=0.0836 | lr=5.80e-05 | epoch=0.7662
[train] step=359 | loss=0.1039 | lr=5.79e-05 | epoch=0.7683
[train] step=360 | loss=0.1182 | lr=5.79e-05 | epoch=0.7705
[train] step=361 | loss=0.1052 | lr=5.78e-05 | epoch=0.7726
[train] step=362 | loss=0.1054 | lr=5.78e-05 | epoch=0.7747
[train] step=363 | loss=0.1295 | lr=5.77e-05 | epoch=0.7769
[train] step=364 | loss=0.1012 | lr=5.77e-05 | epoch=0.7790
[train] step=365 | loss=0.0971 | lr=5.76e-05 | epoch=0.7812
[train] step=366 | loss=0.1184 | lr=5.75e-05 | epoch=0.7833
[train] step=367 | loss=0.0955 | lr=5.75e-05 | epoch=0.7854
[train] step=368 | loss=0.1129 | lr=5.74e-05 | epoch=0.7876
[train] step=369 | loss=0.1162 | lr=5.74e-05 | epoch=0.7897
[train] step=370 | loss=0.1209 | lr=5.73e-05 | epoch=0.7919
[train] step=371 | loss=0.1224 | lr=5.73e-05 | epoch=0.7940
[train] step=372 | loss=0.1112 | lr=5.72e-05 | epoch=0.7961
[train] step=373 | loss=0.1271 | lr=5.72e-05 | epoch=0.7983
[train] step=374 | loss=0.1093 | lr=5.71e-05 | epoch=0.8004
[train] step=375 | loss=0.1180 | lr=5.70e-05 | epoch=0.8026
[train] step=376 | loss=0.1014 | lr=5.70e-05 | epoch=0.8047
[train] step=377 | loss=0.0967 | lr=5.69e-05 | epoch=0.8068
[train] step=378 | loss=0.1009 | lr=5.69e-05 | epoch=0.8090
[train] step=379 | loss=0.1397 | lr=5.68e-05 | epoch=0.8111
[train] step=380 | loss=0.1325 | lr=5.68e-05 | epoch=0.8133
[train] step=381 | loss=0.1331 | lr=5.67e-05 | epoch=0.8154
[train] step=382 | loss=0.1210 | lr=5.67e-05 | epoch=0.8175
[train] step=383 | loss=0.0983 | lr=5.66e-05 | epoch=0.8197
[train] step=384 | loss=0.0883 | lr=5.65e-05 | epoch=0.8218
[train] step=385 | loss=0.1159 | lr=5.65e-05 | epoch=0.8240
[train] step=386 | loss=0.1578 | lr=5.64e-05 | epoch=0.8261
[train] step=387 | loss=0.0962 | lr=5.64e-05 | epoch=0.8283
[train] step=388 | loss=0.1139 | lr=5.63e-05 | epoch=0.8304
[train] step=389 | loss=0.0979 | lr=5.63e-05 | epoch=0.8325
[train] step=390 | loss=0.1015 | lr=5.62e-05 | epoch=0.8347
[train] step=391 | loss=0.0980 | lr=5.62e-05 | epoch=0.8368
[train] step=392 | loss=0.0949 | lr=5.61e-05 | epoch=0.8390
[train] step=393 | loss=0.1049 | lr=5.60e-05 | epoch=0.8411
[train] step=394 | loss=0.1214 | lr=5.60e-05 | epoch=0.8432
[train] step=395 | loss=0.1131 | lr=5.59e-05 | epoch=0.8454
[train] step=396 | loss=0.1203 | lr=5.59e-05 | epoch=0.8475
[train] step=397 | loss=0.1031 | lr=5.58e-05 | epoch=0.8497
[train] step=398 | loss=0.1106 | lr=5.58e-05 | epoch=0.8518
[train] step=399 | loss=0.1047 | lr=5.57e-05 | epoch=0.8539
[train] step=400 | loss=0.1165 | lr=5.57e-05 | epoch=0.8561
[train] step=401 | loss=0.1127 | lr=5.56e-05 | epoch=0.8582
[train] step=402 | loss=0.1095 | lr=5.55e-05 | epoch=0.8604
[train] step=403 | loss=0.0885 | lr=5.55e-05 | epoch=0.8625
[train] step=404 | loss=0.1074 | lr=5.54e-05 | epoch=0.8646
[train] step=405 | loss=0.1106 | lr=5.54e-05 | epoch=0.8668
[train] step=406 | loss=0.0997 | lr=5.53e-05 | epoch=0.8689
[train] step=407 | loss=0.0858 | lr=5.53e-05 | epoch=0.8711
[train] step=408 | loss=0.1275 | lr=5.52e-05 | epoch=0.8732
[train] step=409 | loss=0.1120 | lr=5.52e-05 | epoch=0.8753
[train] step=410 | loss=0.0919 | lr=5.51e-05 | epoch=0.8775
[train] step=411 | loss=0.1018 | lr=5.50e-05 | epoch=0.8796
[train] step=412 | loss=0.1080 | lr=5.50e-05 | epoch=0.8818
[train] step=413 | loss=0.1058 | lr=5.49e-05 | epoch=0.8839
[train] step=414 | loss=0.1182 | lr=5.49e-05 | epoch=0.8860
[train] step=415 | loss=0.0986 | lr=5.48e-05 | epoch=0.8882
[train] step=416 | loss=0.1233 | lr=5.48e-05 | epoch=0.8903
[train] step=417 | loss=0.1193 | lr=5.47e-05 | epoch=0.8925
[train] step=418 | loss=0.0975 | lr=5.47e-05 | epoch=0.8946
[train] step=419 | loss=0.0978 | lr=5.46e-05 | epoch=0.8967
[train] step=420 | loss=0.1160 | lr=5.45e-05 | epoch=0.8989
[train] step=421 | loss=0.0999 | lr=5.45e-05 | epoch=0.9010
[train] step=422 | loss=0.0939 | lr=5.44e-05 | epoch=0.9032
[train] step=423 | loss=0.1204 | lr=5.44e-05 | epoch=0.9053
[train] step=424 | loss=0.1224 | lr=5.43e-05 | epoch=0.9074
[train] step=425 | loss=0.1097 | lr=5.43e-05 | epoch=0.9096
[train] step=426 | loss=0.1034 | lr=5.42e-05 | epoch=0.9117
[train] step=427 | loss=0.1096 | lr=5.42e-05 | epoch=0.9139
[train] step=428 | loss=0.0959 | lr=5.41e-05 | epoch=0.9160
[train] step=429 | loss=0.1105 | lr=5.41e-05 | epoch=0.9181
[train] step=430 | loss=0.1040 | lr=5.40e-05 | epoch=0.9203
[train] step=431 | loss=0.0979 | lr=5.39e-05 | epoch=0.9224
[train] step=432 | loss=0.1447 | lr=5.39e-05 | epoch=0.9246
[train] step=433 | loss=0.0956 | lr=5.38e-05 | epoch=0.9267
[train] step=434 | loss=0.0935 | lr=5.38e-05 | epoch=0.9288
[train] step=435 | loss=0.1130 | lr=5.37e-05 | epoch=0.9310
[train] step=436 | loss=0.1222 | lr=5.37e-05 | epoch=0.9331
[train] step=437 | loss=0.0990 | lr=5.36e-05 | epoch=0.9353
[train] step=438 | loss=0.0903 | lr=5.36e-05 | epoch=0.9374
[train] step=439 | loss=0.1295 | lr=5.35e-05 | epoch=0.9395
[train] step=440 | loss=0.1208 | lr=5.34e-05 | epoch=0.9417
[train] step=441 | loss=0.1129 | lr=5.34e-05 | epoch=0.9438
[train] step=442 | loss=0.1400 | lr=5.33e-05 | epoch=0.9460
[train] step=443 | loss=0.1013 | lr=5.33e-05 | epoch=0.9481
[train] step=444 | loss=0.1038 | lr=5.32e-05 | epoch=0.9502
[train] step=445 | loss=0.1074 | lr=5.32e-05 | epoch=0.9524
[train] step=446 | loss=0.0899 | lr=5.31e-05 | epoch=0.9545
[train] step=447 | loss=0.0914 | lr=5.31e-05 | epoch=0.9567
[train] step=448 | loss=0.1199 | lr=5.30e-05 | epoch=0.9588
[train] step=449 | loss=0.1225 | lr=5.29e-05 | epoch=0.9609
[train] step=450 | loss=0.0886 | lr=5.29e-05 | epoch=0.9631
[train] step=451 | loss=0.1059 | lr=5.28e-05 | epoch=0.9652
[train] step=452 | loss=0.1036 | lr=5.28e-05 | epoch=0.9674
[train] step=453 | loss=0.0974 | lr=5.27e-05 | epoch=0.9695
[train] step=454 | loss=0.1037 | lr=5.27e-05 | epoch=0.9716
[train] step=455 | loss=0.1020 | lr=5.26e-05 | epoch=0.9738
[train] step=456 | loss=0.1164 | lr=5.26e-05 | epoch=0.9759
[train] step=457 | loss=0.1233 | lr=5.25e-05 | epoch=0.9781
[train] step=458 | loss=0.1168 | lr=5.24e-05 | epoch=0.9802
[train] step=459 | loss=0.1218 | lr=5.24e-05 | epoch=0.9823
[train] step=460 | loss=0.1060 | lr=5.23e-05 | epoch=0.9845
[train] step=461 | loss=0.1091 | lr=5.23e-05 | epoch=0.9866
[train] step=462 | loss=0.1080 | lr=5.22e-05 | epoch=0.9888
[train] step=463 | loss=0.0946 | lr=5.22e-05 | epoch=0.9909
[train] step=464 | loss=0.1178 | lr=5.21e-05 | epoch=0.9930
[train] step=465 | loss=0.1018 | lr=5.21e-05 | epoch=0.9952
[train] step=466 | loss=0.1033 | lr=5.20e-05 | epoch=0.9973

Saving model checkpoint to output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-466
2026-04-06 04:08:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:08:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 04:08:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:08:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-466\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-466\tokenizer_config.json

[train] step=467 | loss=0.1134 | lr=5.19e-05 | epoch=0.9995
[train] step=468 | loss=0.0593 | lr=5.19e-05 | epoch=1.0000
[train] step=469 | loss=0.0897 | lr=5.18e-05 | epoch=1.0021
[train] step=470 | loss=0.1038 | lr=5.18e-05 | epoch=1.0043
[train] step=471 | loss=0.1109 | lr=5.17e-05 | epoch=1.0064
[train] step=472 | loss=0.1225 | lr=5.17e-05 | epoch=1.0086
[train] step=473 | loss=0.1068 | lr=5.16e-05 | epoch=1.0107
[train] step=474 | loss=0.1033 | lr=5.16e-05 | epoch=1.0128
[train] step=475 | loss=0.1032 | lr=5.15e-05 | epoch=1.0150
[train] step=476 | loss=0.1160 | lr=5.14e-05 | epoch=1.0171
[train] step=477 | loss=0.1280 | lr=5.14e-05 | epoch=1.0193
[train] step=478 | loss=0.0839 | lr=5.13e-05 | epoch=1.0214
[train] step=479 | loss=0.1172 | lr=5.13e-05 | epoch=1.0235
[train] step=480 | loss=0.0850 | lr=5.12e-05 | epoch=1.0257
[train] step=481 | loss=0.1129 | lr=5.12e-05 | epoch=1.0278
[train] step=482 | loss=0.1250 | lr=5.11e-05 | epoch=1.0300
[train] step=483 | loss=0.0887 | lr=5.11e-05 | epoch=1.0321
[train] step=484 | loss=0.1107 | lr=5.10e-05 | epoch=1.0342
[train] step=485 | loss=0.0882 | lr=5.09e-05 | epoch=1.0364
[train] step=486 | loss=0.1064 | lr=5.09e-05 | epoch=1.0385
[train] step=487 | loss=0.1340 | lr=5.08e-05 | epoch=1.0407
[train] step=488 | loss=0.1189 | lr=5.08e-05 | epoch=1.0428
[train] step=489 | loss=0.0942 | lr=5.07e-05 | epoch=1.0449
[train] step=490 | loss=0.1024 | lr=5.07e-05 | epoch=1.0471
[train] step=491 | loss=0.0993 | lr=5.06e-05 | epoch=1.0492
[train] step=492 | loss=0.1182 | lr=5.06e-05 | epoch=1.0514
[train] step=493 | loss=0.0952 | lr=5.05e-05 | epoch=1.0535
[train] step=494 | loss=0.1115 | lr=5.05e-05 | epoch=1.0556
[train] step=495 | loss=0.1004 | lr=5.04e-05 | epoch=1.0578
[train] step=496 | loss=0.1161 | lr=5.03e-05 | epoch=1.0599
[train] step=497 | loss=0.1022 | lr=5.03e-05 | epoch=1.0621
[train] step=498 | loss=0.1338 | lr=5.02e-05 | epoch=1.0642
[train] step=499 | loss=0.1161 | lr=5.02e-05 | epoch=1.0663
[train] step=500 | loss=0.1102 | lr=5.01e-05 | epoch=1.0685
[train] step=501 | loss=0.0992 | lr=5.01e-05 | epoch=1.0706
[train] step=502 | loss=0.0982 | lr=5.00e-05 | epoch=1.0728
[train] step=503 | loss=0.1457 | lr=5.00e-05 | epoch=1.0749
[train] step=504 | loss=0.1199 | lr=4.99e-05 | epoch=1.0770
[train] step=505 | loss=0.1196 | lr=4.98e-05 | epoch=1.0792
[train] step=506 | loss=0.0991 | lr=4.98e-05 | epoch=1.0813
[train] step=507 | loss=0.1108 | lr=4.97e-05 | epoch=1.0835
[train] step=508 | loss=0.1151 | lr=4.97e-05 | epoch=1.0856
[train] step=509 | loss=0.1507 | lr=4.96e-05 | epoch=1.0877
[train] step=510 | loss=0.1177 | lr=4.96e-05 | epoch=1.0899
[train] step=511 | loss=0.1101 | lr=4.95e-05 | epoch=1.0920
[train] step=512 | loss=0.1068 | lr=4.95e-05 | epoch=1.0942
[train] step=513 | loss=0.0935 | lr=4.94e-05 | epoch=1.0963
[train] step=514 | loss=0.1017 | lr=4.93e-05 | epoch=1.0984
[train] step=515 | loss=0.1073 | lr=4.93e-05 | epoch=1.1006
[train] step=516 | loss=0.1223 | lr=4.92e-05 | epoch=1.1027
[train] step=517 | loss=0.0918 | lr=4.92e-05 | epoch=1.1049
[train] step=518 | loss=0.1319 | lr=4.91e-05 | epoch=1.1070
[train] step=519 | loss=0.1130 | lr=4.91e-05 | epoch=1.1091
[train] step=520 | loss=0.1064 | lr=4.90e-05 | epoch=1.1113
[train] step=521 | loss=0.1027 | lr=4.90e-05 | epoch=1.1134
[train] step=522 | loss=0.1291 | lr=4.89e-05 | epoch=1.1156
[train] step=523 | loss=0.1029 | lr=4.88e-05 | epoch=1.1177
[train] step=524 | loss=0.1040 | lr=4.88e-05 | epoch=1.1199
[train] step=525 | loss=0.0900 | lr=4.87e-05 | epoch=1.1220
[train] step=526 | loss=0.1068 | lr=4.87e-05 | epoch=1.1241
[train] step=527 | loss=0.0909 | lr=4.86e-05 | epoch=1.1263
[train] step=528 | loss=0.1248 | lr=4.86e-05 | epoch=1.1284
[train] step=529 | loss=0.1081 | lr=4.85e-05 | epoch=1.1306
[train] step=530 | loss=0.1110 | lr=4.85e-05 | epoch=1.1327
[train] step=531 | loss=0.1379 | lr=4.84e-05 | epoch=1.1348
[train] step=532 | loss=0.1106 | lr=4.83e-05 | epoch=1.1370
[train] step=533 | loss=0.1068 | lr=4.83e-05 | epoch=1.1391
[train] step=534 | loss=0.1065 | lr=4.82e-05 | epoch=1.1413
[train] step=535 | loss=0.1090 | lr=4.82e-05 | epoch=1.1434
[train] step=536 | loss=0.1168 | lr=4.81e-05 | epoch=1.1455
[train] step=537 | loss=0.0978 | lr=4.81e-05 | epoch=1.1477
[train] step=538 | loss=0.1114 | lr=4.80e-05 | epoch=1.1498
[train] step=539 | loss=0.1077 | lr=4.80e-05 | epoch=1.1520
[train] step=540 | loss=0.0897 | lr=4.79e-05 | epoch=1.1541
[train] step=541 | loss=0.0807 | lr=4.78e-05 | epoch=1.1562
[train] step=542 | loss=0.1163 | lr=4.78e-05 | epoch=1.1584
[train] step=543 | loss=0.1022 | lr=4.77e-05 | epoch=1.1605
[train] step=544 | loss=0.0881 | lr=4.77e-05 | epoch=1.1627
[train] step=545 | loss=0.0998 | lr=4.76e-05 | epoch=1.1648
[train] step=546 | loss=0.0892 | lr=4.76e-05 | epoch=1.1669
[train] step=547 | loss=0.0949 | lr=4.75e-05 | epoch=1.1691
[train] step=548 | loss=0.1023 | lr=4.75e-05 | epoch=1.1712
[train] step=549 | loss=0.0807 | lr=4.74e-05 | epoch=1.1734
[train] step=550 | loss=0.0979 | lr=4.73e-05 | epoch=1.1755
[train] step=551 | loss=0.1052 | lr=4.73e-05 | epoch=1.1776
[train] step=552 | loss=0.1085 | lr=4.72e-05 | epoch=1.1798
[train] step=553 | loss=0.1159 | lr=4.72e-05 | epoch=1.1819
[train] step=554 | loss=0.0957 | lr=4.71e-05 | epoch=1.1841
[train] step=555 | loss=0.0996 | lr=4.71e-05 | epoch=1.1862
[train] step=556 | loss=0.0958 | lr=4.70e-05 | epoch=1.1883
[train] step=557 | loss=0.1230 | lr=4.70e-05 | epoch=1.1905
[train] step=558 | loss=0.1066 | lr=4.69e-05 | epoch=1.1926
[train] step=559 | loss=0.1139 | lr=4.69e-05 | epoch=1.1948
[train] step=560 | loss=0.1002 | lr=4.68e-05 | epoch=1.1969
[train] step=561 | loss=0.1062 | lr=4.67e-05 | epoch=1.1990
[train] step=562 | loss=0.1063 | lr=4.67e-05 | epoch=1.2012
[train] step=563 | loss=0.1178 | lr=4.66e-05 | epoch=1.2033
[train] step=564 | loss=0.0968 | lr=4.66e-05 | epoch=1.2055
[train] step=565 | loss=0.1339 | lr=4.65e-05 | epoch=1.2076
[train] step=566 | loss=0.1136 | lr=4.65e-05 | epoch=1.2097
[train] step=567 | loss=0.0953 | lr=4.64e-05 | epoch=1.2119
[train] step=568 | loss=0.0990 | lr=4.64e-05 | epoch=1.2140
[train] step=569 | loss=0.1088 | lr=4.63e-05 | epoch=1.2162
[train] step=570 | loss=0.0955 | lr=4.62e-05 | epoch=1.2183
[train] step=571 | loss=0.1038 | lr=4.62e-05 | epoch=1.2204
[train] step=572 | loss=0.1110 | lr=4.61e-05 | epoch=1.2226
[train] step=573 | loss=0.1278 | lr=4.61e-05 | epoch=1.2247
[train] step=574 | loss=0.0944 | lr=4.60e-05 | epoch=1.2269
[train] step=575 | loss=0.1046 | lr=4.60e-05 | epoch=1.2290
[train] step=576 | loss=0.1081 | lr=4.59e-05 | epoch=1.2311
[train] step=577 | loss=0.1374 | lr=4.59e-05 | epoch=1.2333
[train] step=578 | loss=0.1124 | lr=4.58e-05 | epoch=1.2354
[train] step=579 | loss=0.1217 | lr=4.57e-05 | epoch=1.2376
[train] step=580 | loss=0.0978 | lr=4.57e-05 | epoch=1.2397
[train] step=581 | loss=0.1003 | lr=4.56e-05 | epoch=1.2418
[train] step=582 | loss=0.1001 | lr=4.56e-05 | epoch=1.2440
[train] step=583 | loss=0.1167 | lr=4.55e-05 | epoch=1.2461
[train] step=584 | loss=0.1023 | lr=4.55e-05 | epoch=1.2483
[train] step=585 | loss=0.1170 | lr=4.54e-05 | epoch=1.2504
[train] step=586 | loss=0.0948 | lr=4.54e-05 | epoch=1.2525
[train] step=587 | loss=0.1112 | lr=4.53e-05 | epoch=1.2547
[train] step=588 | loss=0.1266 | lr=4.52e-05 | epoch=1.2568
[train] step=589 | loss=0.1349 | lr=4.52e-05 | epoch=1.2590
[train] step=590 | loss=0.1240 | lr=4.51e-05 | epoch=1.2611
[train] step=591 | loss=0.0912 | lr=4.51e-05 | epoch=1.2632
[train] step=592 | loss=0.1134 | lr=4.50e-05 | epoch=1.2654
[train] step=593 | loss=0.1012 | lr=4.50e-05 | epoch=1.2675
[train] step=594 | loss=0.0964 | lr=4.49e-05 | epoch=1.2697
[train] step=595 | loss=0.0825 | lr=4.49e-05 | epoch=1.2718
[train] step=596 | loss=0.0994 | lr=4.48e-05 | epoch=1.2739
[train] step=597 | loss=0.1025 | lr=4.47e-05 | epoch=1.2761
[train] step=598 | loss=0.1043 | lr=4.47e-05 | epoch=1.2782
[train] step=599 | loss=0.1014 | lr=4.46e-05 | epoch=1.2804
[train] step=600 | loss=0.1181 | lr=4.46e-05 | epoch=1.2825
[train] step=601 | loss=0.1125 | lr=4.45e-05 | epoch=1.2846
[train] step=602 | loss=0.0970 | lr=4.45e-05 | epoch=1.2868
[train] step=603 | loss=0.0917 | lr=4.44e-05 | epoch=1.2889
[train] step=604 | loss=0.0966 | lr=4.44e-05 | epoch=1.2911
[train] step=605 | loss=0.0969 | lr=4.43e-05 | epoch=1.2932
[train] step=606 | loss=0.0806 | lr=4.42e-05 | epoch=1.2953
[train] step=607 | loss=0.1127 | lr=4.42e-05 | epoch=1.2975
[train] step=608 | loss=0.0854 | lr=4.41e-05 | epoch=1.2996
[train] step=609 | loss=0.1221 | lr=4.41e-05 | epoch=1.3018
[train] step=610 | loss=0.1191 | lr=4.40e-05 | epoch=1.3039
[train] step=611 | loss=0.0846 | lr=4.40e-05 | epoch=1.3060
[train] step=612 | loss=0.1106 | lr=4.39e-05 | epoch=1.3082
[train] step=613 | loss=0.1190 | lr=4.39e-05 | epoch=1.3103
[train] step=614 | loss=0.1076 | lr=4.38e-05 | epoch=1.3125
[train] step=615 | loss=0.1051 | lr=4.37e-05 | epoch=1.3146
[train] step=616 | loss=0.0990 | lr=4.37e-05 | epoch=1.3167
[train] step=617 | loss=0.0777 | lr=4.36e-05 | epoch=1.3189
[train] step=618 | loss=0.1125 | lr=4.36e-05 | epoch=1.3210
[train] step=619 | loss=0.1095 | lr=4.35e-05 | epoch=1.3232
[train] step=620 | loss=0.0998 | lr=4.35e-05 | epoch=1.3253
[train] step=621 | loss=0.1224 | lr=4.34e-05 | epoch=1.3274
[train] step=622 | loss=0.1010 | lr=4.34e-05 | epoch=1.3296
[train] step=623 | loss=0.1040 | lr=4.33e-05 | epoch=1.3317
[train] step=624 | loss=0.1113 | lr=4.33e-05 | epoch=1.3339
[train] step=625 | loss=0.1030 | lr=4.32e-05 | epoch=1.3360
[train] step=626 | loss=0.0924 | lr=4.31e-05 | epoch=1.3381
[train] step=627 | loss=0.1395 | lr=4.31e-05 | epoch=1.3403
[train] step=628 | loss=0.0961 | lr=4.30e-05 | epoch=1.3424
[train] step=629 | loss=0.0790 | lr=4.30e-05 | epoch=1.3446
[train] step=630 | loss=0.1091 | lr=4.29e-05 | epoch=1.3467
[train] step=631 | loss=0.1009 | lr=4.29e-05 | epoch=1.3488
[train] step=632 | loss=0.1096 | lr=4.28e-05 | epoch=1.3510
[train] step=633 | loss=0.1121 | lr=4.28e-05 | epoch=1.3531
[train] step=634 | loss=0.1169 | lr=4.27e-05 | epoch=1.3553
[train] step=635 | loss=0.1004 | lr=4.26e-05 | epoch=1.3574
[train] step=636 | loss=0.1035 | lr=4.26e-05 | epoch=1.3596
[train] step=637 | loss=0.0972 | lr=4.25e-05 | epoch=1.3617
[train] step=638 | loss=0.1102 | lr=4.25e-05 | epoch=1.3638
[train] step=639 | loss=0.1112 | lr=4.24e-05 | epoch=1.3660
[train] step=640 | loss=0.0838 | lr=4.24e-05 | epoch=1.3681
[train] step=641 | loss=0.1009 | lr=4.23e-05 | epoch=1.3703
[train] step=642 | loss=0.1027 | lr=4.23e-05 | epoch=1.3724
[train] step=643 | loss=0.1220 | lr=4.22e-05 | epoch=1.3745
[train] step=644 | loss=0.1172 | lr=4.21e-05 | epoch=1.3767
[train] step=645 | loss=0.1211 | lr=4.21e-05 | epoch=1.3788
[train] step=646 | loss=0.1019 | lr=4.20e-05 | epoch=1.3810
[train] step=647 | loss=0.0911 | lr=4.20e-05 | epoch=1.3831
[train] step=648 | loss=0.1090 | lr=4.19e-05 | epoch=1.3852
[train] step=649 | loss=0.0720 | lr=4.19e-05 | epoch=1.3874
[train] step=650 | loss=0.0904 | lr=4.18e-05 | epoch=1.3895
[train] step=651 | loss=0.0878 | lr=4.18e-05 | epoch=1.3917
[train] step=652 | loss=0.1004 | lr=4.17e-05 | epoch=1.3938
[train] step=653 | loss=0.1179 | lr=4.16e-05 | epoch=1.3959
[train] step=654 | loss=0.0877 | lr=4.16e-05 | epoch=1.3981
[train] step=655 | loss=0.0857 | lr=4.15e-05 | epoch=1.4002
[train] step=656 | loss=0.1106 | lr=4.15e-05 | epoch=1.4024
[train] step=657 | loss=0.1008 | lr=4.14e-05 | epoch=1.4045
[train] step=658 | loss=0.1064 | lr=4.14e-05 | epoch=1.4066
[train] step=659 | loss=0.1152 | lr=4.13e-05 | epoch=1.4088
[train] step=660 | loss=0.1012 | lr=4.13e-05 | epoch=1.4109
[train] step=661 | loss=0.1455 | lr=4.12e-05 | epoch=1.4131
[train] step=662 | loss=0.1086 | lr=4.11e-05 | epoch=1.4152
[train] step=663 | loss=0.1143 | lr=4.11e-05 | epoch=1.4173
[train] step=664 | loss=0.1124 | lr=4.10e-05 | epoch=1.4195
[train] step=665 | loss=0.0963 | lr=4.10e-05 | epoch=1.4216
[train] step=666 | loss=0.0881 | lr=4.09e-05 | epoch=1.4238
[train] step=667 | loss=0.0935 | lr=4.09e-05 | epoch=1.4259
[train] step=668 | loss=0.1004 | lr=4.08e-05 | epoch=1.4280
[train] step=669 | loss=0.1057 | lr=4.08e-05 | epoch=1.4302
[train] step=670 | loss=0.1075 | lr=4.07e-05 | epoch=1.4323
[train] step=671 | loss=0.1063 | lr=4.06e-05 | epoch=1.4345
[train] step=672 | loss=0.0854 | lr=4.06e-05 | epoch=1.4366
[train] step=673 | loss=0.1273 | lr=4.05e-05 | epoch=1.4387
[train] step=674 | loss=0.1132 | lr=4.05e-05 | epoch=1.4409
[train] step=675 | loss=0.0889 | lr=4.04e-05 | epoch=1.4430
[train] step=676 | loss=0.1040 | lr=4.04e-05 | epoch=1.4452
[train] step=677 | loss=0.0937 | lr=4.03e-05 | epoch=1.4473
[train] step=678 | loss=0.0929 | lr=4.03e-05 | epoch=1.4494
[train] step=679 | loss=0.0932 | lr=4.02e-05 | epoch=1.4516
[train] step=680 | loss=0.0932 | lr=4.02e-05 | epoch=1.4537
[train] step=681 | loss=0.1124 | lr=4.01e-05 | epoch=1.4559
[train] step=682 | loss=0.1023 | lr=4.00e-05 | epoch=1.4580
[train] step=683 | loss=0.0916 | lr=4.00e-05 | epoch=1.4601
[train] step=684 | loss=0.1038 | lr=3.99e-05 | epoch=1.4623
[train] step=685 | loss=0.1199 | lr=3.99e-05 | epoch=1.4644
[train] step=686 | loss=0.1055 | lr=3.98e-05 | epoch=1.4666
[train] step=687 | loss=0.0990 | lr=3.98e-05 | epoch=1.4687
[train] step=688 | loss=0.1311 | lr=3.97e-05 | epoch=1.4708
[train] step=689 | loss=0.1083 | lr=3.97e-05 | epoch=1.4730
[train] step=690 | loss=0.1206 | lr=3.96e-05 | epoch=1.4751
[train] step=691 | loss=0.0830 | lr=3.95e-05 | epoch=1.4773
[train] step=692 | loss=0.1096 | lr=3.95e-05 | epoch=1.4794
[train] step=693 | loss=0.0995 | lr=3.94e-05 | epoch=1.4815
[train] step=694 | loss=0.1081 | lr=3.94e-05 | epoch=1.4837
[train] step=695 | loss=0.0873 | lr=3.93e-05 | epoch=1.4858
[train] step=696 | loss=0.1111 | lr=3.93e-05 | epoch=1.4880
[train] step=697 | loss=0.1245 | lr=3.92e-05 | epoch=1.4901
[train] step=698 | loss=0.1161 | lr=3.92e-05 | epoch=1.4922
[train] step=699 | loss=0.1204 | lr=3.91e-05 | epoch=1.4944

Saving model checkpoint to output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-699
2026-04-06 04:17:58 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:17:58 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 04:17:58 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:17:58 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-699\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-699\tokenizer_config.json

[train] step=700 | loss=0.0946 | lr=3.90e-05 | epoch=1.4965
[train] step=701 | loss=0.1207 | lr=3.90e-05 | epoch=1.4987
[train] step=702 | loss=0.0911 | lr=3.89e-05 | epoch=1.5008
[train] step=703 | loss=0.1016 | lr=3.89e-05 | epoch=1.5029
[train] step=704 | loss=0.0970 | lr=3.88e-05 | epoch=1.5051
[train] step=705 | loss=0.1240 | lr=3.88e-05 | epoch=1.5072
[train] step=706 | loss=0.1167 | lr=3.87e-05 | epoch=1.5094
[train] step=707 | loss=0.1109 | lr=3.87e-05 | epoch=1.5115
[train] step=708 | loss=0.0976 | lr=3.86e-05 | epoch=1.5136
[train] step=709 | loss=0.0871 | lr=3.85e-05 | epoch=1.5158
[train] step=710 | loss=0.1063 | lr=3.85e-05 | epoch=1.5179
[train] step=711 | loss=0.0996 | lr=3.84e-05 | epoch=1.5201
[train] step=712 | loss=0.1046 | lr=3.84e-05 | epoch=1.5222
[train] step=713 | loss=0.0903 | lr=3.83e-05 | epoch=1.5243
[train] step=714 | loss=0.0883 | lr=3.83e-05 | epoch=1.5265
[train] step=715 | loss=0.0816 | lr=3.82e-05 | epoch=1.5286
[train] step=716 | loss=0.1091 | lr=3.82e-05 | epoch=1.5308
[train] step=717 | loss=0.1109 | lr=3.81e-05 | epoch=1.5329
[train] step=718 | loss=0.1059 | lr=3.80e-05 | epoch=1.5350
[train] step=719 | loss=0.0782 | lr=3.80e-05 | epoch=1.5372
[train] step=720 | loss=0.1143 | lr=3.79e-05 | epoch=1.5393
[train] step=721 | loss=0.1090 | lr=3.79e-05 | epoch=1.5415
[train] step=722 | loss=0.1011 | lr=3.78e-05 | epoch=1.5436
[train] step=723 | loss=0.1117 | lr=3.78e-05 | epoch=1.5457
[train] step=724 | loss=0.0935 | lr=3.77e-05 | epoch=1.5479
[train] step=725 | loss=0.1614 | lr=3.77e-05 | epoch=1.5500
[train] step=726 | loss=0.1063 | lr=3.76e-05 | epoch=1.5522
[train] step=727 | loss=0.1026 | lr=3.75e-05 | epoch=1.5543
[train] step=728 | loss=0.1008 | lr=3.75e-05 | epoch=1.5564
[train] step=729 | loss=0.1075 | lr=3.74e-05 | epoch=1.5586
[train] step=730 | loss=0.1069 | lr=3.74e-05 | epoch=1.5607
[train] step=731 | loss=0.1049 | lr=3.73e-05 | epoch=1.5629
[train] step=732 | loss=0.1123 | lr=3.73e-05 | epoch=1.5650
[train] step=733 | loss=0.0811 | lr=3.72e-05 | epoch=1.5671
[train] step=734 | loss=0.1009 | lr=3.72e-05 | epoch=1.5693
[train] step=735 | loss=0.1009 | lr=3.71e-05 | epoch=1.5714
[train] step=736 | loss=0.1015 | lr=3.70e-05 | epoch=1.5736
[train] step=737 | loss=0.1025 | lr=3.70e-05 | epoch=1.5757
[train] step=738 | loss=0.1057 | lr=3.69e-05 | epoch=1.5778
[train] step=739 | loss=0.1063 | lr=3.69e-05 | epoch=1.5800
[train] step=740 | loss=0.1234 | lr=3.68e-05 | epoch=1.5821
[train] step=741 | loss=0.1089 | lr=3.68e-05 | epoch=1.5843
[train] step=742 | loss=0.1194 | lr=3.67e-05 | epoch=1.5864
[train] step=743 | loss=0.1027 | lr=3.67e-05 | epoch=1.5886
[train] step=744 | loss=0.1111 | lr=3.66e-05 | epoch=1.5907
[train] step=745 | loss=0.0861 | lr=3.66e-05 | epoch=1.5928
[train] step=746 | loss=0.1062 | lr=3.65e-05 | epoch=1.5950
[train] step=747 | loss=0.1286 | lr=3.64e-05 | epoch=1.5971
[train] step=748 | loss=0.0956 | lr=3.64e-05 | epoch=1.5993
[train] step=749 | loss=0.0983 | lr=3.63e-05 | epoch=1.6014
[train] step=750 | loss=0.1095 | lr=3.63e-05 | epoch=1.6035
[train] step=751 | loss=0.1112 | lr=3.62e-05 | epoch=1.6057
[train] step=752 | loss=0.1036 | lr=3.62e-05 | epoch=1.6078
[train] step=753 | loss=0.1197 | lr=3.61e-05 | epoch=1.6100
[train] step=754 | loss=0.1062 | lr=3.61e-05 | epoch=1.6121
[train] step=755 | loss=0.1105 | lr=3.60e-05 | epoch=1.6142
[train] step=756 | loss=0.1097 | lr=3.59e-05 | epoch=1.6164
[train] step=757 | loss=0.0951 | lr=3.59e-05 | epoch=1.6185
[train] step=758 | loss=0.0925 | lr=3.58e-05 | epoch=1.6207
[train] step=759 | loss=0.0934 | lr=3.58e-05 | epoch=1.6228
[train] step=760 | loss=0.0779 | lr=3.57e-05 | epoch=1.6249
[train] step=761 | loss=0.0965 | lr=3.57e-05 | epoch=1.6271
[train] step=762 | loss=0.1168 | lr=3.56e-05 | epoch=1.6292
[train] step=763 | loss=0.1169 | lr=3.56e-05 | epoch=1.6314
[train] step=764 | loss=0.1332 | lr=3.55e-05 | epoch=1.6335
[train] step=765 | loss=0.0988 | lr=3.54e-05 | epoch=1.6356
[train] step=766 | loss=0.1251 | lr=3.54e-05 | epoch=1.6378
[train] step=767 | loss=0.1271 | lr=3.53e-05 | epoch=1.6399
[train] step=768 | loss=0.0906 | lr=3.53e-05 | epoch=1.6421
[train] step=769 | loss=0.1129 | lr=3.52e-05 | epoch=1.6442
[train] step=770 | loss=0.0855 | lr=3.52e-05 | epoch=1.6463
[train] step=771 | loss=0.1085 | lr=3.51e-05 | epoch=1.6485
[train] step=772 | loss=0.0913 | lr=3.51e-05 | epoch=1.6506
[train] step=773 | loss=0.0974 | lr=3.50e-05 | epoch=1.6528
[train] step=774 | loss=0.0811 | lr=3.49e-05 | epoch=1.6549
[train] step=775 | loss=0.1084 | lr=3.49e-05 | epoch=1.6570
[train] step=776 | loss=0.0832 | lr=3.48e-05 | epoch=1.6592
[train] step=777 | loss=0.1068 | lr=3.48e-05 | epoch=1.6613
[train] step=778 | loss=0.1096 | lr=3.47e-05 | epoch=1.6635
[train] step=779 | loss=0.1089 | lr=3.47e-05 | epoch=1.6656
[train] step=780 | loss=0.1278 | lr=3.46e-05 | epoch=1.6677
[train] step=781 | loss=0.0913 | lr=3.46e-05 | epoch=1.6699
[train] step=782 | loss=0.0971 | lr=3.45e-05 | epoch=1.6720
[train] step=783 | loss=0.1042 | lr=3.44e-05 | epoch=1.6742
[train] step=784 | loss=0.1107 | lr=3.44e-05 | epoch=1.6763
[train] step=785 | loss=0.0839 | lr=3.43e-05 | epoch=1.6784
[train] step=786 | loss=0.1038 | lr=3.43e-05 | epoch=1.6806
[train] step=787 | loss=0.0999 | lr=3.42e-05 | epoch=1.6827
[train] step=788 | loss=0.1186 | lr=3.42e-05 | epoch=1.6849
[train] step=789 | loss=0.1104 | lr=3.41e-05 | epoch=1.6870
[train] step=790 | loss=0.1032 | lr=3.41e-05 | epoch=1.6891
[train] step=791 | loss=0.0948 | lr=3.40e-05 | epoch=1.6913
[train] step=792 | loss=0.0990 | lr=3.39e-05 | epoch=1.6934
[train] step=793 | loss=0.1124 | lr=3.39e-05 | epoch=1.6956
[train] step=794 | loss=0.1060 | lr=3.38e-05 | epoch=1.6977
[train] step=795 | loss=0.0998 | lr=3.38e-05 | epoch=1.6998
[train] step=796 | loss=0.1227 | lr=3.37e-05 | epoch=1.7020
[train] step=797 | loss=0.1088 | lr=3.37e-05 | epoch=1.7041
[train] step=798 | loss=0.1081 | lr=3.36e-05 | epoch=1.7063
[train] step=799 | loss=0.1065 | lr=3.36e-05 | epoch=1.7084
[train] step=800 | loss=0.1053 | lr=3.35e-05 | epoch=1.7105
[train] step=801 | loss=0.1205 | lr=3.34e-05 | epoch=1.7127
[train] step=802 | loss=0.1099 | lr=3.34e-05 | epoch=1.7148
[train] step=803 | loss=0.1262 | lr=3.33e-05 | epoch=1.7170
[train] step=804 | loss=0.0974 | lr=3.33e-05 | epoch=1.7191
[train] step=805 | loss=0.1026 | lr=3.32e-05 | epoch=1.7212
[train] step=806 | loss=0.1008 | lr=3.32e-05 | epoch=1.7234
[train] step=807 | loss=0.1087 | lr=3.31e-05 | epoch=1.7255
[train] step=808 | loss=0.0759 | lr=3.31e-05 | epoch=1.7277
[train] step=809 | loss=0.0961 | lr=3.30e-05 | epoch=1.7298
[train] step=810 | loss=0.1131 | lr=3.30e-05 | epoch=1.7319
[train] step=811 | loss=0.0966 | lr=3.29e-05 | epoch=1.7341
[train] step=812 | loss=0.1150 | lr=3.28e-05 | epoch=1.7362
[train] step=813 | loss=0.1027 | lr=3.28e-05 | epoch=1.7384
[train] step=814 | loss=0.0889 | lr=3.27e-05 | epoch=1.7405
[train] step=815 | loss=0.0884 | lr=3.27e-05 | epoch=1.7426
[train] step=816 | loss=0.1227 | lr=3.26e-05 | epoch=1.7448
[train] step=817 | loss=0.1040 | lr=3.26e-05 | epoch=1.7469
[train] step=818 | loss=0.1205 | lr=3.25e-05 | epoch=1.7491
[train] step=819 | loss=0.0932 | lr=3.25e-05 | epoch=1.7512
[train] step=820 | loss=0.1068 | lr=3.24e-05 | epoch=1.7533
[train] step=821 | loss=0.1137 | lr=3.23e-05 | epoch=1.7555
[train] step=822 | loss=0.0943 | lr=3.23e-05 | epoch=1.7576
[train] step=823 | loss=0.1143 | lr=3.22e-05 | epoch=1.7598
[train] step=824 | loss=0.0905 | lr=3.22e-05 | epoch=1.7619
[train] step=825 | loss=0.1005 | lr=3.21e-05 | epoch=1.7640
[train] step=826 | loss=0.0907 | lr=3.21e-05 | epoch=1.7662
[train] step=827 | loss=0.0958 | lr=3.20e-05 | epoch=1.7683
[train] step=828 | loss=0.1018 | lr=3.20e-05 | epoch=1.7705
[train] step=829 | loss=0.0897 | lr=3.19e-05 | epoch=1.7726
[train] step=830 | loss=0.1046 | lr=3.18e-05 | epoch=1.7747
[train] step=831 | loss=0.0929 | lr=3.18e-05 | epoch=1.7769
[train] step=832 | loss=0.1197 | lr=3.17e-05 | epoch=1.7790
[train] step=833 | loss=0.1228 | lr=3.17e-05 | epoch=1.7812
[train] step=834 | loss=0.0959 | lr=3.16e-05 | epoch=1.7833
[train] step=835 | loss=0.1251 | lr=3.16e-05 | epoch=1.7854
[train] step=836 | loss=0.0972 | lr=3.15e-05 | epoch=1.7876
[train] step=837 | loss=0.0949 | lr=3.15e-05 | epoch=1.7897
[train] step=838 | loss=0.1251 | lr=3.14e-05 | epoch=1.7919
[train] step=839 | loss=0.1095 | lr=3.13e-05 | epoch=1.7940
[train] step=840 | loss=0.0924 | lr=3.13e-05 | epoch=1.7961
[train] step=841 | loss=0.0938 | lr=3.12e-05 | epoch=1.7983
[train] step=842 | loss=0.1084 | lr=3.12e-05 | epoch=1.8004
[train] step=843 | loss=0.0781 | lr=3.11e-05 | epoch=1.8026
[train] step=844 | loss=0.0970 | lr=3.11e-05 | epoch=1.8047
[train] step=845 | loss=0.1013 | lr=3.10e-05 | epoch=1.8068
[train] step=846 | loss=0.1056 | lr=3.10e-05 | epoch=1.8090
[train] step=847 | loss=0.0939 | lr=3.09e-05 | epoch=1.8111
[train] step=848 | loss=0.0774 | lr=3.08e-05 | epoch=1.8133
[train] step=849 | loss=0.0918 | lr=3.08e-05 | epoch=1.8154
[train] step=850 | loss=0.1127 | lr=3.07e-05 | epoch=1.8175
[train] step=851 | loss=0.1103 | lr=3.07e-05 | epoch=1.8197
[train] step=852 | loss=0.0880 | lr=3.06e-05 | epoch=1.8218
[train] step=853 | loss=0.1200 | lr=3.06e-05 | epoch=1.8240
[train] step=854 | loss=0.1011 | lr=3.05e-05 | epoch=1.8261
[train] step=855 | loss=0.0988 | lr=3.05e-05 | epoch=1.8283
[train] step=856 | loss=0.1124 | lr=3.04e-05 | epoch=1.8304
[train] step=857 | loss=0.0939 | lr=3.03e-05 | epoch=1.8325
[train] step=858 | loss=0.0885 | lr=3.03e-05 | epoch=1.8347
[train] step=859 | loss=0.1023 | lr=3.02e-05 | epoch=1.8368
[train] step=860 | loss=0.1156 | lr=3.02e-05 | epoch=1.8390
[train] step=861 | loss=0.0992 | lr=3.01e-05 | epoch=1.8411
[train] step=862 | loss=0.0906 | lr=3.01e-05 | epoch=1.8432
[train] step=863 | loss=0.0880 | lr=3.00e-05 | epoch=1.8454
[train] step=864 | loss=0.1081 | lr=3.00e-05 | epoch=1.8475
[train] step=865 | loss=0.1018 | lr=2.99e-05 | epoch=1.8497
[train] step=866 | loss=0.1011 | lr=2.98e-05 | epoch=1.8518
[train] step=867 | loss=0.1032 | lr=2.98e-05 | epoch=1.8539
[train] step=868 | loss=0.0802 | lr=2.97e-05 | epoch=1.8561
[train] step=869 | loss=0.0987 | lr=2.97e-05 | epoch=1.8582
[train] step=870 | loss=0.1165 | lr=2.96e-05 | epoch=1.8604
[train] step=871 | loss=0.1224 | lr=2.96e-05 | epoch=1.8625
[train] step=872 | loss=0.1386 | lr=2.95e-05 | epoch=1.8646
[train] step=873 | loss=0.0996 | lr=2.95e-05 | epoch=1.8668
[train] step=874 | loss=0.1076 | lr=2.94e-05 | epoch=1.8689
[train] step=875 | loss=0.0939 | lr=2.94e-05 | epoch=1.8711
[train] step=876 | loss=0.1075 | lr=2.93e-05 | epoch=1.8732
[train] step=877 | loss=0.1278 | lr=2.92e-05 | epoch=1.8753
[train] step=878 | loss=0.0965 | lr=2.92e-05 | epoch=1.8775
[train] step=879 | loss=0.0914 | lr=2.91e-05 | epoch=1.8796
[train] step=880 | loss=0.1414 | lr=2.91e-05 | epoch=1.8818
[train] step=881 | loss=0.0916 | lr=2.90e-05 | epoch=1.8839
[train] step=882 | loss=0.1166 | lr=2.90e-05 | epoch=1.8860
[train] step=883 | loss=0.1002 | lr=2.89e-05 | epoch=1.8882
[train] step=884 | loss=0.1134 | lr=2.89e-05 | epoch=1.8903
[train] step=885 | loss=0.1211 | lr=2.88e-05 | epoch=1.8925
[train] step=886 | loss=0.1036 | lr=2.87e-05 | epoch=1.8946
[train] step=887 | loss=0.1234 | lr=2.87e-05 | epoch=1.8967
[train] step=888 | loss=0.1356 | lr=2.86e-05 | epoch=1.8989
[train] step=889 | loss=0.1260 | lr=2.86e-05 | epoch=1.9010
[train] step=890 | loss=0.1081 | lr=2.85e-05 | epoch=1.9032
[train] step=891 | loss=0.1014 | lr=2.85e-05 | epoch=1.9053
[train] step=892 | loss=0.0937 | lr=2.84e-05 | epoch=1.9074
[train] step=893 | loss=0.1096 | lr=2.84e-05 | epoch=1.9096
[train] step=894 | loss=0.1226 | lr=2.83e-05 | epoch=1.9117
[train] step=895 | loss=0.1167 | lr=2.82e-05 | epoch=1.9139
[train] step=896 | loss=0.0860 | lr=2.82e-05 | epoch=1.9160
[train] step=897 | loss=0.1116 | lr=2.81e-05 | epoch=1.9181
[train] step=898 | loss=0.1098 | lr=2.81e-05 | epoch=1.9203
[train] step=899 | loss=0.1039 | lr=2.80e-05 | epoch=1.9224
[train] step=900 | loss=0.1111 | lr=2.80e-05 | epoch=1.9246
[train] step=901 | loss=0.1001 | lr=2.79e-05 | epoch=1.9267
[train] step=902 | loss=0.1106 | lr=2.79e-05 | epoch=1.9288
[train] step=903 | loss=0.0950 | lr=2.78e-05 | epoch=1.9310
[train] step=904 | loss=0.1019 | lr=2.77e-05 | epoch=1.9331
[train] step=905 | loss=0.1139 | lr=2.77e-05 | epoch=1.9353
[train] step=906 | loss=0.1252 | lr=2.76e-05 | epoch=1.9374
[train] step=907 | loss=0.1029 | lr=2.76e-05 | epoch=1.9395
[train] step=908 | loss=0.0910 | lr=2.75e-05 | epoch=1.9417
[train] step=909 | loss=0.1242 | lr=2.75e-05 | epoch=1.9438
[train] step=910 | loss=0.1086 | lr=2.74e-05 | epoch=1.9460
[train] step=911 | loss=0.1057 | lr=2.74e-05 | epoch=1.9481
[train] step=912 | loss=0.1040 | lr=2.73e-05 | epoch=1.9502
[train] step=913 | loss=0.1063 | lr=2.72e-05 | epoch=1.9524
[train] step=914 | loss=0.0800 | lr=2.72e-05 | epoch=1.9545
[train] step=915 | loss=0.0964 | lr=2.71e-05 | epoch=1.9567
[train] step=916 | loss=0.0973 | lr=2.71e-05 | epoch=1.9588
[train] step=917 | loss=0.0887 | lr=2.70e-05 | epoch=1.9609
[train] step=918 | loss=0.1086 | lr=2.70e-05 | epoch=1.9631
[train] step=919 | loss=0.1079 | lr=2.69e-05 | epoch=1.9652
[train] step=920 | loss=0.0922 | lr=2.69e-05 | epoch=1.9674
[train] step=921 | loss=0.0998 | lr=2.68e-05 | epoch=1.9695
[train] step=922 | loss=0.1059 | lr=2.67e-05 | epoch=1.9716
[train] step=923 | loss=0.0911 | lr=2.67e-05 | epoch=1.9738
[train] step=924 | loss=0.0922 | lr=2.66e-05 | epoch=1.9759
[train] step=925 | loss=0.1063 | lr=2.66e-05 | epoch=1.9781
[train] step=926 | loss=0.1005 | lr=2.65e-05 | epoch=1.9802
[train] step=927 | loss=0.1113 | lr=2.65e-05 | epoch=1.9823
[train] step=928 | loss=0.1101 | lr=2.64e-05 | epoch=1.9845
[train] step=929 | loss=0.1205 | lr=2.64e-05 | epoch=1.9866
[train] step=930 | loss=0.1099 | lr=2.63e-05 | epoch=1.9888
[train] step=931 | loss=0.0901 | lr=2.62e-05 | epoch=1.9909
[train] step=932 | loss=0.1086 | lr=2.62e-05 | epoch=1.9930

Saving model checkpoint to output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-932
2026-04-06 04:27:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:27:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 04:27:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:27:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-932\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-932\tokenizer_config.json

[train] step=933 | loss=0.1351 | lr=2.61e-05 | epoch=1.9952
[train] step=934 | loss=0.1082 | lr=2.61e-05 | epoch=1.9973
[train] step=935 | loss=0.1079 | lr=2.60e-05 | epoch=1.9995
[train] step=936 | loss=0.0358 | lr=2.60e-05 | epoch=2.0000
[train] step=937 | loss=0.0929 | lr=2.59e-05 | epoch=2.0021
[train] step=938 | loss=0.0972 | lr=2.59e-05 | epoch=2.0043
[train] step=939 | loss=0.0739 | lr=2.58e-05 | epoch=2.0064
[train] step=940 | loss=0.0980 | lr=2.58e-05 | epoch=2.0086
[train] step=941 | loss=0.1062 | lr=2.57e-05 | epoch=2.0107
[train] step=942 | loss=0.1077 | lr=2.56e-05 | epoch=2.0128
[train] step=943 | loss=0.1032 | lr=2.56e-05 | epoch=2.0150
[train] step=944 | loss=0.1074 | lr=2.55e-05 | epoch=2.0171
[train] step=945 | loss=0.1077 | lr=2.55e-05 | epoch=2.0193
[train] step=946 | loss=0.1102 | lr=2.54e-05 | epoch=2.0214
[train] step=947 | loss=0.1021 | lr=2.54e-05 | epoch=2.0235
[train] step=948 | loss=0.1003 | lr=2.53e-05 | epoch=2.0257
[train] step=949 | loss=0.1253 | lr=2.53e-05 | epoch=2.0278
[train] step=950 | loss=0.0854 | lr=2.52e-05 | epoch=2.0300
[train] step=951 | loss=0.1003 | lr=2.51e-05 | epoch=2.0321
[train] step=952 | loss=0.1096 | lr=2.51e-05 | epoch=2.0342
[train] step=953 | loss=0.1069 | lr=2.50e-05 | epoch=2.0364
[train] step=954 | loss=0.0955 | lr=2.50e-05 | epoch=2.0385
[train] step=955 | loss=0.1502 | lr=2.49e-05 | epoch=2.0407
[train] step=956 | loss=0.0945 | lr=2.49e-05 | epoch=2.0428
[train] step=957 | loss=0.0826 | lr=2.48e-05 | epoch=2.0449
[train] step=958 | loss=0.1203 | lr=2.48e-05 | epoch=2.0471
[train] step=959 | loss=0.0942 | lr=2.47e-05 | epoch=2.0492
[train] step=960 | loss=0.0966 | lr=2.46e-05 | epoch=2.0514
[train] step=961 | loss=0.0993 | lr=2.46e-05 | epoch=2.0535
[train] step=962 | loss=0.0983 | lr=2.45e-05 | epoch=2.0556
[train] step=963 | loss=0.1129 | lr=2.45e-05 | epoch=2.0578
[train] step=964 | loss=0.0818 | lr=2.44e-05 | epoch=2.0599
[train] step=965 | loss=0.0940 | lr=2.44e-05 | epoch=2.0621
[train] step=966 | loss=0.1127 | lr=2.43e-05 | epoch=2.0642
[train] step=967 | loss=0.0954 | lr=2.43e-05 | epoch=2.0663
[train] step=968 | loss=0.1140 | lr=2.42e-05 | epoch=2.0685
[train] step=969 | loss=0.1014 | lr=2.41e-05 | epoch=2.0706
[train] step=970 | loss=0.1065 | lr=2.41e-05 | epoch=2.0728
[train] step=971 | loss=0.1025 | lr=2.40e-05 | epoch=2.0749
[train] step=972 | loss=0.1221 | lr=2.40e-05 | epoch=2.0770
[train] step=973 | loss=0.1088 | lr=2.39e-05 | epoch=2.0792
[train] step=974 | loss=0.1266 | lr=2.39e-05 | epoch=2.0813
[train] step=975 | loss=0.0963 | lr=2.38e-05 | epoch=2.0835
[train] step=976 | loss=0.0907 | lr=2.38e-05 | epoch=2.0856
[train] step=977 | loss=0.0888 | lr=2.37e-05 | epoch=2.0877
[train] step=978 | loss=0.0915 | lr=2.36e-05 | epoch=2.0899
[train] step=979 | loss=0.0869 | lr=2.36e-05 | epoch=2.0920
[train] step=980 | loss=0.0923 | lr=2.35e-05 | epoch=2.0942
[train] step=981 | loss=0.1072 | lr=2.35e-05 | epoch=2.0963
[train] step=982 | loss=0.1132 | lr=2.34e-05 | epoch=2.0984
[train] step=983 | loss=0.1002 | lr=2.34e-05 | epoch=2.1006
[train] step=984 | loss=0.0889 | lr=2.33e-05 | epoch=2.1027
[train] step=985 | loss=0.1133 | lr=2.33e-05 | epoch=2.1049
[train] step=986 | loss=0.1068 | lr=2.32e-05 | epoch=2.1070
[train] step=987 | loss=0.1217 | lr=2.31e-05 | epoch=2.1091
[train] step=988 | loss=0.0864 | lr=2.31e-05 | epoch=2.1113
[train] step=989 | loss=0.1205 | lr=2.30e-05 | epoch=2.1134
[train] step=990 | loss=0.0983 | lr=2.30e-05 | epoch=2.1156
[train] step=991 | loss=0.0991 | lr=2.29e-05 | epoch=2.1177
[train] step=992 | loss=0.1112 | lr=2.29e-05 | epoch=2.1199
[train] step=993 | loss=0.0724 | lr=2.28e-05 | epoch=2.1220
[train] step=994 | loss=0.0942 | lr=2.28e-05 | epoch=2.1241
[train] step=995 | loss=0.1170 | lr=2.27e-05 | epoch=2.1263
[train] step=996 | loss=0.0946 | lr=2.27e-05 | epoch=2.1284
[train] step=997 | loss=0.0908 | lr=2.26e-05 | epoch=2.1306
[train] step=998 | loss=0.0996 | lr=2.25e-05 | epoch=2.1327
[train] step=999 | loss=0.1163 | lr=2.25e-05 | epoch=2.1348
[train] step=1000 | loss=0.0994 | lr=2.24e-05 | epoch=2.1370
[train] step=1001 | loss=0.0899 | lr=2.24e-05 | epoch=2.1391
[train] step=1002 | loss=0.0955 | lr=2.23e-05 | epoch=2.1413
[train] step=1003 | loss=0.0929 | lr=2.23e-05 | epoch=2.1434
[train] step=1004 | loss=0.0987 | lr=2.22e-05 | epoch=2.1455
[train] step=1005 | loss=0.1021 | lr=2.22e-05 | epoch=2.1477
[train] step=1006 | loss=0.0998 | lr=2.21e-05 | epoch=2.1498
[train] step=1007 | loss=0.1019 | lr=2.20e-05 | epoch=2.1520
[train] step=1008 | loss=0.0877 | lr=2.20e-05 | epoch=2.1541
[train] step=1009 | loss=0.0998 | lr=2.19e-05 | epoch=2.1562
[train] step=1010 | loss=0.0786 | lr=2.19e-05 | epoch=2.1584
[train] step=1011 | loss=0.1351 | lr=2.18e-05 | epoch=2.1605
[train] step=1012 | loss=0.1137 | lr=2.18e-05 | epoch=2.1627
[train] step=1013 | loss=0.1053 | lr=2.17e-05 | epoch=2.1648
[train] step=1014 | loss=0.0912 | lr=2.17e-05 | epoch=2.1669
[train] step=1015 | loss=0.0898 | lr=2.16e-05 | epoch=2.1691
[train] step=1016 | loss=0.1023 | lr=2.15e-05 | epoch=2.1712
[train] step=1017 | loss=0.1164 | lr=2.15e-05 | epoch=2.1734
[train] step=1018 | loss=0.0986 | lr=2.14e-05 | epoch=2.1755
[train] step=1019 | loss=0.1214 | lr=2.14e-05 | epoch=2.1776
[train] step=1020 | loss=0.0912 | lr=2.13e-05 | epoch=2.1798
[train] step=1021 | loss=0.0909 | lr=2.13e-05 | epoch=2.1819
[train] step=1022 | loss=0.1198 | lr=2.12e-05 | epoch=2.1841
[train] step=1023 | loss=0.0958 | lr=2.12e-05 | epoch=2.1862
[train] step=1024 | loss=0.0979 | lr=2.11e-05 | epoch=2.1883
[train] step=1025 | loss=0.0969 | lr=2.10e-05 | epoch=2.1905
[train] step=1026 | loss=0.1116 | lr=2.10e-05 | epoch=2.1926
[train] step=1027 | loss=0.1128 | lr=2.09e-05 | epoch=2.1948
[train] step=1028 | loss=0.1005 | lr=2.09e-05 | epoch=2.1969
[train] step=1029 | loss=0.1336 | lr=2.08e-05 | epoch=2.1990
[train] step=1030 | loss=0.1010 | lr=2.08e-05 | epoch=2.2012
[train] step=1031 | loss=0.1128 | lr=2.07e-05 | epoch=2.2033
[train] step=1032 | loss=0.1030 | lr=2.07e-05 | epoch=2.2055
[train] step=1033 | loss=0.1139 | lr=2.06e-05 | epoch=2.2076
[train] step=1034 | loss=0.0993 | lr=2.05e-05 | epoch=2.2097
[train] step=1035 | loss=0.1111 | lr=2.05e-05 | epoch=2.2119
[train] step=1036 | loss=0.0934 | lr=2.04e-05 | epoch=2.2140
[train] step=1037 | loss=0.1264 | lr=2.04e-05 | epoch=2.2162
[train] step=1038 | loss=0.1172 | lr=2.03e-05 | epoch=2.2183
[train] step=1039 | loss=0.1002 | lr=2.03e-05 | epoch=2.2204
[train] step=1040 | loss=0.0837 | lr=2.02e-05 | epoch=2.2226
[train] step=1041 | loss=0.0885 | lr=2.02e-05 | epoch=2.2247
[train] step=1042 | loss=0.0965 | lr=2.01e-05 | epoch=2.2269
[train] step=1043 | loss=0.0885 | lr=2.00e-05 | epoch=2.2290
[train] step=1044 | loss=0.1214 | lr=2.00e-05 | epoch=2.2311
[train] step=1045 | loss=0.0880 | lr=1.99e-05 | epoch=2.2333
[train] step=1046 | loss=0.1290 | lr=1.99e-05 | epoch=2.2354
[train] step=1047 | loss=0.1202 | lr=1.98e-05 | epoch=2.2376
[train] step=1048 | loss=0.0998 | lr=1.98e-05 | epoch=2.2397
[train] step=1049 | loss=0.1068 | lr=1.97e-05 | epoch=2.2418
[train] step=1050 | loss=0.0891 | lr=1.97e-05 | epoch=2.2440
[train] step=1051 | loss=0.0896 | lr=1.96e-05 | epoch=2.2461
[train] step=1052 | loss=0.1092 | lr=1.95e-05 | epoch=2.2483
[train] step=1053 | loss=0.1038 | lr=1.95e-05 | epoch=2.2504
[train] step=1054 | loss=0.0981 | lr=1.94e-05 | epoch=2.2525
[train] step=1055 | loss=0.1105 | lr=1.94e-05 | epoch=2.2547
[train] step=1056 | loss=0.1130 | lr=1.93e-05 | epoch=2.2568
[train] step=1057 | loss=0.0930 | lr=1.93e-05 | epoch=2.2590
[train] step=1058 | loss=0.0896 | lr=1.92e-05 | epoch=2.2611
[train] step=1059 | loss=0.1097 | lr=1.92e-05 | epoch=2.2632
[train] step=1060 | loss=0.1027 | lr=1.91e-05 | epoch=2.2654
[train] step=1061 | loss=0.1006 | lr=1.91e-05 | epoch=2.2675
[train] step=1062 | loss=0.1031 | lr=1.90e-05 | epoch=2.2697
[train] step=1063 | loss=0.0779 | lr=1.89e-05 | epoch=2.2718
[train] step=1064 | loss=0.0942 | lr=1.89e-05 | epoch=2.2739
[train] step=1065 | loss=0.0950 | lr=1.88e-05 | epoch=2.2761
[train] step=1066 | loss=0.1016 | lr=1.88e-05 | epoch=2.2782
[train] step=1067 | loss=0.0899 | lr=1.87e-05 | epoch=2.2804
[train] step=1068 | loss=0.1173 | lr=1.87e-05 | epoch=2.2825
[train] step=1069 | loss=0.0843 | lr=1.86e-05 | epoch=2.2846
[train] step=1070 | loss=0.1089 | lr=1.86e-05 | epoch=2.2868
[train] step=1071 | loss=0.1012 | lr=1.85e-05 | epoch=2.2889
[train] step=1072 | loss=0.0846 | lr=1.84e-05 | epoch=2.2911
[train] step=1073 | loss=0.0890 | lr=1.84e-05 | epoch=2.2932
[train] step=1074 | loss=0.0911 | lr=1.83e-05 | epoch=2.2953
[train] step=1075 | loss=0.1042 | lr=1.83e-05 | epoch=2.2975
[train] step=1076 | loss=0.1056 | lr=1.82e-05 | epoch=2.2996
[train] step=1077 | loss=0.0960 | lr=1.82e-05 | epoch=2.3018
[train] step=1078 | loss=0.0994 | lr=1.81e-05 | epoch=2.3039
[train] step=1079 | loss=0.1171 | lr=1.81e-05 | epoch=2.3060
[train] step=1080 | loss=0.1086 | lr=1.80e-05 | epoch=2.3082
[train] step=1081 | loss=0.1279 | lr=1.79e-05 | epoch=2.3103
[train] step=1082 | loss=0.1099 | lr=1.79e-05 | epoch=2.3125
[train] step=1083 | loss=0.1040 | lr=1.78e-05 | epoch=2.3146
[train] step=1084 | loss=0.0812 | lr=1.78e-05 | epoch=2.3167
[train] step=1085 | loss=0.0970 | lr=1.77e-05 | epoch=2.3189
[train] step=1086 | loss=0.0862 | lr=1.77e-05 | epoch=2.3210
[train] step=1087 | loss=0.1135 | lr=1.76e-05 | epoch=2.3232
[train] step=1088 | loss=0.1163 | lr=1.76e-05 | epoch=2.3253
[train] step=1089 | loss=0.0904 | lr=1.75e-05 | epoch=2.3274
[train] step=1090 | loss=0.1165 | lr=1.74e-05 | epoch=2.3296
[train] step=1091 | loss=0.1126 | lr=1.74e-05 | epoch=2.3317
[train] step=1092 | loss=0.0990 | lr=1.73e-05 | epoch=2.3339
[train] step=1093 | loss=0.0935 | lr=1.73e-05 | epoch=2.3360
[train] step=1094 | loss=0.0913 | lr=1.72e-05 | epoch=2.3381
[train] step=1095 | loss=0.1030 | lr=1.72e-05 | epoch=2.3403
[train] step=1096 | loss=0.1015 | lr=1.71e-05 | epoch=2.3424
[train] step=1097 | loss=0.1188 | lr=1.71e-05 | epoch=2.3446
[train] step=1098 | loss=0.0934 | lr=1.70e-05 | epoch=2.3467
[train] step=1099 | loss=0.0996 | lr=1.69e-05 | epoch=2.3488
[train] step=1100 | loss=0.0943 | lr=1.69e-05 | epoch=2.3510
[train] step=1101 | loss=0.1103 | lr=1.68e-05 | epoch=2.3531
[train] step=1102 | loss=0.1080 | lr=1.68e-05 | epoch=2.3553
[train] step=1103 | loss=0.0849 | lr=1.67e-05 | epoch=2.3574
[train] step=1104 | loss=0.1090 | lr=1.67e-05 | epoch=2.3596
[train] step=1105 | loss=0.0984 | lr=1.66e-05 | epoch=2.3617
[train] step=1106 | loss=0.1462 | lr=1.66e-05 | epoch=2.3638
[train] step=1107 | loss=0.1049 | lr=1.65e-05 | epoch=2.3660
[train] step=1108 | loss=0.0987 | lr=1.64e-05 | epoch=2.3681
[train] step=1109 | loss=0.1098 | lr=1.64e-05 | epoch=2.3703
[train] step=1110 | loss=0.1039 | lr=1.63e-05 | epoch=2.3724
[train] step=1111 | loss=0.1002 | lr=1.63e-05 | epoch=2.3745
[train] step=1112 | loss=0.0926 | lr=1.62e-05 | epoch=2.3767
[train] step=1113 | loss=0.1164 | lr=1.62e-05 | epoch=2.3788
[train] step=1114 | loss=0.1210 | lr=1.61e-05 | epoch=2.3810
[train] step=1115 | loss=0.0914 | lr=1.61e-05 | epoch=2.3831
[train] step=1116 | loss=0.1233 | lr=1.60e-05 | epoch=2.3852
[train] step=1117 | loss=0.1000 | lr=1.59e-05 | epoch=2.3874
[train] step=1118 | loss=0.0944 | lr=1.59e-05 | epoch=2.3895
[train] step=1119 | loss=0.1042 | lr=1.58e-05 | epoch=2.3917
[train] step=1120 | loss=0.0994 | lr=1.58e-05 | epoch=2.3938
[train] step=1121 | loss=0.0986 | lr=1.57e-05 | epoch=2.3959
[train] step=1122 | loss=0.1149 | lr=1.57e-05 | epoch=2.3981
[train] step=1123 | loss=0.1237 | lr=1.56e-05 | epoch=2.4002
[train] step=1124 | loss=0.1008 | lr=1.56e-05 | epoch=2.4024
[train] step=1125 | loss=0.0948 | lr=1.55e-05 | epoch=2.4045
[train] step=1126 | loss=0.0877 | lr=1.55e-05 | epoch=2.4066
[train] step=1127 | loss=0.1002 | lr=1.54e-05 | epoch=2.4088
[train] step=1128 | loss=0.0986 | lr=1.53e-05 | epoch=2.4109
[train] step=1129 | loss=0.0985 | lr=1.53e-05 | epoch=2.4131
[train] step=1130 | loss=0.0919 | lr=1.52e-05 | epoch=2.4152
[train] step=1131 | loss=0.1121 | lr=1.52e-05 | epoch=2.4173
[train] step=1132 | loss=0.0838 | lr=1.51e-05 | epoch=2.4195
[train] step=1133 | loss=0.0892 | lr=1.51e-05 | epoch=2.4216
[train] step=1134 | loss=0.1052 | lr=1.50e-05 | epoch=2.4238
[train] step=1135 | loss=0.1151 | lr=1.50e-05 | epoch=2.4259
[train] step=1136 | loss=0.1110 | lr=1.49e-05 | epoch=2.4280
[train] step=1137 | loss=0.0849 | lr=1.48e-05 | epoch=2.4302
[train] step=1138 | loss=0.0942 | lr=1.48e-05 | epoch=2.4323
[train] step=1139 | loss=0.1005 | lr=1.47e-05 | epoch=2.4345
[train] step=1140 | loss=0.1051 | lr=1.47e-05 | epoch=2.4366
[train] step=1141 | loss=0.1238 | lr=1.46e-05 | epoch=2.4387
[train] step=1142 | loss=0.0940 | lr=1.46e-05 | epoch=2.4409
[train] step=1143 | loss=0.1004 | lr=1.45e-05 | epoch=2.4430
[train] step=1144 | loss=0.0953 | lr=1.45e-05 | epoch=2.4452
[train] step=1145 | loss=0.0855 | lr=1.44e-05 | epoch=2.4473
[train] step=1146 | loss=0.1021 | lr=1.43e-05 | epoch=2.4494
[train] step=1147 | loss=0.0970 | lr=1.43e-05 | epoch=2.4516
[train] step=1148 | loss=0.1429 | lr=1.42e-05 | epoch=2.4537
[train] step=1149 | loss=0.1136 | lr=1.42e-05 | epoch=2.4559
[train] step=1150 | loss=0.0974 | lr=1.41e-05 | epoch=2.4580
[train] step=1151 | loss=0.1010 | lr=1.41e-05 | epoch=2.4601
[train] step=1152 | loss=0.1000 | lr=1.40e-05 | epoch=2.4623
[train] step=1153 | loss=0.1300 | lr=1.40e-05 | epoch=2.4644
[train] step=1154 | loss=0.1052 | lr=1.39e-05 | epoch=2.4666
[train] step=1155 | loss=0.0938 | lr=1.38e-05 | epoch=2.4687
[train] step=1156 | loss=0.0965 | lr=1.38e-05 | epoch=2.4708
[train] step=1157 | loss=0.1022 | lr=1.37e-05 | epoch=2.4730
[train] step=1158 | loss=0.0934 | lr=1.37e-05 | epoch=2.4751
[train] step=1159 | loss=0.1098 | lr=1.36e-05 | epoch=2.4773
[train] step=1160 | loss=0.0945 | lr=1.36e-05 | epoch=2.4794
[train] step=1161 | loss=0.0947 | lr=1.35e-05 | epoch=2.4815
[train] step=1162 | loss=0.0978 | lr=1.35e-05 | epoch=2.4837
[train] step=1163 | loss=0.0980 | lr=1.34e-05 | epoch=2.4858
[train] step=1164 | loss=0.0859 | lr=1.33e-05 | epoch=2.4880
[train] step=1165 | loss=0.0818 | lr=1.33e-05 | epoch=2.4901

Saving model checkpoint to output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1165
2026-04-06 04:37:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:37:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 04:37:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:37:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1165\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1165\tokenizer_config.json

[train] step=1166 | loss=0.0953 | lr=1.32e-05 | epoch=2.4922
[train] step=1167 | loss=0.0939 | lr=1.32e-05 | epoch=2.4944
[train] step=1168 | loss=0.0974 | lr=1.31e-05 | epoch=2.4965
[train] step=1169 | loss=0.1305 | lr=1.31e-05 | epoch=2.4987
[train] step=1170 | loss=0.0869 | lr=1.30e-05 | epoch=2.5008
[train] step=1171 | loss=0.0900 | lr=1.30e-05 | epoch=2.5029
[train] step=1172 | loss=0.1076 | lr=1.29e-05 | epoch=2.5051
[train] step=1173 | loss=0.0759 | lr=1.28e-05 | epoch=2.5072
[train] step=1174 | loss=0.0864 | lr=1.28e-05 | epoch=2.5094
[train] step=1175 | loss=0.0908 | lr=1.27e-05 | epoch=2.5115
[train] step=1176 | loss=0.1028 | lr=1.27e-05 | epoch=2.5136
[train] step=1177 | loss=0.1236 | lr=1.26e-05 | epoch=2.5158
[train] step=1178 | loss=0.0986 | lr=1.26e-05 | epoch=2.5179
[train] step=1179 | loss=0.0999 | lr=1.25e-05 | epoch=2.5201
[train] step=1180 | loss=0.0941 | lr=1.25e-05 | epoch=2.5222
[train] step=1181 | loss=0.1225 | lr=1.24e-05 | epoch=2.5243
[train] step=1182 | loss=0.0927 | lr=1.23e-05 | epoch=2.5265
[train] step=1183 | loss=0.1156 | lr=1.23e-05 | epoch=2.5286
[train] step=1184 | loss=0.1042 | lr=1.22e-05 | epoch=2.5308
[train] step=1185 | loss=0.1031 | lr=1.22e-05 | epoch=2.5329
[train] step=1186 | loss=0.0971 | lr=1.21e-05 | epoch=2.5350
[train] step=1187 | loss=0.0981 | lr=1.21e-05 | epoch=2.5372
[train] step=1188 | loss=0.0918 | lr=1.20e-05 | epoch=2.5393
[train] step=1189 | loss=0.1035 | lr=1.20e-05 | epoch=2.5415
[train] step=1190 | loss=0.1055 | lr=1.19e-05 | epoch=2.5436
[train] step=1191 | loss=0.1308 | lr=1.19e-05 | epoch=2.5457
[train] step=1192 | loss=0.0823 | lr=1.18e-05 | epoch=2.5479
[train] step=1193 | loss=0.0859 | lr=1.17e-05 | epoch=2.5500
[train] step=1194 | loss=0.1011 | lr=1.17e-05 | epoch=2.5522
[train] step=1195 | loss=0.1223 | lr=1.16e-05 | epoch=2.5543
[train] step=1196 | loss=0.0952 | lr=1.16e-05 | epoch=2.5564
[train] step=1197 | loss=0.1089 | lr=1.15e-05 | epoch=2.5586
[train] step=1198 | loss=0.1097 | lr=1.15e-05 | epoch=2.5607
[train] step=1199 | loss=0.0925 | lr=1.14e-05 | epoch=2.5629
[train] step=1200 | loss=0.1075 | lr=1.14e-05 | epoch=2.5650
[train] step=1201 | loss=0.0984 | lr=1.13e-05 | epoch=2.5671
[train] step=1202 | loss=0.1095 | lr=1.12e-05 | epoch=2.5693
[train] step=1203 | loss=0.1061 | lr=1.12e-05 | epoch=2.5714
[train] step=1204 | loss=0.1174 | lr=1.11e-05 | epoch=2.5736
[train] step=1205 | loss=0.0973 | lr=1.11e-05 | epoch=2.5757
[train] step=1206 | loss=0.0921 | lr=1.10e-05 | epoch=2.5778
[train] step=1207 | loss=0.1044 | lr=1.10e-05 | epoch=2.5800
[train] step=1208 | loss=0.0862 | lr=1.09e-05 | epoch=2.5821
[train] step=1209 | loss=0.1033 | lr=1.09e-05 | epoch=2.5843
[train] step=1210 | loss=0.1059 | lr=1.08e-05 | epoch=2.5864
[train] step=1211 | loss=0.1240 | lr=1.07e-05 | epoch=2.5886
[train] step=1212 | loss=0.1025 | lr=1.07e-05 | epoch=2.5907
[train] step=1213 | loss=0.0965 | lr=1.06e-05 | epoch=2.5928
[train] step=1214 | loss=0.0843 | lr=1.06e-05 | epoch=2.5950
[train] step=1215 | loss=0.1071 | lr=1.05e-05 | epoch=2.5971
[train] step=1216 | loss=0.1237 | lr=1.05e-05 | epoch=2.5993
[train] step=1217 | loss=0.1057 | lr=1.04e-05 | epoch=2.6014
[train] step=1218 | loss=0.0985 | lr=1.04e-05 | epoch=2.6035
[train] step=1219 | loss=0.1031 | lr=1.03e-05 | epoch=2.6057
[train] step=1220 | loss=0.0999 | lr=1.02e-05 | epoch=2.6078
[train] step=1221 | loss=0.1059 | lr=1.02e-05 | epoch=2.6100
[train] step=1222 | loss=0.1232 | lr=1.01e-05 | epoch=2.6121
[train] step=1223 | loss=0.1122 | lr=1.01e-05 | epoch=2.6142
[train] step=1224 | loss=0.0867 | lr=1.00e-05 | epoch=2.6164
[train] step=1225 | loss=0.0983 | lr=9.97e-06 | epoch=2.6185
[train] step=1226 | loss=0.0924 | lr=9.91e-06 | epoch=2.6207
[train] step=1227 | loss=0.0957 | lr=9.86e-06 | epoch=2.6228
[train] step=1228 | loss=0.1075 | lr=9.80e-06 | epoch=2.6249
[train] step=1229 | loss=0.0956 | lr=9.75e-06 | epoch=2.6271
[train] step=1230 | loss=0.1059 | lr=9.69e-06 | epoch=2.6292
[train] step=1231 | loss=0.0728 | lr=9.64e-06 | epoch=2.6314
[train] step=1232 | loss=0.1066 | lr=9.58e-06 | epoch=2.6335
[train] step=1233 | loss=0.1189 | lr=9.53e-06 | epoch=2.6356
[train] step=1234 | loss=0.1096 | lr=9.47e-06 | epoch=2.6378
[train] step=1235 | loss=0.1126 | lr=9.41e-06 | epoch=2.6399
[train] step=1236 | loss=0.0823 | lr=9.36e-06 | epoch=2.6421
[train] step=1237 | loss=0.0956 | lr=9.30e-06 | epoch=2.6442
[train] step=1238 | loss=0.0940 | lr=9.25e-06 | epoch=2.6463
[train] step=1239 | loss=0.1176 | lr=9.19e-06 | epoch=2.6485
[train] step=1240 | loss=0.1074 | lr=9.14e-06 | epoch=2.6506
[train] step=1241 | loss=0.0894 | lr=9.08e-06 | epoch=2.6528
[train] step=1242 | loss=0.1222 | lr=9.03e-06 | epoch=2.6549
[train] step=1243 | loss=0.0933 | lr=8.97e-06 | epoch=2.6570
[train] step=1244 | loss=0.1189 | lr=8.92e-06 | epoch=2.6592
[train] step=1245 | loss=0.0889 | lr=8.86e-06 | epoch=2.6613
[train] step=1246 | loss=0.0927 | lr=8.81e-06 | epoch=2.6635
[train] step=1247 | loss=0.1130 | lr=8.75e-06 | epoch=2.6656
[train] step=1248 | loss=0.0983 | lr=8.69e-06 | epoch=2.6677
[train] step=1249 | loss=0.0857 | lr=8.64e-06 | epoch=2.6699
[train] step=1250 | loss=0.0783 | lr=8.58e-06 | epoch=2.6720
[train] step=1251 | loss=0.1267 | lr=8.53e-06 | epoch=2.6742
[train] step=1252 | loss=0.0960 | lr=8.47e-06 | epoch=2.6763
[train] step=1253 | loss=0.1061 | lr=8.42e-06 | epoch=2.6784
[train] step=1254 | loss=0.0997 | lr=8.36e-06 | epoch=2.6806
[train] step=1255 | loss=0.0956 | lr=8.31e-06 | epoch=2.6827
[train] step=1256 | loss=0.0908 | lr=8.25e-06 | epoch=2.6849
[train] step=1257 | loss=0.0769 | lr=8.20e-06 | epoch=2.6870
[train] step=1258 | loss=0.1070 | lr=8.14e-06 | epoch=2.6891
[train] step=1259 | loss=0.1203 | lr=8.09e-06 | epoch=2.6913
[train] step=1260 | loss=0.0954 | lr=8.03e-06 | epoch=2.6934
[train] step=1261 | loss=0.0988 | lr=7.97e-06 | epoch=2.6956
[train] step=1262 | loss=0.1330 | lr=7.92e-06 | epoch=2.6977
[train] step=1263 | loss=0.0903 | lr=7.86e-06 | epoch=2.6998
[train] step=1264 | loss=0.0977 | lr=7.81e-06 | epoch=2.7020
[train] step=1265 | loss=0.1058 | lr=7.75e-06 | epoch=2.7041
[train] step=1266 | loss=0.1272 | lr=7.70e-06 | epoch=2.7063
[train] step=1267 | loss=0.1027 | lr=7.64e-06 | epoch=2.7084
[train] step=1268 | loss=0.1282 | lr=7.59e-06 | epoch=2.7105
[train] step=1269 | loss=0.1284 | lr=7.53e-06 | epoch=2.7127
[train] step=1270 | loss=0.0953 | lr=7.48e-06 | epoch=2.7148
[train] step=1271 | loss=0.0875 | lr=7.42e-06 | epoch=2.7170
[train] step=1272 | loss=0.0909 | lr=7.37e-06 | epoch=2.7191
[train] step=1273 | loss=0.1039 | lr=7.31e-06 | epoch=2.7212
[train] step=1274 | loss=0.0945 | lr=7.25e-06 | epoch=2.7234
[train] step=1275 | loss=0.1052 | lr=7.20e-06 | epoch=2.7255
[train] step=1276 | loss=0.0752 | lr=7.14e-06 | epoch=2.7277
[train] step=1277 | loss=0.1023 | lr=7.09e-06 | epoch=2.7298
[train] step=1278 | loss=0.0993 | lr=7.03e-06 | epoch=2.7319
[train] step=1279 | loss=0.1243 | lr=6.98e-06 | epoch=2.7341
[train] step=1280 | loss=0.1058 | lr=6.92e-06 | epoch=2.7362
[train] step=1281 | loss=0.0951 | lr=6.87e-06 | epoch=2.7384
[train] step=1282 | loss=0.1030 | lr=6.81e-06 | epoch=2.7405
[train] step=1283 | loss=0.0935 | lr=6.76e-06 | epoch=2.7426
[train] step=1284 | loss=0.1269 | lr=6.70e-06 | epoch=2.7448
[train] step=1285 | loss=0.1024 | lr=6.65e-06 | epoch=2.7469
[train] step=1286 | loss=0.0842 | lr=6.59e-06 | epoch=2.7491
[train] step=1287 | loss=0.1012 | lr=6.53e-06 | epoch=2.7512
[train] step=1288 | loss=0.1083 | lr=6.48e-06 | epoch=2.7533
[train] step=1289 | loss=0.0966 | lr=6.42e-06 | epoch=2.7555
[train] step=1290 | loss=0.1251 | lr=6.37e-06 | epoch=2.7576
[train] step=1291 | loss=0.0874 | lr=6.31e-06 | epoch=2.7598
[train] step=1292 | loss=0.1036 | lr=6.26e-06 | epoch=2.7619
[train] step=1293 | loss=0.0889 | lr=6.20e-06 | epoch=2.7640
[train] step=1294 | loss=0.1168 | lr=6.15e-06 | epoch=2.7662
[train] step=1295 | loss=0.1043 | lr=6.09e-06 | epoch=2.7683
[train] step=1296 | loss=0.1276 | lr=6.04e-06 | epoch=2.7705
[train] step=1297 | loss=0.0966 | lr=5.98e-06 | epoch=2.7726
[train] step=1298 | loss=0.0840 | lr=5.93e-06 | epoch=2.7747
[train] step=1299 | loss=0.1109 | lr=5.87e-06 | epoch=2.7769
[train] step=1300 | loss=0.0964 | lr=5.81e-06 | epoch=2.7790
[train] step=1301 | loss=0.1045 | lr=5.76e-06 | epoch=2.7812
[train] step=1302 | loss=0.1021 | lr=5.70e-06 | epoch=2.7833
[train] step=1303 | loss=0.1067 | lr=5.65e-06 | epoch=2.7854
[train] step=1304 | loss=0.1014 | lr=5.59e-06 | epoch=2.7876
[train] step=1305 | loss=0.1183 | lr=5.54e-06 | epoch=2.7897
[train] step=1306 | loss=0.1137 | lr=5.48e-06 | epoch=2.7919
[train] step=1307 | loss=0.0829 | lr=5.43e-06 | epoch=2.7940
[train] step=1308 | loss=0.0917 | lr=5.37e-06 | epoch=2.7961
[train] step=1309 | loss=0.1098 | lr=5.32e-06 | epoch=2.7983
[train] step=1310 | loss=0.0920 | lr=5.26e-06 | epoch=2.8004
[train] step=1311 | loss=0.1183 | lr=5.21e-06 | epoch=2.8026
[train] step=1312 | loss=0.0974 | lr=5.15e-06 | epoch=2.8047
[train] step=1313 | loss=0.1050 | lr=5.09e-06 | epoch=2.8068
[train] step=1314 | loss=0.0962 | lr=5.04e-06 | epoch=2.8090
[train] step=1315 | loss=0.1088 | lr=4.98e-06 | epoch=2.8111
[train] step=1316 | loss=0.0944 | lr=4.93e-06 | epoch=2.8133
[train] step=1317 | loss=0.1101 | lr=4.87e-06 | epoch=2.8154
[train] step=1318 | loss=0.1026 | lr=4.82e-06 | epoch=2.8175
[train] step=1319 | loss=0.0773 | lr=4.76e-06 | epoch=2.8197
[train] step=1320 | loss=0.0952 | lr=4.71e-06 | epoch=2.8218
[train] step=1321 | loss=0.0927 | lr=4.65e-06 | epoch=2.8240
[train] step=1322 | loss=0.0804 | lr=4.60e-06 | epoch=2.8261
[train] step=1323 | loss=0.0839 | lr=4.54e-06 | epoch=2.8283
[train] step=1324 | loss=0.1072 | lr=4.49e-06 | epoch=2.8304
[train] step=1325 | loss=0.0848 | lr=4.43e-06 | epoch=2.8325
[train] step=1326 | loss=0.0974 | lr=4.37e-06 | epoch=2.8347
[train] step=1327 | loss=0.1043 | lr=4.32e-06 | epoch=2.8368
[train] step=1328 | loss=0.1089 | lr=4.26e-06 | epoch=2.8390
[train] step=1329 | loss=0.1070 | lr=4.21e-06 | epoch=2.8411
[train] step=1330 | loss=0.1131 | lr=4.15e-06 | epoch=2.8432
[train] step=1331 | loss=0.0832 | lr=4.10e-06 | epoch=2.8454
[train] step=1332 | loss=0.1367 | lr=4.04e-06 | epoch=2.8475
[train] step=1333 | loss=0.1003 | lr=3.99e-06 | epoch=2.8497
[train] step=1334 | loss=0.0979 | lr=3.93e-06 | epoch=2.8518
[train] step=1335 | loss=0.1221 | lr=3.88e-06 | epoch=2.8539
[train] step=1336 | loss=0.0879 | lr=3.82e-06 | epoch=2.8561
[train] step=1337 | loss=0.1016 | lr=3.77e-06 | epoch=2.8582
[train] step=1338 | loss=0.1063 | lr=3.71e-06 | epoch=2.8604
[train] step=1339 | loss=0.1347 | lr=3.66e-06 | epoch=2.8625
[train] step=1340 | loss=0.1176 | lr=3.60e-06 | epoch=2.8646
[train] step=1341 | loss=0.0867 | lr=3.54e-06 | epoch=2.8668
[train] step=1342 | loss=0.1019 | lr=3.49e-06 | epoch=2.8689
[train] step=1343 | loss=0.1117 | lr=3.43e-06 | epoch=2.8711
[train] step=1344 | loss=0.0885 | lr=3.38e-06 | epoch=2.8732
[train] step=1345 | loss=0.1007 | lr=3.32e-06 | epoch=2.8753
[train] step=1346 | loss=0.1175 | lr=3.27e-06 | epoch=2.8775
[train] step=1347 | loss=0.1176 | lr=3.21e-06 | epoch=2.8796
[train] step=1348 | loss=0.1233 | lr=3.16e-06 | epoch=2.8818
[train] step=1349 | loss=0.0876 | lr=3.10e-06 | epoch=2.8839
[train] step=1350 | loss=0.1123 | lr=3.05e-06 | epoch=2.8860
[train] step=1351 | loss=0.1144 | lr=2.99e-06 | epoch=2.8882
[train] step=1352 | loss=0.1013 | lr=2.94e-06 | epoch=2.8903
[train] step=1353 | loss=0.1012 | lr=2.88e-06 | epoch=2.8925
[train] step=1354 | loss=0.0910 | lr=2.82e-06 | epoch=2.8946
[train] step=1355 | loss=0.1156 | lr=2.77e-06 | epoch=2.8967
[train] step=1356 | loss=0.0901 | lr=2.71e-06 | epoch=2.8989
[train] step=1357 | loss=0.1163 | lr=2.66e-06 | epoch=2.9010
[train] step=1358 | loss=0.0897 | lr=2.60e-06 | epoch=2.9032
[train] step=1359 | loss=0.0996 | lr=2.55e-06 | epoch=2.9053
[train] step=1360 | loss=0.0962 | lr=2.49e-06 | epoch=2.9074
[train] step=1361 | loss=0.0894 | lr=2.44e-06 | epoch=2.9096
[train] step=1362 | loss=0.1035 | lr=2.38e-06 | epoch=2.9117
[train] step=1363 | loss=0.0908 | lr=2.33e-06 | epoch=2.9139
[train] step=1364 | loss=0.1006 | lr=2.27e-06 | epoch=2.9160
[train] step=1365 | loss=0.1201 | lr=2.22e-06 | epoch=2.9181
[train] step=1366 | loss=0.1130 | lr=2.16e-06 | epoch=2.9203
[train] step=1367 | loss=0.1178 | lr=2.10e-06 | epoch=2.9224
[train] step=1368 | loss=0.0666 | lr=2.05e-06 | epoch=2.9246
[train] step=1369 | loss=0.0881 | lr=1.99e-06 | epoch=2.9267
[train] step=1370 | loss=0.0918 | lr=1.94e-06 | epoch=2.9288
[train] step=1371 | loss=0.0741 | lr=1.88e-06 | epoch=2.9310
[train] step=1372 | loss=0.1064 | lr=1.83e-06 | epoch=2.9331
[train] step=1373 | loss=0.1075 | lr=1.77e-06 | epoch=2.9353
[train] step=1374 | loss=0.0889 | lr=1.72e-06 | epoch=2.9374
[train] step=1375 | loss=0.1277 | lr=1.66e-06 | epoch=2.9395
[train] step=1376 | loss=0.1045 | lr=1.61e-06 | epoch=2.9417
[train] step=1377 | loss=0.0865 | lr=1.55e-06 | epoch=2.9438
[train] step=1378 | loss=0.1149 | lr=1.50e-06 | epoch=2.9460
[train] step=1379 | loss=0.0895 | lr=1.44e-06 | epoch=2.9481
[train] step=1380 | loss=0.1140 | lr=1.38e-06 | epoch=2.9502
[train] step=1381 | loss=0.1005 | lr=1.33e-06 | epoch=2.9524
[train] step=1382 | loss=0.0833 | lr=1.27e-06 | epoch=2.9545
[train] step=1383 | loss=0.0877 | lr=1.22e-06 | epoch=2.9567
[train] step=1384 | loss=0.0907 | lr=1.16e-06 | epoch=2.9588
[train] step=1385 | loss=0.1072 | lr=1.11e-06 | epoch=2.9609
[train] step=1386 | loss=0.0960 | lr=1.05e-06 | epoch=2.9631
[train] step=1387 | loss=0.1098 | lr=9.97e-07 | epoch=2.9652
[train] step=1388 | loss=0.1094 | lr=9.41e-07 | epoch=2.9674
[train] step=1389 | loss=0.1066 | lr=8.86e-07 | epoch=2.9695
[train] step=1390 | loss=0.1059 | lr=8.31e-07 | epoch=2.9716
[train] step=1391 | loss=0.1017 | lr=7.75e-07 | epoch=2.9738
[train] step=1392 | loss=0.0935 | lr=7.20e-07 | epoch=2.9759
[train] step=1393 | loss=0.0894 | lr=6.65e-07 | epoch=2.9781
[train] step=1394 | loss=0.0923 | lr=6.09e-07 | epoch=2.9802
[train] step=1395 | loss=0.0871 | lr=5.54e-07 | epoch=2.9823
[train] step=1396 | loss=0.0811 | lr=4.98e-07 | epoch=2.9845
[train] step=1397 | loss=0.1039 | lr=4.43e-07 | epoch=2.9866
[train] step=1398 | loss=0.1040 | lr=3.88e-07 | epoch=2.9888

Saving model checkpoint to output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1398
2026-04-06 04:46:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:46:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 04:46:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:46:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1398\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1398\tokenizer_config.json

[train] step=1399 | loss=0.1059 | lr=3.32e-07 | epoch=2.9909
[train] step=1400 | loss=0.1167 | lr=2.77e-07 | epoch=2.9930
[train] step=1401 | loss=0.0868 | lr=2.22e-07 | epoch=2.9952
[train] step=1402 | loss=0.0991 | lr=1.66e-07 | epoch=2.9973
[train] step=1403 | loss=0.1321 | lr=1.11e-07 | epoch=2.9995
[train] step=1404 | loss=0.0850 | lr=5.54e-08 | epoch=3.0000

Saving model checkpoint to output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1404
2026-04-06 04:47:04 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:04 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 04:47:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1404\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\checkpoint-1404\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=1404 | epoch=3.0000
[train] finished | global_step=1404

Saving model checkpoint to output\fine_tune\run_003_lr7e-5_r16_a32_ep3
2026-04-06 04:47:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 04:47:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:05 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\tokenizer_config.json
chat template saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_003_lr7e-5_r16_a32_ep3\tokenizer_config.json
2026-04-06 04:47:05 | INFO     | root | Done run 4/5: C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_003_lr7e-5_r16_a32_ep3

=== Run 5/5  run_004_lr1e-4_r32_a64_ep3  merged={'learning_rate': 0.0001, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-06 04:47:06 | INFO     | root | Logging to C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_004_lr1e-4_r32_a64_ep3\training_run.log
2026-04-06 04:47:06 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:06 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 04:47:06 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:06 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-06 04:47:06 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-06 04:47:07 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-06 04:47:07 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"
2026-04-06 04:47:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-06 04:47:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9130.68it/s]
2026-04-06 04:47:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": false,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

2026-04-06 04:47:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2-1.5B.
2026-04-06 04:47:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:47:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-06 04:47:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 04:47:09 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-06 04:47:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-06 04:47:10 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-06 04:47:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-06 04:47:12 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 8,716,288

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.6833 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.7304 | lr=7.14e-07 | epoch=0.0043
[train] step=3 | loss=1.7381 | lr=1.43e-06 | epoch=0.0064
[train] step=4 | loss=1.7176 | lr=2.14e-06 | epoch=0.0086
[train] step=5 | loss=1.6846 | lr=2.86e-06 | epoch=0.0107
[train] step=6 | loss=1.7037 | lr=3.57e-06 | epoch=0.0128
[train] step=7 | loss=1.6298 | lr=4.29e-06 | epoch=0.0150
[train] step=8 | loss=1.5986 | lr=5.00e-06 | epoch=0.0171
[train] step=9 | loss=1.6847 | lr=5.71e-06 | epoch=0.0193
[train] step=10 | loss=1.6830 | lr=6.43e-06 | epoch=0.0214
[train] step=11 | loss=1.7218 | lr=7.14e-06 | epoch=0.0235
[train] step=12 | loss=1.7960 | lr=7.86e-06 | epoch=0.0257
[train] step=13 | loss=1.6604 | lr=8.57e-06 | epoch=0.0278
[train] step=14 | loss=1.6980 | lr=9.29e-06 | epoch=0.0300
[train] step=15 | loss=1.7319 | lr=1.00e-05 | epoch=0.0321
[train] step=16 | loss=1.6674 | lr=1.07e-05 | epoch=0.0342
[train] step=17 | loss=1.6322 | lr=1.14e-05 | epoch=0.0364
[train] step=18 | loss=1.6368 | lr=1.21e-05 | epoch=0.0385
[train] step=19 | loss=1.6021 | lr=1.29e-05 | epoch=0.0407
[train] step=20 | loss=1.6009 | lr=1.36e-05 | epoch=0.0428
[train] step=21 | loss=1.5228 | lr=1.43e-05 | epoch=0.0449
[train] step=22 | loss=1.5471 | lr=1.50e-05 | epoch=0.0471
[train] step=23 | loss=1.5116 | lr=1.57e-05 | epoch=0.0492
[train] step=24 | loss=1.5398 | lr=1.64e-05 | epoch=0.0514
[train] step=25 | loss=1.4664 | lr=1.71e-05 | epoch=0.0535
[train] step=26 | loss=1.5617 | lr=1.79e-05 | epoch=0.0556
[train] step=27 | loss=1.4123 | lr=1.86e-05 | epoch=0.0578
[train] step=28 | loss=1.4248 | lr=1.93e-05 | epoch=0.0599
[train] step=29 | loss=1.3990 | lr=2.00e-05 | epoch=0.0621
[train] step=30 | loss=1.4270 | lr=2.07e-05 | epoch=0.0642
[train] step=31 | loss=1.3182 | lr=2.14e-05 | epoch=0.0663
[train] step=32 | loss=1.3244 | lr=2.21e-05 | epoch=0.0685
[train] step=33 | loss=1.3183 | lr=2.29e-05 | epoch=0.0706
[train] step=34 | loss=1.3078 | lr=2.36e-05 | epoch=0.0728
[train] step=35 | loss=1.3785 | lr=2.43e-05 | epoch=0.0749
[train] step=36 | loss=1.2665 | lr=2.50e-05 | epoch=0.0770
[train] step=37 | loss=1.2629 | lr=2.57e-05 | epoch=0.0792
[train] step=38 | loss=1.2147 | lr=2.64e-05 | epoch=0.0813
[train] step=39 | loss=1.1596 | lr=2.71e-05 | epoch=0.0835
[train] step=40 | loss=1.2094 | lr=2.79e-05 | epoch=0.0856
[train] step=41 | loss=1.1127 | lr=2.86e-05 | epoch=0.0877
[train] step=42 | loss=1.0886 | lr=2.93e-05 | epoch=0.0899
[train] step=43 | loss=1.0429 | lr=3.00e-05 | epoch=0.0920
[train] step=44 | loss=0.9637 | lr=3.07e-05 | epoch=0.0942
[train] step=45 | loss=0.9780 | lr=3.14e-05 | epoch=0.0963
[train] step=46 | loss=0.8994 | lr=3.21e-05 | epoch=0.0984
[train] step=47 | loss=0.8732 | lr=3.29e-05 | epoch=0.1006
[train] step=48 | loss=0.7681 | lr=3.36e-05 | epoch=0.1027
[train] step=49 | loss=0.7571 | lr=3.43e-05 | epoch=0.1049
[train] step=50 | loss=0.7512 | lr=3.50e-05 | epoch=0.1070
[train] step=51 | loss=0.6895 | lr=3.57e-05 | epoch=0.1091
[train] step=52 | loss=0.6155 | lr=3.64e-05 | epoch=0.1113
[train] step=53 | loss=0.6042 | lr=3.71e-05 | epoch=0.1134
[train] step=54 | loss=0.5319 | lr=3.79e-05 | epoch=0.1156
[train] step=55 | loss=0.4303 | lr=3.86e-05 | epoch=0.1177
[train] step=56 | loss=0.4108 | lr=3.93e-05 | epoch=0.1199
[train] step=57 | loss=0.3365 | lr=4.00e-05 | epoch=0.1220
[train] step=58 | loss=0.3390 | lr=4.07e-05 | epoch=0.1241
[train] step=59 | loss=0.2847 | lr=4.14e-05 | epoch=0.1263
[train] step=60 | loss=0.2676 | lr=4.21e-05 | epoch=0.1284
[train] step=61 | loss=0.2386 | lr=4.29e-05 | epoch=0.1306
[train] step=62 | loss=0.2216 | lr=4.36e-05 | epoch=0.1327
[train] step=63 | loss=0.2140 | lr=4.43e-05 | epoch=0.1348
[train] step=64 | loss=0.1928 | lr=4.50e-05 | epoch=0.1370
[train] step=65 | loss=0.1927 | lr=4.57e-05 | epoch=0.1391
[train] step=66 | loss=0.1865 | lr=4.64e-05 | epoch=0.1413
[train] step=67 | loss=0.1751 | lr=4.71e-05 | epoch=0.1434
[train] step=68 | loss=0.1698 | lr=4.79e-05 | epoch=0.1455
[train] step=69 | loss=0.1842 | lr=4.86e-05 | epoch=0.1477
[train] step=70 | loss=0.1684 | lr=4.93e-05 | epoch=0.1498
[train] step=71 | loss=0.1583 | lr=5.00e-05 | epoch=0.1520
[train] step=72 | loss=0.1460 | lr=5.07e-05 | epoch=0.1541
[train] step=73 | loss=0.1594 | lr=5.14e-05 | epoch=0.1562
[train] step=74 | loss=0.1475 | lr=5.21e-05 | epoch=0.1584
[train] step=75 | loss=0.1449 | lr=5.29e-05 | epoch=0.1605
[train] step=76 | loss=0.1331 | lr=5.36e-05 | epoch=0.1627
[train] step=77 | loss=0.1273 | lr=5.43e-05 | epoch=0.1648
[train] step=78 | loss=0.1226 | lr=5.50e-05 | epoch=0.1669
[train] step=79 | loss=0.1223 | lr=5.57e-05 | epoch=0.1691
[train] step=80 | loss=0.1566 | lr=5.64e-05 | epoch=0.1712
[train] step=81 | loss=0.1514 | lr=5.71e-05 | epoch=0.1734
[train] step=82 | loss=0.1305 | lr=5.79e-05 | epoch=0.1755
[train] step=83 | loss=0.1223 | lr=5.86e-05 | epoch=0.1776
[train] step=84 | loss=0.1186 | lr=5.93e-05 | epoch=0.1798
[train] step=85 | loss=0.1422 | lr=6.00e-05 | epoch=0.1819
[train] step=86 | loss=0.1459 | lr=6.07e-05 | epoch=0.1841
[train] step=87 | loss=0.1091 | lr=6.14e-05 | epoch=0.1862
[train] step=88 | loss=0.1384 | lr=6.21e-05 | epoch=0.1883
[train] step=89 | loss=0.1183 | lr=6.29e-05 | epoch=0.1905
[train] step=90 | loss=0.1143 | lr=6.36e-05 | epoch=0.1926
[train] step=91 | loss=0.1138 | lr=6.43e-05 | epoch=0.1948
[train] step=92 | loss=0.1343 | lr=6.50e-05 | epoch=0.1969
[train] step=93 | loss=0.1237 | lr=6.57e-05 | epoch=0.1990
[train] step=94 | loss=0.1153 | lr=6.64e-05 | epoch=0.2012
[train] step=95 | loss=0.1182 | lr=6.71e-05 | epoch=0.2033
[train] step=96 | loss=0.1175 | lr=6.79e-05 | epoch=0.2055
[train] step=97 | loss=0.1295 | lr=6.86e-05 | epoch=0.2076
[train] step=98 | loss=0.1203 | lr=6.93e-05 | epoch=0.2097
[train] step=99 | loss=0.1025 | lr=7.00e-05 | epoch=0.2119
[train] step=100 | loss=0.1173 | lr=7.07e-05 | epoch=0.2140
[train] step=101 | loss=0.1016 | lr=7.14e-05 | epoch=0.2162
[train] step=102 | loss=0.1505 | lr=7.21e-05 | epoch=0.2183
[train] step=103 | loss=0.1103 | lr=7.29e-05 | epoch=0.2204
[train] step=104 | loss=0.1284 | lr=7.36e-05 | epoch=0.2226
[train] step=105 | loss=0.1320 | lr=7.43e-05 | epoch=0.2247
[train] step=106 | loss=0.1234 | lr=7.50e-05 | epoch=0.2269
[train] step=107 | loss=0.1336 | lr=7.57e-05 | epoch=0.2290
[train] step=108 | loss=0.1055 | lr=7.64e-05 | epoch=0.2311
[train] step=109 | loss=0.1015 | lr=7.71e-05 | epoch=0.2333
[train] step=110 | loss=0.1421 | lr=7.79e-05 | epoch=0.2354
[train] step=111 | loss=0.1103 | lr=7.86e-05 | epoch=0.2376
[train] step=112 | loss=0.1066 | lr=7.93e-05 | epoch=0.2397
[train] step=113 | loss=0.1049 | lr=8.00e-05 | epoch=0.2418
[train] step=114 | loss=0.1354 | lr=8.07e-05 | epoch=0.2440
[train] step=115 | loss=0.1183 | lr=8.14e-05 | epoch=0.2461
[train] step=116 | loss=0.1285 | lr=8.21e-05 | epoch=0.2483
[train] step=117 | loss=0.1187 | lr=8.29e-05 | epoch=0.2504
[train] step=118 | loss=0.1052 | lr=8.36e-05 | epoch=0.2525
[train] step=119 | loss=0.1074 | lr=8.43e-05 | epoch=0.2547
[train] step=120 | loss=0.1029 | lr=8.50e-05 | epoch=0.2568
[train] step=121 | loss=0.1114 | lr=8.57e-05 | epoch=0.2590
[train] step=122 | loss=0.1300 | lr=8.64e-05 | epoch=0.2611
[train] step=123 | loss=0.1359 | lr=8.71e-05 | epoch=0.2632
[train] step=124 | loss=0.1065 | lr=8.79e-05 | epoch=0.2654
[train] step=125 | loss=0.1260 | lr=8.86e-05 | epoch=0.2675
[train] step=126 | loss=0.1145 | lr=8.93e-05 | epoch=0.2697
[train] step=127 | loss=0.1216 | lr=9.00e-05 | epoch=0.2718
[train] step=128 | loss=0.1025 | lr=9.07e-05 | epoch=0.2739
[train] step=129 | loss=0.1195 | lr=9.14e-05 | epoch=0.2761
[train] step=130 | loss=0.1183 | lr=9.21e-05 | epoch=0.2782
[train] step=131 | loss=0.1371 | lr=9.29e-05 | epoch=0.2804
[train] step=132 | loss=0.1190 | lr=9.36e-05 | epoch=0.2825
[train] step=133 | loss=0.1212 | lr=9.43e-05 | epoch=0.2846
[train] step=134 | loss=0.1098 | lr=9.50e-05 | epoch=0.2868
[train] step=135 | loss=0.1230 | lr=9.57e-05 | epoch=0.2889
[train] step=136 | loss=0.1134 | lr=9.64e-05 | epoch=0.2911
[train] step=137 | loss=0.1341 | lr=9.71e-05 | epoch=0.2932
[train] step=138 | loss=0.1004 | lr=9.79e-05 | epoch=0.2953
[train] step=139 | loss=0.1013 | lr=9.86e-05 | epoch=0.2975
[train] step=140 | loss=0.1146 | lr=9.93e-05 | epoch=0.2996
[train] step=141 | loss=0.1681 | lr=1.00e-04 | epoch=0.3018
[train] step=142 | loss=0.1128 | lr=9.99e-05 | epoch=0.3039
[train] step=143 | loss=0.1202 | lr=9.98e-05 | epoch=0.3060
[train] step=144 | loss=0.1042 | lr=9.98e-05 | epoch=0.3082
[train] step=145 | loss=0.1176 | lr=9.97e-05 | epoch=0.3103
[train] step=146 | loss=0.1112 | lr=9.96e-05 | epoch=0.3125
[train] step=147 | loss=0.1194 | lr=9.95e-05 | epoch=0.3146
[train] step=148 | loss=0.1006 | lr=9.94e-05 | epoch=0.3167
[train] step=149 | loss=0.1126 | lr=9.94e-05 | epoch=0.3189
[train] step=150 | loss=0.0939 | lr=9.93e-05 | epoch=0.3210
[train] step=151 | loss=0.1335 | lr=9.92e-05 | epoch=0.3232
[train] step=152 | loss=0.0950 | lr=9.91e-05 | epoch=0.3253
[train] step=153 | loss=0.1020 | lr=9.91e-05 | epoch=0.3274
[train] step=154 | loss=0.1076 | lr=9.90e-05 | epoch=0.3296
[train] step=155 | loss=0.0872 | lr=9.89e-05 | epoch=0.3317
[train] step=156 | loss=0.1255 | lr=9.88e-05 | epoch=0.3339
[train] step=157 | loss=0.1453 | lr=9.87e-05 | epoch=0.3360
[train] step=158 | loss=0.1095 | lr=9.87e-05 | epoch=0.3381
[train] step=159 | loss=0.1024 | lr=9.86e-05 | epoch=0.3403
[train] step=160 | loss=0.1408 | lr=9.85e-05 | epoch=0.3424
[train] step=161 | loss=0.0990 | lr=9.84e-05 | epoch=0.3446
[train] step=162 | loss=0.0967 | lr=9.83e-05 | epoch=0.3467
[train] step=163 | loss=0.1185 | lr=9.83e-05 | epoch=0.3488
[train] step=164 | loss=0.1320 | lr=9.82e-05 | epoch=0.3510
[train] step=165 | loss=0.1147 | lr=9.81e-05 | epoch=0.3531
[train] step=166 | loss=0.1264 | lr=9.80e-05 | epoch=0.3553
[train] step=167 | loss=0.0976 | lr=9.79e-05 | epoch=0.3574
[train] step=168 | loss=0.1007 | lr=9.79e-05 | epoch=0.3596
[train] step=169 | loss=0.1122 | lr=9.78e-05 | epoch=0.3617
[train] step=170 | loss=0.1025 | lr=9.77e-05 | epoch=0.3638
[train] step=171 | loss=0.1154 | lr=9.76e-05 | epoch=0.3660
[train] step=172 | loss=0.1158 | lr=9.75e-05 | epoch=0.3681
[train] step=173 | loss=0.0937 | lr=9.75e-05 | epoch=0.3703
[train] step=174 | loss=0.1129 | lr=9.74e-05 | epoch=0.3724
[train] step=175 | loss=0.1069 | lr=9.73e-05 | epoch=0.3745
[train] step=176 | loss=0.1380 | lr=9.72e-05 | epoch=0.3767
[train] step=177 | loss=0.0860 | lr=9.72e-05 | epoch=0.3788
[train] step=178 | loss=0.0999 | lr=9.71e-05 | epoch=0.3810
[train] step=179 | loss=0.1052 | lr=9.70e-05 | epoch=0.3831
[train] step=180 | loss=0.1079 | lr=9.69e-05 | epoch=0.3852
[train] step=181 | loss=0.1079 | lr=9.68e-05 | epoch=0.3874
[train] step=182 | loss=0.0888 | lr=9.68e-05 | epoch=0.3895
[train] step=183 | loss=0.0814 | lr=9.67e-05 | epoch=0.3917
[train] step=184 | loss=0.1302 | lr=9.66e-05 | epoch=0.3938
[train] step=185 | loss=0.0966 | lr=9.65e-05 | epoch=0.3959
[train] step=186 | loss=0.0910 | lr=9.64e-05 | epoch=0.3981
[train] step=187 | loss=0.1021 | lr=9.64e-05 | epoch=0.4002
[train] step=188 | loss=0.1337 | lr=9.63e-05 | epoch=0.4024
[train] step=189 | loss=0.1218 | lr=9.62e-05 | epoch=0.4045
[train] step=190 | loss=0.1288 | lr=9.61e-05 | epoch=0.4066
[train] step=191 | loss=0.1005 | lr=9.60e-05 | epoch=0.4088
[train] step=192 | loss=0.1075 | lr=9.60e-05 | epoch=0.4109
[train] step=193 | loss=0.1221 | lr=9.59e-05 | epoch=0.4131
[train] step=194 | loss=0.1050 | lr=9.58e-05 | epoch=0.4152
[train] step=195 | loss=0.1186 | lr=9.57e-05 | epoch=0.4173
[train] step=196 | loss=0.1167 | lr=9.56e-05 | epoch=0.4195
[train] step=197 | loss=0.0925 | lr=9.56e-05 | epoch=0.4216
[train] step=198 | loss=0.1372 | lr=9.55e-05 | epoch=0.4238
[train] step=199 | loss=0.1239 | lr=9.54e-05 | epoch=0.4259
[train] step=200 | loss=0.1038 | lr=9.53e-05 | epoch=0.4280
[train] step=201 | loss=0.1064 | lr=9.53e-05 | epoch=0.4302
[train] step=202 | loss=0.1329 | lr=9.52e-05 | epoch=0.4323
[train] step=203 | loss=0.1078 | lr=9.51e-05 | epoch=0.4345
[train] step=204 | loss=0.1193 | lr=9.50e-05 | epoch=0.4366
[train] step=205 | loss=0.0946 | lr=9.49e-05 | epoch=0.4387
[train] step=206 | loss=0.1051 | lr=9.49e-05 | epoch=0.4409
[train] step=207 | loss=0.1130 | lr=9.48e-05 | epoch=0.4430
[train] step=208 | loss=0.0967 | lr=9.47e-05 | epoch=0.4452
[train] step=209 | loss=0.1169 | lr=9.46e-05 | epoch=0.4473
[train] step=210 | loss=0.1054 | lr=9.45e-05 | epoch=0.4494
[train] step=211 | loss=0.1052 | lr=9.45e-05 | epoch=0.4516
[train] step=212 | loss=0.1100 | lr=9.44e-05 | epoch=0.4537
[train] step=213 | loss=0.1436 | lr=9.43e-05 | epoch=0.4559
[train] step=214 | loss=0.1063 | lr=9.42e-05 | epoch=0.4580
[train] step=215 | loss=0.1232 | lr=9.41e-05 | epoch=0.4601
[train] step=216 | loss=0.1027 | lr=9.41e-05 | epoch=0.4623
[train] step=217 | loss=0.1211 | lr=9.40e-05 | epoch=0.4644
[train] step=218 | loss=0.1012 | lr=9.39e-05 | epoch=0.4666
[train] step=219 | loss=0.0964 | lr=9.38e-05 | epoch=0.4687
[train] step=220 | loss=0.0911 | lr=9.38e-05 | epoch=0.4708
[train] step=221 | loss=0.0969 | lr=9.37e-05 | epoch=0.4730
[train] step=222 | loss=0.1201 | lr=9.36e-05 | epoch=0.4751
[train] step=223 | loss=0.1207 | lr=9.35e-05 | epoch=0.4773
[train] step=224 | loss=0.0978 | lr=9.34e-05 | epoch=0.4794
[train] step=225 | loss=0.1219 | lr=9.34e-05 | epoch=0.4815
[train] step=226 | loss=0.1142 | lr=9.33e-05 | epoch=0.4837
[train] step=227 | loss=0.1168 | lr=9.32e-05 | epoch=0.4858
[train] step=228 | loss=0.1012 | lr=9.31e-05 | epoch=0.4880
[train] step=229 | loss=0.1144 | lr=9.30e-05 | epoch=0.4901
[train] step=230 | loss=0.1045 | lr=9.30e-05 | epoch=0.4922
[train] step=231 | loss=0.1238 | lr=9.29e-05 | epoch=0.4944
[train] step=232 | loss=0.1083 | lr=9.28e-05 | epoch=0.4965
[train] step=233 | loss=0.1212 | lr=9.27e-05 | epoch=0.4987

Saving model checkpoint to output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-233
2026-04-06 04:56:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:56:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 04:56:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 04:56:37 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-233\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-233\tokenizer_config.json

[train] step=234 | loss=0.1102 | lr=9.26e-05 | epoch=0.5008
[train] step=235 | loss=0.0977 | lr=9.26e-05 | epoch=0.5029
[train] step=236 | loss=0.1074 | lr=9.25e-05 | epoch=0.5051
[train] step=237 | loss=0.1115 | lr=9.24e-05 | epoch=0.5072
[train] step=238 | loss=0.1104 | lr=9.23e-05 | epoch=0.5094
[train] step=239 | loss=0.1036 | lr=9.22e-05 | epoch=0.5115
[train] step=240 | loss=0.1049 | lr=9.22e-05 | epoch=0.5136
[train] step=241 | loss=0.1116 | lr=9.21e-05 | epoch=0.5158
[train] step=242 | loss=0.0976 | lr=9.20e-05 | epoch=0.5179
[train] step=243 | loss=0.1307 | lr=9.19e-05 | epoch=0.5201
[train] step=244 | loss=0.1271 | lr=9.19e-05 | epoch=0.5222
[train] step=245 | loss=0.1001 | lr=9.18e-05 | epoch=0.5243
[train] step=246 | loss=0.1313 | lr=9.17e-05 | epoch=0.5265
[train] step=247 | loss=0.1227 | lr=9.16e-05 | epoch=0.5286
[train] step=248 | loss=0.0971 | lr=9.15e-05 | epoch=0.5308
[train] step=249 | loss=0.0916 | lr=9.15e-05 | epoch=0.5329
[train] step=250 | loss=0.1060 | lr=9.14e-05 | epoch=0.5350
[train] step=251 | loss=0.1038 | lr=9.13e-05 | epoch=0.5372
[train] step=252 | loss=0.1113 | lr=9.12e-05 | epoch=0.5393
[train] step=253 | loss=0.1237 | lr=9.11e-05 | epoch=0.5415
[train] step=254 | loss=0.1059 | lr=9.11e-05 | epoch=0.5436
[train] step=255 | loss=0.1069 | lr=9.10e-05 | epoch=0.5457
[train] step=256 | loss=0.0921 | lr=9.09e-05 | epoch=0.5479
[train] step=257 | loss=0.0996 | lr=9.08e-05 | epoch=0.5500
[train] step=258 | loss=0.1009 | lr=9.07e-05 | epoch=0.5522
[train] step=259 | loss=0.1112 | lr=9.07e-05 | epoch=0.5543
[train] step=260 | loss=0.1122 | lr=9.06e-05 | epoch=0.5564
[train] step=261 | loss=0.0950 | lr=9.05e-05 | epoch=0.5586
[train] step=262 | loss=0.1291 | lr=9.04e-05 | epoch=0.5607
[train] step=263 | loss=0.0996 | lr=9.03e-05 | epoch=0.5629
[train] step=264 | loss=0.0923 | lr=9.03e-05 | epoch=0.5650
[train] step=265 | loss=0.1276 | lr=9.02e-05 | epoch=0.5671
[train] step=266 | loss=0.1039 | lr=9.01e-05 | epoch=0.5693
[train] step=267 | loss=0.1086 | lr=9.00e-05 | epoch=0.5714
[train] step=268 | loss=0.1001 | lr=9.00e-05 | epoch=0.5736
[train] step=269 | loss=0.1095 | lr=8.99e-05 | epoch=0.5757
[train] step=270 | loss=0.1239 | lr=8.98e-05 | epoch=0.5778
[train] step=271 | loss=0.1081 | lr=8.97e-05 | epoch=0.5800
[train] step=272 | loss=0.1126 | lr=8.96e-05 | epoch=0.5821
[train] step=273 | loss=0.0906 | lr=8.96e-05 | epoch=0.5843
[train] step=274 | loss=0.0981 | lr=8.95e-05 | epoch=0.5864
[train] step=275 | loss=0.1160 | lr=8.94e-05 | epoch=0.5886
[train] step=276 | loss=0.1188 | lr=8.93e-05 | epoch=0.5907
[train] step=277 | loss=0.1011 | lr=8.92e-05 | epoch=0.5928
[train] step=278 | loss=0.0945 | lr=8.92e-05 | epoch=0.5950
[train] step=279 | loss=0.0968 | lr=8.91e-05 | epoch=0.5971
[train] step=280 | loss=0.1003 | lr=8.90e-05 | epoch=0.5993
[train] step=281 | loss=0.1012 | lr=8.89e-05 | epoch=0.6014
[train] step=282 | loss=0.1108 | lr=8.88e-05 | epoch=0.6035
[train] step=283 | loss=0.1104 | lr=8.88e-05 | epoch=0.6057
[train] step=284 | loss=0.0999 | lr=8.87e-05 | epoch=0.6078
[train] step=285 | loss=0.0972 | lr=8.86e-05 | epoch=0.6100
[train] step=286 | loss=0.0941 | lr=8.85e-05 | epoch=0.6121
[train] step=287 | loss=0.1100 | lr=8.84e-05 | epoch=0.6142
[train] step=288 | loss=0.0945 | lr=8.84e-05 | epoch=0.6164
[train] step=289 | loss=0.0974 | lr=8.83e-05 | epoch=0.6185
[train] step=290 | loss=0.1024 | lr=8.82e-05 | epoch=0.6207
[train] step=291 | loss=0.1226 | lr=8.81e-05 | epoch=0.6228
[train] step=292 | loss=0.1090 | lr=8.81e-05 | epoch=0.6249
[train] step=293 | loss=0.1314 | lr=8.80e-05 | epoch=0.6271
[train] step=294 | loss=0.1003 | lr=8.79e-05 | epoch=0.6292
[train] step=295 | loss=0.1187 | lr=8.78e-05 | epoch=0.6314
[train] step=296 | loss=0.0979 | lr=8.77e-05 | epoch=0.6335
[train] step=297 | loss=0.1099 | lr=8.77e-05 | epoch=0.6356
[train] step=298 | loss=0.0932 | lr=8.76e-05 | epoch=0.6378
[train] step=299 | loss=0.0996 | lr=8.75e-05 | epoch=0.6399
[train] step=300 | loss=0.1089 | lr=8.74e-05 | epoch=0.6421
[train] step=301 | loss=0.1126 | lr=8.73e-05 | epoch=0.6442
[train] step=302 | loss=0.0953 | lr=8.73e-05 | epoch=0.6463
[train] step=303 | loss=0.1060 | lr=8.72e-05 | epoch=0.6485
[train] step=304 | loss=0.1088 | lr=8.71e-05 | epoch=0.6506
[train] step=305 | loss=0.0960 | lr=8.70e-05 | epoch=0.6528
[train] step=306 | loss=0.1253 | lr=8.69e-05 | epoch=0.6549
[train] step=307 | loss=0.1219 | lr=8.69e-05 | epoch=0.6570
[train] step=308 | loss=0.0985 | lr=8.68e-05 | epoch=0.6592
[train] step=309 | loss=0.1270 | lr=8.67e-05 | epoch=0.6613
[train] step=310 | loss=0.0887 | lr=8.66e-05 | epoch=0.6635
[train] step=311 | loss=0.0947 | lr=8.66e-05 | epoch=0.6656
[train] step=312 | loss=0.1350 | lr=8.65e-05 | epoch=0.6677
[train] step=313 | loss=0.1356 | lr=8.64e-05 | epoch=0.6699
[train] step=314 | loss=0.1036 | lr=8.63e-05 | epoch=0.6720
[train] step=315 | loss=0.0929 | lr=8.62e-05 | epoch=0.6742
[train] step=316 | loss=0.1032 | lr=8.62e-05 | epoch=0.6763
[train] step=317 | loss=0.1051 | lr=8.61e-05 | epoch=0.6784
[train] step=318 | loss=0.1027 | lr=8.60e-05 | epoch=0.6806
[train] step=319 | loss=0.1265 | lr=8.59e-05 | epoch=0.6827
[train] step=320 | loss=0.1074 | lr=8.58e-05 | epoch=0.6849
[train] step=321 | loss=0.1021 | lr=8.58e-05 | epoch=0.6870
[train] step=322 | loss=0.1141 | lr=8.57e-05 | epoch=0.6891
[train] step=323 | loss=0.1069 | lr=8.56e-05 | epoch=0.6913
[train] step=324 | loss=0.1065 | lr=8.55e-05 | epoch=0.6934
[train] step=325 | loss=0.1133 | lr=8.54e-05 | epoch=0.6956
[train] step=326 | loss=0.1003 | lr=8.54e-05 | epoch=0.6977
[train] step=327 | loss=0.1124 | lr=8.53e-05 | epoch=0.6998
[train] step=328 | loss=0.1298 | lr=8.52e-05 | epoch=0.7020
[train] step=329 | loss=0.0836 | lr=8.51e-05 | epoch=0.7041
[train] step=330 | loss=0.0921 | lr=8.50e-05 | epoch=0.7063
[train] step=331 | loss=0.0992 | lr=8.50e-05 | epoch=0.7084
[train] step=332 | loss=0.1177 | lr=8.49e-05 | epoch=0.7105
[train] step=333 | loss=0.1265 | lr=8.48e-05 | epoch=0.7127
[train] step=334 | loss=0.1204 | lr=8.47e-05 | epoch=0.7148
[train] step=335 | loss=0.0809 | lr=8.47e-05 | epoch=0.7170
[train] step=336 | loss=0.1023 | lr=8.46e-05 | epoch=0.7191
[train] step=337 | loss=0.0952 | lr=8.45e-05 | epoch=0.7212
[train] step=338 | loss=0.1024 | lr=8.44e-05 | epoch=0.7234
[train] step=339 | loss=0.1128 | lr=8.43e-05 | epoch=0.7255
[train] step=340 | loss=0.1073 | lr=8.43e-05 | epoch=0.7277
[train] step=341 | loss=0.1371 | lr=8.42e-05 | epoch=0.7298
[train] step=342 | loss=0.0967 | lr=8.41e-05 | epoch=0.7319
[train] step=343 | loss=0.0860 | lr=8.40e-05 | epoch=0.7341
[train] step=344 | loss=0.1026 | lr=8.39e-05 | epoch=0.7362
[train] step=345 | loss=0.1162 | lr=8.39e-05 | epoch=0.7384
[train] step=346 | loss=0.1050 | lr=8.38e-05 | epoch=0.7405
[train] step=347 | loss=0.0994 | lr=8.37e-05 | epoch=0.7426
[train] step=348 | loss=0.1159 | lr=8.36e-05 | epoch=0.7448
[train] step=349 | loss=0.0977 | lr=8.35e-05 | epoch=0.7469
[train] step=350 | loss=0.0822 | lr=8.35e-05 | epoch=0.7491
[train] step=351 | loss=0.1159 | lr=8.34e-05 | epoch=0.7512
[train] step=352 | loss=0.0975 | lr=8.33e-05 | epoch=0.7533
[train] step=353 | loss=0.1284 | lr=8.32e-05 | epoch=0.7555
[train] step=354 | loss=0.0817 | lr=8.31e-05 | epoch=0.7576
[train] step=355 | loss=0.1160 | lr=8.31e-05 | epoch=0.7598
[train] step=356 | loss=0.0962 | lr=8.30e-05 | epoch=0.7619
[train] step=357 | loss=0.1116 | lr=8.29e-05 | epoch=0.7640
[train] step=358 | loss=0.0808 | lr=8.28e-05 | epoch=0.7662
[train] step=359 | loss=0.1014 | lr=8.28e-05 | epoch=0.7683
[train] step=360 | loss=0.1156 | lr=8.27e-05 | epoch=0.7705
[train] step=361 | loss=0.1042 | lr=8.26e-05 | epoch=0.7726
[train] step=362 | loss=0.1035 | lr=8.25e-05 | epoch=0.7747
[train] step=363 | loss=0.1277 | lr=8.24e-05 | epoch=0.7769
[train] step=364 | loss=0.0978 | lr=8.24e-05 | epoch=0.7790
[train] step=365 | loss=0.0961 | lr=8.23e-05 | epoch=0.7812
[train] step=366 | loss=0.1154 | lr=8.22e-05 | epoch=0.7833
[train] step=367 | loss=0.0918 | lr=8.21e-05 | epoch=0.7854
[train] step=368 | loss=0.1103 | lr=8.20e-05 | epoch=0.7876
[train] step=369 | loss=0.1122 | lr=8.20e-05 | epoch=0.7897
[train] step=370 | loss=0.1190 | lr=8.19e-05 | epoch=0.7919
[train] step=371 | loss=0.1179 | lr=8.18e-05 | epoch=0.7940
[train] step=372 | loss=0.1084 | lr=8.17e-05 | epoch=0.7961
[train] step=373 | loss=0.1245 | lr=8.16e-05 | epoch=0.7983
[train] step=374 | loss=0.1056 | lr=8.16e-05 | epoch=0.8004
[train] step=375 | loss=0.1161 | lr=8.15e-05 | epoch=0.8026
[train] step=376 | loss=0.0997 | lr=8.14e-05 | epoch=0.8047
[train] step=377 | loss=0.0951 | lr=8.13e-05 | epoch=0.8068
[train] step=378 | loss=0.0969 | lr=8.13e-05 | epoch=0.8090
[train] step=379 | loss=0.1367 | lr=8.12e-05 | epoch=0.8111
[train] step=380 | loss=0.1292 | lr=8.11e-05 | epoch=0.8133
[train] step=381 | loss=0.1306 | lr=8.10e-05 | epoch=0.8154
[train] step=382 | loss=0.1170 | lr=8.09e-05 | epoch=0.8175
[train] step=383 | loss=0.0956 | lr=8.09e-05 | epoch=0.8197
[train] step=384 | loss=0.0857 | lr=8.08e-05 | epoch=0.8218
[train] step=385 | loss=0.1140 | lr=8.07e-05 | epoch=0.8240
[train] step=386 | loss=0.1547 | lr=8.06e-05 | epoch=0.8261
[train] step=387 | loss=0.0925 | lr=8.05e-05 | epoch=0.8283
[train] step=388 | loss=0.1124 | lr=8.05e-05 | epoch=0.8304
[train] step=389 | loss=0.0943 | lr=8.04e-05 | epoch=0.8325
[train] step=390 | loss=0.0988 | lr=8.03e-05 | epoch=0.8347
[train] step=391 | loss=0.0957 | lr=8.02e-05 | epoch=0.8368
[train] step=392 | loss=0.0929 | lr=8.01e-05 | epoch=0.8390
[train] step=393 | loss=0.1027 | lr=8.01e-05 | epoch=0.8411
[train] step=394 | loss=0.1172 | lr=8.00e-05 | epoch=0.8432
[train] step=395 | loss=0.1102 | lr=7.99e-05 | epoch=0.8454
[train] step=396 | loss=0.1167 | lr=7.98e-05 | epoch=0.8475
[train] step=397 | loss=0.0993 | lr=7.97e-05 | epoch=0.8497
[train] step=398 | loss=0.1073 | lr=7.97e-05 | epoch=0.8518
[train] step=399 | loss=0.1015 | lr=7.96e-05 | epoch=0.8539
[train] step=400 | loss=0.1135 | lr=7.95e-05 | epoch=0.8561
[train] step=401 | loss=0.1092 | lr=7.94e-05 | epoch=0.8582
[train] step=402 | loss=0.1073 | lr=7.94e-05 | epoch=0.8604
[train] step=403 | loss=0.0877 | lr=7.93e-05 | epoch=0.8625
[train] step=404 | loss=0.1056 | lr=7.92e-05 | epoch=0.8646
[train] step=405 | loss=0.1089 | lr=7.91e-05 | epoch=0.8668
[train] step=406 | loss=0.0970 | lr=7.90e-05 | epoch=0.8689
[train] step=407 | loss=0.0847 | lr=7.90e-05 | epoch=0.8711
[train] step=408 | loss=0.1250 | lr=7.89e-05 | epoch=0.8732
[train] step=409 | loss=0.1108 | lr=7.88e-05 | epoch=0.8753
[train] step=410 | loss=0.0898 | lr=7.87e-05 | epoch=0.8775
[train] step=411 | loss=0.0985 | lr=7.86e-05 | epoch=0.8796
[train] step=412 | loss=0.1061 | lr=7.86e-05 | epoch=0.8818
[train] step=413 | loss=0.1022 | lr=7.85e-05 | epoch=0.8839
[train] step=414 | loss=0.1157 | lr=7.84e-05 | epoch=0.8860
[train] step=415 | loss=0.0951 | lr=7.83e-05 | epoch=0.8882
[train] step=416 | loss=0.1212 | lr=7.82e-05 | epoch=0.8903
[train] step=417 | loss=0.1166 | lr=7.82e-05 | epoch=0.8925
[train] step=418 | loss=0.0951 | lr=7.81e-05 | epoch=0.8946
[train] step=419 | loss=0.0949 | lr=7.80e-05 | epoch=0.8967
[train] step=420 | loss=0.1141 | lr=7.79e-05 | epoch=0.8989
[train] step=421 | loss=0.0971 | lr=7.78e-05 | epoch=0.9010
[train] step=422 | loss=0.0918 | lr=7.78e-05 | epoch=0.9032
[train] step=423 | loss=0.1176 | lr=7.77e-05 | epoch=0.9053
[train] step=424 | loss=0.1206 | lr=7.76e-05 | epoch=0.9074
[train] step=425 | loss=0.1067 | lr=7.75e-05 | epoch=0.9096
[train] step=426 | loss=0.1014 | lr=7.75e-05 | epoch=0.9117
[train] step=427 | loss=0.1066 | lr=7.74e-05 | epoch=0.9139
[train] step=428 | loss=0.0944 | lr=7.73e-05 | epoch=0.9160
[train] step=429 | loss=0.1077 | lr=7.72e-05 | epoch=0.9181
[train] step=430 | loss=0.1009 | lr=7.71e-05 | epoch=0.9203
[train] step=431 | loss=0.0955 | lr=7.71e-05 | epoch=0.9224
[train] step=432 | loss=0.1426 | lr=7.70e-05 | epoch=0.9246
[train] step=433 | loss=0.0939 | lr=7.69e-05 | epoch=0.9267
[train] step=434 | loss=0.0913 | lr=7.68e-05 | epoch=0.9288
[train] step=435 | loss=0.1107 | lr=7.67e-05 | epoch=0.9310
[train] step=436 | loss=0.1190 | lr=7.67e-05 | epoch=0.9331
[train] step=437 | loss=0.0971 | lr=7.66e-05 | epoch=0.9353
[train] step=438 | loss=0.0877 | lr=7.65e-05 | epoch=0.9374
[train] step=439 | loss=0.1269 | lr=7.64e-05 | epoch=0.9395
[train] step=440 | loss=0.1184 | lr=7.63e-05 | epoch=0.9417
[train] step=441 | loss=0.1110 | lr=7.63e-05 | epoch=0.9438
[train] step=442 | loss=0.1351 | lr=7.62e-05 | epoch=0.9460
[train] step=443 | loss=0.0992 | lr=7.61e-05 | epoch=0.9481
[train] step=444 | loss=0.1010 | lr=7.60e-05 | epoch=0.9502
[train] step=445 | loss=0.1043 | lr=7.59e-05 | epoch=0.9524
[train] step=446 | loss=0.0884 | lr=7.59e-05 | epoch=0.9545
[train] step=447 | loss=0.0898 | lr=7.58e-05 | epoch=0.9567
[train] step=448 | loss=0.1178 | lr=7.57e-05 | epoch=0.9588
[train] step=449 | loss=0.1199 | lr=7.56e-05 | epoch=0.9609
[train] step=450 | loss=0.0871 | lr=7.56e-05 | epoch=0.9631
[train] step=451 | loss=0.1029 | lr=7.55e-05 | epoch=0.9652
[train] step=452 | loss=0.1015 | lr=7.54e-05 | epoch=0.9674
[train] step=453 | loss=0.0947 | lr=7.53e-05 | epoch=0.9695
[train] step=454 | loss=0.1017 | lr=7.52e-05 | epoch=0.9716
[train] step=455 | loss=0.1003 | lr=7.52e-05 | epoch=0.9738
[train] step=456 | loss=0.1142 | lr=7.51e-05 | epoch=0.9759
[train] step=457 | loss=0.1202 | lr=7.50e-05 | epoch=0.9781
[train] step=458 | loss=0.1125 | lr=7.49e-05 | epoch=0.9802
[train] step=459 | loss=0.1201 | lr=7.48e-05 | epoch=0.9823
[train] step=460 | loss=0.1037 | lr=7.48e-05 | epoch=0.9845
[train] step=461 | loss=0.1080 | lr=7.47e-05 | epoch=0.9866
[train] step=462 | loss=0.1069 | lr=7.46e-05 | epoch=0.9888
[train] step=463 | loss=0.0927 | lr=7.45e-05 | epoch=0.9909
[train] step=464 | loss=0.1162 | lr=7.44e-05 | epoch=0.9930
[train] step=465 | loss=0.0977 | lr=7.44e-05 | epoch=0.9952
[train] step=466 | loss=0.1007 | lr=7.43e-05 | epoch=0.9973

Saving model checkpoint to output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-466
2026-04-06 05:05:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:05:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 05:05:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:05:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-466\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-466\tokenizer_config.json

[train] step=467 | loss=0.1104 | lr=7.42e-05 | epoch=0.9995
[train] step=468 | loss=0.0547 | lr=7.41e-05 | epoch=1.0000
[train] step=469 | loss=0.0859 | lr=7.41e-05 | epoch=1.0021
[train] step=470 | loss=0.0960 | lr=7.40e-05 | epoch=1.0043
[train] step=471 | loss=0.1051 | lr=7.39e-05 | epoch=1.0064
[train] step=472 | loss=0.1173 | lr=7.38e-05 | epoch=1.0086
[train] step=473 | loss=0.1014 | lr=7.37e-05 | epoch=1.0107
[train] step=474 | loss=0.0991 | lr=7.37e-05 | epoch=1.0128
[train] step=475 | loss=0.0973 | lr=7.36e-05 | epoch=1.0150
[train] step=476 | loss=0.1104 | lr=7.35e-05 | epoch=1.0171
[train] step=477 | loss=0.1242 | lr=7.34e-05 | epoch=1.0193
[train] step=478 | loss=0.0797 | lr=7.33e-05 | epoch=1.0214
[train] step=479 | loss=0.1149 | lr=7.33e-05 | epoch=1.0235
[train] step=480 | loss=0.0795 | lr=7.32e-05 | epoch=1.0257
[train] step=481 | loss=0.1090 | lr=7.31e-05 | epoch=1.0278
[train] step=482 | loss=0.1206 | lr=7.30e-05 | epoch=1.0300
[train] step=483 | loss=0.0842 | lr=7.29e-05 | epoch=1.0321
[train] step=484 | loss=0.1080 | lr=7.29e-05 | epoch=1.0342
[train] step=485 | loss=0.0857 | lr=7.28e-05 | epoch=1.0364
[train] step=486 | loss=0.1002 | lr=7.27e-05 | epoch=1.0385
[train] step=487 | loss=0.1255 | lr=7.26e-05 | epoch=1.0407
[train] step=488 | loss=0.1139 | lr=7.25e-05 | epoch=1.0428
[train] step=489 | loss=0.0891 | lr=7.25e-05 | epoch=1.0449
[train] step=490 | loss=0.0976 | lr=7.24e-05 | epoch=1.0471
[train] step=491 | loss=0.0939 | lr=7.23e-05 | epoch=1.0492
[train] step=492 | loss=0.1125 | lr=7.22e-05 | epoch=1.0514
[train] step=493 | loss=0.0916 | lr=7.22e-05 | epoch=1.0535
[train] step=494 | loss=0.1071 | lr=7.21e-05 | epoch=1.0556
[train] step=495 | loss=0.0957 | lr=7.20e-05 | epoch=1.0578
[train] step=496 | loss=0.1124 | lr=7.19e-05 | epoch=1.0599
[train] step=497 | loss=0.0975 | lr=7.18e-05 | epoch=1.0621
[train] step=498 | loss=0.1287 | lr=7.18e-05 | epoch=1.0642
[train] step=499 | loss=0.1134 | lr=7.17e-05 | epoch=1.0663
[train] step=500 | loss=0.1047 | lr=7.16e-05 | epoch=1.0685
[train] step=501 | loss=0.0946 | lr=7.15e-05 | epoch=1.0706
[train] step=502 | loss=0.0934 | lr=7.14e-05 | epoch=1.0728
[train] step=503 | loss=0.1426 | lr=7.14e-05 | epoch=1.0749
[train] step=504 | loss=0.1137 | lr=7.13e-05 | epoch=1.0770
[train] step=505 | loss=0.1143 | lr=7.12e-05 | epoch=1.0792
[train] step=506 | loss=0.0930 | lr=7.11e-05 | epoch=1.0813
[train] step=507 | loss=0.1080 | lr=7.10e-05 | epoch=1.0835
[train] step=508 | loss=0.1104 | lr=7.10e-05 | epoch=1.0856
[train] step=509 | loss=0.1464 | lr=7.09e-05 | epoch=1.0877
[train] step=510 | loss=0.1113 | lr=7.08e-05 | epoch=1.0899
[train] step=511 | loss=0.1050 | lr=7.07e-05 | epoch=1.0920
[train] step=512 | loss=0.1018 | lr=7.06e-05 | epoch=1.0942
[train] step=513 | loss=0.0890 | lr=7.06e-05 | epoch=1.0963
[train] step=514 | loss=0.0964 | lr=7.05e-05 | epoch=1.0984
[train] step=515 | loss=0.1007 | lr=7.04e-05 | epoch=1.1006
[train] step=516 | loss=0.1174 | lr=7.03e-05 | epoch=1.1027
[train] step=517 | loss=0.0866 | lr=7.03e-05 | epoch=1.1049
[train] step=518 | loss=0.1268 | lr=7.02e-05 | epoch=1.1070
[train] step=519 | loss=0.1080 | lr=7.01e-05 | epoch=1.1091
[train] step=520 | loss=0.0990 | lr=7.00e-05 | epoch=1.1113
[train] step=521 | loss=0.0984 | lr=6.99e-05 | epoch=1.1134
[train] step=522 | loss=0.1254 | lr=6.99e-05 | epoch=1.1156
[train] step=523 | loss=0.0998 | lr=6.98e-05 | epoch=1.1177
[train] step=524 | loss=0.0986 | lr=6.97e-05 | epoch=1.1199
[train] step=525 | loss=0.0873 | lr=6.96e-05 | epoch=1.1220
[train] step=526 | loss=0.1026 | lr=6.95e-05 | epoch=1.1241
[train] step=527 | loss=0.0855 | lr=6.95e-05 | epoch=1.1263
[train] step=528 | loss=0.1211 | lr=6.94e-05 | epoch=1.1284
[train] step=529 | loss=0.1018 | lr=6.93e-05 | epoch=1.1306
[train] step=530 | loss=0.1062 | lr=6.92e-05 | epoch=1.1327
[train] step=531 | loss=0.1339 | lr=6.91e-05 | epoch=1.1348
[train] step=532 | loss=0.1057 | lr=6.91e-05 | epoch=1.1370
[train] step=533 | loss=0.1001 | lr=6.90e-05 | epoch=1.1391
[train] step=534 | loss=0.1017 | lr=6.89e-05 | epoch=1.1413
[train] step=535 | loss=0.1052 | lr=6.88e-05 | epoch=1.1434
[train] step=536 | loss=0.1116 | lr=6.88e-05 | epoch=1.1455
[train] step=537 | loss=0.0933 | lr=6.87e-05 | epoch=1.1477
[train] step=538 | loss=0.1051 | lr=6.86e-05 | epoch=1.1498
[train] step=539 | loss=0.1030 | lr=6.85e-05 | epoch=1.1520
[train] step=540 | loss=0.0862 | lr=6.84e-05 | epoch=1.1541
[train] step=541 | loss=0.0758 | lr=6.84e-05 | epoch=1.1562
[train] step=542 | loss=0.1100 | lr=6.83e-05 | epoch=1.1584
[train] step=543 | loss=0.0975 | lr=6.82e-05 | epoch=1.1605
[train] step=544 | loss=0.0835 | lr=6.81e-05 | epoch=1.1627
[train] step=545 | loss=0.0971 | lr=6.80e-05 | epoch=1.1648
[train] step=546 | loss=0.0849 | lr=6.80e-05 | epoch=1.1669
[train] step=547 | loss=0.0905 | lr=6.79e-05 | epoch=1.1691
[train] step=548 | loss=0.1000 | lr=6.78e-05 | epoch=1.1712
[train] step=549 | loss=0.0786 | lr=6.77e-05 | epoch=1.1734
[train] step=550 | loss=0.0941 | lr=6.76e-05 | epoch=1.1755
[train] step=551 | loss=0.1013 | lr=6.76e-05 | epoch=1.1776
[train] step=552 | loss=0.1048 | lr=6.75e-05 | epoch=1.1798
[train] step=553 | loss=0.1104 | lr=6.74e-05 | epoch=1.1819
[train] step=554 | loss=0.0915 | lr=6.73e-05 | epoch=1.1841
[train] step=555 | loss=0.0956 | lr=6.72e-05 | epoch=1.1862
[train] step=556 | loss=0.0921 | lr=6.72e-05 | epoch=1.1883
[train] step=557 | loss=0.1174 | lr=6.71e-05 | epoch=1.1905
[train] step=558 | loss=0.1043 | lr=6.70e-05 | epoch=1.1926
[train] step=559 | loss=0.1080 | lr=6.69e-05 | epoch=1.1948
[train] step=560 | loss=0.0942 | lr=6.69e-05 | epoch=1.1969
[train] step=561 | loss=0.1014 | lr=6.68e-05 | epoch=1.1990
[train] step=562 | loss=0.1011 | lr=6.67e-05 | epoch=1.2012
[train] step=563 | loss=0.1125 | lr=6.66e-05 | epoch=1.2033
[train] step=564 | loss=0.0920 | lr=6.65e-05 | epoch=1.2055
[train] step=565 | loss=0.1292 | lr=6.65e-05 | epoch=1.2076
[train] step=566 | loss=0.1104 | lr=6.64e-05 | epoch=1.2097
[train] step=567 | loss=0.0916 | lr=6.63e-05 | epoch=1.2119
[train] step=568 | loss=0.0964 | lr=6.62e-05 | epoch=1.2140
[train] step=569 | loss=0.1038 | lr=6.61e-05 | epoch=1.2162
[train] step=570 | loss=0.0911 | lr=6.61e-05 | epoch=1.2183
[train] step=571 | loss=0.1002 | lr=6.60e-05 | epoch=1.2204
[train] step=572 | loss=0.1068 | lr=6.59e-05 | epoch=1.2226
[train] step=573 | loss=0.1219 | lr=6.58e-05 | epoch=1.2247
[train] step=574 | loss=0.0891 | lr=6.57e-05 | epoch=1.2269
[train] step=575 | loss=0.0992 | lr=6.57e-05 | epoch=1.2290
[train] step=576 | loss=0.1049 | lr=6.56e-05 | epoch=1.2311
[train] step=577 | loss=0.1304 | lr=6.55e-05 | epoch=1.2333
[train] step=578 | loss=0.1089 | lr=6.54e-05 | epoch=1.2354
[train] step=579 | loss=0.1164 | lr=6.53e-05 | epoch=1.2376
[train] step=580 | loss=0.0924 | lr=6.53e-05 | epoch=1.2397
[train] step=581 | loss=0.0968 | lr=6.52e-05 | epoch=1.2418
[train] step=582 | loss=0.0957 | lr=6.51e-05 | epoch=1.2440
[train] step=583 | loss=0.1115 | lr=6.50e-05 | epoch=1.2461
[train] step=584 | loss=0.0985 | lr=6.50e-05 | epoch=1.2483
[train] step=585 | loss=0.1143 | lr=6.49e-05 | epoch=1.2504
[train] step=586 | loss=0.0916 | lr=6.48e-05 | epoch=1.2525
[train] step=587 | loss=0.1081 | lr=6.47e-05 | epoch=1.2547
[train] step=588 | loss=0.1217 | lr=6.46e-05 | epoch=1.2568
[train] step=589 | loss=0.1285 | lr=6.46e-05 | epoch=1.2590
[train] step=590 | loss=0.1181 | lr=6.45e-05 | epoch=1.2611
[train] step=591 | loss=0.0870 | lr=6.44e-05 | epoch=1.2632
[train] step=592 | loss=0.1081 | lr=6.43e-05 | epoch=1.2654
[train] step=593 | loss=0.0964 | lr=6.42e-05 | epoch=1.2675
[train] step=594 | loss=0.0941 | lr=6.42e-05 | epoch=1.2697
[train] step=595 | loss=0.0798 | lr=6.41e-05 | epoch=1.2718
[train] step=596 | loss=0.0954 | lr=6.40e-05 | epoch=1.2739
[train] step=597 | loss=0.0974 | lr=6.39e-05 | epoch=1.2761
[train] step=598 | loss=0.1006 | lr=6.38e-05 | epoch=1.2782
[train] step=599 | loss=0.0980 | lr=6.38e-05 | epoch=1.2804
[train] step=600 | loss=0.1119 | lr=6.37e-05 | epoch=1.2825
[train] step=601 | loss=0.1068 | lr=6.36e-05 | epoch=1.2846
[train] step=602 | loss=0.0929 | lr=6.35e-05 | epoch=1.2868
[train] step=603 | loss=0.0880 | lr=6.34e-05 | epoch=1.2889
[train] step=604 | loss=0.0913 | lr=6.34e-05 | epoch=1.2911
[train] step=605 | loss=0.0928 | lr=6.33e-05 | epoch=1.2932
[train] step=606 | loss=0.0768 | lr=6.32e-05 | epoch=1.2953
[train] step=607 | loss=0.1091 | lr=6.31e-05 | epoch=1.2975
[train] step=608 | loss=0.0828 | lr=6.31e-05 | epoch=1.2996
[train] step=609 | loss=0.1163 | lr=6.30e-05 | epoch=1.3018
[train] step=610 | loss=0.1158 | lr=6.29e-05 | epoch=1.3039
[train] step=611 | loss=0.0798 | lr=6.28e-05 | epoch=1.3060
[train] step=612 | loss=0.1079 | lr=6.27e-05 | epoch=1.3082
[train] step=613 | loss=0.1136 | lr=6.27e-05 | epoch=1.3103
[train] step=614 | loss=0.1040 | lr=6.26e-05 | epoch=1.3125
[train] step=615 | loss=0.1014 | lr=6.25e-05 | epoch=1.3146
[train] step=616 | loss=0.0954 | lr=6.24e-05 | epoch=1.3167
[train] step=617 | loss=0.0748 | lr=6.23e-05 | epoch=1.3189
[train] step=618 | loss=0.1074 | lr=6.23e-05 | epoch=1.3210
[train] step=619 | loss=0.1047 | lr=6.22e-05 | epoch=1.3232
[train] step=620 | loss=0.0955 | lr=6.21e-05 | epoch=1.3253
[train] step=621 | loss=0.1178 | lr=6.20e-05 | epoch=1.3274
[train] step=622 | loss=0.0969 | lr=6.19e-05 | epoch=1.3296
[train] step=623 | loss=0.0986 | lr=6.19e-05 | epoch=1.3317
[train] step=624 | loss=0.1066 | lr=6.18e-05 | epoch=1.3339
[train] step=625 | loss=0.0978 | lr=6.17e-05 | epoch=1.3360
[train] step=626 | loss=0.0887 | lr=6.16e-05 | epoch=1.3381
[train] step=627 | loss=0.1369 | lr=6.16e-05 | epoch=1.3403
[train] step=628 | loss=0.0913 | lr=6.15e-05 | epoch=1.3424
[train] step=629 | loss=0.0759 | lr=6.14e-05 | epoch=1.3446
[train] step=630 | loss=0.1036 | lr=6.13e-05 | epoch=1.3467
[train] step=631 | loss=0.0968 | lr=6.12e-05 | epoch=1.3488
[train] step=632 | loss=0.1064 | lr=6.12e-05 | epoch=1.3510
[train] step=633 | loss=0.1085 | lr=6.11e-05 | epoch=1.3531
[train] step=634 | loss=0.1127 | lr=6.10e-05 | epoch=1.3553
[train] step=635 | loss=0.0963 | lr=6.09e-05 | epoch=1.3574
[train] step=636 | loss=0.0986 | lr=6.08e-05 | epoch=1.3596
[train] step=637 | loss=0.0929 | lr=6.08e-05 | epoch=1.3617
[train] step=638 | loss=0.1042 | lr=6.07e-05 | epoch=1.3638
[train] step=639 | loss=0.1050 | lr=6.06e-05 | epoch=1.3660
[train] step=640 | loss=0.0804 | lr=6.05e-05 | epoch=1.3681
[train] step=641 | loss=0.0968 | lr=6.04e-05 | epoch=1.3703
[train] step=642 | loss=0.0986 | lr=6.04e-05 | epoch=1.3724
[train] step=643 | loss=0.1168 | lr=6.03e-05 | epoch=1.3745
[train] step=644 | loss=0.1112 | lr=6.02e-05 | epoch=1.3767
[train] step=645 | loss=0.1173 | lr=6.01e-05 | epoch=1.3788
[train] step=646 | loss=0.0972 | lr=6.00e-05 | epoch=1.3810
[train] step=647 | loss=0.0867 | lr=6.00e-05 | epoch=1.3831
[train] step=648 | loss=0.1039 | lr=5.99e-05 | epoch=1.3852
[train] step=649 | loss=0.0674 | lr=5.98e-05 | epoch=1.3874
[train] step=650 | loss=0.0865 | lr=5.97e-05 | epoch=1.3895
[train] step=651 | loss=0.0849 | lr=5.97e-05 | epoch=1.3917
[train] step=652 | loss=0.0965 | lr=5.96e-05 | epoch=1.3938
[train] step=653 | loss=0.1122 | lr=5.95e-05 | epoch=1.3959
[train] step=654 | loss=0.0848 | lr=5.94e-05 | epoch=1.3981
[train] step=655 | loss=0.0822 | lr=5.93e-05 | epoch=1.4002
[train] step=656 | loss=0.1052 | lr=5.93e-05 | epoch=1.4024
[train] step=657 | loss=0.0982 | lr=5.92e-05 | epoch=1.4045
[train] step=658 | loss=0.1019 | lr=5.91e-05 | epoch=1.4066
[train] step=659 | loss=0.1110 | lr=5.90e-05 | epoch=1.4088
[train] step=660 | loss=0.0968 | lr=5.89e-05 | epoch=1.4109
[train] step=661 | loss=0.1374 | lr=5.89e-05 | epoch=1.4131
[train] step=662 | loss=0.1035 | lr=5.88e-05 | epoch=1.4152
[train] step=663 | loss=0.1076 | lr=5.87e-05 | epoch=1.4173
[train] step=664 | loss=0.1075 | lr=5.86e-05 | epoch=1.4195
[train] step=665 | loss=0.0916 | lr=5.85e-05 | epoch=1.4216
[train] step=666 | loss=0.0846 | lr=5.85e-05 | epoch=1.4238
[train] step=667 | loss=0.0886 | lr=5.84e-05 | epoch=1.4259
[train] step=668 | loss=0.0967 | lr=5.83e-05 | epoch=1.4280
[train] step=669 | loss=0.1032 | lr=5.82e-05 | epoch=1.4302
[train] step=670 | loss=0.1036 | lr=5.81e-05 | epoch=1.4323
[train] step=671 | loss=0.1020 | lr=5.81e-05 | epoch=1.4345
[train] step=672 | loss=0.0820 | lr=5.80e-05 | epoch=1.4366
[train] step=673 | loss=0.1225 | lr=5.79e-05 | epoch=1.4387
[train] step=674 | loss=0.1095 | lr=5.78e-05 | epoch=1.4409
[train] step=675 | loss=0.0838 | lr=5.78e-05 | epoch=1.4430
[train] step=676 | loss=0.0990 | lr=5.77e-05 | epoch=1.4452
[train] step=677 | loss=0.0900 | lr=5.76e-05 | epoch=1.4473
[train] step=678 | loss=0.0885 | lr=5.75e-05 | epoch=1.4494
[train] step=679 | loss=0.0887 | lr=5.74e-05 | epoch=1.4516
[train] step=680 | loss=0.0888 | lr=5.74e-05 | epoch=1.4537
[train] step=681 | loss=0.1084 | lr=5.73e-05 | epoch=1.4559
[train] step=682 | loss=0.0996 | lr=5.72e-05 | epoch=1.4580
[train] step=683 | loss=0.0872 | lr=5.71e-05 | epoch=1.4601
[train] step=684 | loss=0.1001 | lr=5.70e-05 | epoch=1.4623
[train] step=685 | loss=0.1142 | lr=5.70e-05 | epoch=1.4644
[train] step=686 | loss=0.1015 | lr=5.69e-05 | epoch=1.4666
[train] step=687 | loss=0.0957 | lr=5.68e-05 | epoch=1.4687
[train] step=688 | loss=0.1273 | lr=5.67e-05 | epoch=1.4708
[train] step=689 | loss=0.1058 | lr=5.66e-05 | epoch=1.4730
[train] step=690 | loss=0.1166 | lr=5.66e-05 | epoch=1.4751
[train] step=691 | loss=0.0814 | lr=5.65e-05 | epoch=1.4773
[train] step=692 | loss=0.1054 | lr=5.64e-05 | epoch=1.4794
[train] step=693 | loss=0.0969 | lr=5.63e-05 | epoch=1.4815
[train] step=694 | loss=0.1034 | lr=5.63e-05 | epoch=1.4837
[train] step=695 | loss=0.0832 | lr=5.62e-05 | epoch=1.4858
[train] step=696 | loss=0.1060 | lr=5.61e-05 | epoch=1.4880
[train] step=697 | loss=0.1192 | lr=5.60e-05 | epoch=1.4901
[train] step=698 | loss=0.1107 | lr=5.59e-05 | epoch=1.4922
[train] step=699 | loss=0.1156 | lr=5.59e-05 | epoch=1.4944

Saving model checkpoint to output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-699
2026-04-06 05:15:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:15:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 05:15:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:15:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-699\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-699\tokenizer_config.json

[train] step=700 | loss=0.0908 | lr=5.58e-05 | epoch=1.4965
[train] step=701 | loss=0.1168 | lr=5.57e-05 | epoch=1.4987
[train] step=702 | loss=0.0858 | lr=5.56e-05 | epoch=1.5008
[train] step=703 | loss=0.0984 | lr=5.55e-05 | epoch=1.5029
[train] step=704 | loss=0.0936 | lr=5.55e-05 | epoch=1.5051
[train] step=705 | loss=0.1192 | lr=5.54e-05 | epoch=1.5072
[train] step=706 | loss=0.1123 | lr=5.53e-05 | epoch=1.5094
[train] step=707 | loss=0.1069 | lr=5.52e-05 | epoch=1.5115
[train] step=708 | loss=0.0916 | lr=5.51e-05 | epoch=1.5136
[train] step=709 | loss=0.0828 | lr=5.51e-05 | epoch=1.5158
[train] step=710 | loss=0.1015 | lr=5.50e-05 | epoch=1.5179
[train] step=711 | loss=0.0949 | lr=5.49e-05 | epoch=1.5201
[train] step=712 | loss=0.1020 | lr=5.48e-05 | epoch=1.5222
[train] step=713 | loss=0.0863 | lr=5.47e-05 | epoch=1.5243
[train] step=714 | loss=0.0853 | lr=5.47e-05 | epoch=1.5265
[train] step=715 | loss=0.0777 | lr=5.46e-05 | epoch=1.5286
[train] step=716 | loss=0.1055 | lr=5.45e-05 | epoch=1.5308
[train] step=717 | loss=0.1071 | lr=5.44e-05 | epoch=1.5329
[train] step=718 | loss=0.1010 | lr=5.44e-05 | epoch=1.5350
[train] step=719 | loss=0.0748 | lr=5.43e-05 | epoch=1.5372
[train] step=720 | loss=0.1115 | lr=5.42e-05 | epoch=1.5393
[train] step=721 | loss=0.1068 | lr=5.41e-05 | epoch=1.5415
[train] step=722 | loss=0.0973 | lr=5.40e-05 | epoch=1.5436
[train] step=723 | loss=0.1069 | lr=5.40e-05 | epoch=1.5457
[train] step=724 | loss=0.0894 | lr=5.39e-05 | epoch=1.5479
[train] step=725 | loss=0.1542 | lr=5.38e-05 | epoch=1.5500
[train] step=726 | loss=0.1019 | lr=5.37e-05 | epoch=1.5522
[train] step=727 | loss=0.0990 | lr=5.36e-05 | epoch=1.5543
[train] step=728 | loss=0.0967 | lr=5.36e-05 | epoch=1.5564
[train] step=729 | loss=0.1032 | lr=5.35e-05 | epoch=1.5586
[train] step=730 | loss=0.1008 | lr=5.34e-05 | epoch=1.5607
[train] step=731 | loss=0.1002 | lr=5.33e-05 | epoch=1.5629
[train] step=732 | loss=0.1070 | lr=5.32e-05 | epoch=1.5650
[train] step=733 | loss=0.0768 | lr=5.32e-05 | epoch=1.5671
[train] step=734 | loss=0.0970 | lr=5.31e-05 | epoch=1.5693
[train] step=735 | loss=0.0956 | lr=5.30e-05 | epoch=1.5714
[train] step=736 | loss=0.0974 | lr=5.29e-05 | epoch=1.5736
[train] step=737 | loss=0.0992 | lr=5.28e-05 | epoch=1.5757
[train] step=738 | loss=0.1012 | lr=5.28e-05 | epoch=1.5778
[train] step=739 | loss=0.1019 | lr=5.27e-05 | epoch=1.5800
[train] step=740 | loss=0.1192 | lr=5.26e-05 | epoch=1.5821
[train] step=741 | loss=0.1050 | lr=5.25e-05 | epoch=1.5843
[train] step=742 | loss=0.1142 | lr=5.25e-05 | epoch=1.5864
[train] step=743 | loss=0.0975 | lr=5.24e-05 | epoch=1.5886
[train] step=744 | loss=0.1039 | lr=5.23e-05 | epoch=1.5907
[train] step=745 | loss=0.0829 | lr=5.22e-05 | epoch=1.5928
[train] step=746 | loss=0.1022 | lr=5.21e-05 | epoch=1.5950
[train] step=747 | loss=0.1229 | lr=5.21e-05 | epoch=1.5971
[train] step=748 | loss=0.0929 | lr=5.20e-05 | epoch=1.5993
[train] step=749 | loss=0.0952 | lr=5.19e-05 | epoch=1.6014
[train] step=750 | loss=0.1041 | lr=5.18e-05 | epoch=1.6035
[train] step=751 | loss=0.1065 | lr=5.17e-05 | epoch=1.6057
[train] step=752 | loss=0.0988 | lr=5.17e-05 | epoch=1.6078
[train] step=753 | loss=0.1155 | lr=5.16e-05 | epoch=1.6100
[train] step=754 | loss=0.1007 | lr=5.15e-05 | epoch=1.6121
[train] step=755 | loss=0.1071 | lr=5.14e-05 | epoch=1.6142
[train] step=756 | loss=0.1050 | lr=5.13e-05 | epoch=1.6164
[train] step=757 | loss=0.0924 | lr=5.13e-05 | epoch=1.6185
[train] step=758 | loss=0.0860 | lr=5.12e-05 | epoch=1.6207
[train] step=759 | loss=0.0899 | lr=5.11e-05 | epoch=1.6228
[train] step=760 | loss=0.0731 | lr=5.10e-05 | epoch=1.6249
[train] step=761 | loss=0.0922 | lr=5.09e-05 | epoch=1.6271
[train] step=762 | loss=0.1122 | lr=5.09e-05 | epoch=1.6292
[train] step=763 | loss=0.1122 | lr=5.08e-05 | epoch=1.6314
[train] step=764 | loss=0.1279 | lr=5.07e-05 | epoch=1.6335
[train] step=765 | loss=0.0955 | lr=5.06e-05 | epoch=1.6356
[train] step=766 | loss=0.1200 | lr=5.06e-05 | epoch=1.6378
[train] step=767 | loss=0.1218 | lr=5.05e-05 | epoch=1.6399
[train] step=768 | loss=0.0879 | lr=5.04e-05 | epoch=1.6421
[train] step=769 | loss=0.1079 | lr=5.03e-05 | epoch=1.6442
[train] step=770 | loss=0.0822 | lr=5.02e-05 | epoch=1.6463
[train] step=771 | loss=0.1059 | lr=5.02e-05 | epoch=1.6485
[train] step=772 | loss=0.0875 | lr=5.01e-05 | epoch=1.6506
[train] step=773 | loss=0.0935 | lr=5.00e-05 | epoch=1.6528
[train] step=774 | loss=0.0783 | lr=4.99e-05 | epoch=1.6549
[train] step=775 | loss=0.1040 | lr=4.98e-05 | epoch=1.6570
[train] step=776 | loss=0.0773 | lr=4.98e-05 | epoch=1.6592
[train] step=777 | loss=0.1019 | lr=4.97e-05 | epoch=1.6613
[train] step=778 | loss=0.1045 | lr=4.96e-05 | epoch=1.6635
[train] step=779 | loss=0.1055 | lr=4.95e-05 | epoch=1.6656
[train] step=780 | loss=0.1224 | lr=4.94e-05 | epoch=1.6677
[train] step=781 | loss=0.0876 | lr=4.94e-05 | epoch=1.6699
[train] step=782 | loss=0.0929 | lr=4.93e-05 | epoch=1.6720
[train] step=783 | loss=0.1000 | lr=4.92e-05 | epoch=1.6742
[train] step=784 | loss=0.1067 | lr=4.91e-05 | epoch=1.6763
[train] step=785 | loss=0.0810 | lr=4.91e-05 | epoch=1.6784
[train] step=786 | loss=0.1001 | lr=4.90e-05 | epoch=1.6806
[train] step=787 | loss=0.0973 | lr=4.89e-05 | epoch=1.6827
[train] step=788 | loss=0.1150 | lr=4.88e-05 | epoch=1.6849
[train] step=789 | loss=0.1041 | lr=4.87e-05 | epoch=1.6870
[train] step=790 | loss=0.0988 | lr=4.87e-05 | epoch=1.6891
[train] step=791 | loss=0.0908 | lr=4.86e-05 | epoch=1.6913
[train] step=792 | loss=0.0954 | lr=4.85e-05 | epoch=1.6934
[train] step=793 | loss=0.1092 | lr=4.84e-05 | epoch=1.6956
[train] step=794 | loss=0.1007 | lr=4.83e-05 | epoch=1.6977
[train] step=795 | loss=0.0977 | lr=4.83e-05 | epoch=1.6998
[train] step=796 | loss=0.1167 | lr=4.82e-05 | epoch=1.7020
[train] step=797 | loss=0.1055 | lr=4.81e-05 | epoch=1.7041
[train] step=798 | loss=0.1036 | lr=4.80e-05 | epoch=1.7063
[train] step=799 | loss=0.1008 | lr=4.79e-05 | epoch=1.7084
[train] step=800 | loss=0.1000 | lr=4.79e-05 | epoch=1.7105
[train] step=801 | loss=0.1149 | lr=4.78e-05 | epoch=1.7127
[train] step=802 | loss=0.1074 | lr=4.77e-05 | epoch=1.7148
[train] step=803 | loss=0.1228 | lr=4.76e-05 | epoch=1.7170
[train] step=804 | loss=0.0926 | lr=4.75e-05 | epoch=1.7191
[train] step=805 | loss=0.0981 | lr=4.75e-05 | epoch=1.7212
[train] step=806 | loss=0.0977 | lr=4.74e-05 | epoch=1.7234
[train] step=807 | loss=0.1046 | lr=4.73e-05 | epoch=1.7255
[train] step=808 | loss=0.0728 | lr=4.72e-05 | epoch=1.7277
[train] step=809 | loss=0.0920 | lr=4.72e-05 | epoch=1.7298
[train] step=810 | loss=0.1107 | lr=4.71e-05 | epoch=1.7319
[train] step=811 | loss=0.0929 | lr=4.70e-05 | epoch=1.7341
[train] step=812 | loss=0.1117 | lr=4.69e-05 | epoch=1.7362
[train] step=813 | loss=0.0988 | lr=4.68e-05 | epoch=1.7384
[train] step=814 | loss=0.0837 | lr=4.68e-05 | epoch=1.7405
[train] step=815 | loss=0.0841 | lr=4.67e-05 | epoch=1.7426
[train] step=816 | loss=0.1159 | lr=4.66e-05 | epoch=1.7448
[train] step=817 | loss=0.0992 | lr=4.65e-05 | epoch=1.7469
[train] step=818 | loss=0.1157 | lr=4.64e-05 | epoch=1.7491
[train] step=819 | loss=0.0897 | lr=4.64e-05 | epoch=1.7512
[train] step=820 | loss=0.1037 | lr=4.63e-05 | epoch=1.7533
[train] step=821 | loss=0.1082 | lr=4.62e-05 | epoch=1.7555
[train] step=822 | loss=0.0898 | lr=4.61e-05 | epoch=1.7576
[train] step=823 | loss=0.1102 | lr=4.60e-05 | epoch=1.7598
[train] step=824 | loss=0.0885 | lr=4.60e-05 | epoch=1.7619
[train] step=825 | loss=0.0965 | lr=4.59e-05 | epoch=1.7640
[train] step=826 | loss=0.0853 | lr=4.58e-05 | epoch=1.7662
[train] step=827 | loss=0.0943 | lr=4.57e-05 | epoch=1.7683
[train] step=828 | loss=0.0987 | lr=4.56e-05 | epoch=1.7705
[train] step=829 | loss=0.0870 | lr=4.56e-05 | epoch=1.7726
[train] step=830 | loss=0.1009 | lr=4.55e-05 | epoch=1.7747
[train] step=831 | loss=0.0894 | lr=4.54e-05 | epoch=1.7769
[train] step=832 | loss=0.1157 | lr=4.53e-05 | epoch=1.7790
[train] step=833 | loss=0.1181 | lr=4.53e-05 | epoch=1.7812
[train] step=834 | loss=0.0918 | lr=4.52e-05 | epoch=1.7833
[train] step=835 | loss=0.1220 | lr=4.51e-05 | epoch=1.7854
[train] step=836 | loss=0.0924 | lr=4.50e-05 | epoch=1.7876
[train] step=837 | loss=0.0917 | lr=4.49e-05 | epoch=1.7897
[train] step=838 | loss=0.1204 | lr=4.49e-05 | epoch=1.7919
[train] step=839 | loss=0.1074 | lr=4.48e-05 | epoch=1.7940
[train] step=840 | loss=0.0887 | lr=4.47e-05 | epoch=1.7961
[train] step=841 | loss=0.0916 | lr=4.46e-05 | epoch=1.7983
[train] step=842 | loss=0.1038 | lr=4.45e-05 | epoch=1.8004
[train] step=843 | loss=0.0754 | lr=4.45e-05 | epoch=1.8026
[train] step=844 | loss=0.0942 | lr=4.44e-05 | epoch=1.8047
[train] step=845 | loss=0.0965 | lr=4.43e-05 | epoch=1.8068
[train] step=846 | loss=0.1012 | lr=4.42e-05 | epoch=1.8090
[train] step=847 | loss=0.0916 | lr=4.41e-05 | epoch=1.8111
[train] step=848 | loss=0.0735 | lr=4.41e-05 | epoch=1.8133
[train] step=849 | loss=0.0885 | lr=4.40e-05 | epoch=1.8154
[train] step=850 | loss=0.1101 | lr=4.39e-05 | epoch=1.8175
[train] step=851 | loss=0.1068 | lr=4.38e-05 | epoch=1.8197
[train] step=852 | loss=0.0854 | lr=4.37e-05 | epoch=1.8218
[train] step=853 | loss=0.1148 | lr=4.37e-05 | epoch=1.8240
[train] step=854 | loss=0.0968 | lr=4.36e-05 | epoch=1.8261
[train] step=855 | loss=0.0937 | lr=4.35e-05 | epoch=1.8283
[train] step=856 | loss=0.1085 | lr=4.34e-05 | epoch=1.8304
[train] step=857 | loss=0.0882 | lr=4.34e-05 | epoch=1.8325
[train] step=858 | loss=0.0854 | lr=4.33e-05 | epoch=1.8347
[train] step=859 | loss=0.0987 | lr=4.32e-05 | epoch=1.8368
[train] step=860 | loss=0.1110 | lr=4.31e-05 | epoch=1.8390
[train] step=861 | loss=0.0955 | lr=4.30e-05 | epoch=1.8411
[train] step=862 | loss=0.0893 | lr=4.30e-05 | epoch=1.8432
[train] step=863 | loss=0.0859 | lr=4.29e-05 | epoch=1.8454
[train] step=864 | loss=0.1024 | lr=4.28e-05 | epoch=1.8475
[train] step=865 | loss=0.0984 | lr=4.27e-05 | epoch=1.8497
[train] step=866 | loss=0.0994 | lr=4.26e-05 | epoch=1.8518
[train] step=867 | loss=0.1001 | lr=4.26e-05 | epoch=1.8539
[train] step=868 | loss=0.0775 | lr=4.25e-05 | epoch=1.8561
[train] step=869 | loss=0.0937 | lr=4.24e-05 | epoch=1.8582
[train] step=870 | loss=0.1121 | lr=4.23e-05 | epoch=1.8604
[train] step=871 | loss=0.1189 | lr=4.22e-05 | epoch=1.8625
[train] step=872 | loss=0.1339 | lr=4.22e-05 | epoch=1.8646
[train] step=873 | loss=0.0955 | lr=4.21e-05 | epoch=1.8668
[train] step=874 | loss=0.1040 | lr=4.20e-05 | epoch=1.8689
[train] step=875 | loss=0.0900 | lr=4.19e-05 | epoch=1.8711
[train] step=876 | loss=0.1029 | lr=4.19e-05 | epoch=1.8732
[train] step=877 | loss=0.1231 | lr=4.18e-05 | epoch=1.8753
[train] step=878 | loss=0.0917 | lr=4.17e-05 | epoch=1.8775
[train] step=879 | loss=0.0869 | lr=4.16e-05 | epoch=1.8796
[train] step=880 | loss=0.1369 | lr=4.15e-05 | epoch=1.8818
[train] step=881 | loss=0.0879 | lr=4.15e-05 | epoch=1.8839
[train] step=882 | loss=0.1119 | lr=4.14e-05 | epoch=1.8860
[train] step=883 | loss=0.0965 | lr=4.13e-05 | epoch=1.8882
[train] step=884 | loss=0.1105 | lr=4.12e-05 | epoch=1.8903
[train] step=885 | loss=0.1151 | lr=4.11e-05 | epoch=1.8925
[train] step=886 | loss=0.1000 | lr=4.11e-05 | epoch=1.8946
[train] step=887 | loss=0.1188 | lr=4.10e-05 | epoch=1.8967
[train] step=888 | loss=0.1300 | lr=4.09e-05 | epoch=1.8989
[train] step=889 | loss=0.1220 | lr=4.08e-05 | epoch=1.9010
[train] step=890 | loss=0.1043 | lr=4.07e-05 | epoch=1.9032
[train] step=891 | loss=0.0982 | lr=4.07e-05 | epoch=1.9053
[train] step=892 | loss=0.0902 | lr=4.06e-05 | epoch=1.9074
[train] step=893 | loss=0.1055 | lr=4.05e-05 | epoch=1.9096
[train] step=894 | loss=0.1179 | lr=4.04e-05 | epoch=1.9117
[train] step=895 | loss=0.1123 | lr=4.03e-05 | epoch=1.9139
[train] step=896 | loss=0.0823 | lr=4.03e-05 | epoch=1.9160
[train] step=897 | loss=0.1085 | lr=4.02e-05 | epoch=1.9181
[train] step=898 | loss=0.1060 | lr=4.01e-05 | epoch=1.9203
[train] step=899 | loss=0.1015 | lr=4.00e-05 | epoch=1.9224
[train] step=900 | loss=0.1084 | lr=4.00e-05 | epoch=1.9246
[train] step=901 | loss=0.0960 | lr=3.99e-05 | epoch=1.9267
[train] step=902 | loss=0.1076 | lr=3.98e-05 | epoch=1.9288
[train] step=903 | loss=0.0906 | lr=3.97e-05 | epoch=1.9310
[train] step=904 | loss=0.0976 | lr=3.96e-05 | epoch=1.9331
[train] step=905 | loss=0.1113 | lr=3.96e-05 | epoch=1.9353
[train] step=906 | loss=0.1204 | lr=3.95e-05 | epoch=1.9374
[train] step=907 | loss=0.1000 | lr=3.94e-05 | epoch=1.9395
[train] step=908 | loss=0.0862 | lr=3.93e-05 | epoch=1.9417
[train] step=909 | loss=0.1205 | lr=3.92e-05 | epoch=1.9438
[train] step=910 | loss=0.1042 | lr=3.92e-05 | epoch=1.9460
[train] step=911 | loss=0.1008 | lr=3.91e-05 | epoch=1.9481
[train] step=912 | loss=0.1014 | lr=3.90e-05 | epoch=1.9502
[train] step=913 | loss=0.1011 | lr=3.89e-05 | epoch=1.9524
[train] step=914 | loss=0.0758 | lr=3.88e-05 | epoch=1.9545
[train] step=915 | loss=0.0933 | lr=3.88e-05 | epoch=1.9567
[train] step=916 | loss=0.0934 | lr=3.87e-05 | epoch=1.9588
[train] step=917 | loss=0.0859 | lr=3.86e-05 | epoch=1.9609
[train] step=918 | loss=0.1049 | lr=3.85e-05 | epoch=1.9631
[train] step=919 | loss=0.1060 | lr=3.84e-05 | epoch=1.9652
[train] step=920 | loss=0.0886 | lr=3.84e-05 | epoch=1.9674
[train] step=921 | loss=0.0962 | lr=3.83e-05 | epoch=1.9695
[train] step=922 | loss=0.1016 | lr=3.82e-05 | epoch=1.9716
[train] step=923 | loss=0.0883 | lr=3.81e-05 | epoch=1.9738
[train] step=924 | loss=0.0893 | lr=3.81e-05 | epoch=1.9759
[train] step=925 | loss=0.1033 | lr=3.80e-05 | epoch=1.9781
[train] step=926 | loss=0.0971 | lr=3.79e-05 | epoch=1.9802
[train] step=927 | loss=0.1060 | lr=3.78e-05 | epoch=1.9823
[train] step=928 | loss=0.1061 | lr=3.77e-05 | epoch=1.9845
[train] step=929 | loss=0.1159 | lr=3.77e-05 | epoch=1.9866
[train] step=930 | loss=0.1062 | lr=3.76e-05 | epoch=1.9888
[train] step=931 | loss=0.0873 | lr=3.75e-05 | epoch=1.9909
[train] step=932 | loss=0.1029 | lr=3.74e-05 | epoch=1.9930

Saving model checkpoint to output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-932
2026-04-06 05:24:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:24:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 05:24:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:24:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-932\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-932\tokenizer_config.json

[train] step=933 | loss=0.1303 | lr=3.73e-05 | epoch=1.9952
[train] step=934 | loss=0.1033 | lr=3.73e-05 | epoch=1.9973
[train] step=935 | loss=0.1049 | lr=3.72e-05 | epoch=1.9995
[train] step=936 | loss=0.0345 | lr=3.71e-05 | epoch=2.0000
[train] step=937 | loss=0.0832 | lr=3.70e-05 | epoch=2.0021
[train] step=938 | loss=0.0916 | lr=3.69e-05 | epoch=2.0043
[train] step=939 | loss=0.0690 | lr=3.69e-05 | epoch=2.0064
[train] step=940 | loss=0.0913 | lr=3.68e-05 | epoch=2.0086
[train] step=941 | loss=0.0980 | lr=3.67e-05 | epoch=2.0107
[train] step=942 | loss=0.0999 | lr=3.66e-05 | epoch=2.0128
[train] step=943 | loss=0.0948 | lr=3.66e-05 | epoch=2.0150
[train] step=944 | loss=0.0982 | lr=3.65e-05 | epoch=2.0171
[train] step=945 | loss=0.0991 | lr=3.64e-05 | epoch=2.0193
[train] step=946 | loss=0.1049 | lr=3.63e-05 | epoch=2.0214
[train] step=947 | loss=0.0943 | lr=3.62e-05 | epoch=2.0235
[train] step=948 | loss=0.0930 | lr=3.62e-05 | epoch=2.0257
[train] step=949 | loss=0.1161 | lr=3.61e-05 | epoch=2.0278
[train] step=950 | loss=0.0783 | lr=3.60e-05 | epoch=2.0300
[train] step=951 | loss=0.0949 | lr=3.59e-05 | epoch=2.0321
[train] step=952 | loss=0.1007 | lr=3.58e-05 | epoch=2.0342
[train] step=953 | loss=0.1005 | lr=3.58e-05 | epoch=2.0364
[train] step=954 | loss=0.0886 | lr=3.57e-05 | epoch=2.0385
[train] step=955 | loss=0.1405 | lr=3.56e-05 | epoch=2.0407
[train] step=956 | loss=0.0870 | lr=3.55e-05 | epoch=2.0428
[train] step=957 | loss=0.0743 | lr=3.54e-05 | epoch=2.0449
[train] step=958 | loss=0.1135 | lr=3.54e-05 | epoch=2.0471
[train] step=959 | loss=0.0898 | lr=3.53e-05 | epoch=2.0492
[train] step=960 | loss=0.0872 | lr=3.52e-05 | epoch=2.0514
[train] step=961 | loss=0.0944 | lr=3.51e-05 | epoch=2.0535
[train] step=962 | loss=0.0910 | lr=3.50e-05 | epoch=2.0556
[train] step=963 | loss=0.1052 | lr=3.50e-05 | epoch=2.0578
[train] step=964 | loss=0.0751 | lr=3.49e-05 | epoch=2.0599
[train] step=965 | loss=0.0864 | lr=3.48e-05 | epoch=2.0621
[train] step=966 | loss=0.1043 | lr=3.47e-05 | epoch=2.0642
[train] step=967 | loss=0.0886 | lr=3.47e-05 | epoch=2.0663
[train] step=968 | loss=0.1053 | lr=3.46e-05 | epoch=2.0685
[train] step=969 | loss=0.0928 | lr=3.45e-05 | epoch=2.0706
[train] step=970 | loss=0.0989 | lr=3.44e-05 | epoch=2.0728
[train] step=971 | loss=0.0967 | lr=3.43e-05 | epoch=2.0749
[train] step=972 | loss=0.1148 | lr=3.43e-05 | epoch=2.0770
[train] step=973 | loss=0.1013 | lr=3.42e-05 | epoch=2.0792
[train] step=974 | loss=0.1189 | lr=3.41e-05 | epoch=2.0813
[train] step=975 | loss=0.0902 | lr=3.40e-05 | epoch=2.0835
[train] step=976 | loss=0.0822 | lr=3.39e-05 | epoch=2.0856
[train] step=977 | loss=0.0808 | lr=3.39e-05 | epoch=2.0877
[train] step=978 | loss=0.0871 | lr=3.38e-05 | epoch=2.0899
[train] step=979 | loss=0.0798 | lr=3.37e-05 | epoch=2.0920
[train] step=980 | loss=0.0843 | lr=3.36e-05 | epoch=2.0942
[train] step=981 | loss=0.0996 | lr=3.35e-05 | epoch=2.0963
[train] step=982 | loss=0.1051 | lr=3.35e-05 | epoch=2.0984
[train] step=983 | loss=0.0932 | lr=3.34e-05 | epoch=2.1006
[train] step=984 | loss=0.0805 | lr=3.33e-05 | epoch=2.1027
[train] step=985 | loss=0.1059 | lr=3.32e-05 | epoch=2.1049
[train] step=986 | loss=0.0985 | lr=3.31e-05 | epoch=2.1070
[train] step=987 | loss=0.1142 | lr=3.31e-05 | epoch=2.1091
[train] step=988 | loss=0.0789 | lr=3.30e-05 | epoch=2.1113
[train] step=989 | loss=0.1111 | lr=3.29e-05 | epoch=2.1134
[train] step=990 | loss=0.0933 | lr=3.28e-05 | epoch=2.1156
[train] step=991 | loss=0.0931 | lr=3.28e-05 | epoch=2.1177
[train] step=992 | loss=0.1028 | lr=3.27e-05 | epoch=2.1199
[train] step=993 | loss=0.0669 | lr=3.26e-05 | epoch=2.1220
[train] step=994 | loss=0.0859 | lr=3.25e-05 | epoch=2.1241
[train] step=995 | loss=0.1094 | lr=3.24e-05 | epoch=2.1263
[train] step=996 | loss=0.0884 | lr=3.24e-05 | epoch=2.1284
[train] step=997 | loss=0.0817 | lr=3.23e-05 | epoch=2.1306
[train] step=998 | loss=0.0941 | lr=3.22e-05 | epoch=2.1327
[train] step=999 | loss=0.1106 | lr=3.21e-05 | epoch=2.1348
[train] step=1000 | loss=0.0904 | lr=3.20e-05 | epoch=2.1370
[train] step=1001 | loss=0.0842 | lr=3.20e-05 | epoch=2.1391
[train] step=1002 | loss=0.0888 | lr=3.19e-05 | epoch=2.1413
[train] step=1003 | loss=0.0860 | lr=3.18e-05 | epoch=2.1434
[train] step=1004 | loss=0.0908 | lr=3.17e-05 | epoch=2.1455
[train] step=1005 | loss=0.0941 | lr=3.16e-05 | epoch=2.1477
[train] step=1006 | loss=0.0941 | lr=3.16e-05 | epoch=2.1498
[train] step=1007 | loss=0.0957 | lr=3.15e-05 | epoch=2.1520
[train] step=1008 | loss=0.0802 | lr=3.14e-05 | epoch=2.1541
[train] step=1009 | loss=0.0924 | lr=3.13e-05 | epoch=2.1562
[train] step=1010 | loss=0.0723 | lr=3.13e-05 | epoch=2.1584
[train] step=1011 | loss=0.1255 | lr=3.12e-05 | epoch=2.1605
[train] step=1012 | loss=0.1059 | lr=3.11e-05 | epoch=2.1627
[train] step=1013 | loss=0.0968 | lr=3.10e-05 | epoch=2.1648
[train] step=1014 | loss=0.0850 | lr=3.09e-05 | epoch=2.1669
[train] step=1015 | loss=0.0782 | lr=3.09e-05 | epoch=2.1691
[train] step=1016 | loss=0.0970 | lr=3.08e-05 | epoch=2.1712
[train] step=1017 | loss=0.1071 | lr=3.07e-05 | epoch=2.1734
[train] step=1018 | loss=0.0916 | lr=3.06e-05 | epoch=2.1755
[train] step=1019 | loss=0.1135 | lr=3.05e-05 | epoch=2.1776
[train] step=1020 | loss=0.0863 | lr=3.05e-05 | epoch=2.1798
[train] step=1021 | loss=0.0850 | lr=3.04e-05 | epoch=2.1819
[train] step=1022 | loss=0.1136 | lr=3.03e-05 | epoch=2.1841
[train] step=1023 | loss=0.0887 | lr=3.02e-05 | epoch=2.1862
[train] step=1024 | loss=0.0911 | lr=3.01e-05 | epoch=2.1883
[train] step=1025 | loss=0.0907 | lr=3.01e-05 | epoch=2.1905
[train] step=1026 | loss=0.1010 | lr=3.00e-05 | epoch=2.1926
[train] step=1027 | loss=0.1048 | lr=2.99e-05 | epoch=2.1948
[train] step=1028 | loss=0.0928 | lr=2.98e-05 | epoch=2.1969
[train] step=1029 | loss=0.1241 | lr=2.97e-05 | epoch=2.1990
[train] step=1030 | loss=0.0945 | lr=2.97e-05 | epoch=2.2012
[train] step=1031 | loss=0.1034 | lr=2.96e-05 | epoch=2.2033
[train] step=1032 | loss=0.0943 | lr=2.95e-05 | epoch=2.2055
[train] step=1033 | loss=0.1068 | lr=2.94e-05 | epoch=2.2076
[train] step=1034 | loss=0.0920 | lr=2.94e-05 | epoch=2.2097
[train] step=1035 | loss=0.1036 | lr=2.93e-05 | epoch=2.2119
[train] step=1036 | loss=0.0867 | lr=2.92e-05 | epoch=2.2140
[train] step=1037 | loss=0.1192 | lr=2.91e-05 | epoch=2.2162
[train] step=1038 | loss=0.1087 | lr=2.90e-05 | epoch=2.2183
[train] step=1039 | loss=0.0932 | lr=2.90e-05 | epoch=2.2204
[train] step=1040 | loss=0.0795 | lr=2.89e-05 | epoch=2.2226
[train] step=1041 | loss=0.0817 | lr=2.88e-05 | epoch=2.2247
[train] step=1042 | loss=0.0916 | lr=2.87e-05 | epoch=2.2269
[train] step=1043 | loss=0.0832 | lr=2.86e-05 | epoch=2.2290
[train] step=1044 | loss=0.1093 | lr=2.86e-05 | epoch=2.2311
[train] step=1045 | loss=0.0822 | lr=2.85e-05 | epoch=2.2333
[train] step=1046 | loss=0.1212 | lr=2.84e-05 | epoch=2.2354
[train] step=1047 | loss=0.1124 | lr=2.83e-05 | epoch=2.2376
[train] step=1048 | loss=0.0929 | lr=2.82e-05 | epoch=2.2397
[train] step=1049 | loss=0.0999 | lr=2.82e-05 | epoch=2.2418
[train] step=1050 | loss=0.0832 | lr=2.81e-05 | epoch=2.2440
[train] step=1051 | loss=0.0811 | lr=2.80e-05 | epoch=2.2461
[train] step=1052 | loss=0.1019 | lr=2.79e-05 | epoch=2.2483
[train] step=1053 | loss=0.0965 | lr=2.78e-05 | epoch=2.2504
[train] step=1054 | loss=0.0896 | lr=2.78e-05 | epoch=2.2525
[train] step=1055 | loss=0.1020 | lr=2.77e-05 | epoch=2.2547
[train] step=1056 | loss=0.1038 | lr=2.76e-05 | epoch=2.2568
[train] step=1057 | loss=0.0874 | lr=2.75e-05 | epoch=2.2590
[train] step=1058 | loss=0.0838 | lr=2.75e-05 | epoch=2.2611
[train] step=1059 | loss=0.1024 | lr=2.74e-05 | epoch=2.2632
[train] step=1060 | loss=0.0933 | lr=2.73e-05 | epoch=2.2654
[train] step=1061 | loss=0.0918 | lr=2.72e-05 | epoch=2.2675
[train] step=1062 | loss=0.0966 | lr=2.71e-05 | epoch=2.2697
[train] step=1063 | loss=0.0733 | lr=2.71e-05 | epoch=2.2718
[train] step=1064 | loss=0.0868 | lr=2.70e-05 | epoch=2.2739
[train] step=1065 | loss=0.0892 | lr=2.69e-05 | epoch=2.2761
[train] step=1066 | loss=0.0938 | lr=2.68e-05 | epoch=2.2782
[train] step=1067 | loss=0.0841 | lr=2.67e-05 | epoch=2.2804
[train] step=1068 | loss=0.1106 | lr=2.67e-05 | epoch=2.2825
[train] step=1069 | loss=0.0771 | lr=2.66e-05 | epoch=2.2846
[train] step=1070 | loss=0.1007 | lr=2.65e-05 | epoch=2.2868
[train] step=1071 | loss=0.0912 | lr=2.64e-05 | epoch=2.2889
[train] step=1072 | loss=0.0784 | lr=2.63e-05 | epoch=2.2911
[train] step=1073 | loss=0.0824 | lr=2.63e-05 | epoch=2.2932
[train] step=1074 | loss=0.0856 | lr=2.62e-05 | epoch=2.2953
[train] step=1075 | loss=0.0978 | lr=2.61e-05 | epoch=2.2975
[train] step=1076 | loss=0.0974 | lr=2.60e-05 | epoch=2.2996
[train] step=1077 | loss=0.0891 | lr=2.59e-05 | epoch=2.3018
[train] step=1078 | loss=0.0950 | lr=2.59e-05 | epoch=2.3039
[train] step=1079 | loss=0.1082 | lr=2.58e-05 | epoch=2.3060
[train] step=1080 | loss=0.1003 | lr=2.57e-05 | epoch=2.3082
[train] step=1081 | loss=0.1183 | lr=2.56e-05 | epoch=2.3103
[train] step=1082 | loss=0.1029 | lr=2.56e-05 | epoch=2.3125
[train] step=1083 | loss=0.0958 | lr=2.55e-05 | epoch=2.3146
[train] step=1084 | loss=0.0730 | lr=2.54e-05 | epoch=2.3167
[train] step=1085 | loss=0.0893 | lr=2.53e-05 | epoch=2.3189
[train] step=1086 | loss=0.0788 | lr=2.52e-05 | epoch=2.3210
[train] step=1087 | loss=0.1058 | lr=2.52e-05 | epoch=2.3232
[train] step=1088 | loss=0.1078 | lr=2.51e-05 | epoch=2.3253
[train] step=1089 | loss=0.0834 | lr=2.50e-05 | epoch=2.3274
[train] step=1090 | loss=0.1086 | lr=2.49e-05 | epoch=2.3296
[train] step=1091 | loss=0.1053 | lr=2.48e-05 | epoch=2.3317
[train] step=1092 | loss=0.0907 | lr=2.48e-05 | epoch=2.3339
[train] step=1093 | loss=0.0860 | lr=2.47e-05 | epoch=2.3360
[train] step=1094 | loss=0.0853 | lr=2.46e-05 | epoch=2.3381
[train] step=1095 | loss=0.0939 | lr=2.45e-05 | epoch=2.3403
[train] step=1096 | loss=0.0922 | lr=2.44e-05 | epoch=2.3424
[train] step=1097 | loss=0.1117 | lr=2.44e-05 | epoch=2.3446
[train] step=1098 | loss=0.0870 | lr=2.43e-05 | epoch=2.3467
[train] step=1099 | loss=0.0923 | lr=2.42e-05 | epoch=2.3488
[train] step=1100 | loss=0.0876 | lr=2.41e-05 | epoch=2.3510
[train] step=1101 | loss=0.1042 | lr=2.41e-05 | epoch=2.3531
[train] step=1102 | loss=0.0997 | lr=2.40e-05 | epoch=2.3553
[train] step=1103 | loss=0.0794 | lr=2.39e-05 | epoch=2.3574
[train] step=1104 | loss=0.1021 | lr=2.38e-05 | epoch=2.3596
[train] step=1105 | loss=0.0926 | lr=2.37e-05 | epoch=2.3617
[train] step=1106 | loss=0.1373 | lr=2.37e-05 | epoch=2.3638
[train] step=1107 | loss=0.0971 | lr=2.36e-05 | epoch=2.3660
[train] step=1108 | loss=0.0925 | lr=2.35e-05 | epoch=2.3681
[train] step=1109 | loss=0.1019 | lr=2.34e-05 | epoch=2.3703
[train] step=1110 | loss=0.0953 | lr=2.33e-05 | epoch=2.3724
[train] step=1111 | loss=0.0947 | lr=2.33e-05 | epoch=2.3745
[train] step=1112 | loss=0.0868 | lr=2.32e-05 | epoch=2.3767
[train] step=1113 | loss=0.1093 | lr=2.31e-05 | epoch=2.3788
[train] step=1114 | loss=0.1138 | lr=2.30e-05 | epoch=2.3810
[train] step=1115 | loss=0.0852 | lr=2.29e-05 | epoch=2.3831
[train] step=1116 | loss=0.1143 | lr=2.29e-05 | epoch=2.3852
[train] step=1117 | loss=0.0944 | lr=2.28e-05 | epoch=2.3874
[train] step=1118 | loss=0.0890 | lr=2.27e-05 | epoch=2.3895
[train] step=1119 | loss=0.0955 | lr=2.26e-05 | epoch=2.3917
[train] step=1120 | loss=0.0933 | lr=2.25e-05 | epoch=2.3938
[train] step=1121 | loss=0.0892 | lr=2.25e-05 | epoch=2.3959
[train] step=1122 | loss=0.1075 | lr=2.24e-05 | epoch=2.3981
[train] step=1123 | loss=0.1161 | lr=2.23e-05 | epoch=2.4002
[train] step=1124 | loss=0.0908 | lr=2.22e-05 | epoch=2.4024
[train] step=1125 | loss=0.0870 | lr=2.22e-05 | epoch=2.4045
[train] step=1126 | loss=0.0823 | lr=2.21e-05 | epoch=2.4066
[train] step=1127 | loss=0.0939 | lr=2.20e-05 | epoch=2.4088
[train] step=1128 | loss=0.0924 | lr=2.19e-05 | epoch=2.4109
[train] step=1129 | loss=0.0914 | lr=2.18e-05 | epoch=2.4131
[train] step=1130 | loss=0.0854 | lr=2.18e-05 | epoch=2.4152
[train] step=1131 | loss=0.1037 | lr=2.17e-05 | epoch=2.4173
[train] step=1132 | loss=0.0774 | lr=2.16e-05 | epoch=2.4195
[train] step=1133 | loss=0.0818 | lr=2.15e-05 | epoch=2.4216
[train] step=1134 | loss=0.0983 | lr=2.14e-05 | epoch=2.4238
[train] step=1135 | loss=0.1034 | lr=2.14e-05 | epoch=2.4259
[train] step=1136 | loss=0.1046 | lr=2.13e-05 | epoch=2.4280
[train] step=1137 | loss=0.0780 | lr=2.12e-05 | epoch=2.4302
[train] step=1138 | loss=0.0880 | lr=2.11e-05 | epoch=2.4323
[train] step=1139 | loss=0.0937 | lr=2.10e-05 | epoch=2.4345
[train] step=1140 | loss=0.0969 | lr=2.10e-05 | epoch=2.4366
[train] step=1141 | loss=0.1162 | lr=2.09e-05 | epoch=2.4387
[train] step=1142 | loss=0.0835 | lr=2.08e-05 | epoch=2.4409
[train] step=1143 | loss=0.0938 | lr=2.07e-05 | epoch=2.4430
[train] step=1144 | loss=0.0892 | lr=2.06e-05 | epoch=2.4452
[train] step=1145 | loss=0.0794 | lr=2.06e-05 | epoch=2.4473
[train] step=1146 | loss=0.0956 | lr=2.05e-05 | epoch=2.4494
[train] step=1147 | loss=0.0910 | lr=2.04e-05 | epoch=2.4516
[train] step=1148 | loss=0.1354 | lr=2.03e-05 | epoch=2.4537
[train] step=1149 | loss=0.1073 | lr=2.03e-05 | epoch=2.4559
[train] step=1150 | loss=0.0910 | lr=2.02e-05 | epoch=2.4580
[train] step=1151 | loss=0.0927 | lr=2.01e-05 | epoch=2.4601
[train] step=1152 | loss=0.0936 | lr=2.00e-05 | epoch=2.4623
[train] step=1153 | loss=0.1226 | lr=1.99e-05 | epoch=2.4644
[train] step=1154 | loss=0.0971 | lr=1.99e-05 | epoch=2.4666
[train] step=1155 | loss=0.0884 | lr=1.98e-05 | epoch=2.4687
[train] step=1156 | loss=0.0899 | lr=1.97e-05 | epoch=2.4708
[train] step=1157 | loss=0.0951 | lr=1.96e-05 | epoch=2.4730
[train] step=1158 | loss=0.0872 | lr=1.95e-05 | epoch=2.4751
[train] step=1159 | loss=0.1028 | lr=1.95e-05 | epoch=2.4773
[train] step=1160 | loss=0.0901 | lr=1.94e-05 | epoch=2.4794
[train] step=1161 | loss=0.0884 | lr=1.93e-05 | epoch=2.4815
[train] step=1162 | loss=0.0907 | lr=1.92e-05 | epoch=2.4837
[train] step=1163 | loss=0.0891 | lr=1.91e-05 | epoch=2.4858
[train] step=1164 | loss=0.0782 | lr=1.91e-05 | epoch=2.4880
[train] step=1165 | loss=0.0729 | lr=1.90e-05 | epoch=2.4901

Saving model checkpoint to output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1165
2026-04-06 05:33:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:33:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 05:33:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:33:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1165\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1165\tokenizer_config.json

[train] step=1166 | loss=0.0865 | lr=1.89e-05 | epoch=2.4922
[train] step=1167 | loss=0.0870 | lr=1.88e-05 | epoch=2.4944
[train] step=1168 | loss=0.0904 | lr=1.88e-05 | epoch=2.4965
[train] step=1169 | loss=0.1198 | lr=1.87e-05 | epoch=2.4987
[train] step=1170 | loss=0.0797 | lr=1.86e-05 | epoch=2.5008
[train] step=1171 | loss=0.0817 | lr=1.85e-05 | epoch=2.5029
[train] step=1172 | loss=0.1003 | lr=1.84e-05 | epoch=2.5051
[train] step=1173 | loss=0.0709 | lr=1.84e-05 | epoch=2.5072
[train] step=1174 | loss=0.0778 | lr=1.83e-05 | epoch=2.5094
[train] step=1175 | loss=0.0845 | lr=1.82e-05 | epoch=2.5115
[train] step=1176 | loss=0.0963 | lr=1.81e-05 | epoch=2.5136
[train] step=1177 | loss=0.1162 | lr=1.80e-05 | epoch=2.5158
[train] step=1178 | loss=0.0900 | lr=1.80e-05 | epoch=2.5179
[train] step=1179 | loss=0.0922 | lr=1.79e-05 | epoch=2.5201
[train] step=1180 | loss=0.0864 | lr=1.78e-05 | epoch=2.5222
[train] step=1181 | loss=0.1124 | lr=1.77e-05 | epoch=2.5243
[train] step=1182 | loss=0.0867 | lr=1.76e-05 | epoch=2.5265
[train] step=1183 | loss=0.1078 | lr=1.76e-05 | epoch=2.5286
[train] step=1184 | loss=0.0981 | lr=1.75e-05 | epoch=2.5308
[train] step=1185 | loss=0.0958 | lr=1.74e-05 | epoch=2.5329
[train] step=1186 | loss=0.0899 | lr=1.73e-05 | epoch=2.5350
[train] step=1187 | loss=0.0889 | lr=1.72e-05 | epoch=2.5372
[train] step=1188 | loss=0.0843 | lr=1.72e-05 | epoch=2.5393
[train] step=1189 | loss=0.0961 | lr=1.71e-05 | epoch=2.5415
[train] step=1190 | loss=0.0998 | lr=1.70e-05 | epoch=2.5436
[train] step=1191 | loss=0.1230 | lr=1.69e-05 | epoch=2.5457
[train] step=1192 | loss=0.0761 | lr=1.69e-05 | epoch=2.5479
[train] step=1193 | loss=0.0793 | lr=1.68e-05 | epoch=2.5500
[train] step=1194 | loss=0.0958 | lr=1.67e-05 | epoch=2.5522
[train] step=1195 | loss=0.1154 | lr=1.66e-05 | epoch=2.5543
[train] step=1196 | loss=0.0896 | lr=1.65e-05 | epoch=2.5564
[train] step=1197 | loss=0.1011 | lr=1.65e-05 | epoch=2.5586
[train] step=1198 | loss=0.1025 | lr=1.64e-05 | epoch=2.5607
[train] step=1199 | loss=0.0833 | lr=1.63e-05 | epoch=2.5629
[train] step=1200 | loss=0.1001 | lr=1.62e-05 | epoch=2.5650
[train] step=1201 | loss=0.0899 | lr=1.61e-05 | epoch=2.5671
[train] step=1202 | loss=0.0977 | lr=1.61e-05 | epoch=2.5693
[train] step=1203 | loss=0.0968 | lr=1.60e-05 | epoch=2.5714
[train] step=1204 | loss=0.1094 | lr=1.59e-05 | epoch=2.5736
[train] step=1205 | loss=0.0894 | lr=1.58e-05 | epoch=2.5757
[train] step=1206 | loss=0.0853 | lr=1.57e-05 | epoch=2.5778
[train] step=1207 | loss=0.0957 | lr=1.57e-05 | epoch=2.5800
[train] step=1208 | loss=0.0798 | lr=1.56e-05 | epoch=2.5821
[train] step=1209 | loss=0.0955 | lr=1.55e-05 | epoch=2.5843
[train] step=1210 | loss=0.0997 | lr=1.54e-05 | epoch=2.5864
[train] step=1211 | loss=0.1152 | lr=1.53e-05 | epoch=2.5886
[train] step=1212 | loss=0.0939 | lr=1.53e-05 | epoch=2.5907
[train] step=1213 | loss=0.0904 | lr=1.52e-05 | epoch=2.5928
[train] step=1214 | loss=0.0762 | lr=1.51e-05 | epoch=2.5950
[train] step=1215 | loss=0.1000 | lr=1.50e-05 | epoch=2.5971
[train] step=1216 | loss=0.1138 | lr=1.50e-05 | epoch=2.5993
[train] step=1217 | loss=0.0991 | lr=1.49e-05 | epoch=2.6014
[train] step=1218 | loss=0.0930 | lr=1.48e-05 | epoch=2.6035
[train] step=1219 | loss=0.0964 | lr=1.47e-05 | epoch=2.6057
[train] step=1220 | loss=0.0940 | lr=1.46e-05 | epoch=2.6078
[train] step=1221 | loss=0.0979 | lr=1.46e-05 | epoch=2.6100
[train] step=1222 | loss=0.1162 | lr=1.45e-05 | epoch=2.6121
[train] step=1223 | loss=0.1032 | lr=1.44e-05 | epoch=2.6142
[train] step=1224 | loss=0.0796 | lr=1.43e-05 | epoch=2.6164
[train] step=1225 | loss=0.0909 | lr=1.42e-05 | epoch=2.6185
[train] step=1226 | loss=0.0839 | lr=1.42e-05 | epoch=2.6207
[train] step=1227 | loss=0.0872 | lr=1.41e-05 | epoch=2.6228
[train] step=1228 | loss=0.1007 | lr=1.40e-05 | epoch=2.6249
[train] step=1229 | loss=0.0883 | lr=1.39e-05 | epoch=2.6271
[train] step=1230 | loss=0.0961 | lr=1.38e-05 | epoch=2.6292
[train] step=1231 | loss=0.0671 | lr=1.38e-05 | epoch=2.6314
[train] step=1232 | loss=0.1004 | lr=1.37e-05 | epoch=2.6335
[train] step=1233 | loss=0.1108 | lr=1.36e-05 | epoch=2.6356
[train] step=1234 | loss=0.1024 | lr=1.35e-05 | epoch=2.6378
[train] step=1235 | loss=0.1057 | lr=1.34e-05 | epoch=2.6399
[train] step=1236 | loss=0.0751 | lr=1.34e-05 | epoch=2.6421
[train] step=1237 | loss=0.0881 | lr=1.33e-05 | epoch=2.6442
[train] step=1238 | loss=0.0850 | lr=1.32e-05 | epoch=2.6463
[train] step=1239 | loss=0.1100 | lr=1.31e-05 | epoch=2.6485
[train] step=1240 | loss=0.1012 | lr=1.31e-05 | epoch=2.6506
[train] step=1241 | loss=0.0807 | lr=1.30e-05 | epoch=2.6528
[train] step=1242 | loss=0.1135 | lr=1.29e-05 | epoch=2.6549
[train] step=1243 | loss=0.0859 | lr=1.28e-05 | epoch=2.6570
[train] step=1244 | loss=0.1116 | lr=1.27e-05 | epoch=2.6592
[train] step=1245 | loss=0.0819 | lr=1.27e-05 | epoch=2.6613
[train] step=1246 | loss=0.0851 | lr=1.26e-05 | epoch=2.6635
[train] step=1247 | loss=0.1063 | lr=1.25e-05 | epoch=2.6656
[train] step=1248 | loss=0.0896 | lr=1.24e-05 | epoch=2.6677
[train] step=1249 | loss=0.0781 | lr=1.23e-05 | epoch=2.6699
[train] step=1250 | loss=0.0740 | lr=1.23e-05 | epoch=2.6720
[train] step=1251 | loss=0.1188 | lr=1.22e-05 | epoch=2.6742
[train] step=1252 | loss=0.0885 | lr=1.21e-05 | epoch=2.6763
[train] step=1253 | loss=0.0977 | lr=1.20e-05 | epoch=2.6784
[train] step=1254 | loss=0.0916 | lr=1.19e-05 | epoch=2.6806
[train] step=1255 | loss=0.0891 | lr=1.19e-05 | epoch=2.6827
[train] step=1256 | loss=0.0848 | lr=1.18e-05 | epoch=2.6849
[train] step=1257 | loss=0.0710 | lr=1.17e-05 | epoch=2.6870
[train] step=1258 | loss=0.1005 | lr=1.16e-05 | epoch=2.6891
[train] step=1259 | loss=0.1113 | lr=1.16e-05 | epoch=2.6913
[train] step=1260 | loss=0.0878 | lr=1.15e-05 | epoch=2.6934
[train] step=1261 | loss=0.0915 | lr=1.14e-05 | epoch=2.6956
[train] step=1262 | loss=0.1241 | lr=1.13e-05 | epoch=2.6977
[train] step=1263 | loss=0.0848 | lr=1.12e-05 | epoch=2.6998
[train] step=1264 | loss=0.0905 | lr=1.12e-05 | epoch=2.7020
[train] step=1265 | loss=0.0972 | lr=1.11e-05 | epoch=2.7041
[train] step=1266 | loss=0.1189 | lr=1.10e-05 | epoch=2.7063
[train] step=1267 | loss=0.0955 | lr=1.09e-05 | epoch=2.7084
[train] step=1268 | loss=0.1210 | lr=1.08e-05 | epoch=2.7105
[train] step=1269 | loss=0.1198 | lr=1.08e-05 | epoch=2.7127
[train] step=1270 | loss=0.0898 | lr=1.07e-05 | epoch=2.7148
[train] step=1271 | loss=0.0816 | lr=1.06e-05 | epoch=2.7170
[train] step=1272 | loss=0.0831 | lr=1.05e-05 | epoch=2.7191
[train] step=1273 | loss=0.0952 | lr=1.04e-05 | epoch=2.7212
[train] step=1274 | loss=0.0868 | lr=1.04e-05 | epoch=2.7234
[train] step=1275 | loss=0.0986 | lr=1.03e-05 | epoch=2.7255
[train] step=1276 | loss=0.0709 | lr=1.02e-05 | epoch=2.7277
[train] step=1277 | loss=0.0966 | lr=1.01e-05 | epoch=2.7298
[train] step=1278 | loss=0.0894 | lr=1.00e-05 | epoch=2.7319
[train] step=1279 | loss=0.1162 | lr=9.97e-06 | epoch=2.7341
[train] step=1280 | loss=0.0994 | lr=9.89e-06 | epoch=2.7362
[train] step=1281 | loss=0.0881 | lr=9.81e-06 | epoch=2.7384
[train] step=1282 | loss=0.0953 | lr=9.73e-06 | epoch=2.7405
[train] step=1283 | loss=0.0876 | lr=9.65e-06 | epoch=2.7426
[train] step=1284 | loss=0.1176 | lr=9.57e-06 | epoch=2.7448
[train] step=1285 | loss=0.0964 | lr=9.49e-06 | epoch=2.7469
[train] step=1286 | loss=0.0782 | lr=9.41e-06 | epoch=2.7491
[train] step=1287 | loss=0.0928 | lr=9.34e-06 | epoch=2.7512
[train] step=1288 | loss=0.1012 | lr=9.26e-06 | epoch=2.7533
[train] step=1289 | loss=0.0913 | lr=9.18e-06 | epoch=2.7555
[train] step=1290 | loss=0.1147 | lr=9.10e-06 | epoch=2.7576
[train] step=1291 | loss=0.0820 | lr=9.02e-06 | epoch=2.7598
[train] step=1292 | loss=0.0961 | lr=8.94e-06 | epoch=2.7619
[train] step=1293 | loss=0.0846 | lr=8.86e-06 | epoch=2.7640
[train] step=1294 | loss=0.1096 | lr=8.78e-06 | epoch=2.7662
[train] step=1295 | loss=0.0970 | lr=8.70e-06 | epoch=2.7683
[train] step=1296 | loss=0.1199 | lr=8.62e-06 | epoch=2.7705
[train] step=1297 | loss=0.0898 | lr=8.54e-06 | epoch=2.7726
[train] step=1298 | loss=0.0767 | lr=8.47e-06 | epoch=2.7747
[train] step=1299 | loss=0.1028 | lr=8.39e-06 | epoch=2.7769
[train] step=1300 | loss=0.0897 | lr=8.31e-06 | epoch=2.7790
[train] step=1301 | loss=0.0962 | lr=8.23e-06 | epoch=2.7812
[train] step=1302 | loss=0.0940 | lr=8.15e-06 | epoch=2.7833
[train] step=1303 | loss=0.0960 | lr=8.07e-06 | epoch=2.7854
[train] step=1304 | loss=0.0942 | lr=7.99e-06 | epoch=2.7876
[train] step=1305 | loss=0.1088 | lr=7.91e-06 | epoch=2.7897
[train] step=1306 | loss=0.1072 | lr=7.83e-06 | epoch=2.7919
[train] step=1307 | loss=0.0762 | lr=7.75e-06 | epoch=2.7940
[train] step=1308 | loss=0.0861 | lr=7.67e-06 | epoch=2.7961
[train] step=1309 | loss=0.1041 | lr=7.59e-06 | epoch=2.7983
[train] step=1310 | loss=0.0865 | lr=7.52e-06 | epoch=2.8004
[train] step=1311 | loss=0.1097 | lr=7.44e-06 | epoch=2.8026
[train] step=1312 | loss=0.0912 | lr=7.36e-06 | epoch=2.8047
[train] step=1313 | loss=0.0982 | lr=7.28e-06 | epoch=2.8068
[train] step=1314 | loss=0.0912 | lr=7.20e-06 | epoch=2.8090
[train] step=1315 | loss=0.1025 | lr=7.12e-06 | epoch=2.8111
[train] step=1316 | loss=0.0868 | lr=7.04e-06 | epoch=2.8133
[train] step=1317 | loss=0.1020 | lr=6.96e-06 | epoch=2.8154
[train] step=1318 | loss=0.0962 | lr=6.88e-06 | epoch=2.8175
[train] step=1319 | loss=0.0725 | lr=6.80e-06 | epoch=2.8197
[train] step=1320 | loss=0.0877 | lr=6.72e-06 | epoch=2.8218
[train] step=1321 | loss=0.0866 | lr=6.65e-06 | epoch=2.8240
[train] step=1322 | loss=0.0739 | lr=6.57e-06 | epoch=2.8261
[train] step=1323 | loss=0.0782 | lr=6.49e-06 | epoch=2.8283
[train] step=1324 | loss=0.0981 | lr=6.41e-06 | epoch=2.8304
[train] step=1325 | loss=0.0801 | lr=6.33e-06 | epoch=2.8325
[train] step=1326 | loss=0.0909 | lr=6.25e-06 | epoch=2.8347
[train] step=1327 | loss=0.0969 | lr=6.17e-06 | epoch=2.8368
[train] step=1328 | loss=0.1019 | lr=6.09e-06 | epoch=2.8390
[train] step=1329 | loss=0.1002 | lr=6.01e-06 | epoch=2.8411
[train] step=1330 | loss=0.1052 | lr=5.93e-06 | epoch=2.8432
[train] step=1331 | loss=0.0770 | lr=5.85e-06 | epoch=2.8454
[train] step=1332 | loss=0.1219 | lr=5.78e-06 | epoch=2.8475
[train] step=1333 | loss=0.0909 | lr=5.70e-06 | epoch=2.8497
[train] step=1334 | loss=0.0926 | lr=5.62e-06 | epoch=2.8518
[train] step=1335 | loss=0.1128 | lr=5.54e-06 | epoch=2.8539
[train] step=1336 | loss=0.0810 | lr=5.46e-06 | epoch=2.8561
[train] step=1337 | loss=0.0956 | lr=5.38e-06 | epoch=2.8582
[train] step=1338 | loss=0.0983 | lr=5.30e-06 | epoch=2.8604
[train] step=1339 | loss=0.1258 | lr=5.22e-06 | epoch=2.8625
[train] step=1340 | loss=0.1090 | lr=5.14e-06 | epoch=2.8646
[train] step=1341 | loss=0.0817 | lr=5.06e-06 | epoch=2.8668
[train] step=1342 | loss=0.0935 | lr=4.98e-06 | epoch=2.8689
[train] step=1343 | loss=0.1035 | lr=4.91e-06 | epoch=2.8711
[train] step=1344 | loss=0.0835 | lr=4.83e-06 | epoch=2.8732
[train] step=1345 | loss=0.0923 | lr=4.75e-06 | epoch=2.8753
[train] step=1346 | loss=0.1092 | lr=4.67e-06 | epoch=2.8775
[train] step=1347 | loss=0.1064 | lr=4.59e-06 | epoch=2.8796
[train] step=1348 | loss=0.1156 | lr=4.51e-06 | epoch=2.8818
[train] step=1349 | loss=0.0825 | lr=4.43e-06 | epoch=2.8839
[train] step=1350 | loss=0.1030 | lr=4.35e-06 | epoch=2.8860
[train] step=1351 | loss=0.1072 | lr=4.27e-06 | epoch=2.8882
[train] step=1352 | loss=0.0933 | lr=4.19e-06 | epoch=2.8903
[train] step=1353 | loss=0.0933 | lr=4.11e-06 | epoch=2.8925
[train] step=1354 | loss=0.0832 | lr=4.03e-06 | epoch=2.8946
[train] step=1355 | loss=0.1085 | lr=3.96e-06 | epoch=2.8967
[train] step=1356 | loss=0.0863 | lr=3.88e-06 | epoch=2.8989
[train] step=1357 | loss=0.1086 | lr=3.80e-06 | epoch=2.9010
[train] step=1358 | loss=0.0827 | lr=3.72e-06 | epoch=2.9032
[train] step=1359 | loss=0.0926 | lr=3.64e-06 | epoch=2.9053
[train] step=1360 | loss=0.0894 | lr=3.56e-06 | epoch=2.9074
[train] step=1361 | loss=0.0833 | lr=3.48e-06 | epoch=2.9096
[train] step=1362 | loss=0.0950 | lr=3.40e-06 | epoch=2.9117
[train] step=1363 | loss=0.0854 | lr=3.32e-06 | epoch=2.9139
[train] step=1364 | loss=0.0948 | lr=3.24e-06 | epoch=2.9160
[train] step=1365 | loss=0.1098 | lr=3.16e-06 | epoch=2.9181
[train] step=1366 | loss=0.1041 | lr=3.09e-06 | epoch=2.9203
[train] step=1367 | loss=0.1087 | lr=3.01e-06 | epoch=2.9224
[train] step=1368 | loss=0.0622 | lr=2.93e-06 | epoch=2.9246
[train] step=1369 | loss=0.0827 | lr=2.85e-06 | epoch=2.9267
[train] step=1370 | loss=0.0841 | lr=2.77e-06 | epoch=2.9288
[train] step=1371 | loss=0.0700 | lr=2.69e-06 | epoch=2.9310
[train] step=1372 | loss=0.0995 | lr=2.61e-06 | epoch=2.9331
[train] step=1373 | loss=0.1001 | lr=2.53e-06 | epoch=2.9353
[train] step=1374 | loss=0.0824 | lr=2.45e-06 | epoch=2.9374
[train] step=1375 | loss=0.1190 | lr=2.37e-06 | epoch=2.9395
[train] step=1376 | loss=0.0996 | lr=2.29e-06 | epoch=2.9417
[train] step=1377 | loss=0.0792 | lr=2.22e-06 | epoch=2.9438
[train] step=1378 | loss=0.1070 | lr=2.14e-06 | epoch=2.9460
[train] step=1379 | loss=0.0845 | lr=2.06e-06 | epoch=2.9481
[train] step=1380 | loss=0.1048 | lr=1.98e-06 | epoch=2.9502
[train] step=1381 | loss=0.0938 | lr=1.90e-06 | epoch=2.9524
[train] step=1382 | loss=0.0773 | lr=1.82e-06 | epoch=2.9545
[train] step=1383 | loss=0.0834 | lr=1.74e-06 | epoch=2.9567
[train] step=1384 | loss=0.0858 | lr=1.66e-06 | epoch=2.9588
[train] step=1385 | loss=0.0996 | lr=1.58e-06 | epoch=2.9609
[train] step=1386 | loss=0.0892 | lr=1.50e-06 | epoch=2.9631
[train] step=1387 | loss=0.0974 | lr=1.42e-06 | epoch=2.9652
[train] step=1388 | loss=0.1008 | lr=1.34e-06 | epoch=2.9674
[train] step=1389 | loss=0.0971 | lr=1.27e-06 | epoch=2.9695
[train] step=1390 | loss=0.0965 | lr=1.19e-06 | epoch=2.9716
[train] step=1391 | loss=0.0959 | lr=1.11e-06 | epoch=2.9738
[train] step=1392 | loss=0.0877 | lr=1.03e-06 | epoch=2.9759
[train] step=1393 | loss=0.0827 | lr=9.49e-07 | epoch=2.9781
[train] step=1394 | loss=0.0866 | lr=8.70e-07 | epoch=2.9802
[train] step=1395 | loss=0.0822 | lr=7.91e-07 | epoch=2.9823
[train] step=1396 | loss=0.0739 | lr=7.12e-07 | epoch=2.9845
[train] step=1397 | loss=0.0985 | lr=6.33e-07 | epoch=2.9866
[train] step=1398 | loss=0.0977 | lr=5.54e-07 | epoch=2.9888

Saving model checkpoint to output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1398
2026-04-06 05:42:53 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:42:53 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 05:42:53 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:42:53 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1398\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1398\tokenizer_config.json

[train] step=1399 | loss=0.0994 | lr=4.75e-07 | epoch=2.9909
[train] step=1400 | loss=0.1078 | lr=3.96e-07 | epoch=2.9930
[train] step=1401 | loss=0.0799 | lr=3.16e-07 | epoch=2.9952
[train] step=1402 | loss=0.0922 | lr=2.37e-07 | epoch=2.9973
[train] step=1403 | loss=0.1230 | lr=1.58e-07 | epoch=2.9995
[train] step=1404 | loss=0.0859 | lr=7.91e-08 | epoch=3.0000

Saving model checkpoint to output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1404
2026-04-06 05:43:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:43:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 05:43:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:43:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1404\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\checkpoint-1404\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=1404 | epoch=3.0000
[train] finished | global_step=1404

Saving model checkpoint to output\fine_tune\run_004_lr1e-4_r32_a64_ep3
2026-04-06 05:43:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:43:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-04-06 05:43:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-06 05:43:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at C:\Users\Admin\.cache\huggingface\hub\models--Qwen--Qwen2-1.5B\snapshots\8a16abf2848eda07cc5253dec660bf1ce007ad7a\config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 131072,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\tokenizer_config.json
chat template saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\chat_template.jinja
tokenizer config file saved in output\fine_tune\run_004_lr1e-4_r32_a64_ep3\tokenizer_config.json
2026-04-06 05:43:08 | INFO     | root | Done run 5/5: C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\run_004_lr1e-4_r32_a64_ep3

Wrote sweep index: C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune\sweep_index.json
Finished: total=5, executed=5, skipped=0.
Artifacts under:
  C:\Users\Admin\Desktop\smu\LLM-project\output\fine_tune