# Fine-tune (LoRA)

Fine-tunes a configurable Qwen model on GSM8K using LoRA. Artifacts go to `output/fine_tune/` (gitignored).

| Output | Contents |
|--------|---------|
| Cell output | tqdm bar + `[train] step=… loss=… lr=… epoch=…` per log event |
| `training_run.log` | Timestamped log, appended each run |
| `trainer_log_history.json` | Per-step `loss`, `learning_rate`, `epoch` from HF Trainer |
| `training_summary.json` | Hyperparameters + final loss / step / epoch |
| `adapter_*/`, checkpoints | Saved by HF Trainer under the run folder |

**Single run:** `RUN_HYPERPARAMETER_SWEEP = False` — uses defaults from `hyperparameters.py`.  
**Sweep:** `True` — one run per entry in `PARAM_COMBINATIONS`, each in its own subfolder (`run_000_…`).

Run cells top to bottom.

### 1 — Imports and callback

Imports the stack and defines `NotebookProgressCallback` (prints `[train]` lines per log event). Run once per session.

In [1]:
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import torch
import transformers
from transformers import TrainerCallback

from qwen_math_flow.download_model import download_qwen_25_07b
from qwen_math_flow.load_dataset import format_gsm8k_as_chat, load_and_tokenize_math
from qwen_math_flow.lora_finetune import create_lora_model, run_finetune


class NotebookProgressCallback(TrainerCallback):
    """Print one line per Trainer log so loss / lr / epoch show in the notebook while training."""

    def on_train_begin(self, args, state, control, **kwargs):
        print(
            "[train] started | "
            f"epochs={args.num_train_epochs} | log every {args.logging_steps} step(s) | "
            "progress bar + metrics lines below",
            flush=True,
        )

    def on_log(self, args, state, control, logs=None, **kwargs):
        if not logs:
            return
        parts = [f"step={state.global_step}"]
        if logs.get("loss") is not None:
            parts.append(f"loss={logs['loss']:.4f}")
        if logs.get("learning_rate") is not None:
            parts.append(f"lr={logs['learning_rate']:.2e}")
        if logs.get("epoch") is not None:
            parts.append(f"epoch={logs['epoch']:.4f}")
        print("[train] " + " | ".join(parts), flush=True)

    def on_train_end(self, args, state, control, **kwargs):
        print(f"[train] finished | global_step={state.global_step}", flush=True)

/common/home/users/c/chinyee.lew.2022/jupyterlab-venv-tf-217/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 2 — Config

Set the output path, sweep toggle, and logging verbosity. Training defaults (LR, LoRA rank, batch size, etc.) come from `hyperparameters.py`; entries in `PARAM_COMBINATIONS` override only the keys they list.

Re-run this cell whenever you change sweep settings.

In [2]:
from itertools import product

from qwen_math_flow.hyperparameters import (
    DATASET_NAME,
    DATASET_SPLIT,
    GRADIENT_ACCUMULATION_STEPS,
    LEARNING_RATE,
    LOAD_IN_4BIT,
    LORA_ALPHA,
    LORA_R,
    MAX_LENGTH,
    MAX_TRAIN_SAMPLES,
    MODEL_CACHE_DIR,
    NUM_EPOCHS,
    PER_DEVICE_TRAIN_BATCH_SIZE,
)

OUTPUT_BASE = "output/fine_tune"
MODEL_NAME = "Qwen/Qwen2-1.5B"

# False: one run using hyperparameters.py only. True: one run per dict in PARAM_COMBINATIONS.
RUN_HYPERPARAMETER_SWEEP = True

# Sweeps: each dict can override training keys; missing keys use hyperparameters.py defaults.
# Broader search space (edit these lists to expand/shrink):
LR_GRID = [1e-5, 2e-5, 3e-5, 5e-5, 7e-5, 1e-4]
LORA_R_GRID = [8, 16, 32]
EPOCHS_GRID = [3]
MAX_TRAIN_SAMPLES_GRID = [None]  # use [2000, 4000, None] for faster pilot + full runs

PARAM_COMBINATIONS = [
    {
        "learning_rate": lr,
        "lora_r": r,
        "lora_alpha": r * 2,
        "num_epochs": ep,
        "max_train_samples": m,
    }
    for lr, r, ep, m in product(LR_GRID, LORA_R_GRID, EPOCHS_GRID, MAX_TRAIN_SAMPLES_GRID)
]
# Current size: 6 * 3 * 1 * 1 = 18 combinations.


def merged_training_params(overrides: dict) -> dict:
    """Defaults from hyperparameters.py, overridden by one sweep row."""
    return {
        "learning_rate": overrides.get("learning_rate", LEARNING_RATE),
        "lora_r": overrides.get("lora_r", LORA_R),
        "lora_alpha": overrides.get("lora_alpha", LORA_ALPHA),
        "num_epochs": overrides.get("num_epochs", 3),
        "per_device_train_batch_size": overrides.get(
            "per_device_train_batch_size", PER_DEVICE_TRAIN_BATCH_SIZE
        ),
        "gradient_accumulation_steps": overrides.get(
            "gradient_accumulation_steps", GRADIENT_ACCUMULATION_STEPS
        ),
        "max_length": overrides.get("max_length", MAX_LENGTH),
        "max_train_samples": overrides.get("max_train_samples", MAX_TRAIN_SAMPLES),
    }


def combination_subdir(index: int, m: dict) -> str:
    """Unique folder name for one combination."""
    lr = m["learning_rate"]
    lr_s = f"{lr:.0e}".replace("e-0", "e-").replace("e+0", "e+")
    return f"run_{index:03d}_lr{lr_s}_r{m['lora_r']}_a{m['lora_alpha']}_ep{m['num_epochs']}"


SWEEP_RUNS = PARAM_COMBINATIONS if RUN_HYPERPARAMETER_SWEEP else [{}]
NUM_COMBINATIONS = len(SWEEP_RUNS)

# Resume mode: skip run folders that already contain completed summaries.
RESUME_INCOMPLETE_ONLY = True

# Trainer: log loss / lr every N steps (1 = every step — most verbose)
LOGGING_STEPS = 1
SHOW_NOTEBOOK_LOG_LINES = True
DISABLE_TQDM = False
TRANSFORMERS_DEBUG = False

Path(OUTPUT_BASE).mkdir(parents=True, exist_ok=True)
print(f"Output base: {Path(OUTPUT_BASE).resolve()}")
print(f"Model: {MODEL_NAME}")
print(f"RUN_HYPERPARAMETER_SWEEP={RUN_HYPERPARAMETER_SWEEP}  →  {NUM_COMBINATIONS} training run(s)")
if RUN_HYPERPARAMETER_SWEEP:
    for i, o in enumerate(PARAM_COMBINATIONS):
        print(f"  [{i}] {o}  →  {combination_subdir(i, merged_training_params(o))}")
print(f"RESUME_INCOMPLETE_ONLY={RESUME_INCOMPLETE_ONLY}")
print(
    f"LOGGING_STEPS={LOGGING_STEPS}  SHOW_NOTEBOOK_LOG_LINES={SHOW_NOTEBOOK_LOG_LINES}  "
    f"DISABLE_TQDM={DISABLE_TQDM}  TRANSFORMERS_DEBUG={TRANSFORMERS_DEBUG}"
)

Output base: /common/home/users/c/chinyee.lew.2022/output/fine_tune
RUN_HYPERPARAMETER_SWEEP=True  →  18 training run(s)
  [0] {'learning_rate': 1e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 3, 'max_train_samples': None}  →  run_000_lr1e-5_r8_a16_ep3
  [1] {'learning_rate': 1e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'max_train_samples': None}  →  run_001_lr1e-5_r16_a32_ep3
  [2] {'learning_rate': 1e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'max_train_samples': None}  →  run_002_lr1e-5_r32_a64_ep3
  [3] {'learning_rate': 2e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 3, 'max_train_samples': None}  →  run_003_lr2e-5_r8_a16_ep3
  [4] {'learning_rate': 2e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'max_train_samples': None}  →  run_004_lr2e-5_r16_a32_ep3
  [5] {'learning_rate': 2e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'max_train_samples': None}  →  run_005_lr2e-5_r32_a64_ep3
  [6] {'learning_rate': 3e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 3, 'max_train_samples': None}  →  run_006_lr3e-5_r8_a16_ep3
  [7] {'learning_rate': 3e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'max_train_samples': None}  →  run_007_lr3e-5_r16_a32_ep3
  [8] {'learning_rate': 3e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'max_train_samples': None}  →  run_008_lr3e-5_r32_a64_ep3
  [9] {'learning_rate': 5e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 3, 'max_train_samples': None}  →  run_009_lr5e-5_r8_a16_ep3
  [10] {'learning_rate': 5e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'max_train_samples': None}  →  run_010_lr5e-5_r16_a32_ep3
  [11] {'learning_rate': 5e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'max_train_samples': None}  →  run_011_lr5e-5_r32_a64_ep3
  [12] {'learning_rate': 7e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 3, 'max_train_samples': None}  →  run_012_lr7e-5_r8_a16_ep3
  [13] {'learning_rate': 7e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'max_train_samples': None}  →  run_013_lr7e-5_r16_a32_ep3
  [14] {'learning_rate': 7e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'max_train_samples': None}  →  run_014_lr7e-5_r32_a64_ep3
  [15] {'learning_rate': 0.0001, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 3, 'max_train_samples': None}  →  run_015_lr1e-4_r8_a16_ep3
  [16] {'learning_rate': 0.0001, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'max_train_samples': None}  →  run_016_lr1e-4_r16_a32_ep3
  [17] {'learning_rate': 0.0001, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'max_train_samples': None}  →  run_017_lr1e-4_r32_a64_ep3
RESUME_INCOMPLETE_ONLY=True
LOGGING_STEPS=1  SHOW_NOTEBOOK_LOG_LINES=True  DISABLE_TQDM=False  TRANSFORMERS_DEBUG=False

### 3 — Train

Loads the model and data, runs `run_finetune` for each combination, and writes `training_summary.json`, `trainer_log_history.json`, and `training_run.log` per run. In sweep mode, also writes `sweep_index.json` at the top level. If `RESUME_INCOMPLETE_ONLY=True`, completed run folders are skipped automatically.

Re-run config first if hyperparameters changed.

In [3]:
def _setup_run_logging(log_path: Path) -> None:
    logging.basicConfig(
        level=logging.DEBUG if TRANSFORMERS_DEBUG else logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(log_path, encoding="utf-8", mode="a"),
        ],
        force=True,
    )
    for name in ("transformers", "transformers.trainer", "qwen_math_flow.lora_finetune"):
        logging.getLogger(name).setLevel(logging.DEBUG if TRANSFORMERS_DEBUG else logging.INFO)
    logging.getLogger("datasets").setLevel(logging.WARNING)
    if TRANSFORMERS_DEBUG:
        transformers.logging.set_verbosity_debug()
    else:
        transformers.logging.set_verbosity_info()


all_summaries = []
skipped_runs = 0


def _is_completed_run(out_dir: Path) -> bool:
    summary_path = out_dir / "training_summary.json"
    hist_path = out_dir / "trainer_log_history.json"
    if not summary_path.exists() or not hist_path.exists():
        return False
    try:
        with open(summary_path, "r", encoding="utf-8") as f:
            s = json.load(f)
        with open(hist_path, "r", encoding="utf-8") as f:
            h = json.load(f)
    except Exception:
        return False
    if not isinstance(h, list) or len(h) == 0:
        return False
    last = h[-1] if isinstance(h[-1], dict) else {}
    # Completion marker from Trainer's final summary record.
    return "train_loss" in last and s.get("global_step") is not None


for run_index, overrides in enumerate(SWEEP_RUNS):
    merged = merged_training_params(overrides)
    out = (
        Path(OUTPUT_BASE) / combination_subdir(run_index, merged)
        if RUN_HYPERPARAMETER_SWEEP
        else Path(OUTPUT_BASE)
    )
    out.mkdir(parents=True, exist_ok=True)

    if RESUME_INCOMPLETE_ONLY and _is_completed_run(out):
        print(f"[skip] run {run_index + 1}/{NUM_COMBINATIONS} already completed: {out}", flush=True)
        skipped_runs += 1
        continue

    log_file = out / "training_run.log"

    print(
        f"\n=== Run {run_index + 1}/{NUM_COMBINATIONS}  {out.name}  merged={merged} ===\n",
        flush=True,
    )
    _setup_run_logging(log_file)
    logging.info("Logging to %s", log_file.resolve())

    model, tokenizer = download_qwen_25_07b(
        model_id=MODEL_NAME,
        cache_dir=MODEL_CACHE_DIR,
        load_in_4bit=LOAD_IN_4BIT,
        device_map="auto" if LOAD_IN_4BIT else None,
    )
    tokenized_train = load_and_tokenize_math(
        tokenizer,
        name=DATASET_NAME,
        split=DATASET_SPLIT,
        max_samples=merged["max_train_samples"],
        max_length=merged["max_length"],
        message_formatter=format_gsm8k_as_chat,
    )
    cap_msg = (
        "full train split"
        if merged["max_train_samples"] is None
        else f"up to {merged['max_train_samples']} samples"
    )
    logging.info(
        "GSM8K training: %s samples (%s), %s epoch(s).",
        len(tokenized_train),
        cap_msg,
        merged["num_epochs"],
    )

    peft_model = create_lora_model(
        model,
        r=merged["lora_r"],
        lora_alpha=merged["lora_alpha"],
        use_4bit_or_8bit=LOAD_IN_4BIT,
    )
    callbacks = []
    if SHOW_NOTEBOOK_LOG_LINES:
        callbacks.append(NotebookProgressCallback())

    metrics = run_finetune(
        peft_model,
        tokenizer,
        tokenized_train,
        output_dir=str(out),
        num_epochs=merged["num_epochs"],
        per_device_train_batch_size=merged["per_device_train_batch_size"],
        gradient_accumulation_steps=merged["gradient_accumulation_steps"],
        learning_rate=merged["learning_rate"],
        logging_steps=LOGGING_STEPS,
        logging_first_step=True,
        logging_strategy="steps",
        disable_tqdm=DISABLE_TQDM,
        callbacks=callbacks,
        save_log_history_json=True,
    )

    summary = {
        "run_index": run_index,
        "run_hyperparameter_sweep": RUN_HYPERPARAMETER_SWEEP,
        "sweep_overrides": overrides,
        "merged_params": merged,
        "finished_at_utc": datetime.now(timezone.utc).isoformat(),
        "output_dir": str(out.resolve()),
        "log_files": {
            "training_run_log": str((out / "training_run.log").resolve()),
            "trainer_log_history_json": str((out / "trainer_log_history.json").resolve()),
        },
        "logging_steps": LOGGING_STEPS,
        "show_notebook_log_lines": SHOW_NOTEBOOK_LOG_LINES,
        "disable_tqdm": DISABLE_TQDM,
        "transformers_debug": TRANSFORMERS_DEBUG,
        "model_name": MODEL_NAME,
        "dataset": DATASET_NAME,
        "split": DATASET_SPLIT,
        "num_train_samples": len(tokenized_train),
        "num_epochs": merged["num_epochs"],
        "per_device_train_batch_size": merged["per_device_train_batch_size"],
        "gradient_accumulation_steps": merged["gradient_accumulation_steps"],
        "learning_rate": merged["learning_rate"],
        "max_length": merged["max_length"],
        "lora_r": merged["lora_r"],
        "lora_alpha": merged["lora_alpha"],
        "load_in_4bit": LOAD_IN_4BIT,
        "final_train_loss": metrics.get("train_loss"),
        "global_step": metrics.get("global_step"),
        "epoch": metrics.get("epoch"),
    }
    with open(out / "training_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    all_summaries.append(summary)

    logging.info("Done run %s/%s: %s", run_index + 1, NUM_COMBINATIONS, out.resolve())
    del model, peft_model, tokenizer, tokenized_train
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

if RUN_HYPERPARAMETER_SWEEP:
    sweep_index_path = Path(OUTPUT_BASE) / "sweep_index.json"
    with open(sweep_index_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "finished_at_utc": datetime.now(timezone.utc).isoformat(),
                "num_runs": NUM_COMBINATIONS,
                "num_skipped": skipped_runs,
                "num_executed": len(all_summaries),
                "runs": [
                    {
                        "output_dir": s["output_dir"],
                        "final_train_loss": s.get("final_train_loss"),
                        "merged_params": s["merged_params"],
                    }
                    for s in all_summaries
                ],
            },
            f,
            indent=2,
        )
    print(f"Wrote sweep index: {sweep_index_path.resolve()}")

print(
    f"Finished: total={NUM_COMBINATIONS}, executed={len(all_summaries)}, skipped={skipped_runs}.\n"
    f"Artifacts under:\n  {Path(OUTPUT_BASE).resolve()}\n"
)

[skip] run 1/18 already completed: output/fine_tune/run_000_lr1e-5_r8_a16_ep3
[skip] run 2/18 already completed: output/fine_tune/run_001_lr1e-5_r16_a32_ep3
[skip] run 3/18 already completed: output/fine_tune/run_002_lr1e-5_r32_a64_ep3
[skip] run 4/18 already completed: output/fine_tune/run_003_lr2e-5_r8_a16_ep3
[skip] run 5/18 already completed: output/fine_tune/run_004_lr2e-5_r16_a32_ep3
[skip] run 6/18 already completed: output/fine_tune/run_005_lr2e-5_r32_a64_ep3
[skip] run 7/18 already completed: output/fine_tune/run_006_lr3e-5_r8_a16_ep3
[skip] run 8/18 already completed: output/fine_tune/run_007_lr3e-5_r16_a32_ep3
[skip] run 9/18 already completed: output/fine_tune/run_008_lr3e-5_r32_a64_ep3
[skip] run 10/18 already completed: output/fine_tune/run_009_lr5e-5_r8_a16_ep3
[skip] run 11/18 already completed: output/fine_tune/run_010_lr5e-5_r16_a32_ep3
[skip] run 12/18 already completed: output/fine_tune/run_011_lr5e-5_r32_a64_ep3
[skip] run 13/18 already completed: output/fine_tune/run_012_lr7e-5_r8_a16_ep3
[skip] run 14/18 already completed: output/fine_tune/run_013_lr7e-5_r16_a32_ep3
[skip] run 15/18 already completed: output/fine_tune/run_014_lr7e-5_r32_a64_ep3
[skip] run 16/18 already completed: output/fine_tune/run_015_lr1e-4_r8_a16_ep3

=== Run 17/18  run_016_lr1e-4_r16_a32_ep3  merged={'learning_rate': 0.0001, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-04 12:33:41 | INFO     | root | Logging to /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_016_lr1e-4_r16_a32_ep3/training_run.log
2026-04-04 12:33:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:33:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-04 12:33:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:33:41 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-04 12:33:42 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-04 12:33:42 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-04 12:33:43 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct "HTTP/1.1 200 OK"
2026-04-04 12:33:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:33:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-04 12:33:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:33:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 367.86it/s]
2026-04-04 12:33:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:33:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.1,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2026-04-04 12:33:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-04-04 12:33:45 | WARNING  | huggingface_hub.utils._http | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-0.5B-Instruct.
2026-04-04 12:33:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:33:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-04 12:33:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-04 12:33:46 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-04 12:33:46 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/datasets/openai/gsm8k/revision/740312add88f781978c0658806c59bc2815b9866 "HTTP/1.1 200 OK"
2026-04-04 12:33:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-04 12:33:47 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-04 12:33:47 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/datasets/openai/gsm8k/tree/740312add88f781978c0658806c59bc2815b9866/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-04 12:33:47 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/datasets/openai/gsm8k/tree/740312add88f781978c0658806c59bc2815b9866?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-04-04 12:33:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-04 12:33:49 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 2,162,688

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.4261 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.5759 | lr=7.14e-07 | epoch=0.0043
[train] step=3 | loss=1.5509 | lr=1.43e-06 | epoch=0.0064
[train] step=4 | loss=1.5169 | lr=2.14e-06 | epoch=0.0086
[train] step=5 | loss=1.4341 | lr=2.86e-06 | epoch=0.0107
[train] step=6 | loss=1.4322 | lr=3.57e-06 | epoch=0.0128
[train] step=7 | loss=1.4304 | lr=4.29e-06 | epoch=0.0150
[train] step=8 | loss=1.3627 | lr=5.00e-06 | epoch=0.0171
[train] step=9 | loss=1.4813 | lr=5.71e-06 | epoch=0.0193
[train] step=10 | loss=1.5159 | lr=6.43e-06 | epoch=0.0214
[train] step=11 | loss=1.4842 | lr=7.14e-06 | epoch=0.0235
[train] step=12 | loss=1.6597 | lr=7.86e-06 | epoch=0.0257
[train] step=13 | loss=1.4364 | lr=8.57e-06 | epoch=0.0278
[train] step=14 | loss=1.5096 | lr=9.29e-06 | epoch=0.0300
[train] step=15 | loss=1.5680 | lr=1.00e-05 | epoch=0.0321
[train] step=16 | loss=1.4761 | lr=1.07e-05 | epoch=0.0342
[train] step=17 | loss=1.4635 | lr=1.14e-05 | epoch=0.0364
[train] step=18 | loss=1.3627 | lr=1.21e-05 | epoch=0.0385
[train] step=19 | loss=1.3381 | lr=1.29e-05 | epoch=0.0407
[train] step=20 | loss=1.4330 | lr=1.36e-05 | epoch=0.0428
[train] step=21 | loss=1.2436 | lr=1.43e-05 | epoch=0.0449
[train] step=22 | loss=1.2878 | lr=1.50e-05 | epoch=0.0471
[train] step=23 | loss=1.2616 | lr=1.57e-05 | epoch=0.0492
[train] step=24 | loss=1.2880 | lr=1.64e-05 | epoch=0.0514
[train] step=25 | loss=1.1378 | lr=1.71e-05 | epoch=0.0535
[train] step=26 | loss=1.3431 | lr=1.79e-05 | epoch=0.0556
[train] step=27 | loss=1.1347 | lr=1.86e-05 | epoch=0.0578
[train] step=28 | loss=1.1601 | lr=1.93e-05 | epoch=0.0599
[train] step=29 | loss=1.1095 | lr=2.00e-05 | epoch=0.0621
[train] step=30 | loss=1.1748 | lr=2.07e-05 | epoch=0.0642
[train] step=31 | loss=0.9903 | lr=2.14e-05 | epoch=0.0663
[train] step=32 | loss=1.0869 | lr=2.21e-05 | epoch=0.0685
[train] step=33 | loss=1.0738 | lr=2.29e-05 | epoch=0.0706
[train] step=34 | loss=0.9762 | lr=2.36e-05 | epoch=0.0728
[train] step=35 | loss=1.0577 | lr=2.43e-05 | epoch=0.0749
[train] step=36 | loss=0.9748 | lr=2.50e-05 | epoch=0.0770
[train] step=37 | loss=0.9333 | lr=2.57e-05 | epoch=0.0792
[train] step=38 | loss=0.9318 | lr=2.64e-05 | epoch=0.0813
[train] step=39 | loss=0.8672 | lr=2.71e-05 | epoch=0.0835
[train] step=40 | loss=0.9373 | lr=2.79e-05 | epoch=0.0856
[train] step=41 | loss=0.9544 | lr=2.86e-05 | epoch=0.0877
[train] step=42 | loss=0.8618 | lr=2.93e-05 | epoch=0.0899
[train] step=43 | loss=0.8206 | lr=3.00e-05 | epoch=0.0920
[train] step=44 | loss=0.7943 | lr=3.07e-05 | epoch=0.0942
[train] step=45 | loss=0.8333 | lr=3.14e-05 | epoch=0.0963
[train] step=46 | loss=0.7254 | lr=3.21e-05 | epoch=0.0984
[train] step=47 | loss=0.7577 | lr=3.29e-05 | epoch=0.1006
[train] step=48 | loss=0.6827 | lr=3.36e-05 | epoch=0.1027
[train] step=49 | loss=0.6922 | lr=3.43e-05 | epoch=0.1049
[train] step=50 | loss=0.7142 | lr=3.50e-05 | epoch=0.1070
[train] step=51 | loss=0.7018 | lr=3.57e-05 | epoch=0.1091
[train] step=52 | loss=0.6491 | lr=3.64e-05 | epoch=0.1113
[train] step=53 | loss=0.6905 | lr=3.71e-05 | epoch=0.1134
[train] step=54 | loss=0.6687 | lr=3.79e-05 | epoch=0.1156
[train] step=55 | loss=0.6053 | lr=3.86e-05 | epoch=0.1177
[train] step=56 | loss=0.6156 | lr=3.93e-05 | epoch=0.1199
[train] step=57 | loss=0.5462 | lr=4.00e-05 | epoch=0.1220
[train] step=58 | loss=0.5771 | lr=4.07e-05 | epoch=0.1241
[train] step=59 | loss=0.5747 | lr=4.14e-05 | epoch=0.1263
[train] step=60 | loss=0.5111 | lr=4.21e-05 | epoch=0.1284
[train] step=61 | loss=0.4544 | lr=4.29e-05 | epoch=0.1306
[train] step=62 | loss=0.4605 | lr=4.36e-05 | epoch=0.1327
[train] step=63 | loss=0.5009 | lr=4.43e-05 | epoch=0.1348
[train] step=64 | loss=0.4424 | lr=4.50e-05 | epoch=0.1370
[train] step=65 | loss=0.4347 | lr=4.57e-05 | epoch=0.1391
[train] step=66 | loss=0.4841 | lr=4.64e-05 | epoch=0.1413
[train] step=67 | loss=0.4237 | lr=4.71e-05 | epoch=0.1434
[train] step=68 | loss=0.4805 | lr=4.79e-05 | epoch=0.1455
[train] step=69 | loss=0.5122 | lr=4.86e-05 | epoch=0.1477
[train] step=70 | loss=0.4729 | lr=4.93e-05 | epoch=0.1498
[train] step=71 | loss=0.4264 | lr=5.00e-05 | epoch=0.1520
[train] step=72 | loss=0.4464 | lr=5.07e-05 | epoch=0.1541
[train] step=73 | loss=0.4449 | lr=5.14e-05 | epoch=0.1562
[train] step=74 | loss=0.4553 | lr=5.21e-05 | epoch=0.1584
[train] step=75 | loss=0.4457 | lr=5.29e-05 | epoch=0.1605
[train] step=76 | loss=0.3920 | lr=5.36e-05 | epoch=0.1627
[train] step=77 | loss=0.4000 | lr=5.43e-05 | epoch=0.1648
[train] step=78 | loss=0.3809 | lr=5.50e-05 | epoch=0.1669
[train] step=79 | loss=0.3793 | lr=5.57e-05 | epoch=0.1691
[train] step=80 | loss=0.4780 | lr=5.64e-05 | epoch=0.1712
[train] step=81 | loss=0.4404 | lr=5.71e-05 | epoch=0.1734
[train] step=82 | loss=0.3995 | lr=5.79e-05 | epoch=0.1755
[train] step=83 | loss=0.3948 | lr=5.86e-05 | epoch=0.1776
[train] step=84 | loss=0.4214 | lr=5.93e-05 | epoch=0.1798
[train] step=85 | loss=0.4287 | lr=6.00e-05 | epoch=0.1819
[train] step=86 | loss=0.4382 | lr=6.07e-05 | epoch=0.1841
[train] step=87 | loss=0.3421 | lr=6.14e-05 | epoch=0.1862
[train] step=88 | loss=0.4314 | lr=6.21e-05 | epoch=0.1883
[train] step=89 | loss=0.3805 | lr=6.29e-05 | epoch=0.1905
[train] step=90 | loss=0.3279 | lr=6.36e-05 | epoch=0.1926
[train] step=91 | loss=0.3748 | lr=6.43e-05 | epoch=0.1948
[train] step=92 | loss=0.4266 | lr=6.50e-05 | epoch=0.1969
[train] step=93 | loss=0.3855 | lr=6.57e-05 | epoch=0.1990
[train] step=94 | loss=0.3606 | lr=6.64e-05 | epoch=0.2012
[train] step=95 | loss=0.3846 | lr=6.71e-05 | epoch=0.2033
[train] step=96 | loss=0.3242 | lr=6.79e-05 | epoch=0.2055
[train] step=97 | loss=0.3739 | lr=6.86e-05 | epoch=0.2076
[train] step=98 | loss=0.3853 | lr=6.93e-05 | epoch=0.2097
[train] step=99 | loss=0.3207 | lr=7.00e-05 | epoch=0.2119
[train] step=100 | loss=0.3636 | lr=7.07e-05 | epoch=0.2140
[train] step=101 | loss=0.3384 | lr=7.14e-05 | epoch=0.2162
[train] step=102 | loss=0.4288 | lr=7.21e-05 | epoch=0.2183
[train] step=103 | loss=0.3647 | lr=7.29e-05 | epoch=0.2204
[train] step=104 | loss=0.3619 | lr=7.36e-05 | epoch=0.2226
[train] step=105 | loss=0.4158 | lr=7.43e-05 | epoch=0.2247
[train] step=106 | loss=0.3769 | lr=7.50e-05 | epoch=0.2269
[train] step=107 | loss=0.3812 | lr=7.57e-05 | epoch=0.2290
[train] step=108 | loss=0.3242 | lr=7.64e-05 | epoch=0.2311
[train] step=109 | loss=0.3188 | lr=7.71e-05 | epoch=0.2333
[train] step=110 | loss=0.3970 | lr=7.79e-05 | epoch=0.2354
[train] step=111 | loss=0.3489 | lr=7.86e-05 | epoch=0.2376
[train] step=112 | loss=0.3420 | lr=7.93e-05 | epoch=0.2397
[train] step=113 | loss=0.3587 | lr=8.00e-05 | epoch=0.2418
[train] step=114 | loss=0.3838 | lr=8.07e-05 | epoch=0.2440
[train] step=115 | loss=0.3919 | lr=8.14e-05 | epoch=0.2461
[train] step=116 | loss=0.3822 | lr=8.21e-05 | epoch=0.2483
[train] step=117 | loss=0.3688 | lr=8.29e-05 | epoch=0.2504
[train] step=118 | loss=0.3578 | lr=8.36e-05 | epoch=0.2525
[train] step=119 | loss=0.3924 | lr=8.43e-05 | epoch=0.2547
[train] step=120 | loss=0.3221 | lr=8.50e-05 | epoch=0.2568
[train] step=121 | loss=0.3322 | lr=8.57e-05 | epoch=0.2590
[train] step=122 | loss=0.3823 | lr=8.64e-05 | epoch=0.2611
[train] step=123 | loss=0.3706 | lr=8.71e-05 | epoch=0.2632
[train] step=124 | loss=0.3382 | lr=8.79e-05 | epoch=0.2654
[train] step=125 | loss=0.3591 | lr=8.86e-05 | epoch=0.2675
[train] step=126 | loss=0.3569 | lr=8.93e-05 | epoch=0.2697
[train] step=127 | loss=0.3490 | lr=9.00e-05 | epoch=0.2718
[train] step=128 | loss=0.3166 | lr=9.07e-05 | epoch=0.2739
[train] step=129 | loss=0.3199 | lr=9.14e-05 | epoch=0.2761
[train] step=130 | loss=0.3770 | lr=9.21e-05 | epoch=0.2782
[train] step=131 | loss=0.3989 | lr=9.29e-05 | epoch=0.2804
[train] step=132 | loss=0.3751 | lr=9.36e-05 | epoch=0.2825
[train] step=133 | loss=0.3648 | lr=9.43e-05 | epoch=0.2846
[train] step=134 | loss=0.3275 | lr=9.50e-05 | epoch=0.2868
[train] step=135 | loss=0.3728 | lr=9.57e-05 | epoch=0.2889
[train] step=136 | loss=0.3216 | lr=9.64e-05 | epoch=0.2911
[train] step=137 | loss=0.3854 | lr=9.71e-05 | epoch=0.2932
[train] step=138 | loss=0.3059 | lr=9.79e-05 | epoch=0.2953
[train] step=139 | loss=0.3070 | lr=9.86e-05 | epoch=0.2975
[train] step=140 | loss=0.3179 | lr=9.93e-05 | epoch=0.2996
[train] step=141 | loss=0.4797 | lr=1.00e-04 | epoch=0.3018
[train] step=142 | loss=0.3575 | lr=9.99e-05 | epoch=0.3039
[train] step=143 | loss=0.3438 | lr=9.98e-05 | epoch=0.3060
[train] step=144 | loss=0.3469 | lr=9.98e-05 | epoch=0.3082
[train] step=145 | loss=0.3490 | lr=9.97e-05 | epoch=0.3103
[train] step=146 | loss=0.3278 | lr=9.96e-05 | epoch=0.3125
[train] step=147 | loss=0.3376 | lr=9.95e-05 | epoch=0.3146
[train] step=148 | loss=0.2981 | lr=9.94e-05 | epoch=0.3167
[train] step=149 | loss=0.3509 | lr=9.94e-05 | epoch=0.3189
[train] step=150 | loss=0.2978 | lr=9.93e-05 | epoch=0.3210
[train] step=151 | loss=0.3727 | lr=9.92e-05 | epoch=0.3232
[train] step=152 | loss=0.3268 | lr=9.91e-05 | epoch=0.3253
[train] step=153 | loss=0.3058 | lr=9.91e-05 | epoch=0.3274
[train] step=154 | loss=0.3151 | lr=9.90e-05 | epoch=0.3296
[train] step=155 | loss=0.2963 | lr=9.89e-05 | epoch=0.3317
[train] step=156 | loss=0.3719 | lr=9.88e-05 | epoch=0.3339
[train] step=157 | loss=0.4216 | lr=9.87e-05 | epoch=0.3360
[train] step=158 | loss=0.3238 | lr=9.87e-05 | epoch=0.3381
[train] step=159 | loss=0.3344 | lr=9.86e-05 | epoch=0.3403
[train] step=160 | loss=0.3634 | lr=9.85e-05 | epoch=0.3424
[train] step=161 | loss=0.3227 | lr=9.84e-05 | epoch=0.3446
[train] step=162 | loss=0.3297 | lr=9.83e-05 | epoch=0.3467
[train] step=163 | loss=0.3625 | lr=9.83e-05 | epoch=0.3488
[train] step=164 | loss=0.3891 | lr=9.82e-05 | epoch=0.3510
[train] step=165 | loss=0.3637 | lr=9.81e-05 | epoch=0.3531
[train] step=166 | loss=0.3743 | lr=9.80e-05 | epoch=0.3553
[train] step=167 | loss=0.3174 | lr=9.79e-05 | epoch=0.3574
[train] step=168 | loss=0.2909 | lr=9.79e-05 | epoch=0.3596
[train] step=169 | loss=0.3314 | lr=9.78e-05 | epoch=0.3617
[train] step=170 | loss=0.3106 | lr=9.77e-05 | epoch=0.3638
[train] step=171 | loss=0.3545 | lr=9.76e-05 | epoch=0.3660
[train] step=172 | loss=0.3365 | lr=9.75e-05 | epoch=0.3681
[train] step=173 | loss=0.3293 | lr=9.75e-05 | epoch=0.3703
[train] step=174 | loss=0.3247 | lr=9.74e-05 | epoch=0.3724
[train] step=175 | loss=0.3194 | lr=9.73e-05 | epoch=0.3745
[train] step=176 | loss=0.4143 | lr=9.72e-05 | epoch=0.3767
[train] step=177 | loss=0.2889 | lr=9.72e-05 | epoch=0.3788
[train] step=178 | loss=0.3163 | lr=9.71e-05 | epoch=0.3810
[train] step=179 | loss=0.3342 | lr=9.70e-05 | epoch=0.3831
[train] step=180 | loss=0.3196 | lr=9.69e-05 | epoch=0.3852
[train] step=181 | loss=0.3508 | lr=9.68e-05 | epoch=0.3874
[train] step=182 | loss=0.2579 | lr=9.68e-05 | epoch=0.3895
[train] step=183 | loss=0.2881 | lr=9.67e-05 | epoch=0.3917
[train] step=184 | loss=0.3879 | lr=9.66e-05 | epoch=0.3938
[train] step=185 | loss=0.3170 | lr=9.65e-05 | epoch=0.3959
[train] step=186 | loss=0.2747 | lr=9.64e-05 | epoch=0.3981
[train] step=187 | loss=0.3106 | lr=9.64e-05 | epoch=0.4002
[train] step=188 | loss=0.3739 | lr=9.63e-05 | epoch=0.4024
[train] step=189 | loss=0.3538 | lr=9.62e-05 | epoch=0.4045
[train] step=190 | loss=0.3673 | lr=9.61e-05 | epoch=0.4066
[train] step=191 | loss=0.3194 | lr=9.60e-05 | epoch=0.4088
[train] step=192 | loss=0.3089 | lr=9.60e-05 | epoch=0.4109
[train] step=193 | loss=0.3429 | lr=9.59e-05 | epoch=0.4131
[train] step=194 | loss=0.3244 | lr=9.58e-05 | epoch=0.4152
[train] step=195 | loss=0.3548 | lr=9.57e-05 | epoch=0.4173
[train] step=196 | loss=0.3318 | lr=9.56e-05 | epoch=0.4195
[train] step=197 | loss=0.2893 | lr=9.56e-05 | epoch=0.4216
[train] step=198 | loss=0.3670 | lr=9.55e-05 | epoch=0.4238
[train] step=199 | loss=0.3538 | lr=9.54e-05 | epoch=0.4259
[train] step=200 | loss=0.3402 | lr=9.53e-05 | epoch=0.4280
[train] step=201 | loss=0.3053 | lr=9.53e-05 | epoch=0.4302
[train] step=202 | loss=0.3910 | lr=9.52e-05 | epoch=0.4323
[train] step=203 | loss=0.2960 | lr=9.51e-05 | epoch=0.4345
[train] step=204 | loss=0.3612 | lr=9.50e-05 | epoch=0.4366
[train] step=205 | loss=0.2950 | lr=9.49e-05 | epoch=0.4387
[train] step=206 | loss=0.3248 | lr=9.49e-05 | epoch=0.4409
[train] step=207 | loss=0.3748 | lr=9.48e-05 | epoch=0.4430
[train] step=208 | loss=0.3072 | lr=9.47e-05 | epoch=0.4452
[train] step=209 | loss=0.3227 | lr=9.46e-05 | epoch=0.4473
[train] step=210 | loss=0.3351 | lr=9.45e-05 | epoch=0.4494
[train] step=211 | loss=0.3312 | lr=9.45e-05 | epoch=0.4516
[train] step=212 | loss=0.3182 | lr=9.44e-05 | epoch=0.4537
[train] step=213 | loss=0.3918 | lr=9.43e-05 | epoch=0.4559
[train] step=214 | loss=0.3532 | lr=9.42e-05 | epoch=0.4580
[train] step=215 | loss=0.3759 | lr=9.41e-05 | epoch=0.4601
[train] step=216 | loss=0.3121 | lr=9.41e-05 | epoch=0.4623
[train] step=217 | loss=0.3328 | lr=9.40e-05 | epoch=0.4644
[train] step=218 | loss=0.3055 | lr=9.39e-05 | epoch=0.4666
[train] step=219 | loss=0.3215 | lr=9.38e-05 | epoch=0.4687
[train] step=220 | loss=0.2704 | lr=9.38e-05 | epoch=0.4708
[train] step=221 | loss=0.3004 | lr=9.37e-05 | epoch=0.4730
[train] step=222 | loss=0.3298 | lr=9.36e-05 | epoch=0.4751
[train] step=223 | loss=0.3567 | lr=9.35e-05 | epoch=0.4773
[train] step=224 | loss=0.2759 | lr=9.34e-05 | epoch=0.4794
[train] step=225 | loss=0.3374 | lr=9.34e-05 | epoch=0.4815
[train] step=226 | loss=0.3266 | lr=9.33e-05 | epoch=0.4837
[train] step=227 | loss=0.3383 | lr=9.32e-05 | epoch=0.4858
[train] step=228 | loss=0.3350 | lr=9.31e-05 | epoch=0.4880
[train] step=229 | loss=0.3073 | lr=9.30e-05 | epoch=0.4901
[train] step=230 | loss=0.3580 | lr=9.30e-05 | epoch=0.4922
[train] step=231 | loss=0.3216 | lr=9.29e-05 | epoch=0.4944
[train] step=232 | loss=0.3339 | lr=9.28e-05 | epoch=0.4965
[train] step=233 | loss=0.3482 | lr=9.27e-05 | epoch=0.4987

Saving model checkpoint to output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-233
2026-04-04 12:37:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:37:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:37:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:37:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-233/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-233/tokenizer_config.json

[train] step=234 | loss=0.3223 | lr=9.26e-05 | epoch=0.5008
[train] step=235 | loss=0.2967 | lr=9.26e-05 | epoch=0.5029
[train] step=236 | loss=0.3193 | lr=9.25e-05 | epoch=0.5051
[train] step=237 | loss=0.3305 | lr=9.24e-05 | epoch=0.5072
[train] step=238 | loss=0.3343 | lr=9.23e-05 | epoch=0.5094
[train] step=239 | loss=0.3197 | lr=9.22e-05 | epoch=0.5115
[train] step=240 | loss=0.3144 | lr=9.22e-05 | epoch=0.5136
[train] step=241 | loss=0.3425 | lr=9.21e-05 | epoch=0.5158
[train] step=242 | loss=0.3096 | lr=9.20e-05 | epoch=0.5179
[train] step=243 | loss=0.3986 | lr=9.19e-05 | epoch=0.5201
[train] step=244 | loss=0.3553 | lr=9.19e-05 | epoch=0.5222
[train] step=245 | loss=0.3051 | lr=9.18e-05 | epoch=0.5243
[train] step=246 | loss=0.3843 | lr=9.17e-05 | epoch=0.5265
[train] step=247 | loss=0.3698 | lr=9.16e-05 | epoch=0.5286
[train] step=248 | loss=0.3162 | lr=9.15e-05 | epoch=0.5308
[train] step=249 | loss=0.2718 | lr=9.15e-05 | epoch=0.5329
[train] step=250 | loss=0.3177 | lr=9.14e-05 | epoch=0.5350
[train] step=251 | loss=0.3332 | lr=9.13e-05 | epoch=0.5372
[train] step=252 | loss=0.3303 | lr=9.12e-05 | epoch=0.5393
[train] step=253 | loss=0.3634 | lr=9.11e-05 | epoch=0.5415
[train] step=254 | loss=0.3001 | lr=9.11e-05 | epoch=0.5436
[train] step=255 | loss=0.3034 | lr=9.10e-05 | epoch=0.5457
[train] step=256 | loss=0.3034 | lr=9.09e-05 | epoch=0.5479
[train] step=257 | loss=0.2877 | lr=9.08e-05 | epoch=0.5500
[train] step=258 | loss=0.2996 | lr=9.07e-05 | epoch=0.5522
[train] step=259 | loss=0.3289 | lr=9.07e-05 | epoch=0.5543
[train] step=260 | loss=0.3369 | lr=9.06e-05 | epoch=0.5564
[train] step=261 | loss=0.3083 | lr=9.05e-05 | epoch=0.5586
[train] step=262 | loss=0.3648 | lr=9.04e-05 | epoch=0.5607
[train] step=263 | loss=0.2983 | lr=9.03e-05 | epoch=0.5629
[train] step=264 | loss=0.2748 | lr=9.03e-05 | epoch=0.5650
[train] step=265 | loss=0.3495 | lr=9.02e-05 | epoch=0.5671
[train] step=266 | loss=0.2956 | lr=9.01e-05 | epoch=0.5693
[train] step=267 | loss=0.3100 | lr=9.00e-05 | epoch=0.5714
[train] step=268 | loss=0.3125 | lr=9.00e-05 | epoch=0.5736
[train] step=269 | loss=0.3222 | lr=8.99e-05 | epoch=0.5757
[train] step=270 | loss=0.3710 | lr=8.98e-05 | epoch=0.5778
[train] step=271 | loss=0.3259 | lr=8.97e-05 | epoch=0.5800
[train] step=272 | loss=0.3085 | lr=8.96e-05 | epoch=0.5821
[train] step=273 | loss=0.2743 | lr=8.96e-05 | epoch=0.5843
[train] step=274 | loss=0.3134 | lr=8.95e-05 | epoch=0.5864
[train] step=275 | loss=0.3419 | lr=8.94e-05 | epoch=0.5886
[train] step=276 | loss=0.3306 | lr=8.93e-05 | epoch=0.5907
[train] step=277 | loss=0.2974 | lr=8.92e-05 | epoch=0.5928
[train] step=278 | loss=0.3426 | lr=8.92e-05 | epoch=0.5950
[train] step=279 | loss=0.2922 | lr=8.91e-05 | epoch=0.5971
[train] step=280 | loss=0.3246 | lr=8.90e-05 | epoch=0.5993
[train] step=281 | loss=0.3112 | lr=8.89e-05 | epoch=0.6014
[train] step=282 | loss=0.3256 | lr=8.88e-05 | epoch=0.6035
[train] step=283 | loss=0.3355 | lr=8.88e-05 | epoch=0.6057
[train] step=284 | loss=0.3052 | lr=8.87e-05 | epoch=0.6078
[train] step=285 | loss=0.2853 | lr=8.86e-05 | epoch=0.6100
[train] step=286 | loss=0.3010 | lr=8.85e-05 | epoch=0.6121
[train] step=287 | loss=0.2879 | lr=8.84e-05 | epoch=0.6142
[train] step=288 | loss=0.3062 | lr=8.84e-05 | epoch=0.6164
[train] step=289 | loss=0.2999 | lr=8.83e-05 | epoch=0.6185
[train] step=290 | loss=0.3019 | lr=8.82e-05 | epoch=0.6207
[train] step=291 | loss=0.3349 | lr=8.81e-05 | epoch=0.6228
[train] step=292 | loss=0.3135 | lr=8.81e-05 | epoch=0.6249
[train] step=293 | loss=0.3665 | lr=8.80e-05 | epoch=0.6271
[train] step=294 | loss=0.2956 | lr=8.79e-05 | epoch=0.6292
[train] step=295 | loss=0.3433 | lr=8.78e-05 | epoch=0.6314
[train] step=296 | loss=0.2981 | lr=8.77e-05 | epoch=0.6335
[train] step=297 | loss=0.3274 | lr=8.77e-05 | epoch=0.6356
[train] step=298 | loss=0.2765 | lr=8.76e-05 | epoch=0.6378
[train] step=299 | loss=0.2951 | lr=8.75e-05 | epoch=0.6399
[train] step=300 | loss=0.3047 | lr=8.74e-05 | epoch=0.6421
[train] step=301 | loss=0.3092 | lr=8.73e-05 | epoch=0.6442
[train] step=302 | loss=0.2960 | lr=8.73e-05 | epoch=0.6463
[train] step=303 | loss=0.3310 | lr=8.72e-05 | epoch=0.6485
[train] step=304 | loss=0.3301 | lr=8.71e-05 | epoch=0.6506
[train] step=305 | loss=0.2880 | lr=8.70e-05 | epoch=0.6528
[train] step=306 | loss=0.3843 | lr=8.69e-05 | epoch=0.6549
[train] step=307 | loss=0.3730 | lr=8.69e-05 | epoch=0.6570
[train] step=308 | loss=0.2825 | lr=8.68e-05 | epoch=0.6592
[train] step=309 | loss=0.3671 | lr=8.67e-05 | epoch=0.6613
[train] step=310 | loss=0.2688 | lr=8.66e-05 | epoch=0.6635
[train] step=311 | loss=0.2894 | lr=8.66e-05 | epoch=0.6656
[train] step=312 | loss=0.3637 | lr=8.65e-05 | epoch=0.6677
[train] step=313 | loss=0.3816 | lr=8.64e-05 | epoch=0.6699
[train] step=314 | loss=0.3014 | lr=8.63e-05 | epoch=0.6720
[train] step=315 | loss=0.2805 | lr=8.62e-05 | epoch=0.6742
[train] step=316 | loss=0.3264 | lr=8.62e-05 | epoch=0.6763
[train] step=317 | loss=0.3392 | lr=8.61e-05 | epoch=0.6784
[train] step=318 | loss=0.3132 | lr=8.60e-05 | epoch=0.6806
[train] step=319 | loss=0.3727 | lr=8.59e-05 | epoch=0.6827
[train] step=320 | loss=0.3791 | lr=8.58e-05 | epoch=0.6849
[train] step=321 | loss=0.2952 | lr=8.58e-05 | epoch=0.6870
[train] step=322 | loss=0.3258 | lr=8.57e-05 | epoch=0.6891
[train] step=323 | loss=0.3020 | lr=8.56e-05 | epoch=0.6913
[train] step=324 | loss=0.2957 | lr=8.55e-05 | epoch=0.6934
[train] step=325 | loss=0.3108 | lr=8.54e-05 | epoch=0.6956
[train] step=326 | loss=0.3296 | lr=8.54e-05 | epoch=0.6977
[train] step=327 | loss=0.3062 | lr=8.53e-05 | epoch=0.6998
[train] step=328 | loss=0.3619 | lr=8.52e-05 | epoch=0.7020
[train] step=329 | loss=0.2526 | lr=8.51e-05 | epoch=0.7041
[train] step=330 | loss=0.2934 | lr=8.50e-05 | epoch=0.7063
[train] step=331 | loss=0.3122 | lr=8.50e-05 | epoch=0.7084
[train] step=332 | loss=0.3344 | lr=8.49e-05 | epoch=0.7105
[train] step=333 | loss=0.3353 | lr=8.48e-05 | epoch=0.7127
[train] step=334 | loss=0.3756 | lr=8.47e-05 | epoch=0.7148
[train] step=335 | loss=0.2681 | lr=8.47e-05 | epoch=0.7170
[train] step=336 | loss=0.3217 | lr=8.46e-05 | epoch=0.7191
[train] step=337 | loss=0.2953 | lr=8.45e-05 | epoch=0.7212
[train] step=338 | loss=0.3098 | lr=8.44e-05 | epoch=0.7234
[train] step=339 | loss=0.3538 | lr=8.43e-05 | epoch=0.7255
[train] step=340 | loss=0.3096 | lr=8.43e-05 | epoch=0.7277
[train] step=341 | loss=0.3969 | lr=8.42e-05 | epoch=0.7298
[train] step=342 | loss=0.2766 | lr=8.41e-05 | epoch=0.7319
[train] step=343 | loss=0.2770 | lr=8.40e-05 | epoch=0.7341
[train] step=344 | loss=0.3375 | lr=8.39e-05 | epoch=0.7362
[train] step=345 | loss=0.3579 | lr=8.39e-05 | epoch=0.7384
[train] step=346 | loss=0.3010 | lr=8.38e-05 | epoch=0.7405
[train] step=347 | loss=0.2907 | lr=8.37e-05 | epoch=0.7426
[train] step=348 | loss=0.3656 | lr=8.36e-05 | epoch=0.7448
[train] step=349 | loss=0.3012 | lr=8.35e-05 | epoch=0.7469
[train] step=350 | loss=0.2654 | lr=8.35e-05 | epoch=0.7491
[train] step=351 | loss=0.3249 | lr=8.34e-05 | epoch=0.7512
[train] step=352 | loss=0.3256 | lr=8.33e-05 | epoch=0.7533
[train] step=353 | loss=0.3738 | lr=8.32e-05 | epoch=0.7555
[train] step=354 | loss=0.2425 | lr=8.31e-05 | epoch=0.7576
[train] step=355 | loss=0.3330 | lr=8.31e-05 | epoch=0.7598
[train] step=356 | loss=0.2989 | lr=8.30e-05 | epoch=0.7619
[train] step=357 | loss=0.3336 | lr=8.29e-05 | epoch=0.7640
[train] step=358 | loss=0.2614 | lr=8.28e-05 | epoch=0.7662
[train] step=359 | loss=0.2837 | lr=8.28e-05 | epoch=0.7683
[train] step=360 | loss=0.3264 | lr=8.27e-05 | epoch=0.7705
[train] step=361 | loss=0.2796 | lr=8.26e-05 | epoch=0.7726
[train] step=362 | loss=0.3091 | lr=8.25e-05 | epoch=0.7747
[train] step=363 | loss=0.3651 | lr=8.24e-05 | epoch=0.7769
[train] step=364 | loss=0.3019 | lr=8.24e-05 | epoch=0.7790
[train] step=365 | loss=0.2893 | lr=8.23e-05 | epoch=0.7812
[train] step=366 | loss=0.3658 | lr=8.22e-05 | epoch=0.7833
[train] step=367 | loss=0.2842 | lr=8.21e-05 | epoch=0.7854
[train] step=368 | loss=0.3150 | lr=8.20e-05 | epoch=0.7876
[train] step=369 | loss=0.3327 | lr=8.20e-05 | epoch=0.7897
[train] step=370 | loss=0.3570 | lr=8.19e-05 | epoch=0.7919
[train] step=371 | loss=0.3642 | lr=8.18e-05 | epoch=0.7940
[train] step=372 | loss=0.3273 | lr=8.17e-05 | epoch=0.7961
[train] step=373 | loss=0.3339 | lr=8.16e-05 | epoch=0.7983
[train] step=374 | loss=0.2974 | lr=8.16e-05 | epoch=0.8004
[train] step=375 | loss=0.3191 | lr=8.15e-05 | epoch=0.8026
[train] step=376 | loss=0.2990 | lr=8.14e-05 | epoch=0.8047
[train] step=377 | loss=0.2856 | lr=8.13e-05 | epoch=0.8068
[train] step=378 | loss=0.2845 | lr=8.13e-05 | epoch=0.8090
[train] step=379 | loss=0.3752 | lr=8.12e-05 | epoch=0.8111
[train] step=380 | loss=0.3665 | lr=8.11e-05 | epoch=0.8133
[train] step=381 | loss=0.3485 | lr=8.10e-05 | epoch=0.8154
[train] step=382 | loss=0.3413 | lr=8.09e-05 | epoch=0.8175
[train] step=383 | loss=0.2895 | lr=8.09e-05 | epoch=0.8197
[train] step=384 | loss=0.2655 | lr=8.08e-05 | epoch=0.8218
[train] step=385 | loss=0.3445 | lr=8.07e-05 | epoch=0.8240
[train] step=386 | loss=0.4098 | lr=8.06e-05 | epoch=0.8261
[train] step=387 | loss=0.2962 | lr=8.05e-05 | epoch=0.8283
[train] step=388 | loss=0.3128 | lr=8.05e-05 | epoch=0.8304
[train] step=389 | loss=0.2970 | lr=8.04e-05 | epoch=0.8325
[train] step=390 | loss=0.2878 | lr=8.03e-05 | epoch=0.8347
[train] step=391 | loss=0.2949 | lr=8.02e-05 | epoch=0.8368
[train] step=392 | loss=0.2877 | lr=8.01e-05 | epoch=0.8390
[train] step=393 | loss=0.3199 | lr=8.01e-05 | epoch=0.8411
[train] step=394 | loss=0.3198 | lr=8.00e-05 | epoch=0.8432
[train] step=395 | loss=0.3610 | lr=7.99e-05 | epoch=0.8454
[train] step=396 | loss=0.3590 | lr=7.98e-05 | epoch=0.8475
[train] step=397 | loss=0.2940 | lr=7.97e-05 | epoch=0.8497
[train] step=398 | loss=0.3378 | lr=7.97e-05 | epoch=0.8518
[train] step=399 | loss=0.3252 | lr=7.96e-05 | epoch=0.8539
[train] step=400 | loss=0.3357 | lr=7.95e-05 | epoch=0.8561
[train] step=401 | loss=0.3294 | lr=7.94e-05 | epoch=0.8582
[train] step=402 | loss=0.3193 | lr=7.94e-05 | epoch=0.8604
[train] step=403 | loss=0.2679 | lr=7.93e-05 | epoch=0.8625
[train] step=404 | loss=0.3109 | lr=7.92e-05 | epoch=0.8646
[train] step=405 | loss=0.3300 | lr=7.91e-05 | epoch=0.8668
[train] step=406 | loss=0.3109 | lr=7.90e-05 | epoch=0.8689
[train] step=407 | loss=0.2583 | lr=7.90e-05 | epoch=0.8711
[train] step=408 | loss=0.3628 | lr=7.89e-05 | epoch=0.8732
[train] step=409 | loss=0.3238 | lr=7.88e-05 | epoch=0.8753
[train] step=410 | loss=0.2893 | lr=7.87e-05 | epoch=0.8775
[train] step=411 | loss=0.2769 | lr=7.86e-05 | epoch=0.8796
[train] step=412 | loss=0.3118 | lr=7.86e-05 | epoch=0.8818
[train] step=413 | loss=0.3199 | lr=7.85e-05 | epoch=0.8839
[train] step=414 | loss=0.3102 | lr=7.84e-05 | epoch=0.8860
[train] step=415 | loss=0.3055 | lr=7.83e-05 | epoch=0.8882
[train] step=416 | loss=0.3627 | lr=7.82e-05 | epoch=0.8903
[train] step=417 | loss=0.3498 | lr=7.82e-05 | epoch=0.8925
[train] step=418 | loss=0.3072 | lr=7.81e-05 | epoch=0.8946
[train] step=419 | loss=0.2837 | lr=7.80e-05 | epoch=0.8967
[train] step=420 | loss=0.3505 | lr=7.79e-05 | epoch=0.8989
[train] step=421 | loss=0.3026 | lr=7.78e-05 | epoch=0.9010
[train] step=422 | loss=0.2968 | lr=7.78e-05 | epoch=0.9032
[train] step=423 | loss=0.3656 | lr=7.77e-05 | epoch=0.9053
[train] step=424 | loss=0.3204 | lr=7.76e-05 | epoch=0.9074
[train] step=425 | loss=0.3087 | lr=7.75e-05 | epoch=0.9096
[train] step=426 | loss=0.2965 | lr=7.75e-05 | epoch=0.9117
[train] step=427 | loss=0.3215 | lr=7.74e-05 | epoch=0.9139
[train] step=428 | loss=0.3140 | lr=7.73e-05 | epoch=0.9160
[train] step=429 | loss=0.3130 | lr=7.72e-05 | epoch=0.9181
[train] step=430 | loss=0.2942 | lr=7.71e-05 | epoch=0.9203
[train] step=431 | loss=0.2939 | lr=7.71e-05 | epoch=0.9224
[train] step=432 | loss=0.4084 | lr=7.70e-05 | epoch=0.9246
[train] step=433 | loss=0.2584 | lr=7.69e-05 | epoch=0.9267
[train] step=434 | loss=0.2975 | lr=7.68e-05 | epoch=0.9288
[train] step=435 | loss=0.3292 | lr=7.67e-05 | epoch=0.9310
[train] step=436 | loss=0.3519 | lr=7.67e-05 | epoch=0.9331
[train] step=437 | loss=0.2692 | lr=7.66e-05 | epoch=0.9353
[train] step=438 | loss=0.2704 | lr=7.65e-05 | epoch=0.9374
[train] step=439 | loss=0.3737 | lr=7.64e-05 | epoch=0.9395
[train] step=440 | loss=0.3157 | lr=7.63e-05 | epoch=0.9417
[train] step=441 | loss=0.3071 | lr=7.63e-05 | epoch=0.9438
[train] step=442 | loss=0.3615 | lr=7.62e-05 | epoch=0.9460
[train] step=443 | loss=0.3106 | lr=7.61e-05 | epoch=0.9481
[train] step=444 | loss=0.3087 | lr=7.60e-05 | epoch=0.9502
[train] step=445 | loss=0.3060 | lr=7.59e-05 | epoch=0.9524
[train] step=446 | loss=0.2858 | lr=7.59e-05 | epoch=0.9545
[train] step=447 | loss=0.2629 | lr=7.58e-05 | epoch=0.9567
[train] step=448 | loss=0.3212 | lr=7.57e-05 | epoch=0.9588
[train] step=449 | loss=0.3317 | lr=7.56e-05 | epoch=0.9609
[train] step=450 | loss=0.2787 | lr=7.56e-05 | epoch=0.9631
[train] step=451 | loss=0.3074 | lr=7.55e-05 | epoch=0.9652
[train] step=452 | loss=0.3014 | lr=7.54e-05 | epoch=0.9674
[train] step=453 | loss=0.2881 | lr=7.53e-05 | epoch=0.9695
[train] step=454 | loss=0.3056 | lr=7.52e-05 | epoch=0.9716
[train] step=455 | loss=0.2719 | lr=7.52e-05 | epoch=0.9738
[train] step=456 | loss=0.3549 | lr=7.51e-05 | epoch=0.9759
[train] step=457 | loss=0.3611 | lr=7.50e-05 | epoch=0.9781
[train] step=458 | loss=0.3141 | lr=7.49e-05 | epoch=0.9802
[train] step=459 | loss=0.3132 | lr=7.48e-05 | epoch=0.9823
[train] step=460 | loss=0.3298 | lr=7.48e-05 | epoch=0.9845
[train] step=461 | loss=0.3104 | lr=7.47e-05 | epoch=0.9866
[train] step=462 | loss=0.3011 | lr=7.46e-05 | epoch=0.9888
[train] step=463 | loss=0.2950 | lr=7.45e-05 | epoch=0.9909
[train] step=464 | loss=0.3258 | lr=7.44e-05 | epoch=0.9930
[train] step=465 | loss=0.2921 | lr=7.44e-05 | epoch=0.9952
[train] step=466 | loss=0.3198 | lr=7.43e-05 | epoch=0.9973

Saving model checkpoint to output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-466
2026-04-04 12:40:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:40:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:40:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:40:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-466/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-466/tokenizer_config.json

[train] step=467 | loss=0.3173 | lr=7.42e-05 | epoch=0.9995
[train] step=468 | loss=0.2576 | lr=7.41e-05 | epoch=1.0000
[train] step=469 | loss=0.2888 | lr=7.41e-05 | epoch=1.0021
[train] step=470 | loss=0.2950 | lr=7.40e-05 | epoch=1.0043
[train] step=471 | loss=0.3316 | lr=7.39e-05 | epoch=1.0064
[train] step=472 | loss=0.3389 | lr=7.38e-05 | epoch=1.0086
[train] step=473 | loss=0.3014 | lr=7.37e-05 | epoch=1.0107
[train] step=474 | loss=0.3071 | lr=7.37e-05 | epoch=1.0128
[train] step=475 | loss=0.2999 | lr=7.36e-05 | epoch=1.0150
[train] step=476 | loss=0.3158 | lr=7.35e-05 | epoch=1.0171
[train] step=477 | loss=0.3551 | lr=7.34e-05 | epoch=1.0193
[train] step=478 | loss=0.2754 | lr=7.33e-05 | epoch=1.0214
[train] step=479 | loss=0.3565 | lr=7.33e-05 | epoch=1.0235
[train] step=480 | loss=0.2733 | lr=7.32e-05 | epoch=1.0257
[train] step=481 | loss=0.3191 | lr=7.31e-05 | epoch=1.0278
[train] step=482 | loss=0.3152 | lr=7.30e-05 | epoch=1.0300
[train] step=483 | loss=0.2671 | lr=7.29e-05 | epoch=1.0321
[train] step=484 | loss=0.2937 | lr=7.29e-05 | epoch=1.0342
[train] step=485 | loss=0.2653 | lr=7.28e-05 | epoch=1.0364
[train] step=486 | loss=0.2886 | lr=7.27e-05 | epoch=1.0385
[train] step=487 | loss=0.3692 | lr=7.26e-05 | epoch=1.0407
[train] step=488 | loss=0.2963 | lr=7.25e-05 | epoch=1.0428
[train] step=489 | loss=0.2711 | lr=7.25e-05 | epoch=1.0449
[train] step=490 | loss=0.2865 | lr=7.24e-05 | epoch=1.0471
[train] step=491 | loss=0.3150 | lr=7.23e-05 | epoch=1.0492
[train] step=492 | loss=0.3208 | lr=7.22e-05 | epoch=1.0514
[train] step=493 | loss=0.2792 | lr=7.22e-05 | epoch=1.0535
[train] step=494 | loss=0.3401 | lr=7.21e-05 | epoch=1.0556
[train] step=495 | loss=0.2676 | lr=7.20e-05 | epoch=1.0578
[train] step=496 | loss=0.3247 | lr=7.19e-05 | epoch=1.0599
[train] step=497 | loss=0.3048 | lr=7.18e-05 | epoch=1.0621
[train] step=498 | loss=0.3712 | lr=7.18e-05 | epoch=1.0642
[train] step=499 | loss=0.2908 | lr=7.17e-05 | epoch=1.0663
[train] step=500 | loss=0.3159 | lr=7.16e-05 | epoch=1.0685
[train] step=501 | loss=0.2975 | lr=7.15e-05 | epoch=1.0706
[train] step=502 | loss=0.2783 | lr=7.14e-05 | epoch=1.0728
[train] step=503 | loss=0.3665 | lr=7.14e-05 | epoch=1.0749
[train] step=504 | loss=0.3323 | lr=7.13e-05 | epoch=1.0770
[train] step=505 | loss=0.3292 | lr=7.12e-05 | epoch=1.0792
[train] step=506 | loss=0.3004 | lr=7.11e-05 | epoch=1.0813
[train] step=507 | loss=0.3021 | lr=7.10e-05 | epoch=1.0835
[train] step=508 | loss=0.3500 | lr=7.10e-05 | epoch=1.0856
[train] step=509 | loss=0.4160 | lr=7.09e-05 | epoch=1.0877
[train] step=510 | loss=0.3152 | lr=7.08e-05 | epoch=1.0899
[train] step=511 | loss=0.3278 | lr=7.07e-05 | epoch=1.0920
[train] step=512 | loss=0.2815 | lr=7.06e-05 | epoch=1.0942
[train] step=513 | loss=0.2685 | lr=7.06e-05 | epoch=1.0963
[train] step=514 | loss=0.2772 | lr=7.05e-05 | epoch=1.0984
[train] step=515 | loss=0.3092 | lr=7.04e-05 | epoch=1.1006
[train] step=516 | loss=0.3565 | lr=7.03e-05 | epoch=1.1027
[train] step=517 | loss=0.2734 | lr=7.03e-05 | epoch=1.1049
[train] step=518 | loss=0.3557 | lr=7.02e-05 | epoch=1.1070
[train] step=519 | loss=0.2907 | lr=7.01e-05 | epoch=1.1091
[train] step=520 | loss=0.3137 | lr=7.00e-05 | epoch=1.1113
[train] step=521 | loss=0.3269 | lr=6.99e-05 | epoch=1.1134
[train] step=522 | loss=0.3565 | lr=6.99e-05 | epoch=1.1156
[train] step=523 | loss=0.2853 | lr=6.98e-05 | epoch=1.1177
[train] step=524 | loss=0.2990 | lr=6.97e-05 | epoch=1.1199
[train] step=525 | loss=0.2762 | lr=6.96e-05 | epoch=1.1220
[train] step=526 | loss=0.2935 | lr=6.95e-05 | epoch=1.1241
[train] step=527 | loss=0.2606 | lr=6.95e-05 | epoch=1.1263
[train] step=528 | loss=0.3241 | lr=6.94e-05 | epoch=1.1284
[train] step=529 | loss=0.3047 | lr=6.93e-05 | epoch=1.1306
[train] step=530 | loss=0.3054 | lr=6.92e-05 | epoch=1.1327
[train] step=531 | loss=0.3650 | lr=6.91e-05 | epoch=1.1348
[train] step=532 | loss=0.3117 | lr=6.91e-05 | epoch=1.1370
[train] step=533 | loss=0.2908 | lr=6.90e-05 | epoch=1.1391
[train] step=534 | loss=0.3082 | lr=6.89e-05 | epoch=1.1413
[train] step=535 | loss=0.3152 | lr=6.88e-05 | epoch=1.1434
[train] step=536 | loss=0.3364 | lr=6.88e-05 | epoch=1.1455
[train] step=537 | loss=0.2941 | lr=6.87e-05 | epoch=1.1477
[train] step=538 | loss=0.2978 | lr=6.86e-05 | epoch=1.1498
[train] step=539 | loss=0.3165 | lr=6.85e-05 | epoch=1.1520
[train] step=540 | loss=0.2571 | lr=6.84e-05 | epoch=1.1541
[train] step=541 | loss=0.2399 | lr=6.84e-05 | epoch=1.1562
[train] step=542 | loss=0.3056 | lr=6.83e-05 | epoch=1.1584
[train] step=543 | loss=0.2851 | lr=6.82e-05 | epoch=1.1605
[train] step=544 | loss=0.2607 | lr=6.81e-05 | epoch=1.1627
[train] step=545 | loss=0.2694 | lr=6.80e-05 | epoch=1.1648
[train] step=546 | loss=0.2696 | lr=6.80e-05 | epoch=1.1669
[train] step=547 | loss=0.2726 | lr=6.79e-05 | epoch=1.1691
[train] step=548 | loss=0.3048 | lr=6.78e-05 | epoch=1.1712
[train] step=549 | loss=0.2393 | lr=6.77e-05 | epoch=1.1734
[train] step=550 | loss=0.2932 | lr=6.76e-05 | epoch=1.1755
[train] step=551 | loss=0.2874 | lr=6.76e-05 | epoch=1.1776
[train] step=552 | loss=0.3163 | lr=6.75e-05 | epoch=1.1798
[train] step=553 | loss=0.3114 | lr=6.74e-05 | epoch=1.1819
[train] step=554 | loss=0.2791 | lr=6.73e-05 | epoch=1.1841
[train] step=555 | loss=0.2941 | lr=6.72e-05 | epoch=1.1862
[train] step=556 | loss=0.2965 | lr=6.72e-05 | epoch=1.1883
[train] step=557 | loss=0.3209 | lr=6.71e-05 | epoch=1.1905
[train] step=558 | loss=0.3298 | lr=6.70e-05 | epoch=1.1926
[train] step=559 | loss=0.3151 | lr=6.69e-05 | epoch=1.1948
[train] step=560 | loss=0.3172 | lr=6.69e-05 | epoch=1.1969
[train] step=561 | loss=0.2925 | lr=6.68e-05 | epoch=1.1990
[train] step=562 | loss=0.3208 | lr=6.67e-05 | epoch=1.2012
[train] step=563 | loss=0.3358 | lr=6.66e-05 | epoch=1.2033
[train] step=564 | loss=0.2836 | lr=6.65e-05 | epoch=1.2055
[train] step=565 | loss=0.3531 | lr=6.65e-05 | epoch=1.2076
[train] step=566 | loss=0.3068 | lr=6.64e-05 | epoch=1.2097
[train] step=567 | loss=0.2774 | lr=6.63e-05 | epoch=1.2119
[train] step=568 | loss=0.2709 | lr=6.62e-05 | epoch=1.2140
[train] step=569 | loss=0.3499 | lr=6.61e-05 | epoch=1.2162
[train] step=570 | loss=0.2883 | lr=6.61e-05 | epoch=1.2183
[train] step=571 | loss=0.3124 | lr=6.60e-05 | epoch=1.2204
[train] step=572 | loss=0.3197 | lr=6.59e-05 | epoch=1.2226
[train] step=573 | loss=0.3407 | lr=6.58e-05 | epoch=1.2247
[train] step=574 | loss=0.3002 | lr=6.57e-05 | epoch=1.2269
[train] step=575 | loss=0.2927 | lr=6.57e-05 | epoch=1.2290
[train] step=576 | loss=0.3165 | lr=6.56e-05 | epoch=1.2311
[train] step=577 | loss=0.3542 | lr=6.55e-05 | epoch=1.2333
[train] step=578 | loss=0.3172 | lr=6.54e-05 | epoch=1.2354
[train] step=579 | loss=0.3593 | lr=6.53e-05 | epoch=1.2376
[train] step=580 | loss=0.2857 | lr=6.53e-05 | epoch=1.2397
[train] step=581 | loss=0.3044 | lr=6.52e-05 | epoch=1.2418
[train] step=582 | loss=0.2976 | lr=6.51e-05 | epoch=1.2440
[train] step=583 | loss=0.3553 | lr=6.50e-05 | epoch=1.2461
[train] step=584 | loss=0.3034 | lr=6.50e-05 | epoch=1.2483
[train] step=585 | loss=0.3236 | lr=6.49e-05 | epoch=1.2504
[train] step=586 | loss=0.2656 | lr=6.48e-05 | epoch=1.2525
[train] step=587 | loss=0.2965 | lr=6.47e-05 | epoch=1.2547
[train] step=588 | loss=0.3689 | lr=6.46e-05 | epoch=1.2568
[train] step=589 | loss=0.3547 | lr=6.46e-05 | epoch=1.2590
[train] step=590 | loss=0.3369 | lr=6.45e-05 | epoch=1.2611
[train] step=591 | loss=0.2663 | lr=6.44e-05 | epoch=1.2632
[train] step=592 | loss=0.3159 | lr=6.43e-05 | epoch=1.2654
[train] step=593 | loss=0.2933 | lr=6.42e-05 | epoch=1.2675
[train] step=594 | loss=0.2620 | lr=6.42e-05 | epoch=1.2697
[train] step=595 | loss=0.2596 | lr=6.41e-05 | epoch=1.2718
[train] step=596 | loss=0.2999 | lr=6.40e-05 | epoch=1.2739
[train] step=597 | loss=0.3024 | lr=6.39e-05 | epoch=1.2761
[train] step=598 | loss=0.3165 | lr=6.38e-05 | epoch=1.2782
[train] step=599 | loss=0.2990 | lr=6.38e-05 | epoch=1.2804
[train] step=600 | loss=0.3238 | lr=6.37e-05 | epoch=1.2825
[train] step=601 | loss=0.3017 | lr=6.36e-05 | epoch=1.2846
[train] step=602 | loss=0.2845 | lr=6.35e-05 | epoch=1.2868
[train] step=603 | loss=0.2831 | lr=6.34e-05 | epoch=1.2889
[train] step=604 | loss=0.2972 | lr=6.34e-05 | epoch=1.2911
[train] step=605 | loss=0.2742 | lr=6.33e-05 | epoch=1.2932
[train] step=606 | loss=0.2396 | lr=6.32e-05 | epoch=1.2953
[train] step=607 | loss=0.3276 | lr=6.31e-05 | epoch=1.2975
[train] step=608 | loss=0.2454 | lr=6.31e-05 | epoch=1.2996
[train] step=609 | loss=0.3393 | lr=6.30e-05 | epoch=1.3018
[train] step=610 | loss=0.3312 | lr=6.29e-05 | epoch=1.3039
[train] step=611 | loss=0.2471 | lr=6.28e-05 | epoch=1.3060
[train] step=612 | loss=0.3035 | lr=6.27e-05 | epoch=1.3082
[train] step=613 | loss=0.3286 | lr=6.27e-05 | epoch=1.3103
[train] step=614 | loss=0.3061 | lr=6.26e-05 | epoch=1.3125
[train] step=615 | loss=0.3195 | lr=6.25e-05 | epoch=1.3146
[train] step=616 | loss=0.2760 | lr=6.24e-05 | epoch=1.3167
[train] step=617 | loss=0.2406 | lr=6.23e-05 | epoch=1.3189
[train] step=618 | loss=0.3358 | lr=6.23e-05 | epoch=1.3210
[train] step=619 | loss=0.3034 | lr=6.22e-05 | epoch=1.3232
[train] step=620 | loss=0.2958 | lr=6.21e-05 | epoch=1.3253
[train] step=621 | loss=0.3323 | lr=6.20e-05 | epoch=1.3274
[train] step=622 | loss=0.2926 | lr=6.19e-05 | epoch=1.3296
[train] step=623 | loss=0.3136 | lr=6.19e-05 | epoch=1.3317
[train] step=624 | loss=0.2802 | lr=6.18e-05 | epoch=1.3339
[train] step=625 | loss=0.2841 | lr=6.17e-05 | epoch=1.3360
[train] step=626 | loss=0.2903 | lr=6.16e-05 | epoch=1.3381
[train] step=627 | loss=0.3528 | lr=6.16e-05 | epoch=1.3403
[train] step=628 | loss=0.3015 | lr=6.15e-05 | epoch=1.3424
[train] step=629 | loss=0.2332 | lr=6.14e-05 | epoch=1.3446
[train] step=630 | loss=0.3152 | lr=6.13e-05 | epoch=1.3467
[train] step=631 | loss=0.2663 | lr=6.12e-05 | epoch=1.3488
[train] step=632 | loss=0.3011 | lr=6.12e-05 | epoch=1.3510
[train] step=633 | loss=0.3024 | lr=6.11e-05 | epoch=1.3531
[train] step=634 | loss=0.3207 | lr=6.10e-05 | epoch=1.3553
[train] step=635 | loss=0.2956 | lr=6.09e-05 | epoch=1.3574
[train] step=636 | loss=0.2957 | lr=6.08e-05 | epoch=1.3596
[train] step=637 | loss=0.2722 | lr=6.08e-05 | epoch=1.3617
[train] step=638 | loss=0.3332 | lr=6.07e-05 | epoch=1.3638
[train] step=639 | loss=0.3048 | lr=6.06e-05 | epoch=1.3660
[train] step=640 | loss=0.2764 | lr=6.05e-05 | epoch=1.3681
[train] step=641 | loss=0.2995 | lr=6.04e-05 | epoch=1.3703
[train] step=642 | loss=0.2856 | lr=6.04e-05 | epoch=1.3724
[train] step=643 | loss=0.3191 | lr=6.03e-05 | epoch=1.3745
[train] step=644 | loss=0.3479 | lr=6.02e-05 | epoch=1.3767
[train] step=645 | loss=0.3420 | lr=6.01e-05 | epoch=1.3788
[train] step=646 | loss=0.3137 | lr=6.00e-05 | epoch=1.3810
[train] step=647 | loss=0.2731 | lr=6.00e-05 | epoch=1.3831
[train] step=648 | loss=0.2909 | lr=5.99e-05 | epoch=1.3852
[train] step=649 | loss=0.2298 | lr=5.98e-05 | epoch=1.3874
[train] step=650 | loss=0.2737 | lr=5.97e-05 | epoch=1.3895
[train] step=651 | loss=0.2627 | lr=5.97e-05 | epoch=1.3917
[train] step=652 | loss=0.2812 | lr=5.96e-05 | epoch=1.3938
[train] step=653 | loss=0.3472 | lr=5.95e-05 | epoch=1.3959
[train] step=654 | loss=0.2700 | lr=5.94e-05 | epoch=1.3981
[train] step=655 | loss=0.2728 | lr=5.93e-05 | epoch=1.4002
[train] step=656 | loss=0.3002 | lr=5.93e-05 | epoch=1.4024
[train] step=657 | loss=0.3008 | lr=5.92e-05 | epoch=1.4045
[train] step=658 | loss=0.3196 | lr=5.91e-05 | epoch=1.4066
[train] step=659 | loss=0.3288 | lr=5.90e-05 | epoch=1.4088
[train] step=660 | loss=0.3285 | lr=5.89e-05 | epoch=1.4109
[train] step=661 | loss=0.3782 | lr=5.89e-05 | epoch=1.4131
[train] step=662 | loss=0.3358 | lr=5.88e-05 | epoch=1.4152
[train] step=663 | loss=0.3103 | lr=5.87e-05 | epoch=1.4173
[train] step=664 | loss=0.3070 | lr=5.86e-05 | epoch=1.4195
[train] step=665 | loss=0.2897 | lr=5.85e-05 | epoch=1.4216
[train] step=666 | loss=0.2407 | lr=5.85e-05 | epoch=1.4238
[train] step=667 | loss=0.2965 | lr=5.84e-05 | epoch=1.4259
[train] step=668 | loss=0.2948 | lr=5.83e-05 | epoch=1.4280
[train] step=669 | loss=0.3110 | lr=5.82e-05 | epoch=1.4302
[train] step=670 | loss=0.2905 | lr=5.81e-05 | epoch=1.4323
[train] step=671 | loss=0.3005 | lr=5.81e-05 | epoch=1.4345
[train] step=672 | loss=0.2605 | lr=5.80e-05 | epoch=1.4366
[train] step=673 | loss=0.3409 | lr=5.79e-05 | epoch=1.4387
[train] step=674 | loss=0.3120 | lr=5.78e-05 | epoch=1.4409
[train] step=675 | loss=0.2604 | lr=5.78e-05 | epoch=1.4430
[train] step=676 | loss=0.2768 | lr=5.77e-05 | epoch=1.4452
[train] step=677 | loss=0.2820 | lr=5.76e-05 | epoch=1.4473
[train] step=678 | loss=0.2656 | lr=5.75e-05 | epoch=1.4494
[train] step=679 | loss=0.2693 | lr=5.74e-05 | epoch=1.4516
[train] step=680 | loss=0.2978 | lr=5.74e-05 | epoch=1.4537
[train] step=681 | loss=0.3054 | lr=5.73e-05 | epoch=1.4559
[train] step=682 | loss=0.2742 | lr=5.72e-05 | epoch=1.4580
[train] step=683 | loss=0.2865 | lr=5.71e-05 | epoch=1.4601
[train] step=684 | loss=0.2966 | lr=5.70e-05 | epoch=1.4623
[train] step=685 | loss=0.3552 | lr=5.70e-05 | epoch=1.4644
[train] step=686 | loss=0.2795 | lr=5.69e-05 | epoch=1.4666
[train] step=687 | loss=0.2794 | lr=5.68e-05 | epoch=1.4687
[train] step=688 | loss=0.3369 | lr=5.67e-05 | epoch=1.4708
[train] step=689 | loss=0.3369 | lr=5.66e-05 | epoch=1.4730
[train] step=690 | loss=0.3499 | lr=5.66e-05 | epoch=1.4751
[train] step=691 | loss=0.2468 | lr=5.65e-05 | epoch=1.4773
[train] step=692 | loss=0.3261 | lr=5.64e-05 | epoch=1.4794
[train] step=693 | loss=0.2838 | lr=5.63e-05 | epoch=1.4815
[train] step=694 | loss=0.3168 | lr=5.63e-05 | epoch=1.4837
[train] step=695 | loss=0.2616 | lr=5.62e-05 | epoch=1.4858
[train] step=696 | loss=0.3316 | lr=5.61e-05 | epoch=1.4880
[train] step=697 | loss=0.3439 | lr=5.60e-05 | epoch=1.4901
[train] step=698 | loss=0.3089 | lr=5.59e-05 | epoch=1.4922
[train] step=699 | loss=0.3567 | lr=5.59e-05 | epoch=1.4944

Saving model checkpoint to output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-699
2026-04-04 12:44:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:44:07 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:44:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:44:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-699/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-699/tokenizer_config.json

[train] step=700 | loss=0.3031 | lr=5.58e-05 | epoch=1.4965
[train] step=701 | loss=0.3196 | lr=5.57e-05 | epoch=1.4987
[train] step=702 | loss=0.2864 | lr=5.56e-05 | epoch=1.5008
[train] step=703 | loss=0.3057 | lr=5.55e-05 | epoch=1.5029
[train] step=704 | loss=0.2629 | lr=5.55e-05 | epoch=1.5051
[train] step=705 | loss=0.3511 | lr=5.54e-05 | epoch=1.5072
[train] step=706 | loss=0.3253 | lr=5.53e-05 | epoch=1.5094
[train] step=707 | loss=0.2886 | lr=5.52e-05 | epoch=1.5115
[train] step=708 | loss=0.2855 | lr=5.51e-05 | epoch=1.5136
[train] step=709 | loss=0.2331 | lr=5.51e-05 | epoch=1.5158
[train] step=710 | loss=0.3131 | lr=5.50e-05 | epoch=1.5179
[train] step=711 | loss=0.3031 | lr=5.49e-05 | epoch=1.5201
[train] step=712 | loss=0.2988 | lr=5.48e-05 | epoch=1.5222
[train] step=713 | loss=0.2667 | lr=5.47e-05 | epoch=1.5243
[train] step=714 | loss=0.2614 | lr=5.47e-05 | epoch=1.5265
[train] step=715 | loss=0.2720 | lr=5.46e-05 | epoch=1.5286
[train] step=716 | loss=0.2996 | lr=5.45e-05 | epoch=1.5308
[train] step=717 | loss=0.2972 | lr=5.44e-05 | epoch=1.5329
[train] step=718 | loss=0.3009 | lr=5.44e-05 | epoch=1.5350
[train] step=719 | loss=0.2311 | lr=5.43e-05 | epoch=1.5372
[train] step=720 | loss=0.3198 | lr=5.42e-05 | epoch=1.5393
[train] step=721 | loss=0.3185 | lr=5.41e-05 | epoch=1.5415
[train] step=722 | loss=0.2856 | lr=5.40e-05 | epoch=1.5436
[train] step=723 | loss=0.3072 | lr=5.40e-05 | epoch=1.5457
[train] step=724 | loss=0.2802 | lr=5.39e-05 | epoch=1.5479
[train] step=725 | loss=0.3924 | lr=5.38e-05 | epoch=1.5500
[train] step=726 | loss=0.3029 | lr=5.37e-05 | epoch=1.5522
[train] step=727 | loss=0.2748 | lr=5.36e-05 | epoch=1.5543
[train] step=728 | loss=0.2746 | lr=5.36e-05 | epoch=1.5564
[train] step=729 | loss=0.3115 | lr=5.35e-05 | epoch=1.5586
[train] step=730 | loss=0.3015 | lr=5.34e-05 | epoch=1.5607
[train] step=731 | loss=0.3000 | lr=5.33e-05 | epoch=1.5629
[train] step=732 | loss=0.3498 | lr=5.32e-05 | epoch=1.5650
[train] step=733 | loss=0.2763 | lr=5.32e-05 | epoch=1.5671
[train] step=734 | loss=0.2685 | lr=5.31e-05 | epoch=1.5693
[train] step=735 | loss=0.2993 | lr=5.30e-05 | epoch=1.5714
[train] step=736 | loss=0.2858 | lr=5.29e-05 | epoch=1.5736
[train] step=737 | loss=0.2823 | lr=5.28e-05 | epoch=1.5757
[train] step=738 | loss=0.2982 | lr=5.28e-05 | epoch=1.5778
[train] step=739 | loss=0.3211 | lr=5.27e-05 | epoch=1.5800
[train] step=740 | loss=0.3310 | lr=5.26e-05 | epoch=1.5821
[train] step=741 | loss=0.2944 | lr=5.25e-05 | epoch=1.5843
[train] step=742 | loss=0.3343 | lr=5.25e-05 | epoch=1.5864
[train] step=743 | loss=0.3113 | lr=5.24e-05 | epoch=1.5886
[train] step=744 | loss=0.2985 | lr=5.23e-05 | epoch=1.5907
[train] step=745 | loss=0.2694 | lr=5.22e-05 | epoch=1.5928
[train] step=746 | loss=0.3062 | lr=5.21e-05 | epoch=1.5950
[train] step=747 | loss=0.3384 | lr=5.21e-05 | epoch=1.5971
[train] step=748 | loss=0.2503 | lr=5.20e-05 | epoch=1.5993
[train] step=749 | loss=0.2819 | lr=5.19e-05 | epoch=1.6014
[train] step=750 | loss=0.3164 | lr=5.18e-05 | epoch=1.6035
[train] step=751 | loss=0.3104 | lr=5.17e-05 | epoch=1.6057
[train] step=752 | loss=0.3345 | lr=5.17e-05 | epoch=1.6078
[train] step=753 | loss=0.3315 | lr=5.16e-05 | epoch=1.6100
[train] step=754 | loss=0.3030 | lr=5.15e-05 | epoch=1.6121
[train] step=755 | loss=0.3024 | lr=5.14e-05 | epoch=1.6142
[train] step=756 | loss=0.3003 | lr=5.13e-05 | epoch=1.6164
[train] step=757 | loss=0.2874 | lr=5.13e-05 | epoch=1.6185
[train] step=758 | loss=0.2804 | lr=5.12e-05 | epoch=1.6207
[train] step=759 | loss=0.2954 | lr=5.11e-05 | epoch=1.6228
[train] step=760 | loss=0.2630 | lr=5.10e-05 | epoch=1.6249
[train] step=761 | loss=0.2948 | lr=5.09e-05 | epoch=1.6271
[train] step=762 | loss=0.2845 | lr=5.09e-05 | epoch=1.6292
[train] step=763 | loss=0.3057 | lr=5.08e-05 | epoch=1.6314
[train] step=764 | loss=0.3366 | lr=5.07e-05 | epoch=1.6335
[train] step=765 | loss=0.2727 | lr=5.06e-05 | epoch=1.6356
[train] step=766 | loss=0.3530 | lr=5.06e-05 | epoch=1.6378
[train] step=767 | loss=0.3163 | lr=5.05e-05 | epoch=1.6399
[train] step=768 | loss=0.2615 | lr=5.04e-05 | epoch=1.6421
[train] step=769 | loss=0.3295 | lr=5.03e-05 | epoch=1.6442
[train] step=770 | loss=0.2602 | lr=5.02e-05 | epoch=1.6463
[train] step=771 | loss=0.2991 | lr=5.02e-05 | epoch=1.6485
[train] step=772 | loss=0.2543 | lr=5.01e-05 | epoch=1.6506
[train] step=773 | loss=0.2637 | lr=5.00e-05 | epoch=1.6528
[train] step=774 | loss=0.2579 | lr=4.99e-05 | epoch=1.6549
[train] step=775 | loss=0.3098 | lr=4.98e-05 | epoch=1.6570
[train] step=776 | loss=0.2621 | lr=4.98e-05 | epoch=1.6592
[train] step=777 | loss=0.3158 | lr=4.97e-05 | epoch=1.6613
[train] step=778 | loss=0.3091 | lr=4.96e-05 | epoch=1.6635
[train] step=779 | loss=0.3071 | lr=4.95e-05 | epoch=1.6656
[train] step=780 | loss=0.3426 | lr=4.94e-05 | epoch=1.6677
[train] step=781 | loss=0.3200 | lr=4.94e-05 | epoch=1.6699
[train] step=782 | loss=0.2658 | lr=4.93e-05 | epoch=1.6720
[train] step=783 | loss=0.3104 | lr=4.92e-05 | epoch=1.6742
[train] step=784 | loss=0.2978 | lr=4.91e-05 | epoch=1.6763
[train] step=785 | loss=0.2611 | lr=4.91e-05 | epoch=1.6784
[train] step=786 | loss=0.3077 | lr=4.90e-05 | epoch=1.6806
[train] step=787 | loss=0.2735 | lr=4.89e-05 | epoch=1.6827
[train] step=788 | loss=0.3301 | lr=4.88e-05 | epoch=1.6849
[train] step=789 | loss=0.3096 | lr=4.87e-05 | epoch=1.6870
[train] step=790 | loss=0.2839 | lr=4.87e-05 | epoch=1.6891
[train] step=791 | loss=0.2751 | lr=4.86e-05 | epoch=1.6913
[train] step=792 | loss=0.2891 | lr=4.85e-05 | epoch=1.6934
[train] step=793 | loss=0.3001 | lr=4.84e-05 | epoch=1.6956
[train] step=794 | loss=0.3115 | lr=4.83e-05 | epoch=1.6977
[train] step=795 | loss=0.2934 | lr=4.83e-05 | epoch=1.6998
[train] step=796 | loss=0.3606 | lr=4.82e-05 | epoch=1.7020
[train] step=797 | loss=0.2978 | lr=4.81e-05 | epoch=1.7041
[train] step=798 | loss=0.3042 | lr=4.80e-05 | epoch=1.7063
[train] step=799 | loss=0.3061 | lr=4.79e-05 | epoch=1.7084
[train] step=800 | loss=0.3117 | lr=4.79e-05 | epoch=1.7105
[train] step=801 | loss=0.3211 | lr=4.78e-05 | epoch=1.7127
[train] step=802 | loss=0.2882 | lr=4.77e-05 | epoch=1.7148
[train] step=803 | loss=0.3655 | lr=4.76e-05 | epoch=1.7170
[train] step=804 | loss=0.2777 | lr=4.75e-05 | epoch=1.7191
[train] step=805 | loss=0.2785 | lr=4.75e-05 | epoch=1.7212
[train] step=806 | loss=0.2954 | lr=4.74e-05 | epoch=1.7234
[train] step=807 | loss=0.3066 | lr=4.73e-05 | epoch=1.7255
[train] step=808 | loss=0.2505 | lr=4.72e-05 | epoch=1.7277
[train] step=809 | loss=0.2704 | lr=4.72e-05 | epoch=1.7298
[train] step=810 | loss=0.2778 | lr=4.71e-05 | epoch=1.7319
[train] step=811 | loss=0.2802 | lr=4.70e-05 | epoch=1.7341
[train] step=812 | loss=0.3039 | lr=4.69e-05 | epoch=1.7362
[train] step=813 | loss=0.2905 | lr=4.68e-05 | epoch=1.7384
[train] step=814 | loss=0.2508 | lr=4.68e-05 | epoch=1.7405
[train] step=815 | loss=0.2495 | lr=4.67e-05 | epoch=1.7426
[train] step=816 | loss=0.3424 | lr=4.66e-05 | epoch=1.7448
[train] step=817 | loss=0.3068 | lr=4.65e-05 | epoch=1.7469
[train] step=818 | loss=0.3451 | lr=4.64e-05 | epoch=1.7491
[train] step=819 | loss=0.2719 | lr=4.64e-05 | epoch=1.7512
[train] step=820 | loss=0.2929 | lr=4.63e-05 | epoch=1.7533
[train] step=821 | loss=0.3611 | lr=4.62e-05 | epoch=1.7555
[train] step=822 | loss=0.2621 | lr=4.61e-05 | epoch=1.7576
[train] step=823 | loss=0.3429 | lr=4.60e-05 | epoch=1.7598
[train] step=824 | loss=0.2784 | lr=4.60e-05 | epoch=1.7619
[train] step=825 | loss=0.3346 | lr=4.59e-05 | epoch=1.7640
[train] step=826 | loss=0.2703 | lr=4.58e-05 | epoch=1.7662
[train] step=827 | loss=0.2939 | lr=4.57e-05 | epoch=1.7683
[train] step=828 | loss=0.3094 | lr=4.56e-05 | epoch=1.7705
[train] step=829 | loss=0.2532 | lr=4.56e-05 | epoch=1.7726
[train] step=830 | loss=0.3082 | lr=4.55e-05 | epoch=1.7747
[train] step=831 | loss=0.2624 | lr=4.54e-05 | epoch=1.7769
[train] step=832 | loss=0.3213 | lr=4.53e-05 | epoch=1.7790
[train] step=833 | loss=0.3273 | lr=4.53e-05 | epoch=1.7812
[train] step=834 | loss=0.2664 | lr=4.52e-05 | epoch=1.7833
[train] step=835 | loss=0.3397 | lr=4.51e-05 | epoch=1.7854
[train] step=836 | loss=0.2851 | lr=4.50e-05 | epoch=1.7876
[train] step=837 | loss=0.3078 | lr=4.49e-05 | epoch=1.7897
[train] step=838 | loss=0.3505 | lr=4.49e-05 | epoch=1.7919
[train] step=839 | loss=0.3006 | lr=4.48e-05 | epoch=1.7940
[train] step=840 | loss=0.2884 | lr=4.47e-05 | epoch=1.7961
[train] step=841 | loss=0.2711 | lr=4.46e-05 | epoch=1.7983
[train] step=842 | loss=0.3076 | lr=4.45e-05 | epoch=1.8004
[train] step=843 | loss=0.2573 | lr=4.45e-05 | epoch=1.8026
[train] step=844 | loss=0.2712 | lr=4.44e-05 | epoch=1.8047
[train] step=845 | loss=0.3121 | lr=4.43e-05 | epoch=1.8068
[train] step=846 | loss=0.2904 | lr=4.42e-05 | epoch=1.8090
[train] step=847 | loss=0.2687 | lr=4.41e-05 | epoch=1.8111
[train] step=848 | loss=0.2374 | lr=4.41e-05 | epoch=1.8133
[train] step=849 | loss=0.2383 | lr=4.40e-05 | epoch=1.8154
[train] step=850 | loss=0.3127 | lr=4.39e-05 | epoch=1.8175
[train] step=851 | loss=0.3113 | lr=4.38e-05 | epoch=1.8197
[train] step=852 | loss=0.2634 | lr=4.37e-05 | epoch=1.8218
[train] step=853 | loss=0.3318 | lr=4.37e-05 | epoch=1.8240
[train] step=854 | loss=0.2813 | lr=4.36e-05 | epoch=1.8261
[train] step=855 | loss=0.3076 | lr=4.35e-05 | epoch=1.8283
[train] step=856 | loss=0.3594 | lr=4.34e-05 | epoch=1.8304
[train] step=857 | loss=0.2967 | lr=4.34e-05 | epoch=1.8325
[train] step=858 | loss=0.2445 | lr=4.33e-05 | epoch=1.8347
[train] step=859 | loss=0.3009 | lr=4.32e-05 | epoch=1.8368
[train] step=860 | loss=0.3206 | lr=4.31e-05 | epoch=1.8390
[train] step=861 | loss=0.2736 | lr=4.30e-05 | epoch=1.8411
[train] step=862 | loss=0.2590 | lr=4.30e-05 | epoch=1.8432
[train] step=863 | loss=0.2931 | lr=4.29e-05 | epoch=1.8454
[train] step=864 | loss=0.3266 | lr=4.28e-05 | epoch=1.8475
[train] step=865 | loss=0.2954 | lr=4.27e-05 | epoch=1.8497
[train] step=866 | loss=0.2945 | lr=4.26e-05 | epoch=1.8518
[train] step=867 | loss=0.2947 | lr=4.26e-05 | epoch=1.8539
[train] step=868 | loss=0.2339 | lr=4.25e-05 | epoch=1.8561
[train] step=869 | loss=0.3028 | lr=4.24e-05 | epoch=1.8582
[train] step=870 | loss=0.3103 | lr=4.23e-05 | epoch=1.8604
[train] step=871 | loss=0.3158 | lr=4.22e-05 | epoch=1.8625
[train] step=872 | loss=0.3594 | lr=4.22e-05 | epoch=1.8646
[train] step=873 | loss=0.2841 | lr=4.21e-05 | epoch=1.8668
[train] step=874 | loss=0.2963 | lr=4.20e-05 | epoch=1.8689
[train] step=875 | loss=0.2712 | lr=4.19e-05 | epoch=1.8711
[train] step=876 | loss=0.3259 | lr=4.19e-05 | epoch=1.8732
[train] step=877 | loss=0.3225 | lr=4.18e-05 | epoch=1.8753
[train] step=878 | loss=0.2812 | lr=4.17e-05 | epoch=1.8775
[train] step=879 | loss=0.2814 | lr=4.16e-05 | epoch=1.8796
[train] step=880 | loss=0.3363 | lr=4.15e-05 | epoch=1.8818
[train] step=881 | loss=0.2828 | lr=4.15e-05 | epoch=1.8839
[train] step=882 | loss=0.3345 | lr=4.14e-05 | epoch=1.8860
[train] step=883 | loss=0.2791 | lr=4.13e-05 | epoch=1.8882
[train] step=884 | loss=0.3312 | lr=4.12e-05 | epoch=1.8903
[train] step=885 | loss=0.3509 | lr=4.11e-05 | epoch=1.8925
[train] step=886 | loss=0.2614 | lr=4.11e-05 | epoch=1.8946
[train] step=887 | loss=0.3344 | lr=4.10e-05 | epoch=1.8967
[train] step=888 | loss=0.3434 | lr=4.09e-05 | epoch=1.8989
[train] step=889 | loss=0.3127 | lr=4.08e-05 | epoch=1.9010
[train] step=890 | loss=0.3103 | lr=4.07e-05 | epoch=1.9032
[train] step=891 | loss=0.2814 | lr=4.07e-05 | epoch=1.9053
[train] step=892 | loss=0.2521 | lr=4.06e-05 | epoch=1.9074
[train] step=893 | loss=0.3042 | lr=4.05e-05 | epoch=1.9096
[train] step=894 | loss=0.3356 | lr=4.04e-05 | epoch=1.9117
[train] step=895 | loss=0.3122 | lr=4.03e-05 | epoch=1.9139
[train] step=896 | loss=0.2231 | lr=4.03e-05 | epoch=1.9160
[train] step=897 | loss=0.2911 | lr=4.02e-05 | epoch=1.9181
[train] step=898 | loss=0.3213 | lr=4.01e-05 | epoch=1.9203
[train] step=899 | loss=0.3097 | lr=4.00e-05 | epoch=1.9224
[train] step=900 | loss=0.3436 | lr=4.00e-05 | epoch=1.9246
[train] step=901 | loss=0.2752 | lr=3.99e-05 | epoch=1.9267
[train] step=902 | loss=0.2914 | lr=3.98e-05 | epoch=1.9288
[train] step=903 | loss=0.2557 | lr=3.97e-05 | epoch=1.9310
[train] step=904 | loss=0.2998 | lr=3.96e-05 | epoch=1.9331
[train] step=905 | loss=0.3246 | lr=3.96e-05 | epoch=1.9353
[train] step=906 | loss=0.3198 | lr=3.95e-05 | epoch=1.9374
[train] step=907 | loss=0.2819 | lr=3.94e-05 | epoch=1.9395
[train] step=908 | loss=0.2901 | lr=3.93e-05 | epoch=1.9417
[train] step=909 | loss=0.3402 | lr=3.92e-05 | epoch=1.9438
[train] step=910 | loss=0.2983 | lr=3.92e-05 | epoch=1.9460
[train] step=911 | loss=0.3039 | lr=3.91e-05 | epoch=1.9481
[train] step=912 | loss=0.3080 | lr=3.90e-05 | epoch=1.9502
[train] step=913 | loss=0.3150 | lr=3.89e-05 | epoch=1.9524
[train] step=914 | loss=0.2709 | lr=3.88e-05 | epoch=1.9545
[train] step=915 | loss=0.2918 | lr=3.88e-05 | epoch=1.9567
[train] step=916 | loss=0.2924 | lr=3.87e-05 | epoch=1.9588
[train] step=917 | loss=0.2737 | lr=3.86e-05 | epoch=1.9609
[train] step=918 | loss=0.3117 | lr=3.85e-05 | epoch=1.9631
[train] step=919 | loss=0.2901 | lr=3.84e-05 | epoch=1.9652
[train] step=920 | loss=0.2676 | lr=3.84e-05 | epoch=1.9674
[train] step=921 | loss=0.2929 | lr=3.83e-05 | epoch=1.9695
[train] step=922 | loss=0.3037 | lr=3.82e-05 | epoch=1.9716
[train] step=923 | loss=0.2504 | lr=3.81e-05 | epoch=1.9738
[train] step=924 | loss=0.2927 | lr=3.81e-05 | epoch=1.9759
[train] step=925 | loss=0.2949 | lr=3.80e-05 | epoch=1.9781
[train] step=926 | loss=0.2837 | lr=3.79e-05 | epoch=1.9802
[train] step=927 | loss=0.3066 | lr=3.78e-05 | epoch=1.9823
[train] step=928 | loss=0.3094 | lr=3.77e-05 | epoch=1.9845
[train] step=929 | loss=0.3334 | lr=3.77e-05 | epoch=1.9866
[train] step=930 | loss=0.3073 | lr=3.76e-05 | epoch=1.9888
[train] step=931 | loss=0.2942 | lr=3.75e-05 | epoch=1.9909
[train] step=932 | loss=0.3033 | lr=3.74e-05 | epoch=1.9930

Saving model checkpoint to output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-932
2026-04-04 12:47:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:47:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:47:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:47:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-932/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-932/tokenizer_config.json

[train] step=933 | loss=0.3523 | lr=3.73e-05 | epoch=1.9952
[train] step=934 | loss=0.3363 | lr=3.73e-05 | epoch=1.9973
[train] step=935 | loss=0.3173 | lr=3.72e-05 | epoch=1.9995
[train] step=936 | loss=0.1649 | lr=3.71e-05 | epoch=2.0000
[train] step=937 | loss=0.2796 | lr=3.70e-05 | epoch=2.0021
[train] step=938 | loss=0.2604 | lr=3.69e-05 | epoch=2.0043
[train] step=939 | loss=0.2229 | lr=3.69e-05 | epoch=2.0064
[train] step=940 | loss=0.2685 | lr=3.68e-05 | epoch=2.0086
[train] step=941 | loss=0.3105 | lr=3.67e-05 | epoch=2.0107
[train] step=942 | loss=0.2983 | lr=3.66e-05 | epoch=2.0128
[train] step=943 | loss=0.2954 | lr=3.66e-05 | epoch=2.0150
[train] step=944 | loss=0.3385 | lr=3.65e-05 | epoch=2.0171
[train] step=945 | loss=0.2760 | lr=3.64e-05 | epoch=2.0193
[train] step=946 | loss=0.3007 | lr=3.63e-05 | epoch=2.0214
[train] step=947 | loss=0.2860 | lr=3.62e-05 | epoch=2.0235
[train] step=948 | loss=0.2820 | lr=3.62e-05 | epoch=2.0257
[train] step=949 | loss=0.3400 | lr=3.61e-05 | epoch=2.0278
[train] step=950 | loss=0.2663 | lr=3.60e-05 | epoch=2.0300
[train] step=951 | loss=0.2800 | lr=3.59e-05 | epoch=2.0321
[train] step=952 | loss=0.2983 | lr=3.58e-05 | epoch=2.0342
[train] step=953 | loss=0.3003 | lr=3.58e-05 | epoch=2.0364
[train] step=954 | loss=0.2934 | lr=3.57e-05 | epoch=2.0385
[train] step=955 | loss=0.4053 | lr=3.56e-05 | epoch=2.0407
[train] step=956 | loss=0.2742 | lr=3.55e-05 | epoch=2.0428
[train] step=957 | loss=0.2723 | lr=3.54e-05 | epoch=2.0449
[train] step=958 | loss=0.3256 | lr=3.54e-05 | epoch=2.0471
[train] step=959 | loss=0.2548 | lr=3.53e-05 | epoch=2.0492
[train] step=960 | loss=0.3034 | lr=3.52e-05 | epoch=2.0514
[train] step=961 | loss=0.2765 | lr=3.51e-05 | epoch=2.0535
[train] step=962 | loss=0.2855 | lr=3.50e-05 | epoch=2.0556
[train] step=963 | loss=0.3133 | lr=3.50e-05 | epoch=2.0578
[train] step=964 | loss=0.2345 | lr=3.49e-05 | epoch=2.0599
[train] step=965 | loss=0.2712 | lr=3.48e-05 | epoch=2.0621
[train] step=966 | loss=0.2783 | lr=3.47e-05 | epoch=2.0642
[train] step=967 | loss=0.3245 | lr=3.47e-05 | epoch=2.0663
[train] step=968 | loss=0.3290 | lr=3.46e-05 | epoch=2.0685
[train] step=969 | loss=0.3456 | lr=3.45e-05 | epoch=2.0706
[train] step=970 | loss=0.2855 | lr=3.44e-05 | epoch=2.0728
[train] step=971 | loss=0.2967 | lr=3.43e-05 | epoch=2.0749
[train] step=972 | loss=0.3516 | lr=3.43e-05 | epoch=2.0770
[train] step=973 | loss=0.2705 | lr=3.42e-05 | epoch=2.0792
[train] step=974 | loss=0.3881 | lr=3.41e-05 | epoch=2.0813
[train] step=975 | loss=0.2556 | lr=3.40e-05 | epoch=2.0835
[train] step=976 | loss=0.2601 | lr=3.39e-05 | epoch=2.0856
[train] step=977 | loss=0.3096 | lr=3.39e-05 | epoch=2.0877
[train] step=978 | loss=0.2384 | lr=3.38e-05 | epoch=2.0899
[train] step=979 | loss=0.2692 | lr=3.37e-05 | epoch=2.0920
[train] step=980 | loss=0.2698 | lr=3.36e-05 | epoch=2.0942
[train] step=981 | loss=0.3090 | lr=3.35e-05 | epoch=2.0963
[train] step=982 | loss=0.2976 | lr=3.35e-05 | epoch=2.0984
[train] step=983 | loss=0.3020 | lr=3.34e-05 | epoch=2.1006
[train] step=984 | loss=0.2598 | lr=3.33e-05 | epoch=2.1027
[train] step=985 | loss=0.2939 | lr=3.32e-05 | epoch=2.1049
[train] step=986 | loss=0.2944 | lr=3.31e-05 | epoch=2.1070
[train] step=987 | loss=0.3582 | lr=3.31e-05 | epoch=2.1091
[train] step=988 | loss=0.2686 | lr=3.30e-05 | epoch=2.1113
[train] step=989 | loss=0.3499 | lr=3.29e-05 | epoch=2.1134
[train] step=990 | loss=0.2818 | lr=3.28e-05 | epoch=2.1156
[train] step=991 | loss=0.2677 | lr=3.28e-05 | epoch=2.1177
[train] step=992 | loss=0.2812 | lr=3.27e-05 | epoch=2.1199
[train] step=993 | loss=0.2393 | lr=3.26e-05 | epoch=2.1220
[train] step=994 | loss=0.2914 | lr=3.25e-05 | epoch=2.1241
[train] step=995 | loss=0.2983 | lr=3.24e-05 | epoch=2.1263
[train] step=996 | loss=0.2583 | lr=3.24e-05 | epoch=2.1284
[train] step=997 | loss=0.2628 | lr=3.23e-05 | epoch=2.1306
[train] step=998 | loss=0.2993 | lr=3.22e-05 | epoch=2.1327
[train] step=999 | loss=0.3027 | lr=3.21e-05 | epoch=2.1348
[train] step=1000 | loss=0.2956 | lr=3.20e-05 | epoch=2.1370
[train] step=1001 | loss=0.2423 | lr=3.20e-05 | epoch=2.1391
[train] step=1002 | loss=0.2867 | lr=3.19e-05 | epoch=2.1413
[train] step=1003 | loss=0.2753 | lr=3.18e-05 | epoch=2.1434
[train] step=1004 | loss=0.3123 | lr=3.17e-05 | epoch=2.1455
[train] step=1005 | loss=0.3002 | lr=3.16e-05 | epoch=2.1477
[train] step=1006 | loss=0.2783 | lr=3.16e-05 | epoch=2.1498
[train] step=1007 | loss=0.2877 | lr=3.15e-05 | epoch=2.1520
[train] step=1008 | loss=0.2707 | lr=3.14e-05 | epoch=2.1541
[train] step=1009 | loss=0.2694 | lr=3.13e-05 | epoch=2.1562
[train] step=1010 | loss=0.2372 | lr=3.13e-05 | epoch=2.1584
[train] step=1011 | loss=0.3757 | lr=3.12e-05 | epoch=2.1605
[train] step=1012 | loss=0.2957 | lr=3.11e-05 | epoch=2.1627
[train] step=1013 | loss=0.3151 | lr=3.10e-05 | epoch=2.1648
[train] step=1014 | loss=0.2842 | lr=3.09e-05 | epoch=2.1669
[train] step=1015 | loss=0.3181 | lr=3.09e-05 | epoch=2.1691
[train] step=1016 | loss=0.2918 | lr=3.08e-05 | epoch=2.1712
[train] step=1017 | loss=0.2969 | lr=3.07e-05 | epoch=2.1734
[train] step=1018 | loss=0.3157 | lr=3.06e-05 | epoch=2.1755
[train] step=1019 | loss=0.3343 | lr=3.05e-05 | epoch=2.1776
[train] step=1020 | loss=0.2448 | lr=3.05e-05 | epoch=2.1798
[train] step=1021 | loss=0.2716 | lr=3.04e-05 | epoch=2.1819
[train] step=1022 | loss=0.3190 | lr=3.03e-05 | epoch=2.1841
[train] step=1023 | loss=0.2635 | lr=3.02e-05 | epoch=2.1862
[train] step=1024 | loss=0.2992 | lr=3.01e-05 | epoch=2.1883
[train] step=1025 | loss=0.3099 | lr=3.01e-05 | epoch=2.1905
[train] step=1026 | loss=0.3480 | lr=3.00e-05 | epoch=2.1926
[train] step=1027 | loss=0.3112 | lr=2.99e-05 | epoch=2.1948
[train] step=1028 | loss=0.2938 | lr=2.98e-05 | epoch=2.1969
[train] step=1029 | loss=0.3584 | lr=2.97e-05 | epoch=2.1990
[train] step=1030 | loss=0.2826 | lr=2.97e-05 | epoch=2.2012
[train] step=1031 | loss=0.3000 | lr=2.96e-05 | epoch=2.2033
[train] step=1032 | loss=0.2995 | lr=2.95e-05 | epoch=2.2055
[train] step=1033 | loss=0.3016 | lr=2.94e-05 | epoch=2.2076
[train] step=1034 | loss=0.2921 | lr=2.94e-05 | epoch=2.2097
[train] step=1035 | loss=0.3359 | lr=2.93e-05 | epoch=2.2119
[train] step=1036 | loss=0.2618 | lr=2.92e-05 | epoch=2.2140
[train] step=1037 | loss=0.3302 | lr=2.91e-05 | epoch=2.2162
[train] step=1038 | loss=0.3422 | lr=2.90e-05 | epoch=2.2183
[train] step=1039 | loss=0.2922 | lr=2.90e-05 | epoch=2.2204
[train] step=1040 | loss=0.2373 | lr=2.89e-05 | epoch=2.2226
[train] step=1041 | loss=0.2422 | lr=2.88e-05 | epoch=2.2247
[train] step=1042 | loss=0.2779 | lr=2.87e-05 | epoch=2.2269
[train] step=1043 | loss=0.2701 | lr=2.86e-05 | epoch=2.2290
[train] step=1044 | loss=0.3477 | lr=2.86e-05 | epoch=2.2311
[train] step=1045 | loss=0.2728 | lr=2.85e-05 | epoch=2.2333
[train] step=1046 | loss=0.3461 | lr=2.84e-05 | epoch=2.2354
[train] step=1047 | loss=0.3186 | lr=2.83e-05 | epoch=2.2376
[train] step=1048 | loss=0.2735 | lr=2.82e-05 | epoch=2.2397
[train] step=1049 | loss=0.3042 | lr=2.82e-05 | epoch=2.2418
[train] step=1050 | loss=0.2550 | lr=2.81e-05 | epoch=2.2440
[train] step=1051 | loss=0.2616 | lr=2.80e-05 | epoch=2.2461
[train] step=1052 | loss=0.3157 | lr=2.79e-05 | epoch=2.2483
[train] step=1053 | loss=0.2767 | lr=2.78e-05 | epoch=2.2504
[train] step=1054 | loss=0.2721 | lr=2.78e-05 | epoch=2.2525
[train] step=1055 | loss=0.3176 | lr=2.77e-05 | epoch=2.2547
[train] step=1056 | loss=0.2972 | lr=2.76e-05 | epoch=2.2568
[train] step=1057 | loss=0.2438 | lr=2.75e-05 | epoch=2.2590
[train] step=1058 | loss=0.2495 | lr=2.75e-05 | epoch=2.2611
[train] step=1059 | loss=0.3238 | lr=2.74e-05 | epoch=2.2632
[train] step=1060 | loss=0.2889 | lr=2.73e-05 | epoch=2.2654
[train] step=1061 | loss=0.2885 | lr=2.72e-05 | epoch=2.2675
[train] step=1062 | loss=0.2965 | lr=2.71e-05 | epoch=2.2697
[train] step=1063 | loss=0.2360 | lr=2.71e-05 | epoch=2.2718
[train] step=1064 | loss=0.2716 | lr=2.70e-05 | epoch=2.2739
[train] step=1065 | loss=0.2598 | lr=2.69e-05 | epoch=2.2761
[train] step=1066 | loss=0.2803 | lr=2.68e-05 | epoch=2.2782
[train] step=1067 | loss=0.2617 | lr=2.67e-05 | epoch=2.2804
[train] step=1068 | loss=0.3197 | lr=2.67e-05 | epoch=2.2825
[train] step=1069 | loss=0.2375 | lr=2.66e-05 | epoch=2.2846
[train] step=1070 | loss=0.2983 | lr=2.65e-05 | epoch=2.2868
[train] step=1071 | loss=0.2979 | lr=2.64e-05 | epoch=2.2889
[train] step=1072 | loss=0.2411 | lr=2.63e-05 | epoch=2.2911
[train] step=1073 | loss=0.2607 | lr=2.63e-05 | epoch=2.2932
[train] step=1074 | loss=0.2642 | lr=2.62e-05 | epoch=2.2953
[train] step=1075 | loss=0.3306 | lr=2.61e-05 | epoch=2.2975
[train] step=1076 | loss=0.2928 | lr=2.60e-05 | epoch=2.2996
[train] step=1077 | loss=0.2571 | lr=2.59e-05 | epoch=2.3018
[train] step=1078 | loss=0.2647 | lr=2.59e-05 | epoch=2.3039
[train] step=1079 | loss=0.3292 | lr=2.58e-05 | epoch=2.3060
[train] step=1080 | loss=0.2729 | lr=2.57e-05 | epoch=2.3082
[train] step=1081 | loss=0.3533 | lr=2.56e-05 | epoch=2.3103
[train] step=1082 | loss=0.3230 | lr=2.56e-05 | epoch=2.3125
[train] step=1083 | loss=0.3136 | lr=2.55e-05 | epoch=2.3146
[train] step=1084 | loss=0.2526 | lr=2.54e-05 | epoch=2.3167
[train] step=1085 | loss=0.2947 | lr=2.53e-05 | epoch=2.3189
[train] step=1086 | loss=0.2917 | lr=2.52e-05 | epoch=2.3210
[train] step=1087 | loss=0.3179 | lr=2.52e-05 | epoch=2.3232
[train] step=1088 | loss=0.3121 | lr=2.51e-05 | epoch=2.3253
[train] step=1089 | loss=0.2703 | lr=2.50e-05 | epoch=2.3274
[train] step=1090 | loss=0.3049 | lr=2.49e-05 | epoch=2.3296
[train] step=1091 | loss=0.3023 | lr=2.48e-05 | epoch=2.3317
[train] step=1092 | loss=0.3019 | lr=2.48e-05 | epoch=2.3339
[train] step=1093 | loss=0.2696 | lr=2.47e-05 | epoch=2.3360
[train] step=1094 | loss=0.3020 | lr=2.46e-05 | epoch=2.3381
[train] step=1095 | loss=0.3113 | lr=2.45e-05 | epoch=2.3403
[train] step=1096 | loss=0.2752 | lr=2.44e-05 | epoch=2.3424
[train] step=1097 | loss=0.3141 | lr=2.44e-05 | epoch=2.3446
[train] step=1098 | loss=0.2836 | lr=2.43e-05 | epoch=2.3467
[train] step=1099 | loss=0.2857 | lr=2.42e-05 | epoch=2.3488
[train] step=1100 | loss=0.2690 | lr=2.41e-05 | epoch=2.3510
[train] step=1101 | loss=0.3103 | lr=2.41e-05 | epoch=2.3531
[train] step=1102 | loss=0.2880 | lr=2.40e-05 | epoch=2.3553
[train] step=1103 | loss=0.2641 | lr=2.39e-05 | epoch=2.3574
[train] step=1104 | loss=0.2992 | lr=2.38e-05 | epoch=2.3596
[train] step=1105 | loss=0.2639 | lr=2.37e-05 | epoch=2.3617
[train] step=1106 | loss=0.3738 | lr=2.37e-05 | epoch=2.3638
[train] step=1107 | loss=0.2949 | lr=2.36e-05 | epoch=2.3660
[train] step=1108 | loss=0.3002 | lr=2.35e-05 | epoch=2.3681
[train] step=1109 | loss=0.3177 | lr=2.34e-05 | epoch=2.3703
[train] step=1110 | loss=0.2757 | lr=2.33e-05 | epoch=2.3724
[train] step=1111 | loss=0.3081 | lr=2.33e-05 | epoch=2.3745
[train] step=1112 | loss=0.2713 | lr=2.32e-05 | epoch=2.3767
[train] step=1113 | loss=0.3483 | lr=2.31e-05 | epoch=2.3788
[train] step=1114 | loss=0.3197 | lr=2.30e-05 | epoch=2.3810
[train] step=1115 | loss=0.2392 | lr=2.29e-05 | epoch=2.3831
[train] step=1116 | loss=0.3345 | lr=2.29e-05 | epoch=2.3852
[train] step=1117 | loss=0.2878 | lr=2.28e-05 | epoch=2.3874
[train] step=1118 | loss=0.2780 | lr=2.27e-05 | epoch=2.3895
[train] step=1119 | loss=0.3043 | lr=2.26e-05 | epoch=2.3917
[train] step=1120 | loss=0.2856 | lr=2.25e-05 | epoch=2.3938
[train] step=1121 | loss=0.2987 | lr=2.25e-05 | epoch=2.3959
[train] step=1122 | loss=0.2964 | lr=2.24e-05 | epoch=2.3981
[train] step=1123 | loss=0.3316 | lr=2.23e-05 | epoch=2.4002
[train] step=1124 | loss=0.2975 | lr=2.22e-05 | epoch=2.4024
[train] step=1125 | loss=0.2587 | lr=2.22e-05 | epoch=2.4045
[train] step=1126 | loss=0.2632 | lr=2.21e-05 | epoch=2.4066
[train] step=1127 | loss=0.2786 | lr=2.20e-05 | epoch=2.4088
[train] step=1128 | loss=0.2810 | lr=2.19e-05 | epoch=2.4109
[train] step=1129 | loss=0.2741 | lr=2.18e-05 | epoch=2.4131
[train] step=1130 | loss=0.2755 | lr=2.18e-05 | epoch=2.4152
[train] step=1131 | loss=0.3142 | lr=2.17e-05 | epoch=2.4173
[train] step=1132 | loss=0.2549 | lr=2.16e-05 | epoch=2.4195
[train] step=1133 | loss=0.2774 | lr=2.15e-05 | epoch=2.4216
[train] step=1134 | loss=0.2759 | lr=2.14e-05 | epoch=2.4238
[train] step=1135 | loss=0.3303 | lr=2.14e-05 | epoch=2.4259
[train] step=1136 | loss=0.2905 | lr=2.13e-05 | epoch=2.4280
[train] step=1137 | loss=0.2577 | lr=2.12e-05 | epoch=2.4302
[train] step=1138 | loss=0.2981 | lr=2.11e-05 | epoch=2.4323
[train] step=1139 | loss=0.2860 | lr=2.10e-05 | epoch=2.4345
[train] step=1140 | loss=0.3193 | lr=2.10e-05 | epoch=2.4366
[train] step=1141 | loss=0.3283 | lr=2.09e-05 | epoch=2.4387
[train] step=1142 | loss=0.2724 | lr=2.08e-05 | epoch=2.4409
[train] step=1143 | loss=0.2755 | lr=2.07e-05 | epoch=2.4430
[train] step=1144 | loss=0.2835 | lr=2.06e-05 | epoch=2.4452
[train] step=1145 | loss=0.2590 | lr=2.06e-05 | epoch=2.4473
[train] step=1146 | loss=0.2593 | lr=2.05e-05 | epoch=2.4494
[train] step=1147 | loss=0.2922 | lr=2.04e-05 | epoch=2.4516
[train] step=1148 | loss=0.3931 | lr=2.03e-05 | epoch=2.4537
[train] step=1149 | loss=0.2981 | lr=2.03e-05 | epoch=2.4559
[train] step=1150 | loss=0.2792 | lr=2.02e-05 | epoch=2.4580
[train] step=1151 | loss=0.3101 | lr=2.01e-05 | epoch=2.4601
[train] step=1152 | loss=0.2744 | lr=2.00e-05 | epoch=2.4623
[train] step=1153 | loss=0.3128 | lr=1.99e-05 | epoch=2.4644
[train] step=1154 | loss=0.3187 | lr=1.99e-05 | epoch=2.4666
[train] step=1155 | loss=0.2524 | lr=1.98e-05 | epoch=2.4687
[train] step=1156 | loss=0.3096 | lr=1.97e-05 | epoch=2.4708
[train] step=1157 | loss=0.2999 | lr=1.96e-05 | epoch=2.4730
[train] step=1158 | loss=0.2691 | lr=1.95e-05 | epoch=2.4751
[train] step=1159 | loss=0.3054 | lr=1.95e-05 | epoch=2.4773
[train] step=1160 | loss=0.2709 | lr=1.94e-05 | epoch=2.4794
[train] step=1161 | loss=0.3174 | lr=1.93e-05 | epoch=2.4815
[train] step=1162 | loss=0.2791 | lr=1.92e-05 | epoch=2.4837
[train] step=1163 | loss=0.2939 | lr=1.91e-05 | epoch=2.4858
[train] step=1164 | loss=0.2573 | lr=1.91e-05 | epoch=2.4880
[train] step=1165 | loss=0.2647 | lr=1.90e-05 | epoch=2.4901

Saving model checkpoint to output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1165
2026-04-04 12:50:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:50:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:50:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:50:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1165/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1165/tokenizer_config.json

[train] step=1166 | loss=0.2984 | lr=1.89e-05 | epoch=2.4922
[train] step=1167 | loss=0.2740 | lr=1.88e-05 | epoch=2.4944
[train] step=1168 | loss=0.2742 | lr=1.88e-05 | epoch=2.4965
[train] step=1169 | loss=0.3640 | lr=1.87e-05 | epoch=2.4987
[train] step=1170 | loss=0.2612 | lr=1.86e-05 | epoch=2.5008
[train] step=1171 | loss=0.2747 | lr=1.85e-05 | epoch=2.5029
[train] step=1172 | loss=0.2935 | lr=1.84e-05 | epoch=2.5051
[train] step=1173 | loss=0.2419 | lr=1.84e-05 | epoch=2.5072
[train] step=1174 | loss=0.2693 | lr=1.83e-05 | epoch=2.5094
[train] step=1175 | loss=0.2550 | lr=1.82e-05 | epoch=2.5115
[train] step=1176 | loss=0.3102 | lr=1.81e-05 | epoch=2.5136
[train] step=1177 | loss=0.3215 | lr=1.80e-05 | epoch=2.5158
[train] step=1178 | loss=0.2718 | lr=1.80e-05 | epoch=2.5179
[train] step=1179 | loss=0.2792 | lr=1.79e-05 | epoch=2.5201
[train] step=1180 | loss=0.2885 | lr=1.78e-05 | epoch=2.5222
[train] step=1181 | loss=0.3449 | lr=1.77e-05 | epoch=2.5243
[train] step=1182 | loss=0.2580 | lr=1.76e-05 | epoch=2.5265
[train] step=1183 | loss=0.3348 | lr=1.76e-05 | epoch=2.5286
[train] step=1184 | loss=0.2979 | lr=1.75e-05 | epoch=2.5308
[train] step=1185 | loss=0.3070 | lr=1.74e-05 | epoch=2.5329
[train] step=1186 | loss=0.2881 | lr=1.73e-05 | epoch=2.5350
[train] step=1187 | loss=0.2969 | lr=1.72e-05 | epoch=2.5372
[train] step=1188 | loss=0.2738 | lr=1.72e-05 | epoch=2.5393
[train] step=1189 | loss=0.2843 | lr=1.71e-05 | epoch=2.5415
[train] step=1190 | loss=0.2916 | lr=1.70e-05 | epoch=2.5436
[train] step=1191 | loss=0.3505 | lr=1.69e-05 | epoch=2.5457
[train] step=1192 | loss=0.2548 | lr=1.69e-05 | epoch=2.5479
[train] step=1193 | loss=0.2294 | lr=1.68e-05 | epoch=2.5500
[train] step=1194 | loss=0.2942 | lr=1.67e-05 | epoch=2.5522
[train] step=1195 | loss=0.3037 | lr=1.66e-05 | epoch=2.5543
[train] step=1196 | loss=0.2454 | lr=1.65e-05 | epoch=2.5564
[train] step=1197 | loss=0.2990 | lr=1.65e-05 | epoch=2.5586
[train] step=1198 | loss=0.2883 | lr=1.64e-05 | epoch=2.5607
[train] step=1199 | loss=0.2574 | lr=1.63e-05 | epoch=2.5629
[train] step=1200 | loss=0.2825 | lr=1.62e-05 | epoch=2.5650
[train] step=1201 | loss=0.2850 | lr=1.61e-05 | epoch=2.5671
[train] step=1202 | loss=0.3489 | lr=1.61e-05 | epoch=2.5693
[train] step=1203 | loss=0.2994 | lr=1.60e-05 | epoch=2.5714
[train] step=1204 | loss=0.3045 | lr=1.59e-05 | epoch=2.5736
[train] step=1205 | loss=0.2839 | lr=1.58e-05 | epoch=2.5757
[train] step=1206 | loss=0.2616 | lr=1.57e-05 | epoch=2.5778
[train] step=1207 | loss=0.2969 | lr=1.57e-05 | epoch=2.5800
[train] step=1208 | loss=0.2621 | lr=1.56e-05 | epoch=2.5821
[train] step=1209 | loss=0.3110 | lr=1.55e-05 | epoch=2.5843
[train] step=1210 | loss=0.2805 | lr=1.54e-05 | epoch=2.5864
[train] step=1211 | loss=0.3266 | lr=1.53e-05 | epoch=2.5886
[train] step=1212 | loss=0.3260 | lr=1.53e-05 | epoch=2.5907
[train] step=1213 | loss=0.2688 | lr=1.52e-05 | epoch=2.5928
[train] step=1214 | loss=0.2526 | lr=1.51e-05 | epoch=2.5950
[train] step=1215 | loss=0.2848 | lr=1.50e-05 | epoch=2.5971
[train] step=1216 | loss=0.3452 | lr=1.50e-05 | epoch=2.5993
[train] step=1217 | loss=0.2955 | lr=1.49e-05 | epoch=2.6014
[train] step=1218 | loss=0.2778 | lr=1.48e-05 | epoch=2.6035
[train] step=1219 | loss=0.2869 | lr=1.47e-05 | epoch=2.6057
[train] step=1220 | loss=0.2531 | lr=1.46e-05 | epoch=2.6078
[train] step=1221 | loss=0.3247 | lr=1.46e-05 | epoch=2.6100
[train] step=1222 | loss=0.3119 | lr=1.45e-05 | epoch=2.6121
[train] step=1223 | loss=0.2994 | lr=1.44e-05 | epoch=2.6142
[train] step=1224 | loss=0.2364 | lr=1.43e-05 | epoch=2.6164
[train] step=1225 | loss=0.2620 | lr=1.42e-05 | epoch=2.6185
[train] step=1226 | loss=0.2609 | lr=1.42e-05 | epoch=2.6207
[train] step=1227 | loss=0.2760 | lr=1.41e-05 | epoch=2.6228
[train] step=1228 | loss=0.2992 | lr=1.40e-05 | epoch=2.6249
[train] step=1229 | loss=0.2816 | lr=1.39e-05 | epoch=2.6271
[train] step=1230 | loss=0.2819 | lr=1.38e-05 | epoch=2.6292
[train] step=1231 | loss=0.2232 | lr=1.38e-05 | epoch=2.6314
[train] step=1232 | loss=0.2987 | lr=1.37e-05 | epoch=2.6335
[train] step=1233 | loss=0.3222 | lr=1.36e-05 | epoch=2.6356
[train] step=1234 | loss=0.3132 | lr=1.35e-05 | epoch=2.6378
[train] step=1235 | loss=0.3043 | lr=1.34e-05 | epoch=2.6399
[train] step=1236 | loss=0.2744 | lr=1.34e-05 | epoch=2.6421
[train] step=1237 | loss=0.2790 | lr=1.33e-05 | epoch=2.6442
[train] step=1238 | loss=0.2753 | lr=1.32e-05 | epoch=2.6463
[train] step=1239 | loss=0.3156 | lr=1.31e-05 | epoch=2.6485
[train] step=1240 | loss=0.2766 | lr=1.31e-05 | epoch=2.6506
[train] step=1241 | loss=0.2802 | lr=1.30e-05 | epoch=2.6528
[train] step=1242 | loss=0.3741 | lr=1.29e-05 | epoch=2.6549
[train] step=1243 | loss=0.2627 | lr=1.28e-05 | epoch=2.6570
[train] step=1244 | loss=0.2846 | lr=1.27e-05 | epoch=2.6592
[train] step=1245 | loss=0.2986 | lr=1.27e-05 | epoch=2.6613
[train] step=1246 | loss=0.2429 | lr=1.26e-05 | epoch=2.6635
[train] step=1247 | loss=0.2903 | lr=1.25e-05 | epoch=2.6656
[train] step=1248 | loss=0.2734 | lr=1.24e-05 | epoch=2.6677
[train] step=1249 | loss=0.2550 | lr=1.23e-05 | epoch=2.6699
[train] step=1250 | loss=0.2267 | lr=1.23e-05 | epoch=2.6720
[train] step=1251 | loss=0.3260 | lr=1.22e-05 | epoch=2.6742
[train] step=1252 | loss=0.2651 | lr=1.21e-05 | epoch=2.6763
[train] step=1253 | loss=0.2937 | lr=1.20e-05 | epoch=2.6784
[train] step=1254 | loss=0.2880 | lr=1.19e-05 | epoch=2.6806
[train] step=1255 | loss=0.2579 | lr=1.19e-05 | epoch=2.6827
[train] step=1256 | loss=0.2568 | lr=1.18e-05 | epoch=2.6849
[train] step=1257 | loss=0.2613 | lr=1.17e-05 | epoch=2.6870
[train] step=1258 | loss=0.2966 | lr=1.16e-05 | epoch=2.6891
[train] step=1259 | loss=0.3124 | lr=1.16e-05 | epoch=2.6913
[train] step=1260 | loss=0.2808 | lr=1.15e-05 | epoch=2.6934
[train] step=1261 | loss=0.2692 | lr=1.14e-05 | epoch=2.6956
[train] step=1262 | loss=0.3517 | lr=1.13e-05 | epoch=2.6977
[train] step=1263 | loss=0.2507 | lr=1.12e-05 | epoch=2.6998
[train] step=1264 | loss=0.2671 | lr=1.12e-05 | epoch=2.7020
[train] step=1265 | loss=0.3363 | lr=1.11e-05 | epoch=2.7041
[train] step=1266 | loss=0.3273 | lr=1.10e-05 | epoch=2.7063
[train] step=1267 | loss=0.2950 | lr=1.09e-05 | epoch=2.7084
[train] step=1268 | loss=0.3279 | lr=1.08e-05 | epoch=2.7105
[train] step=1269 | loss=0.3205 | lr=1.08e-05 | epoch=2.7127
[train] step=1270 | loss=0.2469 | lr=1.07e-05 | epoch=2.7148
[train] step=1271 | loss=0.2587 | lr=1.06e-05 | epoch=2.7170
[train] step=1272 | loss=0.2836 | lr=1.05e-05 | epoch=2.7191
[train] step=1273 | loss=0.2956 | lr=1.04e-05 | epoch=2.7212
[train] step=1274 | loss=0.2710 | lr=1.04e-05 | epoch=2.7234
[train] step=1275 | loss=0.2982 | lr=1.03e-05 | epoch=2.7255
[train] step=1276 | loss=0.2373 | lr=1.02e-05 | epoch=2.7277
[train] step=1277 | loss=0.2904 | lr=1.01e-05 | epoch=2.7298
[train] step=1278 | loss=0.2790 | lr=1.00e-05 | epoch=2.7319
[train] step=1279 | loss=0.3250 | lr=9.97e-06 | epoch=2.7341
[train] step=1280 | loss=0.2970 | lr=9.89e-06 | epoch=2.7362
[train] step=1281 | loss=0.2641 | lr=9.81e-06 | epoch=2.7384
[train] step=1282 | loss=0.3088 | lr=9.73e-06 | epoch=2.7405
[train] step=1283 | loss=0.2842 | lr=9.65e-06 | epoch=2.7426
[train] step=1284 | loss=0.3221 | lr=9.57e-06 | epoch=2.7448
[train] step=1285 | loss=0.2696 | lr=9.49e-06 | epoch=2.7469
[train] step=1286 | loss=0.2670 | lr=9.41e-06 | epoch=2.7491
[train] step=1287 | loss=0.2662 | lr=9.34e-06 | epoch=2.7512
[train] step=1288 | loss=0.2916 | lr=9.26e-06 | epoch=2.7533
[train] step=1289 | loss=0.2683 | lr=9.18e-06 | epoch=2.7555
[train] step=1290 | loss=0.3269 | lr=9.10e-06 | epoch=2.7576
[train] step=1291 | loss=0.2308 | lr=9.02e-06 | epoch=2.7598
[train] step=1292 | loss=0.2989 | lr=8.94e-06 | epoch=2.7619
[train] step=1293 | loss=0.2595 | lr=8.86e-06 | epoch=2.7640
[train] step=1294 | loss=0.3073 | lr=8.78e-06 | epoch=2.7662
[train] step=1295 | loss=0.2780 | lr=8.70e-06 | epoch=2.7683
[train] step=1296 | loss=0.3183 | lr=8.62e-06 | epoch=2.7705
[train] step=1297 | loss=0.2902 | lr=8.54e-06 | epoch=2.7726
[train] step=1298 | loss=0.2447 | lr=8.47e-06 | epoch=2.7747
[train] step=1299 | loss=0.2845 | lr=8.39e-06 | epoch=2.7769
[train] step=1300 | loss=0.2667 | lr=8.31e-06 | epoch=2.7790
[train] step=1301 | loss=0.2828 | lr=8.23e-06 | epoch=2.7812
[train] step=1302 | loss=0.2839 | lr=8.15e-06 | epoch=2.7833
[train] step=1303 | loss=0.3432 | lr=8.07e-06 | epoch=2.7854
[train] step=1304 | loss=0.2611 | lr=7.99e-06 | epoch=2.7876
[train] step=1305 | loss=0.3271 | lr=7.91e-06 | epoch=2.7897
[train] step=1306 | loss=0.3278 | lr=7.83e-06 | epoch=2.7919
[train] step=1307 | loss=0.2571 | lr=7.75e-06 | epoch=2.7940
[train] step=1308 | loss=0.2543 | lr=7.67e-06 | epoch=2.7961
[train] step=1309 | loss=0.2895 | lr=7.59e-06 | epoch=2.7983
[train] step=1310 | loss=0.2601 | lr=7.52e-06 | epoch=2.8004
[train] step=1311 | loss=0.3202 | lr=7.44e-06 | epoch=2.8026
[train] step=1312 | loss=0.2701 | lr=7.36e-06 | epoch=2.8047
[train] step=1313 | loss=0.2920 | lr=7.28e-06 | epoch=2.8068
[train] step=1314 | loss=0.2756 | lr=7.20e-06 | epoch=2.8090
[train] step=1315 | loss=0.2804 | lr=7.12e-06 | epoch=2.8111
[train] step=1316 | loss=0.3093 | lr=7.04e-06 | epoch=2.8133
[train] step=1317 | loss=0.3044 | lr=6.96e-06 | epoch=2.8154
[train] step=1318 | loss=0.2685 | lr=6.88e-06 | epoch=2.8175
[train] step=1319 | loss=0.2465 | lr=6.80e-06 | epoch=2.8197
[train] step=1320 | loss=0.2664 | lr=6.72e-06 | epoch=2.8218
[train] step=1321 | loss=0.2736 | lr=6.65e-06 | epoch=2.8240
[train] step=1322 | loss=0.2498 | lr=6.57e-06 | epoch=2.8261
[train] step=1323 | loss=0.2431 | lr=6.49e-06 | epoch=2.8283
[train] step=1324 | loss=0.3121 | lr=6.41e-06 | epoch=2.8304
[train] step=1325 | loss=0.2753 | lr=6.33e-06 | epoch=2.8325
[train] step=1326 | loss=0.2695 | lr=6.25e-06 | epoch=2.8347
[train] step=1327 | loss=0.3063 | lr=6.17e-06 | epoch=2.8368
[train] step=1328 | loss=0.3137 | lr=6.09e-06 | epoch=2.8390
[train] step=1329 | loss=0.3064 | lr=6.01e-06 | epoch=2.8411
[train] step=1330 | loss=0.3004 | lr=5.93e-06 | epoch=2.8432
[train] step=1331 | loss=0.2437 | lr=5.85e-06 | epoch=2.8454
[train] step=1332 | loss=0.3869 | lr=5.78e-06 | epoch=2.8475
[train] step=1333 | loss=0.3026 | lr=5.70e-06 | epoch=2.8497
[train] step=1334 | loss=0.2723 | lr=5.62e-06 | epoch=2.8518
[train] step=1335 | loss=0.3464 | lr=5.54e-06 | epoch=2.8539
[train] step=1336 | loss=0.2535 | lr=5.46e-06 | epoch=2.8561
[train] step=1337 | loss=0.3071 | lr=5.38e-06 | epoch=2.8582
[train] step=1338 | loss=0.3201 | lr=5.30e-06 | epoch=2.8604
[train] step=1339 | loss=0.3480 | lr=5.22e-06 | epoch=2.8625
[train] step=1340 | loss=0.3412 | lr=5.14e-06 | epoch=2.8646
[train] step=1341 | loss=0.2461 | lr=5.06e-06 | epoch=2.8668
[train] step=1342 | loss=0.2796 | lr=4.98e-06 | epoch=2.8689
[train] step=1343 | loss=0.2994 | lr=4.91e-06 | epoch=2.8711
[train] step=1344 | loss=0.2321 | lr=4.83e-06 | epoch=2.8732
[train] step=1345 | loss=0.2698 | lr=4.75e-06 | epoch=2.8753
[train] step=1346 | loss=0.3213 | lr=4.67e-06 | epoch=2.8775
[train] step=1347 | loss=0.3124 | lr=4.59e-06 | epoch=2.8796
[train] step=1348 | loss=0.3259 | lr=4.51e-06 | epoch=2.8818
[train] step=1349 | loss=0.2386 | lr=4.43e-06 | epoch=2.8839
[train] step=1350 | loss=0.3260 | lr=4.35e-06 | epoch=2.8860
[train] step=1351 | loss=0.3033 | lr=4.27e-06 | epoch=2.8882
[train] step=1352 | loss=0.2952 | lr=4.19e-06 | epoch=2.8903
[train] step=1353 | loss=0.2982 | lr=4.11e-06 | epoch=2.8925
[train] step=1354 | loss=0.2609 | lr=4.03e-06 | epoch=2.8946
[train] step=1355 | loss=0.2988 | lr=3.96e-06 | epoch=2.8967
[train] step=1356 | loss=0.2357 | lr=3.88e-06 | epoch=2.8989
[train] step=1357 | loss=0.3152 | lr=3.80e-06 | epoch=2.9010
[train] step=1358 | loss=0.2622 | lr=3.72e-06 | epoch=2.9032
[train] step=1359 | loss=0.2833 | lr=3.64e-06 | epoch=2.9053
[train] step=1360 | loss=0.2777 | lr=3.56e-06 | epoch=2.9074
[train] step=1361 | loss=0.2726 | lr=3.48e-06 | epoch=2.9096
[train] step=1362 | loss=0.3454 | lr=3.40e-06 | epoch=2.9117
[train] step=1363 | loss=0.2533 | lr=3.32e-06 | epoch=2.9139
[train] step=1364 | loss=0.2791 | lr=3.24e-06 | epoch=2.9160
[train] step=1365 | loss=0.3249 | lr=3.16e-06 | epoch=2.9181
[train] step=1366 | loss=0.3182 | lr=3.09e-06 | epoch=2.9203
[train] step=1367 | loss=0.3256 | lr=3.01e-06 | epoch=2.9224
[train] step=1368 | loss=0.2093 | lr=2.93e-06 | epoch=2.9246
[train] step=1369 | loss=0.2544 | lr=2.85e-06 | epoch=2.9267
[train] step=1370 | loss=0.2565 | lr=2.77e-06 | epoch=2.9288
[train] step=1371 | loss=0.2146 | lr=2.69e-06 | epoch=2.9310
[train] step=1372 | loss=0.2901 | lr=2.61e-06 | epoch=2.9331
[train] step=1373 | loss=0.2945 | lr=2.53e-06 | epoch=2.9353
[train] step=1374 | loss=0.2868 | lr=2.45e-06 | epoch=2.9374
[train] step=1375 | loss=0.3174 | lr=2.37e-06 | epoch=2.9395
[train] step=1376 | loss=0.2563 | lr=2.29e-06 | epoch=2.9417
[train] step=1377 | loss=0.2881 | lr=2.22e-06 | epoch=2.9438
[train] step=1378 | loss=0.3035 | lr=2.14e-06 | epoch=2.9460
[train] step=1379 | loss=0.2643 | lr=2.06e-06 | epoch=2.9481
[train] step=1380 | loss=0.3050 | lr=1.98e-06 | epoch=2.9502
[train] step=1381 | loss=0.2974 | lr=1.90e-06 | epoch=2.9524
[train] step=1382 | loss=0.2486 | lr=1.82e-06 | epoch=2.9545
[train] step=1383 | loss=0.2391 | lr=1.74e-06 | epoch=2.9567
[train] step=1384 | loss=0.2519 | lr=1.66e-06 | epoch=2.9588
[train] step=1385 | loss=0.2721 | lr=1.58e-06 | epoch=2.9609
[train] step=1386 | loss=0.2787 | lr=1.50e-06 | epoch=2.9631
[train] step=1387 | loss=0.2974 | lr=1.42e-06 | epoch=2.9652
[train] step=1388 | loss=0.3093 | lr=1.34e-06 | epoch=2.9674
[train] step=1389 | loss=0.3141 | lr=1.27e-06 | epoch=2.9695
[train] step=1390 | loss=0.2866 | lr=1.19e-06 | epoch=2.9716
[train] step=1391 | loss=0.2887 | lr=1.11e-06 | epoch=2.9738
[train] step=1392 | loss=0.2574 | lr=1.03e-06 | epoch=2.9759
[train] step=1393 | loss=0.2375 | lr=9.49e-07 | epoch=2.9781
[train] step=1394 | loss=0.2523 | lr=8.70e-07 | epoch=2.9802
[train] step=1395 | loss=0.2344 | lr=7.91e-07 | epoch=2.9823
[train] step=1396 | loss=0.2537 | lr=7.12e-07 | epoch=2.9845
[train] step=1397 | loss=0.2908 | lr=6.33e-07 | epoch=2.9866
[train] step=1398 | loss=0.2765 | lr=5.54e-07 | epoch=2.9888

Saving model checkpoint to output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1398
2026-04-04 12:54:23 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:23 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:54:23 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:23 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1398/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1398/tokenizer_config.json

[train] step=1399 | loss=0.2634 | lr=4.75e-07 | epoch=2.9909
[train] step=1400 | loss=0.3103 | lr=3.96e-07 | epoch=2.9930
[train] step=1401 | loss=0.2477 | lr=3.16e-07 | epoch=2.9952
[train] step=1402 | loss=0.2713 | lr=2.37e-07 | epoch=2.9973
[train] step=1403 | loss=0.3422 | lr=1.58e-07 | epoch=2.9995
[train] step=1404 | loss=0.2358 | lr=7.91e-08 | epoch=3.0000

Saving model checkpoint to output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1404
2026-04-04 12:54:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:54:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1404/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/checkpoint-1404/tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=1404 | epoch=3.0000
[train] finished | global_step=1404

Saving model checkpoint to output/fine_tune/run_016_lr1e-4_r16_a32_ep3
2026-04-04 12:54:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:29 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:54:30 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:30 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/tokenizer_config.json
chat template saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_016_lr1e-4_r16_a32_ep3/tokenizer_config.json
2026-04-04 12:54:30 | INFO     | root | Done run 17/18: /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_016_lr1e-4_r16_a32_ep3

=== Run 18/18  run_017_lr1e-4_r32_a64_ep3  merged={'learning_rate': 0.0001, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-04 12:54:30 | INFO     | root | Logging to /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_017_lr1e-4_r32_a64_ep3/training_run.log
2026-04-04 12:54:30 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:30 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-04 12:54:30 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:30 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-04 12:54:31 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-04 12:54:31 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-04 12:54:32 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct "HTTP/1.1 200 OK"
2026-04-04 12:54:32 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:32 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-04 12:54:32 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:32 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 6933.60it/s]
2026-04-04 12:54:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.1,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2026-04-04 12:54:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-0.5B-Instruct.
2026-04-04 12:54:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:54:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-04 12:54:33 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-04 12:54:34 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-04 12:54:34 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-04 12:54:35 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-04 12:54:35 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-04 12:54:37 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 4,325,376

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.4261 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.5759 | lr=7.14e-07 | epoch=0.0043
[train] step=3 | loss=1.5502 | lr=1.43e-06 | epoch=0.0064
[train] step=4 | loss=1.5152 | lr=2.14e-06 | epoch=0.0086
[train] step=5 | loss=1.4351 | lr=2.86e-06 | epoch=0.0107
[train] step=6 | loss=1.4276 | lr=3.57e-06 | epoch=0.0128
[train] step=7 | loss=1.4182 | lr=4.29e-06 | epoch=0.0150
[train] step=8 | loss=1.3456 | lr=5.00e-06 | epoch=0.0171
[train] step=9 | loss=1.4565 | lr=5.71e-06 | epoch=0.0193
[train] step=10 | loss=1.4827 | lr=6.43e-06 | epoch=0.0214
[train] step=11 | loss=1.4403 | lr=7.14e-06 | epoch=0.0235
[train] step=12 | loss=1.6020 | lr=7.86e-06 | epoch=0.0257
[train] step=13 | loss=1.3704 | lr=8.57e-06 | epoch=0.0278
[train] step=14 | loss=1.4240 | lr=9.29e-06 | epoch=0.0300
[train] step=15 | loss=1.4677 | lr=1.00e-05 | epoch=0.0321
[train] step=16 | loss=1.3635 | lr=1.07e-05 | epoch=0.0342
[train] step=17 | loss=1.3481 | lr=1.14e-05 | epoch=0.0364
[train] step=18 | loss=1.2356 | lr=1.21e-05 | epoch=0.0385
[train] step=19 | loss=1.2112 | lr=1.29e-05 | epoch=0.0407
[train] step=20 | loss=1.2862 | lr=1.36e-05 | epoch=0.0428
[train] step=21 | loss=1.1133 | lr=1.43e-05 | epoch=0.0449
[train] step=22 | loss=1.1281 | lr=1.50e-05 | epoch=0.0471
[train] step=23 | loss=1.1035 | lr=1.57e-05 | epoch=0.0492
[train] step=24 | loss=1.1021 | lr=1.64e-05 | epoch=0.0514
[train] step=25 | loss=0.9644 | lr=1.71e-05 | epoch=0.0535
[train] step=26 | loss=1.1160 | lr=1.79e-05 | epoch=0.0556
[train] step=27 | loss=0.9299 | lr=1.86e-05 | epoch=0.0578
[train] step=28 | loss=0.9440 | lr=1.93e-05 | epoch=0.0599
[train] step=29 | loss=0.9031 | lr=2.00e-05 | epoch=0.0621
[train] step=30 | loss=0.9531 | lr=2.07e-05 | epoch=0.0642
[train] step=31 | loss=0.7733 | lr=2.14e-05 | epoch=0.0663
[train] step=32 | loss=0.8650 | lr=2.21e-05 | epoch=0.0685
[train] step=33 | loss=0.8537 | lr=2.29e-05 | epoch=0.0706
[train] step=34 | loss=0.7297 | lr=2.36e-05 | epoch=0.0728
[train] step=35 | loss=0.7818 | lr=2.43e-05 | epoch=0.0749
[train] step=36 | loss=0.7321 | lr=2.50e-05 | epoch=0.0770
[train] step=37 | loss=0.6750 | lr=2.57e-05 | epoch=0.0792
[train] step=38 | loss=0.6808 | lr=2.64e-05 | epoch=0.0813
[train] step=39 | loss=0.6164 | lr=2.71e-05 | epoch=0.0835
[train] step=40 | loss=0.6470 | lr=2.79e-05 | epoch=0.0856
[train] step=41 | loss=0.6945 | lr=2.86e-05 | epoch=0.0877
[train] step=42 | loss=0.6096 | lr=2.93e-05 | epoch=0.0899
[train] step=43 | loss=0.5861 | lr=3.00e-05 | epoch=0.0920
[train] step=44 | loss=0.5677 | lr=3.07e-05 | epoch=0.0942
[train] step=45 | loss=0.6077 | lr=3.14e-05 | epoch=0.0963
[train] step=46 | loss=0.5103 | lr=3.21e-05 | epoch=0.0984
[train] step=47 | loss=0.5416 | lr=3.29e-05 | epoch=0.1006
[train] step=48 | loss=0.5052 | lr=3.36e-05 | epoch=0.1027
[train] step=49 | loss=0.4872 | lr=3.43e-05 | epoch=0.1049
[train] step=50 | loss=0.4875 | lr=3.50e-05 | epoch=0.1070
[train] step=51 | loss=0.5010 | lr=3.57e-05 | epoch=0.1091
[train] step=52 | loss=0.4542 | lr=3.64e-05 | epoch=0.1113
[train] step=53 | loss=0.4937 | lr=3.71e-05 | epoch=0.1134
[train] step=54 | loss=0.5133 | lr=3.79e-05 | epoch=0.1156
[train] step=55 | loss=0.4742 | lr=3.86e-05 | epoch=0.1177
[train] step=56 | loss=0.4465 | lr=3.93e-05 | epoch=0.1199
[train] step=57 | loss=0.4285 | lr=4.00e-05 | epoch=0.1220
[train] step=58 | loss=0.4447 | lr=4.07e-05 | epoch=0.1241
[train] step=59 | loss=0.4520 | lr=4.14e-05 | epoch=0.1263
[train] step=60 | loss=0.3959 | lr=4.21e-05 | epoch=0.1284
[train] step=61 | loss=0.3473 | lr=4.29e-05 | epoch=0.1306
[train] step=62 | loss=0.3511 | lr=4.36e-05 | epoch=0.1327
[train] step=63 | loss=0.4047 | lr=4.43e-05 | epoch=0.1348
[train] step=64 | loss=0.3281 | lr=4.50e-05 | epoch=0.1370
[train] step=65 | loss=0.3458 | lr=4.57e-05 | epoch=0.1391
[train] step=66 | loss=0.3983 | lr=4.64e-05 | epoch=0.1413
[train] step=67 | loss=0.3452 | lr=4.71e-05 | epoch=0.1434
[train] step=68 | loss=0.3943 | lr=4.79e-05 | epoch=0.1455
[train] step=69 | loss=0.4291 | lr=4.86e-05 | epoch=0.1477
[train] step=70 | loss=0.3950 | lr=4.93e-05 | epoch=0.1498
[train] step=71 | loss=0.3633 | lr=5.00e-05 | epoch=0.1520
[train] step=72 | loss=0.3842 | lr=5.07e-05 | epoch=0.1541
[train] step=73 | loss=0.3983 | lr=5.14e-05 | epoch=0.1562
[train] step=74 | loss=0.3992 | lr=5.21e-05 | epoch=0.1584
[train] step=75 | loss=0.4053 | lr=5.29e-05 | epoch=0.1605
[train] step=76 | loss=0.3518 | lr=5.36e-05 | epoch=0.1627
[train] step=77 | loss=0.3630 | lr=5.43e-05 | epoch=0.1648
[train] step=78 | loss=0.3439 | lr=5.50e-05 | epoch=0.1669
[train] step=79 | loss=0.3428 | lr=5.57e-05 | epoch=0.1691
[train] step=80 | loss=0.4490 | lr=5.64e-05 | epoch=0.1712
[train] step=81 | loss=0.4092 | lr=5.71e-05 | epoch=0.1734
[train] step=82 | loss=0.3689 | lr=5.79e-05 | epoch=0.1755
[train] step=83 | loss=0.3668 | lr=5.86e-05 | epoch=0.1776
[train] step=84 | loss=0.3958 | lr=5.93e-05 | epoch=0.1798
[train] step=85 | loss=0.4038 | lr=6.00e-05 | epoch=0.1819
[train] step=86 | loss=0.4123 | lr=6.07e-05 | epoch=0.1841
[train] step=87 | loss=0.3174 | lr=6.14e-05 | epoch=0.1862
[train] step=88 | loss=0.4064 | lr=6.21e-05 | epoch=0.1883
[train] step=89 | loss=0.3602 | lr=6.29e-05 | epoch=0.1905
[train] step=90 | loss=0.3061 | lr=6.36e-05 | epoch=0.1926
[train] step=91 | loss=0.3569 | lr=6.43e-05 | epoch=0.1948
[train] step=92 | loss=0.4023 | lr=6.50e-05 | epoch=0.1969
[train] step=93 | loss=0.3635 | lr=6.57e-05 | epoch=0.1990
[train] step=94 | loss=0.3381 | lr=6.64e-05 | epoch=0.2012
[train] step=95 | loss=0.3610 | lr=6.71e-05 | epoch=0.2033
[train] step=96 | loss=0.3085 | lr=6.79e-05 | epoch=0.2055
[train] step=97 | loss=0.3584 | lr=6.86e-05 | epoch=0.2076
[train] step=98 | loss=0.3684 | lr=6.93e-05 | epoch=0.2097
[train] step=99 | loss=0.3016 | lr=7.00e-05 | epoch=0.2119
[train] step=100 | loss=0.3414 | lr=7.07e-05 | epoch=0.2140
[train] step=101 | loss=0.3159 | lr=7.14e-05 | epoch=0.2162
[train] step=102 | loss=0.4073 | lr=7.21e-05 | epoch=0.2183
[train] step=103 | loss=0.3506 | lr=7.29e-05 | epoch=0.2204
[train] step=104 | loss=0.3418 | lr=7.36e-05 | epoch=0.2226
[train] step=105 | loss=0.3927 | lr=7.43e-05 | epoch=0.2247
[train] step=106 | loss=0.3584 | lr=7.50e-05 | epoch=0.2269
[train] step=107 | loss=0.3645 | lr=7.57e-05 | epoch=0.2290
[train] step=108 | loss=0.3056 | lr=7.64e-05 | epoch=0.2311
[train] step=109 | loss=0.3024 | lr=7.71e-05 | epoch=0.2333
[train] step=110 | loss=0.3798 | lr=7.79e-05 | epoch=0.2354
[train] step=111 | loss=0.3355 | lr=7.86e-05 | epoch=0.2376
[train] step=112 | loss=0.3261 | lr=7.93e-05 | epoch=0.2397
[train] step=113 | loss=0.3447 | lr=8.00e-05 | epoch=0.2418
[train] step=114 | loss=0.3645 | lr=8.07e-05 | epoch=0.2440
[train] step=115 | loss=0.3763 | lr=8.14e-05 | epoch=0.2461
[train] step=116 | loss=0.3673 | lr=8.21e-05 | epoch=0.2483
[train] step=117 | loss=0.3576 | lr=8.29e-05 | epoch=0.2504
[train] step=118 | loss=0.3422 | lr=8.36e-05 | epoch=0.2525
[train] step=119 | loss=0.3792 | lr=8.43e-05 | epoch=0.2547
[train] step=120 | loss=0.3124 | lr=8.50e-05 | epoch=0.2568
[train] step=121 | loss=0.3201 | lr=8.57e-05 | epoch=0.2590
[train] step=122 | loss=0.3681 | lr=8.64e-05 | epoch=0.2611
[train] step=123 | loss=0.3539 | lr=8.71e-05 | epoch=0.2632
[train] step=124 | loss=0.3251 | lr=8.79e-05 | epoch=0.2654
[train] step=125 | loss=0.3470 | lr=8.86e-05 | epoch=0.2675
[train] step=126 | loss=0.3456 | lr=8.93e-05 | epoch=0.2697
[train] step=127 | loss=0.3344 | lr=9.00e-05 | epoch=0.2718
[train] step=128 | loss=0.3021 | lr=9.07e-05 | epoch=0.2739
[train] step=129 | loss=0.3092 | lr=9.14e-05 | epoch=0.2761
[train] step=130 | loss=0.3672 | lr=9.21e-05 | epoch=0.2782
[train] step=131 | loss=0.3878 | lr=9.29e-05 | epoch=0.2804
[train] step=132 | loss=0.3636 | lr=9.36e-05 | epoch=0.2825
[train] step=133 | loss=0.3572 | lr=9.43e-05 | epoch=0.2846
[train] step=134 | loss=0.3145 | lr=9.50e-05 | epoch=0.2868
[train] step=135 | loss=0.3632 | lr=9.57e-05 | epoch=0.2889
[train] step=136 | loss=0.3110 | lr=9.64e-05 | epoch=0.2911
[train] step=137 | loss=0.3744 | lr=9.71e-05 | epoch=0.2932
[train] step=138 | loss=0.2962 | lr=9.79e-05 | epoch=0.2953
[train] step=139 | loss=0.2958 | lr=9.86e-05 | epoch=0.2975
[train] step=140 | loss=0.3094 | lr=9.93e-05 | epoch=0.2996
[train] step=141 | loss=0.4682 | lr=1.00e-04 | epoch=0.3018
[train] step=142 | loss=0.3446 | lr=9.99e-05 | epoch=0.3039
[train] step=143 | loss=0.3338 | lr=9.98e-05 | epoch=0.3060
[train] step=144 | loss=0.3339 | lr=9.98e-05 | epoch=0.3082
[train] step=145 | loss=0.3357 | lr=9.97e-05 | epoch=0.3103
[train] step=146 | loss=0.3158 | lr=9.96e-05 | epoch=0.3125
[train] step=147 | loss=0.3351 | lr=9.95e-05 | epoch=0.3146
[train] step=148 | loss=0.2919 | lr=9.94e-05 | epoch=0.3167
[train] step=149 | loss=0.3389 | lr=9.94e-05 | epoch=0.3189
[train] step=150 | loss=0.2932 | lr=9.93e-05 | epoch=0.3210
[train] step=151 | loss=0.3641 | lr=9.92e-05 | epoch=0.3232
[train] step=152 | loss=0.3169 | lr=9.91e-05 | epoch=0.3253
[train] step=153 | loss=0.2933 | lr=9.91e-05 | epoch=0.3274
[train] step=154 | loss=0.3090 | lr=9.90e-05 | epoch=0.3296
[train] step=155 | loss=0.2870 | lr=9.89e-05 | epoch=0.3317
[train] step=156 | loss=0.3623 | lr=9.88e-05 | epoch=0.3339
[train] step=157 | loss=0.4080 | lr=9.87e-05 | epoch=0.3360
[train] step=158 | loss=0.3172 | lr=9.87e-05 | epoch=0.3381
[train] step=159 | loss=0.3252 | lr=9.86e-05 | epoch=0.3403
[train] step=160 | loss=0.3583 | lr=9.85e-05 | epoch=0.3424
[train] step=161 | loss=0.3154 | lr=9.84e-05 | epoch=0.3446
[train] step=162 | loss=0.3246 | lr=9.83e-05 | epoch=0.3467
[train] step=163 | loss=0.3584 | lr=9.83e-05 | epoch=0.3488
[train] step=164 | loss=0.3869 | lr=9.82e-05 | epoch=0.3510
[train] step=165 | loss=0.3592 | lr=9.81e-05 | epoch=0.3531
[train] step=166 | loss=0.3663 | lr=9.80e-05 | epoch=0.3553
[train] step=167 | loss=0.3135 | lr=9.79e-05 | epoch=0.3574
[train] step=168 | loss=0.2881 | lr=9.79e-05 | epoch=0.3596
[train] step=169 | loss=0.3260 | lr=9.78e-05 | epoch=0.3617
[train] step=170 | loss=0.3036 | lr=9.77e-05 | epoch=0.3638
[train] step=171 | loss=0.3450 | lr=9.76e-05 | epoch=0.3660
[train] step=172 | loss=0.3289 | lr=9.75e-05 | epoch=0.3681
[train] step=173 | loss=0.3205 | lr=9.75e-05 | epoch=0.3703
[train] step=174 | loss=0.3128 | lr=9.74e-05 | epoch=0.3724
[train] step=175 | loss=0.3133 | lr=9.73e-05 | epoch=0.3745
[train] step=176 | loss=0.4058 | lr=9.72e-05 | epoch=0.3767
[train] step=177 | loss=0.2835 | lr=9.72e-05 | epoch=0.3788
[train] step=178 | loss=0.3089 | lr=9.71e-05 | epoch=0.3810
[train] step=179 | loss=0.3259 | lr=9.70e-05 | epoch=0.3831
[train] step=180 | loss=0.3160 | lr=9.69e-05 | epoch=0.3852
[train] step=181 | loss=0.3447 | lr=9.68e-05 | epoch=0.3874
[train] step=182 | loss=0.2528 | lr=9.68e-05 | epoch=0.3895
[train] step=183 | loss=0.2828 | lr=9.67e-05 | epoch=0.3917
[train] step=184 | loss=0.3815 | lr=9.66e-05 | epoch=0.3938
[train] step=185 | loss=0.3112 | lr=9.65e-05 | epoch=0.3959
[train] step=186 | loss=0.2705 | lr=9.64e-05 | epoch=0.3981
[train] step=187 | loss=0.3031 | lr=9.64e-05 | epoch=0.4002
[train] step=188 | loss=0.3691 | lr=9.63e-05 | epoch=0.4024
[train] step=189 | loss=0.3470 | lr=9.62e-05 | epoch=0.4045
[train] step=190 | loss=0.3553 | lr=9.61e-05 | epoch=0.4066
[train] step=191 | loss=0.3097 | lr=9.60e-05 | epoch=0.4088
[train] step=192 | loss=0.3048 | lr=9.60e-05 | epoch=0.4109
[train] step=193 | loss=0.3352 | lr=9.59e-05 | epoch=0.4131
[train] step=194 | loss=0.3156 | lr=9.58e-05 | epoch=0.4152
[train] step=195 | loss=0.3491 | lr=9.57e-05 | epoch=0.4173
[train] step=196 | loss=0.3234 | lr=9.56e-05 | epoch=0.4195
[train] step=197 | loss=0.2785 | lr=9.56e-05 | epoch=0.4216
[train] step=198 | loss=0.3592 | lr=9.55e-05 | epoch=0.4238
[train] step=199 | loss=0.3441 | lr=9.54e-05 | epoch=0.4259
[train] step=200 | loss=0.3359 | lr=9.53e-05 | epoch=0.4280
[train] step=201 | loss=0.2999 | lr=9.53e-05 | epoch=0.4302
[train] step=202 | loss=0.3837 | lr=9.52e-05 | epoch=0.4323
[train] step=203 | loss=0.2883 | lr=9.51e-05 | epoch=0.4345
[train] step=204 | loss=0.3556 | lr=9.50e-05 | epoch=0.4366
[train] step=205 | loss=0.2845 | lr=9.49e-05 | epoch=0.4387
[train] step=206 | loss=0.3225 | lr=9.49e-05 | epoch=0.4409
[train] step=207 | loss=0.3682 | lr=9.48e-05 | epoch=0.4430
[train] step=208 | loss=0.3002 | lr=9.47e-05 | epoch=0.4452
[train] step=209 | loss=0.3132 | lr=9.46e-05 | epoch=0.4473
[train] step=210 | loss=0.3299 | lr=9.45e-05 | epoch=0.4494
[train] step=211 | loss=0.3229 | lr=9.45e-05 | epoch=0.4516
[train] step=212 | loss=0.3150 | lr=9.44e-05 | epoch=0.4537
[train] step=213 | loss=0.3839 | lr=9.43e-05 | epoch=0.4559
[train] step=214 | loss=0.3493 | lr=9.42e-05 | epoch=0.4580
[train] step=215 | loss=0.3675 | lr=9.41e-05 | epoch=0.4601
[train] step=216 | loss=0.2998 | lr=9.41e-05 | epoch=0.4623
[train] step=217 | loss=0.3330 | lr=9.40e-05 | epoch=0.4644
[train] step=218 | loss=0.2980 | lr=9.39e-05 | epoch=0.4666
[train] step=219 | loss=0.3140 | lr=9.38e-05 | epoch=0.4687
[train] step=220 | loss=0.2621 | lr=9.38e-05 | epoch=0.4708
[train] step=221 | loss=0.2921 | lr=9.37e-05 | epoch=0.4730
[train] step=222 | loss=0.3218 | lr=9.36e-05 | epoch=0.4751
[train] step=223 | loss=0.3521 | lr=9.35e-05 | epoch=0.4773
[train] step=224 | loss=0.2693 | lr=9.34e-05 | epoch=0.4794
[train] step=225 | loss=0.3332 | lr=9.34e-05 | epoch=0.4815
[train] step=226 | loss=0.3189 | lr=9.33e-05 | epoch=0.4837
[train] step=227 | loss=0.3329 | lr=9.32e-05 | epoch=0.4858
[train] step=228 | loss=0.3333 | lr=9.31e-05 | epoch=0.4880
[train] step=229 | loss=0.2998 | lr=9.30e-05 | epoch=0.4901
[train] step=230 | loss=0.3520 | lr=9.30e-05 | epoch=0.4922
[train] step=231 | loss=0.3175 | lr=9.29e-05 | epoch=0.4944
[train] step=232 | loss=0.3315 | lr=9.28e-05 | epoch=0.4965
[train] step=233 | loss=0.3424 | lr=9.27e-05 | epoch=0.4987

Saving model checkpoint to output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-233
2026-04-04 12:58:03 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:58:03 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 12:58:03 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 12:58:03 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-233/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-233/tokenizer_config.json

[train] step=234 | loss=0.3178 | lr=9.26e-05 | epoch=0.5008
[train] step=235 | loss=0.2884 | lr=9.26e-05 | epoch=0.5029
[train] step=236 | loss=0.3154 | lr=9.25e-05 | epoch=0.5051
[train] step=237 | loss=0.3227 | lr=9.24e-05 | epoch=0.5072
[train] step=238 | loss=0.3273 | lr=9.23e-05 | epoch=0.5094
[train] step=239 | loss=0.3156 | lr=9.22e-05 | epoch=0.5115
[train] step=240 | loss=0.3097 | lr=9.22e-05 | epoch=0.5136
[train] step=241 | loss=0.3383 | lr=9.21e-05 | epoch=0.5158
[train] step=242 | loss=0.3034 | lr=9.20e-05 | epoch=0.5179
[train] step=243 | loss=0.3916 | lr=9.19e-05 | epoch=0.5201
[train] step=244 | loss=0.3493 | lr=9.19e-05 | epoch=0.5222
[train] step=245 | loss=0.3000 | lr=9.18e-05 | epoch=0.5243
[train] step=246 | loss=0.3768 | lr=9.17e-05 | epoch=0.5265
[train] step=247 | loss=0.3600 | lr=9.16e-05 | epoch=0.5286
[train] step=248 | loss=0.3076 | lr=9.15e-05 | epoch=0.5308
[train] step=249 | loss=0.2650 | lr=9.15e-05 | epoch=0.5329
[train] step=250 | loss=0.3112 | lr=9.14e-05 | epoch=0.5350
[train] step=251 | loss=0.3281 | lr=9.13e-05 | epoch=0.5372
[train] step=252 | loss=0.3238 | lr=9.12e-05 | epoch=0.5393
[train] step=253 | loss=0.3588 | lr=9.11e-05 | epoch=0.5415
[train] step=254 | loss=0.2970 | lr=9.11e-05 | epoch=0.5436
[train] step=255 | loss=0.2979 | lr=9.10e-05 | epoch=0.5457
[train] step=256 | loss=0.2977 | lr=9.09e-05 | epoch=0.5479
[train] step=257 | loss=0.2842 | lr=9.08e-05 | epoch=0.5500
[train] step=258 | loss=0.2949 | lr=9.07e-05 | epoch=0.5522
[train] step=259 | loss=0.3224 | lr=9.07e-05 | epoch=0.5543
[train] step=260 | loss=0.3334 | lr=9.06e-05 | epoch=0.5564
[train] step=261 | loss=0.2978 | lr=9.05e-05 | epoch=0.5586
[train] step=262 | loss=0.3610 | lr=9.04e-05 | epoch=0.5607
[train] step=263 | loss=0.2948 | lr=9.03e-05 | epoch=0.5629
[train] step=264 | loss=0.2733 | lr=9.03e-05 | epoch=0.5650
[train] step=265 | loss=0.3429 | lr=9.02e-05 | epoch=0.5671
[train] step=266 | loss=0.2897 | lr=9.01e-05 | epoch=0.5693
[train] step=267 | loss=0.3083 | lr=9.00e-05 | epoch=0.5714
[train] step=268 | loss=0.3097 | lr=9.00e-05 | epoch=0.5736
[train] step=269 | loss=0.3162 | lr=8.99e-05 | epoch=0.5757
[train] step=270 | loss=0.3641 | lr=8.98e-05 | epoch=0.5778
[train] step=271 | loss=0.3200 | lr=8.97e-05 | epoch=0.5800
[train] step=272 | loss=0.3048 | lr=8.96e-05 | epoch=0.5821
[train] step=273 | loss=0.2716 | lr=8.96e-05 | epoch=0.5843
[train] step=274 | loss=0.3058 | lr=8.95e-05 | epoch=0.5864
[train] step=275 | loss=0.3356 | lr=8.94e-05 | epoch=0.5886
[train] step=276 | loss=0.3235 | lr=8.93e-05 | epoch=0.5907
[train] step=277 | loss=0.2940 | lr=8.92e-05 | epoch=0.5928
[train] step=278 | loss=0.3384 | lr=8.92e-05 | epoch=0.5950
[train] step=279 | loss=0.2856 | lr=8.91e-05 | epoch=0.5971
[train] step=280 | loss=0.3176 | lr=8.90e-05 | epoch=0.5993
[train] step=281 | loss=0.3041 | lr=8.89e-05 | epoch=0.6014
[train] step=282 | loss=0.3215 | lr=8.88e-05 | epoch=0.6035
[train] step=283 | loss=0.3305 | lr=8.88e-05 | epoch=0.6057
[train] step=284 | loss=0.3009 | lr=8.87e-05 | epoch=0.6078
[train] step=285 | loss=0.2793 | lr=8.86e-05 | epoch=0.6100
[train] step=286 | loss=0.2953 | lr=8.85e-05 | epoch=0.6121
[train] step=287 | loss=0.2847 | lr=8.84e-05 | epoch=0.6142
[train] step=288 | loss=0.3007 | lr=8.84e-05 | epoch=0.6164
[train] step=289 | loss=0.2964 | lr=8.83e-05 | epoch=0.6185
[train] step=290 | loss=0.2989 | lr=8.82e-05 | epoch=0.6207
[train] step=291 | loss=0.3339 | lr=8.81e-05 | epoch=0.6228
[train] step=292 | loss=0.3080 | lr=8.81e-05 | epoch=0.6249
[train] step=293 | loss=0.3602 | lr=8.80e-05 | epoch=0.6271
[train] step=294 | loss=0.2893 | lr=8.79e-05 | epoch=0.6292
[train] step=295 | loss=0.3390 | lr=8.78e-05 | epoch=0.6314
[train] step=296 | loss=0.2947 | lr=8.77e-05 | epoch=0.6335
[train] step=297 | loss=0.3224 | lr=8.77e-05 | epoch=0.6356
[train] step=298 | loss=0.2729 | lr=8.76e-05 | epoch=0.6378
[train] step=299 | loss=0.2902 | lr=8.75e-05 | epoch=0.6399
[train] step=300 | loss=0.2989 | lr=8.74e-05 | epoch=0.6421
[train] step=301 | loss=0.3083 | lr=8.73e-05 | epoch=0.6442
[train] step=302 | loss=0.2906 | lr=8.73e-05 | epoch=0.6463
[train] step=303 | loss=0.3257 | lr=8.72e-05 | epoch=0.6485
[train] step=304 | loss=0.3237 | lr=8.71e-05 | epoch=0.6506
[train] step=305 | loss=0.2839 | lr=8.70e-05 | epoch=0.6528
[train] step=306 | loss=0.3740 | lr=8.69e-05 | epoch=0.6549
[train] step=307 | loss=0.3646 | lr=8.69e-05 | epoch=0.6570
[train] step=308 | loss=0.2769 | lr=8.68e-05 | epoch=0.6592
[train] step=309 | loss=0.3620 | lr=8.67e-05 | epoch=0.6613
[train] step=310 | loss=0.2609 | lr=8.66e-05 | epoch=0.6635
[train] step=311 | loss=0.2865 | lr=8.66e-05 | epoch=0.6656
[train] step=312 | loss=0.3583 | lr=8.65e-05 | epoch=0.6677
[train] step=313 | loss=0.3758 | lr=8.64e-05 | epoch=0.6699
[train] step=314 | loss=0.2996 | lr=8.63e-05 | epoch=0.6720
[train] step=315 | loss=0.2721 | lr=8.62e-05 | epoch=0.6742
[train] step=316 | loss=0.3222 | lr=8.62e-05 | epoch=0.6763
[train] step=317 | loss=0.3364 | lr=8.61e-05 | epoch=0.6784
[train] step=318 | loss=0.3081 | lr=8.60e-05 | epoch=0.6806
[train] step=319 | loss=0.3670 | lr=8.59e-05 | epoch=0.6827
[train] step=320 | loss=0.3740 | lr=8.58e-05 | epoch=0.6849
[train] step=321 | loss=0.2887 | lr=8.58e-05 | epoch=0.6870
[train] step=322 | loss=0.3233 | lr=8.57e-05 | epoch=0.6891
[train] step=323 | loss=0.2964 | lr=8.56e-05 | epoch=0.6913
[train] step=324 | loss=0.2917 | lr=8.55e-05 | epoch=0.6934
[train] step=325 | loss=0.3062 | lr=8.54e-05 | epoch=0.6956
[train] step=326 | loss=0.3203 | lr=8.54e-05 | epoch=0.6977
[train] step=327 | loss=0.3024 | lr=8.53e-05 | epoch=0.6998
[train] step=328 | loss=0.3560 | lr=8.52e-05 | epoch=0.7020
[train] step=329 | loss=0.2454 | lr=8.51e-05 | epoch=0.7041
[train] step=330 | loss=0.2892 | lr=8.50e-05 | epoch=0.7063
[train] step=331 | loss=0.3096 | lr=8.50e-05 | epoch=0.7084
[train] step=332 | loss=0.3300 | lr=8.49e-05 | epoch=0.7105
[train] step=333 | loss=0.3331 | lr=8.48e-05 | epoch=0.7127
[train] step=334 | loss=0.3681 | lr=8.47e-05 | epoch=0.7148
[train] step=335 | loss=0.2644 | lr=8.47e-05 | epoch=0.7170
[train] step=336 | loss=0.3222 | lr=8.46e-05 | epoch=0.7191
[train] step=337 | loss=0.2931 | lr=8.45e-05 | epoch=0.7212
[train] step=338 | loss=0.3053 | lr=8.44e-05 | epoch=0.7234
[train] step=339 | loss=0.3489 | lr=8.43e-05 | epoch=0.7255
[train] step=340 | loss=0.3029 | lr=8.43e-05 | epoch=0.7277
[train] step=341 | loss=0.3902 | lr=8.42e-05 | epoch=0.7298
[train] step=342 | loss=0.2754 | lr=8.41e-05 | epoch=0.7319
[train] step=343 | loss=0.2699 | lr=8.40e-05 | epoch=0.7341
[train] step=344 | loss=0.3352 | lr=8.39e-05 | epoch=0.7362
[train] step=345 | loss=0.3494 | lr=8.39e-05 | epoch=0.7384
[train] step=346 | loss=0.2925 | lr=8.38e-05 | epoch=0.7405
[train] step=347 | loss=0.2862 | lr=8.37e-05 | epoch=0.7426
[train] step=348 | loss=0.3598 | lr=8.36e-05 | epoch=0.7448
[train] step=349 | loss=0.2985 | lr=8.35e-05 | epoch=0.7469
[train] step=350 | loss=0.2600 | lr=8.35e-05 | epoch=0.7491
[train] step=351 | loss=0.3200 | lr=8.34e-05 | epoch=0.7512
[train] step=352 | loss=0.3194 | lr=8.33e-05 | epoch=0.7533
[train] step=353 | loss=0.3722 | lr=8.32e-05 | epoch=0.7555
[train] step=354 | loss=0.2372 | lr=8.31e-05 | epoch=0.7576
[train] step=355 | loss=0.3277 | lr=8.31e-05 | epoch=0.7598
[train] step=356 | loss=0.2934 | lr=8.30e-05 | epoch=0.7619
[train] step=357 | loss=0.3275 | lr=8.29e-05 | epoch=0.7640
[train] step=358 | loss=0.2561 | lr=8.28e-05 | epoch=0.7662
[train] step=359 | loss=0.2797 | lr=8.28e-05 | epoch=0.7683
[train] step=360 | loss=0.3183 | lr=8.27e-05 | epoch=0.7705
[train] step=361 | loss=0.2763 | lr=8.26e-05 | epoch=0.7726
[train] step=362 | loss=0.3016 | lr=8.25e-05 | epoch=0.7747
[train] step=363 | loss=0.3595 | lr=8.24e-05 | epoch=0.7769
[train] step=364 | loss=0.2983 | lr=8.24e-05 | epoch=0.7790
[train] step=365 | loss=0.2878 | lr=8.23e-05 | epoch=0.7812
[train] step=366 | loss=0.3615 | lr=8.22e-05 | epoch=0.7833
[train] step=367 | loss=0.2764 | lr=8.21e-05 | epoch=0.7854
[train] step=368 | loss=0.3107 | lr=8.20e-05 | epoch=0.7876
[train] step=369 | loss=0.3285 | lr=8.20e-05 | epoch=0.7897
[train] step=370 | loss=0.3502 | lr=8.19e-05 | epoch=0.7919
[train] step=371 | loss=0.3575 | lr=8.18e-05 | epoch=0.7940
[train] step=372 | loss=0.3225 | lr=8.17e-05 | epoch=0.7961
[train] step=373 | loss=0.3342 | lr=8.16e-05 | epoch=0.7983
[train] step=374 | loss=0.2941 | lr=8.16e-05 | epoch=0.8004
[train] step=375 | loss=0.3165 | lr=8.15e-05 | epoch=0.8026
[train] step=376 | loss=0.2954 | lr=8.14e-05 | epoch=0.8047
[train] step=377 | loss=0.2786 | lr=8.13e-05 | epoch=0.8068
[train] step=378 | loss=0.2809 | lr=8.13e-05 | epoch=0.8090
[train] step=379 | loss=0.3688 | lr=8.12e-05 | epoch=0.8111
[train] step=380 | loss=0.3621 | lr=8.11e-05 | epoch=0.8133
[train] step=381 | loss=0.3425 | lr=8.10e-05 | epoch=0.8154
[train] step=382 | loss=0.3342 | lr=8.09e-05 | epoch=0.8175
[train] step=383 | loss=0.2857 | lr=8.09e-05 | epoch=0.8197
[train] step=384 | loss=0.2611 | lr=8.08e-05 | epoch=0.8218
[train] step=385 | loss=0.3385 | lr=8.07e-05 | epoch=0.8240
[train] step=386 | loss=0.4047 | lr=8.06e-05 | epoch=0.8261
[train] step=387 | loss=0.2899 | lr=8.05e-05 | epoch=0.8283
[train] step=388 | loss=0.3065 | lr=8.05e-05 | epoch=0.8304
[train] step=389 | loss=0.2889 | lr=8.04e-05 | epoch=0.8325
[train] step=390 | loss=0.2823 | lr=8.03e-05 | epoch=0.8347
[train] step=391 | loss=0.2890 | lr=8.02e-05 | epoch=0.8368
[train] step=392 | loss=0.2830 | lr=8.01e-05 | epoch=0.8390
[train] step=393 | loss=0.3175 | lr=8.01e-05 | epoch=0.8411
[train] step=394 | loss=0.3173 | lr=8.00e-05 | epoch=0.8432
[train] step=395 | loss=0.3548 | lr=7.99e-05 | epoch=0.8454
[train] step=396 | loss=0.3544 | lr=7.98e-05 | epoch=0.8475
[train] step=397 | loss=0.2862 | lr=7.97e-05 | epoch=0.8497
[train] step=398 | loss=0.3311 | lr=7.97e-05 | epoch=0.8518
[train] step=399 | loss=0.3210 | lr=7.96e-05 | epoch=0.8539
[train] step=400 | loss=0.3326 | lr=7.95e-05 | epoch=0.8561
[train] step=401 | loss=0.3254 | lr=7.94e-05 | epoch=0.8582
[train] step=402 | loss=0.3151 | lr=7.94e-05 | epoch=0.8604
[train] step=403 | loss=0.2590 | lr=7.93e-05 | epoch=0.8625
[train] step=404 | loss=0.3063 | lr=7.92e-05 | epoch=0.8646
[train] step=405 | loss=0.3238 | lr=7.91e-05 | epoch=0.8668
[train] step=406 | loss=0.3022 | lr=7.90e-05 | epoch=0.8689
[train] step=407 | loss=0.2557 | lr=7.90e-05 | epoch=0.8711
[train] step=408 | loss=0.3601 | lr=7.89e-05 | epoch=0.8732
[train] step=409 | loss=0.3197 | lr=7.88e-05 | epoch=0.8753
[train] step=410 | loss=0.2863 | lr=7.87e-05 | epoch=0.8775
[train] step=411 | loss=0.2712 | lr=7.86e-05 | epoch=0.8796
[train] step=412 | loss=0.3065 | lr=7.86e-05 | epoch=0.8818
[train] step=413 | loss=0.3156 | lr=7.85e-05 | epoch=0.8839
[train] step=414 | loss=0.3044 | lr=7.84e-05 | epoch=0.8860
[train] step=415 | loss=0.2995 | lr=7.83e-05 | epoch=0.8882
[train] step=416 | loss=0.3582 | lr=7.82e-05 | epoch=0.8903
[train] step=417 | loss=0.3461 | lr=7.82e-05 | epoch=0.8925
[train] step=418 | loss=0.3054 | lr=7.81e-05 | epoch=0.8946
[train] step=419 | loss=0.2774 | lr=7.80e-05 | epoch=0.8967
[train] step=420 | loss=0.3463 | lr=7.79e-05 | epoch=0.8989
[train] step=421 | loss=0.2993 | lr=7.78e-05 | epoch=0.9010
[train] step=422 | loss=0.2893 | lr=7.78e-05 | epoch=0.9032
[train] step=423 | loss=0.3596 | lr=7.77e-05 | epoch=0.9053
[train] step=424 | loss=0.3166 | lr=7.76e-05 | epoch=0.9074
[train] step=425 | loss=0.3050 | lr=7.75e-05 | epoch=0.9096
[train] step=426 | loss=0.2923 | lr=7.75e-05 | epoch=0.9117
[train] step=427 | loss=0.3162 | lr=7.74e-05 | epoch=0.9139
[train] step=428 | loss=0.3098 | lr=7.73e-05 | epoch=0.9160
[train] step=429 | loss=0.3080 | lr=7.72e-05 | epoch=0.9181
[train] step=430 | loss=0.2890 | lr=7.71e-05 | epoch=0.9203
[train] step=431 | loss=0.2901 | lr=7.71e-05 | epoch=0.9224
[train] step=432 | loss=0.4044 | lr=7.70e-05 | epoch=0.9246
[train] step=433 | loss=0.2568 | lr=7.69e-05 | epoch=0.9267
[train] step=434 | loss=0.2880 | lr=7.68e-05 | epoch=0.9288
[train] step=435 | loss=0.3220 | lr=7.67e-05 | epoch=0.9310
[train] step=436 | loss=0.3474 | lr=7.67e-05 | epoch=0.9331
[train] step=437 | loss=0.2662 | lr=7.66e-05 | epoch=0.9353
[train] step=438 | loss=0.2658 | lr=7.65e-05 | epoch=0.9374
[train] step=439 | loss=0.3715 | lr=7.64e-05 | epoch=0.9395
[train] step=440 | loss=0.3110 | lr=7.63e-05 | epoch=0.9417
[train] step=441 | loss=0.3051 | lr=7.63e-05 | epoch=0.9438
[train] step=442 | loss=0.3550 | lr=7.62e-05 | epoch=0.9460
[train] step=443 | loss=0.3042 | lr=7.61e-05 | epoch=0.9481
[train] step=444 | loss=0.3012 | lr=7.60e-05 | epoch=0.9502
[train] step=445 | loss=0.2993 | lr=7.59e-05 | epoch=0.9524
[train] step=446 | loss=0.2800 | lr=7.59e-05 | epoch=0.9545
[train] step=447 | loss=0.2588 | lr=7.58e-05 | epoch=0.9567
[train] step=448 | loss=0.3207 | lr=7.57e-05 | epoch=0.9588
[train] step=449 | loss=0.3256 | lr=7.56e-05 | epoch=0.9609
[train] step=450 | loss=0.2727 | lr=7.56e-05 | epoch=0.9631
[train] step=451 | loss=0.3027 | lr=7.55e-05 | epoch=0.9652
[train] step=452 | loss=0.2970 | lr=7.54e-05 | epoch=0.9674
[train] step=453 | loss=0.2840 | lr=7.53e-05 | epoch=0.9695
[train] step=454 | loss=0.3011 | lr=7.52e-05 | epoch=0.9716
[train] step=455 | loss=0.2650 | lr=7.52e-05 | epoch=0.9738
[train] step=456 | loss=0.3520 | lr=7.51e-05 | epoch=0.9759
[train] step=457 | loss=0.3534 | lr=7.50e-05 | epoch=0.9781
[train] step=458 | loss=0.3089 | lr=7.49e-05 | epoch=0.9802
[train] step=459 | loss=0.3083 | lr=7.48e-05 | epoch=0.9823
[train] step=460 | loss=0.3200 | lr=7.48e-05 | epoch=0.9845
[train] step=461 | loss=0.3049 | lr=7.47e-05 | epoch=0.9866
[train] step=462 | loss=0.2950 | lr=7.46e-05 | epoch=0.9888
[train] step=463 | loss=0.2896 | lr=7.45e-05 | epoch=0.9909
[train] step=464 | loss=0.3233 | lr=7.44e-05 | epoch=0.9930
[train] step=465 | loss=0.2887 | lr=7.44e-05 | epoch=0.9952
[train] step=466 | loss=0.3139 | lr=7.43e-05 | epoch=0.9973

Saving model checkpoint to output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-466
2026-04-04 13:01:28 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:01:28 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 13:01:28 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:01:28 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-466/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-466/tokenizer_config.json

[train] step=467 | loss=0.3165 | lr=7.42e-05 | epoch=0.9995
[train] step=468 | loss=0.2604 | lr=7.41e-05 | epoch=1.0000
[train] step=469 | loss=0.2801 | lr=7.41e-05 | epoch=1.0021
[train] step=470 | loss=0.2867 | lr=7.40e-05 | epoch=1.0043
[train] step=471 | loss=0.3206 | lr=7.39e-05 | epoch=1.0064
[train] step=472 | loss=0.3276 | lr=7.38e-05 | epoch=1.0086
[train] step=473 | loss=0.2925 | lr=7.37e-05 | epoch=1.0107
[train] step=474 | loss=0.3002 | lr=7.37e-05 | epoch=1.0128
[train] step=475 | loss=0.2915 | lr=7.36e-05 | epoch=1.0150
[train] step=476 | loss=0.3006 | lr=7.35e-05 | epoch=1.0171
[train] step=477 | loss=0.3417 | lr=7.34e-05 | epoch=1.0193
[train] step=478 | loss=0.2660 | lr=7.33e-05 | epoch=1.0214
[train] step=479 | loss=0.3470 | lr=7.33e-05 | epoch=1.0235
[train] step=480 | loss=0.2624 | lr=7.32e-05 | epoch=1.0257
[train] step=481 | loss=0.3106 | lr=7.31e-05 | epoch=1.0278
[train] step=482 | loss=0.3045 | lr=7.30e-05 | epoch=1.0300
[train] step=483 | loss=0.2562 | lr=7.29e-05 | epoch=1.0321
[train] step=484 | loss=0.2857 | lr=7.29e-05 | epoch=1.0342
[train] step=485 | loss=0.2542 | lr=7.28e-05 | epoch=1.0364
[train] step=486 | loss=0.2776 | lr=7.27e-05 | epoch=1.0385
[train] step=487 | loss=0.3557 | lr=7.26e-05 | epoch=1.0407
[train] step=488 | loss=0.2863 | lr=7.25e-05 | epoch=1.0428
[train] step=489 | loss=0.2652 | lr=7.25e-05 | epoch=1.0449
[train] step=490 | loss=0.2772 | lr=7.24e-05 | epoch=1.0471
[train] step=491 | loss=0.3031 | lr=7.23e-05 | epoch=1.0492
[train] step=492 | loss=0.3119 | lr=7.22e-05 | epoch=1.0514
[train] step=493 | loss=0.2708 | lr=7.22e-05 | epoch=1.0535
[train] step=494 | loss=0.3333 | lr=7.21e-05 | epoch=1.0556
[train] step=495 | loss=0.2629 | lr=7.20e-05 | epoch=1.0578
[train] step=496 | loss=0.3096 | lr=7.19e-05 | epoch=1.0599
[train] step=497 | loss=0.2978 | lr=7.18e-05 | epoch=1.0621
[train] step=498 | loss=0.3621 | lr=7.18e-05 | epoch=1.0642
[train] step=499 | loss=0.2835 | lr=7.17e-05 | epoch=1.0663
[train] step=500 | loss=0.3058 | lr=7.16e-05 | epoch=1.0685
[train] step=501 | loss=0.2845 | lr=7.15e-05 | epoch=1.0706
[train] step=502 | loss=0.2726 | lr=7.14e-05 | epoch=1.0728
[train] step=503 | loss=0.3547 | lr=7.14e-05 | epoch=1.0749
[train] step=504 | loss=0.3239 | lr=7.13e-05 | epoch=1.0770
[train] step=505 | loss=0.3184 | lr=7.12e-05 | epoch=1.0792
[train] step=506 | loss=0.2897 | lr=7.11e-05 | epoch=1.0813
[train] step=507 | loss=0.2967 | lr=7.10e-05 | epoch=1.0835
[train] step=508 | loss=0.3396 | lr=7.10e-05 | epoch=1.0856
[train] step=509 | loss=0.4041 | lr=7.09e-05 | epoch=1.0877
[train] step=510 | loss=0.3050 | lr=7.08e-05 | epoch=1.0899
[train] step=511 | loss=0.3156 | lr=7.07e-05 | epoch=1.0920
[train] step=512 | loss=0.2692 | lr=7.06e-05 | epoch=1.0942
[train] step=513 | loss=0.2586 | lr=7.06e-05 | epoch=1.0963
[train] step=514 | loss=0.2681 | lr=7.05e-05 | epoch=1.0984
[train] step=515 | loss=0.2971 | lr=7.04e-05 | epoch=1.1006
[train] step=516 | loss=0.3496 | lr=7.03e-05 | epoch=1.1027
[train] step=517 | loss=0.2653 | lr=7.03e-05 | epoch=1.1049
[train] step=518 | loss=0.3437 | lr=7.02e-05 | epoch=1.1070
[train] step=519 | loss=0.2828 | lr=7.01e-05 | epoch=1.1091
[train] step=520 | loss=0.3033 | lr=7.00e-05 | epoch=1.1113
[train] step=521 | loss=0.3157 | lr=6.99e-05 | epoch=1.1134
[train] step=522 | loss=0.3468 | lr=6.99e-05 | epoch=1.1156
[train] step=523 | loss=0.2752 | lr=6.98e-05 | epoch=1.1177
[train] step=524 | loss=0.2902 | lr=6.97e-05 | epoch=1.1199
[train] step=525 | loss=0.2693 | lr=6.96e-05 | epoch=1.1220
[train] step=526 | loss=0.2872 | lr=6.95e-05 | epoch=1.1241
[train] step=527 | loss=0.2468 | lr=6.95e-05 | epoch=1.1263
[train] step=528 | loss=0.3158 | lr=6.94e-05 | epoch=1.1284
[train] step=529 | loss=0.2930 | lr=6.93e-05 | epoch=1.1306
[train] step=530 | loss=0.2968 | lr=6.92e-05 | epoch=1.1327
[train] step=531 | loss=0.3550 | lr=6.91e-05 | epoch=1.1348
[train] step=532 | loss=0.3017 | lr=6.91e-05 | epoch=1.1370
[train] step=533 | loss=0.2779 | lr=6.90e-05 | epoch=1.1391
[train] step=534 | loss=0.2963 | lr=6.89e-05 | epoch=1.1413
[train] step=535 | loss=0.3063 | lr=6.88e-05 | epoch=1.1434
[train] step=536 | loss=0.3258 | lr=6.88e-05 | epoch=1.1455
[train] step=537 | loss=0.2860 | lr=6.87e-05 | epoch=1.1477
[train] step=538 | loss=0.2900 | lr=6.86e-05 | epoch=1.1498
[train] step=539 | loss=0.3084 | lr=6.85e-05 | epoch=1.1520
[train] step=540 | loss=0.2491 | lr=6.84e-05 | epoch=1.1541
[train] step=541 | loss=0.2294 | lr=6.84e-05 | epoch=1.1562
[train] step=542 | loss=0.2975 | lr=6.83e-05 | epoch=1.1584
[train] step=543 | loss=0.2713 | lr=6.82e-05 | epoch=1.1605
[train] step=544 | loss=0.2518 | lr=6.81e-05 | epoch=1.1627
[train] step=545 | loss=0.2608 | lr=6.80e-05 | epoch=1.1648
[train] step=546 | loss=0.2593 | lr=6.80e-05 | epoch=1.1669
[train] step=547 | loss=0.2622 | lr=6.79e-05 | epoch=1.1691
[train] step=548 | loss=0.2981 | lr=6.78e-05 | epoch=1.1712
[train] step=549 | loss=0.2325 | lr=6.77e-05 | epoch=1.1734
[train] step=550 | loss=0.2793 | lr=6.76e-05 | epoch=1.1755
[train] step=551 | loss=0.2767 | lr=6.76e-05 | epoch=1.1776
[train] step=552 | loss=0.3067 | lr=6.75e-05 | epoch=1.1798
[train] step=553 | loss=0.3013 | lr=6.74e-05 | epoch=1.1819
[train] step=554 | loss=0.2708 | lr=6.73e-05 | epoch=1.1841
[train] step=555 | loss=0.2850 | lr=6.72e-05 | epoch=1.1862
[train] step=556 | loss=0.2869 | lr=6.72e-05 | epoch=1.1883
[train] step=557 | loss=0.3090 | lr=6.71e-05 | epoch=1.1905
[train] step=558 | loss=0.3173 | lr=6.70e-05 | epoch=1.1926
[train] step=559 | loss=0.3074 | lr=6.69e-05 | epoch=1.1948
[train] step=560 | loss=0.3071 | lr=6.69e-05 | epoch=1.1969
[train] step=561 | loss=0.2844 | lr=6.68e-05 | epoch=1.1990
[train] step=562 | loss=0.3111 | lr=6.67e-05 | epoch=1.2012
[train] step=563 | loss=0.3261 | lr=6.66e-05 | epoch=1.2033
[train] step=564 | loss=0.2727 | lr=6.65e-05 | epoch=1.2055
[train] step=565 | loss=0.3461 | lr=6.65e-05 | epoch=1.2076
[train] step=566 | loss=0.2983 | lr=6.64e-05 | epoch=1.2097
[train] step=567 | loss=0.2652 | lr=6.63e-05 | epoch=1.2119
[train] step=568 | loss=0.2635 | lr=6.62e-05 | epoch=1.2140
[train] step=569 | loss=0.3386 | lr=6.61e-05 | epoch=1.2162
[train] step=570 | loss=0.2800 | lr=6.61e-05 | epoch=1.2183
[train] step=571 | loss=0.3020 | lr=6.60e-05 | epoch=1.2204
[train] step=572 | loss=0.3120 | lr=6.59e-05 | epoch=1.2226
[train] step=573 | loss=0.3274 | lr=6.58e-05 | epoch=1.2247
[train] step=574 | loss=0.2888 | lr=6.57e-05 | epoch=1.2269
[train] step=575 | loss=0.2839 | lr=6.57e-05 | epoch=1.2290
[train] step=576 | loss=0.3076 | lr=6.56e-05 | epoch=1.2311
[train] step=577 | loss=0.3413 | lr=6.55e-05 | epoch=1.2333
[train] step=578 | loss=0.3081 | lr=6.54e-05 | epoch=1.2354
[train] step=579 | loss=0.3489 | lr=6.53e-05 | epoch=1.2376
[train] step=580 | loss=0.2765 | lr=6.53e-05 | epoch=1.2397
[train] step=581 | loss=0.2940 | lr=6.52e-05 | epoch=1.2418
[train] step=582 | loss=0.2865 | lr=6.51e-05 | epoch=1.2440
[train] step=583 | loss=0.3415 | lr=6.50e-05 | epoch=1.2461
[train] step=584 | loss=0.2935 | lr=6.50e-05 | epoch=1.2483
[train] step=585 | loss=0.3104 | lr=6.49e-05 | epoch=1.2504
[train] step=586 | loss=0.2570 | lr=6.48e-05 | epoch=1.2525
[train] step=587 | loss=0.2867 | lr=6.47e-05 | epoch=1.2547
[train] step=588 | loss=0.3620 | lr=6.46e-05 | epoch=1.2568
[train] step=589 | loss=0.3438 | lr=6.46e-05 | epoch=1.2590
[train] step=590 | loss=0.3260 | lr=6.45e-05 | epoch=1.2611
[train] step=591 | loss=0.2605 | lr=6.44e-05 | epoch=1.2632
[train] step=592 | loss=0.3055 | lr=6.43e-05 | epoch=1.2654
[train] step=593 | loss=0.2841 | lr=6.42e-05 | epoch=1.2675
[train] step=594 | loss=0.2536 | lr=6.42e-05 | epoch=1.2697
[train] step=595 | loss=0.2493 | lr=6.41e-05 | epoch=1.2718
[train] step=596 | loss=0.2907 | lr=6.40e-05 | epoch=1.2739
[train] step=597 | loss=0.2926 | lr=6.39e-05 | epoch=1.2761
[train] step=598 | loss=0.3051 | lr=6.38e-05 | epoch=1.2782
[train] step=599 | loss=0.2863 | lr=6.38e-05 | epoch=1.2804
[train] step=600 | loss=0.3135 | lr=6.37e-05 | epoch=1.2825
[train] step=601 | loss=0.2943 | lr=6.36e-05 | epoch=1.2846
[train] step=602 | loss=0.2743 | lr=6.35e-05 | epoch=1.2868
[train] step=603 | loss=0.2733 | lr=6.34e-05 | epoch=1.2889
[train] step=604 | loss=0.2853 | lr=6.34e-05 | epoch=1.2911
[train] step=605 | loss=0.2652 | lr=6.33e-05 | epoch=1.2932
[train] step=606 | loss=0.2331 | lr=6.32e-05 | epoch=1.2953
[train] step=607 | loss=0.3176 | lr=6.31e-05 | epoch=1.2975
[train] step=608 | loss=0.2369 | lr=6.31e-05 | epoch=1.2996
[train] step=609 | loss=0.3280 | lr=6.30e-05 | epoch=1.3018
[train] step=610 | loss=0.3210 | lr=6.29e-05 | epoch=1.3039
[train] step=611 | loss=0.2377 | lr=6.28e-05 | epoch=1.3060
[train] step=612 | loss=0.2962 | lr=6.27e-05 | epoch=1.3082
[train] step=613 | loss=0.3200 | lr=6.27e-05 | epoch=1.3103
[train] step=614 | loss=0.2952 | lr=6.26e-05 | epoch=1.3125
[train] step=615 | loss=0.3107 | lr=6.25e-05 | epoch=1.3146
[train] step=616 | loss=0.2671 | lr=6.24e-05 | epoch=1.3167
[train] step=617 | loss=0.2329 | lr=6.23e-05 | epoch=1.3189
[train] step=618 | loss=0.3259 | lr=6.23e-05 | epoch=1.3210
[train] step=619 | loss=0.2936 | lr=6.22e-05 | epoch=1.3232
[train] step=620 | loss=0.2891 | lr=6.21e-05 | epoch=1.3253
[train] step=621 | loss=0.3200 | lr=6.20e-05 | epoch=1.3274
[train] step=622 | loss=0.2854 | lr=6.19e-05 | epoch=1.3296
[train] step=623 | loss=0.3015 | lr=6.19e-05 | epoch=1.3317
[train] step=624 | loss=0.2735 | lr=6.18e-05 | epoch=1.3339
[train] step=625 | loss=0.2738 | lr=6.17e-05 | epoch=1.3360
[train] step=626 | loss=0.2793 | lr=6.16e-05 | epoch=1.3381
[train] step=627 | loss=0.3433 | lr=6.16e-05 | epoch=1.3403
[train] step=628 | loss=0.2922 | lr=6.15e-05 | epoch=1.3424
[train] step=629 | loss=0.2273 | lr=6.14e-05 | epoch=1.3446
[train] step=630 | loss=0.3037 | lr=6.13e-05 | epoch=1.3467
[train] step=631 | loss=0.2601 | lr=6.12e-05 | epoch=1.3488
[train] step=632 | loss=0.2929 | lr=6.12e-05 | epoch=1.3510
[train] step=633 | loss=0.2977 | lr=6.11e-05 | epoch=1.3531
[train] step=634 | loss=0.3090 | lr=6.10e-05 | epoch=1.3553
[train] step=635 | loss=0.2885 | lr=6.09e-05 | epoch=1.3574
[train] step=636 | loss=0.2873 | lr=6.08e-05 | epoch=1.3596
[train] step=637 | loss=0.2629 | lr=6.08e-05 | epoch=1.3617
[train] step=638 | loss=0.3228 | lr=6.07e-05 | epoch=1.3638
[train] step=639 | loss=0.2942 | lr=6.06e-05 | epoch=1.3660
[train] step=640 | loss=0.2669 | lr=6.05e-05 | epoch=1.3681
[train] step=641 | loss=0.2936 | lr=6.04e-05 | epoch=1.3703
[train] step=642 | loss=0.2750 | lr=6.04e-05 | epoch=1.3724
[train] step=643 | loss=0.3116 | lr=6.03e-05 | epoch=1.3745
[train] step=644 | loss=0.3327 | lr=6.02e-05 | epoch=1.3767
[train] step=645 | loss=0.3316 | lr=6.01e-05 | epoch=1.3788
[train] step=646 | loss=0.3045 | lr=6.00e-05 | epoch=1.3810
[train] step=647 | loss=0.2641 | lr=6.00e-05 | epoch=1.3831
[train] step=648 | loss=0.2800 | lr=5.99e-05 | epoch=1.3852
[train] step=649 | loss=0.2203 | lr=5.98e-05 | epoch=1.3874
[train] step=650 | loss=0.2635 | lr=5.97e-05 | epoch=1.3895
[train] step=651 | loss=0.2567 | lr=5.97e-05 | epoch=1.3917
[train] step=652 | loss=0.2726 | lr=5.96e-05 | epoch=1.3938
[train] step=653 | loss=0.3357 | lr=5.95e-05 | epoch=1.3959
[train] step=654 | loss=0.2639 | lr=5.94e-05 | epoch=1.3981
[train] step=655 | loss=0.2588 | lr=5.93e-05 | epoch=1.4002
[train] step=656 | loss=0.2931 | lr=5.93e-05 | epoch=1.4024
[train] step=657 | loss=0.2925 | lr=5.92e-05 | epoch=1.4045
[train] step=658 | loss=0.3094 | lr=5.91e-05 | epoch=1.4066
[train] step=659 | loss=0.3187 | lr=5.90e-05 | epoch=1.4088
[train] step=660 | loss=0.3231 | lr=5.89e-05 | epoch=1.4109
[train] step=661 | loss=0.3652 | lr=5.89e-05 | epoch=1.4131
[train] step=662 | loss=0.3286 | lr=5.88e-05 | epoch=1.4152
[train] step=663 | loss=0.3015 | lr=5.87e-05 | epoch=1.4173
[train] step=664 | loss=0.2983 | lr=5.86e-05 | epoch=1.4195
[train] step=665 | loss=0.2807 | lr=5.85e-05 | epoch=1.4216
[train] step=666 | loss=0.2336 | lr=5.85e-05 | epoch=1.4238
[train] step=667 | loss=0.2872 | lr=5.84e-05 | epoch=1.4259
[train] step=668 | loss=0.2860 | lr=5.83e-05 | epoch=1.4280
[train] step=669 | loss=0.3024 | lr=5.82e-05 | epoch=1.4302
[train] step=670 | loss=0.2809 | lr=5.81e-05 | epoch=1.4323
[train] step=671 | loss=0.2905 | lr=5.81e-05 | epoch=1.4345
[train] step=672 | loss=0.2531 | lr=5.80e-05 | epoch=1.4366
[train] step=673 | loss=0.3308 | lr=5.79e-05 | epoch=1.4387
[train] step=674 | loss=0.3005 | lr=5.78e-05 | epoch=1.4409
[train] step=675 | loss=0.2486 | lr=5.78e-05 | epoch=1.4430
[train] step=676 | loss=0.2699 | lr=5.77e-05 | epoch=1.4452
[train] step=677 | loss=0.2706 | lr=5.76e-05 | epoch=1.4473
[train] step=678 | loss=0.2595 | lr=5.75e-05 | epoch=1.4494
[train] step=679 | loss=0.2609 | lr=5.74e-05 | epoch=1.4516
[train] step=680 | loss=0.2869 | lr=5.74e-05 | epoch=1.4537
[train] step=681 | loss=0.2988 | lr=5.73e-05 | epoch=1.4559
[train] step=682 | loss=0.2681 | lr=5.72e-05 | epoch=1.4580
[train] step=683 | loss=0.2713 | lr=5.71e-05 | epoch=1.4601
[train] step=684 | loss=0.2862 | lr=5.70e-05 | epoch=1.4623
[train] step=685 | loss=0.3439 | lr=5.70e-05 | epoch=1.4644
[train] step=686 | loss=0.2708 | lr=5.69e-05 | epoch=1.4666
[train] step=687 | loss=0.2716 | lr=5.68e-05 | epoch=1.4687
[train] step=688 | loss=0.3291 | lr=5.67e-05 | epoch=1.4708
[train] step=689 | loss=0.3241 | lr=5.66e-05 | epoch=1.4730
[train] step=690 | loss=0.3401 | lr=5.66e-05 | epoch=1.4751
[train] step=691 | loss=0.2405 | lr=5.65e-05 | epoch=1.4773
[train] step=692 | loss=0.3142 | lr=5.64e-05 | epoch=1.4794
[train] step=693 | loss=0.2709 | lr=5.63e-05 | epoch=1.4815
[train] step=694 | loss=0.3085 | lr=5.63e-05 | epoch=1.4837
[train] step=695 | loss=0.2540 | lr=5.62e-05 | epoch=1.4858
[train] step=696 | loss=0.3192 | lr=5.61e-05 | epoch=1.4880
[train] step=697 | loss=0.3337 | lr=5.60e-05 | epoch=1.4901
[train] step=698 | loss=0.2990 | lr=5.59e-05 | epoch=1.4922
[train] step=699 | loss=0.3509 | lr=5.59e-05 | epoch=1.4944

Saving model checkpoint to output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-699
2026-04-04 13:04:58 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:04:58 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 13:04:58 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:04:58 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-699/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-699/tokenizer_config.json

[train] step=700 | loss=0.2945 | lr=5.58e-05 | epoch=1.4965
[train] step=701 | loss=0.3138 | lr=5.57e-05 | epoch=1.4987
[train] step=702 | loss=0.2740 | lr=5.56e-05 | epoch=1.5008
[train] step=703 | loss=0.2978 | lr=5.55e-05 | epoch=1.5029
[train] step=704 | loss=0.2570 | lr=5.55e-05 | epoch=1.5051
[train] step=705 | loss=0.3377 | lr=5.54e-05 | epoch=1.5072
[train] step=706 | loss=0.3161 | lr=5.53e-05 | epoch=1.5094
[train] step=707 | loss=0.2769 | lr=5.52e-05 | epoch=1.5115
[train] step=708 | loss=0.2724 | lr=5.51e-05 | epoch=1.5136
[train] step=709 | loss=0.2257 | lr=5.51e-05 | epoch=1.5158
[train] step=710 | loss=0.3058 | lr=5.50e-05 | epoch=1.5179
[train] step=711 | loss=0.2946 | lr=5.49e-05 | epoch=1.5201
[train] step=712 | loss=0.2887 | lr=5.48e-05 | epoch=1.5222
[train] step=713 | loss=0.2598 | lr=5.47e-05 | epoch=1.5243
[train] step=714 | loss=0.2520 | lr=5.47e-05 | epoch=1.5265
[train] step=715 | loss=0.2591 | lr=5.46e-05 | epoch=1.5286
[train] step=716 | loss=0.2911 | lr=5.45e-05 | epoch=1.5308
[train] step=717 | loss=0.2874 | lr=5.44e-05 | epoch=1.5329
[train] step=718 | loss=0.2919 | lr=5.44e-05 | epoch=1.5350
[train] step=719 | loss=0.2217 | lr=5.43e-05 | epoch=1.5372
[train] step=720 | loss=0.3133 | lr=5.42e-05 | epoch=1.5393
[train] step=721 | loss=0.3080 | lr=5.41e-05 | epoch=1.5415
[train] step=722 | loss=0.2768 | lr=5.40e-05 | epoch=1.5436
[train] step=723 | loss=0.2958 | lr=5.40e-05 | epoch=1.5457
[train] step=724 | loss=0.2692 | lr=5.39e-05 | epoch=1.5479
[train] step=725 | loss=0.3865 | lr=5.38e-05 | epoch=1.5500
[train] step=726 | loss=0.2960 | lr=5.37e-05 | epoch=1.5522
[train] step=727 | loss=0.2646 | lr=5.36e-05 | epoch=1.5543
[train] step=728 | loss=0.2670 | lr=5.36e-05 | epoch=1.5564
[train] step=729 | loss=0.3006 | lr=5.35e-05 | epoch=1.5586
[train] step=730 | loss=0.2898 | lr=5.34e-05 | epoch=1.5607
[train] step=731 | loss=0.2899 | lr=5.33e-05 | epoch=1.5629
[train] step=732 | loss=0.3383 | lr=5.32e-05 | epoch=1.5650
[train] step=733 | loss=0.2685 | lr=5.32e-05 | epoch=1.5671
[train] step=734 | loss=0.2614 | lr=5.31e-05 | epoch=1.5693
[train] step=735 | loss=0.2888 | lr=5.30e-05 | epoch=1.5714
[train] step=736 | loss=0.2753 | lr=5.29e-05 | epoch=1.5736
[train] step=737 | loss=0.2714 | lr=5.28e-05 | epoch=1.5757
[train] step=738 | loss=0.2897 | lr=5.28e-05 | epoch=1.5778
[train] step=739 | loss=0.3134 | lr=5.27e-05 | epoch=1.5800
[train] step=740 | loss=0.3219 | lr=5.26e-05 | epoch=1.5821
[train] step=741 | loss=0.2850 | lr=5.25e-05 | epoch=1.5843
[train] step=742 | loss=0.3238 | lr=5.25e-05 | epoch=1.5864
[train] step=743 | loss=0.3031 | lr=5.24e-05 | epoch=1.5886
[train] step=744 | loss=0.2873 | lr=5.23e-05 | epoch=1.5907
[train] step=745 | loss=0.2592 | lr=5.22e-05 | epoch=1.5928
[train] step=746 | loss=0.2953 | lr=5.21e-05 | epoch=1.5950
[train] step=747 | loss=0.3288 | lr=5.21e-05 | epoch=1.5971
[train] step=748 | loss=0.2421 | lr=5.20e-05 | epoch=1.5993
[train] step=749 | loss=0.2760 | lr=5.19e-05 | epoch=1.6014
[train] step=750 | loss=0.3093 | lr=5.18e-05 | epoch=1.6035
[train] step=751 | loss=0.3024 | lr=5.17e-05 | epoch=1.6057
[train] step=752 | loss=0.3213 | lr=5.17e-05 | epoch=1.6078
[train] step=753 | loss=0.3226 | lr=5.16e-05 | epoch=1.6100
[train] step=754 | loss=0.2921 | lr=5.15e-05 | epoch=1.6121
[train] step=755 | loss=0.2946 | lr=5.14e-05 | epoch=1.6142
[train] step=756 | loss=0.2884 | lr=5.13e-05 | epoch=1.6164
[train] step=757 | loss=0.2797 | lr=5.13e-05 | epoch=1.6185
[train] step=758 | loss=0.2721 | lr=5.12e-05 | epoch=1.6207
[train] step=759 | loss=0.2894 | lr=5.11e-05 | epoch=1.6228
[train] step=760 | loss=0.2531 | lr=5.10e-05 | epoch=1.6249
[train] step=761 | loss=0.2854 | lr=5.09e-05 | epoch=1.6271
[train] step=762 | loss=0.2787 | lr=5.09e-05 | epoch=1.6292
[train] step=763 | loss=0.2936 | lr=5.08e-05 | epoch=1.6314
[train] step=764 | loss=0.3316 | lr=5.07e-05 | epoch=1.6335
[train] step=765 | loss=0.2635 | lr=5.06e-05 | epoch=1.6356
[train] step=766 | loss=0.3403 | lr=5.06e-05 | epoch=1.6378
[train] step=767 | loss=0.3070 | lr=5.05e-05 | epoch=1.6399
[train] step=768 | loss=0.2528 | lr=5.04e-05 | epoch=1.6421
[train] step=769 | loss=0.3170 | lr=5.03e-05 | epoch=1.6442
[train] step=770 | loss=0.2509 | lr=5.02e-05 | epoch=1.6463
[train] step=771 | loss=0.2927 | lr=5.02e-05 | epoch=1.6485
[train] step=772 | loss=0.2459 | lr=5.01e-05 | epoch=1.6506
[train] step=773 | loss=0.2566 | lr=5.00e-05 | epoch=1.6528
[train] step=774 | loss=0.2481 | lr=4.99e-05 | epoch=1.6549
[train] step=775 | loss=0.3017 | lr=4.98e-05 | epoch=1.6570
[train] step=776 | loss=0.2513 | lr=4.98e-05 | epoch=1.6592
[train] step=777 | loss=0.3077 | lr=4.97e-05 | epoch=1.6613
[train] step=778 | loss=0.2972 | lr=4.96e-05 | epoch=1.6635
[train] step=779 | loss=0.2964 | lr=4.95e-05 | epoch=1.6656
[train] step=780 | loss=0.3351 | lr=4.94e-05 | epoch=1.6677
[train] step=781 | loss=0.3098 | lr=4.94e-05 | epoch=1.6699
[train] step=782 | loss=0.2585 | lr=4.93e-05 | epoch=1.6720
[train] step=783 | loss=0.2985 | lr=4.92e-05 | epoch=1.6742
[train] step=784 | loss=0.2898 | lr=4.91e-05 | epoch=1.6763
[train] step=785 | loss=0.2547 | lr=4.91e-05 | epoch=1.6784
[train] step=786 | loss=0.2993 | lr=4.90e-05 | epoch=1.6806
[train] step=787 | loss=0.2643 | lr=4.89e-05 | epoch=1.6827
[train] step=788 | loss=0.3201 | lr=4.88e-05 | epoch=1.6849
[train] step=789 | loss=0.3006 | lr=4.87e-05 | epoch=1.6870
[train] step=790 | loss=0.2757 | lr=4.87e-05 | epoch=1.6891
[train] step=791 | loss=0.2664 | lr=4.86e-05 | epoch=1.6913
[train] step=792 | loss=0.2797 | lr=4.85e-05 | epoch=1.6934
[train] step=793 | loss=0.2835 | lr=4.84e-05 | epoch=1.6956
[train] step=794 | loss=0.3010 | lr=4.83e-05 | epoch=1.6977
[train] step=795 | loss=0.2878 | lr=4.83e-05 | epoch=1.6998
[train] step=796 | loss=0.3487 | lr=4.82e-05 | epoch=1.7020
[train] step=797 | loss=0.2888 | lr=4.81e-05 | epoch=1.7041
[train] step=798 | loss=0.2968 | lr=4.80e-05 | epoch=1.7063
[train] step=799 | loss=0.2934 | lr=4.79e-05 | epoch=1.7084
[train] step=800 | loss=0.3052 | lr=4.79e-05 | epoch=1.7105
[train] step=801 | loss=0.3087 | lr=4.78e-05 | epoch=1.7127
[train] step=802 | loss=0.2834 | lr=4.77e-05 | epoch=1.7148
[train] step=803 | loss=0.3592 | lr=4.76e-05 | epoch=1.7170
[train] step=804 | loss=0.2721 | lr=4.75e-05 | epoch=1.7191
[train] step=805 | loss=0.2674 | lr=4.75e-05 | epoch=1.7212
[train] step=806 | loss=0.2822 | lr=4.74e-05 | epoch=1.7234
[train] step=807 | loss=0.2980 | lr=4.73e-05 | epoch=1.7255
[train] step=808 | loss=0.2408 | lr=4.72e-05 | epoch=1.7277
[train] step=809 | loss=0.2642 | lr=4.72e-05 | epoch=1.7298
[train] step=810 | loss=0.2708 | lr=4.71e-05 | epoch=1.7319
[train] step=811 | loss=0.2731 | lr=4.70e-05 | epoch=1.7341
[train] step=812 | loss=0.2960 | lr=4.69e-05 | epoch=1.7362
[train] step=813 | loss=0.2833 | lr=4.68e-05 | epoch=1.7384
[train] step=814 | loss=0.2394 | lr=4.68e-05 | epoch=1.7405
[train] step=815 | loss=0.2417 | lr=4.67e-05 | epoch=1.7426
[train] step=816 | loss=0.3327 | lr=4.66e-05 | epoch=1.7448
[train] step=817 | loss=0.2973 | lr=4.65e-05 | epoch=1.7469
[train] step=818 | loss=0.3329 | lr=4.64e-05 | epoch=1.7491
[train] step=819 | loss=0.2667 | lr=4.64e-05 | epoch=1.7512
[train] step=820 | loss=0.2848 | lr=4.63e-05 | epoch=1.7533
[train] step=821 | loss=0.3507 | lr=4.62e-05 | epoch=1.7555
[train] step=822 | loss=0.2526 | lr=4.61e-05 | epoch=1.7576
[train] step=823 | loss=0.3315 | lr=4.60e-05 | epoch=1.7598
[train] step=824 | loss=0.2685 | lr=4.60e-05 | epoch=1.7619
[train] step=825 | loss=0.3234 | lr=4.59e-05 | epoch=1.7640
[train] step=826 | loss=0.2618 | lr=4.58e-05 | epoch=1.7662
[train] step=827 | loss=0.2859 | lr=4.57e-05 | epoch=1.7683
[train] step=828 | loss=0.3001 | lr=4.56e-05 | epoch=1.7705
[train] step=829 | loss=0.2455 | lr=4.56e-05 | epoch=1.7726
[train] step=830 | loss=0.2968 | lr=4.55e-05 | epoch=1.7747
[train] step=831 | loss=0.2549 | lr=4.54e-05 | epoch=1.7769
[train] step=832 | loss=0.3140 | lr=4.53e-05 | epoch=1.7790
[train] step=833 | loss=0.3136 | lr=4.53e-05 | epoch=1.7812
[train] step=834 | loss=0.2586 | lr=4.52e-05 | epoch=1.7833
[train] step=835 | loss=0.3333 | lr=4.51e-05 | epoch=1.7854
[train] step=836 | loss=0.2772 | lr=4.50e-05 | epoch=1.7876
[train] step=837 | loss=0.2997 | lr=4.49e-05 | epoch=1.7897
[train] step=838 | loss=0.3398 | lr=4.49e-05 | epoch=1.7919
[train] step=839 | loss=0.2903 | lr=4.48e-05 | epoch=1.7940
[train] step=840 | loss=0.2780 | lr=4.47e-05 | epoch=1.7961
[train] step=841 | loss=0.2618 | lr=4.46e-05 | epoch=1.7983
[train] step=842 | loss=0.2969 | lr=4.45e-05 | epoch=1.8004
[train] step=843 | loss=0.2504 | lr=4.45e-05 | epoch=1.8026
[train] step=844 | loss=0.2664 | lr=4.44e-05 | epoch=1.8047
[train] step=845 | loss=0.3036 | lr=4.43e-05 | epoch=1.8068
[train] step=846 | loss=0.2810 | lr=4.42e-05 | epoch=1.8090
[train] step=847 | loss=0.2584 | lr=4.41e-05 | epoch=1.8111
[train] step=848 | loss=0.2310 | lr=4.41e-05 | epoch=1.8133
[train] step=849 | loss=0.2290 | lr=4.40e-05 | epoch=1.8154
[train] step=850 | loss=0.3031 | lr=4.39e-05 | epoch=1.8175
[train] step=851 | loss=0.3010 | lr=4.38e-05 | epoch=1.8197
[train] step=852 | loss=0.2531 | lr=4.37e-05 | epoch=1.8218
[train] step=853 | loss=0.3230 | lr=4.37e-05 | epoch=1.8240
[train] step=854 | loss=0.2742 | lr=4.36e-05 | epoch=1.8261
[train] step=855 | loss=0.2973 | lr=4.35e-05 | epoch=1.8283
[train] step=856 | loss=0.3532 | lr=4.34e-05 | epoch=1.8304
[train] step=857 | loss=0.2863 | lr=4.34e-05 | epoch=1.8325
[train] step=858 | loss=0.2369 | lr=4.33e-05 | epoch=1.8347
[train] step=859 | loss=0.2887 | lr=4.32e-05 | epoch=1.8368
[train] step=860 | loss=0.3115 | lr=4.31e-05 | epoch=1.8390
[train] step=861 | loss=0.2647 | lr=4.30e-05 | epoch=1.8411
[train] step=862 | loss=0.2507 | lr=4.30e-05 | epoch=1.8432
[train] step=863 | loss=0.2845 | lr=4.29e-05 | epoch=1.8454
[train] step=864 | loss=0.3141 | lr=4.28e-05 | epoch=1.8475
[train] step=865 | loss=0.2888 | lr=4.27e-05 | epoch=1.8497
[train] step=866 | loss=0.2829 | lr=4.26e-05 | epoch=1.8518
[train] step=867 | loss=0.2855 | lr=4.26e-05 | epoch=1.8539
[train] step=868 | loss=0.2274 | lr=4.25e-05 | epoch=1.8561
[train] step=869 | loss=0.2942 | lr=4.24e-05 | epoch=1.8582
[train] step=870 | loss=0.2989 | lr=4.23e-05 | epoch=1.8604
[train] step=871 | loss=0.3059 | lr=4.22e-05 | epoch=1.8625
[train] step=872 | loss=0.3524 | lr=4.22e-05 | epoch=1.8646
[train] step=873 | loss=0.2707 | lr=4.21e-05 | epoch=1.8668
[train] step=874 | loss=0.2896 | lr=4.20e-05 | epoch=1.8689
[train] step=875 | loss=0.2615 | lr=4.19e-05 | epoch=1.8711
[train] step=876 | loss=0.3163 | lr=4.19e-05 | epoch=1.8732
[train] step=877 | loss=0.3140 | lr=4.18e-05 | epoch=1.8753
[train] step=878 | loss=0.2701 | lr=4.17e-05 | epoch=1.8775
[train] step=879 | loss=0.2724 | lr=4.16e-05 | epoch=1.8796
[train] step=880 | loss=0.3245 | lr=4.15e-05 | epoch=1.8818
[train] step=881 | loss=0.2740 | lr=4.15e-05 | epoch=1.8839
[train] step=882 | loss=0.3218 | lr=4.14e-05 | epoch=1.8860
[train] step=883 | loss=0.2675 | lr=4.13e-05 | epoch=1.8882
[train] step=884 | loss=0.3208 | lr=4.12e-05 | epoch=1.8903
[train] step=885 | loss=0.3369 | lr=4.11e-05 | epoch=1.8925
[train] step=886 | loss=0.2518 | lr=4.11e-05 | epoch=1.8946
[train] step=887 | loss=0.3285 | lr=4.10e-05 | epoch=1.8967
[train] step=888 | loss=0.3323 | lr=4.09e-05 | epoch=1.8989
[train] step=889 | loss=0.3021 | lr=4.08e-05 | epoch=1.9010
[train] step=890 | loss=0.3027 | lr=4.07e-05 | epoch=1.9032
[train] step=891 | loss=0.2754 | lr=4.07e-05 | epoch=1.9053
[train] step=892 | loss=0.2447 | lr=4.06e-05 | epoch=1.9074
[train] step=893 | loss=0.2933 | lr=4.05e-05 | epoch=1.9096
[train] step=894 | loss=0.3244 | lr=4.04e-05 | epoch=1.9117
[train] step=895 | loss=0.3044 | lr=4.03e-05 | epoch=1.9139
[train] step=896 | loss=0.2140 | lr=4.03e-05 | epoch=1.9160
[train] step=897 | loss=0.2792 | lr=4.02e-05 | epoch=1.9181
[train] step=898 | loss=0.3163 | lr=4.01e-05 | epoch=1.9203
[train] step=899 | loss=0.3022 | lr=4.00e-05 | epoch=1.9224
[train] step=900 | loss=0.3369 | lr=4.00e-05 | epoch=1.9246
[train] step=901 | loss=0.2684 | lr=3.99e-05 | epoch=1.9267
[train] step=902 | loss=0.2836 | lr=3.98e-05 | epoch=1.9288
[train] step=903 | loss=0.2456 | lr=3.97e-05 | epoch=1.9310
[train] step=904 | loss=0.2913 | lr=3.96e-05 | epoch=1.9331
[train] step=905 | loss=0.3182 | lr=3.96e-05 | epoch=1.9353
[train] step=906 | loss=0.3121 | lr=3.95e-05 | epoch=1.9374
[train] step=907 | loss=0.2738 | lr=3.94e-05 | epoch=1.9395
[train] step=908 | loss=0.2821 | lr=3.93e-05 | epoch=1.9417
[train] step=909 | loss=0.3342 | lr=3.92e-05 | epoch=1.9438
[train] step=910 | loss=0.2882 | lr=3.92e-05 | epoch=1.9460
[train] step=911 | loss=0.2963 | lr=3.91e-05 | epoch=1.9481
[train] step=912 | loss=0.3039 | lr=3.90e-05 | epoch=1.9502
[train] step=913 | loss=0.3023 | lr=3.89e-05 | epoch=1.9524
[train] step=914 | loss=0.2607 | lr=3.88e-05 | epoch=1.9545
[train] step=915 | loss=0.2835 | lr=3.88e-05 | epoch=1.9567
[train] step=916 | loss=0.2824 | lr=3.87e-05 | epoch=1.9588
[train] step=917 | loss=0.2657 | lr=3.86e-05 | epoch=1.9609
[train] step=918 | loss=0.3002 | lr=3.85e-05 | epoch=1.9631
[train] step=919 | loss=0.2866 | lr=3.84e-05 | epoch=1.9652
[train] step=920 | loss=0.2589 | lr=3.84e-05 | epoch=1.9674
[train] step=921 | loss=0.2834 | lr=3.83e-05 | epoch=1.9695
[train] step=922 | loss=0.2939 | lr=3.82e-05 | epoch=1.9716
[train] step=923 | loss=0.2431 | lr=3.81e-05 | epoch=1.9738
[train] step=924 | loss=0.2818 | lr=3.81e-05 | epoch=1.9759
[train] step=925 | loss=0.2881 | lr=3.80e-05 | epoch=1.9781
[train] step=926 | loss=0.2759 | lr=3.79e-05 | epoch=1.9802
[train] step=927 | loss=0.2973 | lr=3.78e-05 | epoch=1.9823
[train] step=928 | loss=0.2988 | lr=3.77e-05 | epoch=1.9845
[train] step=929 | loss=0.3261 | lr=3.77e-05 | epoch=1.9866
[train] step=930 | loss=0.3017 | lr=3.76e-05 | epoch=1.9888
[train] step=931 | loss=0.2789 | lr=3.75e-05 | epoch=1.9909
[train] step=932 | loss=0.2919 | lr=3.74e-05 | epoch=1.9930

Saving model checkpoint to output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-932
2026-04-04 13:08:27 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:08:27 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 13:08:28 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:08:28 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-932/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-932/tokenizer_config.json

[train] step=933 | loss=0.3435 | lr=3.73e-05 | epoch=1.9952
[train] step=934 | loss=0.3244 | lr=3.73e-05 | epoch=1.9973
[train] step=935 | loss=0.3097 | lr=3.72e-05 | epoch=1.9995
[train] step=936 | loss=0.1610 | lr=3.71e-05 | epoch=2.0000
[train] step=937 | loss=0.2682 | lr=3.70e-05 | epoch=2.0021
[train] step=938 | loss=0.2533 | lr=3.69e-05 | epoch=2.0043
[train] step=939 | loss=0.2144 | lr=3.69e-05 | epoch=2.0064
[train] step=940 | loss=0.2554 | lr=3.68e-05 | epoch=2.0086
[train] step=941 | loss=0.2981 | lr=3.67e-05 | epoch=2.0107
[train] step=942 | loss=0.2847 | lr=3.66e-05 | epoch=2.0128
[train] step=943 | loss=0.2830 | lr=3.66e-05 | epoch=2.0150
[train] step=944 | loss=0.3224 | lr=3.65e-05 | epoch=2.0171
[train] step=945 | loss=0.2648 | lr=3.64e-05 | epoch=2.0193
[train] step=946 | loss=0.2862 | lr=3.63e-05 | epoch=2.0214
[train] step=947 | loss=0.2741 | lr=3.62e-05 | epoch=2.0235
[train] step=948 | loss=0.2688 | lr=3.62e-05 | epoch=2.0257
[train] step=949 | loss=0.3266 | lr=3.61e-05 | epoch=2.0278
[train] step=950 | loss=0.2528 | lr=3.60e-05 | epoch=2.0300
[train] step=951 | loss=0.2656 | lr=3.59e-05 | epoch=2.0321
[train] step=952 | loss=0.2855 | lr=3.58e-05 | epoch=2.0342
[train] step=953 | loss=0.2872 | lr=3.58e-05 | epoch=2.0364
[train] step=954 | loss=0.2823 | lr=3.57e-05 | epoch=2.0385
[train] step=955 | loss=0.3906 | lr=3.56e-05 | epoch=2.0407
[train] step=956 | loss=0.2611 | lr=3.55e-05 | epoch=2.0428
[train] step=957 | loss=0.2577 | lr=3.54e-05 | epoch=2.0449
[train] step=958 | loss=0.3157 | lr=3.54e-05 | epoch=2.0471
[train] step=959 | loss=0.2445 | lr=3.53e-05 | epoch=2.0492
[train] step=960 | loss=0.2875 | lr=3.52e-05 | epoch=2.0514
[train] step=961 | loss=0.2629 | lr=3.51e-05 | epoch=2.0535
[train] step=962 | loss=0.2739 | lr=3.50e-05 | epoch=2.0556
[train] step=963 | loss=0.3008 | lr=3.50e-05 | epoch=2.0578
[train] step=964 | loss=0.2221 | lr=3.49e-05 | epoch=2.0599
[train] step=965 | loss=0.2643 | lr=3.48e-05 | epoch=2.0621
[train] step=966 | loss=0.2654 | lr=3.47e-05 | epoch=2.0642
[train] step=967 | loss=0.3085 | lr=3.47e-05 | epoch=2.0663
[train] step=968 | loss=0.3165 | lr=3.46e-05 | epoch=2.0685
[train] step=969 | loss=0.3306 | lr=3.45e-05 | epoch=2.0706
[train] step=970 | loss=0.2726 | lr=3.44e-05 | epoch=2.0728
[train] step=971 | loss=0.2870 | lr=3.43e-05 | epoch=2.0749
[train] step=972 | loss=0.3361 | lr=3.43e-05 | epoch=2.0770
[train] step=973 | loss=0.2614 | lr=3.42e-05 | epoch=2.0792
[train] step=974 | loss=0.3727 | lr=3.41e-05 | epoch=2.0813
[train] step=975 | loss=0.2443 | lr=3.40e-05 | epoch=2.0835
[train] step=976 | loss=0.2501 | lr=3.39e-05 | epoch=2.0856
[train] step=977 | loss=0.2918 | lr=3.39e-05 | epoch=2.0877
[train] step=978 | loss=0.2285 | lr=3.38e-05 | epoch=2.0899
[train] step=979 | loss=0.2582 | lr=3.37e-05 | epoch=2.0920
[train] step=980 | loss=0.2567 | lr=3.36e-05 | epoch=2.0942
[train] step=981 | loss=0.2956 | lr=3.35e-05 | epoch=2.0963
[train] step=982 | loss=0.2845 | lr=3.35e-05 | epoch=2.0984
[train] step=983 | loss=0.2893 | lr=3.34e-05 | epoch=2.1006
[train] step=984 | loss=0.2483 | lr=3.33e-05 | epoch=2.1027
[train] step=985 | loss=0.2825 | lr=3.32e-05 | epoch=2.1049
[train] step=986 | loss=0.2789 | lr=3.31e-05 | epoch=2.1070
[train] step=987 | loss=0.3405 | lr=3.31e-05 | epoch=2.1091
[train] step=988 | loss=0.2522 | lr=3.30e-05 | epoch=2.1113
[train] step=989 | loss=0.3322 | lr=3.29e-05 | epoch=2.1134
[train] step=990 | loss=0.2717 | lr=3.28e-05 | epoch=2.1156
[train] step=991 | loss=0.2552 | lr=3.28e-05 | epoch=2.1177
[train] step=992 | loss=0.2663 | lr=3.27e-05 | epoch=2.1199
[train] step=993 | loss=0.2271 | lr=3.26e-05 | epoch=2.1220
[train] step=994 | loss=0.2793 | lr=3.25e-05 | epoch=2.1241
[train] step=995 | loss=0.2865 | lr=3.24e-05 | epoch=2.1263
[train] step=996 | loss=0.2488 | lr=3.24e-05 | epoch=2.1284
[train] step=997 | loss=0.2490 | lr=3.23e-05 | epoch=2.1306
[train] step=998 | loss=0.2886 | lr=3.22e-05 | epoch=2.1327
[train] step=999 | loss=0.2939 | lr=3.21e-05 | epoch=2.1348
[train] step=1000 | loss=0.2834 | lr=3.20e-05 | epoch=2.1370
[train] step=1001 | loss=0.2303 | lr=3.20e-05 | epoch=2.1391
[train] step=1002 | loss=0.2708 | lr=3.19e-05 | epoch=2.1413
[train] step=1003 | loss=0.2599 | lr=3.18e-05 | epoch=2.1434
[train] step=1004 | loss=0.2981 | lr=3.17e-05 | epoch=2.1455
[train] step=1005 | loss=0.2871 | lr=3.16e-05 | epoch=2.1477
[train] step=1006 | loss=0.2654 | lr=3.16e-05 | epoch=2.1498
[train] step=1007 | loss=0.2722 | lr=3.15e-05 | epoch=2.1520
[train] step=1008 | loss=0.2582 | lr=3.14e-05 | epoch=2.1541
[train] step=1009 | loss=0.2567 | lr=3.13e-05 | epoch=2.1562
[train] step=1010 | loss=0.2265 | lr=3.13e-05 | epoch=2.1584
[train] step=1011 | loss=0.3644 | lr=3.12e-05 | epoch=2.1605
[train] step=1012 | loss=0.2813 | lr=3.11e-05 | epoch=2.1627
[train] step=1013 | loss=0.3020 | lr=3.10e-05 | epoch=2.1648
[train] step=1014 | loss=0.2718 | lr=3.09e-05 | epoch=2.1669
[train] step=1015 | loss=0.3056 | lr=3.09e-05 | epoch=2.1691
[train] step=1016 | loss=0.2781 | lr=3.08e-05 | epoch=2.1712
[train] step=1017 | loss=0.2838 | lr=3.07e-05 | epoch=2.1734
[train] step=1018 | loss=0.3018 | lr=3.06e-05 | epoch=2.1755
[train] step=1019 | loss=0.3223 | lr=3.05e-05 | epoch=2.1776
[train] step=1020 | loss=0.2329 | lr=3.05e-05 | epoch=2.1798
[train] step=1021 | loss=0.2604 | lr=3.04e-05 | epoch=2.1819
[train] step=1022 | loss=0.3102 | lr=3.03e-05 | epoch=2.1841
[train] step=1023 | loss=0.2562 | lr=3.02e-05 | epoch=2.1862
[train] step=1024 | loss=0.2836 | lr=3.01e-05 | epoch=2.1883
[train] step=1025 | loss=0.2988 | lr=3.01e-05 | epoch=2.1905
[train] step=1026 | loss=0.3329 | lr=3.00e-05 | epoch=2.1926
[train] step=1027 | loss=0.2972 | lr=2.99e-05 | epoch=2.1948
[train] step=1028 | loss=0.2817 | lr=2.98e-05 | epoch=2.1969
[train] step=1029 | loss=0.3467 | lr=2.97e-05 | epoch=2.1990
[train] step=1030 | loss=0.2710 | lr=2.97e-05 | epoch=2.2012
[train] step=1031 | loss=0.2887 | lr=2.96e-05 | epoch=2.2033
[train] step=1032 | loss=0.2864 | lr=2.95e-05 | epoch=2.2055
[train] step=1033 | loss=0.2872 | lr=2.94e-05 | epoch=2.2076
[train] step=1034 | loss=0.2808 | lr=2.94e-05 | epoch=2.2097
[train] step=1035 | loss=0.3235 | lr=2.93e-05 | epoch=2.2119
[train] step=1036 | loss=0.2504 | lr=2.92e-05 | epoch=2.2140
[train] step=1037 | loss=0.3156 | lr=2.91e-05 | epoch=2.2162
[train] step=1038 | loss=0.3289 | lr=2.90e-05 | epoch=2.2183
[train] step=1039 | loss=0.2793 | lr=2.90e-05 | epoch=2.2204
[train] step=1040 | loss=0.2244 | lr=2.89e-05 | epoch=2.2226
[train] step=1041 | loss=0.2312 | lr=2.88e-05 | epoch=2.2247
[train] step=1042 | loss=0.2663 | lr=2.87e-05 | epoch=2.2269
[train] step=1043 | loss=0.2568 | lr=2.86e-05 | epoch=2.2290
[train] step=1044 | loss=0.3348 | lr=2.86e-05 | epoch=2.2311
[train] step=1045 | loss=0.2581 | lr=2.85e-05 | epoch=2.2333
[train] step=1046 | loss=0.3313 | lr=2.84e-05 | epoch=2.2354
[train] step=1047 | loss=0.3051 | lr=2.83e-05 | epoch=2.2376
[train] step=1048 | loss=0.2564 | lr=2.82e-05 | epoch=2.2397
[train] step=1049 | loss=0.2925 | lr=2.82e-05 | epoch=2.2418
[train] step=1050 | loss=0.2413 | lr=2.81e-05 | epoch=2.2440
[train] step=1051 | loss=0.2495 | lr=2.80e-05 | epoch=2.2461
[train] step=1052 | loss=0.2990 | lr=2.79e-05 | epoch=2.2483
[train] step=1053 | loss=0.2665 | lr=2.78e-05 | epoch=2.2504
[train] step=1054 | loss=0.2597 | lr=2.78e-05 | epoch=2.2525
[train] step=1055 | loss=0.3033 | lr=2.77e-05 | epoch=2.2547
[train] step=1056 | loss=0.2843 | lr=2.76e-05 | epoch=2.2568
[train] step=1057 | loss=0.2337 | lr=2.75e-05 | epoch=2.2590
[train] step=1058 | loss=0.2403 | lr=2.75e-05 | epoch=2.2611
[train] step=1059 | loss=0.3089 | lr=2.74e-05 | epoch=2.2632
[train] step=1060 | loss=0.2758 | lr=2.73e-05 | epoch=2.2654
[train] step=1061 | loss=0.2756 | lr=2.72e-05 | epoch=2.2675
[train] step=1062 | loss=0.2826 | lr=2.71e-05 | epoch=2.2697
[train] step=1063 | loss=0.2230 | lr=2.71e-05 | epoch=2.2718
[train] step=1064 | loss=0.2573 | lr=2.70e-05 | epoch=2.2739
[train] step=1065 | loss=0.2490 | lr=2.69e-05 | epoch=2.2761
[train] step=1066 | loss=0.2682 | lr=2.68e-05 | epoch=2.2782
[train] step=1067 | loss=0.2508 | lr=2.67e-05 | epoch=2.2804
[train] step=1068 | loss=0.3042 | lr=2.67e-05 | epoch=2.2825
[train] step=1069 | loss=0.2261 | lr=2.66e-05 | epoch=2.2846
[train] step=1070 | loss=0.2860 | lr=2.65e-05 | epoch=2.2868
[train] step=1071 | loss=0.2819 | lr=2.64e-05 | epoch=2.2889
[train] step=1072 | loss=0.2317 | lr=2.63e-05 | epoch=2.2911
[train] step=1073 | loss=0.2518 | lr=2.63e-05 | epoch=2.2932
[train] step=1074 | loss=0.2512 | lr=2.62e-05 | epoch=2.2953
[train] step=1075 | loss=0.3175 | lr=2.61e-05 | epoch=2.2975
[train] step=1076 | loss=0.2811 | lr=2.60e-05 | epoch=2.2996
[train] step=1077 | loss=0.2455 | lr=2.59e-05 | epoch=2.3018
[train] step=1078 | loss=0.2578 | lr=2.59e-05 | epoch=2.3039
[train] step=1079 | loss=0.3175 | lr=2.58e-05 | epoch=2.3060
[train] step=1080 | loss=0.2604 | lr=2.57e-05 | epoch=2.3082
[train] step=1081 | loss=0.3402 | lr=2.56e-05 | epoch=2.3103
[train] step=1082 | loss=0.3071 | lr=2.56e-05 | epoch=2.3125
[train] step=1083 | loss=0.3025 | lr=2.55e-05 | epoch=2.3146
[train] step=1084 | loss=0.2411 | lr=2.54e-05 | epoch=2.3167
[train] step=1085 | loss=0.2791 | lr=2.53e-05 | epoch=2.3189
[train] step=1086 | loss=0.2785 | lr=2.52e-05 | epoch=2.3210
[train] step=1087 | loss=0.3065 | lr=2.52e-05 | epoch=2.3232
[train] step=1088 | loss=0.2988 | lr=2.51e-05 | epoch=2.3253
[train] step=1089 | loss=0.2565 | lr=2.50e-05 | epoch=2.3274
[train] step=1090 | loss=0.2903 | lr=2.49e-05 | epoch=2.3296
[train] step=1091 | loss=0.2877 | lr=2.48e-05 | epoch=2.3317
[train] step=1092 | loss=0.2885 | lr=2.48e-05 | epoch=2.3339
[train] step=1093 | loss=0.2584 | lr=2.47e-05 | epoch=2.3360
[train] step=1094 | loss=0.2905 | lr=2.46e-05 | epoch=2.3381
[train] step=1095 | loss=0.2999 | lr=2.45e-05 | epoch=2.3403
[train] step=1096 | loss=0.2653 | lr=2.44e-05 | epoch=2.3424
[train] step=1097 | loss=0.3025 | lr=2.44e-05 | epoch=2.3446
[train] step=1098 | loss=0.2734 | lr=2.43e-05 | epoch=2.3467
[train] step=1099 | loss=0.2735 | lr=2.42e-05 | epoch=2.3488
[train] step=1100 | loss=0.2590 | lr=2.41e-05 | epoch=2.3510
[train] step=1101 | loss=0.3001 | lr=2.41e-05 | epoch=2.3531
[train] step=1102 | loss=0.2745 | lr=2.40e-05 | epoch=2.3553
[train] step=1103 | loss=0.2546 | lr=2.39e-05 | epoch=2.3574
[train] step=1104 | loss=0.2865 | lr=2.38e-05 | epoch=2.3596
[train] step=1105 | loss=0.2541 | lr=2.37e-05 | epoch=2.3617
[train] step=1106 | loss=0.3619 | lr=2.37e-05 | epoch=2.3638
[train] step=1107 | loss=0.2833 | lr=2.36e-05 | epoch=2.3660
[train] step=1108 | loss=0.2847 | lr=2.35e-05 | epoch=2.3681
[train] step=1109 | loss=0.3050 | lr=2.34e-05 | epoch=2.3703
[train] step=1110 | loss=0.2632 | lr=2.33e-05 | epoch=2.3724
[train] step=1111 | loss=0.2944 | lr=2.33e-05 | epoch=2.3745
[train] step=1112 | loss=0.2603 | lr=2.32e-05 | epoch=2.3767
[train] step=1113 | loss=0.3331 | lr=2.31e-05 | epoch=2.3788
[train] step=1114 | loss=0.3051 | lr=2.30e-05 | epoch=2.3810
[train] step=1115 | loss=0.2331 | lr=2.29e-05 | epoch=2.3831
[train] step=1116 | loss=0.3202 | lr=2.29e-05 | epoch=2.3852
[train] step=1117 | loss=0.2763 | lr=2.28e-05 | epoch=2.3874
[train] step=1118 | loss=0.2662 | lr=2.27e-05 | epoch=2.3895
[train] step=1119 | loss=0.2912 | lr=2.26e-05 | epoch=2.3917
[train] step=1120 | loss=0.2749 | lr=2.25e-05 | epoch=2.3938
[train] step=1121 | loss=0.2817 | lr=2.25e-05 | epoch=2.3959
[train] step=1122 | loss=0.2841 | lr=2.24e-05 | epoch=2.3981
[train] step=1123 | loss=0.3170 | lr=2.23e-05 | epoch=2.4002
[train] step=1124 | loss=0.2844 | lr=2.22e-05 | epoch=2.4024
[train] step=1125 | loss=0.2475 | lr=2.22e-05 | epoch=2.4045
[train] step=1126 | loss=0.2502 | lr=2.21e-05 | epoch=2.4066
[train] step=1127 | loss=0.2686 | lr=2.20e-05 | epoch=2.4088
[train] step=1128 | loss=0.2682 | lr=2.19e-05 | epoch=2.4109
[train] step=1129 | loss=0.2651 | lr=2.18e-05 | epoch=2.4131
[train] step=1130 | loss=0.2641 | lr=2.18e-05 | epoch=2.4152
[train] step=1131 | loss=0.3010 | lr=2.17e-05 | epoch=2.4173
[train] step=1132 | loss=0.2438 | lr=2.16e-05 | epoch=2.4195
[train] step=1133 | loss=0.2648 | lr=2.15e-05 | epoch=2.4216
[train] step=1134 | loss=0.2661 | lr=2.14e-05 | epoch=2.4238
[train] step=1135 | loss=0.3171 | lr=2.14e-05 | epoch=2.4259
[train] step=1136 | loss=0.2775 | lr=2.13e-05 | epoch=2.4280
[train] step=1137 | loss=0.2478 | lr=2.12e-05 | epoch=2.4302
[train] step=1138 | loss=0.2845 | lr=2.11e-05 | epoch=2.4323
[train] step=1139 | loss=0.2762 | lr=2.10e-05 | epoch=2.4345
[train] step=1140 | loss=0.3042 | lr=2.10e-05 | epoch=2.4366
[train] step=1141 | loss=0.3155 | lr=2.09e-05 | epoch=2.4387
[train] step=1142 | loss=0.2582 | lr=2.08e-05 | epoch=2.4409
[train] step=1143 | loss=0.2651 | lr=2.07e-05 | epoch=2.4430
[train] step=1144 | loss=0.2709 | lr=2.06e-05 | epoch=2.4452
[train] step=1145 | loss=0.2480 | lr=2.06e-05 | epoch=2.4473
[train] step=1146 | loss=0.2470 | lr=2.05e-05 | epoch=2.4494
[train] step=1147 | loss=0.2792 | lr=2.04e-05 | epoch=2.4516
[train] step=1148 | loss=0.3797 | lr=2.03e-05 | epoch=2.4537
[train] step=1149 | loss=0.2849 | lr=2.03e-05 | epoch=2.4559
[train] step=1150 | loss=0.2702 | lr=2.02e-05 | epoch=2.4580
[train] step=1151 | loss=0.2949 | lr=2.01e-05 | epoch=2.4601
[train] step=1152 | loss=0.2638 | lr=2.00e-05 | epoch=2.4623
[train] step=1153 | loss=0.3031 | lr=1.99e-05 | epoch=2.4644
[train] step=1154 | loss=0.3024 | lr=1.99e-05 | epoch=2.4666
[train] step=1155 | loss=0.2432 | lr=1.98e-05 | epoch=2.4687
[train] step=1156 | loss=0.2972 | lr=1.97e-05 | epoch=2.4708
[train] step=1157 | loss=0.2860 | lr=1.96e-05 | epoch=2.4730
[train] step=1158 | loss=0.2544 | lr=1.95e-05 | epoch=2.4751
[train] step=1159 | loss=0.2922 | lr=1.95e-05 | epoch=2.4773
[train] step=1160 | loss=0.2612 | lr=1.94e-05 | epoch=2.4794
[train] step=1161 | loss=0.3034 | lr=1.93e-05 | epoch=2.4815
[train] step=1162 | loss=0.2632 | lr=1.92e-05 | epoch=2.4837
[train] step=1163 | loss=0.2789 | lr=1.91e-05 | epoch=2.4858
[train] step=1164 | loss=0.2449 | lr=1.91e-05 | epoch=2.4880
[train] step=1165 | loss=0.2529 | lr=1.90e-05 | epoch=2.4901

Saving model checkpoint to output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1165
2026-04-04 13:11:56 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:11:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 13:11:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:11:57 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1165/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1165/tokenizer_config.json

[train] step=1166 | loss=0.2830 | lr=1.89e-05 | epoch=2.4922
[train] step=1167 | loss=0.2600 | lr=1.88e-05 | epoch=2.4944
[train] step=1168 | loss=0.2616 | lr=1.88e-05 | epoch=2.4965
[train] step=1169 | loss=0.3470 | lr=1.87e-05 | epoch=2.4987
[train] step=1170 | loss=0.2451 | lr=1.86e-05 | epoch=2.5008
[train] step=1171 | loss=0.2606 | lr=1.85e-05 | epoch=2.5029
[train] step=1172 | loss=0.2827 | lr=1.84e-05 | epoch=2.5051
[train] step=1173 | loss=0.2315 | lr=1.84e-05 | epoch=2.5072
[train] step=1174 | loss=0.2565 | lr=1.83e-05 | epoch=2.5094
[train] step=1175 | loss=0.2408 | lr=1.82e-05 | epoch=2.5115
[train] step=1176 | loss=0.2982 | lr=1.81e-05 | epoch=2.5136
[train] step=1177 | loss=0.3138 | lr=1.80e-05 | epoch=2.5158
[train] step=1178 | loss=0.2604 | lr=1.80e-05 | epoch=2.5179
[train] step=1179 | loss=0.2654 | lr=1.79e-05 | epoch=2.5201
[train] step=1180 | loss=0.2773 | lr=1.78e-05 | epoch=2.5222
[train] step=1181 | loss=0.3287 | lr=1.77e-05 | epoch=2.5243
[train] step=1182 | loss=0.2457 | lr=1.76e-05 | epoch=2.5265
[train] step=1183 | loss=0.3182 | lr=1.76e-05 | epoch=2.5286
[train] step=1184 | loss=0.2858 | lr=1.75e-05 | epoch=2.5308
[train] step=1185 | loss=0.2952 | lr=1.74e-05 | epoch=2.5329
[train] step=1186 | loss=0.2726 | lr=1.73e-05 | epoch=2.5350
[train] step=1187 | loss=0.2837 | lr=1.72e-05 | epoch=2.5372
[train] step=1188 | loss=0.2603 | lr=1.72e-05 | epoch=2.5393
[train] step=1189 | loss=0.2704 | lr=1.71e-05 | epoch=2.5415
[train] step=1190 | loss=0.2796 | lr=1.70e-05 | epoch=2.5436
[train] step=1191 | loss=0.3346 | lr=1.69e-05 | epoch=2.5457
[train] step=1192 | loss=0.2433 | lr=1.69e-05 | epoch=2.5479
[train] step=1193 | loss=0.2158 | lr=1.68e-05 | epoch=2.5500
[train] step=1194 | loss=0.2837 | lr=1.67e-05 | epoch=2.5522
[train] step=1195 | loss=0.2907 | lr=1.66e-05 | epoch=2.5543
[train] step=1196 | loss=0.2358 | lr=1.65e-05 | epoch=2.5564
[train] step=1197 | loss=0.2849 | lr=1.65e-05 | epoch=2.5586
[train] step=1198 | loss=0.2758 | lr=1.64e-05 | epoch=2.5607
[train] step=1199 | loss=0.2414 | lr=1.63e-05 | epoch=2.5629
[train] step=1200 | loss=0.2722 | lr=1.62e-05 | epoch=2.5650
[train] step=1201 | loss=0.2712 | lr=1.61e-05 | epoch=2.5671
[train] step=1202 | loss=0.3302 | lr=1.61e-05 | epoch=2.5693
[train] step=1203 | loss=0.2852 | lr=1.60e-05 | epoch=2.5714
[train] step=1204 | loss=0.2929 | lr=1.59e-05 | epoch=2.5736
[train] step=1205 | loss=0.2697 | lr=1.58e-05 | epoch=2.5757
[train] step=1206 | loss=0.2488 | lr=1.57e-05 | epoch=2.5778
[train] step=1207 | loss=0.2820 | lr=1.57e-05 | epoch=2.5800
[train] step=1208 | loss=0.2499 | lr=1.56e-05 | epoch=2.5821
[train] step=1209 | loss=0.2979 | lr=1.55e-05 | epoch=2.5843
[train] step=1210 | loss=0.2686 | lr=1.54e-05 | epoch=2.5864
[train] step=1211 | loss=0.3103 | lr=1.53e-05 | epoch=2.5886
[train] step=1212 | loss=0.3093 | lr=1.53e-05 | epoch=2.5907
[train] step=1213 | loss=0.2558 | lr=1.52e-05 | epoch=2.5928
[train] step=1214 | loss=0.2430 | lr=1.51e-05 | epoch=2.5950
[train] step=1215 | loss=0.2765 | lr=1.50e-05 | epoch=2.5971
[train] step=1216 | loss=0.3354 | lr=1.50e-05 | epoch=2.5993
[train] step=1217 | loss=0.2837 | lr=1.49e-05 | epoch=2.6014
[train] step=1218 | loss=0.2678 | lr=1.48e-05 | epoch=2.6035
[train] step=1219 | loss=0.2771 | lr=1.47e-05 | epoch=2.6057
[train] step=1220 | loss=0.2434 | lr=1.46e-05 | epoch=2.6078
[train] step=1221 | loss=0.3117 | lr=1.46e-05 | epoch=2.6100
[train] step=1222 | loss=0.3000 | lr=1.45e-05 | epoch=2.6121
[train] step=1223 | loss=0.2883 | lr=1.44e-05 | epoch=2.6142
[train] step=1224 | loss=0.2264 | lr=1.43e-05 | epoch=2.6164
[train] step=1225 | loss=0.2531 | lr=1.42e-05 | epoch=2.6185
[train] step=1226 | loss=0.2491 | lr=1.42e-05 | epoch=2.6207
[train] step=1227 | loss=0.2627 | lr=1.41e-05 | epoch=2.6228
[train] step=1228 | loss=0.2842 | lr=1.40e-05 | epoch=2.6249
[train] step=1229 | loss=0.2703 | lr=1.39e-05 | epoch=2.6271
[train] step=1230 | loss=0.2718 | lr=1.38e-05 | epoch=2.6292
[train] step=1231 | loss=0.2118 | lr=1.38e-05 | epoch=2.6314
[train] step=1232 | loss=0.2872 | lr=1.37e-05 | epoch=2.6335
[train] step=1233 | loss=0.3102 | lr=1.36e-05 | epoch=2.6356
[train] step=1234 | loss=0.3008 | lr=1.35e-05 | epoch=2.6378
[train] step=1235 | loss=0.2936 | lr=1.34e-05 | epoch=2.6399
[train] step=1236 | loss=0.2583 | lr=1.34e-05 | epoch=2.6421
[train] step=1237 | loss=0.2694 | lr=1.33e-05 | epoch=2.6442
[train] step=1238 | loss=0.2591 | lr=1.32e-05 | epoch=2.6463
[train] step=1239 | loss=0.3036 | lr=1.31e-05 | epoch=2.6485
[train] step=1240 | loss=0.2622 | lr=1.31e-05 | epoch=2.6506
[train] step=1241 | loss=0.2686 | lr=1.30e-05 | epoch=2.6528
[train] step=1242 | loss=0.3615 | lr=1.29e-05 | epoch=2.6549
[train] step=1243 | loss=0.2494 | lr=1.28e-05 | epoch=2.6570
[train] step=1244 | loss=0.2716 | lr=1.27e-05 | epoch=2.6592
[train] step=1245 | loss=0.2870 | lr=1.27e-05 | epoch=2.6613
[train] step=1246 | loss=0.2297 | lr=1.26e-05 | epoch=2.6635
[train] step=1247 | loss=0.2793 | lr=1.25e-05 | epoch=2.6656
[train] step=1248 | loss=0.2567 | lr=1.24e-05 | epoch=2.6677
[train] step=1249 | loss=0.2448 | lr=1.23e-05 | epoch=2.6699
[train] step=1250 | loss=0.2179 | lr=1.23e-05 | epoch=2.6720
[train] step=1251 | loss=0.3146 | lr=1.22e-05 | epoch=2.6742
[train] step=1252 | loss=0.2494 | lr=1.21e-05 | epoch=2.6763
[train] step=1253 | loss=0.2805 | lr=1.20e-05 | epoch=2.6784
[train] step=1254 | loss=0.2770 | lr=1.19e-05 | epoch=2.6806
[train] step=1255 | loss=0.2467 | lr=1.19e-05 | epoch=2.6827
[train] step=1256 | loss=0.2455 | lr=1.18e-05 | epoch=2.6849
[train] step=1257 | loss=0.2494 | lr=1.17e-05 | epoch=2.6870
[train] step=1258 | loss=0.2837 | lr=1.16e-05 | epoch=2.6891
[train] step=1259 | loss=0.3003 | lr=1.16e-05 | epoch=2.6913
[train] step=1260 | loss=0.2661 | lr=1.15e-05 | epoch=2.6934
[train] step=1261 | loss=0.2581 | lr=1.14e-05 | epoch=2.6956
[train] step=1262 | loss=0.3380 | lr=1.13e-05 | epoch=2.6977
[train] step=1263 | loss=0.2405 | lr=1.12e-05 | epoch=2.6998
[train] step=1264 | loss=0.2564 | lr=1.12e-05 | epoch=2.7020
[train] step=1265 | loss=0.3221 | lr=1.11e-05 | epoch=2.7041
[train] step=1266 | loss=0.3082 | lr=1.10e-05 | epoch=2.7063
[train] step=1267 | loss=0.2802 | lr=1.09e-05 | epoch=2.7084
[train] step=1268 | loss=0.3171 | lr=1.08e-05 | epoch=2.7105
[train] step=1269 | loss=0.3055 | lr=1.08e-05 | epoch=2.7127
[train] step=1270 | loss=0.2429 | lr=1.07e-05 | epoch=2.7148
[train] step=1271 | loss=0.2487 | lr=1.06e-05 | epoch=2.7170
[train] step=1272 | loss=0.2717 | lr=1.05e-05 | epoch=2.7191
[train] step=1273 | loss=0.2828 | lr=1.04e-05 | epoch=2.7212
[train] step=1274 | loss=0.2603 | lr=1.04e-05 | epoch=2.7234
[train] step=1275 | loss=0.2862 | lr=1.03e-05 | epoch=2.7255
[train] step=1276 | loss=0.2253 | lr=1.02e-05 | epoch=2.7277
[train] step=1277 | loss=0.2781 | lr=1.01e-05 | epoch=2.7298
[train] step=1278 | loss=0.2687 | lr=1.00e-05 | epoch=2.7319
[train] step=1279 | loss=0.3128 | lr=9.97e-06 | epoch=2.7341
[train] step=1280 | loss=0.2857 | lr=9.89e-06 | epoch=2.7362
[train] step=1281 | loss=0.2531 | lr=9.81e-06 | epoch=2.7384
[train] step=1282 | loss=0.2960 | lr=9.73e-06 | epoch=2.7405
[train] step=1283 | loss=0.2709 | lr=9.65e-06 | epoch=2.7426
[train] step=1284 | loss=0.3066 | lr=9.57e-06 | epoch=2.7448
[train] step=1285 | loss=0.2588 | lr=9.49e-06 | epoch=2.7469
[train] step=1286 | loss=0.2605 | lr=9.41e-06 | epoch=2.7491
[train] step=1287 | loss=0.2588 | lr=9.34e-06 | epoch=2.7512
[train] step=1288 | loss=0.2785 | lr=9.26e-06 | epoch=2.7533
[train] step=1289 | loss=0.2564 | lr=9.18e-06 | epoch=2.7555
[train] step=1290 | loss=0.3093 | lr=9.10e-06 | epoch=2.7576
[train] step=1291 | loss=0.2220 | lr=9.02e-06 | epoch=2.7598
[train] step=1292 | loss=0.2879 | lr=8.94e-06 | epoch=2.7619
[train] step=1293 | loss=0.2527 | lr=8.86e-06 | epoch=2.7640
[train] step=1294 | loss=0.2960 | lr=8.78e-06 | epoch=2.7662
[train] step=1295 | loss=0.2653 | lr=8.70e-06 | epoch=2.7683
[train] step=1296 | loss=0.3069 | lr=8.62e-06 | epoch=2.7705
[train] step=1297 | loss=0.2756 | lr=8.54e-06 | epoch=2.7726
[train] step=1298 | loss=0.2334 | lr=8.47e-06 | epoch=2.7747
[train] step=1299 | loss=0.2742 | lr=8.39e-06 | epoch=2.7769
[train] step=1300 | loss=0.2547 | lr=8.31e-06 | epoch=2.7790
[train] step=1301 | loss=0.2688 | lr=8.23e-06 | epoch=2.7812
[train] step=1302 | loss=0.2694 | lr=8.15e-06 | epoch=2.7833
[train] step=1303 | loss=0.3288 | lr=8.07e-06 | epoch=2.7854
[train] step=1304 | loss=0.2468 | lr=7.99e-06 | epoch=2.7876
[train] step=1305 | loss=0.3166 | lr=7.91e-06 | epoch=2.7897
[train] step=1306 | loss=0.3148 | lr=7.83e-06 | epoch=2.7919
[train] step=1307 | loss=0.2460 | lr=7.75e-06 | epoch=2.7940
[train] step=1308 | loss=0.2467 | lr=7.67e-06 | epoch=2.7961
[train] step=1309 | loss=0.2731 | lr=7.59e-06 | epoch=2.7983
[train] step=1310 | loss=0.2526 | lr=7.52e-06 | epoch=2.8004
[train] step=1311 | loss=0.3058 | lr=7.44e-06 | epoch=2.8026
[train] step=1312 | loss=0.2572 | lr=7.36e-06 | epoch=2.8047
[train] step=1313 | loss=0.2801 | lr=7.28e-06 | epoch=2.8068
[train] step=1314 | loss=0.2631 | lr=7.20e-06 | epoch=2.8090
[train] step=1315 | loss=0.2712 | lr=7.12e-06 | epoch=2.8111
[train] step=1316 | loss=0.2968 | lr=7.04e-06 | epoch=2.8133
[train] step=1317 | loss=0.2951 | lr=6.96e-06 | epoch=2.8154
[train] step=1318 | loss=0.2586 | lr=6.88e-06 | epoch=2.8175
[train] step=1319 | loss=0.2328 | lr=6.80e-06 | epoch=2.8197
[train] step=1320 | loss=0.2539 | lr=6.72e-06 | epoch=2.8218
[train] step=1321 | loss=0.2655 | lr=6.65e-06 | epoch=2.8240
[train] step=1322 | loss=0.2399 | lr=6.57e-06 | epoch=2.8261
[train] step=1323 | loss=0.2340 | lr=6.49e-06 | epoch=2.8283
[train] step=1324 | loss=0.3006 | lr=6.41e-06 | epoch=2.8304
[train] step=1325 | loss=0.2599 | lr=6.33e-06 | epoch=2.8325
[train] step=1326 | loss=0.2567 | lr=6.25e-06 | epoch=2.8347
[train] step=1327 | loss=0.2913 | lr=6.17e-06 | epoch=2.8368
[train] step=1328 | loss=0.3030 | lr=6.09e-06 | epoch=2.8390
[train] step=1329 | loss=0.2953 | lr=6.01e-06 | epoch=2.8411
[train] step=1330 | loss=0.2905 | lr=5.93e-06 | epoch=2.8432
[train] step=1331 | loss=0.2345 | lr=5.85e-06 | epoch=2.8454
[train] step=1332 | loss=0.3707 | lr=5.78e-06 | epoch=2.8475
[train] step=1333 | loss=0.2879 | lr=5.70e-06 | epoch=2.8497
[train] step=1334 | loss=0.2618 | lr=5.62e-06 | epoch=2.8518
[train] step=1335 | loss=0.3342 | lr=5.54e-06 | epoch=2.8539
[train] step=1336 | loss=0.2407 | lr=5.46e-06 | epoch=2.8561
[train] step=1337 | loss=0.2949 | lr=5.38e-06 | epoch=2.8582
[train] step=1338 | loss=0.3053 | lr=5.30e-06 | epoch=2.8604
[train] step=1339 | loss=0.3364 | lr=5.22e-06 | epoch=2.8625
[train] step=1340 | loss=0.3329 | lr=5.14e-06 | epoch=2.8646
[train] step=1341 | loss=0.2372 | lr=5.06e-06 | epoch=2.8668
[train] step=1342 | loss=0.2669 | lr=4.98e-06 | epoch=2.8689
[train] step=1343 | loss=0.2879 | lr=4.91e-06 | epoch=2.8711
[train] step=1344 | loss=0.2215 | lr=4.83e-06 | epoch=2.8732
[train] step=1345 | loss=0.2601 | lr=4.75e-06 | epoch=2.8753
[train] step=1346 | loss=0.3064 | lr=4.67e-06 | epoch=2.8775
[train] step=1347 | loss=0.2969 | lr=4.59e-06 | epoch=2.8796
[train] step=1348 | loss=0.3059 | lr=4.51e-06 | epoch=2.8818
[train] step=1349 | loss=0.2292 | lr=4.43e-06 | epoch=2.8839
[train] step=1350 | loss=0.3122 | lr=4.35e-06 | epoch=2.8860
[train] step=1351 | loss=0.2899 | lr=4.27e-06 | epoch=2.8882
[train] step=1352 | loss=0.2814 | lr=4.19e-06 | epoch=2.8903
[train] step=1353 | loss=0.2877 | lr=4.11e-06 | epoch=2.8925
[train] step=1354 | loss=0.2489 | lr=4.03e-06 | epoch=2.8946
[train] step=1355 | loss=0.2873 | lr=3.96e-06 | epoch=2.8967
[train] step=1356 | loss=0.2236 | lr=3.88e-06 | epoch=2.8989
[train] step=1357 | loss=0.3026 | lr=3.80e-06 | epoch=2.9010
[train] step=1358 | loss=0.2479 | lr=3.72e-06 | epoch=2.9032
[train] step=1359 | loss=0.2682 | lr=3.64e-06 | epoch=2.9053
[train] step=1360 | loss=0.2655 | lr=3.56e-06 | epoch=2.9074
[train] step=1361 | loss=0.2617 | lr=3.48e-06 | epoch=2.9096
[train] step=1362 | loss=0.3308 | lr=3.40e-06 | epoch=2.9117
[train] step=1363 | loss=0.2411 | lr=3.32e-06 | epoch=2.9139
[train] step=1364 | loss=0.2676 | lr=3.24e-06 | epoch=2.9160
[train] step=1365 | loss=0.3112 | lr=3.16e-06 | epoch=2.9181
[train] step=1366 | loss=0.3024 | lr=3.09e-06 | epoch=2.9203
[train] step=1367 | loss=0.3091 | lr=3.01e-06 | epoch=2.9224
[train] step=1368 | loss=0.1968 | lr=2.93e-06 | epoch=2.9246
[train] step=1369 | loss=0.2424 | lr=2.85e-06 | epoch=2.9267
[train] step=1370 | loss=0.2441 | lr=2.77e-06 | epoch=2.9288
[train] step=1371 | loss=0.2040 | lr=2.69e-06 | epoch=2.9310
[train] step=1372 | loss=0.2777 | lr=2.61e-06 | epoch=2.9331
[train] step=1373 | loss=0.2818 | lr=2.53e-06 | epoch=2.9353
[train] step=1374 | loss=0.2719 | lr=2.45e-06 | epoch=2.9374
[train] step=1375 | loss=0.3074 | lr=2.37e-06 | epoch=2.9395
[train] step=1376 | loss=0.2442 | lr=2.29e-06 | epoch=2.9417
[train] step=1377 | loss=0.2705 | lr=2.22e-06 | epoch=2.9438
[train] step=1378 | loss=0.2905 | lr=2.14e-06 | epoch=2.9460
[train] step=1379 | loss=0.2565 | lr=2.06e-06 | epoch=2.9481
[train] step=1380 | loss=0.2874 | lr=1.98e-06 | epoch=2.9502
[train] step=1381 | loss=0.2875 | lr=1.90e-06 | epoch=2.9524
[train] step=1382 | loss=0.2356 | lr=1.82e-06 | epoch=2.9545
[train] step=1383 | loss=0.2286 | lr=1.74e-06 | epoch=2.9567
[train] step=1384 | loss=0.2405 | lr=1.66e-06 | epoch=2.9588
[train] step=1385 | loss=0.2655 | lr=1.58e-06 | epoch=2.9609
[train] step=1386 | loss=0.2621 | lr=1.50e-06 | epoch=2.9631
[train] step=1387 | loss=0.2840 | lr=1.42e-06 | epoch=2.9652
[train] step=1388 | loss=0.2975 | lr=1.34e-06 | epoch=2.9674
[train] step=1389 | loss=0.2975 | lr=1.27e-06 | epoch=2.9695
[train] step=1390 | loss=0.2692 | lr=1.19e-06 | epoch=2.9716
[train] step=1391 | loss=0.2759 | lr=1.11e-06 | epoch=2.9738
[train] step=1392 | loss=0.2455 | lr=1.03e-06 | epoch=2.9759
[train] step=1393 | loss=0.2232 | lr=9.49e-07 | epoch=2.9781
[train] step=1394 | loss=0.2422 | lr=8.70e-07 | epoch=2.9802
[train] step=1395 | loss=0.2228 | lr=7.91e-07 | epoch=2.9823
[train] step=1396 | loss=0.2442 | lr=7.12e-07 | epoch=2.9845
[train] step=1397 | loss=0.2779 | lr=6.33e-07 | epoch=2.9866
[train] step=1398 | loss=0.2663 | lr=5.54e-07 | epoch=2.9888

Saving model checkpoint to output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1398
2026-04-04 13:15:23 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:15:24 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 13:15:24 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:15:24 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1398/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1398/tokenizer_config.json

[train] step=1399 | loss=0.2511 | lr=4.75e-07 | epoch=2.9909
[train] step=1400 | loss=0.2961 | lr=3.96e-07 | epoch=2.9930
[train] step=1401 | loss=0.2352 | lr=3.16e-07 | epoch=2.9952
[train] step=1402 | loss=0.2627 | lr=2.37e-07 | epoch=2.9973
[train] step=1403 | loss=0.3272 | lr=1.58e-07 | epoch=2.9995
[train] step=1404 | loss=0.2123 | lr=7.91e-08 | epoch=3.0000

Saving model checkpoint to output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1404
2026-04-04 13:15:30 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:15:30 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 13:15:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:15:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1404/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/checkpoint-1404/tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=1404 | epoch=3.0000
[train] finished | global_step=1404

Saving model checkpoint to output/fine_tune/run_017_lr1e-4_r32_a64_ep3
2026-04-04 13:15:31 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:15:32 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-04 13:15:32 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-04 13:15:32 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/tokenizer_config.json
chat template saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_017_lr1e-4_r32_a64_ep3/tokenizer_config.json
2026-04-04 13:15:32 | INFO     | root | Done run 18/18: /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_017_lr1e-4_r32_a64_ep3

Wrote sweep index: /common/home/users/c/chinyee.lew.2022/output/fine_tune/sweep_index.json
Finished: total=18, executed=2, skipped=16.
Artifacts under:
  /common/home/users/c/chinyee.lew.2022/output/fine_tune