# Fine-tune (LoRA)

Fine-tunes **Qwen2.5-0.5B-Instruct** on GSM8K using LoRA. Artifacts go to `output/fine_tune/` (gitignored).

| Output | Contents |
|--------|---------|
| Cell output | tqdm bar + `[train] step=… loss=… lr=… epoch=…` per log event |
| `training_run.log` | Timestamped log, appended each run |
| `trainer_log_history.json` | Per-step `loss`, `learning_rate`, `epoch` from HF Trainer |
| `training_summary.json` | Hyperparameters + final loss / step / epoch |
| `adapter_*/`, checkpoints | Saved by HF Trainer under the run folder |

**Single run:** `RUN_HYPERPARAMETER_SWEEP = False` — uses defaults from `hyperparameters.py`.  
**Sweep:** `True` — one run per entry in `PARAM_COMBINATIONS`, each in its own subfolder (`run_000_…`).

Run cells top to bottom.

### 1 — Imports and callbacks

Imports the stack and defines `NotebookProgressCallback` (prints `[train]` lines per log event) and `LossConvergenceCallback` (early stopping). Run once per session.

In [2]:
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import torch
import transformers
from transformers import TrainerCallback

from qwen_math_flow.download_model import download_qwen_25_07b
from qwen_math_flow.load_dataset import format_gsm8k_as_chat, load_and_tokenize_math
from qwen_math_flow.lora_finetune import LossConvergenceCallback, create_lora_model, run_finetune


class NotebookProgressCallback(TrainerCallback):
    """Print one line per Trainer log so loss / lr / epoch show in the notebook while training."""

    def on_train_begin(self, args, state, control, **kwargs):
        print(
            "[train] started | "
            f"epochs={args.num_train_epochs} | log every {args.logging_steps} step(s) | "
            "progress bar + metrics lines below",
            flush=True,
        )

    def on_log(self, args, state, control, logs=None, **kwargs):
        if not logs:
            return
        parts = [f"step={state.global_step}"]
        if logs.get("loss") is not None:
            parts.append(f"loss={logs['loss']:.4f}")
        if logs.get("learning_rate") is not None:
            parts.append(f"lr={logs['learning_rate']:.2e}")
        if logs.get("epoch") is not None:
            parts.append(f"epoch={logs['epoch']:.4f}")
        print("[train] " + " | ".join(parts), flush=True)

    def on_train_end(self, args, state, control, **kwargs):
        print(f"[train] finished | global_step={state.global_step}", flush=True)

### 2 — Config

Set the output path, sweep toggle, and logging verbosity. Training defaults (LR, LoRA rank, batch size, etc.) come from `hyperparameters.py`; entries in `PARAM_COMBINATIONS` override only the keys they list.

Re-run this cell whenever you change sweep settings.

In [3]:
from itertools import product

from qwen_math_flow.hyperparameters import (
    DATASET_NAME,
    DATASET_SPLIT,
    GRADIENT_ACCUMULATION_STEPS,
    LEARNING_RATE,
    LOAD_IN_4BIT,
    LORA_ALPHA,
    LORA_R,
    MAX_LENGTH,
    MAX_TRAIN_SAMPLES,
    MODEL_CACHE_DIR,
    NUM_EPOCHS,
    PER_DEVICE_TRAIN_BATCH_SIZE,
)

OUTPUT_BASE = "output/fine_tune"

# False: one run using hyperparameters.py only. True: one run per dict in PARAM_COMBINATIONS.
RUN_HYPERPARAMETER_SWEEP = True

# Sweeps: each dict can override training keys; missing keys use hyperparameters.py defaults.
PARAM_COMBINATIONS = [
    {"learning_rate": 1e-5, "lora_r": 8,  "lora_alpha": 16, "num_epochs": 1},
    {"learning_rate": 2e-5, "lora_r": 8,  "lora_alpha": 16, "num_epochs": 2},
    {"learning_rate": 2e-5, "lora_r": 16, "lora_alpha": 32, "num_epochs": 2},
    {"learning_rate": 3e-5, "lora_r": 16, "lora_alpha": 32, "num_epochs": 3},
    {"learning_rate": 3e-5, "lora_r": 32, "lora_alpha": 64, "num_epochs": 3},
]
# Example — Cartesian grid (2×2×2 = 8 combinations). Replace PARAM_COMBINATIONS above or assign to it.
# PARAM_COMBINATIONS = [
#     {"learning_rate": lr, "lora_r": r, "lora_alpha": r * 2, "num_epochs": ep}
#     for lr, r, ep in product([1e-5, 2e-5], [8, 16], [1, 2])
# ]


def merged_training_params(overrides: dict) -> dict:
    """Defaults from hyperparameters.py, overridden by one sweep row."""
    return {
        "learning_rate": overrides.get("learning_rate", LEARNING_RATE),
        "lora_r": overrides.get("lora_r", LORA_R),
        "lora_alpha": overrides.get("lora_alpha", LORA_ALPHA),
        "num_epochs": overrides.get("num_epochs", NUM_EPOCHS),
        "per_device_train_batch_size": overrides.get(
            "per_device_train_batch_size", PER_DEVICE_TRAIN_BATCH_SIZE
        ),
        "gradient_accumulation_steps": overrides.get(
            "gradient_accumulation_steps", GRADIENT_ACCUMULATION_STEPS
        ),
        "max_length": overrides.get("max_length", MAX_LENGTH),
        "max_train_samples": overrides.get("max_train_samples", MAX_TRAIN_SAMPLES),
    }


def combination_subdir(index: int, m: dict) -> str:
    """Unique folder name for one combination."""
    lr = m["learning_rate"]
    lr_s = f"{lr:.0e}".replace("e-0", "e-").replace("e+0", "e+")
    return f"run_{index:03d}_lr{lr_s}_r{m['lora_r']}_a{m['lora_alpha']}_ep{m['num_epochs']}"


SWEEP_RUNS = PARAM_COMBINATIONS if RUN_HYPERPARAMETER_SWEEP else [{}]
NUM_COMBINATIONS = len(SWEEP_RUNS)

# Trainer: log loss / lr every N steps (1 = every step — most verbose)
LOGGING_STEPS = 1
SHOW_NOTEBOOK_LOG_LINES = True
DISABLE_TQDM = False
TRANSFORMERS_DEBUG = False

Path(OUTPUT_BASE).mkdir(parents=True, exist_ok=True)
print(f"Output base: {Path(OUTPUT_BASE).resolve()}")
print(f"RUN_HYPERPARAMETER_SWEEP={RUN_HYPERPARAMETER_SWEEP}  →  {NUM_COMBINATIONS} training run(s)")
if RUN_HYPERPARAMETER_SWEEP:
    for i, o in enumerate(PARAM_COMBINATIONS):
        print(f"  [{i}] {o}  →  {combination_subdir(i, merged_training_params(o))}")
print(
    f"LOGGING_STEPS={LOGGING_STEPS}  SHOW_NOTEBOOK_LOG_LINES={SHOW_NOTEBOOK_LOG_LINES}  "
    f"DISABLE_TQDM={DISABLE_TQDM}  TRANSFORMERS_DEBUG={TRANSFORMERS_DEBUG}"
)

Output base: /common/home/users/c/chinyee.lew.2022/output/fine_tune
RUN_HYPERPARAMETER_SWEEP=True  →  5 training run(s)
  [0] {'learning_rate': 1e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 1}  →  run_000_lr1e-5_r8_a16_ep1
  [1] {'learning_rate': 2e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 2}  →  run_001_lr2e-5_r8_a16_ep2
  [2] {'learning_rate': 2e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 2}  →  run_002_lr2e-5_r16_a32_ep2
  [3] {'learning_rate': 3e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3}  →  run_003_lr3e-5_r16_a32_ep3
  [4] {'learning_rate': 3e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3}  →  run_004_lr3e-5_r32_a64_ep3
LOGGING_STEPS=1  SHOW_NOTEBOOK_LOG_LINES=True  DISABLE_TQDM=False  TRANSFORMERS_DEBUG=False

### 3 — Train

Loads the model and data, runs `run_finetune` for each combination, and writes `training_summary.json`, `trainer_log_history.json`, and `training_run.log` per run. In sweep mode, also writes `sweep_index.json` at the top level.

Re-run config first if hyperparameters changed.

In [4]:
def _setup_run_logging(log_path: Path) -> None:
    logging.basicConfig(
        level=logging.DEBUG if TRANSFORMERS_DEBUG else logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(log_path, encoding="utf-8", mode="a"),
        ],
        force=True,
    )
    for name in ("transformers", "transformers.trainer", "qwen_math_flow.lora_finetune"):
        logging.getLogger(name).setLevel(logging.DEBUG if TRANSFORMERS_DEBUG else logging.INFO)
    logging.getLogger("datasets").setLevel(logging.WARNING)
    if TRANSFORMERS_DEBUG:
        transformers.logging.set_verbosity_debug()
    else:
        transformers.logging.set_verbosity_info()


# Early stopping based on training loss convergence.
# With ~7473 samples, effective batch=16 → ~467 steps/epoch.
# WINDOW=20 covers ~4% of one epoch — enough to confirm a real plateau, not a transient dip.
# MIN_DELTA=0.005: stop if loss hasn't dropped by more than 0.005 over those 20 log events.
EARLY_STOP_WINDOW = 20
EARLY_STOP_MIN_DELTA = 0.005

all_summaries = []

for run_index, overrides in enumerate(SWEEP_RUNS):
    merged = merged_training_params(overrides)
    out = (
        Path(OUTPUT_BASE) / combination_subdir(run_index, merged)
        if RUN_HYPERPARAMETER_SWEEP
        else Path(OUTPUT_BASE)
    )
    out.mkdir(parents=True, exist_ok=True)
    log_file = out / "training_run.log"

    print(
        f"\n=== Run {run_index + 1}/{NUM_COMBINATIONS}  {out.name}  merged={merged} ===\n",
        flush=True,
    )
    _setup_run_logging(log_file)
    logging.info("Logging to %s", log_file.resolve())

    model, tokenizer = download_qwen_25_07b(
        cache_dir=MODEL_CACHE_DIR,
        load_in_4bit=LOAD_IN_4BIT,
        device_map="auto" if LOAD_IN_4BIT else None,
    )
    tokenized_train = load_and_tokenize_math(
        tokenizer,
        name=DATASET_NAME,
        split=DATASET_SPLIT,
        max_samples=merged["max_train_samples"],
        max_length=merged["max_length"],
        message_formatter=format_gsm8k_as_chat,
    )
    cap_msg = (
        "full train split"
        if merged["max_train_samples"] is None
        else f"up to {merged['max_train_samples']} samples"
    )
    logging.info(
        "GSM8K training: %s samples (%s), %s epoch(s).",
        len(tokenized_train),
        cap_msg,
        merged["num_epochs"],
    )

    peft_model = create_lora_model(
        model,
        r=merged["lora_r"],
        lora_alpha=merged["lora_alpha"],
        use_4bit_or_8bit=LOAD_IN_4BIT,
    )
    callbacks = [LossConvergenceCallback(window=EARLY_STOP_WINDOW, min_delta=EARLY_STOP_MIN_DELTA)]
    if SHOW_NOTEBOOK_LOG_LINES:
        callbacks.append(NotebookProgressCallback())

    metrics = run_finetune(
        peft_model,
        tokenizer,
        tokenized_train,
        output_dir=str(out),
        num_epochs=merged["num_epochs"],
        per_device_train_batch_size=merged["per_device_train_batch_size"],
        gradient_accumulation_steps=merged["gradient_accumulation_steps"],
        learning_rate=merged["learning_rate"],
        logging_steps=LOGGING_STEPS,
        logging_first_step=True,
        logging_strategy="steps",
        disable_tqdm=DISABLE_TQDM,
        callbacks=callbacks,
        save_log_history_json=True,
    )

    summary = {
        "run_index": run_index,
        "run_hyperparameter_sweep": RUN_HYPERPARAMETER_SWEEP,
        "sweep_overrides": overrides,
        "merged_params": merged,
        "finished_at_utc": datetime.now(timezone.utc).isoformat(),
        "output_dir": str(out.resolve()),
        "log_files": {
            "training_run_log": str((out / "training_run.log").resolve()),
            "trainer_log_history_json": str((out / "trainer_log_history.json").resolve()),
        },
        "logging_steps": LOGGING_STEPS,
        "show_notebook_log_lines": SHOW_NOTEBOOK_LOG_LINES,
        "disable_tqdm": DISABLE_TQDM,
        "transformers_debug": TRANSFORMERS_DEBUG,
        "early_stop_window": EARLY_STOP_WINDOW,
        "early_stop_min_delta": EARLY_STOP_MIN_DELTA,
        "dataset": DATASET_NAME,
        "split": DATASET_SPLIT,
        "num_train_samples": len(tokenized_train),
        "num_epochs": merged["num_epochs"],
        "per_device_train_batch_size": merged["per_device_train_batch_size"],
        "gradient_accumulation_steps": merged["gradient_accumulation_steps"],
        "learning_rate": merged["learning_rate"],
        "max_length": merged["max_length"],
        "lora_r": merged["lora_r"],
        "lora_alpha": merged["lora_alpha"],
        "load_in_4bit": LOAD_IN_4BIT,
        "final_train_loss": metrics.get("train_loss"),
        "global_step": metrics.get("global_step"),
        "epoch": metrics.get("epoch"),
    }
    with open(out / "training_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    all_summaries.append(summary)

    logging.info("Done run %s/%s: %s", run_index + 1, NUM_COMBINATIONS, out.resolve())
    del model, peft_model, tokenizer, tokenized_train
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

if RUN_HYPERPARAMETER_SWEEP:
    sweep_index_path = Path(OUTPUT_BASE) / "sweep_index.json"
    with open(sweep_index_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "finished_at_utc": datetime.now(timezone.utc).isoformat(),
                "num_runs": NUM_COMBINATIONS,
                "runs": [
                    {
                        "output_dir": s["output_dir"],
                        "final_train_loss": s.get("final_train_loss"),
                        "merged_params": s["merged_params"],
                    }
                    for s in all_summaries
                ],
            },
            f,
            indent=2,
        )
    print(f"Wrote sweep index: {sweep_index_path.resolve()}")

print(
    f"Finished {NUM_COMBINATIONS} run(s). Artifacts under each run folder in:\n  {Path(OUTPUT_BASE).resolve()}\n"
)

=== Run 1/5  run_000_lr1e-5_r8_a16_ep1  merged={'learning_rate': 1e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 1, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-02 21:53:43 | INFO     | root | Logging to /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_000_lr1e-5_r8_a16_ep1/training_run.log
2026-04-02 21:53:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:53:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-02 21:53:44 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:53:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-04-02 21:53:44 | WARNING  | huggingface_hub.utils._http | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-04-02 21:53:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-02 21:53:44 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-02 21:53:44 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-02 21:53:44 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/vocab.json "HTTP/1.1 200 OK"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/vocab.json "HTTP/1.1 200 OK"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/merges.txt "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/merges.txt "HTTP/1.1 200 OK"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/merges.txt "HTTP/1.1 200 OK"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer.json "HTTP/1.1 200 OK"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer.json "HTTP/1.1 200 OK"
2026-04-02 21:53:45 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-04-02 21:53:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
2026-04-02 21:53:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-04-02 21:53:47 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct "HTTP/1.1 200 OK"
2026-04-02 21:53:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:53:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-02 21:53:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:53:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:53:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-02 21:53:48 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/model.safetensors "HTTP/1.1 302 Found"
2026-04-02 21:53:48 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/xet-read-token/7ae557604adf67be50417f59c2c2f167def9a775 "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 6929.50it/s]
2026-04-02 21:54:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
2026-04-02 21:54:08 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.1,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2026-04-02 21:54:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-0.5B-Instruct.
2026-04-02 21:54:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:08 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-02 21:54:08 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-02 21:54:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:54:09 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:54:10 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/datasets/openai/gsm8k/revision/740312add88f781978c0658806c59bc2815b9866 "HTTP/1.1 200 OK"
2026-04-02 21:54:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-02 21:54:10 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-02 21:54:10 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/datasets/openai/gsm8k/tree/740312add88f781978c0658806c59bc2815b9866/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-02 21:54:11 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/datasets/openai/gsm8k/tree/740312add88f781978c0658806c59bc2815b9866?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-04-02 21:54:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-02 21:54:11 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/main/train-00000-of-00001.parquet "HTTP/1.1 302 Found"
2026-04-02 21:54:11 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/datasets/openai/gsm8k/xet-read-token/740312add88f781978c0658806c59bc2815b9866 "HTTP/1.1 200 OK"
2026-04-02 21:54:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/main/test-00000-of-00001.parquet "HTTP/1.1 302 Found"
Generating train split: 100%|██████████| 7473/7473 [00:00<00:00, 483502.77 examples/s]
Generating test split: 100%|██████████| 1319/1319 [00:00<00:00, 348754.14 examples/s]
Tokenizing (num_proc=1): 100%|██████████| 7473/7473 [00:10<00:00, 746.81 examples/s]
2026-04-02 21:54:24 | INFO     | root | GSM8K training: 7473 samples (full train split), 1 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 1
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 468
  Number of trainable parameters = 1,081,344

[train] started | epochs=1 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.4261 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.5759 | lr=2.17e-07 | epoch=0.0043
[train] step=3 | loss=1.5481 | lr=4.35e-07 | epoch=0.0064
[train] step=4 | loss=1.5164 | lr=6.52e-07 | epoch=0.0086
[train] step=5 | loss=1.4368 | lr=8.70e-07 | epoch=0.0107
[train] step=6 | loss=1.4355 | lr=1.09e-06 | epoch=0.0128
[train] step=7 | loss=1.4319 | lr=1.30e-06 | epoch=0.0150
[train] step=8 | loss=1.3694 | lr=1.52e-06 | epoch=0.0171
[train] step=9 | loss=1.4893 | lr=1.74e-06 | epoch=0.0193
[train] step=10 | loss=1.5329 | lr=1.96e-06 | epoch=0.0214
[train] step=11 | loss=1.5082 | lr=2.17e-06 | epoch=0.0235
[train] step=12 | loss=1.7010 | lr=2.39e-06 | epoch=0.0257
[train] step=13 | loss=1.4807 | lr=2.61e-06 | epoch=0.0278
[train] step=14 | loss=1.5720 | lr=2.83e-06 | epoch=0.0300
[train] step=15 | loss=1.6400 | lr=3.04e-06 | epoch=0.0321
[train] step=16 | loss=1.5696 | lr=3.26e-06 | epoch=0.0342
[train] step=17 | loss=1.5681 | lr=3.48e-06 | epoch=0.0364
[train] step=18 | loss=1.4950 | lr=3.70e-06 | epoch=0.0385
[train] step=19 | loss=1.4858 | lr=3.91e-06 | epoch=0.0407

2026-04-02 21:54:46 | INFO     | qwen_math_flow.lora_finetune | LossConvergenceCallback: loss converged (improvement=-0.1757 < min_delta=0.0050) over last 20 log events — stopping early at step 20.

[train] step=20 | loss=1.6018 | lr=4.13e-06 | epoch=0.0428

Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=20 | epoch=0.0428
[train] finished | global_step=20

Saving model checkpoint to output/fine_tune/run_000_lr1e-5_r8_a16_ep1
2026-04-02 21:54:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-02 21:54:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_000_lr1e-5_r8_a16_ep1/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_000_lr1e-5_r8_a16_ep1/tokenizer_config.json
chat template saved in output/fine_tune/run_000_lr1e-5_r8_a16_ep1/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_000_lr1e-5_r8_a16_ep1/tokenizer_config.json
2026-04-02 21:54:47 | INFO     | root | Done run 1/5: /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_000_lr1e-5_r8_a16_ep1

=== Run 2/5  run_001_lr2e-5_r8_a16_ep2  merged={'learning_rate': 2e-05, 'lora_r': 8, 'lora_alpha': 16, 'num_epochs': 2, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-02 21:54:47 | INFO     | root | Logging to /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_001_lr2e-5_r8_a16_ep2/training_run.log
2026-04-02 21:54:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:54:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:47 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-02 21:54:48 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-02 21:54:48 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-02 21:54:49 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct "HTTP/1.1 200 OK"
2026-04-02 21:54:49 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:49 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:54:49 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:49 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 6890.55it/s]
2026-04-02 21:54:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.1,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2026-04-02 21:54:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-0.5B-Instruct.
2026-04-02 21:54:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:54:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-02 21:54:50 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:54:51 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:54:51 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-02 21:54:52 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-02 21:54:52 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-02 21:54:53 | INFO     | root | GSM8K training: 7473 samples (full train split), 2 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 2
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 936
  Number of trainable parameters = 1,081,344

[train] started | epochs=2 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.4261 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.5759 | lr=2.15e-07 | epoch=0.0043
[train] step=3 | loss=1.5470 | lr=4.30e-07 | epoch=0.0064
[train] step=4 | loss=1.5139 | lr=6.45e-07 | epoch=0.0086
[train] step=5 | loss=1.4383 | lr=8.60e-07 | epoch=0.0107
[train] step=6 | loss=1.4363 | lr=1.08e-06 | epoch=0.0128
[train] step=7 | loss=1.4314 | lr=1.29e-06 | epoch=0.0150
[train] step=8 | loss=1.3694 | lr=1.51e-06 | epoch=0.0171
[train] step=9 | loss=1.4885 | lr=1.72e-06 | epoch=0.0193
[train] step=10 | loss=1.5323 | lr=1.94e-06 | epoch=0.0214
[train] step=11 | loss=1.5101 | lr=2.15e-06 | epoch=0.0235
[train] step=12 | loss=1.6991 | lr=2.37e-06 | epoch=0.0257
[train] step=13 | loss=1.4816 | lr=2.58e-06 | epoch=0.0278
[train] step=14 | loss=1.5703 | lr=2.80e-06 | epoch=0.0300
[train] step=15 | loss=1.6403 | lr=3.01e-06 | epoch=0.0321
[train] step=16 | loss=1.5697 | lr=3.23e-06 | epoch=0.0342
[train] step=17 | loss=1.5707 | lr=3.44e-06 | epoch=0.0364
[train] step=18 | loss=1.4937 | lr=3.66e-06 | epoch=0.0385
[train] step=19 | loss=1.4868 | lr=3.87e-06 | epoch=0.0407

2026-04-02 21:55:12 | INFO     | qwen_math_flow.lora_finetune | LossConvergenceCallback: loss converged (improvement=-0.1776 < min_delta=0.0050) over last 20 log events — stopping early at step 20.

[train] step=20 | loss=1.6036 | lr=4.09e-06 | epoch=0.0428

Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=20 | epoch=0.0428
[train] finished | global_step=20

Saving model checkpoint to output/fine_tune/run_001_lr2e-5_r8_a16_ep2
2026-04-02 21:55:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-02 21:55:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_001_lr2e-5_r8_a16_ep2/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_001_lr2e-5_r8_a16_ep2/tokenizer_config.json
chat template saved in output/fine_tune/run_001_lr2e-5_r8_a16_ep2/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_001_lr2e-5_r8_a16_ep2/tokenizer_config.json
2026-04-02 21:55:13 | INFO     | root | Done run 2/5: /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_001_lr2e-5_r8_a16_ep2

=== Run 3/5  run_002_lr2e-5_r16_a32_ep2  merged={'learning_rate': 2e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 2, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-02 21:55:13 | INFO     | root | Logging to /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_002_lr2e-5_r16_a32_ep2/training_run.log
2026-04-02 21:55:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:55:14 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:14 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-02 21:55:14 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-02 21:55:14 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-02 21:55:15 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct "HTTP/1.1 200 OK"
2026-04-02 21:55:15 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:15 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:55:15 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:15 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 6852.47it/s]
2026-04-02 21:55:16 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:16 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.1,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2026-04-02 21:55:16 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-0.5B-Instruct.
2026-04-02 21:55:16 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:16 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-02 21:55:16 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:55:17 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:55:17 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-02 21:55:18 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-02 21:55:18 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-02 21:55:19 | INFO     | root | GSM8K training: 7473 samples (full train split), 2 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 2
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 936
  Number of trainable parameters = 2,162,688

[train] started | epochs=2 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.4261 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.5759 | lr=2.15e-07 | epoch=0.0043
[train] step=3 | loss=1.5480 | lr=4.30e-07 | epoch=0.0064
[train] step=4 | loss=1.5183 | lr=6.45e-07 | epoch=0.0086
[train] step=5 | loss=1.4344 | lr=8.60e-07 | epoch=0.0107
[train] step=6 | loss=1.4337 | lr=1.08e-06 | epoch=0.0128
[train] step=7 | loss=1.4340 | lr=1.29e-06 | epoch=0.0150
[train] step=8 | loss=1.3690 | lr=1.51e-06 | epoch=0.0171
[train] step=9 | loss=1.4877 | lr=1.72e-06 | epoch=0.0193
[train] step=10 | loss=1.5302 | lr=1.94e-06 | epoch=0.0214
[train] step=11 | loss=1.5025 | lr=2.15e-06 | epoch=0.0235
[train] step=12 | loss=1.6960 | lr=2.37e-06 | epoch=0.0257
[train] step=13 | loss=1.4761 | lr=2.58e-06 | epoch=0.0278
[train] step=14 | loss=1.5652 | lr=2.80e-06 | epoch=0.0300
[train] step=15 | loss=1.6334 | lr=3.01e-06 | epoch=0.0321
[train] step=16 | loss=1.5604 | lr=3.23e-06 | epoch=0.0342
[train] step=17 | loss=1.5545 | lr=3.44e-06 | epoch=0.0364
[train] step=18 | loss=1.4751 | lr=3.66e-06 | epoch=0.0385
[train] step=19 | loss=1.4677 | lr=3.87e-06 | epoch=0.0407

2026-04-02 21:55:38 | INFO     | qwen_math_flow.lora_finetune | LossConvergenceCallback: loss converged (improvement=-0.1514 < min_delta=0.0050) over last 20 log events — stopping early at step 20.

[train] step=20 | loss=1.5774 | lr=4.09e-06 | epoch=0.0428

Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=20 | epoch=0.0428
[train] finished | global_step=20

Saving model checkpoint to output/fine_tune/run_002_lr2e-5_r16_a32_ep2
2026-04-02 21:55:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-02 21:55:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:39 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_002_lr2e-5_r16_a32_ep2/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_002_lr2e-5_r16_a32_ep2/tokenizer_config.json
chat template saved in output/fine_tune/run_002_lr2e-5_r16_a32_ep2/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_002_lr2e-5_r16_a32_ep2/tokenizer_config.json
2026-04-02 21:55:39 | INFO     | root | Done run 3/5: /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_002_lr2e-5_r16_a32_ep2

=== Run 4/5  run_003_lr3e-5_r16_a32_ep3  merged={'learning_rate': 3e-05, 'lora_r': 16, 'lora_alpha': 32, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-02 21:55:40 | INFO     | root | Logging to /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_003_lr3e-5_r16_a32_ep3/training_run.log
2026-04-02 21:55:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:55:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:40 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-02 21:55:41 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-02 21:55:41 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-02 21:55:42 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct "HTTP/1.1 200 OK"
2026-04-02 21:55:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:42 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:55:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 6670.84it/s]
2026-04-02 21:55:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:43 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.1,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2026-04-02 21:55:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-0.5B-Instruct.
2026-04-02 21:55:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:55:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-02 21:55:44 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:55:46 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:55:46 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-02 21:55:48 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-02 21:55:48 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-02 21:55:50 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 2,162,688

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.4261 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.5759 | lr=2.14e-07 | epoch=0.0043
[train] step=3 | loss=1.5480 | lr=4.29e-07 | epoch=0.0064
[train] step=4 | loss=1.5191 | lr=6.43e-07 | epoch=0.0086
[train] step=5 | loss=1.4363 | lr=8.57e-07 | epoch=0.0107
[train] step=6 | loss=1.4335 | lr=1.07e-06 | epoch=0.0128
[train] step=7 | loss=1.4321 | lr=1.29e-06 | epoch=0.0150
[train] step=8 | loss=1.3693 | lr=1.50e-06 | epoch=0.0171
[train] step=9 | loss=1.4888 | lr=1.71e-06 | epoch=0.0193
[train] step=10 | loss=1.5313 | lr=1.93e-06 | epoch=0.0214
[train] step=11 | loss=1.5055 | lr=2.14e-06 | epoch=0.0235
[train] step=12 | loss=1.6989 | lr=2.36e-06 | epoch=0.0257
[train] step=13 | loss=1.4783 | lr=2.57e-06 | epoch=0.0278
[train] step=14 | loss=1.5677 | lr=2.79e-06 | epoch=0.0300
[train] step=15 | loss=1.6327 | lr=3.00e-06 | epoch=0.0321
[train] step=16 | loss=1.5592 | lr=3.21e-06 | epoch=0.0342
[train] step=17 | loss=1.5560 | lr=3.43e-06 | epoch=0.0364
[train] step=18 | loss=1.4789 | lr=3.64e-06 | epoch=0.0385
[train] step=19 | loss=1.4663 | lr=3.86e-06 | epoch=0.0407

2026-04-02 21:56:09 | INFO     | qwen_math_flow.lora_finetune | LossConvergenceCallback: loss converged (improvement=-0.1526 < min_delta=0.0050) over last 20 log events — stopping early at step 20.

[train] step=20 | loss=1.5786 | lr=4.07e-06 | epoch=0.0428

Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=20 | epoch=0.0428
[train] finished | global_step=20

Saving model checkpoint to output/fine_tune/run_003_lr3e-5_r16_a32_ep3
2026-04-02 21:56:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-02 21:56:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:09 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_003_lr3e-5_r16_a32_ep3/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_003_lr3e-5_r16_a32_ep3/tokenizer_config.json
chat template saved in output/fine_tune/run_003_lr3e-5_r16_a32_ep3/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_003_lr3e-5_r16_a32_ep3/tokenizer_config.json
2026-04-02 21:56:10 | INFO     | root | Done run 4/5: /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_003_lr3e-5_r16_a32_ep3

=== Run 5/5  run_004_lr3e-5_r32_a64_ep3  merged={'learning_rate': 3e-05, 'lora_r': 32, 'lora_alpha': 64, 'num_epochs': 3, 'per_device_train_batch_size': 4, 'gradient_accumulation_steps': 4, 'max_length': 512, 'max_train_samples': None} ===

2026-04-02 21:56:10 | INFO     | root | Logging to /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_004_lr3e-5_r32_a64_ep3/training_run.log
2026-04-02 21:56:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:56:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:10 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-02 21:56:11 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-02 21:56:11 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-02 21:56:12 | INFO     | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct "HTTP/1.1 200 OK"
2026-04-02 21:56:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

2026-04-02 21:56:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading weights file model.safetensors from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 6878.67it/s]
2026-04-02 21:56:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:12 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
loading configuration file generation_config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.1,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2026-04-02 21:56:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-0.5B-Instruct.
2026-04-02 21:56:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/openai/gsm8k/740312add88f781978c0658806c59bc2815b9866/README.md "HTTP/1.1 200 OK"
2026-04-02 21:56:13 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:56:14 | INFO     | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/openai/gsm8k/openai/gsm8k.py "HTTP/1.1 404 Not Found"
2026-04-02 21:56:14 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-02 21:56:15 | INFO     | httpx | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=openai/gsm8k "HTTP/1.1 200 OK"
2026-04-02 21:56:15 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/datasets/openai/gsm8k/resolve/740312add88f781978c0658806c59bc2815b9866/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-02 21:56:17 | INFO     | root | GSM8K training: 7473 samples (full train split), 3 epoch(s).
PyTorch: setting up devices
***** Running training *****
  Num examples = 7,473
  Num Epochs = 3
  Num update steps per epoch = 468
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 4
  Total optimization steps = 1,404
  Number of trainable parameters = 4,325,376

[train] started | epochs=3 | log every 1 step(s) | progress bar + metrics lines below

[train] step=1 | loss=1.4261 | lr=0.00e+00 | epoch=0.0021
[train] step=2 | loss=1.5759 | lr=2.14e-07 | epoch=0.0043
[train] step=3 | loss=1.5467 | lr=4.29e-07 | epoch=0.0064
[train] step=4 | loss=1.5181 | lr=6.43e-07 | epoch=0.0086
[train] step=5 | loss=1.4372 | lr=8.57e-07 | epoch=0.0107
[train] step=6 | loss=1.4339 | lr=1.07e-06 | epoch=0.0128
[train] step=7 | loss=1.4295 | lr=1.29e-06 | epoch=0.0150
[train] step=8 | loss=1.3683 | lr=1.50e-06 | epoch=0.0171
[train] step=9 | loss=1.4856 | lr=1.71e-06 | epoch=0.0193
[train] step=10 | loss=1.5262 | lr=1.93e-06 | epoch=0.0214
[train] step=11 | loss=1.5020 | lr=2.14e-06 | epoch=0.0235
[train] step=12 | loss=1.6888 | lr=2.36e-06 | epoch=0.0257
[train] step=13 | loss=1.4626 | lr=2.57e-06 | epoch=0.0278
[train] step=14 | loss=1.5505 | lr=2.79e-06 | epoch=0.0300
[train] step=15 | loss=1.6108 | lr=3.00e-06 | epoch=0.0321
[train] step=16 | loss=1.5322 | lr=3.21e-06 | epoch=0.0342
[train] step=17 | loss=1.5261 | lr=3.43e-06 | epoch=0.0364
[train] step=18 | loss=1.4395 | lr=3.64e-06 | epoch=0.0385
[train] step=19 | loss=1.4237 | lr=3.86e-06 | epoch=0.0407

2026-04-02 21:56:36 | INFO     | qwen_math_flow.lora_finetune | LossConvergenceCallback: loss converged (improvement=-0.1042 < min_delta=0.0050) over last 20 log events — stopping early at step 20.

[train] step=20 | loss=1.5303 | lr=4.07e-06 | epoch=0.0428

Training completed. Do not forget to share your model on huggingface.co/models =)

[train] step=20 | epoch=0.0428
[train] finished | global_step=20

Saving model checkpoint to output/fine_tune/run_004_lr3e-5_r32_a64_ep3
2026-04-02 21:56:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-04-02 21:56:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-02 21:56:36 | INFO     | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
loading configuration file config.json from cache at /common/home/users/c/chinyee.lew.2022/.cache/huggingface/hub/models--Qwen--Qwen2.5-0.5B-Instruct/snapshots/7ae557604adf67be50417f59c2c2f167def9a775/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

Saving Trainer.data_collator.tokenizer by default as Trainer.processing_class is `None`
chat template saved in output/fine_tune/run_004_lr3e-5_r32_a64_ep3/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_004_lr3e-5_r32_a64_ep3/tokenizer_config.json
chat template saved in output/fine_tune/run_004_lr3e-5_r32_a64_ep3/chat_template.jinja
tokenizer config file saved in output/fine_tune/run_004_lr3e-5_r32_a64_ep3/tokenizer_config.json
2026-04-02 21:56:36 | INFO     | root | Done run 5/5: /common/home/users/c/chinyee.lew.2022/output/fine_tune/run_004_lr3e-5_r32_a64_ep3

Wrote sweep index: /common/home/users/c/chinyee.lew.2022/output/fine_tune/sweep_index.json
Finished 5 run(s). Artifacts under each run folder in:
  /common/home/users/c/chinyee.lew.2022/output/fine_tune